import json
from pathlib import Path
from pykakasi import kakasi

TARGETS = {
    "daily life": 120,
    "travel": 100,
    "common verbs": 100,
    "numbers": 100,
}

CANDIDATES = {
    "daily life": [
        ("玄関", "げんかん", "entrance hall", "玄关"),
        ("廊下", "ろうか", "hallway", "走廊"),
        ("天井", "てんじょう", "ceiling", "天花板"),
        ("床", "ゆか", "floor", "地板"),
        ("壁", "かべ", "wall", "墙"),
        ("窓", "まど", "window", "窗户"),
        ("カーテン", "かーてん", "curtain", "窗帘"),
        ("冷蔵庫", "れいぞうこ", "refrigerator", "冰箱"),
        ("冷凍庫", "れいとうこ", "freezer", "冷冻柜"),
        ("洗濯機", "せんたくき", "washing machine", "洗衣机"),
        ("電子レンジ", "でんしれんじ", "microwave", "微波炉"),
        ("炊飯器", "すいはんき", "rice cooker", "电饭锅"),
        ("掃除機", "そうじき", "vacuum cleaner", "吸尘器"),
        ("扇風機", "せんぷうき", "electric fan", "电风扇"),
        ("暖房", "だんぼう", "heating", "暖气"),
        ("冷房", "れいぼう", "air conditioning", "冷气"),
        ("歯ブラシ", "はぶらし", "toothbrush", "牙刷"),
        ("歯磨き", "はみがき", "tooth brushing", "刷牙"),
        ("石けん", "せっけん", "soap", "肥皂"),
        ("シャンプー", "しゃんぷー", "shampoo", "洗发水"),
        ("タオル", "たおる", "towel", "毛巾"),
        ("枕", "まくら", "pillow", "枕头"),
        ("布団", "ふとん", "futon", "被褥"),
        ("毛布", "もうふ", "blanket", "毛毯"),
        ("目覚まし", "めざまし", "alarm clock", "闹钟"),
        ("財布", "さいふ", "wallet", "钱包"),
        ("鍵", "かぎ", "key", "钥匙"),
        ("傘", "かさ", "umbrella", "雨伞"),
        ("充電器", "じゅうでんき", "charger", "充电器"),
        ("ごみ箱", "ごみばこ", "trash can", "垃圾桶"),
        ("郵便", "ゆうびん", "mail", "邮寄"),
        ("宅配", "たくはい", "home delivery", "宅配"),
        ("家賃", "やちん", "rent", "房租"),
        ("近所", "きんじょ", "neighborhood", "附近"),
        ("洗濯", "せんたく", "laundry", "洗衣"),
        ("掃除", "そうじ", "cleaning", "打扫"),
        ("料理", "りょうり", "cooking", "做饭"),
        ("買い物", "かいもの", "shopping", "购物"),
        ("散歩", "さんぽ", "walk", "散步"),
        ("睡眠", "すいみん", "sleep", "睡眠"),
        ("昼寝", "ひるね", "nap", "午睡"),
        ("日用品", "にちようひん", "daily necessities", "日用品"),
        ("薬", "くすり", "medicine", "药"),
        ("病院", "びょういん", "hospital", "医院"),
        ("歯医者", "はいしゃ", "dentist", "牙医"),
        ("美容院", "びよういん", "hair salon", "美容院"),
        ("銀行", "ぎんこう", "bank", "银行"),
        ("郵便局", "ゆうびんきょく", "post office", "邮局"),
        ("コンビニ", "こんびに", "convenience store", "便利店"),
        ("スーパー", "すーぱー", "supermarket", "超市"),
        ("洗面所", "せんめんじょ", "washroom", "洗漱间"),
        ("台所", "だいどころ", "kitchen", "厨房"),
        ("風呂", "ふろ", "bath", "浴室"),
        ("シャワー", "しゃわー", "shower", "淋浴"),
        ("トイレ", "といれ", "toilet", "厕所"),
        ("寝室", "しんしつ", "bedroom", "卧室"),
        ("居間", "いま", "living room", "起居室"),
        ("ベランダ", "べらんだ", "balcony", "阳台"),
        ("階段", "かいだん", "stairs", "楼梯"),
        ("エレベーター", "えれべーたー", "elevator", "电梯"),
    ],
    "travel": [
        ("空港", "くうこう", "airport", "机场"),
        ("駅", "えき", "station", "车站"),
        ("電車", "でんしゃ", "train", "电车"),
        ("地下鉄", "ちかてつ", "subway", "地铁"),
        ("バス", "ばす", "bus", "公交车"),
        ("タクシー", "たくしー", "taxi", "出租车"),
        ("飛行機", "ひこうき", "airplane", "飞机"),
        ("船", "ふね", "ship", "船"),
        ("フェリー", "ふぇりー", "ferry", "渡轮"),
        ("新幹線", "しんかんせん", "bullet train", "新干线"),
        ("ホテル", "ほてる", "hotel", "酒店"),
        ("旅館", "りょかん", "Japanese inn", "日式旅馆"),
        ("宿", "やど", "lodging", "住处"),
        ("部屋", "へや", "room", "房间"),
        ("予約", "よやく", "reservation", "预订"),
        ("切符", "きっぷ", "ticket", "车票"),
        ("乗車券", "じょうしゃけん", "passenger ticket", "乘车票"),
        ("航空券", "こうくうけん", "airline ticket", "机票"),
        ("パスポート", "ぱすぽーと", "passport", "护照"),
        ("ビザ", "びざ", "visa", "签证"),
        ("荷物", "にもつ", "luggage", "行李"),
        ("手荷物", "てにもつ", "carry-on baggage", "随身行李"),
        ("スーツケース", "すーつけーす", "suitcase", "行李箱"),
        ("リュック", "りゅっく", "backpack", "背包"),
        ("地図", "ちず", "map", "地图"),
        ("道", "みち", "road", "道路"),
        ("入口", "いりぐち", "entrance", "入口"),
        ("出口", "でぐち", "exit", "出口"),
        ("改札", "かいさつ", "ticket gate", "检票口"),
        ("ホーム", "ほーむ", "platform", "站台"),
        ("番線", "ばんせん", "platform number", "站台编号"),
        ("時刻表", "じこくひょう", "timetable", "时刻表"),
        ("案内所", "あんないじょ", "information desk", "问讯处"),
        ("観光", "かんこう", "sightseeing", "观光"),
        ("旅行", "りょこう", "travel", "旅行"),
        ("出発", "しゅっぱつ", "departure", "出发"),
        ("到着", "とうちゃく", "arrival", "到达"),
        ("乗り換え", "のりかえ", "transfer", "换乘"),
        ("遅延", "ちえん", "delay", "延误"),
        ("欠航", "けっこう", "flight cancellation", "航班取消"),
        ("搭乗口", "とうじょうぐち", "boarding gate", "登机口"),
        ("座席", "ざせき", "seat", "座位"),
        ("窓側", "まどがわ", "window side", "靠窗"),
        ("通路側", "つうろがわ", "aisle side", "靠过道"),
        ("片道", "かたみち", "one way", "单程"),
        ("往復", "おうふく", "round trip", "往返"),
        ("目的地", "もくてきち", "destination", "目的地"),
        ("出発地", "しゅっぱつち", "origin", "出发地"),
        ("住所", "じゅうしょ", "address", "地址"),
        ("料金", "りょうきん", "fee", "费用"),
        ("運賃", "うんちん", "fare", "票价"),
        ("現金", "げんきん", "cash", "现金"),
        ("両替", "りょうがえ", "currency exchange", "换汇"),
        ("海外", "かいがい", "overseas", "海外"),
        ("国内", "こくない", "domestic", "国内"),
        ("入国", "にゅうこく", "entry into a country", "入境"),
        ("出国", "しゅっこく", "departure from a country", "出境"),
        ("税関", "ぜいかん", "customs", "海关"),
        ("検疫", "けんえき", "quarantine", "检疫"),
        ("宿泊", "しゅくはく", "lodging", "住宿"),
        ("民宿", "みんしゅく", "guesthouse", "民宿"),
        ("温泉", "おんせん", "hot spring", "温泉"),
        ("お土産", "おみやげ", "souvenir", "伴手礼"),
        ("写真", "しゃしん", "photo", "照片"),
        ("景色", "けしき", "scenery", "景色"),
        ("海", "うみ", "sea", "海"),
        ("山", "やま", "mountain", "山"),
        ("島", "しま", "island", "岛"),
        ("町", "まち", "town", "城镇"),
        ("都市", "とし", "city", "城市"),
        ("村", "むら", "village", "村庄"),
        ("橋", "はし", "bridge", "桥"),
        ("道路", "どうろ", "roadway", "公路"),
        ("交差点", "こうさてん", "intersection", "十字路口"),
        ("信号", "しんごう", "traffic light", "红绿灯"),
        ("駐車場", "ちゅうしゃじょう", "parking lot", "停车场"),
        ("ガソリンスタンド", "がそりんすたんど", "gas station", "加油站"),
        ("レンタカー", "れんたかー", "rental car", "租车"),
        ("免許証", "めんきょしょう", "driver's license", "驾照"),
        ("観光地", "かんこうち", "tourist destination", "旅游地"),
        ("名所", "めいしょ", "famous sight", "名胜"),
        ("案内", "あんない", "guidance", "指引"),
        ("便", "びん", "flight or service", "班次"),
        ("航空会社", "こうくうがいしゃ", "airline", "航空公司"),
        ("乗客", "じょうきゃく", "passenger", "乘客"),
        ("乗員", "じょういん", "crew member", "机组人员"),
        ("機内", "きない", "on board", "机内"),
        ("港", "みなと", "port", "港口"),
        ("線路", "せんろ", "railway track", "铁路"),
        ("停留所", "ていりゅうじょ", "bus stop", "公交站"),
        ("終点", "しゅうてん", "last stop", "终点站"),
        ("始発", "しはつ", "first train", "首班车"),
        ("終電", "しゅうでん", "last train", "末班车"),
        ("乗り場", "のりば", "boarding point", "乘车处"),
        ("降り場", "おりば", "drop-off point", "下车处"),
        ("渋滞", "じゅうたい", "traffic jam", "堵车"),
        ("国境", "こっきょう", "border", "国境"),
        ("旅費", "りょひ", "travel expenses", "旅费"),
        ("日帰り", "ひがえり", "day trip", "当天往返"),
        ("滞在", "たいざい", "stay", "停留"),
        ("観光客", "かんこうきゃく", "tourist", "游客"),
        ("荷札", "にふだ", "baggage tag", "行李牌"),
        ("搭乗券", "とうじょうけん", "boarding pass", "登机牌"),
        ("搭乗", "とうじょう", "boarding", "登机"),
        ("到着口", "とうちゃくぐち", "arrivals exit", "到达出口"),
        ("乗り継ぎ", "のりつぎ", "connection", "转机"),
        ("直行便", "ちょっこうびん", "direct flight", "直飞航班"),
        ("経由", "けいゆ", "via", "经由"),
        ("空席", "くうせき", "vacant seat", "空座"),
        ("満席", "まんせき", "full seating", "满座"),
        ("指定席", "していせき", "reserved seat", "指定席"),
        ("自由席", "じゆうせき", "unreserved seat", "自由席"),
        ("車両", "しゃりょう", "rail car", "车厢"),
        ("車内", "しゃない", "inside a vehicle", "车内"),
        ("駅員", "えきいん", "station staff", "车站工作人员"),
        ("運転手", "うんてんしゅ", "driver", "司机"),
        ("案内板", "あんないばん", "information board", "指示牌"),
        ("標識", "ひょうしき", "sign", "标志"),
        ("歩道", "ほどう", "sidewalk", "人行道"),
        ("横断歩道", "おうだんほどう", "crosswalk", "人行横道"),
        ("旅程", "りょてい", "itinerary", "行程"),
    ],
    "common verbs": [
        ("会う", "あう", "meet", "见面"),
        ("開く", "あく", "open", "打开"),
        ("開ける", "あける", "open something", "打开"),
        ("閉まる", "しまる", "close", "关上"),
        ("閉める", "しめる", "close something", "关闭"),
        ("始まる", "はじまる", "begin", "开始"),
        ("始める", "はじめる", "start something", "开始"),
        ("終わる", "おわる", "finish", "结束"),
        ("待つ", "まつ", "wait", "等待"),
        ("急ぐ", "いそぐ", "hurry", "赶快"),
        ("選ぶ", "えらぶ", "choose", "选择"),
        ("決める", "きめる", "decide", "决定"),
        ("忘れる", "わすれる", "forget", "忘记"),
        ("覚える", "おぼえる", "remember", "记住"),
        ("持つ", "もつ", "hold", "拿着"),
        ("置く", "おく", "put", "放置"),
        ("取る", "とる", "take", "拿取"),
        ("使う", "つかう", "use", "使用"),
        ("作る", "つくる", "make", "制作"),
        ("売る", "うる", "sell", "卖"),
        ("買う", "かう", "buy", "买"),
        ("借りる", "かりる", "borrow", "借入"),
        ("貸す", "かす", "lend", "借出"),
        ("返す", "かえす", "return", "归还"),
        ("呼ぶ", "よぶ", "call", "叫；称呼"),
        ("止まる", "とまる", "stop", "停下"),
        ("止める", "とめる", "stop something", "停止"),
        ("曲がる", "まがる", "turn", "转弯"),
        ("渡る", "わたる", "cross", "横过"),
        ("乗る", "のる", "ride", "乘坐"),
        ("降りる", "おりる", "get off", "下车"),
        ("着く", "つく", "arrive", "到达"),
        ("出る", "でる", "leave", "出去"),
        ("入る", "はいる", "enter", "进入"),
        ("送る", "おくる", "send", "发送"),
        ("受け取る", "うけとる", "receive", "接收"),
        ("教える", "おしえる", "teach", "教"),
        ("習う", "ならう", "learn", "学习"),
        ("働く", "はたらく", "work", "工作"),
        ("休む", "やすむ", "rest", "休息"),
        ("洗う", "あらう", "wash", "洗"),
        ("着る", "きる", "wear", "穿"),
        ("脱ぐ", "ぬぐ", "take off clothes", "脱衣"),
        ("立つ", "たつ", "stand", "站立"),
        ("座る", "すわる", "sit", "坐"),
        ("歩く", "あるく", "walk", "走路"),
        ("走る", "はしる", "run", "跑"),
        ("泳ぐ", "およぐ", "swim", "游泳"),
        ("遊ぶ", "あそぶ", "play", "玩"),
        ("手伝う", "てつだう", "help", "帮忙"),
        ("探す", "さがす", "look for", "寻找"),
        ("見つける", "みつける", "find", "找到"),
        ("直す", "なおす", "fix", "修理"),
        ("直る", "なおる", "be fixed", "修好"),
        ("押す", "おす", "push", "推"),
        ("引く", "ひく", "pull", "拉"),
        ("消す", "けす", "turn off", "关闭"),
        ("つける", "つける", "turn on", "打开"),
        ("変える", "かえる", "change something", "改变"),
        ("変わる", "かわる", "change", "变化"),
        ("答える", "こたえる", "answer", "回答"),
    ],
    "numbers": [
        ("零", "れい", "zero", "零"),
        ("ゼロ", "ぜろ", "zero", "零"),
        ("一", "いち", "one", "一"),
        ("二", "に", "two", "二"),
        ("三", "さん", "three", "三"),
        ("四", "よん", "four", "四"),
        ("五", "ご", "five", "五"),
        ("六", "ろく", "six", "六"),
        ("七", "なな", "seven", "七"),
        ("八", "はち", "eight", "八"),
        ("九", "きゅう", "nine", "九"),
        ("十", "じゅう", "ten", "十"),
        ("十一", "じゅういち", "eleven", "十一"),
        ("十二", "じゅうに", "twelve", "十二"),
        ("十三", "じゅうさん", "thirteen", "十三"),
        ("十四", "じゅうよん", "fourteen", "十四"),
        ("十五", "じゅうご", "fifteen", "十五"),
        ("十六", "じゅうろく", "sixteen", "十六"),
        ("十七", "じゅうなな", "seventeen", "十七"),
        ("十八", "じゅうはち", "eighteen", "十八"),
        ("十九", "じゅうきゅう", "nineteen", "十九"),
        ("二十", "にじゅう", "twenty", "二十"),
        ("三十", "さんじゅう", "thirty", "三十"),
        ("四十", "よんじゅう", "forty", "四十"),
        ("五十", "ごじゅう", "fifty", "五十"),
        ("六十", "ろくじゅう", "sixty", "六十"),
        ("七十", "ななじゅう", "seventy", "七十"),
        ("八十", "はちじゅう", "eighty", "八十"),
        ("九十", "きゅうじゅう", "ninety", "九十"),
        ("百", "ひゃく", "hundred", "百"),
        ("千", "せん", "thousand", "千"),
        ("万", "まん", "ten thousand", "万"),
        ("億", "おく", "hundred million", "亿"),
        ("一つ", "ひとつ", "one thing", "一个"),
        ("二つ", "ふたつ", "two things", "两个"),
        ("三つ", "みっつ", "three things", "三个"),
        ("四つ", "よっつ", "four things", "四个"),
        ("五つ", "いつつ", "five things", "五个"),
        ("六つ", "むっつ", "six things", "六个"),
        ("七つ", "ななつ", "seven things", "七个"),
        ("八つ", "やっつ", "eight things", "八个"),
        ("九つ", "ここのつ", "nine things", "九个"),
        ("一人", "ひとり", "one person", "一个人"),
        ("二人", "ふたり", "two people", "两个人"),
        ("三人", "さんにん", "three people", "三个人"),
        ("四人", "よにん", "four people", "四个人"),
        ("五人", "ごにん", "five people", "五个人"),
        ("十人", "じゅうにん", "ten people", "十个人"),
        ("何人", "なんにん", "how many people", "几个人"),
        ("個", "こ", "piece counter", "个"),
        ("枚", "まい", "flat-object counter", "张；片"),
        ("冊", "さつ", "book counter", "册"),
        ("台", "だい", "machine counter", "台"),
        ("匹", "ひき", "small-animal counter", "只"),
        ("羽", "わ", "bird counter", "只（鸟）"),
        ("杯", "はい", "cup counter", "杯"),
        ("回", "かい", "times counter", "次"),
        ("階", "かい", "floor counter", "层"),
        ("歳", "さい", "years old", "岁"),
        ("番", "ばん", "number or order", "号；顺序"),
        ("時", "じ", "hour", "点钟"),
        ("分", "ふん", "minute", "分钟"),
        ("秒", "びょう", "second", "秒"),
        ("日", "にち", "day", "日"),
        ("週", "しゅう", "week", "周"),
        ("年", "ねん", "year", "年"),
        ("円", "えん", "yen", "日元"),
        ("キロ", "きろ", "kilo", "千克；公里"),
        ("メートル", "めーとる", "meter", "米"),
        ("センチ", "せんち", "centimeter", "厘米"),
        ("グラム", "ぐらむ", "gram", "克"),
        ("キログラム", "きろぐらむ", "kilogram", "千克"),
        ("リットル", "りっとる", "liter", "升"),
        ("パーセント", "ぱーせんと", "percent", "百分比"),
        ("半", "はん", "half", "半"),
        ("半分", "はんぶん", "half", "一半"),
        ("倍", "ばい", "times or multiple", "倍"),
        ("全部", "ぜんぶ", "all", "全部"),
        ("少し", "すこし", "a little", "一点"),
        ("たくさん", "たくさん", "many", "很多"),
        ("いくつ", "いくつ", "how many", "几个"),
        ("いくら", "いくら", "how much", "多少钱"),
        ("何", "なん", "what number", "多少；什么"),
        ("何個", "なんこ", "how many pieces", "几个"),
        ("何枚", "なんまい", "how many flat items", "几张"),
        ("何冊", "なんさつ", "how many books", "几册"),
        ("何台", "なんだい", "how many machines", "几台"),
        ("何匹", "なんびき", "how many small animals", "几只"),
        ("何回", "なんかい", "how many times", "几次"),
        ("何階", "なんがい", "which floor", "几楼"),
        ("何歳", "なんさい", "how old", "几岁"),
        ("何番", "なんばん", "what number", "几号"),
        ("何時", "なんじ", "what time", "几点"),
        ("何分", "なんぷん", "how many minutes", "几分钟"),
        ("何秒", "なんびょう", "how many seconds", "几秒"),
        ("何日", "なんにち", "how many days", "几天"),
        ("何週間", "なんしゅうかん", "how many weeks", "几周"),
        ("何か月", "なんかげつ", "how many months", "几个月"),
        ("何年", "なんねん", "how many years", "几年"),
        ("午前", "ごぜん", "a.m.", "上午"),
        ("午後", "ごご", "p.m.", "下午"),
        ("正午", "しょうご", "noon", "正午"),
        ("深夜", "しんや", "late night", "深夜"),
        ("一番", "いちばん", "number one", "第一"),
        ("最初", "さいしょ", "first", "最初"),
        ("最後", "さいご", "last", "最后"),
        ("次", "つぎ", "next", "下一个"),
        ("半額", "はんがく", "half price", "半价"),
        ("合計", "ごうけい", "total", "合计"),
        ("数", "かず", "number", "数量"),
        ("数字", "すうじ", "digit", "数字"),
        ("番号", "ばんごう", "number", "号码"),
        ("順番", "じゅんばん", "order", "顺序"),
        ("回数", "かいすう", "number of times", "次数"),
        ("人数", "にんずう", "number of people", "人数"),
        ("年齢", "ねんれい", "age", "年龄"),
        ("時間", "じかん", "time or hours", "时间"),
        ("期間", "きかん", "period", "期间"),
        ("距離", "きょり", "distance", "距离"),
        ("長さ", "ながさ", "length", "长度"),
        ("高さ", "たかさ", "height", "高度"),
        ("重さ", "おもさ", "weight", "重量"),
        ("幅", "はば", "width", "宽度"),
        ("温度", "おんど", "temperature", "温度"),
        ("時刻", "じこく", "time of day", "时刻"),
        ("時半", "じはん", "half past", "半点"),
        ("一時間", "いちじかん", "one hour", "一小时"),
        ("二時間", "にじかん", "two hours", "两小时"),
        ("一週間", "いっしゅうかん", "one week", "一周"),
        ("二週間", "にしゅうかん", "two weeks", "两周"),
        ("一か月", "いっかげつ", "one month", "一个月"),
        ("二か月", "にかげつ", "two months", "两个月"),
        ("一年", "いちねん", "one year", "一年"),
        ("二年", "にねん", "two years", "两年"),
        ("一日", "いちにち", "one day", "一天"),
        ("二日", "ふつか", "two days or the second", "两天；二号"),
        ("三日", "みっか", "three days or the third", "三天；三号"),
        ("四日", "よっか", "four days or the fourth", "四天；四号"),
        ("五日", "いつか", "five days or the fifth", "五天；五号"),
        ("六日", "むいか", "six days or the sixth", "六天；六号"),
        ("七日", "なのか", "seven days or the seventh", "七天；七号"),
        ("八日", "ようか", "eight days or the eighth", "八天；八号"),
        ("九日", "ここのか", "nine days or the ninth", "九天；九号"),
        ("十日", "とおか", "ten days or the tenth", "十天；十号"),
        ("二十日", "はつか", "twenty days or the twentieth", "二十天；二十号"),
        ("一月", "いちがつ", "January", "一月"),
        ("二月", "にがつ", "February", "二月"),
        ("三月", "さんがつ", "March", "三月"),
        ("四月", "しがつ", "April", "四月"),
        ("五月", "ごがつ", "May", "五月"),
        ("六月", "ろくがつ", "June", "六月"),
        ("七月", "しちがつ", "July", "七月"),
        ("八月", "はちがつ", "August", "八月"),
        ("九月", "くがつ", "September", "九月"),
        ("十月", "じゅうがつ", "October", "十月"),
        ("十一月", "じゅういちがつ", "November", "十一月"),
        ("十二月", "じゅうにがつ", "December", "十二月"),
        ("月曜日", "げつようび", "Monday", "星期一"),
        ("火曜日", "かようび", "Tuesday", "星期二"),
        ("水曜日", "すいようび", "Wednesday", "星期三"),
        ("木曜日", "もくようび", "Thursday", "星期四"),
        ("金曜日", "きんようび", "Friday", "星期五"),
        ("土曜日", "どようび", "Saturday", "星期六"),
        ("日曜日", "にちようび", "Sunday", "星期日"),
    ],
}

runtime = json.loads(Path('/tmp/ja-basic-runtime.json').read_text())
jlpt_map = json.loads(Path('/tmp/jlpt-map.json').read_text())
existing = set(runtime['existing'])
counts = runtime['counts']
converter = kakasi()


def romanize(reading: str) -> str:
    return ''.join(piece['hepburn'] for piece in converter.convert(reading))


def examples(topic: str, word: str):
    if topic == 'daily life':
        return (
            f'「{word}」は日常生活でよく使う言葉です。',
            f'“{word}” is a common word in daily life.',
            f'“{word}”是日常生活中常用的词。',
        )
    if topic == 'travel':
        return (
            f'旅行では「{word}」という言葉をよく使います。',
            f'“{word}” is a useful word when traveling.',
            f'旅行时经常会用到“{word}”这个词。',
        )
    if topic == 'common verbs':
        return (
            f'「{word}」は日常会話でよく使う動詞です。',
            f'“{word}” is a common verb in everyday conversation.',
            f'“{word}”是日常会话中常用的动词。',
        )
    return (
        f'「{word}」は数・量・時間を表すときに使います。',
        f'“{word}” is used when expressing numbers, quantity, or time.',
        f'“{word}”可用于表示数字、数量或时间。',
    )

selected = []
for topic, target in TARGETS.items():
    need = max(0, target - int(counts.get(topic, 0)))
    chosen = []
    for word, reading, en, zh in CANDIDATES[topic]:
        if word in existing:
            continue
        mapped = jlpt_map.get(word)
        if mapped not in (None, 'N5', 'N4'):
            continue
        if any(row['targetText'] == word for row in selected):
            continue
        ja_example, en_example, zh_example = examples(topic, word)
        chosen.append({
            'id': f"ja-basic-topicfill-{topic.replace(' ', '-')}-{len(chosen)+1:03d}",
            'targetLanguage': 'Japanese',
            'targetText': word,
            'meanings': {'English': en, 'Simplified Chinese': zh},
            'reading': reading,
            'romanization': romanize(reading),
            'level': 'Basic',
            'topic': topic,
            'exampleSentence': ja_example,
            'exampleTranslations': {'English': en_example, 'Simplified Chinese': zh_example},
        })
        existing.add(word)
        if len(chosen) == need:
            break
    if len(chosen) != need:
        raise SystemExit(f'{topic}: need {need} fresh Basic entries, only found {len(chosen)}')
    selected.extend(chosen)
    print(f'{topic}: {counts.get(topic,0)} + {len(chosen)} = {target}')

header = '''import type { VocabItem } from "./vocabulary";\n\n// Targeted Japanese Basic fill for practical topic buckets.\n// Standalone high-frequency headwords only; generated after runtime de-duplication.\nexport const japaneseBasicTopicFill: VocabItem[] = '''
Path('src/vocabulary-basic-topic-fill-ja.ts').write_text(
    header + json.dumps(selected, ensure_ascii=False, indent=2) + ';\n'
)
print(f'Generated {len(selected)} new Japanese Basic entries.')
