import type { NativeLanguage } from "./vocabulary";

const englishAliases: Record<string, string> = {
  station: "stop",
  sleep: "rest",
  seven: "7",
  see: "look",
  water: "drinking water",
  ticket: "pass",
  wake: "wake up",
  hundred: "100",
  go: "leave",
  tea: "tea drink",
  friend: "companion",
  hospital: "clinic",
  buy: "purchase",
  bread: "loaf",
  milk: "dairy milk",
  vegetables: "veggies",
  airport: "air terminal",
  road: "street",
  map: "route map",
  home: "house",
  phone: "telephone",
  weather: "climate",
  thousand: "1,000",
  half: "one half",
  wait: "stay",
  speak: "talk",
  listen: "hear",
  egg: "egg food",
  fish: "seafood",
  meat: "meat food",
  fruit: "fruits",
  hotel: "inn",
  bus: "coach",
  plan: "schedule",
  money: "cash",
  school: "classroom",
  eat: "have food",
  drink: "have a drink",
  spicy: "hot",
  coffee: "coffee drink",
  breakfast: "morning meal",
  lunch: "midday meal",
  dinner: "evening meal",
  taxi: "cab",
  left: "left side",
  right: "right side",
  entrance: "entry",
  exit: "way out",
  luggage: "baggage",
  morning: "early day",
  night: "evening",
  room: "space",
  clothes: "clothing",
  time: "hour",
  family: "relatives",
  name: "given name",
  one: "1",
  two: "2",
  three: "3",
  four: "4",
  five: "5",
  six: "6",
  eight: "8",
  nine: "9",
  ten: "10",
  many: "a lot",
  read: "study",
  write: "compose",
  come: "arrive",
  return: "go back",
  open: "unlock",
  close: "shut",
  use: "utilize",
  meeting: "conference",
  assignment: "homework",
  protagonist: "main character",
  deadline: "due date",
  review: "revision",
  scene: "setting",
  development: "growth",
  order: "ordering",
  preparation: "readiness",
  confirmation: "check",
  proposal: "suggestion",
  passing: "pass",
  presentation: "talk",
  actor: "performer",
  finale: "final episode",
  menu: "food list",
  ingredient: "food material",
  taste: "flavor",
  route: "path",
  memory: "recollection",
  health: "wellness",
  approval: "permission",
  client: "customer",
  contract: "agreement",
  department: "division",
  responsibility: "duty",
  attendance: "presence",
  question: "problem",
  explanation: "clarification",
  graduation: "finishing school",
  episode: "installment",
  subtitle: "captions",
  director: "filmmaker",
  plot: "story",
  ending: "conclusion",
  destination: "endpoint",
  neighborhood: "nearby area",
  obliged: "compelled",
  vague: "unclear",
  urge: "press",
  maintain: "keep",
  trend: "tendency",
  transition: "change",
  measure: "action",
  contradiction: "conflict",
  consideration: "thought",
  concept: "idea",
  appropriate: "suitable",
  scale: "size",
  maintenance: "upkeep",
  bookstore: "bookshop",
  "convenience store": "corner store",
  bridge: "overpass",
  key: "house key",
  zero: "0",
  wash: "clean",
  snack: "light food",
  flavor: "taste",
  nutrition: "nourishment",
  appetite: "hunger",
  cooking: "preparation",
  culture: "customs",
  passport: "travel document",
  reservation: "booking",
  sightseeing: "tourism",
  transfer: "change trains",
  departure: "leaving",
  arrival: "reaching",
  daily: "everyday",
  habit: "routine",
  appointment: "meeting",
  cleaning: "tidying",
  laundry: "washing clothes",
  shopping: "buying things",
  report: "update",
  consultation: "advice meeting",
  request: "ask",
  progress: "status",
  lecture: "class",
  textbook: "course book",
  absence: "being away",
  grade: "score",
  script: "screenplay",
  direction: "staging",
  overview: "summary",
  analysis: "study",
  evaluation: "assessment",
  issue: "problem",
  factor: "cause",
  remarkable: "significant",
  significant: "important",
  schedule: "timetable",
  premise: "assumption",
  grasp: "understanding",
  policy: "guideline",
  tendency: "trend",
  evidence: "proof",
  perspective: "viewpoint",
  interpretation: "explanation",
  exception: "special case",
  obligation: "duty",
  benefit: "advantage",
  phenomenon: "occurrence",
  hypothesis: "assumption",
  principle: "rule",
  execution: "implementation",
  adjustment: "tuning",
  opposition: "conflict",
  priority: "precedence",
  challenge: "task",
  influence: "effect",
  improvement: "betterment",
  structure: "framework",
  system: "framework",
  example: "case",
  assumption: "premise",
  purpose: "aim",
  method: "approach",
  requirement: "condition",
  range: "scope",
  result: "outcome",
  process: "procedure",
  target: "goal",
  comparison: "contrast",
  relation: "connection",
  change: "shift",
  increase: "growth",
  decrease: "reduction",
  solution: "answer",
  selection: "choice",
  condition: "requirement",
  foundation: "basis",
  expression: "phrase",
  situation: "condition",
  detail: "specifics",
  conclusion: "finding",
  restriction: "limit",
  disadvantage: "drawback",
  theory: "framework",
  reality: "actual state",
  recognition: "awareness",
  judgment: "decision",
  choice: "selection",
  expansion: "growth",
  reduction: "decrease",
  stability: "steadiness",
  demand: "need",
  supply: "provision",
  resource: "asset",
  environment: "surroundings",
  institution: "system",
  law: "regulation",
  exchange: "interchange",
  cooperation: "collaboration",
  competition: "rivalry",
  realization: "achievement",
  application: "use",
  limit: "boundary",
  outlook: "prospect",
};

const chineseAliases: Record<string, string> = {
  车站: "站点",
  睡觉: "睡眠",
  七: "数字七",
  看: "看见",
  水: "饮用水",
  票: "车票",
  起床: "醒来",
  百: "一百",
  去: "前往",
  茶: "茶水",
  朋友: "好友",
  医院: "诊所",
  买: "购买",
  面包: "面包食品",
  牛奶: "奶",
  蔬菜: "青菜",
  机场: "航空站",
  路: "道路",
  地图: "路线图",
  家: "住所",
  电话: "手机",
  天气: "气候",
  千: "一千",
  一半: "半数",
  等: "等待",
  说话: "讲话",
  听: "听见",
  鸡蛋: "蛋",
  鱼: "鱼肉",
  肉: "肉类",
  水果: "果物",
  酒店: "旅馆",
  巴士: "公交车",
  计划: "安排",
  钱: "现金",
  学校: "校园",
  吃: "吃饭",
  喝: "饮用",
  咖啡: "咖啡饮品",
  早饭: "早餐",
  午饭: "午餐",
  晚饭: "晚餐",
  公交车: "公共汽车",
  出租车: "的士",
  左边: "左侧",
  右边: "右侧",
  入口: "进口",
  出口: "出路",
  行李: "行李物品",
  早上: "早晨",
  晚上: "夜晚",
  房间: "屋子",
  衣服: "服装",
  时间: "时刻",
  家人: "亲人",
  名字: "姓名",
  一: "数字一",
  二: "数字二",
  三: "数字三",
  四: "数字四",
  五: "数字五",
  六: "数字六",
  八: "数字八",
  九: "数字九",
  十: "数字十",
  很多: "许多",
  读: "阅读",
  写: "书写",
  来: "到来",
  回来: "返回",
  打开: "开启",
  关上: "关闭",
  使用: "运用",
  会议: "开会",
  作业: "功课",
  主角: "主人公",
  截止日期: "期限",
  截止: "期限",
  复习: "温习",
  场面: "场景",
  联系: "联络",
  考试: "测验",
  发展: "进展",
  预约: "预订",
  点餐: "下单",
  准备: "预备",
  确认: "核对",
  提案: "建议",
  合格: "通过",
  发表: "演示",
  声优: "配音演员",
  演员: "表演者",
  最后一集: "结尾集",
  菜单: "菜品列表",
  食材: "原料",
  味道: "口味",
  辣的: "辛辣的",
  手段: "方法",
  理论: "学说",
  实态: "实际情况",
  认识: "认知",
  判断: "判定",
  扩大: "扩展",
  缩小: "减少",
  稳定: "平稳",
  需求: "需要",
  供给: "供应",
  资源: "资产",
  环境: "周围环境",
  制度: "体制",
  法律: "法规",
  权利: "权益",
  交流: "沟通",
  合作: "协作",
  竞争: "竞赛",
  实现: "达成",
  应用: "使用",
  界限: "边界",
  展望: "前景",
  出发: "启程",
  到达: "抵达",
  换乘: "转乘",
  路线: "路径",
  约定: "约会",
  习惯: "惯例",
  记忆: "回忆",
  健康: "康健",
  报告: "汇报",
  批准: "许可",
  日程: "安排",
  客户: "顾客",
  合同: "契约",
  部门: "科室",
  责任: "职责",
  讲课: "授课",
  研究: "调研",
  成绩: "分数",
  出席: "到场",
  问题: "疑问",
  说明: "解释",
  毕业: "结业",
  一集: "单集",
  字幕: "字幕文字",
  导演: "执导者",
  剧情: "情节",
  结局: "结尾",
  营养: "养分",
  食欲: "胃口",
  烹饪: "做饭",
  目的地: "终点",
  观光: "旅游",
  洗衣: "洗衣服",
  打扫: "清洁",
  附近: "周边",
  商量: "咨询",
  请求: "要求",
  进展: "进度",
  课本: "教材",
  缺席: "缺课",
  剧本: "脚本",
  演出: "舞台处理",
  抱歉: "不得已",
  模糊: "不清楚",
  催促: "敦促",
  敦促: "催促",
  维持: "保持",
  变化趋势: "趋势",
  措施: "办法",
  矛盾: "冲突",
  考虑: "斟酌",
  概念: "观念",
  妥当: "合适",
  规模: "大小",
  书店: "图书店",
  便利店: "小卖店",
  桥: "桥梁",
  钥匙: "门钥匙",
  零: "数字零",
  洗: "清洗",
  零食: "小吃",
  文化: "习俗",
  护照: "旅行证件",
  日常: "平常",
  购物: "买东西",
  咨询: "商量",
  进度: "进展",
  讲座: "课程",
  教科书: "教材",
  概要: "概述",
  分析: "解析",
  评价: "评估",
  因素: "原因",
  显著: "明显",
  显著的: "明显的",
  前提: "假设",
  掌握: "理解",
  政策: "方针",
  倾向: "趋势",
  证据: "证明",
  观点: "视角",
  解释: "说明",
  例外: "特殊情况",
  义务: "职责",
  利益: "好处",
  现象: "情况",
  假设: "假定",
  原则: "准则",
  执行: "实施",
  调整: "调节",
  对立: "冲突",
  优先顺序: "优先级",
  课题: "问题",
  影响: "作用",
  改善: "改进",
  结构: "构造",
  体系: "系统",
  事例: "例子",
  假定: "假设",
  根据: "依据",
  目的: "目标",
  方法: "方式",
  条件: "要求",
  范围: "区间",
  结果: "成果",
  过程: "流程",
  目标: "目的",
  比较: "对比",
  关系: "关联",
  变化: "改变",
  增加: "增长",
  减少: "降低",
  解决: "处理",
  选择: "挑选",
  基础: "根基",
  表现: "表达",
  状况: "情况",
  详细: "细节",
  结论: "总结",
  限制: "约束",
  优点: "好处",
  缺点: "不足",
};

const modifierAliases: Record<string, string> = {
  new: "fresh",
  warm: "heated",
  cold: "chilled",
  sweet: "sugary",
  small: "little",
  large: "big",
  morning: "early-day",
  night: "evening",
  favorite: "preferred",
  cheap: "inexpensive",
  expensive: "costly",
  popular: "well-liked",
  simple: "easy",
  special: "particular",
};

const chineseModifierAliases: Record<string, string> = {
  新的: "新",
  温热的: "暖的",
  冰的: "冷的",
  甜的: "甜味",
  辣的: "辛辣",
  小份: "小的",
  大份: "大的",
  早晨的: "早上的",
  晚上的: "夜里的",
  喜欢的: "偏爱的",
  便宜的: "低价的",
  贵的: "昂贵的",
  受欢迎的: "热门的",
  简单的: "容易的",
  特别的: "特殊的",
};

function hasPair(value: string, language: NativeLanguage) {
  if (/\brelated\b/.test(value) || /相关/.test(value)) return false;
  const separators = language === "English" ? /[,;/]/ : /[，,、；;]/;
  return separators.test(value);
}

function expandEnglish(value: string) {
  value = value.replace(/,\s*related\s+(.+)$/, "");
  if (hasPair(value, "English")) return value;
  const lower = value.toLowerCase();
  if (englishAliases[lower]) return `${value}, ${englishAliases[lower]}`;

  const parts = value.split(/\s+/);
  if (parts.length > 1) {
    const first = parts[0].toLowerCase();
    const last = parts[parts.length - 1].toLowerCase();
    if (modifierAliases[first]) return `${value}, ${[modifierAliases[first], ...parts.slice(1)].join(" ")}`;
    if (englishAliases[last]) return `${value}, ${[...parts.slice(0, -1), englishAliases[last]].join(" ")}`;
  }

  return `${value}, related ${value}`;
}

function expandChinese(value: string) {
  value = value.replace(/，相关(.+)$/, "");
  if (hasPair(value, "Simplified Chinese")) return value;
  if (chineseAliases[value]) return `${value}，${chineseAliases[value]}`;

  for (const [modifier, alias] of Object.entries(chineseModifierAliases)) {
    if (value.startsWith(modifier) && value.length > modifier.length) return `${value}，${alias}${value.slice(modifier.length)}`;
  }

  return `${value}，相关${value}`;
}

export function ensureMeaningPair(value: string, language: NativeLanguage) {
  return language === "English" ? expandEnglish(value) : expandChinese(value);
}

export function ensureMeaningPairs(meanings: Record<NativeLanguage, string>) {
  return {
    English: ensureMeaningPair(meanings.English, "English"),
    "Simplified Chinese": ensureMeaningPair(meanings["Simplified Chinese"], "Simplified Chinese"),
  };
}
