export type TargetLanguage = "Japanese" | "Korean";
export type NativeLanguage = "English" | "Simplified Chinese" | "Traditional Chinese";
export type Level = "Basic" | "Intermediate" | "Advanced";
export type Topic =
  | "food"
  | "travel"
  | "daily life"
  | "numbers"
  | "common verbs"
  | "work"
  | "school"
  | "anime/drama"
  | "JLPT"
  | "TOPIK";
export type Familiarity = "New" | "Learning" | "Familiar" | "Mastered";
export type VocabItem = {
  id: string;
  targetLanguage: TargetLanguage;
  targetText: string;
  meanings: Record<NativeLanguage, string>;
  reading: string;
  romanization: string;
  level: Level;
  topic: Topic;
  exampleSentence: string;
  exampleTranslations: Record<NativeLanguage, string>;
  status?: Familiarity;
  favorite?: boolean;
  timesPlayed?: number;
  lastPlayed?: string;
};

export const vocabSeed: VocabItem[] = [
  {
    id: "ja-food-basic-1",
    targetLanguage: "Japanese",
    targetText: "ご飯",
    meanings: { English: "meal; cooked rice", "Simplified Chinese": "吃饭", "Traditional Chinese": "吃飯" },
    reading: "ごはん",
    romanization: "gohan",
    level: "Basic",
    topic: "food",
    exampleSentence: "朝ご飯を食べます。",
    exampleTranslations: { English: "I eat breakfast.", "Simplified Chinese": "我吃早饭。", "Traditional Chinese": "我吃早飯。" },
  },
  {
    id: "ja-travel-basic-1",
    targetLanguage: "Japanese",
    targetText: "駅",
    meanings: { English: "station", "Simplified Chinese": "车站", "Traditional Chinese": "車站" },
    reading: "えき",
    romanization: "eki",
    level: "Basic",
    topic: "travel",
    exampleSentence: "駅はどこですか。",
    exampleTranslations: { English: "Where is the station?", "Simplified Chinese": "车站在哪里？", "Traditional Chinese": "車站在哪裡？" },
  },
  {
    id: "ja-life-basic-1",
    targetLanguage: "Japanese",
    targetText: "寝る",
    meanings: { English: "to sleep", "Simplified Chinese": "睡觉", "Traditional Chinese": "睡覺" },
    reading: "ねる",
    romanization: "neru",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "十一時に寝ます。",
    exampleTranslations: { English: "I go to sleep at eleven.", "Simplified Chinese": "我十一点睡觉。", "Traditional Chinese": "我十一點睡覺。" },
  },
  {
    id: "ja-numbers-basic-1",
    targetLanguage: "Japanese",
    targetText: "七",
    meanings: { English: "seven", "Simplified Chinese": "七", "Traditional Chinese": "七" },
    reading: "なな / しち",
    romanization: "nana / shichi",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "七つください。",
    exampleTranslations: { English: "Seven, please.", "Simplified Chinese": "请给我七个。", "Traditional Chinese": "請給我七個。" },
  },
  {
    id: "ja-verbs-basic-1",
    targetLanguage: "Japanese",
    targetText: "見る",
    meanings: { English: "to see; to watch", "Simplified Chinese": "看", "Traditional Chinese": "看" },
    reading: "みる",
    romanization: "miru",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "映画を見ます。",
    exampleTranslations: { English: "I watch a movie.", "Simplified Chinese": "我看电影。", "Traditional Chinese": "我看電影。" },
  },
  {
    id: "ja-work-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "会議",
    meanings: { English: "meeting; conference", "Simplified Chinese": "会议", "Traditional Chinese": "會議" },
    reading: "かいぎ",
    romanization: "kaigi",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "午後に会議があります。",
    exampleTranslations: { English: "There is a meeting in the afternoon.", "Simplified Chinese": "下午有会议。", "Traditional Chinese": "下午有會議。" },
  },
  {
    id: "ja-school-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "課題",
    meanings: { English: "assignment; task", "Simplified Chinese": "课题；作业", "Traditional Chinese": "課題；作業" },
    reading: "かだい",
    romanization: "kadai",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "課題を提出しました。",
    exampleTranslations: { English: "I submitted the assignment.", "Simplified Chinese": "我提交了作业。", "Traditional Chinese": "我提交了作業。" },
  },
  {
    id: "ja-anime-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "主人公",
    meanings: { English: "main character", "Simplified Chinese": "主角", "Traditional Chinese": "主角" },
    reading: "しゅじんこう",
    romanization: "shujinko",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "主人公は勇敢です。",
    exampleTranslations: { English: "The main character is brave.", "Simplified Chinese": "主角很勇敢。", "Traditional Chinese": "主角很勇敢。" },
  },
  {
    id: "ja-jlpt-advanced-1",
    targetLanguage: "Japanese",
    targetText: "恐縮",
    meanings: { English: "feeling obliged; humbled", "Simplified Chinese": "惶恐；不好意思", "Traditional Chinese": "惶恐；不好意思" },
    reading: "きょうしゅく",
    romanization: "kyoshuku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "お手数をおかけして恐縮です。",
    exampleTranslations: {
      English: "I am sorry to trouble you.",
      "Simplified Chinese": "给您添麻烦，我很不好意思。",
      "Traditional Chinese": "給您添麻煩，我很不好意思。",
    },
  },
  {
    id: "ja-food-basic-2",
    targetLanguage: "Japanese",
    targetText: "水",
    meanings: { English: "water", "Simplified Chinese": "水", "Traditional Chinese": "水" },
    reading: "みず",
    romanization: "mizu",
    level: "Basic",
    topic: "food",
    exampleSentence: "水をください。",
    exampleTranslations: { English: "Water, please.", "Simplified Chinese": "请给我水。", "Traditional Chinese": "請給我水。" },
  },
  {
    id: "ja-travel-basic-2",
    targetLanguage: "Japanese",
    targetText: "切符",
    meanings: { English: "ticket", "Simplified Chinese": "票", "Traditional Chinese": "票" },
    reading: "きっぷ",
    romanization: "kippu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "切符を買います。",
    exampleTranslations: { English: "I buy a ticket.", "Simplified Chinese": "我买票。", "Traditional Chinese": "我買票。" },
  },
  {
    id: "ja-life-basic-2",
    targetLanguage: "Japanese",
    targetText: "起きる",
    meanings: { English: "to wake up; to get up", "Simplified Chinese": "起床", "Traditional Chinese": "起床" },
    reading: "おきる",
    romanization: "okiru",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "六時に起きます。",
    exampleTranslations: { English: "I get up at six.", "Simplified Chinese": "我六点起床。", "Traditional Chinese": "我六點起床。" },
  },
  {
    id: "ja-numbers-basic-2",
    targetLanguage: "Japanese",
    targetText: "百",
    meanings: { English: "hundred", "Simplified Chinese": "百", "Traditional Chinese": "百" },
    reading: "ひゃく",
    romanization: "hyaku",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "百円です。",
    exampleTranslations: { English: "It is one hundred yen.", "Simplified Chinese": "是一百日元。", "Traditional Chinese": "是一百日圓。" },
  },
  {
    id: "ja-verbs-basic-2",
    targetLanguage: "Japanese",
    targetText: "行く",
    meanings: { English: "to go", "Simplified Chinese": "去", "Traditional Chinese": "去" },
    reading: "いく",
    romanization: "iku",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "学校へ行きます。",
    exampleTranslations: { English: "I go to school.", "Simplified Chinese": "我去学校。", "Traditional Chinese": "我去學校。" },
  },
  {
    id: "ja-work-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "締め切り",
    meanings: { English: "deadline", "Simplified Chinese": "截止日期", "Traditional Chinese": "截止日期" },
    reading: "しめきり",
    romanization: "shimekiri",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "締め切りは金曜日です。",
    exampleTranslations: { English: "The deadline is Friday.", "Simplified Chinese": "截止日期是星期五。", "Traditional Chinese": "截止日期是星期五。" },
  },
  {
    id: "ja-school-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "復習",
    meanings: { English: "review; revision", "Simplified Chinese": "复习", "Traditional Chinese": "複習" },
    reading: "ふくしゅう",
    romanization: "fukushu",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "寝る前に復習します。",
    exampleTranslations: { English: "I review before sleeping.", "Simplified Chinese": "我睡前复习。", "Traditional Chinese": "我睡前複習。" },
  },
  {
    id: "ja-anime-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "場面",
    meanings: { English: "scene; situation", "Simplified Chinese": "场面", "Traditional Chinese": "場面" },
    reading: "ばめん",
    romanization: "bamen",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "この場面が好きです。",
    exampleTranslations: { English: "I like this scene.", "Simplified Chinese": "我喜欢这个场面。", "Traditional Chinese": "我喜歡這個場面。" },
  },
  {
    id: "ja-jlpt-advanced-2",
    targetLanguage: "Japanese",
    targetText: "曖昧",
    meanings: { English: "vague; ambiguous", "Simplified Chinese": "暧昧；模糊", "Traditional Chinese": "曖昧；模糊" },
    reading: "あいまい",
    romanization: "aimai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "説明が曖昧でした。",
    exampleTranslations: { English: "The explanation was vague.", "Simplified Chinese": "说明很模糊。", "Traditional Chinese": "說明很模糊。" },
  },
  {
    id: "ja-jlpt-advanced-3",
    targetLanguage: "Japanese",
    targetText: "促す",
    meanings: { English: "to urge; to prompt", "Simplified Chinese": "促使；催促", "Traditional Chinese": "促使；催促" },
    reading: "うながす",
    romanization: "unagasu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "先生は学生に発言を促しました。",
    exampleTranslations: {
      English: "The teacher encouraged the students to speak.",
      "Simplified Chinese": "老师鼓励学生发言。",
      "Traditional Chinese": "老師鼓勵學生發言。",
    },
  },
  {
    id: "ko-food-basic-1",
    targetLanguage: "Korean",
    targetText: "밥",
    meanings: { English: "rice; meal", "Simplified Chinese": "吃饭", "Traditional Chinese": "吃飯" },
    reading: "밥",
    romanization: "bap",
    level: "Basic",
    topic: "food",
    exampleSentence: "밥을 먹어요.",
    exampleTranslations: { English: "I eat a meal.", "Simplified Chinese": "我吃饭。", "Traditional Chinese": "我吃飯。" },
  },
  {
    id: "ko-travel-basic-1",
    targetLanguage: "Korean",
    targetText: "역",
    meanings: { English: "station", "Simplified Chinese": "车站", "Traditional Chinese": "車站" },
    reading: "역",
    romanization: "yeok",
    level: "Basic",
    topic: "travel",
    exampleSentence: "역이 어디예요?",
    exampleTranslations: { English: "Where is the station?", "Simplified Chinese": "车站在哪里？", "Traditional Chinese": "車站在哪裡？" },
  },
  {
    id: "ko-life-basic-1",
    targetLanguage: "Korean",
    targetText: "자다",
    meanings: { English: "to sleep", "Simplified Chinese": "睡觉", "Traditional Chinese": "睡覺" },
    reading: "자다",
    romanization: "jada",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "열한 시에 자요.",
    exampleTranslations: { English: "I sleep at eleven.", "Simplified Chinese": "我十一点睡觉。", "Traditional Chinese": "我十一點睡覺。" },
  },
  {
    id: "ko-numbers-basic-1",
    targetLanguage: "Korean",
    targetText: "일곱",
    meanings: { English: "seven", "Simplified Chinese": "七", "Traditional Chinese": "七" },
    reading: "일곱",
    romanization: "ilgop",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "일곱 개 주세요.",
    exampleTranslations: { English: "Seven, please.", "Simplified Chinese": "请给我七个。", "Traditional Chinese": "請給我七個。" },
  },
  {
    id: "ko-verbs-basic-1",
    targetLanguage: "Korean",
    targetText: "보다",
    meanings: { English: "to see; to watch", "Simplified Chinese": "看", "Traditional Chinese": "看" },
    reading: "보다",
    romanization: "boda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "드라마를 봐요.",
    exampleTranslations: { English: "I watch a drama.", "Simplified Chinese": "我看电视剧。", "Traditional Chinese": "我看電視劇。" },
  },
  {
    id: "ko-work-intermediate-1",
    targetLanguage: "Korean",
    targetText: "회의",
    meanings: { English: "meeting", "Simplified Chinese": "会议", "Traditional Chinese": "會議" },
    reading: "회의",
    romanization: "hoeui",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "오후에 회의가 있어요.",
    exampleTranslations: { English: "There is a meeting in the afternoon.", "Simplified Chinese": "下午有会议。", "Traditional Chinese": "下午有會議。" },
  },
  {
    id: "ko-school-intermediate-1",
    targetLanguage: "Korean",
    targetText: "과제",
    meanings: { English: "assignment", "Simplified Chinese": "作业；课题", "Traditional Chinese": "作業；課題" },
    reading: "과제",
    romanization: "gwaje",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "과제를 냈어요.",
    exampleTranslations: { English: "I turned in the assignment.", "Simplified Chinese": "我交了作业。", "Traditional Chinese": "我交了作業。" },
  },
  {
    id: "ko-drama-intermediate-1",
    targetLanguage: "Korean",
    targetText: "주인공",
    meanings: { English: "main character", "Simplified Chinese": "主角", "Traditional Chinese": "主角" },
    reading: "주인공",
    romanization: "juingong",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "주인공이 용감해요.",
    exampleTranslations: { English: "The main character is brave.", "Simplified Chinese": "主角很勇敢。", "Traditional Chinese": "主角很勇敢。" },
  },
  {
    id: "ko-topik-advanced-1",
    targetLanguage: "Korean",
    targetText: "유지하다",
    meanings: { English: "to maintain", "Simplified Chinese": "维持", "Traditional Chinese": "維持" },
    reading: "유지하다",
    romanization: "yujihada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "건강한 습관을 유지해야 합니다.",
    exampleTranslations: {
      English: "You should maintain healthy habits.",
      "Simplified Chinese": "应该维持健康的习惯。",
      "Traditional Chinese": "應該維持健康的習慣。",
    },
  },
  {
    id: "ko-food-basic-2",
    targetLanguage: "Korean",
    targetText: "물",
    meanings: { English: "water", "Simplified Chinese": "水", "Traditional Chinese": "水" },
    reading: "물",
    romanization: "mul",
    level: "Basic",
    topic: "food",
    exampleSentence: "물 주세요.",
    exampleTranslations: { English: "Water, please.", "Simplified Chinese": "请给我水。", "Traditional Chinese": "請給我水。" },
  },
  {
    id: "ko-travel-basic-2",
    targetLanguage: "Korean",
    targetText: "표",
    meanings: { English: "ticket", "Simplified Chinese": "票", "Traditional Chinese": "票" },
    reading: "표",
    romanization: "pyo",
    level: "Basic",
    topic: "travel",
    exampleSentence: "표를 사요.",
    exampleTranslations: { English: "I buy a ticket.", "Simplified Chinese": "我买票。", "Traditional Chinese": "我買票。" },
  },
  {
    id: "ko-life-basic-2",
    targetLanguage: "Korean",
    targetText: "일어나다",
    meanings: { English: "to wake up; to get up", "Simplified Chinese": "起床", "Traditional Chinese": "起床" },
    reading: "일어나다",
    romanization: "ireonada",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "여섯 시에 일어나요.",
    exampleTranslations: { English: "I get up at six.", "Simplified Chinese": "我六点起床。", "Traditional Chinese": "我六點起床。" },
  },
  {
    id: "ko-numbers-basic-2",
    targetLanguage: "Korean",
    targetText: "백",
    meanings: { English: "hundred", "Simplified Chinese": "百", "Traditional Chinese": "百" },
    reading: "백",
    romanization: "baek",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "백 원이에요.",
    exampleTranslations: { English: "It is one hundred won.", "Simplified Chinese": "是一百韩元。", "Traditional Chinese": "是一百韓元。" },
  },
  {
    id: "ko-verbs-basic-2",
    targetLanguage: "Korean",
    targetText: "가다",
    meanings: { English: "to go", "Simplified Chinese": "去", "Traditional Chinese": "去" },
    reading: "가다",
    romanization: "gada",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "학교에 가요.",
    exampleTranslations: { English: "I go to school.", "Simplified Chinese": "我去学校。", "Traditional Chinese": "我去學校。" },
  },
  {
    id: "ko-work-intermediate-2",
    targetLanguage: "Korean",
    targetText: "마감",
    meanings: { English: "deadline; closing", "Simplified Chinese": "截止", "Traditional Chinese": "截止" },
    reading: "마감",
    romanization: "magam",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "마감은 금요일이에요.",
    exampleTranslations: { English: "The deadline is Friday.", "Simplified Chinese": "截止日期是星期五。", "Traditional Chinese": "截止日期是星期五。" },
  },
  {
    id: "ko-school-intermediate-2",
    targetLanguage: "Korean",
    targetText: "복습",
    meanings: { English: "review; revision", "Simplified Chinese": "复习", "Traditional Chinese": "複習" },
    reading: "복습",
    romanization: "bokseup",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "자기 전에 복습해요.",
    exampleTranslations: { English: "I review before sleeping.", "Simplified Chinese": "我睡前复习。", "Traditional Chinese": "我睡前複習。" },
  },
  {
    id: "ko-drama-intermediate-2",
    targetLanguage: "Korean",
    targetText: "장면",
    meanings: { English: "scene", "Simplified Chinese": "场面", "Traditional Chinese": "場面" },
    reading: "장면",
    romanization: "jangmyeon",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "이 장면이 좋아요.",
    exampleTranslations: { English: "I like this scene.", "Simplified Chinese": "我喜欢这个场面。", "Traditional Chinese": "我喜歡這個場面。" },
  },
  {
    id: "ko-topik-advanced-2",
    targetLanguage: "Korean",
    targetText: "모호하다",
    meanings: { English: "to be vague; ambiguous", "Simplified Chinese": "模糊；暧昧", "Traditional Chinese": "模糊；曖昧" },
    reading: "모호하다",
    romanization: "mohohada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "설명이 모호했어요.",
    exampleTranslations: { English: "The explanation was vague.", "Simplified Chinese": "说明很模糊。", "Traditional Chinese": "說明很模糊。" },
  },
  {
    id: "ko-topik-advanced-3",
    targetLanguage: "Korean",
    targetText: "촉구하다",
    meanings: { English: "to urge; to call for", "Simplified Chinese": "敦促；促请", "Traditional Chinese": "敦促；促請" },
    reading: "촉구하다",
    romanization: "chokguhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "전문가들은 대책을 촉구했습니다.",
    exampleTranslations: {
      English: "Experts called for countermeasures.",
      "Simplified Chinese": "专家们敦促采取对策。",
      "Traditional Chinese": "專家們敦促採取對策。",
    },
  },
  {
    id: "ja-food-basic-3",
    targetLanguage: "Japanese",
    targetText: "お茶",
    meanings: { English: "tea", "Simplified Chinese": "茶", "Traditional Chinese": "茶" },
    reading: "おちゃ",
    romanization: "ocha",
    level: "Basic",
    topic: "food",
    exampleSentence: "温かいお茶を飲みます。",
    exampleTranslations: { English: "I drink warm tea.", "Simplified Chinese": "我喝热茶。", "Traditional Chinese": "我喝熱茶。" },
  },
  {
    id: "ja-life-basic-3",
    targetLanguage: "Japanese",
    targetText: "友達",
    meanings: { English: "friend", "Simplified Chinese": "朋友", "Traditional Chinese": "朋友" },
    reading: "ともだち",
    romanization: "tomodachi",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "友達に会います。",
    exampleTranslations: { English: "I meet a friend.", "Simplified Chinese": "我见朋友。", "Traditional Chinese": "我見朋友。" },
  },
  {
    id: "ja-travel-basic-3",
    targetLanguage: "Japanese",
    targetText: "病院",
    meanings: { English: "hospital", "Simplified Chinese": "医院", "Traditional Chinese": "醫院" },
    reading: "びょういん",
    romanization: "byoin",
    level: "Basic",
    topic: "travel",
    exampleSentence: "病院は近いです。",
    exampleTranslations: { English: "The hospital is nearby.", "Simplified Chinese": "医院很近。", "Traditional Chinese": "醫院很近。" },
  },
  {
    id: "ja-verbs-basic-3",
    targetLanguage: "Japanese",
    targetText: "買う",
    meanings: { English: "to buy", "Simplified Chinese": "买", "Traditional Chinese": "買" },
    reading: "かう",
    romanization: "kau",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "パンを買います。",
    exampleTranslations: { English: "I buy bread.", "Simplified Chinese": "我买面包。", "Traditional Chinese": "我買麵包。" },
  },
  {
    id: "ja-work-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "連絡",
    meanings: { English: "contact; communication", "Simplified Chinese": "联系", "Traditional Chinese": "聯絡" },
    reading: "れんらく",
    romanization: "renraku",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "後で連絡します。",
    exampleTranslations: { English: "I will contact you later.", "Simplified Chinese": "我稍后联系你。", "Traditional Chinese": "我稍後聯絡你。" },
  },
  {
    id: "ja-school-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "試験",
    meanings: { English: "exam", "Simplified Chinese": "考试", "Traditional Chinese": "考試" },
    reading: "しけん",
    romanization: "shiken",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "明日は試験です。",
    exampleTranslations: { English: "Tomorrow is the exam.", "Simplified Chinese": "明天是考试。", "Traditional Chinese": "明天是考試。" },
  },
  {
    id: "ja-anime-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "展開",
    meanings: { English: "development; turn of events", "Simplified Chinese": "展开；剧情发展", "Traditional Chinese": "展開；劇情發展" },
    reading: "てんかい",
    romanization: "tenkai",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "次の展開が気になります。",
    exampleTranslations: { English: "I wonder what happens next.", "Simplified Chinese": "我很好奇接下来的发展。", "Traditional Chinese": "我很好奇接下來的發展。" },
  },
  {
    id: "ja-travel-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "予約",
    meanings: { English: "reservation; booking", "Simplified Chinese": "预约", "Traditional Chinese": "預約" },
    reading: "よやく",
    romanization: "yoyaku",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "ホテルを予約しました。",
    exampleTranslations: { English: "I booked a hotel.", "Simplified Chinese": "我预约了酒店。", "Traditional Chinese": "我預約了飯店。" },
  },
  {
    id: "ja-jlpt-advanced-4",
    targetLanguage: "Japanese",
    targetText: "著しい",
    meanings: { English: "remarkable; significant", "Simplified Chinese": "显著的", "Traditional Chinese": "顯著的" },
    reading: "いちじるしい",
    romanization: "ichijirushii",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "著しい変化がありました。",
    exampleTranslations: { English: "There was a significant change.", "Simplified Chinese": "发生了显著变化。", "Traditional Chinese": "發生了顯著變化。" },
  },
  {
    id: "ja-jlpt-advanced-5",
    targetLanguage: "Japanese",
    targetText: "推移",
    meanings: { English: "transition; trend", "Simplified Chinese": "变化趋势", "Traditional Chinese": "變化趨勢" },
    reading: "すいい",
    romanization: "suii",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "人口の推移を調べます。",
    exampleTranslations: { English: "I examine population trends.", "Simplified Chinese": "我调查人口变化趋势。", "Traditional Chinese": "我調查人口變化趨勢。" },
  },
  {
    id: "ja-jlpt-advanced-6",
    targetLanguage: "Japanese",
    targetText: "措置",
    meanings: { English: "measure; step", "Simplified Chinese": "措施", "Traditional Chinese": "措施" },
    reading: "そち",
    romanization: "sochi",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "早急な措置が必要です。",
    exampleTranslations: { English: "Urgent measures are necessary.", "Simplified Chinese": "需要紧急措施。", "Traditional Chinese": "需要緊急措施。" },
  },
  {
    id: "ja-jlpt-advanced-7",
    targetLanguage: "Japanese",
    targetText: "矛盾",
    meanings: { English: "contradiction", "Simplified Chinese": "矛盾", "Traditional Chinese": "矛盾" },
    reading: "むじゅん",
    romanization: "mujun",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "その説明には矛盾があります。",
    exampleTranslations: { English: "There is a contradiction in that explanation.", "Simplified Chinese": "那个说明有矛盾。", "Traditional Chinese": "那個說明有矛盾。" },
  },
  {
    id: "ja-jlpt-advanced-8",
    targetLanguage: "Japanese",
    targetText: "考慮",
    meanings: { English: "consideration", "Simplified Chinese": "考虑", "Traditional Chinese": "考慮" },
    reading: "こうりょ",
    romanization: "koryo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "安全を考慮します。",
    exampleTranslations: { English: "I take safety into consideration.", "Simplified Chinese": "我会考虑安全。", "Traditional Chinese": "我會考慮安全。" },
  },
  {
    id: "ko-food-basic-3",
    targetLanguage: "Korean",
    targetText: "차",
    meanings: { English: "tea", "Simplified Chinese": "茶", "Traditional Chinese": "茶" },
    reading: "차",
    romanization: "cha",
    level: "Basic",
    topic: "food",
    exampleSentence: "따뜻한 차를 마셔요.",
    exampleTranslations: { English: "I drink warm tea.", "Simplified Chinese": "我喝热茶。", "Traditional Chinese": "我喝熱茶。" },
  },
  {
    id: "ko-life-basic-3",
    targetLanguage: "Korean",
    targetText: "친구",
    meanings: { English: "friend", "Simplified Chinese": "朋友", "Traditional Chinese": "朋友" },
    reading: "친구",
    romanization: "chingu",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "친구를 만나요.",
    exampleTranslations: { English: "I meet a friend.", "Simplified Chinese": "我见朋友。", "Traditional Chinese": "我見朋友。" },
  },
  {
    id: "ko-travel-basic-3",
    targetLanguage: "Korean",
    targetText: "병원",
    meanings: { English: "hospital", "Simplified Chinese": "医院", "Traditional Chinese": "醫院" },
    reading: "병원",
    romanization: "byeongwon",
    level: "Basic",
    topic: "travel",
    exampleSentence: "병원이 가까워요.",
    exampleTranslations: { English: "The hospital is nearby.", "Simplified Chinese": "医院很近。", "Traditional Chinese": "醫院很近。" },
  },
  {
    id: "ko-verbs-basic-3",
    targetLanguage: "Korean",
    targetText: "사다",
    meanings: { English: "to buy", "Simplified Chinese": "买", "Traditional Chinese": "買" },
    reading: "사다",
    romanization: "sada",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "빵을 사요.",
    exampleTranslations: { English: "I buy bread.", "Simplified Chinese": "我买面包。", "Traditional Chinese": "我買麵包。" },
  },
  {
    id: "ko-work-intermediate-3",
    targetLanguage: "Korean",
    targetText: "연락",
    meanings: { English: "contact; communication", "Simplified Chinese": "联系", "Traditional Chinese": "聯絡" },
    reading: "연락",
    romanization: "yeollak",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "나중에 연락할게요.",
    exampleTranslations: { English: "I will contact you later.", "Simplified Chinese": "我稍后联系你。", "Traditional Chinese": "我稍後聯絡你。" },
  },
  {
    id: "ko-school-intermediate-3",
    targetLanguage: "Korean",
    targetText: "시험",
    meanings: { English: "exam", "Simplified Chinese": "考试", "Traditional Chinese": "考試" },
    reading: "시험",
    romanization: "siheom",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "내일은 시험이에요.",
    exampleTranslations: { English: "Tomorrow is the exam.", "Simplified Chinese": "明天是考试。", "Traditional Chinese": "明天是考試。" },
  },
  {
    id: "ko-drama-intermediate-3",
    targetLanguage: "Korean",
    targetText: "전개",
    meanings: { English: "development; turn of events", "Simplified Chinese": "展开；剧情发展", "Traditional Chinese": "展開；劇情發展" },
    reading: "전개",
    romanization: "jeongae",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "다음 전개가 궁금해요.",
    exampleTranslations: { English: "I wonder what happens next.", "Simplified Chinese": "我很好奇接下来的发展。", "Traditional Chinese": "我很好奇接下來的發展。" },
  },
  {
    id: "ko-travel-intermediate-1",
    targetLanguage: "Korean",
    targetText: "예약",
    meanings: { English: "reservation; booking", "Simplified Chinese": "预约", "Traditional Chinese": "預約" },
    reading: "예약",
    romanization: "yeyak",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "호텔을 예약했어요.",
    exampleTranslations: { English: "I booked a hotel.", "Simplified Chinese": "我预约了酒店。", "Traditional Chinese": "我預約了飯店。" },
  },
  {
    id: "ko-topik-advanced-4",
    targetLanguage: "Korean",
    targetText: "현저하다",
    meanings: { English: "to be remarkable; significant", "Simplified Chinese": "显著", "Traditional Chinese": "顯著" },
    reading: "현저하다",
    romanization: "hyeonjeohada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "현저한 변화가 있었어요.",
    exampleTranslations: { English: "There was a significant change.", "Simplified Chinese": "发生了显著变化。", "Traditional Chinese": "發生了顯著變化。" },
  },
  {
    id: "ko-topik-advanced-5",
    targetLanguage: "Korean",
    targetText: "추이",
    meanings: { English: "trend; transition", "Simplified Chinese": "变化趋势", "Traditional Chinese": "變化趨勢" },
    reading: "추이",
    romanization: "chui",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "인구 추이를 조사합니다.",
    exampleTranslations: { English: "I examine population trends.", "Simplified Chinese": "我调查人口变化趋势。", "Traditional Chinese": "我調查人口變化趨勢。" },
  },
  {
    id: "ko-topik-advanced-6",
    targetLanguage: "Korean",
    targetText: "조치",
    meanings: { English: "measure; step", "Simplified Chinese": "措施", "Traditional Chinese": "措施" },
    reading: "조치",
    romanization: "jochi",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "긴급한 조치가 필요합니다.",
    exampleTranslations: { English: "Urgent measures are necessary.", "Simplified Chinese": "需要紧急措施。", "Traditional Chinese": "需要緊急措施。" },
  },
  {
    id: "ko-topik-advanced-7",
    targetLanguage: "Korean",
    targetText: "모순",
    meanings: { English: "contradiction", "Simplified Chinese": "矛盾", "Traditional Chinese": "矛盾" },
    reading: "모순",
    romanization: "mosun",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 설명에는 모순이 있어요.",
    exampleTranslations: { English: "There is a contradiction in that explanation.", "Simplified Chinese": "那个说明有矛盾。", "Traditional Chinese": "那個說明有矛盾。" },
  },
  {
    id: "ko-topik-advanced-8",
    targetLanguage: "Korean",
    targetText: "고려",
    meanings: { English: "consideration", "Simplified Chinese": "考虑", "Traditional Chinese": "考慮" },
    reading: "고려",
    romanization: "goryeo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "안전을 고려합니다.",
    exampleTranslations: { English: "I take safety into consideration.", "Simplified Chinese": "我会考虑安全。", "Traditional Chinese": "我會考慮安全。" },
  },
];