import type { Topic, VocabItem } from "./vocabulary";

// Curated Intermediate expansion: 250 standalone concepts x Japanese/Korean = 500 entries.
// Globally de-duplicated against the current vocabulary; no modifier+noun combinatorial filler.
type SourceTopic = Topic | "exam";
type Pos = "noun" | "verb" | "adj";
type IntermediateRow = [topic: SourceTopic, pos: Pos, en: string, zh: string, ja: string, jaReading: string, jaRomanization: string, ko: string];

const rows: IntermediateRow[] = [
  ["work", "noun", "rejection", "驳回", "却下", "きゃっか", "kyakka", "반려"],
  ["work", "noun", "request", "委托", "依頼", "いらい", "irai", "의뢰"],
  ["work", "noun", "sharing", "共享", "共有", "きょうゆう", "kyouyuu", "공유"],
  ["work", "noun", "submission", "提交", "提出", "ていしゅつ", "teishutsu", "제출"],
  ["work", "noun", "renewal", "更新", "更新", "こうしん", "koushin", "갱신"],
  ["work", "noun", "recruitment", "招聘", "採用", "さいよう", "saiyou", "채용"],
  ["work", "noun", "goal", "目标", "目標", "もくひょう", "mokuhyou", "목표"],
  ["work", "noun", "payment", "付款", "支払", "しはらい", "shiharai", "지불"],
  ["work", "noun", "deposit received", "到账", "入金", "にゅうきん", "nyuukin", "입금"],
  ["work", "noun", "refund", "退款", "返金", "へんきん", "henkin", "환불"],
  ["work", "noun", "user", "用户", "利用者", "りようしゃ", "riyousha", "이용자"],
  ["work", "noun", "administrator", "管理员", "管理者", "かんりしゃ", "kanrisha", "관리자"],
  ["work", "noun", "person responsible", "负责人", "責任者", "せきにんしゃ", "sekininsha", "책임자"],
  ["work", "noun", "warning", "警告", "警告", "けいこく", "keikoku", "경고"],
  ["work", "noun", "workload", "工作量", "業務量", "ぎょうむりょう", "gyoumuryou", "업무량"],
  ["work", "noun", "status", "状态", "状態", "じょうたい", "joutai", "상태"],
  ["work", "noun", "risk", "风险", "リスク", "りすく", "risuku", "위험요소"],
  ["work", "noun", "client", "客户", "依頼主", "いらいしゅ", "iraishu", "의뢰인"],
  ["work", "noun", "vendor", "供应商", "業者", "ぎょうしゃ", "gyousha", "업체"],
  ["travel", "noun", "airline ticket", "机票", "航空券", "こうくうけん", "koukuuken", "항공권"],
  ["travel", "noun", "flight operation", "航班运行", "運航", "うんこう", "unkou", "운항"],
  ["travel", "noun", "duty free", "免税", "免税", "めんぜい", "menzei", "면세"],
  ["travel", "noun", "entry", "入境", "入国", "にゅうこく", "nyuukoku", "입국"],
  ["travel", "noun", "departure from country", "出境", "出国", "しゅっこく", "shukkoku", "출국"],
  ["travel", "noun", "information", "指引", "案内", "あんない", "annai", "안내"],
  ["travel", "noun", "origin", "出发地", "出発地", "しゅっぱつち", "shuppatsuchi", "출발지"],
  ["travel", "noun", "airline", "航空公司", "航空会社", "こうくうがいしゃ", "koukuugaisha", "항공사"],
  ["travel", "noun", "passenger", "旅客", "旅客", "りょきゃく", "ryokyaku", "여객"],
  ["travel", "noun", "crew", "乘务员", "乗員", "じょういん", "jouin", "승무원"],
  ["travel", "noun", "cabin", "客舱", "機内", "きない", "kinai", "기내"],
  ["travel", "noun", "border", "国境", "国境", "こっきょう", "kokkyou", "국경"],
  ["travel", "noun", "consulate", "领事馆", "領事館", "りょうじかん", "ryoujikan", "영사관"],
  ["travel", "noun", "embassy", "大使馆", "大使館", "たいしかん", "taishikan", "대사관"],
  ["travel", "noun", "local currency", "当地货币", "現地通貨", "げんちつうか", "genchitsuuka", "현지통화"],
  ["travel", "noun", "ride", "乘车", "乗車", "じょうしゃ", "jousha", "승차"],
  ["travel", "noun", "get off", "下车", "下車", "げしゃ", "gesha", "하차"],
  ["travel", "noun", "departure", "发车", "発車", "はっしゃ", "hassha", "발차"],
  ["travel", "noun", "travel insurance", "旅行保险", "旅行保険", "りょこうほけん", "ryokouhoken", "여행보험"],
  ["travel", "noun", "reservation number", "预约号", "予約番号", "よやくばんごう", "yoyakubangou", "예약번호"],
  ["travel", "noun", "baggage claim", "行李提取", "手荷物受取", "てにもつうけとり", "tenimotsuuketori", "수하물수취"],
  ["travel", "noun", "screening", "安检", "保安検査", "ほあんけんさ", "hoankensa", "보안검색"],
  ["travel", "noun", "delay", "延误", "遅れ", "おくれ", "okure", "지체"],
  ["travel", "noun", "cancellation", "取消", "取消", "とりけし", "torikeshi", "취소"],
  ["travel", "noun", "vacancy", "空房", "空室", "くうしつ", "kuushitsu", "빈방"],
  ["travel", "noun", "checkout", "退房", "退室", "たいしつ", "taishitsu", "퇴실"],
  ["travel", "noun", "guide", "导游", "案内人", "あんないにん", "annainin", "안내원"],
  ["travel", "noun", "travelogue", "游记", "旅行記", "りょこうき", "ryokouki", "여행기"],
  ["travel", "noun", "departure lounge", "候机室", "待合室", "まちあいしつ", "machiaishitsu", "대합실"],
  ["travel", "noun", "transfer", "换乘", "乗換", "のりかえ", "norikae", "갈아타기"],
  ["food", "noun", "aroma", "香味", "香り", "かおり", "kaori", "향"],
  ["food", "noun", "seasoning", "调味料", "調味料", "ちょうみりょう", "choumiryou", "조미료"],
  ["food", "noun", "portion", "分量", "分量", "ぶんりょう", "bunryou", "양"],
  ["food", "noun", "sourness", "酸味", "酸味", "さんみ", "sanmi", "신맛"],
  ["food", "noun", "bitterness", "苦味", "苦味", "にがみ", "nigami", "쓴맛"],
  ["food", "noun", "saltiness", "咸味", "塩味", "しおあじ", "shioaji", "짠맛"],
  ["food", "noun", "fried food", "油炸食品", "揚物", "あげもの", "agemono", "튀김"],
  ["food", "noun", "grilled food", "烤物", "焼物", "やきもの", "yakimono", "구이"],
  ["food", "noun", "simmered food", "煮物", "煮物", "にもの", "nimono", "조림"],
  ["food", "noun", "frozen food", "冷冻食品", "冷凍食品", "れいとうしょくひん", "reitoushokuhin", "냉동식품"],
  ["food", "noun", "expiration date", "保质期", "賞味期限", "しょうみきげん", "shoumikigen", "유통기한"],
  ["food", "noun", "protein", "蛋白质", "蛋白質", "たんぱくしつ", "tanpakushitsu", "단백질"],
  ["food", "noun", "carbohydrate", "碳水化合物", "炭水化物", "たんすいかぶつ", "tansuikabutsu", "탄수화물"],
  ["food", "noun", "calorie", "卡路里", "カロリー", "かろりー", "karorii", "칼로리"],
  ["food", "noun", "allergy", "过敏", "アレルギー", "あれるぎー", "arerugii", "알레르기"],
  ["daily life", "noun", "circumstance", "情况", "都合", "つごう", "tsugou", "사정"],
  ["daily life", "noun", "errand", "事情", "用事", "ようじ", "youji", "용무"],
  ["daily life", "noun", "nap", "午睡", "昼寝", "ひるね", "hirune", "낮잠"],
  ["daily life", "noun", "alarm", "闹钟", "目覚し", "めざまし", "mezamashi", "알람"],
  ["daily life", "noun", "shopping", "购物", "買物", "かいもの", "kaimono", "장보기"],
  ["daily life", "noun", "lack of sleep", "睡眠不足", "寝不足", "ねぶそく", "nebusoku", "수면부족"],
  ["daily life", "noun", "stomachache", "腹痛", "腹痛", "ふくつう", "fukutsuu", "복통"],
  ["daily life", "noun", "pharmacy", "药店", "薬局", "やっきょく", "yakkyoku", "약국"],
  ["daily life", "noun", "treatment", "治疗", "治療", "ちりょう", "chiryou", "치료"],
  ["daily life", "noun", "symptom", "症状", "症状", "しょうじょう", "shoujou", "증상"],
  ["daily life", "noun", "coins", "零钱", "小銭", "こぜに", "kozeni", "동전"],
  ["daily life", "noun", "replacement", "更换", "交換", "こうかん", "koukan", "교환"],
  ["daily life", "noun", "communication", "通信", "通信", "つうしん", "tsuushin", "통신"],
  ["daily life", "noun", "signal", "信号", "電波", "でんぱ", "denpa", "전파"],
  ["daily life", "noun", "photo", "照片", "写真", "しゃしん", "shashin", "사진"],
  ["daily life", "noun", "video", "视频", "動画", "どうが", "douga", "동영상"],
  ["daily life", "noun", "recording", "录音", "録音", "ろくおん", "rokuon", "녹음"],
  ["daily life", "noun", "function", "功能", "機能", "きのう", "kinou", "기능"],
  ["daily life", "noun", "search", "搜索", "検索", "けんさく", "kensaku", "검색"],
  ["daily life", "noun", "deletion", "删除", "削除", "さくじょ", "sakujo", "삭제"],
  ["daily life", "noun", "mail", "邮政", "郵便", "ゆうびん", "yuubin", "우편"],
  ["daily life", "noun", "envelope", "信封", "封筒", "ふうとう", "fuutou", "봉투"],
  ["daily life", "noun", "noise", "噪音", "騒音", "そうおん", "souon", "소음"],
  ["daily life", "noun", "typhoon", "台风", "台風", "たいふう", "taifuu", "태풍"],
  ["daily life", "noun", "earthquake", "地震", "地震", "じしん", "jishin", "지진"],
  ["daily life", "noun", "mood", "心情", "気分", "きぶん", "kibun", "기분"],
  ["daily life", "noun", "worry", "烦恼", "悩み", "なやみ", "nayami", "고민"],
  ["daily life", "noun", "anxiety", "担心", "心配", "しんぱい", "shinpai", "걱정"],
  ["daily life", "noun", "relief", "安心", "安心", "あんしん", "anshin", "안심"],
  ["daily life", "noun", "expectation", "期待", "期待", "きたい", "kitai", "기대"],
  ["daily life", "noun", "disappointment", "失望", "失望", "しつぼう", "shitsubou", "실망"],
  ["daily life", "noun", "relationship", "关系", "人間関係", "にんげんかんけい", "ningenkankei", "인간관계"],
  ["daily life", "noun", "conversation", "对话", "会話", "かいわ", "kaiwa", "대화"],
  ["daily life", "noun", "invitation", "邀请", "招待", "しょうたい", "shoutai", "초대"],
  ["daily life", "noun", "memory", "回忆", "思い出", "おもいで", "omoide", "추억"],
  ["daily life", "noun", "experience", "经历", "経験", "けいけん", "keiken", "경험"],
  ["daily life", "noun", "reason", "理由", "理由", "りゆう", "riyuu", "이유"],
  ["daily life", "noun", "chance", "机会", "機会", "きかい", "kikai", "기회"],
  ["daily life", "adj", "comfortable", "舒适", "快適", "かいてき", "kaiteki", "쾌적하다"],
  ["daily life", "adj", "inconvenient", "不方便", "不便", "ふべん", "fuben", "불편하다"],
  ["daily life", "adj", "complicated", "复杂", "複雑", "ふくざつ", "fukuzatsu", "복잡하다"],
  ["daily life", "adj", "simple", "简单", "単純", "たんじゅん", "tanjun", "단순하다"],
  ["daily life", "adj", "safe", "安全", "安全", "あんぜん", "anzen", "안전하다"],
  ["daily life", "adj", "natural", "自然", "自然", "しぜん", "shizen", "자연스럽다"],
  ["daily life", "adj", "special", "特别", "特別", "とくべつ", "tokubetsu", "특별하다"],
  ["school", "noun", "answer sheet", "答卷", "答案", "とうあん", "touan", "답안"],
  ["school", "noun", "admission", "入学", "入学", "にゅうがく", "nyuugaku", "입학"],
  ["school", "noun", "department", "学科", "学科", "がっか", "gakka", "학과"],
  ["school", "noun", "professor", "教授", "教授", "きょうじゅ", "kyouju", "교수"],
  ["school", "noun", "international student", "留学生", "留学生", "りゅうがくせい", "ryuugakusei", "유학생"],
  ["school", "noun", "answer", "回答", "回答", "かいとう", "kaitou", "답변"],
  ["school", "noun", "memorization", "背诵", "暗記", "あんき", "anki", "암기"],
  ["school", "noun", "grammar", "语法", "文法", "ぶんぽう", "bunpou", "문법"],
  ["school", "noun", "vocabulary", "词汇", "語彙", "ごい", "goi", "어휘"],
  ["school", "noun", "pronunciation", "发音", "発音", "はつおん", "hatsuon", "발음"],
  ["school", "noun", "grading", "评分", "採点", "さいてん", "saiten", "채점"],
  ["school", "noun", "failure", "不合格", "不合格", "ふごうかく", "fugoukaku", "불합격"],
  ["school", "noun", "qualification", "资格", "資格", "しかく", "shikaku", "자격"],
  ["school", "noun", "topic", "主题", "テーマ", "てーま", "teema", "주제"],
  ["school", "noun", "reference", "参考资料", "参考資料", "さんこうしりょう", "sankoushiryou", "참고자료"],
  ["school", "noun", "data", "数据", "データ", "でーた", "deeta", "데이터"],
  ["school", "noun", "outline", "提纲", "概要", "がいよう", "gaiyou", "개요"],
  ["school", "noun", "example", "例子", "例", "れい", "rei", "예시"],
  ["school", "noun", "definition", "定义", "定義", "ていぎ", "teigi", "정의"],
  ["school", "noun", "meaning", "含义", "意味", "いみ", "imi", "의미"],
  ["school", "noun", "translation", "翻译", "翻訳", "ほんやく", "honyaku", "번역"],
  ["school", "noun", "interpretation", "口译", "通訳", "つうやく", "tsuuyaku", "통역"],
  ["school", "noun", "reading comprehension", "阅读理解", "読解", "どくかい", "dokukai", "독해"],
  ["school", "noun", "listening comprehension", "听力", "聴解", "ちょうかい", "choukai", "듣기"],
  ["school", "noun", "writing", "写作", "記述", "きじゅつ", "kijutsu", "쓰기"],
  ["school", "noun", "speaking", "口语", "会話力", "かいわちから", "kaiwachikara", "말하기"],
  ["anime/drama", "noun", "supporting role", "配角", "脇役", "わきやく", "wakiyaku", "조연"],
  ["anime/drama", "noun", "actress", "女演员", "女優", "じょゆう", "joyuu", "여배우"],
  ["anime/drama", "noun", "viewing", "观看", "視聴", "しちょう", "shichou", "시청"],
  ["anime/drama", "noun", "popularity", "人气", "人気", "にんき", "ninki", "인기"],
  ["anime/drama", "noun", "appearance", "登场", "登場", "とうじょう", "toujou", "등장"],
  ["anime/drama", "noun", "ending", "结局", "結末", "けつまつ", "ketsumatsu", "결말"],
  ["anime/drama", "noun", "reader", "读者", "読者", "どくしゃ", "dokusha", "독자"],
  ["anime/drama", "noun", "audience", "观众", "観客", "かんきゃく", "kankyaku", "관객"],
  ["anime/drama", "noun", "stage", "舞台", "舞台", "ぶたい", "butai", "무대"],
  ["anime/drama", "noun", "visuals", "影像", "映像", "えいぞう", "eizou", "영상"],
  ["anime/drama", "noun", "novel", "小说", "小説", "しょうせつ", "shousetsu", "소설"],
  ["anime/drama", "noun", "episode", "集数", "話", "はなし", "hanashi", "회차"],
  ["anime/drama", "noun", "character", "角色", "登場人物", "とうじょうじんぶつ", "toujoujinbutsu", "등장인물"],
  ["anime/drama", "noun", "climax", "高潮", "山場", "やまば", "yamaba", "절정"],
  ["anime/drama", "adj", "moving", "感人", "感動的", "かんどうてき", "kandouteki", "감동적이다"],
  ["anime/drama", "adj", "realistic", "真实", "現実的", "げんじつてき", "genjitsuteki", "현실적이다"],
  ["anime/drama", "adj", "dramatic", "戏剧性", "劇的", "げきてき", "gekiteki", "극적이다"],
  ["anime/drama", "adj", "memorable", "难忘", "印象的", "いんしょうてき", "inshouteki", "인상적이다"],
  ["common verbs", "verb", "to finish", "结束", "終える", "おえる", "oeru", "끝내다"],
  ["common verbs", "verb", "to compare", "比较", "比べる", "くらべる", "kuraberu", "비교하다"],
  ["common verbs", "verb", "to change", "变化", "変わる", "かわる", "kawaru", "변하다"],
  ["common verbs", "verb", "to increase", "增加", "増える", "ふえる", "fueru", "늘다"],
  ["common verbs", "verb", "to increase something", "增加某物", "増やす", "ふやす", "fuyasu", "늘리다"],
  ["common verbs", "verb", "to decrease", "减少", "減る", "へる", "heru", "줄다"],
  ["common verbs", "verb", "to reduce", "减少某物", "減らす", "へらす", "herasu", "줄이다"],
  ["common verbs", "verb", "to recover", "痊愈", "治る", "なおる", "naoru", "낫다"],
  ["common verbs", "verb", "to break", "坏掉", "壊れる", "こわれる", "kowareru", "고장나다"],
  ["common verbs", "verb", "to destroy", "弄坏", "壊す", "こわす", "kowasu", "부수다"],
  ["common verbs", "verb", "to remember", "想起", "思い出す", "おもいだす", "omoidasu", "떠올리다"],
  ["common verbs", "verb", "to notice", "注意到", "気づく", "きづく", "kizuku", "깨닫다"],
  ["common verbs", "verb", "to investigate", "调查", "調べる", "しらべる", "shiraberu", "조사하다"],
  ["common verbs", "verb", "to search", "寻找", "探す", "さがす", "sagasu", "찾다"],
  ["common verbs", "verb", "to find", "找到", "見つける", "みつける", "mitsukeru", "발견하다"],
  ["common verbs", "verb", "to lose", "丢失", "失う", "うしなう", "ushinau", "잃다"],
  ["common verbs", "verb", "to carry", "搬运", "運ぶ", "はこぶ", "hakobu", "나르다"],
  ["common verbs", "verb", "to receive", "收到", "受取る", "うけとる", "uketoru", "받다"],
  ["common verbs", "verb", "to hand over", "递交", "渡す", "わたす", "watasu", "건네다"],
  ["common verbs", "verb", "to save money", "存钱", "貯める", "ためる", "tameru", "모으다"],
  ["common verbs", "verb", "to apply", "申请", "申込む", "もうしこみむ", "moushikomimu", "신청하다"],
  ["common verbs", "verb", "to refuse", "拒绝", "断る", "ことわる", "kotowaru", "거절하다"],
  ["common verbs", "verb", "to request", "请求", "頼む", "たのむ", "tanomu", "부탁하다"],
  ["common verbs", "verb", "to invite", "邀请", "誘う", "さそう", "sasou", "초대하다"],
  ["common verbs", "verb", "to promise", "约定", "約束する", "やくそくする", "yakusokusuru", "약속하다"],
  ["common verbs", "verb", "to contact", "联系", "連絡する", "れんらくする", "renrakusuru", "연락하다"],
  ["common verbs", "verb", "to consult", "商量", "相談する", "そうだんする", "soudansuru", "상담하다"],
  ["common verbs", "verb", "to explain", "说明", "説明する", "せつめいする", "setsumeisuru", "설명하다"],
  ["common verbs", "verb", "to confirm", "确认", "確認する", "かくにんする", "kakuninsuru", "확인하다"],
  ["common verbs", "verb", "to prepare", "准备", "準備する", "じゅんびする", "junbisuru", "준비하다"],
  ["common verbs", "verb", "to organize", "整理", "片付ける", "かたづける", "katazukeru", "정리하다"],
  ["common verbs", "verb", "to change clothes", "换衣服", "着替える", "きがえる", "kigaeru", "갈아입다"],
  ["common verbs", "verb", "to wake someone", "叫醒", "起こす", "おこす", "okosu", "깨우다"],
  ["common verbs", "verb", "to sleep", "入睡", "眠る", "ねむる", "nemuru", "잠들다"],
  ["common verbs", "verb", "to wake up", "醒来", "目覚める", "めざめる", "mezameru", "깨다"],
  ["common verbs", "verb", "to get lost", "迷路", "迷う", "まよう", "mayou", "헤매다"],
  ["common verbs", "verb", "to proceed", "前进", "進む", "すすむ", "susumu", "나아가다"],
  ["common verbs", "verb", "to stay overnight", "住宿", "泊まる", "とまる", "tomaru", "묵다"],
  ["common verbs", "verb", "to visit", "访问", "訪ねる", "たずねる", "tazuneru", "방문하다"],
  ["common verbs", "verb", "to guide", "引导", "案内する", "あんないする", "annaisuru", "안내하다"],
  ["exam", "noun", "condition", "条件", "条件", "じょうけん", "jouken", "조건"],
  ["exam", "noun", "opinion", "意见", "意見", "いけん", "iken", "의견"],
  ["exam", "noun", "problem", "问题", "問題", "もんだい", "mondai", "문제"],
  ["exam", "noun", "solution", "解决", "解決", "かいけつ", "kaiketsu", "해결"],
  ["exam", "noun", "change", "变化", "変化", "へんか", "henka", "변화"],
  ["exam", "noun", "comparison", "比较", "比較", "ひかく", "hikaku", "비교"],
  ["exam", "noun", "possibility", "可能性", "可能性", "かのうせい", "kanousei", "가능성"],
  ["exam", "noun", "culture", "文化", "文化", "ぶんか", "bunka", "문화"],
  ["exam", "noun", "environment", "环境", "環境", "かんきょう", "kankyou", "환경"],
  ["exam", "noun", "technology", "技术", "技術", "ぎじゅつ", "gijutsu", "기술"],
  ["exam", "noun", "information", "信息", "情報", "じょうほう", "jouhou", "정보"],
  ["exam", "noun", "international affairs", "国际", "国際", "こくさい", "kokusai", "국제"],
  ["exam", "noun", "population", "人口", "人口", "じんこう", "jinkou", "인구"],
  ["exam", "noun", "generation", "世代", "世代", "せだい", "sedai", "세대"],
  ["exam", "noun", "law", "法律", "法律", "ほうりつ", "houritsu", "법률"],
  ["exam", "noun", "right", "权利", "権利", "けんり", "kenri", "권리"],
  ["exam", "noun", "duty", "义务", "義務", "ぎむ", "gimu", "의무"],
  ["exam", "noun", "freedom", "自由", "自由", "じゆう", "jiyuu", "자유"],
  ["exam", "noun", "ability", "能力", "能力", "のうりょく", "nouryoku", "능력"],
  ["exam", "noun", "value", "价值", "価値", "かち", "kachi", "가치"],
  ["exam", "noun", "content", "内容", "内容", "ないよう", "naiyou", "내용"],
  ["exam", "noun", "part", "部分", "部分", "ぶぶん", "bubun", "부분"],
  ["exam", "noun", "whole", "整体", "全体", "ぜんたい", "zentai", "전체"],
  ["exam", "noun", "reality", "现实", "現実", "げんじつ", "genjitsu", "현실"],
  ["exam", "noun", "future", "未来", "未来", "みらい", "mirai", "미래"],
  ["exam", "noun", "past", "过去", "過去", "かこ", "kako", "과거"],
  ["exam", "noun", "present", "现在", "現在", "げんざい", "genzai", "현재"],
  ["exam", "noun", "example", "实例", "事例", "じれい", "jirei", "사례"],
  ["exam", "noun", "common point", "共同点", "共通点", "きょうつうてん", "kyoutsuuten", "공통점"],
  ["exam", "noun", "resource", "资源", "資源", "しげん", "shigen", "자원"],
  ["food", "noun", "recipe", "食谱", "レシピ", "れしぴ", "reshipi", "조리법"],
  ["food", "noun", "leftovers", "剩菜", "残り物", "のこりもの", "nokorimono", "남은음식"],
  ["food", "noun", "takeout", "外带", "持帰り", "じかえり", "jikaeri", "포장"],
  ["food", "noun", "chef", "厨师", "料理人", "りょうりにん", "ryourinin", "요리사"],
  ["food", "noun", "specialty", "招牌菜", "名物", "めいぶつ", "meibutsu", "특산물"],
  ["food", "noun", "serving", "份", "一人前", "いちにんまえ", "ichininmae", "일인분"],
  ["food", "adj", "fresh", "新鲜", "新鮮", "しんせん", "shinsen", "신선하다"],
  ["food", "adj", "rich", "浓郁", "濃厚", "のうこう", "noukou", "진하다"],
  ["food", "adj", "mild", "清淡", "薄味", "うすあじ", "usuaji", "담백하다"],
  ["food", "adj", "greasy", "油腻", "脂っこい", "あぶらっこい", "aburakkoi", "느끼하다"],
  ["food", "adj", "tasty", "美味", "美味しい", "おいしい", "oishii", "맛있다"],
  ["food", "adj", "bland", "淡", "味気ない", "あじけない", "ajikenai", "싱겁다"],
  ["daily life", "adj", "ordinary", "普通", "普通", "ふつう", "futsuu", "평범하다"],
  ["common verbs", "verb", "to participate", "参加", "参加する", "さんかする", "sankasuru", "참가하다"],
  ["common verbs", "verb", "to pass an exam", "合格", "合格する", "ごうかくする", "goukakusuru", "합격하다"],
  ["common verbs", "verb", "to graduate", "毕业", "卒業する", "そつぎょうする", "sotsugyousuru", "졸업하다"],
  ["common verbs", "verb", "to protect", "保护", "守る", "まもる", "mamoru", "지키다"],
  ["common verbs", "verb", "to recognize", "认可", "認める", "みとめる", "mitomeru", "인정하다"],
  ["common verbs", "verb", "to give up", "放弃", "諦める", "あきらめる", "akirameru", "포기하다"],
  ["common verbs", "verb", "to improve", "改善", "改善する", "かいぜんする", "kaizensuru", "개선하다"],
  ["common verbs", "verb", "to solve", "解决", "解決する", "かいけつする", "kaiketsusuru", "해결하다"],
  ["common verbs", "verb", "to prevent", "防止", "防ぐ", "ふせぐ", "fusegu", "막다"],
  ["common verbs", "verb", "to avoid", "避免", "避ける", "さける", "sakeru", "피하다"],
  ["common verbs", "verb", "to exchange", "交换", "交換する", "こうかんする", "koukansuru", "교환하다"],
  ["common verbs", "verb", "to save", "保存", "保存する", "ほぞんする", "hozonsuru", "저장하다"],
  ["common verbs", "verb", "to delete", "删除", "削除する", "さくじょする", "sakujosuru", "삭제하다"],
  ["common verbs", "verb", "to update", "更新", "更新する", "こうしんする", "koushinsuru", "갱신하다"],
];

function examples(pos: Pos, topic: SourceTopic, ja: string, ko: string, en: string, zh: string) {
  if (pos === "verb") return { ja: `「${ja}」という動詞を自然に使えるように練習します。`, ko: `“${ko}”라는 동사를 자연스럽게 쓰는 연습을 해요.`, en: `I practice using the verb “${en}” naturally.`, zh: `我练习自然地使用“${zh}”这个动词。` };
  if (pos === "adj") return { ja: `「${ja}」という表現を例文で確認します。`, ko: `“${ko}”라는 표현을 예문으로 확인해요.`, en: `I review the expression “${en}” in an example sentence.`, zh: `我通过例句复习“${zh}”这个表达。` };
  if (topic === "work") return { ja: `${ja}について担当者に確認しました。`, ko: `${ko} 관련 내용을 담당자에게 확인했어요.`, en: `I checked the details about ${en} with the person in charge.`, zh: `我向负责人确认了“${zh}”相关内容。` };
  if (topic === "travel") return { ja: `${ja}について事前に確認しました。`, ko: `${ko} 관련 내용을 미리 확인했어요.`, en: `I checked ${en} in advance.`, zh: `我提前确认了“${zh}”相关信息。` };
  if (topic === "school") return { ja: `${ja}について授業で学びました。`, ko: `${ko} 관련 내용을 수업에서 배웠어요.`, en: `I learned about ${en} in class.`, zh: `我在课上学习了“${zh}”。` };
  if (topic === "anime/drama") return { ja: `${ja}が特に印象に残りました。`, ko: `${ko} 부분이 특히 인상적이었어요.`, en: `The ${en} was especially memorable.`, zh: `“${zh}”这一点尤其令人印象深刻。` };
  if (topic === "food") return { ja: `${ja}について店員に聞きました。`, ko: `${ko} 관련 내용을 직원에게 물어봤어요.`, en: `I asked the staff about ${en}.`, zh: `我向店员询问了“${zh}”。` };
  if (topic === "exam") return { ja: `${ja}の意味と使い方を確認します。`, ko: `${ko}의 뜻과 쓰임을 확인해요.`, en: `I review the meaning and usage of ${en}.`, zh: `我复习“${zh}”的含义和用法。` };
  return { ja: `${ja}について詳しく調べました。`, ko: `${ko}에 대해 자세히 알아봤어요.`, en: `I looked into ${en} in more detail.`, zh: `我进一步了解了“${zh}”。` };
}

export const intermediateCuratedExpansion: VocabItem[] = rows.flatMap(([sourceTopic, pos, en, zh, ja, jaReading, jaRomanization, ko], index) => {
  const suffix = String(index + 1).padStart(3, "0");
  const jaTopic: Topic = sourceTopic === "exam" ? "JLPT" : sourceTopic;
  const koTopic: Topic = sourceTopic === "exam" ? "TOPIK" : sourceTopic;
  const ex = examples(pos, sourceTopic, ja, ko, en, zh);
  return [
    { id: `ja-intermediate-curated-${suffix}`, targetLanguage: "Japanese", targetText: ja, meanings: { English: en, "Simplified Chinese": zh }, reading: jaReading, romanization: jaRomanization, level: "Intermediate", topic: jaTopic, exampleSentence: ex.ja, exampleTranslations: { English: ex.en, "Simplified Chinese": ex.zh } },
    { id: `ko-intermediate-curated-${suffix}`, targetLanguage: "Korean", targetText: ko, meanings: { English: en, "Simplified Chinese": zh }, reading: ko, romanization: "", level: "Intermediate", topic: koTopic, exampleSentence: ex.ko, exampleTranslations: { English: ex.en, "Simplified Chinese": ex.zh } },
  ];
});
