import type { VocabItem } from "./vocabulary";

export const intermediateVocab: VocabItem[] = [
  {
    id: "ja-work-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "会議",
    meanings: { English: "meeting", "Simplified Chinese": "会议" },
    reading: "かいぎ",
    romanization: "kaigi",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "午後に会議があります。",
    exampleTranslations: { English: "There is a meeting in the afternoon.", "Simplified Chinese": "下午有会议。" },
  },
  {
    id: "ja-school-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "課題",
    meanings: { English: "assignment", "Simplified Chinese": "作业" },
    reading: "かだい",
    romanization: "kadai",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "課題を提出しました。",
    exampleTranslations: { English: "I submitted the assignment.", "Simplified Chinese": "我提交了作业。" },
  },
  {
    id: "ja-anime-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "主人公",
    meanings: { English: "protagonist", "Simplified Chinese": "主角" },
    reading: "しゅじんこう",
    romanization: "shujinko",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "主人公は勇敢です。",
    exampleTranslations: { English: "The main character is brave.", "Simplified Chinese": "主角很勇敢。" },
  },
  {
    id: "ja-work-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "締め切り",
    meanings: { English: "deadline", "Simplified Chinese": "截止日期" },
    reading: "しめきり",
    romanization: "shimekiri",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "締め切りは金曜日です。",
    exampleTranslations: { English: "The deadline is Friday.", "Simplified Chinese": "截止日期是星期五。" },
  },
  {
    id: "ja-school-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "復習",
    meanings: { English: "review", "Simplified Chinese": "复习" },
    reading: "ふくしゅう",
    romanization: "fukushu",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "寝る前に復習します。",
    exampleTranslations: { English: "I review before sleeping.", "Simplified Chinese": "我睡前复习。" },
  },
  {
    id: "ja-anime-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "場面",
    meanings: { English: "scene", "Simplified Chinese": "场面" },
    reading: "ばめん",
    romanization: "bamen",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "この場面が好きです。",
    exampleTranslations: { English: "I like this scene.", "Simplified Chinese": "我喜欢这个场面。" },
  },
  {
    id: "ko-work-intermediate-1",
    targetLanguage: "Korean",
    targetText: "회의",
    meanings: { English: "meeting", "Simplified Chinese": "会议" },
    reading: "회의",
    romanization: "hoeui",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "오후에 회의가 있어요.",
    exampleTranslations: { English: "There is a meeting in the afternoon.", "Simplified Chinese": "下午有会议。" },
  },
  {
    id: "ko-school-intermediate-1",
    targetLanguage: "Korean",
    targetText: "과제",
    meanings: { English: "assignment", "Simplified Chinese": "作业" },
    reading: "과제",
    romanization: "gwaje",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "과제를 냈어요.",
    exampleTranslations: { English: "I turned in the assignment.", "Simplified Chinese": "我交了作业。" },
  },
  {
    id: "ko-drama-intermediate-1",
    targetLanguage: "Korean",
    targetText: "주인공",
    meanings: { English: "protagonist", "Simplified Chinese": "主角" },
    reading: "주인공",
    romanization: "juingong",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "주인공이 용감해요.",
    exampleTranslations: { English: "The main character is brave.", "Simplified Chinese": "主角很勇敢。" },
  },
  {
    id: "ko-work-intermediate-2",
    targetLanguage: "Korean",
    targetText: "마감",
    meanings: { English: "deadline", "Simplified Chinese": "截止" },
    reading: "마감",
    romanization: "magam",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "마감은 금요일이에요.",
    exampleTranslations: { English: "The deadline is Friday.", "Simplified Chinese": "截止日期是星期五。" },
  },
  {
    id: "ko-school-intermediate-2",
    targetLanguage: "Korean",
    targetText: "복습",
    meanings: { English: "review", "Simplified Chinese": "复习" },
    reading: "복습",
    romanization: "bokseup",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "자기 전에 복습해요.",
    exampleTranslations: { English: "I review before sleeping.", "Simplified Chinese": "我睡前复习。" },
  },
  {
    id: "ko-drama-intermediate-2",
    targetLanguage: "Korean",
    targetText: "장면",
    meanings: { English: "scene", "Simplified Chinese": "场面" },
    reading: "장면",
    romanization: "jangmyeon",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "이 장면이 좋아요.",
    exampleTranslations: { English: "I like this scene.", "Simplified Chinese": "我喜欢这个场面。" },
  },
  {
    id: "ja-work-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "連絡",
    meanings: { English: "contact", "Simplified Chinese": "联系" },
    reading: "れんらく",
    romanization: "renraku",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "後で連絡します。",
    exampleTranslations: { English: "I will contact you later.", "Simplified Chinese": "我稍后联系你。" },
  },
  {
    id: "ja-school-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "試験",
    meanings: { English: "exam", "Simplified Chinese": "考试" },
    reading: "しけん",
    romanization: "shiken",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "明日は試験です。",
    exampleTranslations: { English: "Tomorrow is the exam.", "Simplified Chinese": "明天是考试。" },
  },
  {
    id: "ja-anime-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "展開",
    meanings: { English: "development", "Simplified Chinese": "发展" },
    reading: "てんかい",
    romanization: "tenkai",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "次の展開が気になります。",
    exampleTranslations: { English: "I wonder what happens next.", "Simplified Chinese": "我很好奇接下来的发展。" },
  },
  {
    id: "ja-travel-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "予約",
    meanings: { English: "reservation", "Simplified Chinese": "预约" },
    reading: "よやく",
    romanization: "yoyaku",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "ホテルを予約しました。",
    exampleTranslations: { English: "I booked a hotel.", "Simplified Chinese": "我预约了酒店。" },
  },
  {
    id: "ko-work-intermediate-3",
    targetLanguage: "Korean",
    targetText: "연락",
    meanings: { English: "contact", "Simplified Chinese": "联系" },
    reading: "연락",
    romanization: "yeollak",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "나중에 연락할게요.",
    exampleTranslations: { English: "I will contact you later.", "Simplified Chinese": "我稍后联系你。" },
  },
  {
    id: "ko-school-intermediate-3",
    targetLanguage: "Korean",
    targetText: "시험",
    meanings: { English: "exam", "Simplified Chinese": "考试" },
    reading: "시험",
    romanization: "siheom",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "내일은 시험이에요.",
    exampleTranslations: { English: "Tomorrow is the exam.", "Simplified Chinese": "明天是考试。" },
  },
  {
    id: "ko-drama-intermediate-3",
    targetLanguage: "Korean",
    targetText: "전개",
    meanings: { English: "development", "Simplified Chinese": "发展" },
    reading: "전개",
    romanization: "jeongae",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "다음 전개가 궁금해요.",
    exampleTranslations: { English: "I wonder what happens next.", "Simplified Chinese": "我很好奇接下来的发展。" },
  },
  {
    id: "ko-travel-intermediate-1",
    targetLanguage: "Korean",
    targetText: "예약",
    meanings: { English: "reservation", "Simplified Chinese": "预约" },
    reading: "예약",
    romanization: "yeyak",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "호텔을 예약했어요.",
    exampleTranslations: { English: "I booked a hotel.", "Simplified Chinese": "我预约了酒店。" },
  },
  {
    id: "ja-food-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "注文",
    meanings: { English: "order", "Simplified Chinese": "点餐" },
    reading: "ちゅうもん",
    romanization: "chumon",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "料理を注文しました。",
    exampleTranslations: { English: "I ordered food.", "Simplified Chinese": "我点了菜。" },
  },
  {
    id: "ja-life-intermediate-1",
    targetLanguage: "Japanese",
    targetText: "準備",
    meanings: { English: "preparation", "Simplified Chinese": "准备" },
    reading: "じゅんび",
    romanization: "junbi",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "旅行の準備をします。",
    exampleTranslations: { English: "I prepare for the trip.", "Simplified Chinese": "我准备旅行。" },
  },
  {
    id: "ja-work-intermediate-4",
    targetLanguage: "Japanese",
    targetText: "確認",
    meanings: { English: "confirmation", "Simplified Chinese": "确认" },
    reading: "かくにん",
    romanization: "kakunin",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "資料を確認します。",
    exampleTranslations: { English: "I check the documents.", "Simplified Chinese": "我确认资料。" },
  },
  {
    id: "ja-work-intermediate-5",
    targetLanguage: "Japanese",
    targetText: "提案",
    meanings: { English: "proposal", "Simplified Chinese": "提案" },
    reading: "ていあん",
    romanization: "teian",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "新しい提案があります。",
    exampleTranslations: { English: "I have a new proposal.", "Simplified Chinese": "我有新的提案。" },
  },
  {
    id: "ja-school-intermediate-4",
    targetLanguage: "Japanese",
    targetText: "合格",
    meanings: { English: "passing", "Simplified Chinese": "合格" },
    reading: "ごうかく",
    romanization: "gokaku",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "試験に合格しました。",
    exampleTranslations: { English: "I passed the exam.", "Simplified Chinese": "我考试合格了。" },
  },
  {
    id: "ja-school-intermediate-5",
    targetLanguage: "Japanese",
    targetText: "発表",
    meanings: { English: "presentation", "Simplified Chinese": "发表" },
    reading: "はっぴょう",
    romanization: "happyo",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "授業で発表します。",
    exampleTranslations: { English: "I give a presentation in class.", "Simplified Chinese": "我在课上发表。" },
  },
  {
    id: "ja-anime-intermediate-4",
    targetLanguage: "Japanese",
    targetText: "声優",
    meanings: { English: "actor", "Simplified Chinese": "声优" },
    reading: "せいゆう",
    romanization: "seiyu",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "この声優が好きです。",
    exampleTranslations: { English: "I like this voice actor.", "Simplified Chinese": "我喜欢这个声优。" },
  },
  {
    id: "ja-anime-intermediate-5",
    targetLanguage: "Japanese",
    targetText: "最終回",
    meanings: { English: "finale", "Simplified Chinese": "最后一集" },
    reading: "さいしゅうかい",
    romanization: "saishukai",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "最終回を見ました。",
    exampleTranslations: { English: "I watched the final episode.", "Simplified Chinese": "我看了最后一集。" },
  },
  {
    id: "ko-food-intermediate-1",
    targetLanguage: "Korean",
    targetText: "주문",
    meanings: { English: "order", "Simplified Chinese": "点餐" },
    reading: "주문",
    romanization: "jumun",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "음식을 주문했어요.",
    exampleTranslations: { English: "I ordered food.", "Simplified Chinese": "我点了菜。" },
  },
  {
    id: "ko-life-intermediate-1",
    targetLanguage: "Korean",
    targetText: "준비",
    meanings: { English: "preparation", "Simplified Chinese": "准备" },
    reading: "준비",
    romanization: "junbi",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "여행 준비를 해요.",
    exampleTranslations: { English: "I prepare for the trip.", "Simplified Chinese": "我准备旅行。" },
  },
  {
    id: "ko-work-intermediate-4",
    targetLanguage: "Korean",
    targetText: "확인",
    meanings: { English: "confirmation", "Simplified Chinese": "确认" },
    reading: "확인",
    romanization: "hwagin",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "자료를 확인해요.",
    exampleTranslations: { English: "I check the documents.", "Simplified Chinese": "我确认资料。" },
  },
  {
    id: "ko-work-intermediate-5",
    targetLanguage: "Korean",
    targetText: "제안",
    meanings: { English: "proposal", "Simplified Chinese": "提案" },
    reading: "제안",
    romanization: "jean",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "새로운 제안이 있어요.",
    exampleTranslations: { English: "I have a new proposal.", "Simplified Chinese": "我有新的提案。" },
  },
  {
    id: "ko-school-intermediate-4",
    targetLanguage: "Korean",
    targetText: "합격",
    meanings: { English: "passing", "Simplified Chinese": "合格" },
    reading: "합격",
    romanization: "hapgyeok",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "시험에 합격했어요.",
    exampleTranslations: { English: "I passed the exam.", "Simplified Chinese": "我考试合格了。" },
  },
  {
    id: "ko-school-intermediate-5",
    targetLanguage: "Korean",
    targetText: "발표",
    meanings: { English: "presentation", "Simplified Chinese": "发表" },
    reading: "발표",
    romanization: "balpyo",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "수업에서 발표해요.",
    exampleTranslations: { English: "I give a presentation in class.", "Simplified Chinese": "我在课上发表。" },
  },
  {
    id: "ko-drama-intermediate-4",
    targetLanguage: "Korean",
    targetText: "성우",
    meanings: { English: "actor", "Simplified Chinese": "声优" },
    reading: "성우",
    romanization: "seongu",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "이 성우를 좋아해요.",
    exampleTranslations: { English: "I like this voice actor.", "Simplified Chinese": "我喜欢这个声优。" },
  },
  {
    id: "ko-drama-intermediate-5",
    targetLanguage: "Korean",
    targetText: "마지막 회",
    meanings: { English: "finale", "Simplified Chinese": "最后一集" },
    reading: "마지막 회",
    romanization: "majimak hoe",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "마지막 회를 봤어요.",
    exampleTranslations: { English: "I watched the final episode.", "Simplified Chinese": "我看了最后一集。" },
  },
  {
    id: "ja-food-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "メニュー",
    meanings: { English: "menu", "Simplified Chinese": "菜单" },
    reading: "メニュー",
    romanization: "menyu",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "メニューを確認します。",
    exampleTranslations: { English: "I check the menu.", "Simplified Chinese": "我确认菜单。" },
  },
  {
    id: "ko-food-intermediate-2",
    targetLanguage: "Korean",
    targetText: "메뉴",
    meanings: { English: "menu", "Simplified Chinese": "菜单" },
    reading: "메뉴",
    romanization: "menyu",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "메뉴를 확인해요.",
    exampleTranslations: { English: "I check the menu.", "Simplified Chinese": "我确认菜单。" },
  },
  {
    id: "ja-food-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "材料",
    meanings: { English: "ingredient", "Simplified Chinese": "食材" },
    reading: "ざいりょう",
    romanization: "zairyo",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "材料を切ります。",
    exampleTranslations: { English: "I cut the ingredients.", "Simplified Chinese": "我切食材。" },
  },
  {
    id: "ko-food-intermediate-3",
    targetLanguage: "Korean",
    targetText: "재료",
    meanings: { English: "ingredient", "Simplified Chinese": "食材" },
    reading: "재료",
    romanization: "jaeryo",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "재료를 썰어요.",
    exampleTranslations: { English: "I cut the ingredients.", "Simplified Chinese": "我切食材。" },
  },
  {
    id: "ja-food-intermediate-4",
    targetLanguage: "Japanese",
    targetText: "味",
    meanings: { English: "taste", "Simplified Chinese": "味道" },
    reading: "あじ",
    romanization: "aji",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "味が濃いです。",
    exampleTranslations: { English: "The taste is strong.", "Simplified Chinese": "味道很浓。" },
  },
  {
    id: "ko-food-intermediate-4",
    targetLanguage: "Korean",
    targetText: "맛",
    meanings: { English: "taste", "Simplified Chinese": "味道" },
    reading: "맛",
    romanization: "mat",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "맛이 진해요.",
    exampleTranslations: { English: "The taste is strong.", "Simplified Chinese": "味道很浓。" },
  },
  {
    id: "ja-food-intermediate-5",
    targetLanguage: "Japanese",
    targetText: "辛い",
    meanings: { English: "spicy", "Simplified Chinese": "辣的" },
    reading: "からい",
    romanization: "karai",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "この料理は辛いです。",
    exampleTranslations: { English: "This food is spicy.", "Simplified Chinese": "这道菜很辣。" },
  },
  {
    id: "ko-food-intermediate-5",
    targetLanguage: "Korean",
    targetText: "맵다",
    meanings: { English: "spicy", "Simplified Chinese": "辣的" },
    reading: "맵다",
    romanization: "maepda",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "이 음식은 매워요.",
    exampleTranslations: { English: "This food is spicy.", "Simplified Chinese": "这道菜很辣。" },
  },
  {
    id: "ja-travel-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "出発",
    meanings: { English: "departure", "Simplified Chinese": "出发" },
    reading: "しゅっぱつ",
    romanization: "shuppatsu",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "出発は朝です。",
    exampleTranslations: { English: "Departure is in the morning.", "Simplified Chinese": "早上出发。" },
  },
  {
    id: "ko-travel-intermediate-2",
    targetLanguage: "Korean",
    targetText: "출발",
    meanings: { English: "departure", "Simplified Chinese": "出发" },
    reading: "출발",
    romanization: "chulbal",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "출발은 아침이에요.",
    exampleTranslations: { English: "Departure is in the morning.", "Simplified Chinese": "早上出发。" },
  },
  {
    id: "ja-travel-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "到着",
    meanings: { English: "arrival", "Simplified Chinese": "到达" },
    reading: "とうちゃく",
    romanization: "tochaku",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "到着は夜です。",
    exampleTranslations: { English: "Arrival is at night.", "Simplified Chinese": "晚上到达。" },
  },
  {
    id: "ko-travel-intermediate-3",
    targetLanguage: "Korean",
    targetText: "도착",
    meanings: { English: "arrival", "Simplified Chinese": "到达" },
    reading: "도착",
    romanization: "dochag",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "도착은 밤이에요.",
    exampleTranslations: { English: "Arrival is at night.", "Simplified Chinese": "晚上到达。" },
  },
  {
    id: "ja-travel-intermediate-4",
    targetLanguage: "Japanese",
    targetText: "乗り換え",
    meanings: { English: "transfer", "Simplified Chinese": "换乘" },
    reading: "のりかえ",
    romanization: "norikae",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "駅で乗り換えます。",
    exampleTranslations: { English: "I transfer at the station.", "Simplified Chinese": "我在车站换乘。" },
  },
  {
    id: "ko-travel-intermediate-4",
    targetLanguage: "Korean",
    targetText: "환승",
    meanings: { English: "transfer", "Simplified Chinese": "换乘" },
    reading: "환승",
    romanization: "hwanseung",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "역에서 환승해요.",
    exampleTranslations: { English: "I transfer at the station.", "Simplified Chinese": "我在车站换乘。" },
  },
  {
    id: "ja-travel-intermediate-5",
    targetLanguage: "Japanese",
    targetText: "経路",
    meanings: { English: "route", "Simplified Chinese": "路线" },
    reading: "けいろ",
    romanization: "keiro",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "経路を調べます。",
    exampleTranslations: { English: "I look up the route.", "Simplified Chinese": "我查路线。" },
  },
  {
    id: "ko-travel-intermediate-5",
    targetLanguage: "Korean",
    targetText: "경로",
    meanings: { English: "route", "Simplified Chinese": "路线" },
    reading: "경로",
    romanization: "gyeongno",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "경로를 찾아봐요.",
    exampleTranslations: { English: "I look up the route.", "Simplified Chinese": "我查路线。" },
  },
  {
    id: "ja-life-intermediate-2",
    targetLanguage: "Japanese",
    targetText: "約束",
    meanings: { English: "appointment", "Simplified Chinese": "约定" },
    reading: "やくそく",
    romanization: "yakusoku",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "友達と約束があります。",
    exampleTranslations: { English: "I have an appointment with a friend.", "Simplified Chinese": "我和朋友有约。" },
  },
  {
    id: "ko-life-intermediate-2",
    targetLanguage: "Korean",
    targetText: "약속",
    meanings: { English: "appointment", "Simplified Chinese": "约定" },
    reading: "약속",
    romanization: "yaksok",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "친구와 약속이 있어요.",
    exampleTranslations: { English: "I have an appointment with a friend.", "Simplified Chinese": "我和朋友有约。" },
  },
  {
    id: "ja-life-intermediate-3",
    targetLanguage: "Japanese",
    targetText: "習慣",
    meanings: { English: "habit", "Simplified Chinese": "习惯" },
    reading: "しゅうかん",
    romanization: "shukan",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "早起きの習慣があります。",
    exampleTranslations: { English: "I have a habit of waking early.", "Simplified Chinese": "我有早起的习惯。" },
  },
  {
    id: "ko-life-intermediate-3",
    targetLanguage: "Korean",
    targetText: "습관",
    meanings: { English: "habit", "Simplified Chinese": "习惯" },
    reading: "습관",
    romanization: "seupgwan",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "일찍 일어나는 습관이 있어요.",
    exampleTranslations: { English: "I have a habit of waking early.", "Simplified Chinese": "我有早起的习惯。" },
  },
  {
    id: "ja-life-intermediate-4",
    targetLanguage: "Japanese",
    targetText: "記憶",
    meanings: { English: "memory", "Simplified Chinese": "记忆" },
    reading: "きおく",
    romanization: "kioku",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "その記憶は大切です。",
    exampleTranslations: { English: "That memory is precious.", "Simplified Chinese": "那个记忆很珍贵。" },
  },
  {
    id: "ko-life-intermediate-4",
    targetLanguage: "Korean",
    targetText: "기억",
    meanings: { English: "memory", "Simplified Chinese": "记忆" },
    reading: "기억",
    romanization: "gieok",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "그 기억은 소중해요.",
    exampleTranslations: { English: "That memory is precious.", "Simplified Chinese": "那个记忆很珍贵。" },
  },
  {
    id: "ja-life-intermediate-5",
    targetLanguage: "Japanese",
    targetText: "健康",
    meanings: { English: "health", "Simplified Chinese": "健康" },
    reading: "けんこう",
    romanization: "kenko",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "健康に気をつけます。",
    exampleTranslations: { English: "I take care of my health.", "Simplified Chinese": "我注意健康。" },
  },
  {
    id: "ko-life-intermediate-5",
    targetLanguage: "Korean",
    targetText: "건강",
    meanings: { English: "health", "Simplified Chinese": "健康" },
    reading: "건강",
    romanization: "geongang",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "건강을 챙겨요.",
    exampleTranslations: { English: "I take care of my health.", "Simplified Chinese": "我注意健康。" },
  },
  {
    id: "ja-work-intermediate-6",
    targetLanguage: "Japanese",
    targetText: "報告",
    meanings: { English: "report", "Simplified Chinese": "报告" },
    reading: "ほうこく",
    romanization: "hokoku",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "結果を報告します。",
    exampleTranslations: { English: "I report the results.", "Simplified Chinese": "我报告结果。" },
  },
  {
    id: "ko-work-intermediate-6",
    targetLanguage: "Korean",
    targetText: "보고",
    meanings: { English: "report", "Simplified Chinese": "报告" },
    reading: "보고",
    romanization: "bogo",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "결과를 보고해요.",
    exampleTranslations: { English: "I report the results.", "Simplified Chinese": "我报告结果。" },
  },
  {
    id: "ja-work-intermediate-7",
    targetLanguage: "Japanese",
    targetText: "承認",
    meanings: { English: "approval", "Simplified Chinese": "批准" },
    reading: "しょうにん",
    romanization: "shonin",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "承認を待っています。",
    exampleTranslations: { English: "I am waiting for approval.", "Simplified Chinese": "我在等批准。" },
  },
  {
    id: "ko-work-intermediate-7",
    targetLanguage: "Korean",
    targetText: "승인",
    meanings: { English: "approval", "Simplified Chinese": "批准" },
    reading: "승인",
    romanization: "seungin",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "승인을 기다려요.",
    exampleTranslations: { English: "I am waiting for approval.", "Simplified Chinese": "我在等批准。" },
  },
  {
    id: "ja-work-intermediate-8",
    targetLanguage: "Japanese",
    targetText: "予定",
    meanings: { English: "schedule", "Simplified Chinese": "日程" },
    reading: "よてい",
    romanization: "yotei",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "予定を変更します。",
    exampleTranslations: { English: "I change the schedule.", "Simplified Chinese": "我改日程。" },
  },
  {
    id: "ko-work-intermediate-8",
    targetLanguage: "Korean",
    targetText: "일정",
    meanings: { English: "schedule", "Simplified Chinese": "日程" },
    reading: "일정",
    romanization: "iljeong",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "일정을 바꿔요.",
    exampleTranslations: { English: "I change the schedule.", "Simplified Chinese": "我改日程。" },
  },
  {
    id: "ja-work-intermediate-9",
    targetLanguage: "Japanese",
    targetText: "顧客",
    meanings: { English: "client", "Simplified Chinese": "客户" },
    reading: "こきゃく",
    romanization: "kokyaku",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "顧客に説明します。",
    exampleTranslations: { English: "I explain it to the client.", "Simplified Chinese": "我向客户说明。" },
  },
  {
    id: "ko-work-intermediate-9",
    targetLanguage: "Korean",
    targetText: "고객",
    meanings: { English: "client", "Simplified Chinese": "客户" },
    reading: "고객",
    romanization: "gogaek",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "고객에게 설명해요.",
    exampleTranslations: { English: "I explain it to the client.", "Simplified Chinese": "我向客户说明。" },
  },
  {
    id: "ja-work-intermediate-10",
    targetLanguage: "Japanese",
    targetText: "契約",
    meanings: { English: "contract", "Simplified Chinese": "合同" },
    reading: "けいやく",
    romanization: "keiyaku",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "契約を結びます。",
    exampleTranslations: { English: "We sign a contract.", "Simplified Chinese": "我们签合同。" },
  },
  {
    id: "ko-work-intermediate-10",
    targetLanguage: "Korean",
    targetText: "계약",
    meanings: { English: "contract", "Simplified Chinese": "合同" },
    reading: "계약",
    romanization: "gyeyak",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "계약을 맺어요.",
    exampleTranslations: { English: "We sign a contract.", "Simplified Chinese": "我们签合同。" },
  },
  {
    id: "ja-work-intermediate-11",
    targetLanguage: "Japanese",
    targetText: "部署",
    meanings: { English: "department", "Simplified Chinese": "部门" },
    reading: "ぶしょ",
    romanization: "busho",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "部署を移ります。",
    exampleTranslations: { English: "I move to another department.", "Simplified Chinese": "我调到别的部门。" },
  },
  {
    id: "ko-work-intermediate-11",
    targetLanguage: "Korean",
    targetText: "부서",
    meanings: { English: "department", "Simplified Chinese": "部门" },
    reading: "부서",
    romanization: "buseo",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "부서를 옮겨요.",
    exampleTranslations: { English: "I move to another department.", "Simplified Chinese": "我调到别的部门。" },
  },
  {
    id: "ja-work-intermediate-12",
    targetLanguage: "Japanese",
    targetText: "責任",
    meanings: { English: "responsibility", "Simplified Chinese": "责任" },
    reading: "せきにん",
    romanization: "sekinin",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "責任を持ちます。",
    exampleTranslations: { English: "I take responsibility.", "Simplified Chinese": "我承担责任。" },
  },
  {
    id: "ko-work-intermediate-12",
    targetLanguage: "Korean",
    targetText: "책임",
    meanings: { English: "responsibility", "Simplified Chinese": "责任" },
    reading: "책임",
    romanization: "chaegim",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "책임을 져요.",
    exampleTranslations: { English: "I take responsibility.", "Simplified Chinese": "我承担责任。" },
  },
  {
    id: "ja-school-intermediate-6",
    targetLanguage: "Japanese",
    targetText: "講義",
    meanings: { English: "lecture", "Simplified Chinese": "讲课" },
    reading: "こうぎ",
    romanization: "kogi",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "講義を受けます。",
    exampleTranslations: { English: "I attend a lecture.", "Simplified Chinese": "我听课。" },
  },
  {
    id: "ko-school-intermediate-6",
    targetLanguage: "Korean",
    targetText: "강의",
    meanings: { English: "lecture", "Simplified Chinese": "讲课" },
    reading: "강의",
    romanization: "gangui",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "강의를 들어요.",
    exampleTranslations: { English: "I attend a lecture.", "Simplified Chinese": "我听课。" },
  },
  {
    id: "ja-school-intermediate-7",
    targetLanguage: "Japanese",
    targetText: "研究",
    meanings: { English: "research", "Simplified Chinese": "研究" },
    reading: "けんきゅう",
    romanization: "kenkyu",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "日本語を研究します。",
    exampleTranslations: { English: "I research the language.", "Simplified Chinese": "我研究语言。" },
  },
  {
    id: "ko-school-intermediate-7",
    targetLanguage: "Korean",
    targetText: "연구",
    meanings: { English: "research", "Simplified Chinese": "研究" },
    reading: "연구",
    romanization: "yeongu",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "한국어를 연구해요.",
    exampleTranslations: { English: "I research the language.", "Simplified Chinese": "我研究语言。" },
  },
  {
    id: "ja-school-intermediate-8",
    targetLanguage: "Japanese",
    targetText: "成績",
    meanings: { English: "grade", "Simplified Chinese": "成绩" },
    reading: "せいせき",
    romanization: "seiseki",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "成績が上がりました。",
    exampleTranslations: { English: "My grades improved.", "Simplified Chinese": "我的成绩提高了。" },
  },
  {
    id: "ko-school-intermediate-8",
    targetLanguage: "Korean",
    targetText: "성적",
    meanings: { English: "grade", "Simplified Chinese": "成绩" },
    reading: "성적",
    romanization: "seongjeok",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "성적이 올랐어요.",
    exampleTranslations: { English: "My grades improved.", "Simplified Chinese": "我的成绩提高了。" },
  },
  {
    id: "ja-school-intermediate-9",
    targetLanguage: "Japanese",
    targetText: "出席",
    meanings: { English: "attendance", "Simplified Chinese": "出席" },
    reading: "しゅっせき",
    romanization: "shusseki",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "毎日出席します。",
    exampleTranslations: { English: "I attend every day.", "Simplified Chinese": "我每天出席。" },
  },
  {
    id: "ko-school-intermediate-9",
    targetLanguage: "Korean",
    targetText: "출석",
    meanings: { English: "attendance", "Simplified Chinese": "出席" },
    reading: "출석",
    romanization: "chulseok",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "매일 출석해요.",
    exampleTranslations: { English: "I attend every day.", "Simplified Chinese": "我每天出席。" },
  },
  {
    id: "ja-school-intermediate-10",
    targetLanguage: "Japanese",
    targetText: "質問",
    meanings: { English: "question", "Simplified Chinese": "问题" },
    reading: "しつもん",
    romanization: "shitsumon",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "先生に質問します。",
    exampleTranslations: { English: "I ask the teacher a question.", "Simplified Chinese": "我问老师问题。" },
  },
  {
    id: "ko-school-intermediate-10",
    targetLanguage: "Korean",
    targetText: "질문",
    meanings: { English: "question", "Simplified Chinese": "问题" },
    reading: "질문",
    romanization: "jilmun",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "선생님께 질문해요.",
    exampleTranslations: { English: "I ask the teacher a question.", "Simplified Chinese": "我问老师问题。" },
  },
  {
    id: "ja-school-intermediate-11",
    targetLanguage: "Japanese",
    targetText: "説明",
    meanings: { English: "explanation", "Simplified Chinese": "说明" },
    reading: "せつめい",
    romanization: "setsumei",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "説明を聞きます。",
    exampleTranslations: { English: "I listen to the explanation.", "Simplified Chinese": "我听说明。" },
  },
  {
    id: "ko-school-intermediate-11",
    targetLanguage: "Korean",
    targetText: "설명",
    meanings: { English: "explanation", "Simplified Chinese": "说明" },
    reading: "설명",
    romanization: "seolmyeong",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "설명을 들어요.",
    exampleTranslations: { English: "I listen to the explanation.", "Simplified Chinese": "我听说明。" },
  },
  {
    id: "ja-school-intermediate-12",
    targetLanguage: "Japanese",
    targetText: "卒業",
    meanings: { English: "graduation", "Simplified Chinese": "毕业" },
    reading: "そつぎょう",
    romanization: "sotsugyo",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "来年卒業します。",
    exampleTranslations: { English: "I graduate next year.", "Simplified Chinese": "我明年毕业。" },
  },
  {
    id: "ko-school-intermediate-12",
    targetLanguage: "Korean",
    targetText: "졸업",
    meanings: { English: "graduation", "Simplified Chinese": "毕业" },
    reading: "졸업",
    romanization: "joreop",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "내년에 졸업해요.",
    exampleTranslations: { English: "I graduate next year.", "Simplified Chinese": "我明年毕业。" },
  },
  {
    id: "ja-anime-intermediate-6",
    targetLanguage: "Japanese",
    targetText: "エピソード",
    meanings: { English: "episode", "Simplified Chinese": "一集" },
    reading: "エピソード",
    romanization: "episodo",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "次のエピソードを見ます。",
    exampleTranslations: { English: "I watch the next episode.", "Simplified Chinese": "我看下一集。" },
  },
  {
    id: "ko-drama-intermediate-6",
    targetLanguage: "Korean",
    targetText: "에피소드",
    meanings: { English: "episode", "Simplified Chinese": "一集" },
    reading: "에피소드",
    romanization: "episodeu",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "다음 에피소드를 봐요.",
    exampleTranslations: { English: "I watch the next episode.", "Simplified Chinese": "我看下一集。" },
  },
  {
    id: "ja-anime-intermediate-7",
    targetLanguage: "Japanese",
    targetText: "字幕",
    meanings: { English: "subtitle", "Simplified Chinese": "字幕" },
    reading: "じまく",
    romanization: "jimaku",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "字幕をつけます。",
    exampleTranslations: { English: "I turn on subtitles.", "Simplified Chinese": "我打开字幕。" },
  },
  {
    id: "ko-drama-intermediate-7",
    targetLanguage: "Korean",
    targetText: "자막",
    meanings: { English: "subtitle", "Simplified Chinese": "字幕" },
    reading: "자막",
    romanization: "jamak",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "자막을 켜요.",
    exampleTranslations: { English: "I turn on subtitles.", "Simplified Chinese": "我打开字幕。" },
  },
  {
    id: "ja-anime-intermediate-8",
    targetLanguage: "Japanese",
    targetText: "監督",
    meanings: { English: "director", "Simplified Chinese": "导演" },
    reading: "かんとく",
    romanization: "kantoku",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "監督の名前を知っています。",
    exampleTranslations: { English: "I know the director's name.", "Simplified Chinese": "我知道导演的名字。" },
  },
  {
    id: "ko-drama-intermediate-8",
    targetLanguage: "Korean",
    targetText: "감독",
    meanings: { English: "director", "Simplified Chinese": "导演" },
    reading: "감독",
    romanization: "gamdok",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "감독 이름을 알아요.",
    exampleTranslations: { English: "I know the director's name.", "Simplified Chinese": "我知道导演的名字。" },
  },
  {
    id: "ja-anime-intermediate-9",
    targetLanguage: "Japanese",
    targetText: "俳優",
    meanings: { English: "actor", "Simplified Chinese": "演员" },
    reading: "はいゆう",
    romanization: "haiyu",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "俳優が上手です。",
    exampleTranslations: { English: "The actor performs well.", "Simplified Chinese": "演员演得很好。" },
  },
  {
    id: "ko-drama-intermediate-9",
    targetLanguage: "Korean",
    targetText: "배우",
    meanings: { English: "actor", "Simplified Chinese": "演员" },
    reading: "배우",
    romanization: "baeu",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "배우가 연기를 잘해요.",
    exampleTranslations: { English: "The actor performs well.", "Simplified Chinese": "演员演得很好。" },
  },
  {
    id: "ja-anime-intermediate-10",
    targetLanguage: "Japanese",
    targetText: "筋",
    meanings: { English: "plot", "Simplified Chinese": "剧情" },
    reading: "すじ",
    romanization: "suji",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "話の筋が面白いです。",
    exampleTranslations: { English: "The plot is interesting.", "Simplified Chinese": "剧情很有趣。" },
  },
  {
    id: "ko-drama-intermediate-10",
    targetLanguage: "Korean",
    targetText: "줄거리",
    meanings: { English: "plot", "Simplified Chinese": "剧情" },
    reading: "줄거리",
    romanization: "julgeori",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "줄거리가 재미있어요.",
    exampleTranslations: { English: "The plot is interesting.", "Simplified Chinese": "剧情很有趣。" },
  },
  {
    id: "ja-anime-intermediate-11",
    targetLanguage: "Japanese",
    targetText: "結末",
    meanings: { English: "ending", "Simplified Chinese": "结局" },
    reading: "けつまつ",
    romanization: "ketsumatsu",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "結末に驚きました。",
    exampleTranslations: { English: "I was surprised by the ending.", "Simplified Chinese": "结局让我吃惊。" },
  },
  {
    id: "ko-drama-intermediate-11",
    targetLanguage: "Korean",
    targetText: "결말",
    meanings: { English: "ending", "Simplified Chinese": "结局" },
    reading: "결말",
    romanization: "gyeolmal",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "결말에 놀랐어요.",
    exampleTranslations: { English: "I was surprised by the ending.", "Simplified Chinese": "结局让我吃惊。" },
  },
  {
    id: "ja-food-intermediate-6",
    targetLanguage: "Japanese",
    targetText: "食材",
    meanings: { English: "ingredient", "Simplified Chinese": "食材" },
    reading: "しょくざい",
    romanization: "shokuzai",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "新鮮な食材を選びます。",
    exampleTranslations: { English: "I choose fresh ingredients.", "Simplified Chinese": "我选择新鲜食材。" },
  },
  {
    id: "ko-food-intermediate-6",
    targetLanguage: "Korean",
    targetText: "식재료",
    meanings: { English: "ingredient", "Simplified Chinese": "食材" },
    reading: "식재료",
    romanization: "sikjaeryo",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "신선한 식재료를 골라요.",
    exampleTranslations: { English: "I choose fresh ingredients.", "Simplified Chinese": "我选择新鲜食材。" },
  },
  {
    id: "ja-food-intermediate-7",
    targetLanguage: "Japanese",
    targetText: "味",
    meanings: { English: "taste", "Simplified Chinese": "味道" },
    reading: "あじ",
    romanization: "aji",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "味を確認します。",
    exampleTranslations: { English: "I check the taste.", "Simplified Chinese": "我确认味道。" },
  },
  {
    id: "ko-food-intermediate-7",
    targetLanguage: "Korean",
    targetText: "맛",
    meanings: { English: "taste", "Simplified Chinese": "味道" },
    reading: "맛",
    romanization: "mat",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "맛을 확인해요.",
    exampleTranslations: { English: "I check the taste.", "Simplified Chinese": "我确认味道。" },
  },
  {
    id: "ja-food-intermediate-8",
    targetLanguage: "Japanese",
    targetText: "栄養",
    meanings: { English: "nutrition", "Simplified Chinese": "营养" },
    reading: "えいよう",
    romanization: "eiyo",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "栄養を考えます。",
    exampleTranslations: { English: "I consider nutrition.", "Simplified Chinese": "我考虑营养。" },
  },
  {
    id: "ko-food-intermediate-8",
    targetLanguage: "Korean",
    targetText: "영양",
    meanings: { English: "nutrition", "Simplified Chinese": "营养" },
    reading: "영양",
    romanization: "yeongyang",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "영양을 생각해요.",
    exampleTranslations: { English: "I consider nutrition.", "Simplified Chinese": "我考虑营养。" },
  },
  {
    id: "ja-food-intermediate-9",
    targetLanguage: "Japanese",
    targetText: "食欲",
    meanings: { English: "appetite", "Simplified Chinese": "食欲" },
    reading: "しょくよく",
    romanization: "shokuyoku",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "食欲があります。",
    exampleTranslations: { English: "I have an appetite.", "Simplified Chinese": "我有食欲。" },
  },
  {
    id: "ko-food-intermediate-9",
    targetLanguage: "Korean",
    targetText: "식욕",
    meanings: { English: "appetite", "Simplified Chinese": "食欲" },
    reading: "식욕",
    romanization: "sigyok",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "식욕이 있어요.",
    exampleTranslations: { English: "I have an appetite.", "Simplified Chinese": "我有食欲。" },
  },
  {
    id: "ja-food-intermediate-10",
    targetLanguage: "Japanese",
    targetText: "調理",
    meanings: { English: "cooking", "Simplified Chinese": "烹饪" },
    reading: "ちょうり",
    romanization: "chori",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "野菜を調理します。",
    exampleTranslations: { English: "I cook vegetables.", "Simplified Chinese": "我烹饪蔬菜。" },
  },
  {
    id: "ko-food-intermediate-10",
    targetLanguage: "Korean",
    targetText: "조리",
    meanings: { English: "cooking", "Simplified Chinese": "烹饪" },
    reading: "조리",
    romanization: "jori",
    level: "Intermediate",
    topic: "food",
    exampleSentence: "채소를 조리해요.",
    exampleTranslations: { English: "I cook vegetables.", "Simplified Chinese": "我烹饪蔬菜。" },
  },
  {
    id: "ja-travel-intermediate-6",
    targetLanguage: "Japanese",
    targetText: "乗り換え",
    meanings: { English: "transfer", "Simplified Chinese": "换乘" },
    reading: "のりかえ",
    romanization: "norikae",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "駅で乗り換えます。",
    exampleTranslations: { English: "I transfer at the station.", "Simplified Chinese": "我在车站换乘。" },
  },
  {
    id: "ko-travel-intermediate-6",
    targetLanguage: "Korean",
    targetText: "환승",
    meanings: { English: "transfer", "Simplified Chinese": "换乘" },
    reading: "환승",
    romanization: "hwanseung",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "역에서 환승해요.",
    exampleTranslations: { English: "I transfer at the station.", "Simplified Chinese": "我在车站换乘。" },
  },
  {
    id: "ja-travel-intermediate-7",
    targetLanguage: "Japanese",
    targetText: "目的地",
    meanings: { English: "destination", "Simplified Chinese": "目的地" },
    reading: "もくてきち",
    romanization: "mokutekichi",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "目的地に着きました。",
    exampleTranslations: { English: "I arrived at the destination.", "Simplified Chinese": "我到达目的地。" },
  },
  {
    id: "ko-travel-intermediate-7",
    targetLanguage: "Korean",
    targetText: "목적지",
    meanings: { English: "destination", "Simplified Chinese": "目的地" },
    reading: "목적지",
    romanization: "mokjeokji",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "목적지에 도착했어요.",
    exampleTranslations: { English: "I arrived at the destination.", "Simplified Chinese": "我到达目的地。" },
  },
  {
    id: "ja-travel-intermediate-8",
    targetLanguage: "Japanese",
    targetText: "出発",
    meanings: { English: "departure", "Simplified Chinese": "出发" },
    reading: "しゅっぱつ",
    romanization: "shuppatsu",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "出発は朝です。",
    exampleTranslations: { English: "Departure is in the morning.", "Simplified Chinese": "早上出发。" },
  },
  {
    id: "ko-travel-intermediate-8",
    targetLanguage: "Korean",
    targetText: "출발",
    meanings: { English: "departure", "Simplified Chinese": "出发" },
    reading: "출발",
    romanization: "chulbal",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "출발은 아침이에요.",
    exampleTranslations: { English: "Departure is in the morning.", "Simplified Chinese": "早上出发。" },
  },
  {
    id: "ja-travel-intermediate-9",
    targetLanguage: "Japanese",
    targetText: "到着",
    meanings: { English: "arrival", "Simplified Chinese": "到达" },
    reading: "とうちゃく",
    romanization: "tochaku",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "到着を待ちます。",
    exampleTranslations: { English: "I wait for arrival.", "Simplified Chinese": "我等待到达。" },
  },
  {
    id: "ko-travel-intermediate-9",
    targetLanguage: "Korean",
    targetText: "도착",
    meanings: { English: "arrival", "Simplified Chinese": "到达" },
    reading: "도착",
    romanization: "dochag",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "도착을 기다려요.",
    exampleTranslations: { English: "I wait for arrival.", "Simplified Chinese": "我等待到达。" },
  },
  {
    id: "ja-travel-intermediate-10",
    targetLanguage: "Japanese",
    targetText: "観光",
    meanings: { English: "sightseeing", "Simplified Chinese": "观光" },
    reading: "かんこう",
    romanization: "kanko",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "京都を観光します。",
    exampleTranslations: { English: "I go sightseeing.", "Simplified Chinese": "我去观光。" },
  },
  {
    id: "ko-travel-intermediate-10",
    targetLanguage: "Korean",
    targetText: "관광",
    meanings: { English: "sightseeing", "Simplified Chinese": "观光" },
    reading: "관광",
    romanization: "gwangwang",
    level: "Intermediate",
    topic: "travel",
    exampleSentence: "서울을 관광해요.",
    exampleTranslations: { English: "I go sightseeing.", "Simplified Chinese": "我去观光。" },
  },
  {
    id: "ja-life-intermediate-6",
    targetLanguage: "Japanese",
    targetText: "洗濯",
    meanings: { English: "laundry", "Simplified Chinese": "洗衣" },
    reading: "せんたく",
    romanization: "sentaku",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "週末に洗濯します。",
    exampleTranslations: { English: "I do laundry on weekends.", "Simplified Chinese": "我周末洗衣服。" },
  },
  {
    id: "ko-life-intermediate-6",
    targetLanguage: "Korean",
    targetText: "세탁",
    meanings: { English: "laundry", "Simplified Chinese": "洗衣" },
    reading: "세탁",
    romanization: "setak",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "주말에 세탁해요.",
    exampleTranslations: { English: "I do laundry on weekends.", "Simplified Chinese": "我周末洗衣服。" },
  },
  {
    id: "ja-life-intermediate-7",
    targetLanguage: "Japanese",
    targetText: "掃除",
    meanings: { English: "cleaning", "Simplified Chinese": "打扫" },
    reading: "そうじ",
    romanization: "soji",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "部屋を掃除します。",
    exampleTranslations: { English: "I clean the room.", "Simplified Chinese": "我打扫房间。" },
  },
  {
    id: "ko-life-intermediate-7",
    targetLanguage: "Korean",
    targetText: "청소",
    meanings: { English: "cleaning", "Simplified Chinese": "打扫" },
    reading: "청소",
    romanization: "cheongso",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "방을 청소해요.",
    exampleTranslations: { English: "I clean the room.", "Simplified Chinese": "我打扫房间。" },
  },
  {
    id: "ja-life-intermediate-8",
    targetLanguage: "Japanese",
    targetText: "予定",
    meanings: { English: "schedule", "Simplified Chinese": "日程" },
    reading: "よてい",
    romanization: "yotei",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "予定を確認します。",
    exampleTranslations: { English: "I check the schedule.", "Simplified Chinese": "我确认日程。" },
  },
  {
    id: "ko-life-intermediate-8",
    targetLanguage: "Korean",
    targetText: "일정",
    meanings: { English: "schedule", "Simplified Chinese": "日程" },
    reading: "일정",
    romanization: "iljeong",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "일정을 확인해요.",
    exampleTranslations: { English: "I check the schedule.", "Simplified Chinese": "我确认日程。" },
  },
  {
    id: "ja-life-intermediate-9",
    targetLanguage: "Japanese",
    targetText: "近所",
    meanings: { English: "neighborhood", "Simplified Chinese": "附近" },
    reading: "きんじょ",
    romanization: "kinjo",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "近所を散歩します。",
    exampleTranslations: { English: "I walk around the neighborhood.", "Simplified Chinese": "我在附近散步。" },
  },
  {
    id: "ko-life-intermediate-9",
    targetLanguage: "Korean",
    targetText: "동네",
    meanings: { English: "neighborhood", "Simplified Chinese": "附近" },
    reading: "동네",
    romanization: "dongne",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "동네를 산책해요.",
    exampleTranslations: { English: "I walk around the neighborhood.", "Simplified Chinese": "我在附近散步。" },
  },
  {
    id: "ja-life-intermediate-10",
    targetLanguage: "Japanese",
    targetText: "習慣",
    meanings: { English: "habit", "Simplified Chinese": "习惯" },
    reading: "しゅうかん",
    romanization: "shukan",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "良い習慣を作ります。",
    exampleTranslations: { English: "I build a good habit.", "Simplified Chinese": "我养成好习惯。" },
  },
  {
    id: "ko-life-intermediate-10",
    targetLanguage: "Korean",
    targetText: "습관",
    meanings: { English: "habit", "Simplified Chinese": "习惯" },
    reading: "습관",
    romanization: "seupgwan",
    level: "Intermediate",
    topic: "daily life",
    exampleSentence: "좋은 습관을 만들어요.",
    exampleTranslations: { English: "I build a good habit.", "Simplified Chinese": "我养成好习惯。" },
  },
  {
    id: "ja-work-intermediate-13",
    targetLanguage: "Japanese",
    targetText: "報告",
    meanings: { English: "report", "Simplified Chinese": "报告" },
    reading: "ほうこく",
    romanization: "hokoku",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "結果を報告します。",
    exampleTranslations: { English: "I report the result.", "Simplified Chinese": "我报告结果。" },
  },
  {
    id: "ko-work-intermediate-13",
    targetLanguage: "Korean",
    targetText: "보고",
    meanings: { English: "report", "Simplified Chinese": "报告" },
    reading: "보고",
    romanization: "bogo",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "결과를 보고해요.",
    exampleTranslations: { English: "I report the result.", "Simplified Chinese": "我报告结果。" },
  },
  {
    id: "ja-work-intermediate-14",
    targetLanguage: "Japanese",
    targetText: "相談",
    meanings: { English: "consultation", "Simplified Chinese": "商量" },
    reading: "そうだん",
    romanization: "sodan",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "上司に相談します。",
    exampleTranslations: { English: "I consult my manager.", "Simplified Chinese": "我和上司商量。" },
  },
  {
    id: "ko-work-intermediate-14",
    targetLanguage: "Korean",
    targetText: "상담",
    meanings: { English: "consultation", "Simplified Chinese": "商量" },
    reading: "상담",
    romanization: "sangdam",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "상사와 상담해요.",
    exampleTranslations: { English: "I consult my manager.", "Simplified Chinese": "我和上司商量。" },
  },
  {
    id: "ja-work-intermediate-15",
    targetLanguage: "Japanese",
    targetText: "依頼",
    meanings: { English: "request", "Simplified Chinese": "请求" },
    reading: "いらい",
    romanization: "irai",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "資料を依頼します。",
    exampleTranslations: { English: "I request the documents.", "Simplified Chinese": "我请求资料。" },
  },
  {
    id: "ko-work-intermediate-15",
    targetLanguage: "Korean",
    targetText: "요청",
    meanings: { English: "request", "Simplified Chinese": "请求" },
    reading: "요청",
    romanization: "yocheong",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "자료를 요청해요.",
    exampleTranslations: { English: "I request the documents.", "Simplified Chinese": "我请求资料。" },
  },
  {
    id: "ja-work-intermediate-16",
    targetLanguage: "Japanese",
    targetText: "進捗",
    meanings: { English: "progress", "Simplified Chinese": "进展" },
    reading: "しんちょく",
    romanization: "shinchoku",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "進捗を共有します。",
    exampleTranslations: { English: "I share progress.", "Simplified Chinese": "我分享进展。" },
  },
  {
    id: "ko-work-intermediate-16",
    targetLanguage: "Korean",
    targetText: "진행",
    meanings: { English: "progress", "Simplified Chinese": "进展" },
    reading: "진행",
    romanization: "jinhaeng",
    level: "Intermediate",
    topic: "work",
    exampleSentence: "진행 상황을 공유해요.",
    exampleTranslations: { English: "I share progress.", "Simplified Chinese": "我分享进展。" },
  },
  {
    id: "ja-school-intermediate-13",
    targetLanguage: "Japanese",
    targetText: "講義",
    meanings: { English: "lecture", "Simplified Chinese": "讲课" },
    reading: "こうぎ",
    romanization: "kogi",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "講義を受けます。",
    exampleTranslations: { English: "I attend a lecture.", "Simplified Chinese": "我听课。" },
  },
  {
    id: "ko-school-intermediate-13",
    targetLanguage: "Korean",
    targetText: "강의",
    meanings: { English: "lecture", "Simplified Chinese": "讲课" },
    reading: "강의",
    romanization: "gangui",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "강의를 들어요.",
    exampleTranslations: { English: "I attend a lecture.", "Simplified Chinese": "我听课。" },
  },
  {
    id: "ja-school-intermediate-14",
    targetLanguage: "Japanese",
    targetText: "教科書",
    meanings: { English: "textbook", "Simplified Chinese": "课本" },
    reading: "きょうかしょ",
    romanization: "kyokasho",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "教科書を開きます。",
    exampleTranslations: { English: "I open the textbook.", "Simplified Chinese": "我打开课本。" },
  },
  {
    id: "ko-school-intermediate-14",
    targetLanguage: "Korean",
    targetText: "교과서",
    meanings: { English: "textbook", "Simplified Chinese": "课本" },
    reading: "교과서",
    romanization: "gyogwaseo",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "교과서를 펴요.",
    exampleTranslations: { English: "I open the textbook.", "Simplified Chinese": "我打开课本。" },
  },
  {
    id: "ja-school-intermediate-15",
    targetLanguage: "Japanese",
    targetText: "欠席",
    meanings: { English: "absence", "Simplified Chinese": "缺席" },
    reading: "けっせき",
    romanization: "kesseki",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "今日は欠席です。",
    exampleTranslations: { English: "I am absent today.", "Simplified Chinese": "我今天缺席。" },
  },
  {
    id: "ko-school-intermediate-15",
    targetLanguage: "Korean",
    targetText: "결석",
    meanings: { English: "absence", "Simplified Chinese": "缺席" },
    reading: "결석",
    romanization: "gyeolseok",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "오늘은 결석이에요.",
    exampleTranslations: { English: "I am absent today.", "Simplified Chinese": "我今天缺席。" },
  },
  {
    id: "ja-school-intermediate-16",
    targetLanguage: "Japanese",
    targetText: "成績",
    meanings: { English: "grade", "Simplified Chinese": "成绩" },
    reading: "せいせき",
    romanization: "seiseki",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "成績が上がりました。",
    exampleTranslations: { English: "My grade improved.", "Simplified Chinese": "我的成绩提高了。" },
  },
  {
    id: "ko-school-intermediate-16",
    targetLanguage: "Korean",
    targetText: "성적",
    meanings: { English: "grade", "Simplified Chinese": "成绩" },
    reading: "성적",
    romanization: "seongjeok",
    level: "Intermediate",
    topic: "school",
    exampleSentence: "성적이 올랐어요.",
    exampleTranslations: { English: "My grade improved.", "Simplified Chinese": "我的成绩提高了。" },
  },
  {
    id: "ja-anime-intermediate-12",
    targetLanguage: "Japanese",
    targetText: "脚本",
    meanings: { English: "script", "Simplified Chinese": "剧本" },
    reading: "きゃくほん",
    romanization: "kyakuhon",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "脚本を読みます。",
    exampleTranslations: { English: "I read the script.", "Simplified Chinese": "我读剧本。" },
  },
  {
    id: "ko-drama-intermediate-12",
    targetLanguage: "Korean",
    targetText: "대본",
    meanings: { English: "script", "Simplified Chinese": "剧本" },
    reading: "대본",
    romanization: "daebon",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "대본을 읽어요.",
    exampleTranslations: { English: "I read the script.", "Simplified Chinese": "我读剧本。" },
  },
  {
    id: "ja-anime-intermediate-13",
    targetLanguage: "Japanese",
    targetText: "演出",
    meanings: { English: "direction", "Simplified Chinese": "演出" },
    reading: "えんしゅつ",
    romanization: "enshutsu",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "演出が印象的です。",
    exampleTranslations: { English: "The direction is impressive.", "Simplified Chinese": "演出令人印象深刻。" },
  },
  {
    id: "ko-drama-intermediate-13",
    targetLanguage: "Korean",
    targetText: "연출",
    meanings: { English: "direction", "Simplified Chinese": "演出" },
    reading: "연출",
    romanization: "yeonchul",
    level: "Intermediate",
    topic: "anime/drama",
    exampleSentence: "연출이 인상적이에요.",
    exampleTranslations: { English: "The direction is impressive.", "Simplified Chinese": "演出令人印象深刻。" },
  }
];
