import type { Topic, VocabItem } from "./vocabulary";

// Curated Basic expansion: 250 standalone concepts x Japanese/Korean = 500 entries.
// High-frequency standalone vocabulary only; no modifier+noun combinatorial filler.
type BasicRow = [topic: Topic, pos: "noun" | "verb", en: string, zh: string, ja: string, jaReading: string, jaRomanization: string, ko: string];

const rows: BasicRow[] = [
  ["food", "noun", "pepper", "胡椒", "胡椒", "こしょう", "koshou", "후추"],
  ["food", "noun", "vinegar", "醋", "酢", "す", "su", "식초"],
  ["food", "noun", "flour", "面粉", "小麦粉", "こむぎこ", "komugiko", "밀가루"],
  ["food", "noun", "noodles", "面条", "麺", "めん", "men", "면"],
  ["food", "noun", "udon", "乌冬面", "うどん", "うどん", "udon", "우동"],
  ["food", "noun", "somen", "素面", "そうめん", "そうめん", "soumen", "소면"],
  ["food", "noun", "seaweed", "海苔", "海苔", "のり", "nori", "김"],
  ["food", "noun", "wakame", "裙带菜", "わかめ", "わかめ", "wakame", "미역"],
  ["food", "noun", "mushroom", "蘑菇", "きのこ", "きのこ", "kinoko", "버섯"],
  ["food", "noun", "onion", "洋葱", "玉ねぎ", "たまねぎ", "tamanegi", "양파"],
  ["food", "noun", "carrot", "胡萝卜", "にんじん", "にんじん", "ninjin", "당근"],
  ["food", "noun", "potato", "土豆", "じゃがいも", "じゃがいも", "jagaimo", "감자"],
  ["food", "noun", "tomato", "番茄", "トマト", "とまと", "tomato", "토마토"],
  ["food", "noun", "cucumber", "黄瓜", "きゅうり", "きゅうり", "kyuuri", "오이"],
  ["food", "noun", "cabbage", "卷心菜", "キャベツ", "きゃべつ", "kyabetsu", "양배추"],
  ["food", "noun", "lettuce", "生菜", "レタス", "れたす", "retasu", "양상추"],
  ["food", "noun", "green onion", "葱", "ねぎ", "ねぎ", "negi", "파"],
  ["food", "noun", "garlic", "大蒜", "にんにく", "にんにく", "ninniku", "마늘"],
  ["food", "noun", "ginger", "姜", "生姜", "しょうが", "shouga", "생강"],
  ["food", "noun", "strawberry", "草莓", "いちご", "いちご", "ichigo", "딸기"],
  ["food", "noun", "grape", "葡萄", "ぶどう", "ぶどう", "budou", "포도"],
  ["food", "noun", "peach", "桃子", "桃", "もも", "momo", "복숭아"],
  ["food", "noun", "banana", "香蕉", "バナナ", "ばなな", "banana", "바나나"],
  ["food", "noun", "lemon", "柠檬", "レモン", "れもん", "remon", "레몬"],
  ["food", "noun", "honey", "蜂蜜", "蜂蜜", "はちみつ", "hachimitsu", "꿀"],
  ["food", "noun", "jam", "果酱", "ジャム", "じゃむ", "jamu", "잼"],
  ["food", "noun", "butter", "黄油", "バター", "ばたー", "bataa", "버터"],
  ["food", "noun", "cheese", "奶酪", "チーズ", "ちーず", "chiizu", "치즈"],
  ["food", "noun", "yogurt", "酸奶", "ヨーグルト", "よーぐると", "yooguruto", "요거트"],
  ["food", "noun", "sausage", "香肠", "ソーセージ", "そーせーじ", "sooseeji", "소시지"],
  ["food", "noun", "ham", "火腿", "ハム", "はむ", "hamu", "햄"],
  ["food", "noun", "chicken", "鸡肉", "鶏肉", "とりにく", "toriniku", "닭고기"],
  ["food", "noun", "pork", "猪肉", "豚肉", "ぶたにく", "butaniku", "돼지고기"],
  ["food", "noun", "beef", "牛肉", "牛肉", "ぎゅうにく", "gyuuniku", "소고기"],
  ["food", "noun", "shrimp", "虾", "海老", "えび", "ebi", "새우"],
  ["travel", "noun", "ticket gate", "检票口", "改札", "かいさつ", "kaisatsu", "개찰구"],
  ["travel", "noun", "fare", "票价", "運賃", "うんちん", "unchin", "운임"],
  ["travel", "noun", "route", "路线", "路線", "ろせん", "rosen", "노선"],
  ["travel", "noun", "station staff", "车站工作人员", "駅員", "えきいん", "ekiin", "역무원"],
  ["travel", "noun", "timetable", "时刻表", "時刻表", "じこくひょう", "jikokuhyou", "시간표"],
  ["travel", "noun", "boarding area", "乘车处", "乗り場", "のりば", "noriba", "승차장"],
  ["travel", "noun", "stairs", "楼梯", "階段", "かいだん", "kaidan", "계단"],
  ["travel", "noun", "elevator", "电梯", "エレベーター", "えれべーたー", "erebeetaa", "엘리베이터"],
  ["travel", "noun", "escalator", "自动扶梯", "エスカレーター", "えすかれーたー", "esukareetaa", "에스컬레이터"],
  ["travel", "noun", "address", "地址", "住所", "じゅうしょ", "juusho", "주소"],
  ["travel", "noun", "sidewalk", "人行道", "歩道", "ほどう", "hodou", "보도"],
  ["travel", "noun", "port", "港口", "港", "みなと", "minato", "항구"],
  ["travel", "noun", "driver", "司机", "運転手", "うんてんしゅ", "untenshu", "운전기사"],
  ["travel", "noun", "reservation", "预约", "予約", "よやく", "yoyaku", "예약"],
  ["travel", "noun", "customs", "海关", "税関", "ぜいかん", "zeikan", "세관"],
  ["travel", "noun", "inspection", "检查", "検査", "けんさ", "kensa", "검사"],
  ["travel", "noun", "arrival", "到达", "到着", "とうちゃく", "touchaku", "도착"],
  ["travel", "noun", "departure", "出发", "出発", "しゅっぱつ", "shuppatsu", "출발"],
  ["travel", "noun", "domestic flight", "国内航班", "国内線", "こくないせん", "kokunaisen", "국내선"],
  ["travel", "noun", "international flight", "国际航班", "国際線", "こくさいせん", "kokusaisen", "국제선"],
  ["travel", "noun", "service counter", "柜台", "窓口", "まどぐち", "madoguchi", "창구"],
  ["travel", "noun", "one way", "单程", "片道", "かたみち", "katamichi", "편도"],
  ["travel", "noun", "round trip", "往返", "往復", "おうふく", "oufuku", "왕복"],
  ["travel", "noun", "seat", "座位", "座席", "ざせき", "zaseki", "좌석"],
  ["travel", "noun", "aisle", "通道", "通路", "つうろ", "tsuuro", "통로"],
  ["travel", "noun", "window seat", "靠窗座位", "窓側", "まどがわ", "madogawa", "창가"],
  ["travel", "noun", "information desk", "问讯处", "案内所", "あんないじょ", "annaijo", "안내소"],
  ["travel", "noun", "sightseeing", "观光", "観光", "かんこう", "kankou", "관광"],
  ["travel", "noun", "Japanese inn", "日式旅馆", "旅館", "りょかん", "ryokan", "료칸"],
  ["travel", "noun", "lodging", "住宿处", "宿", "やど", "yado", "숙소"],
  ["travel", "noun", "reception", "前台", "受付", "うけつけ", "uketsuke", "접수처"],
  ["travel", "noun", "gasoline", "汽油", "ガソリン", "がそりん", "gasorin", "휘발유"],
  ["travel", "noun", "road", "道路", "道路", "どうろ", "douro", "도로"],
  ["travel", "noun", "highway", "高速公路", "高速道路", "こうそくどうろ", "kousokudouro", "고속도로"],
  ["travel", "noun", "bus stop", "公交站", "バス停", "ばすてい", "basutei", "버스정류장"],
  ["daily life", "noun", "watch", "手表", "腕時計", "うでどけい", "udedokei", "손목시계"],
  ["daily life", "noun", "bag", "袋子", "袋", "ふくろ", "fukuro", "봉투"],
  ["daily life", "noun", "box", "盒子", "箱", "はこ", "hako", "상자"],
  ["daily life", "noun", "bottle", "瓶子", "瓶", "かめ", "kame", "병"],
  ["daily life", "noun", "can", "罐", "缶", "かん", "kan", "캔"],
  ["daily life", "noun", "paper", "纸", "紙", "かみ", "kami", "종이"],
  ["daily life", "noun", "notebook", "笔记本", "ノート", "のーと", "nooto", "공책"],
  ["daily life", "noun", "pencil", "铅笔", "鉛筆", "えんぴつ", "enpitsu", "연필"],
  ["daily life", "noun", "eraser", "橡皮", "消しゴム", "けしごむ", "keshigomu", "지우개"],
  ["daily life", "noun", "scissors", "剪刀", "はさみ", "はさみ", "hasami", "가위"],
  ["daily life", "noun", "ruler", "尺子", "定規", "じょうぎ", "jougi", "자"],
  ["daily life", "noun", "shelf", "架子", "棚", "たな", "tana", "선반"],
  ["daily life", "noun", "drawer", "抽屉", "引き出し", "ひきだし", "hikidashi", "서랍"],
  ["daily life", "noun", "rice cooker", "电饭锅", "炊飯器", "すいはんき", "suihanki", "밥솥"],
  ["daily life", "noun", "fan", "电风扇", "扇風機", "せんぷうき", "senpuuki", "선풍기"],
  ["daily life", "noun", "heater", "暖气", "暖房", "だんぼう", "danbou", "난방"],
  ["daily life", "noun", "air conditioning", "空调", "冷房", "れいぼう", "reibou", "냉방"],
  ["daily life", "noun", "kitchen", "厨房", "台所", "だいどころ", "daidokoro", "부엌"],
  ["daily life", "noun", "entryway", "玄关", "玄関", "げんかん", "genkan", "현관"],
  ["daily life", "noun", "hallway", "走廊", "廊下", "ろうか", "rouka", "복도"],
  ["daily life", "noun", "balcony", "阳台", "ベランダ", "べらんだ", "beranda", "베란다"],
  ["daily life", "noun", "roof", "屋顶", "屋根", "やね", "yane", "지붕"],
  ["daily life", "noun", "garden", "院子", "庭", "にわ", "niwa", "마당"],
  ["daily life", "noun", "detergent", "洗涤剂", "洗剤", "せんざい", "senzai", "세제"],
  ["daily life", "noun", "toothpaste", "牙膏", "歯磨き粉", "はみがきこ", "hamigakiko", "치약"],
  ["daily life", "noun", "blanket", "毛毯", "毛布", "もうふ", "moufu", "담요"],
  ["daily life", "noun", "pillow", "枕头", "枕", "まくら", "makura", "베개"],
  ["daily life", "noun", "futon", "被褥", "布団", "ふとん", "futon", "이불"],
  ["daily life", "noun", "socks", "袜子", "靴下", "くつした", "kutsushita", "양말"],
  ["daily life", "noun", "hat", "帽子", "帽子", "ぼうし", "boushi", "모자"],
  ["daily life", "noun", "gloves", "手套", "手袋", "てぶくろ", "tebukuro", "장갑"],
  ["daily life", "noun", "ring", "戒指", "指輪", "ゆびわ", "yubiwa", "반지"],
  ["daily life", "noun", "necklace", "项链", "ネックレス", "ねっくれす", "nekkuresu", "목걸이"],
  ["daily life", "noun", "pocket", "口袋", "ポケット", "ぽけっと", "poketto", "주머니"],
  ["daily life", "noun", "button", "纽扣", "ボタン", "ぼたん", "botan", "단추"],
  ["daily life", "noun", "zipper", "拉链", "ファスナー", "ふぁすなー", "fasunaa", "지퍼"],
  ["daily life", "noun", "comb", "梳子", "くし", "くし", "kushi", "빗"],
  ["daily life", "noun", "hair dryer", "吹风机", "ドライヤー", "どらいやー", "doraiyaa", "헤어드라이어"],
  ["daily life", "noun", "shampoo", "洗发水", "シャンプー", "しゃんぷー", "shanpuu", "샴푸"],
  ["daily life", "noun", "tissue", "纸巾", "ティッシュ", "てぃっしゅ", "teisshu", "휴지"],
  ["daily life", "noun", "thermometer", "体温计", "体温計", "たいおんけい", "taionkei", "체온계"],
  ["daily life", "noun", "cold", "感冒", "風邪", "かぜ", "kaze", "감기"],
  ["daily life", "noun", "cough", "咳嗽", "咳", "せき", "seki", "기침"],
  ["daily life", "noun", "pain", "疼痛", "痛み", "いたみ", "itami", "통증"],
  ["daily life", "noun", "wound", "伤口", "傷", "きず", "kizu", "상처"],
  ["daily life", "noun", "illness", "疾病", "病気", "びょうき", "byouki", "질병"],
  ["daily life", "noun", "health", "健康", "健康", "けんこう", "kenkou", "건강"],
  ["daily life", "noun", "exercise", "运动", "運動", "うんどう", "undou", "운동"],
  ["daily life", "noun", "walk", "散步", "散歩", "さんぽ", "sanpo", "산책"],
  ["daily life", "noun", "break", "休息", "休憩", "きゅうけい", "kyuukei", "휴식"],
  ["daily life", "noun", "weekday", "工作日", "平日", "へいじつ", "heijitsu", "평일"],
  ["daily life", "noun", "weekend", "周末", "週末", "しゅうまつ", "shuumatsu", "주말"],
  ["daily life", "noun", "evening", "傍晚", "夕方", "ゆうがた", "yuugata", "저녁때"],
  ["daily life", "noun", "snow", "雪", "雪", "ゆき", "yuki", "눈"],
  ["daily life", "noun", "wind", "风", "風", "かぜ", "kaze", "바람"],
  ["daily life", "noun", "cloud", "云", "雲", "くも", "kumo", "구름"],
  ["daily life", "noun", "sunny weather", "晴天", "晴れ", "はれ", "hare", "맑음"],
  ["daily life", "noun", "cloudy weather", "阴天", "曇り", "くもり", "kumori", "흐림"],
  ["daily life", "noun", "temperature", "温度", "温度", "おんど", "ondo", "온도"],
  ["daily life", "noun", "season", "季节", "季節", "きせつ", "kisetsu", "계절"],
  ["work", "noun", "schedule", "日程", "予定", "よてい", "yotei", "일정"],
  ["work", "noun", "contact", "联络", "連絡", "れんらく", "renraku", "연락"],
  ["work", "noun", "reply", "回复", "返信", "へんしん", "henshin", "답장"],
  ["work", "noun", "material", "资料", "資料", "しりょう", "shiryou", "자료"],
  ["work", "noun", "document", "文件", "書類", "しょるい", "shorui", "서류"],
  ["work", "noun", "office", "办公室", "事務所", "じむしょ", "jimusho", "사무실"],
  ["work", "noun", "leave", "休假", "休暇", "きゅうか", "kyuuka", "휴가"],
  ["work", "noun", "salary", "工资", "給料", "きゅうりょう", "kyuuryou", "월급"],
  ["work", "noun", "customer", "顾客", "客", "きゃく", "kyaku", "고객"],
  ["work", "noun", "order", "订单", "注文", "ちゅうもん", "chuumon", "주문"],
  ["work", "noun", "email", "电子邮件", "メール", "めーる", "meeru", "이메일"],
  ["work", "noun", "computer", "电脑", "パソコン", "ぱそこん", "pasokon", "컴퓨터"],
  ["work", "noun", "screen", "屏幕", "画面", "がめん", "gamen", "화면"],
  ["work", "noun", "file", "文件", "ファイル", "ふぁいる", "fairu", "파일"],
  ["work", "noun", "folder", "文件夹", "フォルダ", "ふぉるだ", "foruda", "폴더"],
  ["work", "noun", "printing", "打印", "印刷", "いんさつ", "insatsu", "인쇄"],
  ["work", "noun", "copy", "复印件", "コピー", "こぴー", "kopii", "복사본"],
  ["work", "noun", "signature", "签名", "署名", "しょめい", "shomei", "서명"],
  ["work", "noun", "deadline", "期限", "期限", "きげん", "kigen", "기한"],
  ["work", "noun", "department", "部门", "部署", "ぶしょ", "busho", "부서"],
  ["work", "noun", "employee", "员工", "社員", "しゃいん", "shain", "사원"],
  ["work", "noun", "interview", "面试", "面接", "めんせつ", "mensetsu", "면접"],
  ["work", "noun", "resume", "简历", "履歴書", "りれきしょ", "rirekisho", "이력서"],
  ["work", "noun", "business card", "名片", "名刺", "めいし", "meishi", "명함"],
  ["work", "noun", "uniform", "制服", "制服", "せいふく", "seifuku", "유니폼"],
  ["work", "noun", "shift", "班次", "シフト", "しふと", "shifuto", "근무조"],
  ["work", "noun", "attendance", "出勤", "出勤", "しゅっきん", "shukkin", "출근"],
  ["work", "noun", "clock-out", "下班打卡", "退勤", "たいきん", "taikin", "퇴근"],
  ["work", "noun", "meeting room", "会议室", "会議室", "かいぎしつ", "kaigishitsu", "회의실"],
  ["work", "noun", "break room", "休息室", "休憩室", "きゅうけいしつ", "kyuukeishitsu", "휴게실"],
  ["school", "noun", "textbook", "教科书", "教科書", "きょうかしょ", "kyoukasho", "교과서"],
  ["school", "noun", "dictionary", "词典", "辞書", "じしょ", "jisho", "사전"],
  ["school", "noun", "homework", "作业", "宿題", "しゅくだい", "shukudai", "숙제"],
  ["school", "noun", "exam", "考试", "試験", "しけん", "shiken", "시험"],
  ["school", "noun", "grade", "成绩", "成績", "せいせき", "seiseki", "성적"],
  ["school", "noun", "classroom", "教室", "教室", "きょうしつ", "kyoushitsu", "교실"],
  ["school", "noun", "library", "图书馆", "図書館", "としょかん", "toshokan", "도서관"],
  ["school", "noun", "gymnasium", "体育馆", "体育館", "たいいくかん", "taiikukan", "체육관"],
  ["school", "noun", "schoolyard", "操场", "校庭", "こうてい", "koutei", "운동장"],
  ["school", "noun", "classmate", "同班同学", "同級生", "どうきゅうせい", "doukyuusei", "반 친구"],
  ["school", "noun", "senior student", "前辈", "先輩", "せんぱい", "senpai", "선배"],
  ["school", "noun", "junior student", "后辈", "後輩", "こうはい", "kouhai", "후배"],
  ["school", "noun", "school year", "年级", "学年", "がくねん", "gakunen", "학년"],
  ["school", "noun", "class", "课程", "授業", "じゅぎょう", "jugyou", "수업"],
  ["school", "noun", "question", "问题", "質問", "しつもん", "shitsumon", "질문"],
  ["school", "noun", "answer", "答案", "答え", "こたえ", "kotae", "답"],
  ["school", "noun", "practice", "练习", "練習", "れんしゅう", "renshuu", "연습"],
  ["school", "noun", "review", "复习", "復習", "ふくしゅう", "fukushuu", "복습"],
  ["school", "noun", "preparation", "预习", "予習", "よしゅう", "yoshuu", "예습"],
  ["school", "noun", "assignment", "课题", "課題", "かだい", "kadai", "과제"],
  ["school", "noun", "composition", "作文", "作文", "さくぶん", "sakubun", "작문"],
  ["school", "noun", "presentation", "发表", "発表", "はっぴょう", "happyou", "발표"],
  ["school", "noun", "mathematics", "数学", "数学", "すうがく", "suugaku", "수학"],
  ["school", "noun", "science", "理科", "理科", "りか", "rika", "과학"],
  ["school", "noun", "history", "历史", "歴史", "れきし", "rekishi", "역사"],
  ["school", "noun", "geography", "地理", "地理", "ちり", "chiri", "지리"],
  ["school", "noun", "music", "音乐", "音楽", "おんがく", "ongaku", "음악"],
  ["school", "noun", "art", "美术", "美術", "びじゅつ", "bijutsu", "미술"],
  ["school", "noun", "physical education", "体育", "体育", "たいいく", "taiiku", "체육"],
  ["school", "noun", "study abroad", "留学", "留学", "りゅうがく", "ryuugaku", "유학"],
  ["anime/drama", "noun", "main character", "主角", "主人公", "しゅじんこう", "shujinkou", "주인공"],
  ["anime/drama", "noun", "heroine", "女主角", "ヒロイン", "ひろいん", "hiroin", "여주인공"],
  ["anime/drama", "noun", "villain", "反派", "悪役", "あくやく", "akuyaku", "악역"],
  ["anime/drama", "noun", "voice actor", "声优", "声優", "せいゆう", "seiyuu", "성우"],
  ["anime/drama", "noun", "manga", "漫画", "漫画", "まんが", "manga", "만화"],
  ["anime/drama", "noun", "movie", "电影", "映画", "えいが", "eiga", "영화"],
  ["anime/drama", "noun", "drama", "电视剧", "ドラマ", "どらま", "dorama", "드라마"],
  ["anime/drama", "noun", "program", "节目", "番組", "ばんぐみ", "bangumi", "프로그램"],
  ["anime/drama", "noun", "scene", "场景", "場面", "ばめん", "bamen", "장면"],
  ["anime/drama", "noun", "line", "台词", "台詞", "せりふ", "serifu", "대사"],
  ["anime/drama", "noun", "work", "作品", "作品", "さくひん", "sakuhin", "작품"],
  ["anime/drama", "noun", "author", "作者", "作者", "さくしゃ", "sakusha", "작가"],
  ["anime/drama", "noun", "director", "导演", "監督", "かんとく", "kantoku", "감독"],
  ["anime/drama", "noun", "character", "角色", "キャラクター", "きゃらくたー", "kyarakutaa", "캐릭터"],
  ["anime/drama", "noun", "story", "故事", "物語", "ものがたり", "monogatari", "이야기"],
  ["common verbs", "verb", "to put", "放置", "置く", "おく", "oku", "놓다"],
  ["common verbs", "verb", "to take", "拿取", "取る", "とる", "toru", "가져가다"],
  ["common verbs", "verb", "to hold", "拿着", "持つ", "もつ", "motsu", "들다"],
  ["common verbs", "verb", "to put in", "放入", "入れる", "いれる", "ireru", "넣다"],
  ["common verbs", "verb", "to take out", "拿出", "出す", "だす", "dasu", "꺼내다"],
  ["common verbs", "verb", "to make", "制作", "作る", "つくる", "tsukuru", "만들다"],
  ["common verbs", "verb", "to clean", "打扫", "掃除する", "そうじする", "soujisuru", "청소하다"],
  ["common verbs", "verb", "to cook", "做饭", "料理する", "りょうりする", "ryourisuru", "요리하다"],
  ["common verbs", "verb", "to wear", "穿上衣", "着る", "きる", "kiru", "입다"],
  ["common verbs", "verb", "to take off", "脱下", "脱ぐ", "ぬぐ", "nugu", "벗다"],
  ["common verbs", "verb", "to put on shoes", "穿鞋", "履く", "はく", "haku", "신다"],
  ["common verbs", "verb", "to get on", "乘坐", "乗る", "のる", "noru", "타다"],
  ["common verbs", "verb", "to turn", "转弯", "曲がる", "まがる", "magaru", "돌다"],
  ["common verbs", "verb", "to cross", "穿过", "渡る", "わたる", "wataru", "건너다"],
  ["common verbs", "verb", "to stop", "停下", "止まる", "とまる", "tomaru", "멈추다"],
  ["common verbs", "verb", "to move", "移动", "動く", "うごく", "ugoku", "움직이다"],
  ["common verbs", "verb", "to hurry", "赶快", "急ぐ", "いそぐ", "isogu", "서두르다"],
  ["common verbs", "verb", "to be late", "迟到", "遅れる", "おくれる", "okureru", "늦다"],
  ["common verbs", "verb", "to call", "叫/呼叫", "呼ぶ", "よぶ", "yobu", "부르다"],
  ["common verbs", "verb", "to answer", "回答", "答える", "こたえる", "kotaeru", "대답하다"],
  ["common verbs", "verb", "to show", "展示", "見せる", "みせる", "miseru", "보여주다"],
  ["common verbs", "verb", "to forget", "忘记", "忘れる", "わすれる", "wasureru", "잊다"],
  ["common verbs", "verb", "to practice", "练习", "練習する", "れんしゅうする", "renshuusuru", "연습하다"],
  ["common verbs", "verb", "to begin", "开始", "始める", "はじめる", "hajimeru", "시작하다"],
  ["common verbs", "verb", "to finish", "结束", "終わる", "おわる", "owaru", "끝나다"],
  ["common verbs", "verb", "to continue", "继续", "続ける", "つづける", "tsuzukeru", "계속하다"],
  ["common verbs", "verb", "to choose", "选择", "選ぶ", "えらぶ", "erabu", "고르다"],
  ["common verbs", "verb", "to decide", "决定", "決める", "きめる", "kimeru", "정하다"],
  ["common verbs", "verb", "to change", "改变", "変える", "かえる", "kaeru", "바꾸다"],
  ["common verbs", "verb", "to fix", "修理", "直す", "なおす", "naosu", "고치다"],
  ["common verbs", "verb", "to throw away", "扔掉", "捨てる", "すてる", "suteru", "버리다"],
  ["common verbs", "verb", "to pick up", "捡起", "拾う", "ひろう", "hirou", "줍다"],
  ["common verbs", "verb", "to lend", "借出", "貸す", "かす", "kasu", "빌려주다"],
  ["common verbs", "verb", "to borrow", "借入", "借りる", "かりる", "kariru", "빌리다"],
  ["common verbs", "verb", "to return", "归还", "返す", "かえす", "kaesu", "돌려주다"],
  ["common verbs", "verb", "to send", "发送", "送る", "おくる", "okuru", "보내다"],
  ["common verbs", "verb", "to arrive", "送达", "届く", "とどく", "todoku", "도착하다"],
  ["common verbs", "verb", "to pay", "付款", "払う", "はらう", "harau", "지불하다"],
  ["common verbs", "verb", "to sell", "出售", "売る", "うる", "uru", "팔다"],
  ["common verbs", "verb", "to walk", "走路", "歩く", "あるく", "aruku", "걷다"],
  ["common verbs", "verb", "to sing", "唱歌", "歌う", "うたう", "utau", "노래하다"],
  ["common verbs", "verb", "to think", "想", "思う", "おもう", "omou", "생각하다"],
  ["common verbs", "verb", "to understand", "明白", "分かる", "わかる", "wakaru", "이해하다"],
  ["common verbs", "verb", "to need", "需要", "要る", "いる", "iru", "필요하다"],
  ["common verbs", "verb", "to help", "帮忙", "手伝う", "てつだう", "tetsudau", "돕다"],
];

export const basicCuratedExpansion: VocabItem[] = rows.flatMap(([topic, pos, en, zh, ja, jaReading, jaRomanization, ko], index) => {
  const suffix = String(index + 1).padStart(3, "0");
  return [
    { id: `ja-basic-curated-${suffix}`, targetLanguage: "Japanese", targetText: ja, meanings: { English: en, "Simplified Chinese": zh }, reading: jaReading, romanization: jaRomanization, level: "Basic", topic, exampleSentence: `「${ja}」を覚えます。`, exampleTranslations: { English: `I am learning the word “${en}”.`, "Simplified Chinese": `我在学习“${zh}”这个词。` } },
    { id: `ko-basic-curated-${suffix}`, targetLanguage: "Korean", targetText: ko, meanings: { English: en, "Simplified Chinese": zh }, reading: ko, romanization: "", level: "Basic", topic, exampleSentence: `“${ko}”라는 단어를 배워요.`, exampleTranslations: { English: `I am learning the word “${en}”.`, "Simplified Chinese": `我在学习“${zh}”这个词。` } },
  ];
});
