import type { VocabItem } from "./vocabulary";

export const advancedVocab: VocabItem[] = [
  {
    id: "ja-jlpt-advanced-1",
    targetLanguage: "Japanese",
    targetText: "恐縮",
    meanings: { English: "obliged", "Simplified Chinese": "抱歉" },
    reading: "きょうしゅく",
    romanization: "kyoshuku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "お手数をおかけして恐縮です。",
    exampleTranslations: {
      English: "I am sorry to trouble you.",
      "Simplified Chinese": "给您添麻烦，我很不好意思。",
  },
  },
  {
    id: "ja-jlpt-advanced-2",
    targetLanguage: "Japanese",
    targetText: "曖昧",
    meanings: { English: "vague", "Simplified Chinese": "模糊" },
    reading: "あいまい",
    romanization: "aimai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "説明が曖昧でした。",
    exampleTranslations: { English: "The explanation was vague.", "Simplified Chinese": "说明很模糊。" },
  },
  {
    id: "ja-jlpt-advanced-3",
    targetLanguage: "Japanese",
    targetText: "促す",
    meanings: { English: "urge", "Simplified Chinese": "催促" },
    reading: "うながす",
    romanization: "unagasu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "先生は学生に発言を促しました。",
    exampleTranslations: {
      English: "The teacher encouraged the students to speak.",
      "Simplified Chinese": "老师鼓励学生发言。",
  },
  },
  {
    id: "ko-topik-advanced-1",
    targetLanguage: "Korean",
    targetText: "유지하다",
    meanings: { English: "maintain", "Simplified Chinese": "维持" },
    reading: "유지하다",
    romanization: "yujihada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "건강한 습관을 유지해야 합니다.",
    exampleTranslations: {
      English: "You should maintain healthy habits.",
      "Simplified Chinese": "应该维持健康的习惯。",
  },
  },
  {
    id: "ko-topik-advanced-2",
    targetLanguage: "Korean",
    targetText: "모호하다",
    meanings: { English: "vague", "Simplified Chinese": "模糊" },
    reading: "모호하다",
    romanization: "mohohada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "설명이 모호했어요.",
    exampleTranslations: { English: "The explanation was vague.", "Simplified Chinese": "说明很模糊。" },
  },
  {
    id: "ko-topik-advanced-3",
    targetLanguage: "Korean",
    targetText: "촉구하다",
    meanings: { English: "urge", "Simplified Chinese": "敦促" },
    reading: "촉구하다",
    romanization: "chokguhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "전문가들은 대책을 촉구했습니다.",
    exampleTranslations: {
      English: "Experts called for countermeasures.",
      "Simplified Chinese": "专家们敦促采取对策。",
  },
  },
  {
    id: "ja-jlpt-advanced-4",
    targetLanguage: "Japanese",
    targetText: "著しい",
    meanings: { English: "remarkable", "Simplified Chinese": "显著的" },
    reading: "いちじるしい",
    romanization: "ichijirushii",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "著しい変化がありました。",
    exampleTranslations: { English: "There was a significant change.", "Simplified Chinese": "发生了显著变化。" },
  },
  {
    id: "ja-jlpt-advanced-5",
    targetLanguage: "Japanese",
    targetText: "推移",
    meanings: { English: "transition", "Simplified Chinese": "变化趋势" },
    reading: "すいい",
    romanization: "suii",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "人口の推移を調べます。",
    exampleTranslations: { English: "I examine population trends.", "Simplified Chinese": "我调查人口变化趋势。" },
  },
  {
    id: "ja-jlpt-advanced-6",
    targetLanguage: "Japanese",
    targetText: "措置",
    meanings: { English: "measure", "Simplified Chinese": "措施" },
    reading: "そち",
    romanization: "sochi",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "早急な措置が必要です。",
    exampleTranslations: { English: "Urgent measures are necessary.", "Simplified Chinese": "需要紧急措施。" },
  },
  {
    id: "ja-jlpt-advanced-7",
    targetLanguage: "Japanese",
    targetText: "矛盾",
    meanings: { English: "contradiction", "Simplified Chinese": "矛盾" },
    reading: "むじゅん",
    romanization: "mujun",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "その説明には矛盾があります。",
    exampleTranslations: { English: "There is a contradiction in that explanation.", "Simplified Chinese": "那个说明有矛盾。" },
  },
  {
    id: "ja-jlpt-advanced-8",
    targetLanguage: "Japanese",
    targetText: "考慮",
    meanings: { English: "consideration", "Simplified Chinese": "考虑" },
    reading: "こうりょ",
    romanization: "koryo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "安全を考慮します。",
    exampleTranslations: { English: "I take safety into consideration.", "Simplified Chinese": "我会考虑安全。" },
  },
  {
    id: "ko-topik-advanced-4",
    targetLanguage: "Korean",
    targetText: "현저하다",
    meanings: { English: "remarkable", "Simplified Chinese": "显著" },
    reading: "현저하다",
    romanization: "hyeonjeohada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "현저한 변화가 있었어요.",
    exampleTranslations: { English: "There was a significant change.", "Simplified Chinese": "发生了显著变化。" },
  },
  {
    id: "ko-topik-advanced-5",
    targetLanguage: "Korean",
    targetText: "추이",
    meanings: { English: "trend", "Simplified Chinese": "变化趋势" },
    reading: "추이",
    romanization: "chui",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "인구 추이를 조사합니다.",
    exampleTranslations: { English: "I examine population trends.", "Simplified Chinese": "我调查人口变化趋势。" },
  },
  {
    id: "ko-topik-advanced-6",
    targetLanguage: "Korean",
    targetText: "조치",
    meanings: { English: "measure", "Simplified Chinese": "措施" },
    reading: "조치",
    romanization: "jochi",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "긴급한 조치가 필요합니다.",
    exampleTranslations: { English: "Urgent measures are necessary.", "Simplified Chinese": "需要紧急措施。" },
  },
  {
    id: "ko-topik-advanced-7",
    targetLanguage: "Korean",
    targetText: "모순",
    meanings: { English: "contradiction", "Simplified Chinese": "矛盾" },
    reading: "모순",
    romanization: "mosun",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 설명에는 모순이 있어요.",
    exampleTranslations: { English: "There is a contradiction in that explanation.", "Simplified Chinese": "那个说明有矛盾。" },
  },
  {
    id: "ko-topik-advanced-8",
    targetLanguage: "Korean",
    targetText: "고려",
    meanings: { English: "consideration", "Simplified Chinese": "考虑" },
    reading: "고려",
    romanization: "goryeo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "안전을 고려합니다.",
    exampleTranslations: { English: "I take safety into consideration.", "Simplified Chinese": "我会考虑安全。" },
  },
  {
    id: "ja-jlpt-advanced-9",
    targetLanguage: "Japanese",
    targetText: "概念",
    meanings: { English: "concept", "Simplified Chinese": "概念" },
    reading: "がいねん",
    romanization: "gainen",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "この概念は重要です。",
    exampleTranslations: { English: "This concept is important.", "Simplified Chinese": "这个概念很重要。" },
  },
  {
    id: "ja-jlpt-advanced-10",
    targetLanguage: "Japanese",
    targetText: "妥当",
    meanings: { English: "appropriate", "Simplified Chinese": "妥当" },
    reading: "だとう",
    romanization: "dato",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "妥当な判断です。",
    exampleTranslations: { English: "It is an appropriate judgment.", "Simplified Chinese": "这是妥当的判断。" },
  },
  {
    id: "ja-jlpt-advanced-11",
    targetLanguage: "Japanese",
    targetText: "規模",
    meanings: { English: "scale", "Simplified Chinese": "规模" },
    reading: "きぼ",
    romanization: "kibo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "規模が大きいです。",
    exampleTranslations: { English: "The scale is large.", "Simplified Chinese": "规模很大。" },
  },
  {
    id: "ja-jlpt-advanced-12",
    targetLanguage: "Japanese",
    targetText: "維持",
    meanings: { English: "maintenance", "Simplified Chinese": "维持" },
    reading: "いじ",
    romanization: "iji",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "品質を維持します。",
    exampleTranslations: { English: "We maintain quality.", "Simplified Chinese": "我们维持品质。" },
  },
  {
    id: "ja-jlpt-advanced-13",
    targetLanguage: "Japanese",
    targetText: "前提",
    meanings: { English: "premise", "Simplified Chinese": "前提" },
    reading: "ぜんてい",
    romanization: "zentei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "前提が違います。",
    exampleTranslations: { English: "The premise is different.", "Simplified Chinese": "前提不同。" },
  },
  {
    id: "ja-jlpt-advanced-14",
    targetLanguage: "Japanese",
    targetText: "把握",
    meanings: { English: "grasp", "Simplified Chinese": "掌握" },
    reading: "はあく",
    romanization: "haaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "状況を把握します。",
    exampleTranslations: { English: "I grasp the situation.", "Simplified Chinese": "我掌握情况。" },
  },
  {
    id: "ko-topik-advanced-9",
    targetLanguage: "Korean",
    targetText: "개념",
    meanings: { English: "concept", "Simplified Chinese": "概念" },
    reading: "개념",
    romanization: "gaenyeom",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 개념은 중요합니다.",
    exampleTranslations: { English: "This concept is important.", "Simplified Chinese": "这个概念很重要。" },
  },
  {
    id: "ko-topik-advanced-10",
    targetLanguage: "Korean",
    targetText: "타당하다",
    meanings: { English: "appropriate", "Simplified Chinese": "妥当" },
    reading: "타당하다",
    romanization: "tadanghada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "타당한 판단입니다.",
    exampleTranslations: { English: "It is an appropriate judgment.", "Simplified Chinese": "这是妥当的判断。" },
  },
  {
    id: "ko-topik-advanced-11",
    targetLanguage: "Korean",
    targetText: "규모",
    meanings: { English: "scale", "Simplified Chinese": "规模" },
    reading: "규모",
    romanization: "gyumo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "규모가 큽니다.",
    exampleTranslations: { English: "The scale is large.", "Simplified Chinese": "规模很大。" },
  },
  {
    id: "ko-topik-advanced-12",
    targetLanguage: "Korean",
    targetText: "유지",
    meanings: { English: "maintenance", "Simplified Chinese": "维持" },
    reading: "유지",
    romanization: "yuji",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "품질을 유지합니다.",
    exampleTranslations: { English: "We maintain quality.", "Simplified Chinese": "我们维持品质。" },
  },
  {
    id: "ko-topik-advanced-13",
    targetLanguage: "Korean",
    targetText: "전제",
    meanings: { English: "premise", "Simplified Chinese": "前提" },
    reading: "전제",
    romanization: "jeonje",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "전제가 다릅니다.",
    exampleTranslations: { English: "The premise is different.", "Simplified Chinese": "前提不同。" },
  },
  {
    id: "ko-topik-advanced-14",
    targetLanguage: "Korean",
    targetText: "파악",
    meanings: { English: "grasp", "Simplified Chinese": "掌握" },
    reading: "파악",
    romanization: "paak",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "상황을 파악합니다.",
    exampleTranslations: { English: "I grasp the situation.", "Simplified Chinese": "我掌握情况。" },
  },
  {
    id: "ja-jlpt-advanced-15",
    targetLanguage: "Japanese",
    targetText: "政策",
    meanings: { English: "policy", "Simplified Chinese": "政策" },
    reading: "せいさく",
    romanization: "seisaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "新しい政策を検討します。",
    exampleTranslations: { English: "We examine a new policy.", "Simplified Chinese": "我们研究新政策。" },
  },
  {
    id: "ko-topik-advanced-15",
    targetLanguage: "Korean",
    targetText: "정책",
    meanings: { English: "policy", "Simplified Chinese": "政策" },
    reading: "정책",
    romanization: "jeongchaek",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "새로운 정책을 검토합니다.",
    exampleTranslations: { English: "We examine a new policy.", "Simplified Chinese": "我们研究新政策。" },
  },
  {
    id: "ja-jlpt-advanced-16",
    targetLanguage: "Japanese",
    targetText: "傾向",
    meanings: { English: "tendency", "Simplified Chinese": "倾向" },
    reading: "けいこう",
    romanization: "keiko",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "最近の傾向を分析します。",
    exampleTranslations: { English: "We analyze recent trends.", "Simplified Chinese": "我们分析最近的倾向。" },
  },
  {
    id: "ko-topik-advanced-16",
    targetLanguage: "Korean",
    targetText: "경향",
    meanings: { English: "tendency", "Simplified Chinese": "倾向" },
    reading: "경향",
    romanization: "gyeonghyang",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "최근 경향을 분석합니다.",
    exampleTranslations: { English: "We analyze recent trends.", "Simplified Chinese": "我们分析最近的倾向。" },
  },
  {
    id: "ja-jlpt-advanced-17",
    targetLanguage: "Japanese",
    targetText: "根拠",
    meanings: { English: "evidence", "Simplified Chinese": "证据" },
    reading: "こんきょ",
    romanization: "konkyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "根拠を示してください。",
    exampleTranslations: { English: "Please show the evidence.", "Simplified Chinese": "请出示证据。" },
  },
  {
    id: "ko-topik-advanced-17",
    targetLanguage: "Korean",
    targetText: "근거",
    meanings: { English: "evidence", "Simplified Chinese": "证据" },
    reading: "근거",
    romanization: "geungeo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "근거를 제시해 주세요.",
    exampleTranslations: { English: "Please show the evidence.", "Simplified Chinese": "请出示证据。" },
  },
  {
    id: "ja-jlpt-advanced-18",
    targetLanguage: "Japanese",
    targetText: "観点",
    meanings: { English: "perspective", "Simplified Chinese": "观点" },
    reading: "かんてん",
    romanization: "kanten",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "別の観点から考えます。",
    exampleTranslations: { English: "I think from another perspective.", "Simplified Chinese": "我从另一个观点思考。" },
  },
  {
    id: "ko-topik-advanced-18",
    targetLanguage: "Korean",
    targetText: "관점",
    meanings: { English: "perspective", "Simplified Chinese": "观点" },
    reading: "관점",
    romanization: "gwanjeom",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "다른 관점에서 생각합니다.",
    exampleTranslations: { English: "I think from another perspective.", "Simplified Chinese": "我从另一个观点思考。" },
  },
  {
    id: "ja-jlpt-advanced-19",
    targetLanguage: "Japanese",
    targetText: "解釈",
    meanings: { English: "interpretation", "Simplified Chinese": "解释" },
    reading: "かいしゃく",
    romanization: "kaishaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "文章を解釈します。",
    exampleTranslations: { English: "I interpret the sentence.", "Simplified Chinese": "我解释句子。" },
  },
  {
    id: "ko-topik-advanced-19",
    targetLanguage: "Korean",
    targetText: "해석",
    meanings: { English: "interpretation", "Simplified Chinese": "解释" },
    reading: "해석",
    romanization: "haeseok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "문장을 해석합니다.",
    exampleTranslations: { English: "I interpret the sentence.", "Simplified Chinese": "我解释句子。" },
  },
  {
    id: "ja-jlpt-advanced-20",
    targetLanguage: "Japanese",
    targetText: "例外",
    meanings: { English: "exception", "Simplified Chinese": "例外" },
    reading: "れいがい",
    romanization: "reigai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "例外を認めます。",
    exampleTranslations: { English: "We acknowledge the exception.", "Simplified Chinese": "我们承认例外。" },
  },
  {
    id: "ko-topik-advanced-20",
    targetLanguage: "Korean",
    targetText: "예외",
    meanings: { English: "exception", "Simplified Chinese": "例外" },
    reading: "예외",
    romanization: "yeoe",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "예외를 인정합니다.",
    exampleTranslations: { English: "We acknowledge the exception.", "Simplified Chinese": "我们承认例外。" },
  },
  {
    id: "ja-jlpt-advanced-21",
    targetLanguage: "Japanese",
    targetText: "義務",
    meanings: { English: "obligation", "Simplified Chinese": "义务" },
    reading: "ぎむ",
    romanization: "gimu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "義務を果たします。",
    exampleTranslations: { English: "I fulfill my obligation.", "Simplified Chinese": "我履行义务。" },
  },
  {
    id: "ko-topik-advanced-21",
    targetLanguage: "Korean",
    targetText: "의무",
    meanings: { English: "obligation", "Simplified Chinese": "义务" },
    reading: "의무",
    romanization: "uimu",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "의무를 다합니다.",
    exampleTranslations: { English: "I fulfill my obligation.", "Simplified Chinese": "我履行义务。" },
  },
  {
    id: "ja-jlpt-advanced-22",
    targetLanguage: "Japanese",
    targetText: "利益",
    meanings: { English: "benefit", "Simplified Chinese": "利益" },
    reading: "りえき",
    romanization: "rieki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "長期的な利益を考えます。",
    exampleTranslations: { English: "I consider long-term benefits.", "Simplified Chinese": "我考虑长期利益。" },
  },
  {
    id: "ko-topik-advanced-22",
    targetLanguage: "Korean",
    targetText: "이익",
    meanings: { English: "benefit", "Simplified Chinese": "利益" },
    reading: "이익",
    romanization: "iik",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "장기적인 이익을 생각합니다.",
    exampleTranslations: { English: "I consider long-term benefits.", "Simplified Chinese": "我考虑长期利益。" },
  },
  {
    id: "ja-jlpt-advanced-23",
    targetLanguage: "Japanese",
    targetText: "問題",
    meanings: { English: "issue", "Simplified Chinese": "问题" },
    reading: "もんだい",
    romanization: "mondai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "重要な問題に取り組みます。",
    exampleTranslations: { English: "We tackle an important issue.", "Simplified Chinese": "我们处理重要问题。" },
  },
  {
    id: "ko-topik-advanced-23",
    targetLanguage: "Korean",
    targetText: "문제",
    meanings: { English: "issue", "Simplified Chinese": "问题" },
    reading: "문제",
    romanization: "munje",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "중요한 문제를 다룹니다.",
    exampleTranslations: { English: "We tackle an important issue.", "Simplified Chinese": "我们处理重要问题。" },
  },
  {
    id: "ja-jlpt-advanced-24",
    targetLanguage: "Japanese",
    targetText: "現象",
    meanings: { English: "phenomenon", "Simplified Chinese": "现象" },
    reading: "げんしょう",
    romanization: "gensho",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "この現象を説明します。",
    exampleTranslations: { English: "I explain this phenomenon.", "Simplified Chinese": "我说明这个现象。" },
  },
  {
    id: "ko-topik-advanced-24",
    targetLanguage: "Korean",
    targetText: "현상",
    meanings: { English: "phenomenon", "Simplified Chinese": "现象" },
    reading: "현상",
    romanization: "hyeonsang",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 현상을 설명합니다.",
    exampleTranslations: { English: "I explain this phenomenon.", "Simplified Chinese": "我说明这个现象。" },
  },
  {
    id: "ja-jlpt-advanced-25",
    targetLanguage: "Japanese",
    targetText: "仮説",
    meanings: { English: "hypothesis", "Simplified Chinese": "假设" },
    reading: "かせつ",
    romanization: "kasetsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "仮説を立てます。",
    exampleTranslations: { English: "I form a hypothesis.", "Simplified Chinese": "我提出假设。" },
  },
  {
    id: "ko-topik-advanced-25",
    targetLanguage: "Korean",
    targetText: "가설",
    meanings: { English: "hypothesis", "Simplified Chinese": "假设" },
    reading: "가설",
    romanization: "gaseol",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "가설을 세웁니다.",
    exampleTranslations: { English: "I form a hypothesis.", "Simplified Chinese": "我提出假设。" },
  },
  {
    id: "ja-jlpt-advanced-26",
    targetLanguage: "Japanese",
    targetText: "原則",
    meanings: { English: "principle", "Simplified Chinese": "原则" },
    reading: "げんそく",
    romanization: "gensoku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "原則を守ります。",
    exampleTranslations: { English: "I follow the principle.", "Simplified Chinese": "我遵守原则。" },
  },
  {
    id: "ko-topik-advanced-26",
    targetLanguage: "Korean",
    targetText: "원칙",
    meanings: { English: "principle", "Simplified Chinese": "原则" },
    reading: "원칙",
    romanization: "wonchik",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "원칙을 지킵니다.",
    exampleTranslations: { English: "I follow the principle.", "Simplified Chinese": "我遵守原则。" },
  },
  {
    id: "ja-jlpt-advanced-27",
    targetLanguage: "Japanese",
    targetText: "実行",
    meanings: { English: "execution", "Simplified Chinese": "执行" },
    reading: "じっこう",
    romanization: "jikko",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "計画を実行します。",
    exampleTranslations: { English: "I execute the plan.", "Simplified Chinese": "我执行计划。" },
  },
  {
    id: "ko-topik-advanced-27",
    targetLanguage: "Korean",
    targetText: "실행",
    meanings: { English: "execution", "Simplified Chinese": "执行" },
    reading: "실행",
    romanization: "silhaeng",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "계획을 실행합니다.",
    exampleTranslations: { English: "I execute the plan.", "Simplified Chinese": "我执行计划。" },
  },
  {
    id: "ja-jlpt-advanced-28",
    targetLanguage: "Japanese",
    targetText: "調整",
    meanings: { English: "adjustment", "Simplified Chinese": "调整" },
    reading: "ちょうせい",
    romanization: "chosei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "予定を調整します。",
    exampleTranslations: { English: "I adjust the schedule.", "Simplified Chinese": "我调整日程。" },
  },
  {
    id: "ko-topik-advanced-28",
    targetLanguage: "Korean",
    targetText: "조정",
    meanings: { English: "adjustment", "Simplified Chinese": "调整" },
    reading: "조정",
    romanization: "jojeong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "일정을 조정합니다.",
    exampleTranslations: { English: "I adjust the schedule.", "Simplified Chinese": "我调整日程。" },
  },
  {
    id: "ja-jlpt-advanced-29",
    targetLanguage: "Japanese",
    targetText: "対立",
    meanings: { English: "opposition", "Simplified Chinese": "对立" },
    reading: "たいりつ",
    romanization: "tairitsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "意見が対立しています。",
    exampleTranslations: { English: "Opinions are in opposition.", "Simplified Chinese": "意见对立。" },
  },
  {
    id: "ko-topik-advanced-29",
    targetLanguage: "Korean",
    targetText: "대립",
    meanings: { English: "opposition", "Simplified Chinese": "对立" },
    reading: "대립",
    romanization: "daerip",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "의견이 대립하고 있습니다.",
    exampleTranslations: { English: "Opinions are in opposition.", "Simplified Chinese": "意见对立。" },
  },
  {
    id: "ja-jlpt-advanced-30",
    targetLanguage: "Japanese",
    targetText: "優先順位",
    meanings: { English: "priority", "Simplified Chinese": "优先顺序" },
    reading: "ゆうせんじゅんい",
    romanization: "yusen jun'i",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "優先順位を決めます。",
    exampleTranslations: { English: "I decide the priority.", "Simplified Chinese": "我决定优先顺序。" },
  },
  {
    id: "ko-topik-advanced-30",
    targetLanguage: "Korean",
    targetText: "우선순위",
    meanings: { English: "priority", "Simplified Chinese": "优先顺序" },
    reading: "우선순위",
    romanization: "useonsunwi",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "우선순위를 정합니다.",
    exampleTranslations: { English: "I decide the priority.", "Simplified Chinese": "我决定优先顺序。" },
  },
  {
    id: "ja-jlpt-advanced-31",
    targetLanguage: "Japanese",
    targetText: "概要",
    meanings: { English: "overview", "Simplified Chinese": "概要" },
    reading: "がいよう",
    romanization: "gaiyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "概要を確認します。",
    exampleTranslations: { English: "I confirm the overview.", "Simplified Chinese": "我确认概要。" },
  },
  {
    id: "ko-topik-advanced-31",
    targetLanguage: "Korean",
    targetText: "개요",
    meanings: { English: "overview", "Simplified Chinese": "概要" },
    reading: "개요",
    romanization: "gaeyo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "개요을 확인합니다.",
    exampleTranslations: { English: "I confirm the overview.", "Simplified Chinese": "我确认概要。" },
  },
  {
    id: "ja-jlpt-advanced-32",
    targetLanguage: "Japanese",
    targetText: "分析",
    meanings: { English: "analysis", "Simplified Chinese": "分析" },
    reading: "ぶんせき",
    romanization: "bunseki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "分析を確認します。",
    exampleTranslations: { English: "I confirm the analysis.", "Simplified Chinese": "我确认分析。" },
  },
  {
    id: "ko-topik-advanced-32",
    targetLanguage: "Korean",
    targetText: "분석",
    meanings: { English: "analysis", "Simplified Chinese": "分析" },
    reading: "분석",
    romanization: "bunseok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "분석을 확인합니다.",
    exampleTranslations: { English: "I confirm the analysis.", "Simplified Chinese": "我确认分析。" },
  },
  {
    id: "ja-jlpt-advanced-33",
    targetLanguage: "Japanese",
    targetText: "評価",
    meanings: { English: "evaluation", "Simplified Chinese": "评价" },
    reading: "ひょうか",
    romanization: "hyoka",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "評価を確認します。",
    exampleTranslations: { English: "I confirm the evaluation.", "Simplified Chinese": "我确认评价。" },
  },
  {
    id: "ko-topik-advanced-33",
    targetLanguage: "Korean",
    targetText: "평가",
    meanings: { English: "evaluation", "Simplified Chinese": "评价" },
    reading: "평가",
    romanization: "pyeongga",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "평가을 확인합니다.",
    exampleTranslations: { English: "I confirm the evaluation.", "Simplified Chinese": "我确认评价。" },
  },
  {
    id: "ja-jlpt-advanced-34",
    targetLanguage: "Japanese",
    targetText: "課題",
    meanings: { English: "challenge", "Simplified Chinese": "课题" },
    reading: "かだい",
    romanization: "kadai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "課題を確認します。",
    exampleTranslations: { English: "I confirm the challenge.", "Simplified Chinese": "我确认课题。" },
  },
  {
    id: "ko-topik-advanced-34",
    targetLanguage: "Korean",
    targetText: "과제",
    meanings: { English: "challenge", "Simplified Chinese": "课题" },
    reading: "과제",
    romanization: "gwaje",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "과제을 확인합니다.",
    exampleTranslations: { English: "I confirm the challenge.", "Simplified Chinese": "我确认课题。" },
  },
  {
    id: "ja-jlpt-advanced-35",
    targetLanguage: "Japanese",
    targetText: "要因",
    meanings: { English: "factor", "Simplified Chinese": "因素" },
    reading: "よういん",
    romanization: "yoin",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "要因を確認します。",
    exampleTranslations: { English: "I confirm the factor.", "Simplified Chinese": "我确认因素。" },
  },
  {
    id: "ko-topik-advanced-35",
    targetLanguage: "Korean",
    targetText: "요인",
    meanings: { English: "factor", "Simplified Chinese": "因素" },
    reading: "요인",
    romanization: "yoin",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "요인을 확인합니다.",
    exampleTranslations: { English: "I confirm the factor.", "Simplified Chinese": "我确认因素。" },
  },
  {
    id: "ja-jlpt-advanced-36",
    targetLanguage: "Japanese",
    targetText: "影響",
    meanings: { English: "influence", "Simplified Chinese": "影响" },
    reading: "えいきょう",
    romanization: "eikyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "影響を確認します。",
    exampleTranslations: { English: "I confirm the influence.", "Simplified Chinese": "我确认影响。" },
  },
  {
    id: "ko-topik-advanced-36",
    targetLanguage: "Korean",
    targetText: "영향",
    meanings: { English: "influence", "Simplified Chinese": "影响" },
    reading: "영향",
    romanization: "yeonghyang",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "영향을 확인합니다.",
    exampleTranslations: { English: "I confirm the influence.", "Simplified Chinese": "我确认影响。" },
  },
  {
    id: "ja-jlpt-advanced-37",
    targetLanguage: "Japanese",
    targetText: "傾向",
    meanings: { English: "tendency", "Simplified Chinese": "倾向" },
    reading: "けいこう",
    romanization: "keiko",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "傾向を確認します。",
    exampleTranslations: { English: "I confirm the tendency.", "Simplified Chinese": "我确认倾向。" },
  },
  {
    id: "ko-topik-advanced-37",
    targetLanguage: "Korean",
    targetText: "경향",
    meanings: { English: "tendency", "Simplified Chinese": "倾向" },
    reading: "경향",
    romanization: "gyeonghyang",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "경향을 확인합니다.",
    exampleTranslations: { English: "I confirm the tendency.", "Simplified Chinese": "我确认倾向。" },
  },
  {
    id: "ja-jlpt-advanced-38",
    targetLanguage: "Japanese",
    targetText: "改善",
    meanings: { English: "improvement", "Simplified Chinese": "改善" },
    reading: "かいぜん",
    romanization: "kaizen",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "改善を確認します。",
    exampleTranslations: { English: "I confirm the improvement.", "Simplified Chinese": "我确认改善。" },
  },
  {
    id: "ko-topik-advanced-38",
    targetLanguage: "Korean",
    targetText: "개선",
    meanings: { English: "improvement", "Simplified Chinese": "改善" },
    reading: "개선",
    romanization: "gaeseon",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "개선을 확인합니다.",
    exampleTranslations: { English: "I confirm the improvement.", "Simplified Chinese": "我确认改善。" },
  },
  {
    id: "ja-jlpt-advanced-39",
    targetLanguage: "Japanese",
    targetText: "検討",
    meanings: { English: "review", "Simplified Chinese": "研究" },
    reading: "けんとう",
    romanization: "kento",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "検討を確認します。",
    exampleTranslations: { English: "I confirm the review.", "Simplified Chinese": "我确认研究。" },
  },
  {
    id: "ko-topik-advanced-39",
    targetLanguage: "Korean",
    targetText: "검토",
    meanings: { English: "review", "Simplified Chinese": "研究" },
    reading: "검토",
    romanization: "geomto",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "검토을 확인합니다.",
    exampleTranslations: { English: "I confirm the review.", "Simplified Chinese": "我确认研究。" },
  },
  {
    id: "ja-jlpt-advanced-40",
    targetLanguage: "Japanese",
    targetText: "構造",
    meanings: { English: "structure", "Simplified Chinese": "结构" },
    reading: "こうぞう",
    romanization: "kozo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "構造を確認します。",
    exampleTranslations: { English: "I confirm the structure.", "Simplified Chinese": "我确认结构。" },
  },
  {
    id: "ko-topik-advanced-40",
    targetLanguage: "Korean",
    targetText: "구조",
    meanings: { English: "structure", "Simplified Chinese": "结构" },
    reading: "구조",
    romanization: "gujo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "구조을 확인합니다.",
    exampleTranslations: { English: "I confirm the structure.", "Simplified Chinese": "我确认结构。" },
  },
  {
    id: "ja-jlpt-advanced-41",
    targetLanguage: "Japanese",
    targetText: "体系",
    meanings: { English: "system", "Simplified Chinese": "体系" },
    reading: "たいけい",
    romanization: "taikei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "体系を確認します。",
    exampleTranslations: { English: "I confirm the system.", "Simplified Chinese": "我确认体系。" },
  },
  {
    id: "ko-topik-advanced-41",
    targetLanguage: "Korean",
    targetText: "체계",
    meanings: { English: "system", "Simplified Chinese": "体系" },
    reading: "체계",
    romanization: "chegye",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "체계을 확인합니다.",
    exampleTranslations: { English: "I confirm the system.", "Simplified Chinese": "我确认体系。" },
  },
  {
    id: "ja-jlpt-advanced-42",
    targetLanguage: "Japanese",
    targetText: "事例",
    meanings: { English: "example", "Simplified Chinese": "事例" },
    reading: "じれい",
    romanization: "jirei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "事例を確認します。",
    exampleTranslations: { English: "I confirm the example.", "Simplified Chinese": "我确认事例。" },
  },
  {
    id: "ko-topik-advanced-42",
    targetLanguage: "Korean",
    targetText: "사례",
    meanings: { English: "example", "Simplified Chinese": "事例" },
    reading: "사례",
    romanization: "sarye",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "사례을 확인합니다.",
    exampleTranslations: { English: "I confirm the example.", "Simplified Chinese": "我确认事例。" },
  },
  {
    id: "ja-jlpt-advanced-43",
    targetLanguage: "Japanese",
    targetText: "仮定",
    meanings: { English: "assumption", "Simplified Chinese": "假定" },
    reading: "かてい",
    romanization: "katei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "仮定を確認します。",
    exampleTranslations: { English: "I confirm the assumption.", "Simplified Chinese": "我确认假定。" },
  },
  {
    id: "ko-topik-advanced-43",
    targetLanguage: "Korean",
    targetText: "가정",
    meanings: { English: "assumption", "Simplified Chinese": "假定" },
    reading: "가정",
    romanization: "gajeong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "가정을 확인합니다.",
    exampleTranslations: { English: "I confirm the assumption.", "Simplified Chinese": "我确认假定。" },
  },
  {
    id: "ja-jlpt-advanced-44",
    targetLanguage: "Japanese",
    targetText: "根拠",
    meanings: { English: "evidence", "Simplified Chinese": "根据" },
    reading: "こんきょ",
    romanization: "konkyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "根拠を確認します。",
    exampleTranslations: { English: "I confirm the evidence.", "Simplified Chinese": "我确认根据。" },
  },
  {
    id: "ko-topik-advanced-44",
    targetLanguage: "Korean",
    targetText: "근거",
    meanings: { English: "evidence", "Simplified Chinese": "根据" },
    reading: "근거",
    romanization: "geungeo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "근거을 확인합니다.",
    exampleTranslations: { English: "I confirm the evidence.", "Simplified Chinese": "我确认根据。" },
  },
  {
    id: "ja-jlpt-advanced-45",
    targetLanguage: "Japanese",
    targetText: "目的",
    meanings: { English: "purpose", "Simplified Chinese": "目的" },
    reading: "もくてき",
    romanization: "mokuteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "目的を確認します。",
    exampleTranslations: { English: "I confirm the purpose.", "Simplified Chinese": "我确认目的。" },
  },
  {
    id: "ko-topik-advanced-45",
    targetLanguage: "Korean",
    targetText: "목적",
    meanings: { English: "purpose", "Simplified Chinese": "目的" },
    reading: "목적",
    romanization: "mokjeok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "목적을 확인합니다.",
    exampleTranslations: { English: "I confirm the purpose.", "Simplified Chinese": "我确认目的。" },
  },
  {
    id: "ja-jlpt-advanced-46",
    targetLanguage: "Japanese",
    targetText: "手段",
    meanings: { English: "method", "Simplified Chinese": "手段" },
    reading: "しゅだん",
    romanization: "shudan",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "手段を確認します。",
    exampleTranslations: { English: "I confirm the method.", "Simplified Chinese": "我确认手段。" },
  },
  {
    id: "ko-topik-advanced-46",
    targetLanguage: "Korean",
    targetText: "수단",
    meanings: { English: "method", "Simplified Chinese": "手段" },
    reading: "수단",
    romanization: "sudan",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "수단을 확인합니다.",
    exampleTranslations: { English: "I confirm the method.", "Simplified Chinese": "我确认手段。" },
  },
  {
    id: "ja-jlpt-advanced-47",
    targetLanguage: "Japanese",
    targetText: "結果",
    meanings: { English: "result", "Simplified Chinese": "结果" },
    reading: "けっか",
    romanization: "kekka",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "結果を確認します。",
    exampleTranslations: { English: "I confirm the result.", "Simplified Chinese": "我确认结果。" },
  },
  {
    id: "ko-topik-advanced-47",
    targetLanguage: "Korean",
    targetText: "결과",
    meanings: { English: "result", "Simplified Chinese": "结果" },
    reading: "결과",
    romanization: "gyeolgwa",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "결과을 확인합니다.",
    exampleTranslations: { English: "I confirm the result.", "Simplified Chinese": "我确认结果。" },
  },
  {
    id: "ja-jlpt-advanced-48",
    targetLanguage: "Japanese",
    targetText: "過程",
    meanings: { English: "process", "Simplified Chinese": "过程" },
    reading: "かてい",
    romanization: "katei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "過程を確認します。",
    exampleTranslations: { English: "I confirm the process.", "Simplified Chinese": "我确认过程。" },
  },
  {
    id: "ko-topik-advanced-48",
    targetLanguage: "Korean",
    targetText: "과정",
    meanings: { English: "process", "Simplified Chinese": "过程" },
    reading: "과정",
    romanization: "gwajeong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "과정을 확인합니다.",
    exampleTranslations: { English: "I confirm the process.", "Simplified Chinese": "我确认过程。" },
  },
  {
    id: "ja-jlpt-advanced-49",
    targetLanguage: "Japanese",
    targetText: "理論",
    meanings: { English: "theory", "Simplified Chinese": "理论" },
    reading: "りろん",
    romanization: "riron",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "理論を確認します。",
    exampleTranslations: { English: "I confirm the theory.", "Simplified Chinese": "我确认理论。" },
  },
  {
    id: "ko-topik-advanced-49",
    targetLanguage: "Korean",
    targetText: "이론",
    meanings: { English: "theory", "Simplified Chinese": "理论" },
    reading: "이론",
    romanization: "iron",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이론을 확인합니다.",
    exampleTranslations: { English: "I confirm the theory.", "Simplified Chinese": "我确认理论。" },
  },
  {
    id: "ja-jlpt-advanced-50",
    targetLanguage: "Japanese",
    targetText: "実態",
    meanings: { English: "reality", "Simplified Chinese": "实态" },
    reading: "じったい",
    romanization: "jittai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "実態を確認します。",
    exampleTranslations: { English: "I confirm the reality.", "Simplified Chinese": "我确认实态。" },
  },
  {
    id: "ko-topik-advanced-50",
    targetLanguage: "Korean",
    targetText: "실태",
    meanings: { English: "reality", "Simplified Chinese": "实态" },
    reading: "실태",
    romanization: "siltae",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "실태을 확인합니다.",
    exampleTranslations: { English: "I confirm the reality.", "Simplified Chinese": "我确认实态。" },
  },
  {
    id: "ja-jlpt-advanced-51",
    targetLanguage: "Japanese",
    targetText: "認識",
    meanings: { English: "recognition", "Simplified Chinese": "认识" },
    reading: "にんしき",
    romanization: "ninshiki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "認識を確認します。",
    exampleTranslations: { English: "I confirm the recognition.", "Simplified Chinese": "我确认认识。" },
  },
  {
    id: "ko-topik-advanced-51",
    targetLanguage: "Korean",
    targetText: "인식",
    meanings: { English: "recognition", "Simplified Chinese": "认识" },
    reading: "인식",
    romanization: "insik",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "인식을 확인합니다.",
    exampleTranslations: { English: "I confirm the recognition.", "Simplified Chinese": "我确认认识。" },
  },
  {
    id: "ja-jlpt-advanced-52",
    targetLanguage: "Japanese",
    targetText: "判断",
    meanings: { English: "judgment", "Simplified Chinese": "判断" },
    reading: "はんだん",
    romanization: "handan",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "判断を確認します。",
    exampleTranslations: { English: "I confirm the judgment.", "Simplified Chinese": "我确认判断。" },
  },
  {
    id: "ko-topik-advanced-52",
    targetLanguage: "Korean",
    targetText: "판단",
    meanings: { English: "judgment", "Simplified Chinese": "判断" },
    reading: "판단",
    romanization: "pandan",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "판단을 확인합니다.",
    exampleTranslations: { English: "I confirm the judgment.", "Simplified Chinese": "我确认判断。" },
  },
  {
    id: "ja-jlpt-advanced-53",
    targetLanguage: "Japanese",
    targetText: "選択",
    meanings: { English: "choice", "Simplified Chinese": "选择" },
    reading: "せんたく",
    romanization: "sentaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "選択を確認します。",
    exampleTranslations: { English: "I confirm the choice.", "Simplified Chinese": "我确认选择。" },
  },
  {
    id: "ko-topik-advanced-53",
    targetLanguage: "Korean",
    targetText: "선택",
    meanings: { English: "choice", "Simplified Chinese": "选择" },
    reading: "선택",
    romanization: "seontaek",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "선택을 확인합니다.",
    exampleTranslations: { English: "I confirm the choice.", "Simplified Chinese": "我确认选择。" },
  },
  {
    id: "ja-jlpt-advanced-54",
    targetLanguage: "Japanese",
    targetText: "比較",
    meanings: { English: "comparison", "Simplified Chinese": "比较" },
    reading: "ひかく",
    romanization: "hikaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "比較を確認します。",
    exampleTranslations: { English: "I confirm the comparison.", "Simplified Chinese": "我确认比较。" },
  },
  {
    id: "ko-topik-advanced-54",
    targetLanguage: "Korean",
    targetText: "비교",
    meanings: { English: "comparison", "Simplified Chinese": "比较" },
    reading: "비교",
    romanization: "bigyo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "비교을 확인합니다.",
    exampleTranslations: { English: "I confirm the comparison.", "Simplified Chinese": "我确认比较。" },
  },
  {
    id: "ja-jlpt-advanced-55",
    targetLanguage: "Japanese",
    targetText: "変化",
    meanings: { English: "change", "Simplified Chinese": "变化" },
    reading: "へんか",
    romanization: "henka",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "変化を確認します。",
    exampleTranslations: { English: "I confirm the change.", "Simplified Chinese": "我确认变化。" },
  },
  {
    id: "ko-topik-advanced-55",
    targetLanguage: "Korean",
    targetText: "변화",
    meanings: { English: "change", "Simplified Chinese": "变化" },
    reading: "변화",
    romanization: "byeonhwa",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "변화을 확인합니다.",
    exampleTranslations: { English: "I confirm the change.", "Simplified Chinese": "我确认变化。" },
  },
  {
    id: "ja-jlpt-advanced-56",
    targetLanguage: "Japanese",
    targetText: "拡大",
    meanings: { English: "expansion", "Simplified Chinese": "扩大" },
    reading: "かくだい",
    romanization: "kakudai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "拡大を確認します。",
    exampleTranslations: { English: "I confirm the expansion.", "Simplified Chinese": "我确认扩大。" },
  },
  {
    id: "ko-topik-advanced-56",
    targetLanguage: "Korean",
    targetText: "확대",
    meanings: { English: "expansion", "Simplified Chinese": "扩大" },
    reading: "확대",
    romanization: "hwakdae",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "확대을 확인합니다.",
    exampleTranslations: { English: "I confirm the expansion.", "Simplified Chinese": "我确认扩大。" },
  },
  {
    id: "ja-jlpt-advanced-57",
    targetLanguage: "Japanese",
    targetText: "縮小",
    meanings: { English: "reduction", "Simplified Chinese": "缩小" },
    reading: "しゅくしょう",
    romanization: "shukusho",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "縮小を確認します。",
    exampleTranslations: { English: "I confirm the reduction.", "Simplified Chinese": "我确认缩小。" },
  },
  {
    id: "ko-topik-advanced-57",
    targetLanguage: "Korean",
    targetText: "축소",
    meanings: { English: "reduction", "Simplified Chinese": "缩小" },
    reading: "축소",
    romanization: "chukso",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "축소을 확인합니다.",
    exampleTranslations: { English: "I confirm the reduction.", "Simplified Chinese": "我确认缩小。" },
  },
  {
    id: "ja-jlpt-advanced-58",
    targetLanguage: "Japanese",
    targetText: "安定",
    meanings: { English: "stability", "Simplified Chinese": "稳定" },
    reading: "あんてい",
    romanization: "antei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "安定を確認します。",
    exampleTranslations: { English: "I confirm the stability.", "Simplified Chinese": "我确认稳定。" },
  },
  {
    id: "ko-topik-advanced-58",
    targetLanguage: "Korean",
    targetText: "안정",
    meanings: { English: "stability", "Simplified Chinese": "稳定" },
    reading: "안정",
    romanization: "anjeong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "안정을 확인합니다.",
    exampleTranslations: { English: "I confirm the stability.", "Simplified Chinese": "我确认稳定。" },
  },
  {
    id: "ja-jlpt-advanced-59",
    targetLanguage: "Japanese",
    targetText: "需要",
    meanings: { English: "demand", "Simplified Chinese": "需求" },
    reading: "じゅよう",
    romanization: "juyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "需要を確認します。",
    exampleTranslations: { English: "I confirm the demand.", "Simplified Chinese": "我确认需求。" },
  },
  {
    id: "ko-topik-advanced-59",
    targetLanguage: "Korean",
    targetText: "수요",
    meanings: { English: "demand", "Simplified Chinese": "需求" },
    reading: "수요",
    romanization: "suyo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "수요을 확인합니다.",
    exampleTranslations: { English: "I confirm the demand.", "Simplified Chinese": "我确认需求。" },
  },
  {
    id: "ja-jlpt-advanced-60",
    targetLanguage: "Japanese",
    targetText: "供給",
    meanings: { English: "supply", "Simplified Chinese": "供给" },
    reading: "きょうきゅう",
    romanization: "kyokyu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "供給を確認します。",
    exampleTranslations: { English: "I confirm the supply.", "Simplified Chinese": "我确认供给。" },
  },
  {
    id: "ko-topik-advanced-60",
    targetLanguage: "Korean",
    targetText: "공급",
    meanings: { English: "supply", "Simplified Chinese": "供给" },
    reading: "공급",
    romanization: "gonggeup",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "공급을 확인합니다.",
    exampleTranslations: { English: "I confirm the supply.", "Simplified Chinese": "我确认供给。" },
  },
  {
    id: "ja-jlpt-advanced-61",
    targetLanguage: "Japanese",
    targetText: "資源",
    meanings: { English: "resource", "Simplified Chinese": "资源" },
    reading: "しげん",
    romanization: "shigen",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "資源を確認します。",
    exampleTranslations: { English: "I confirm the resource.", "Simplified Chinese": "我确认资源。" },
  },
  {
    id: "ko-topik-advanced-61",
    targetLanguage: "Korean",
    targetText: "자원",
    meanings: { English: "resource", "Simplified Chinese": "资源" },
    reading: "자원",
    romanization: "jawon",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "자원을 확인합니다.",
    exampleTranslations: { English: "I confirm the resource.", "Simplified Chinese": "我确认资源。" },
  },
  {
    id: "ja-jlpt-advanced-62",
    targetLanguage: "Japanese",
    targetText: "環境",
    meanings: { English: "environment", "Simplified Chinese": "环境" },
    reading: "かんきょう",
    romanization: "kankyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "環境を確認します。",
    exampleTranslations: { English: "I confirm the environment.", "Simplified Chinese": "我确认环境。" },
  },
  {
    id: "ko-topik-advanced-62",
    targetLanguage: "Korean",
    targetText: "환경",
    meanings: { English: "environment", "Simplified Chinese": "环境" },
    reading: "환경",
    romanization: "hwangyeong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "환경을 확인합니다.",
    exampleTranslations: { English: "I confirm the environment.", "Simplified Chinese": "我确认环境。" },
  },
  {
    id: "ja-jlpt-advanced-63",
    targetLanguage: "Japanese",
    targetText: "制度",
    meanings: { English: "institution", "Simplified Chinese": "制度" },
    reading: "せいど",
    romanization: "seido",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "制度を確認します。",
    exampleTranslations: { English: "I confirm the institution.", "Simplified Chinese": "我确认制度。" },
  },
  {
    id: "ko-topik-advanced-63",
    targetLanguage: "Korean",
    targetText: "제도",
    meanings: { English: "institution", "Simplified Chinese": "制度" },
    reading: "제도",
    romanization: "jedo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "제도을 확인합니다.",
    exampleTranslations: { English: "I confirm the institution.", "Simplified Chinese": "我确认制度。" },
  },
  {
    id: "ja-jlpt-advanced-64",
    targetLanguage: "Japanese",
    targetText: "法律",
    meanings: { English: "law", "Simplified Chinese": "法律" },
    reading: "ほうりつ",
    romanization: "horitsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "法律を確認します。",
    exampleTranslations: { English: "I confirm the law.", "Simplified Chinese": "我确认法律。" },
  },
  {
    id: "ko-topik-advanced-64",
    targetLanguage: "Korean",
    targetText: "법률",
    meanings: { English: "law", "Simplified Chinese": "法律" },
    reading: "법률",
    romanization: "beomnyul",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "법률을 확인합니다.",
    exampleTranslations: { English: "I confirm the law.", "Simplified Chinese": "我确认法律。" },
  },
  {
    id: "ja-jlpt-advanced-65",
    targetLanguage: "Japanese",
    targetText: "権利",
    meanings: { English: "right", "Simplified Chinese": "权利" },
    reading: "けんり",
    romanization: "kenri",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "権利を確認します。",
    exampleTranslations: { English: "I confirm the right.", "Simplified Chinese": "我确认权利。" },
  },
  {
    id: "ko-topik-advanced-65",
    targetLanguage: "Korean",
    targetText: "권리",
    meanings: { English: "right", "Simplified Chinese": "权利" },
    reading: "권리",
    romanization: "gwolli",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "권리을 확인합니다.",
    exampleTranslations: { English: "I confirm the right.", "Simplified Chinese": "我确认权利。" },
  },
  {
    id: "ja-jlpt-advanced-66",
    targetLanguage: "Japanese",
    targetText: "責任",
    meanings: { English: "responsibility", "Simplified Chinese": "责任" },
    reading: "せきにん",
    romanization: "sekinin",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "責任を確認します。",
    exampleTranslations: { English: "I confirm the responsibility.", "Simplified Chinese": "我确认责任。" },
  },
  {
    id: "ko-topik-advanced-66",
    targetLanguage: "Korean",
    targetText: "책임",
    meanings: { English: "responsibility", "Simplified Chinese": "责任" },
    reading: "책임",
    romanization: "chaegim",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "책임을 확인합니다.",
    exampleTranslations: { English: "I confirm the responsibility.", "Simplified Chinese": "我确认责任。" },
  },
  {
    id: "ja-jlpt-advanced-67",
    targetLanguage: "Japanese",
    targetText: "交流",
    meanings: { English: "exchange", "Simplified Chinese": "交流" },
    reading: "こうりゅう",
    romanization: "koryu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "交流を確認します。",
    exampleTranslations: { English: "I confirm the exchange.", "Simplified Chinese": "我确认交流。" },
  },
  {
    id: "ko-topik-advanced-67",
    targetLanguage: "Korean",
    targetText: "교류",
    meanings: { English: "exchange", "Simplified Chinese": "交流" },
    reading: "교류",
    romanization: "gyoryu",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "교류을 확인합니다.",
    exampleTranslations: { English: "I confirm the exchange.", "Simplified Chinese": "我确认交流。" },
  },
  {
    id: "ja-jlpt-advanced-68",
    targetLanguage: "Japanese",
    targetText: "協力",
    meanings: { English: "cooperation", "Simplified Chinese": "合作" },
    reading: "きょうりょく",
    romanization: "kyoryoku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "協力を確認します。",
    exampleTranslations: { English: "I confirm the cooperation.", "Simplified Chinese": "我确认合作。" },
  },
  {
    id: "ko-topik-advanced-68",
    targetLanguage: "Korean",
    targetText: "협력",
    meanings: { English: "cooperation", "Simplified Chinese": "合作" },
    reading: "협력",
    romanization: "hyeomnyeok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "협력을 확인합니다.",
    exampleTranslations: { English: "I confirm the cooperation.", "Simplified Chinese": "我确认合作。" },
  },
  {
    id: "ja-jlpt-advanced-69",
    targetLanguage: "Japanese",
    targetText: "競争",
    meanings: { English: "competition", "Simplified Chinese": "竞争" },
    reading: "きょうそう",
    romanization: "kyoso",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "競争を確認します。",
    exampleTranslations: { English: "I confirm the competition.", "Simplified Chinese": "我确认竞争。" },
  },
  {
    id: "ko-topik-advanced-69",
    targetLanguage: "Korean",
    targetText: "경쟁",
    meanings: { English: "competition", "Simplified Chinese": "竞争" },
    reading: "경쟁",
    romanization: "gyeongjaeng",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "경쟁을 확인합니다.",
    exampleTranslations: { English: "I confirm the competition.", "Simplified Chinese": "我确认竞争。" },
  },
  {
    id: "ja-jlpt-advanced-70",
    targetLanguage: "Japanese",
    targetText: "解決",
    meanings: { English: "solution", "Simplified Chinese": "解决" },
    reading: "かいけつ",
    romanization: "kaiketsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "解決を確認します。",
    exampleTranslations: { English: "I confirm the solution.", "Simplified Chinese": "我确认解决。" },
  },
  {
    id: "ko-topik-advanced-70",
    targetLanguage: "Korean",
    targetText: "해결",
    meanings: { English: "solution", "Simplified Chinese": "解决" },
    reading: "해결",
    romanization: "haegyeol",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "해결을 확인합니다.",
    exampleTranslations: { English: "I confirm the solution.", "Simplified Chinese": "我确认解决。" },
  },
  {
    id: "ja-jlpt-advanced-71",
    targetLanguage: "Japanese",
    targetText: "提案",
    meanings: { English: "proposal", "Simplified Chinese": "提案" },
    reading: "ていあん",
    romanization: "teian",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "提案を確認します。",
    exampleTranslations: { English: "I confirm the proposal.", "Simplified Chinese": "我确认提案。" },
  },
  {
    id: "ko-topik-advanced-71",
    targetLanguage: "Korean",
    targetText: "제안",
    meanings: { English: "proposal", "Simplified Chinese": "提案" },
    reading: "제안",
    romanization: "jean",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "제안을 확인합니다.",
    exampleTranslations: { English: "I confirm the proposal.", "Simplified Chinese": "我确认提案。" },
  },
  {
    id: "ja-jlpt-advanced-72",
    targetLanguage: "Japanese",
    targetText: "実現",
    meanings: { English: "realization", "Simplified Chinese": "实现" },
    reading: "じつげん",
    romanization: "jitsugen",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "実現を確認します。",
    exampleTranslations: { English: "I confirm the realization.", "Simplified Chinese": "我确认实现。" },
  },
  {
    id: "ko-topik-advanced-72",
    targetLanguage: "Korean",
    targetText: "실현",
    meanings: { English: "realization", "Simplified Chinese": "实现" },
    reading: "실현",
    romanization: "silhyeon",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "실현을 확인합니다.",
    exampleTranslations: { English: "I confirm the realization.", "Simplified Chinese": "我确认实现。" },
  },
  {
    id: "ja-jlpt-advanced-73",
    targetLanguage: "Japanese",
    targetText: "適用",
    meanings: { English: "application", "Simplified Chinese": "应用" },
    reading: "てきよう",
    romanization: "tekiyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "適用を確認します。",
    exampleTranslations: { English: "I confirm the application.", "Simplified Chinese": "我确认应用。" },
  },
  {
    id: "ko-topik-advanced-73",
    targetLanguage: "Korean",
    targetText: "적용",
    meanings: { English: "application", "Simplified Chinese": "应用" },
    reading: "적용",
    romanization: "jeogyong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "적용을 확인합니다.",
    exampleTranslations: { English: "I confirm the application.", "Simplified Chinese": "我确认应用。" },
  },
  {
    id: "ja-jlpt-advanced-74",
    targetLanguage: "Japanese",
    targetText: "限界",
    meanings: { English: "limit", "Simplified Chinese": "界限" },
    reading: "げんかい",
    romanization: "genkai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "限界を確認します。",
    exampleTranslations: { English: "I confirm the limit.", "Simplified Chinese": "我确认界限。" },
  },
  {
    id: "ko-topik-advanced-74",
    targetLanguage: "Korean",
    targetText: "한계",
    meanings: { English: "limit", "Simplified Chinese": "界限" },
    reading: "한계",
    romanization: "hangye",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "한계을 확인합니다.",
    exampleTranslations: { English: "I confirm the limit.", "Simplified Chinese": "我确认界限。" },
  },
  {
    id: "ja-jlpt-advanced-75",
    targetLanguage: "Japanese",
    targetText: "展望",
    meanings: { English: "outlook", "Simplified Chinese": "展望" },
    reading: "てんぼう",
    romanization: "tenbo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "展望を確認します。",
    exampleTranslations: { English: "I confirm the outlook.", "Simplified Chinese": "我确认展望。" },
  },
  {
    id: "ko-topik-advanced-75",
    targetLanguage: "Korean",
    targetText: "전망",
    meanings: { English: "outlook", "Simplified Chinese": "展望" },
    reading: "전망",
    romanization: "jeonmang",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "전망을 확인합니다.",
    exampleTranslations: { English: "I confirm the outlook.", "Simplified Chinese": "我确认展望。" },
  }
];
