import type { Topic, VocabItem } from "./vocabulary";

type NounPair = [topic: Topic, en: string, zh: string, ja: string, jaReading: string, jaRomanization: string, ko: string];

const makePair = (level: "Intermediate" | "Advanced", index: number, [topic, en, zh, ja, jaReading, jaRomanization, ko]: NounPair): VocabItem[] => {
  const suffix = String(index + 1).padStart(3, "0");
  const levelKey = level === "Intermediate" ? "intermediate" : "advanced";
  return [
    { id: `ja-noun-${levelKey}-${suffix}`, targetLanguage: "Japanese", targetText: ja, meanings: { English: en, "Simplified Chinese": zh }, reading: jaReading, romanization: jaRomanization, level, topic, exampleSentence: `${ja}について確認します。`, exampleTranslations: { English: `We will review ${en}.`, "Simplified Chinese": `我们确认“${zh}”相关内容。` } },
    { id: `ko-noun-${levelKey}-${suffix}`, targetLanguage: "Korean", targetText: ko, meanings: { English: en, "Simplified Chinese": zh }, reading: ko, romanization: "", level, topic, exampleSentence: `${ko}에 대해 확인합니다.`, exampleTranslations: { English: `We will review ${en}.`, "Simplified Chinese": `我们确认“${zh}”相关内容。` } },
  ];
};

const intermediateNouns: NounPair[] = [
  ["work", "agenda", "议题", "議題", "ぎだい", "gidai", "안건"],
  ["work", "office supplies", "办公用品", "備品", "びひん", "bihin", "비품"],
  ["work", "internal approval", "内部审批", "稟議", "りんぎ", "ringi", "품의"],
  ["work", "invoice", "账单/发票", "請求書", "せいきゅうしょ", "seikyuusho", "청구서"],
  ["work", "quotation", "报价单", "見積書", "みつもりしょ", "mitsumorisho", "견적서"],
  ["work", "budget", "预算", "予算", "よさん", "yosan", "예산"],
  ["work", "revenue", "营业收入", "売上", "うりあげ", "uriage", "매출"],
  ["work", "profit", "利润", "利益", "りえき", "rieki", "이익"],
  ["work", "loss", "损失", "損失", "そんしつ", "sonshitsu", "손실"],
  ["work", "inventory", "库存", "在庫", "ざいこ", "zaiko", "재고"],
  ["work", "warehouse", "仓库", "倉庫", "そうこ", "souko", "창고"],
  ["work", "shipment", "出货", "出荷", "しゅっか", "shukka", "출하"],
  ["work", "supplier", "供应商", "仕入先", "しいれさき", "shiiresaki", "공급사"],
  ["work", "colleague", "同事", "同僚", "どうりょう", "douryou", "동료"],
  ["work", "supervisor", "上司", "上司", "じょうし", "joushi", "상사"],
  ["work", "subordinate", "下属", "部下", "ぶか", "buka", "부하"],
  ["work", "branch office", "分店/分公司", "支店", "してん", "shiten", "지점"],
  ["work", "headquarters", "总部", "本社", "ほんしゃ", "honsha", "본사"],
  ["work", "payroll", "工资单/薪资", "給与", "きゅうよ", "kyuuyo", "급여"],
  ["work", "allowance", "津贴", "手当", "てあて", "teate", "수당"],
  ["work", "expense", "经费", "経費", "けいひ", "keihi", "경비"],
  ["work", "receipt", "收据", "領収書", "りょうしゅうしょ", "ryoushuusho", "영수증"],
  ["work", "signature", "签名", "署名", "しょめい", "shomei", "서명"],
  ["work", "attachment", "附件", "添付", "てんぷ", "tenpu", "첨부"],
  ["work", "draft", "草案", "草案", "そうあん", "souan", "초안"],
  ["travel", "fare", "票价/运费", "運賃", "うんちん", "unchin", "운임"],
  ["travel", "platform", "站台", "ホーム", "ほーむ", "hoomu", "승강장"],
  ["travel", "boarding order", "登机顺序", "搭乗順", "とうじょうじゅん", "toujoujun", "탑승순서"],
  ["travel", "boarding pass", "登机牌", "搭乗券", "とうじょうけん", "toujouken", "탑승권"],
  ["travel", "baggage", "行李", "手荷物", "てにもつ", "tenimotsu", "수하물"],
  ["travel", "suitcase", "行李箱", "スーツケース", "すーつけーす", "suutsukeesu", "여행가방"],
  ["travel", "passport", "护照", "パスポート", "ぱすぽーと", "pasupooto", "여권"],
  ["travel", "visa", "签证", "ビザ", "びざ", "biza", "비자"],
  ["travel", "immigration control", "出入境", "出入国", "しゅつにゅうこく", "shutsunyuukoku", "출입국"],
  ["travel", "quarantine", "检疫", "検疫", "けんえき", "ken'eki", "검역"],
  ["travel", "terminal", "航站楼", "ターミナル", "たーみなる", "taaminaru", "터미널"],
  ["travel", "runway", "跑道", "滑走路", "かっそうろ", "kassouro", "활주로"],
  ["travel", "departure board", "出发信息牌", "出発案内", "しゅっぱつあんない", "shuppatsuannai", "출발안내"],
  ["travel", "seat map", "座位图", "座席表", "ざせきひょう", "zasekihyou", "좌석표"],
  ["travel", "arrival hall", "到达大厅", "到着ロビー", "とうちゃくろびー", "touchakurobii", "도착로비"],
  ["travel", "transfer station", "换乘站", "乗換駅", "のりかええき", "norikaeeki", "환승역"],
  ["travel", "itinerary", "行程", "旅程", "りょてい", "ryotei", "여정"],
  ["travel", "lodging", "住宿处", "宿泊先", "しゅくはくさき", "shukuhakusaki", "숙소"],
  ["travel", "hostel", "青年旅舍", "ホステル", "ほすてる", "hosuteru", "호스텔"],
  ["travel", "souvenir", "纪念品", "土産", "みやげ", "miyage", "기념품"],
  ["travel", "guidebook", "旅行指南", "ガイドブック", "がいどぶっく", "gaidobukku", "안내책자"],
  ["travel", "currency", "货币", "通貨", "つうか", "tsuuka", "통화"],
  ["travel", "exchange rate", "汇率", "為替", "かわせ", "kawase", "환율"],
  ["travel", "deposit", "押金", "保証金", "ほしょうきん", "hoshoukin", "보증금"],
  ["travel", "luggage cart", "行李车", "カート", "かーと", "kaato", "수하물카트"],
  ["daily life", "maintenance fee", "管理费", "管理費", "かんりひ", "kanrihi", "관리비"],
  ["daily life", "electricity bill", "电费", "電気料金", "でんきりょうきん", "denkiryoukin", "전기요금"],
  ["daily life", "mortgage", "房贷", "住宅ローン", "じゅうたくろーん", "juutakuroon", "주택대출"],
  ["daily life", "appliance", "家电", "家電", "かでん", "kaden", "가전"],
  ["daily life", "detergent", "洗涤剂", "洗剤", "せんざい", "senzai", "세제"],
  ["daily life", "laundry", "洗好的衣物", "洗濯物", "せんたくもの", "sentakumono", "빨래"],
  ["daily life", "trash", "垃圾", "ごみ", "ごみ", "gomi", "쓰레기"],
  ["daily life", "recycling", "回收利用", "再利用", "さいりよう", "sairiyou", "재활용"],
  ["daily life", "parcel", "包裹", "小包", "こづつみ", "kozutsumi", "택배"],
  ["daily life", "delivery", "配送", "配達", "はいたつ", "haitatsu", "배송"],
  ["daily life", "calendar", "日历", "カレンダー", "かれんだー", "karendaa", "달력"],
  ["daily life", "wallet", "钱包", "財布", "さいふ", "saifu", "지갑"],
  ["daily life", "charger", "充电器", "充電器", "じゅうでんき", "juudenki", "충전기"],
  ["daily life", "battery", "电池", "電池", "でんち", "denchi", "배터리"],
  ["daily life", "umbrella", "雨伞", "傘", "かさ", "kasa", "우산"],
  ["daily life", "blanket", "毛毯", "毛布", "もうふ", "moufu", "담요"],
  ["daily life", "pillow", "枕头", "枕", "まくら", "makura", "베개"],
  ["daily life", "towel", "毛巾", "タオル", "たおる", "taoru", "수건"],
  ["daily life", "mirror", "镜子", "鏡", "かがみ", "kagami", "거울"],
  ["daily life", "shelf", "架子", "棚", "たな", "tana", "선반"],
  ["daily life", "drawer", "抽屉", "引出し", "ひきだし", "hikidashi", "서랍"],
  ["daily life", "balcony", "阳台", "ベランダ", "べらんだ", "beranda", "베란다"],
  ["daily life", "hallway", "走廊", "廊下", "ろうか", "rouka", "복도"],
  ["daily life", "residents association", "居民会", "自治会", "じちかい", "jichikai", "주민회"],
  ["daily life", "clinic", "诊所", "診療所", "しんりょうじょ", "shinryoujo", "의원"],
  ["school", "syllabus", "课程大纲", "シラバス", "しらばす", "shirabasu", "강의계획서"],
  ["school", "seminar", "研讨课", "ゼミ", "ぜみ", "zemi", "세미나"],
  ["school", "laboratory", "研究室", "研究室", "けんきゅうしつ", "kenkyuushitsu", "연구실"],
  ["school", "campus", "校园", "キャンパス", "きゃんぱす", "kyanpasu", "캠퍼스"],
  ["school", "dormitory", "宿舍", "寮", "りょう", "ryou", "기숙사"],
  ["school", "cafeteria", "食堂", "食堂", "しょくどう", "shokudou", "학생식당"],
  ["school", "student status", "学籍", "学籍", "がくせき", "gakuseki", "학적"],
  ["school", "transcript", "成绩单", "成績証明書", "せいせきしょうめいしょ", "seisekishoumeisho", "성적증명서"],
  ["school", "diploma", "毕业证书", "卒業証書", "そつぎょうしょうしょ", "sotsugyoushousho", "졸업장"],
  ["school", "certificate", "证明书", "証明書", "しょうめいしょ", "shoumeisho", "증명서"],
  ["school", "timetable", "课程表", "時間割", "じかんわり", "jikanwari", "시간표"],
  ["school", "faculty", "学部", "学部", "がくぶ", "gakubu", "학부"],
  ["school", "minor", "辅修", "副専攻", "ふくせんこう", "fukusenkou", "부전공"],
  ["school", "bibliography", "参考文献", "参考文献", "さんこうぶんけん", "sankoubunken", "참고문헌"],
  ["school", "citation", "引用", "引用", "いんよう", "inyou", "인용"],
  ["school", "plagiarism", "抄袭", "剽窃", "ひょうせつ", "hyousetsu", "표절"],
  ["school", "survey", "问卷调查", "調査", "ちょうさ", "chousa", "설문"],
  ["school", "questionnaire", "问卷", "質問票", "しつもんひょう", "shitsumonhyou", "설문지"],
  ["school", "internship", "实习", "インターン", "いんたーん", "intaan", "인턴십"],
  ["school", "mentor", "导师", "指導者", "しどうしゃ", "shidousha", "멘토"],
  ["school", "school regulations", "校规", "校則", "こうそく", "kousoku", "학칙"],
  ["school", "elective", "选修课", "選択科目", "せんたくかもく", "sentakukamoku", "선택과목"],
  ["school", "prerequisite", "先修条件", "前提科目", "ぜんていかもく", "zenteikamoku", "선수과목"],
  ["school", "enrollment", "注册入学", "履修登録", "りしゅうとうろく", "rishuutouroku", "수강신청"],
  ["school", "alumni", "校友", "卒業生", "そつぎょうせい", "sotsugyousei", "동문"],
  ["anime/drama", "storyboard", "分镜", "絵コンテ", "えこんて", "ekonte", "스토리보드"],
  ["anime/drama", "plot", "剧情", "筋書き", "すじがき", "sujigaki", "줄거리"],
  ["anime/drama", "setting", "设定", "設定", "せってい", "settei", "배경설정"],
  ["anime/drama", "season", "季度/季", "シーズン", "しーずん", "shiizun", "시즌"],
  ["anime/drama", "cast", "演员阵容", "配役", "はいやく", "haiyaku", "배역"],
  ["anime/drama", "soundtrack", "原声带", "サントラ", "さんとら", "santora", "사운드트랙"],
  ["anime/drama", "key animation", "原画", "原画", "げんが", "genga", "원화"],
  ["anime/drama", "character design", "角色设计", "キャラデザイン", "きゃらでざいん", "kyaradezain", "캐릭터디자인"],
  ["anime/drama", "opening", "片头", "オープニング", "おーぷにんぐ", "oopuningu", "오프닝"],
  ["anime/drama", "ending", "片尾", "エンディング", "えんでぃんぐ", "endingu", "엔딩"],
  ["anime/drama", "bonus feature", "特典", "特典", "とくてん", "tokuten", "특전"],
  ["anime/drama", "fandom", "粉丝圈", "ファンダム", "ふぁんだむ", "fandamu", "팬덤"],
  ["anime/drama", "merchandise", "周边", "グッズ", "ぐっず", "guzzu", "굿즈"],
  ["anime/drama", "figure", "手办", "フィギュア", "ふぃぎゅあ", "figyua", "피규어"],
  ["anime/drama", "adaptation", "改编", "映像化", "えいぞうか", "eizouka", "영상화"],
  ["anime/drama", "remake", "重制版", "リメイク", "りめいく", "rimeiku", "리메이크"],
  ["anime/drama", "dubbing", "配音版", "吹替", "ふきかえ", "fukikae", "더빙"],
  ["anime/drama", "rating", "收视率", "視聴率", "しちょうりつ", "shichouritsu", "시청률"],
  ["anime/drama", "premiere", "首播", "初放送", "はつほうそう", "hatsuhousou", "첫방송"],
  ["anime/drama", "cliffhanger", "悬念结尾", "引き", "ひき", "hiki", "클리프행어"],
  ["anime/drama", "villain", "反派", "悪役", "あくやく", "akuyaku", "악역"],
  ["anime/drama", "heroine", "女主角", "ヒロイン", "ひろいん", "hiroin", "여주인공"],
  ["anime/drama", "genre", "类型", "ジャンル", "じゃんる", "janru", "장르"],
  ["anime/drama", "mystery", "悬疑", "ミステリー", "みすてりー", "misuterii", "미스터리"],
  ["anime/drama", "romance", "爱情题材", "恋愛", "れんあい", "ren'ai", "로맨스"],
];

const advancedNouns: NounPair[] = [
  ["work", "governance", "治理", "ガバナンス", "がばなんす", "gabanansu", "거버넌스"],
  ["work", "compliance", "合规", "コンプライアンス", "こんぷらいあんす", "konpuraiansu", "컴플라이언스"],
  ["work", "control", "管控", "統制", "とうせい", "tousei", "통제"],
  ["work", "procurement", "采购", "調達", "ちょうたつ", "choutatsu", "조달"],
  ["work", "stakeholder", "利益相关方", "利害関係者", "りがいかんけいしゃ", "rigaikankeisha", "이해관계자"],
  ["work", "approval", "认可/批准", "認可", "にんか", "ninka", "인가"],
  ["work", "delegation", "授权委托", "権限委譲", "けんげんいじょう", "kengen'ijou", "권한위임"],
  ["work", "escalation", "升级处理", "エスカレーション", "えすかれーしょん", "esukareeshon", "에스컬레이션"],
  ["work", "redundancy", "冗余", "冗長性", "じょうちょうせい", "jouchousei", "이중화"],
  ["work", "capacity", "容量", "容量", "ようりょう", "youryou", "용량"],
  ["work", "throughput", "吞吐量", "スループット", "するーぷっと", "suruuputto", "처리량"],
  ["work", "latency", "延迟", "レイテンシ", "れいてんし", "reitenshi", "지연시간"],
  ["work", "bottleneck", "瓶颈", "ボトルネック", "ぼとるねっく", "botorunekku", "병목"],
  ["work", "outage", "服务中断", "障害", "しょうがい", "shougai", "장애"],
  ["work", "incident", "事故/事件", "インシデント", "いんしでんと", "inshidento", "인시던트"],
  ["work", "root cause", "根因", "根本原因", "こんぽんげんいん", "konpongen'in", "근본원인"],
  ["work", "remediation", "整改", "是正措置", "ぜせいそち", "zeseisochi", "개선조치"],
  ["work", "resilience", "韧性", "回復力", "かいふくりょく", "kaifukuryoku", "회복탄력성"],
  ["work", "availability", "可用性", "可用性", "かようせい", "kayousei", "가용성"],
  ["work", "scalability", "可扩展性", "拡張性", "かくちょうせい", "kakuchousei", "확장성"],
  ["work", "dependency", "依赖关系", "依存関係", "いぞんかんけい", "izonkankei", "의존성"],
  ["work", "migration", "迁移", "移行", "いこう", "ikou", "마이그레이션"],
  ["work", "retention", "保留期", "保持", "ほじ", "hoji", "보존기간"],
  ["work", "encryption", "加密", "暗号化", "あんごうか", "angouka", "암호화"],
  ["work", "credential", "凭证", "認証情報", "にんしょうじょうほう", "ninshoujouhou", "자격증명"],
  ["travel", "jurisdiction", "管辖权", "管轄", "かんかつ", "kankatsu", "관할"],
  ["travel", "deportation", "驱逐出境", "退去強制", "たいきょきょうせい", "taikyokyousei", "강제퇴거"],
  ["travel", "inadmissibility", "不准入境", "入国不許可", "にゅうこくふきょか", "nyuukokufukyoka", "입국불허"],
  ["travel", "asylum", "庇护", "庇護", "ひご", "higo", "망명"],
  ["travel", "refugee", "难民", "難民", "なんみん", "nanmin", "난민"],
  ["travel", "nationality", "国籍", "国籍", "こくせき", "kokuseki", "국적"],
  ["travel", "residency", "居留资格", "在留資格", "ざいりゅうしかく", "zairyuushikaku", "체류자격"],
  ["travel", "permit", "许可证", "許可証", "きょかしょう", "kyokashou", "허가증"],
  ["travel", "sponsorship", "担保/资助", "身元保証", "みもとほしょう", "mimotohoshou", "신원보증"],
  ["travel", "declaration", "申报", "申告", "しんこく", "shinkoku", "신고"],
  ["travel", "manifest", "舱单/旅客名单", "旅客名簿", "りょきゃくめいぼ", "ryokyakumeibo", "승객명단"],
  ["travel", "contraband", "违禁品", "禁制品", "きんせいひん", "kinseihin", "금제품"],
  ["travel", "customs duty", "关税", "関税", "かんぜい", "kanzei", "관세"],
  ["travel", "exemption", "豁免", "免除", "めんじょ", "menjo", "면제"],
  ["travel", "transit", "过境", "通過", "つうか", "tsuuka", "통과"],
  ["travel", "diversion", "备降/改降", "ダイバート", "だいばーと", "daibaato", "회항"],
  ["travel", "alternate airport", "备降机场", "代替空港", "だいがえくうこう", "daigaekuukou", "대체공항"],
  ["travel", "slot", "航班时刻", "発着枠", "はっちゃくわく", "hatchakuwaku", "슬롯"],
  ["travel", "congestion", "拥堵", "混雑", "こんざつ", "konzatsu", "혼잡"],
  ["travel", "turbulence", "湍流", "乱気流", "らんきりゅう", "rankiryuu", "난기류"],
  ["travel", "airspace", "领空", "領空", "りょうくう", "ryoukuu", "영공"],
  ["travel", "clearance", "许可", "許可", "きょか", "kyoka", "허가"],
  ["travel", "apron", "机坪", "駐機場", "ちゅうきじょう", "chuukijou", "계류장"],
  ["travel", "taxiway", "滑行道", "誘導路", "ゆうどうみち", "yuudoumichi", "유도로"],
  ["travel", "jet bridge", "廊桥", "搭乗橋", "とうじょうはし", "toujouhashi", "탑승교"],
  ["daily life", "welfare", "福利", "福祉", "ふくし", "fukushi", "복지"],
  ["daily life", "pension", "养老金", "年金", "ねんきん", "nenkin", "연금"],
  ["daily life", "subsidy", "补贴", "補助金", "ほじょきん", "hojokin", "보조금"],
  ["daily life", "taxation", "课税", "課税", "かぜい", "kazei", "과세"],
  ["daily life", "demographics", "人口统计", "人口動態", "じんこうどうたい", "jinkoudoutai", "인구동태"],
  ["daily life", "aging", "老龄化", "高齢化", "こうれいか", "koureika", "고령화"],
  ["daily life", "inequality", "不平等/差距", "格差", "かくさ", "kakusa", "불평등"],
  ["daily life", "privacy", "隐私", "プライバシー", "ぷらいばしー", "puraibashii", "사생활"],
  ["daily life", "consent", "同意", "同意", "どうい", "doui", "동의"],
  ["daily life", "identity", "身份", "身元", "みもと", "mimoto", "신원"],
  ["daily life", "fraud", "欺诈", "詐欺", "さぎ", "sagi", "사기"],
  ["daily life", "compensation", "赔偿", "賠償", "ばいしょう", "baishou", "배상"],
  ["daily life", "dispute", "争议", "紛争", "ふんそう", "funsou", "분쟁"],
  ["daily life", "arbitration", "仲裁", "仲裁", "ちゅうさい", "chuusai", "중재"],
  ["daily life", "mediation", "调解", "調停", "ちょうてい", "choutei", "조정"],
  ["daily life", "complaint", "投诉", "苦情", "くじょう", "kujou", "민원"],
  ["daily life", "regulation", "法规/规制", "規制", "きせい", "kisei", "규제"],
  ["daily life", "ordinance", "条例", "条例", "じょうれい", "jourei", "조례"],
  ["daily life", "census", "人口普查", "国勢調査", "こくせいちょうさ", "kokuseichousa", "인구조사"],
  ["daily life", "household", "家庭户", "世帯", "せたい", "setai", "가구"],
  ["daily life", "tenancy", "租赁关系", "賃貸借", "ちんたいしゃく", "chintaishaku", "임대차"],
  ["daily life", "inheritance", "继承", "相続", "そうぞく", "souzoku", "상속"],
  ["daily life", "guardianship", "监护", "後見", "こうけん", "kouken", "후견"],
  ["daily life", "citizenship", "公民身份", "市民権", "しみんけん", "shiminken", "시민권"],
  ["daily life", "litigation", "诉讼", "訴訟", "そしょう", "soshou", "소송"],
  ["school", "proposition", "命题", "命題", "めいだい", "meidai", "명제"],
  ["school", "methodology", "方法论", "方法論", "ほうほうろん", "houhouron", "방법론"],
  ["school", "variable", "变量", "変数", "へんすう", "hensuu", "변수"],
  ["school", "dataset", "数据集", "データセット", "でーたせっと", "deetasetto", "데이터셋"],
  ["school", "sample", "样本", "標本", "ひょうほん", "hyouhon", "표본"],
  ["school", "bias", "偏差", "偏り", "かたより", "katayori", "편향"],
  ["school", "correlation", "相关性", "相関", "そうかん", "soukan", "상관"],
  ["school", "confounding", "混杂因素", "交絡", "こうらく", "kouraku", "교란"],
  ["school", "reliability", "可靠性", "信頼性", "しんらいせい", "shinraisei", "신뢰도"],
  ["school", "replication", "重复验证", "再現", "さいげん", "saigen", "재현"],
  ["school", "peer review", "同行评审", "査読", "さどく", "sadoku", "동료평가"],
  ["school", "abstract", "摘要", "要旨", "ようし", "youshi", "초록"],
  ["school", "appendix", "附录", "付録", "ふろく", "furoku", "부록"],
  ["school", "footnote", "脚注", "脚注", "きゃくちゅう", "kyakuchuu", "각주"],
  ["school", "citation index", "引用指数", "引用指数", "いんようしすう", "inyoushisuu", "인용지수"],
  ["school", "archive", "档案库", "アーカイブ", "あーかいぶ", "aakaibu", "아카이브"],
  ["school", "corpus", "语料库", "コーパス", "こーぱす", "koopasu", "말뭉치"],
  ["school", "framework", "框架", "枠組み", "わくぐみ", "wakugumi", "프레임워크"],
  ["school", "rubric", "评分标准", "評価基準", "ひょうかきじゅん", "hyoukakijun", "평가기준"],
  ["school", "accreditation", "认证", "認証", "にんしょう", "ninshou", "인증"],
  ["school", "grant", "研究资助", "助成金", "じょせいきん", "joseikin", "연구비"],
  ["school", "fellowship", "研究奖学金", "研究奨励金", "けんきゅうしょうれいきん", "kenkyuushoureikin", "펠로십"],
  ["school", "tenure", "终身教职", "終身在職権", "しゅうしんざいしょくけん", "shuushinzaishokuken", "정년보장"],
  ["school", "protocol", "研究规程", "手順書", "てじゅんしょ", "tejunsho", "프로토콜"],
  ["school", "benchmark", "基准", "ベンチマーク", "べんちまーく", "benchimaaku", "벤치마크"],
  ["anime/drama", "cinematography", "摄影", "撮影", "さつえい", "satsuei", "촬영"],
  ["anime/drama", "editing", "剪辑", "編集", "へんしゅう", "henshuu", "편집"],
  ["anime/drama", "direction", "演出", "演出", "えんしゅつ", "enshutsu", "연출"],
  ["anime/drama", "choreography", "编舞", "振付", "ふりつけ", "furitsuke", "안무"],
  ["anime/drama", "costume", "服装", "衣装", "いしょう", "ishou", "의상"],
  ["anime/drama", "makeup", "化妆造型", "メイク", "めいく", "meiku", "분장"],
  ["anime/drama", "prop", "道具", "小道具", "こどうぐ", "kodougu", "소품"],
  ["anime/drama", "set design", "美术设计", "美術", "びじゅつ", "bijutsu", "미술"],
  ["anime/drama", "lighting", "灯光", "照明", "しょうめい", "shoumei", "조명"],
  ["anime/drama", "framing", "构图", "構図", "こうず", "kouzu", "구도"],
  ["anime/drama", "montage", "蒙太奇", "モンタージュ", "もんたーじゅ", "montaaju", "몽타주"],
  ["anime/drama", "narration", "旁白", "語り", "かたり", "katari", "내레이션"],
  ["anime/drama", "symbolism", "象征", "象徴", "しょうちょう", "shouchou", "상징"],
  ["anime/drama", "motif", "母题", "モチーフ", "もちーふ", "mochiifu", "모티프"],
  ["anime/drama", "archetype", "原型", "原型", "げんけい", "genkei", "원형"],
  ["anime/drama", "canon", "正史", "正史", "せいし", "seishi", "정사"],
  ["anime/drama", "lore", "世界观设定", "世界観", "せかいかん", "sekaikan", "세계관"],
  ["anime/drama", "continuity", "连续性", "連続性", "れんぞくせい", "renzokusei", "연속성"],
  ["anime/drama", "pacing", "节奏", "テンポ", "てんぽ", "tenpo", "호흡"],
  ["anime/drama", "foreshadowing", "伏笔", "伏線", "ふくせん", "fukusen", "복선"],
  ["anime/drama", "subtext", "潜台词", "含意", "がんい", "gan'i", "함의"],
  ["anime/drama", "ensemble", "群像", "群像", "ぐんぞう", "gunzou", "군상"],
  ["anime/drama", "auteurism", "作者论", "作家主義", "さっかしゅぎ", "sakkashugi", "작가주의"],
  ["anime/drama", "franchise", "系列作品", "シリーズ", "しりーず", "shiriizu", "프랜차이즈"],
  ["anime/drama", "censorship", "审查", "検閲", "けんえつ", "ken'etsu", "검열"],
];

export const intermediateNounExpansion: VocabItem[] = intermediateNouns.flatMap((pair, index) => makePair("Intermediate", index, pair));
export const advancedNounExpansion: VocabItem[] = advancedNouns.flatMap((pair, index) => makePair("Advanced", index, pair));
