import type { VocabItem } from "./vocabulary";

export const basicVocab: VocabItem[] = [
  {
    id: "ja-food-basic-1",
    targetLanguage: "Japanese",
    targetText: "ご飯",
    meanings: { English: "rice, meal", "Simplified Chinese": "饭，吃饭" },
    reading: "ごはん",
    romanization: "gohan",
    level: "Basic",
    topic: "food",
    exampleSentence: "朝ご飯を食べます。",
    exampleTranslations: { English: "I eat breakfast.", "Simplified Chinese": "我吃早饭。" },
  },
  {
    id: "ja-travel-basic-1",
    targetLanguage: "Japanese",
    targetText: "駅",
    meanings: { English: "station, stop", "Simplified Chinese": "车站，站点" },
    reading: "えき",
    romanization: "eki",
    level: "Basic",
    topic: "travel",
    exampleSentence: "駅はどこですか。",
    exampleTranslations: { English: "Where is the station?", "Simplified Chinese": "车站在哪里？" },
  },
  {
    id: "ja-life-basic-1",
    targetLanguage: "Japanese",
    targetText: "寝る",
    meanings: { English: "sleep, rest", "Simplified Chinese": "睡觉，睡眠" },
    reading: "ねる",
    romanization: "neru",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "十一時に寝ます。",
    exampleTranslations: { English: "I go to sleep at eleven.", "Simplified Chinese": "我十一点睡觉。" },
  },
  {
    id: "ja-numbers-basic-1",
    targetLanguage: "Japanese",
    targetText: "七",
    meanings: { English: "seven, 7", "Simplified Chinese": "七，数字七" },
    reading: "なな / しち",
    romanization: "nana / shichi",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "七つください。",
    exampleTranslations: { English: "Seven, please.", "Simplified Chinese": "请给我七个。" },
  },
  {
    id: "ja-verbs-basic-1",
    targetLanguage: "Japanese",
    targetText: "見る",
    meanings: { English: "see, look", "Simplified Chinese": "看，看见" },
    reading: "みる",
    romanization: "miru",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "映画を見ます。",
    exampleTranslations: { English: "I watch a movie.", "Simplified Chinese": "我看电影。" },
  },
  {
    id: "ja-food-basic-2",
    targetLanguage: "Japanese",
    targetText: "水",
    meanings: { English: "water, drinking water", "Simplified Chinese": "水，饮用水" },
    reading: "みず",
    romanization: "mizu",
    level: "Basic",
    topic: "food",
    exampleSentence: "水をください。",
    exampleTranslations: { English: "Water, please.", "Simplified Chinese": "请给我水。" },
  },
  {
    id: "ja-travel-basic-2",
    targetLanguage: "Japanese",
    targetText: "切符",
    meanings: { English: "ticket, pass", "Simplified Chinese": "票，车票" },
    reading: "きっぷ",
    romanization: "kippu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "切符を買います。",
    exampleTranslations: { English: "I buy a ticket.", "Simplified Chinese": "我买票。" },
  },
  {
    id: "ja-life-basic-2",
    targetLanguage: "Japanese",
    targetText: "起きる",
    meanings: { English: "wake, wake up", "Simplified Chinese": "起床，醒来" },
    reading: "おきる",
    romanization: "okiru",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "六時に起きます。",
    exampleTranslations: { English: "I get up at six.", "Simplified Chinese": "我六点起床。" },
  },
  {
    id: "ja-numbers-basic-2",
    targetLanguage: "Japanese",
    targetText: "百",
    meanings: { English: "hundred, 100", "Simplified Chinese": "百，一百" },
    reading: "ひゃく",
    romanization: "hyaku",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "百円です。",
    exampleTranslations: { English: "It is one hundred yen.", "Simplified Chinese": "是一百日元。" },
  },
  {
    id: "ja-verbs-basic-2",
    targetLanguage: "Japanese",
    targetText: "行く",
    meanings: { English: "go, leave", "Simplified Chinese": "去，前往" },
    reading: "いく",
    romanization: "iku",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "学校へ行きます。",
    exampleTranslations: { English: "I go to school.", "Simplified Chinese": "我去学校。" },
  },
  {
    id: "ko-food-basic-1",
    targetLanguage: "Korean",
    targetText: "밥",
    meanings: { English: "rice, meal", "Simplified Chinese": "米饭，饭" },
    reading: "밥",
    romanization: "bap",
    level: "Basic",
    topic: "food",
    exampleSentence: "밥을 먹어요.",
    exampleTranslations: { English: "I eat a meal.", "Simplified Chinese": "我吃饭。" },
  },
  {
    id: "ko-travel-basic-1",
    targetLanguage: "Korean",
    targetText: "역",
    meanings: { English: "station, stop", "Simplified Chinese": "车站，站点" },
    reading: "역",
    romanization: "yeok",
    level: "Basic",
    topic: "travel",
    exampleSentence: "역이 어디예요?",
    exampleTranslations: { English: "Where is the station?", "Simplified Chinese": "车站在哪里？" },
  },
  {
    id: "ko-life-basic-1",
    targetLanguage: "Korean",
    targetText: "자다",
    meanings: { English: "sleep, rest", "Simplified Chinese": "睡觉，睡眠" },
    reading: "자다",
    romanization: "jada",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "열한 시에 자요.",
    exampleTranslations: { English: "I sleep at eleven.", "Simplified Chinese": "我十一点睡觉。" },
  },
  {
    id: "ko-numbers-basic-1",
    targetLanguage: "Korean",
    targetText: "일곱",
    meanings: { English: "seven, 7", "Simplified Chinese": "七，数字七" },
    reading: "일곱",
    romanization: "ilgop",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "일곱 개 주세요.",
    exampleTranslations: { English: "Seven, please.", "Simplified Chinese": "请给我七个。" },
  },
  {
    id: "ko-verbs-basic-1",
    targetLanguage: "Korean",
    targetText: "보다",
    meanings: { English: "see, look", "Simplified Chinese": "看，看见" },
    reading: "보다",
    romanization: "boda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "드라마를 봐요.",
    exampleTranslations: { English: "I watch a drama.", "Simplified Chinese": "我看电视剧。" },
  },
  {
    id: "ko-food-basic-2",
    targetLanguage: "Korean",
    targetText: "물",
    meanings: { English: "water, drinking water", "Simplified Chinese": "水，饮用水" },
    reading: "물",
    romanization: "mul",
    level: "Basic",
    topic: "food",
    exampleSentence: "물 주세요.",
    exampleTranslations: { English: "Water, please.", "Simplified Chinese": "请给我水。" },
  },
  {
    id: "ko-travel-basic-2",
    targetLanguage: "Korean",
    targetText: "표",
    meanings: { English: "ticket, pass", "Simplified Chinese": "票，车票" },
    reading: "표",
    romanization: "pyo",
    level: "Basic",
    topic: "travel",
    exampleSentence: "표를 사요.",
    exampleTranslations: { English: "I buy a ticket.", "Simplified Chinese": "我买票。" },
  },
  {
    id: "ko-life-basic-2",
    targetLanguage: "Korean",
    targetText: "일어나다",
    meanings: { English: "wake, wake up", "Simplified Chinese": "起床，醒来" },
    reading: "일어나다",
    romanization: "ireonada",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "여섯 시에 일어나요.",
    exampleTranslations: { English: "I get up at six.", "Simplified Chinese": "我六点起床。" },
  },
  {
    id: "ko-numbers-basic-2",
    targetLanguage: "Korean",
    targetText: "백",
    meanings: { English: "hundred, 100", "Simplified Chinese": "百，一百" },
    reading: "백",
    romanization: "baek",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "백 원이에요.",
    exampleTranslations: { English: "It is one hundred won.", "Simplified Chinese": "是一百韩元。" },
  },
  {
    id: "ko-verbs-basic-2",
    targetLanguage: "Korean",
    targetText: "가다",
    meanings: { English: "go, leave", "Simplified Chinese": "去，前往" },
    reading: "가다",
    romanization: "gada",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "학교에 가요.",
    exampleTranslations: { English: "I go to school.", "Simplified Chinese": "我去学校。" },
  },
  {
    id: "ja-food-basic-3",
    targetLanguage: "Japanese",
    targetText: "お茶",
    meanings: { English: "tea, tea drink", "Simplified Chinese": "茶，茶水" },
    reading: "おちゃ",
    romanization: "ocha",
    level: "Basic",
    topic: "food",
    exampleSentence: "温かいお茶を飲みます。",
    exampleTranslations: { English: "I drink warm tea.", "Simplified Chinese": "我喝热茶。" },
  },
  {
    id: "ja-life-basic-3",
    targetLanguage: "Japanese",
    targetText: "友達",
    meanings: { English: "friend, companion", "Simplified Chinese": "朋友，好友" },
    reading: "ともだち",
    romanization: "tomodachi",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "友達に会います。",
    exampleTranslations: { English: "I meet a friend.", "Simplified Chinese": "我见朋友。" },
  },
  {
    id: "ja-travel-basic-3",
    targetLanguage: "Japanese",
    targetText: "病院",
    meanings: { English: "hospital, clinic", "Simplified Chinese": "医院，诊所" },
    reading: "びょういん",
    romanization: "byoin",
    level: "Basic",
    topic: "travel",
    exampleSentence: "病院は近いです。",
    exampleTranslations: { English: "The hospital is nearby.", "Simplified Chinese": "医院很近。" },
  },
  {
    id: "ja-verbs-basic-3",
    targetLanguage: "Japanese",
    targetText: "買う",
    meanings: { English: "buy, purchase", "Simplified Chinese": "买，购买" },
    reading: "かう",
    romanization: "kau",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "パンを買います。",
    exampleTranslations: { English: "I buy bread.", "Simplified Chinese": "我买面包。" },
  },
  {
    id: "ko-food-basic-3",
    targetLanguage: "Korean",
    targetText: "차",
    meanings: { English: "tea, tea drink", "Simplified Chinese": "茶，茶水" },
    reading: "차",
    romanization: "cha",
    level: "Basic",
    topic: "food",
    exampleSentence: "따뜻한 차를 마셔요.",
    exampleTranslations: { English: "I drink warm tea.", "Simplified Chinese": "我喝热茶。" },
  },
  {
    id: "ko-life-basic-3",
    targetLanguage: "Korean",
    targetText: "친구",
    meanings: { English: "friend, companion", "Simplified Chinese": "朋友，好友" },
    reading: "친구",
    romanization: "chingu",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "친구를 만나요.",
    exampleTranslations: { English: "I meet a friend.", "Simplified Chinese": "我见朋友。" },
  },
  {
    id: "ko-travel-basic-3",
    targetLanguage: "Korean",
    targetText: "병원",
    meanings: { English: "hospital, clinic", "Simplified Chinese": "医院，诊所" },
    reading: "병원",
    romanization: "byeongwon",
    level: "Basic",
    topic: "travel",
    exampleSentence: "병원이 가까워요.",
    exampleTranslations: { English: "The hospital is nearby.", "Simplified Chinese": "医院很近。" },
  },
  {
    id: "ko-verbs-basic-3",
    targetLanguage: "Korean",
    targetText: "사다",
    meanings: { English: "buy, purchase", "Simplified Chinese": "买，购买" },
    reading: "사다",
    romanization: "sada",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "빵을 사요.",
    exampleTranslations: { English: "I buy bread.", "Simplified Chinese": "我买面包。" },
  },
  {
    id: "ja-food-basic-4",
    targetLanguage: "Japanese",
    targetText: "パン",
    meanings: { English: "bread, loaf", "Simplified Chinese": "面包，面包食品" },
    reading: "パン",
    romanization: "pan",
    level: "Basic",
    topic: "food",
    exampleSentence: "パンを食べます。",
    exampleTranslations: { English: "I eat bread.", "Simplified Chinese": "我吃面包。" },
  },
  {
    id: "ja-food-basic-5",
    targetLanguage: "Japanese",
    targetText: "牛乳",
    meanings: { English: "milk, dairy milk", "Simplified Chinese": "牛奶，奶" },
    reading: "ぎゅうにゅう",
    romanization: "gyunyu",
    level: "Basic",
    topic: "food",
    exampleSentence: "牛乳を飲みます。",
    exampleTranslations: { English: "I drink milk.", "Simplified Chinese": "我喝牛奶。" },
  },
  {
    id: "ja-food-basic-6",
    targetLanguage: "Japanese",
    targetText: "野菜",
    meanings: { English: "vegetables, veggies", "Simplified Chinese": "蔬菜，青菜" },
    reading: "やさい",
    romanization: "yasai",
    level: "Basic",
    topic: "food",
    exampleSentence: "野菜が好きです。",
    exampleTranslations: { English: "I like vegetables.", "Simplified Chinese": "我喜欢蔬菜。" },
  },
  {
    id: "ja-travel-basic-4",
    targetLanguage: "Japanese",
    targetText: "空港",
    meanings: { English: "airport, air terminal", "Simplified Chinese": "机场，航空站" },
    reading: "くうこう",
    romanization: "kuko",
    level: "Basic",
    topic: "travel",
    exampleSentence: "空港へ行きます。",
    exampleTranslations: { English: "I go to the airport.", "Simplified Chinese": "我去机场。" },
  },
  {
    id: "ja-travel-basic-5",
    targetLanguage: "Japanese",
    targetText: "道",
    meanings: { English: "road, street", "Simplified Chinese": "路，道路" },
    reading: "みち",
    romanization: "michi",
    level: "Basic",
    topic: "travel",
    exampleSentence: "この道を歩きます。",
    exampleTranslations: { English: "I walk on this road.", "Simplified Chinese": "我走这条路。" },
  },
  {
    id: "ja-travel-basic-6",
    targetLanguage: "Japanese",
    targetText: "地図",
    meanings: { English: "map, route map", "Simplified Chinese": "地图，路线图" },
    reading: "ちず",
    romanization: "chizu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "地図を見ます。",
    exampleTranslations: { English: "I look at the map.", "Simplified Chinese": "我看地图。" },
  },
  {
    id: "ja-life-basic-4",
    targetLanguage: "Japanese",
    targetText: "家",
    meanings: { English: "home, house", "Simplified Chinese": "家，住所" },
    reading: "いえ",
    romanization: "ie",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "家に帰ります。",
    exampleTranslations: { English: "I go home.", "Simplified Chinese": "我回家。" },
  },
  {
    id: "ja-life-basic-5",
    targetLanguage: "Japanese",
    targetText: "電話",
    meanings: { English: "phone, telephone", "Simplified Chinese": "电话，手机" },
    reading: "でんわ",
    romanization: "denwa",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "電話をします。",
    exampleTranslations: { English: "I make a phone call.", "Simplified Chinese": "我打电话。" },
  },
  {
    id: "ja-life-basic-6",
    targetLanguage: "Japanese",
    targetText: "天気",
    meanings: { English: "weather, climate", "Simplified Chinese": "天气，气候" },
    reading: "てんき",
    romanization: "tenki",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "今日は天気がいいです。",
    exampleTranslations: { English: "The weather is nice today.", "Simplified Chinese": "今天天气很好。" },
  },
  {
    id: "ja-numbers-basic-3",
    targetLanguage: "Japanese",
    targetText: "千",
    meanings: { English: "thousand, 1,000", "Simplified Chinese": "千，一千" },
    reading: "せん",
    romanization: "sen",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "千円です。",
    exampleTranslations: { English: "It is one thousand yen.", "Simplified Chinese": "是一千日元。" },
  },
  {
    id: "ja-numbers-basic-4",
    targetLanguage: "Japanese",
    targetText: "半分",
    meanings: { English: "half, one half", "Simplified Chinese": "一半，半数" },
    reading: "はんぶん",
    romanization: "hanbun",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "半分ください。",
    exampleTranslations: { English: "Please give me half.", "Simplified Chinese": "请给我一半。" },
  },
  {
    id: "ja-verbs-basic-4",
    targetLanguage: "Japanese",
    targetText: "待つ",
    meanings: { English: "wait, stay", "Simplified Chinese": "等，等待" },
    reading: "まつ",
    romanization: "matsu",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "少し待ちます。",
    exampleTranslations: { English: "I wait a little.", "Simplified Chinese": "我等一下。" },
  },
  {
    id: "ja-verbs-basic-5",
    targetLanguage: "Japanese",
    targetText: "話す",
    meanings: { English: "speak, talk", "Simplified Chinese": "说话，讲话" },
    reading: "はなす",
    romanization: "hanasu",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "日本語を話します。",
    exampleTranslations: { English: "I speak Japanese.", "Simplified Chinese": "我说日语。" },
  },
  {
    id: "ja-verbs-basic-6",
    targetLanguage: "Japanese",
    targetText: "聞く",
    meanings: { English: "listen, hear", "Simplified Chinese": "听，听见" },
    reading: "きく",
    romanization: "kiku",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "音楽を聞きます。",
    exampleTranslations: { English: "I listen to music.", "Simplified Chinese": "我听音乐。" },
  },
  {
    id: "ko-food-basic-4",
    targetLanguage: "Korean",
    targetText: "빵",
    meanings: { English: "bread, loaf", "Simplified Chinese": "面包，面包食品" },
    reading: "빵",
    romanization: "ppang",
    level: "Basic",
    topic: "food",
    exampleSentence: "빵을 먹어요.",
    exampleTranslations: { English: "I eat bread.", "Simplified Chinese": "我吃面包。" },
  },
  {
    id: "ko-food-basic-5",
    targetLanguage: "Korean",
    targetText: "우유",
    meanings: { English: "milk, dairy milk", "Simplified Chinese": "牛奶，奶" },
    reading: "우유",
    romanization: "uyu",
    level: "Basic",
    topic: "food",
    exampleSentence: "우유를 마셔요.",
    exampleTranslations: { English: "I drink milk.", "Simplified Chinese": "我喝牛奶。" },
  },
  {
    id: "ko-food-basic-6",
    targetLanguage: "Korean",
    targetText: "채소",
    meanings: { English: "vegetables, veggies", "Simplified Chinese": "蔬菜，青菜" },
    reading: "채소",
    romanization: "chaeso",
    level: "Basic",
    topic: "food",
    exampleSentence: "채소를 좋아해요.",
    exampleTranslations: { English: "I like vegetables.", "Simplified Chinese": "我喜欢蔬菜。" },
  },
  {
    id: "ko-travel-basic-4",
    targetLanguage: "Korean",
    targetText: "공항",
    meanings: { English: "airport, air terminal", "Simplified Chinese": "机场，航空站" },
    reading: "공항",
    romanization: "gonghang",
    level: "Basic",
    topic: "travel",
    exampleSentence: "공항에 가요.",
    exampleTranslations: { English: "I go to the airport.", "Simplified Chinese": "我去机场。" },
  },
  {
    id: "ko-travel-basic-5",
    targetLanguage: "Korean",
    targetText: "길",
    meanings: { English: "road, street", "Simplified Chinese": "路，道路" },
    reading: "길",
    romanization: "gil",
    level: "Basic",
    topic: "travel",
    exampleSentence: "이 길로 걸어요.",
    exampleTranslations: { English: "I walk on this road.", "Simplified Chinese": "我走这条路。" },
  },
  {
    id: "ko-travel-basic-6",
    targetLanguage: "Korean",
    targetText: "지도",
    meanings: { English: "map, route map", "Simplified Chinese": "地图，路线图" },
    reading: "지도",
    romanization: "jido",
    level: "Basic",
    topic: "travel",
    exampleSentence: "지도를 봐요.",
    exampleTranslations: { English: "I look at the map.", "Simplified Chinese": "我看地图。" },
  },
  {
    id: "ko-life-basic-4",
    targetLanguage: "Korean",
    targetText: "집",
    meanings: { English: "home, house", "Simplified Chinese": "家，住所" },
    reading: "집",
    romanization: "jip",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "집에 가요.",
    exampleTranslations: { English: "I go home.", "Simplified Chinese": "我回家。" },
  },
  {
    id: "ko-life-basic-5",
    targetLanguage: "Korean",
    targetText: "전화",
    meanings: { English: "phone, telephone", "Simplified Chinese": "电话，手机" },
    reading: "전화",
    romanization: "jeonhwa",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "전화를 해요.",
    exampleTranslations: { English: "I make a phone call.", "Simplified Chinese": "我打电话。" },
  },
  {
    id: "ko-life-basic-6",
    targetLanguage: "Korean",
    targetText: "날씨",
    meanings: { English: "weather, climate", "Simplified Chinese": "天气，气候" },
    reading: "날씨",
    romanization: "nalssi",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "오늘은 날씨가 좋아요.",
    exampleTranslations: { English: "The weather is nice today.", "Simplified Chinese": "今天天气很好。" },
  },
  {
    id: "ko-numbers-basic-3",
    targetLanguage: "Korean",
    targetText: "천",
    meanings: { English: "thousand, 1,000", "Simplified Chinese": "千，一千" },
    reading: "천",
    romanization: "cheon",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "천 원이에요.",
    exampleTranslations: { English: "It is one thousand won.", "Simplified Chinese": "是一千韩元。" },
  },
  {
    id: "ko-numbers-basic-4",
    targetLanguage: "Korean",
    targetText: "반",
    meanings: { English: "half, one half", "Simplified Chinese": "一半，半数" },
    reading: "반",
    romanization: "ban",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "반 주세요.",
    exampleTranslations: { English: "Please give me half.", "Simplified Chinese": "请给我一半。" },
  },
  {
    id: "ko-verbs-basic-4",
    targetLanguage: "Korean",
    targetText: "기다리다",
    meanings: { English: "wait, stay", "Simplified Chinese": "等，等待" },
    reading: "기다리다",
    romanization: "gidarida",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "조금 기다려요.",
    exampleTranslations: { English: "I wait a little.", "Simplified Chinese": "我等一下。" },
  },
  {
    id: "ko-verbs-basic-5",
    targetLanguage: "Korean",
    targetText: "말하다",
    meanings: { English: "speak, talk", "Simplified Chinese": "说话，讲话" },
    reading: "말하다",
    romanization: "malhada",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "한국어를 말해요.",
    exampleTranslations: { English: "I speak Korean.", "Simplified Chinese": "我说韩语。" },
  },
  {
    id: "ko-verbs-basic-6",
    targetLanguage: "Korean",
    targetText: "듣다",
    meanings: { English: "listen, hear", "Simplified Chinese": "听，听见" },
    reading: "듣다",
    romanization: "deutda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "음악을 들어요.",
    exampleTranslations: { English: "I listen to music.", "Simplified Chinese": "我听音乐。" },
  },
  {
    id: "ja-food-basic-7",
    targetLanguage: "Japanese",
    targetText: "卵",
    meanings: { English: "egg, egg food", "Simplified Chinese": "鸡蛋，蛋" },
    reading: "たまご",
    romanization: "tamago",
    level: "Basic",
    topic: "food",
    exampleSentence: "卵を食べます。",
    exampleTranslations: { English: "I eat an egg.", "Simplified Chinese": "我吃鸡蛋。" },
  },
  {
    id: "ko-food-basic-7",
    targetLanguage: "Korean",
    targetText: "계란",
    meanings: { English: "egg, egg food", "Simplified Chinese": "鸡蛋，蛋" },
    reading: "계란",
    romanization: "gyeran",
    level: "Basic",
    topic: "food",
    exampleSentence: "계란을 먹어요.",
    exampleTranslations: { English: "I eat an egg.", "Simplified Chinese": "我吃鸡蛋。" },
  },
  {
    id: "ja-food-basic-8",
    targetLanguage: "Japanese",
    targetText: "魚",
    meanings: { English: "fish, seafood", "Simplified Chinese": "鱼，鱼肉" },
    reading: "さかな",
    romanization: "sakana",
    level: "Basic",
    topic: "food",
    exampleSentence: "魚を食べます。",
    exampleTranslations: { English: "I eat fish.", "Simplified Chinese": "我吃鱼。" },
  },
  {
    id: "ko-food-basic-8",
    targetLanguage: "Korean",
    targetText: "생선",
    meanings: { English: "fish, seafood", "Simplified Chinese": "鱼，鱼肉" },
    reading: "생선",
    romanization: "saengseon",
    level: "Basic",
    topic: "food",
    exampleSentence: "생선을 먹어요.",
    exampleTranslations: { English: "I eat fish.", "Simplified Chinese": "我吃鱼。" },
  },
  {
    id: "ja-food-basic-9",
    targetLanguage: "Japanese",
    targetText: "肉",
    meanings: { English: "meat, meat food", "Simplified Chinese": "肉，肉类" },
    reading: "にく",
    romanization: "niku",
    level: "Basic",
    topic: "food",
    exampleSentence: "肉を買います。",
    exampleTranslations: { English: "I buy meat.", "Simplified Chinese": "我买肉。" },
  },
  {
    id: "ko-food-basic-9",
    targetLanguage: "Korean",
    targetText: "고기",
    meanings: { English: "meat, meat food", "Simplified Chinese": "肉，肉类" },
    reading: "고기",
    romanization: "gogi",
    level: "Basic",
    topic: "food",
    exampleSentence: "고기를 사요.",
    exampleTranslations: { English: "I buy meat.", "Simplified Chinese": "我买肉。" },
  },
  {
    id: "ja-food-basic-10",
    targetLanguage: "Japanese",
    targetText: "果物",
    meanings: { English: "fruit, fruits", "Simplified Chinese": "水果，果物" },
    reading: "くだもの",
    romanization: "kudamono",
    level: "Basic",
    topic: "food",
    exampleSentence: "果物が好きです。",
    exampleTranslations: { English: "I like fruit.", "Simplified Chinese": "我喜欢水果。" },
  },
  {
    id: "ko-food-basic-10",
    targetLanguage: "Korean",
    targetText: "과일",
    meanings: { English: "fruit, fruits", "Simplified Chinese": "水果，果物" },
    reading: "과일",
    romanization: "gwail",
    level: "Basic",
    topic: "food",
    exampleSentence: "과일을 좋아해요.",
    exampleTranslations: { English: "I like fruit.", "Simplified Chinese": "我喜欢水果。" },
  },
  {
    id: "ja-food-basic-11",
    targetLanguage: "Japanese",
    targetText: "コーヒー",
    meanings: { English: "coffee, coffee drink", "Simplified Chinese": "咖啡，咖啡饮品" },
    reading: "コーヒー",
    romanization: "kohi",
    level: "Basic",
    topic: "food",
    exampleSentence: "コーヒーを飲みます。",
    exampleTranslations: { English: "I drink coffee.", "Simplified Chinese": "我喝咖啡。" },
  },
  {
    id: "ko-food-basic-11",
    targetLanguage: "Korean",
    targetText: "커피",
    meanings: { English: "coffee, coffee drink", "Simplified Chinese": "咖啡，咖啡饮品" },
    reading: "커피",
    romanization: "keopi",
    level: "Basic",
    topic: "food",
    exampleSentence: "커피를 마셔요.",
    exampleTranslations: { English: "I drink coffee.", "Simplified Chinese": "我喝咖啡。" },
  },
  {
    id: "ja-food-basic-12",
    targetLanguage: "Japanese",
    targetText: "朝食",
    meanings: { English: "breakfast, morning meal", "Simplified Chinese": "早饭，早餐" },
    reading: "ちょうしょく",
    romanization: "choshoku",
    level: "Basic",
    topic: "food",
    exampleSentence: "朝食を作ります。",
    exampleTranslations: { English: "I prepare breakfast.", "Simplified Chinese": "我准备早饭。" },
  },
  {
    id: "ko-food-basic-12",
    targetLanguage: "Korean",
    targetText: "아침 식사",
    meanings: { English: "breakfast, morning meal", "Simplified Chinese": "早饭，早餐" },
    reading: "아침 식사",
    romanization: "achim siksa",
    level: "Basic",
    topic: "food",
    exampleSentence: "아침 식사를 준비해요.",
    exampleTranslations: { English: "I prepare breakfast.", "Simplified Chinese": "我准备早饭。" },
  },
  {
    id: "ja-food-basic-13",
    targetLanguage: "Japanese",
    targetText: "昼食",
    meanings: { English: "lunch, midday meal", "Simplified Chinese": "午饭，午餐" },
    reading: "ちゅうしょく",
    romanization: "chushoku",
    level: "Basic",
    topic: "food",
    exampleSentence: "昼食を食べます。",
    exampleTranslations: { English: "I eat lunch.", "Simplified Chinese": "我吃午饭。" },
  },
  {
    id: "ko-food-basic-13",
    targetLanguage: "Korean",
    targetText: "점심",
    meanings: { English: "lunch, midday meal", "Simplified Chinese": "午饭，午餐" },
    reading: "점심",
    romanization: "jeomsim",
    level: "Basic",
    topic: "food",
    exampleSentence: "점심을 먹어요.",
    exampleTranslations: { English: "I eat lunch.", "Simplified Chinese": "我吃午饭。" },
  },
  {
    id: "ja-food-basic-14",
    targetLanguage: "Japanese",
    targetText: "夕食",
    meanings: { English: "dinner, evening meal", "Simplified Chinese": "晚饭，晚餐" },
    reading: "ゆうしょく",
    romanization: "yushoku",
    level: "Basic",
    topic: "food",
    exampleSentence: "夕食は七時です。",
    exampleTranslations: { English: "Dinner is at seven.", "Simplified Chinese": "晚饭是七点。" },
  },
  {
    id: "ko-food-basic-14",
    targetLanguage: "Korean",
    targetText: "저녁",
    meanings: { English: "dinner, evening meal", "Simplified Chinese": "晚饭，晚餐" },
    reading: "저녁",
    romanization: "jeonyeok",
    level: "Basic",
    topic: "food",
    exampleSentence: "저녁은 일곱 시예요.",
    exampleTranslations: { English: "Dinner is at seven.", "Simplified Chinese": "晚饭是七点。" },
  },
  {
    id: "ja-travel-basic-7",
    targetLanguage: "Japanese",
    targetText: "ホテル",
    meanings: { English: "hotel, inn", "Simplified Chinese": "酒店，旅馆" },
    reading: "ホテル",
    romanization: "hoteru",
    level: "Basic",
    topic: "travel",
    exampleSentence: "ホテルに泊まります。",
    exampleTranslations: { English: "I stay at a hotel.", "Simplified Chinese": "我住酒店。" },
  },
  {
    id: "ko-travel-basic-7",
    targetLanguage: "Korean",
    targetText: "호텔",
    meanings: { English: "hotel, inn", "Simplified Chinese": "酒店，旅馆" },
    reading: "호텔",
    romanization: "hotel",
    level: "Basic",
    topic: "travel",
    exampleSentence: "호텔에 묵어요.",
    exampleTranslations: { English: "I stay at a hotel.", "Simplified Chinese": "我住酒店。" },
  },
  {
    id: "ja-travel-basic-8",
    targetLanguage: "Japanese",
    targetText: "バス",
    meanings: { English: "bus, coach", "Simplified Chinese": "公交车，公共汽车" },
    reading: "バス",
    romanization: "basu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "バスに乗ります。",
    exampleTranslations: { English: "I take the bus.", "Simplified Chinese": "我坐公交车。" },
  },
  {
    id: "ko-travel-basic-8",
    targetLanguage: "Korean",
    targetText: "버스",
    meanings: { English: "bus, coach", "Simplified Chinese": "公交车，公共汽车" },
    reading: "버스",
    romanization: "beoseu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "버스를 타요.",
    exampleTranslations: { English: "I take the bus.", "Simplified Chinese": "我坐公交车。" },
  },
  {
    id: "ja-travel-basic-9",
    targetLanguage: "Japanese",
    targetText: "タクシー",
    meanings: { English: "taxi, cab", "Simplified Chinese": "出租车，的士" },
    reading: "タクシー",
    romanization: "takushi",
    level: "Basic",
    topic: "travel",
    exampleSentence: "タクシーを呼びます。",
    exampleTranslations: { English: "I call a taxi.", "Simplified Chinese": "我叫出租车。" },
  },
  {
    id: "ko-travel-basic-9",
    targetLanguage: "Korean",
    targetText: "택시",
    meanings: { English: "taxi, cab", "Simplified Chinese": "出租车，的士" },
    reading: "택시",
    romanization: "taeksi",
    level: "Basic",
    topic: "travel",
    exampleSentence: "택시를 불러요.",
    exampleTranslations: { English: "I call a taxi.", "Simplified Chinese": "我叫出租车。" },
  },
  {
    id: "ja-travel-basic-10",
    targetLanguage: "Japanese",
    targetText: "左",
    meanings: { English: "left, left side", "Simplified Chinese": "左边，左侧" },
    reading: "ひだり",
    romanization: "hidari",
    level: "Basic",
    topic: "travel",
    exampleSentence: "左に曲がります。",
    exampleTranslations: { English: "I turn left.", "Simplified Chinese": "我向左转。" },
  },
  {
    id: "ko-travel-basic-10",
    targetLanguage: "Korean",
    targetText: "왼쪽",
    meanings: { English: "left, left side", "Simplified Chinese": "左边，左侧" },
    reading: "왼쪽",
    romanization: "oenjjok",
    level: "Basic",
    topic: "travel",
    exampleSentence: "왼쪽으로 돌아요.",
    exampleTranslations: { English: "I turn left.", "Simplified Chinese": "我向左转。" },
  },
  {
    id: "ja-travel-basic-11",
    targetLanguage: "Japanese",
    targetText: "右",
    meanings: { English: "right, right side", "Simplified Chinese": "右边，右侧" },
    reading: "みぎ",
    romanization: "migi",
    level: "Basic",
    topic: "travel",
    exampleSentence: "右に曲がります。",
    exampleTranslations: { English: "I turn right.", "Simplified Chinese": "我向右转。" },
  },
  {
    id: "ko-travel-basic-11",
    targetLanguage: "Korean",
    targetText: "오른쪽",
    meanings: { English: "right, right side", "Simplified Chinese": "右边，右侧" },
    reading: "오른쪽",
    romanization: "oreunjjok",
    level: "Basic",
    topic: "travel",
    exampleSentence: "오른쪽으로 돌아요.",
    exampleTranslations: { English: "I turn right.", "Simplified Chinese": "我向右转。" },
  },
  {
    id: "ja-travel-basic-12",
    targetLanguage: "Japanese",
    targetText: "入口",
    meanings: { English: "entrance, entry", "Simplified Chinese": "入口，进口" },
    reading: "いりぐち",
    romanization: "iriguchi",
    level: "Basic",
    topic: "travel",
    exampleSentence: "入口はここです。",
    exampleTranslations: { English: "The entrance is here.", "Simplified Chinese": "入口在这里。" },
  },
  {
    id: "ko-travel-basic-12",
    targetLanguage: "Korean",
    targetText: "입구",
    meanings: { English: "entrance, entry", "Simplified Chinese": "入口，进口" },
    reading: "입구",
    romanization: "ipgu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "입구는 여기예요.",
    exampleTranslations: { English: "The entrance is here.", "Simplified Chinese": "入口在这里。" },
  },
  {
    id: "ja-travel-basic-13",
    targetLanguage: "Japanese",
    targetText: "出口",
    meanings: { English: "exit, way out", "Simplified Chinese": "出口，出路" },
    reading: "でぐち",
    romanization: "deguchi",
    level: "Basic",
    topic: "travel",
    exampleSentence: "出口はあそこです。",
    exampleTranslations: { English: "The exit is over there.", "Simplified Chinese": "出口在那里。" },
  },
  {
    id: "ko-travel-basic-13",
    targetLanguage: "Korean",
    targetText: "출구",
    meanings: { English: "exit, way out", "Simplified Chinese": "出口，出路" },
    reading: "출구",
    romanization: "chulgu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "출구는 저기예요.",
    exampleTranslations: { English: "The exit is over there.", "Simplified Chinese": "出口在那里。" },
  },
  {
    id: "ja-travel-basic-14",
    targetLanguage: "Japanese",
    targetText: "荷物",
    meanings: { English: "luggage, baggage", "Simplified Chinese": "行李，行李物品" },
    reading: "にもつ",
    romanization: "nimotsu",
    level: "Basic",
    topic: "travel",
    exampleSentence: "荷物が重いです。",
    exampleTranslations: { English: "The luggage is heavy.", "Simplified Chinese": "行李很重。" },
  },
  {
    id: "ko-travel-basic-14",
    targetLanguage: "Korean",
    targetText: "짐",
    meanings: { English: "luggage, baggage", "Simplified Chinese": "行李，行李物品" },
    reading: "짐",
    romanization: "jim",
    level: "Basic",
    topic: "travel",
    exampleSentence: "짐이 무거워요.",
    exampleTranslations: { English: "The luggage is heavy.", "Simplified Chinese": "行李很重。" },
  },
  {
    id: "ja-life-basic-7",
    targetLanguage: "Japanese",
    targetText: "朝",
    meanings: { English: "morning, early day", "Simplified Chinese": "早上，早晨" },
    reading: "あさ",
    romanization: "asa",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "朝に散歩します。",
    exampleTranslations: { English: "I take a walk in the morning.", "Simplified Chinese": "我早上散步。" },
  },
  {
    id: "ko-life-basic-7",
    targetLanguage: "Korean",
    targetText: "아침",
    meanings: { English: "morning, early day", "Simplified Chinese": "早上，早晨" },
    reading: "아침",
    romanization: "achim",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "아침에 산책해요.",
    exampleTranslations: { English: "I take a walk in the morning.", "Simplified Chinese": "我早上散步。" },
  },
  {
    id: "ja-life-basic-8",
    targetLanguage: "Japanese",
    targetText: "夜",
    meanings: { English: "night, evening", "Simplified Chinese": "晚上，夜晚" },
    reading: "よる",
    romanization: "yoru",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "夜に勉強します。",
    exampleTranslations: { English: "I study at night.", "Simplified Chinese": "我晚上学习。" },
  },
  {
    id: "ko-life-basic-8",
    targetLanguage: "Korean",
    targetText: "밤",
    meanings: { English: "night, evening", "Simplified Chinese": "晚上，夜晚" },
    reading: "밤",
    romanization: "bam",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "밤에 공부해요.",
    exampleTranslations: { English: "I study at night.", "Simplified Chinese": "我晚上学习。" },
  },
  {
    id: "ja-life-basic-9",
    targetLanguage: "Japanese",
    targetText: "部屋",
    meanings: { English: "room, space", "Simplified Chinese": "房间，屋子" },
    reading: "へや",
    romanization: "heya",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "部屋を掃除します。",
    exampleTranslations: { English: "I clean the room.", "Simplified Chinese": "我打扫房间。" },
  },
  {
    id: "ko-life-basic-9",
    targetLanguage: "Korean",
    targetText: "방",
    meanings: { English: "room, space", "Simplified Chinese": "房间，屋子" },
    reading: "방",
    romanization: "bang",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "방을 청소해요.",
    exampleTranslations: { English: "I clean the room.", "Simplified Chinese": "我打扫房间。" },
  },
  {
    id: "ja-life-basic-10",
    targetLanguage: "Japanese",
    targetText: "服",
    meanings: { English: "clothes, clothing", "Simplified Chinese": "衣服，服装" },
    reading: "ふく",
    romanization: "fuku",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "新しい服を買います。",
    exampleTranslations: { English: "I buy new clothes.", "Simplified Chinese": "我买新衣服。" },
  },
  {
    id: "ko-life-basic-10",
    targetLanguage: "Korean",
    targetText: "옷",
    meanings: { English: "clothes, clothing", "Simplified Chinese": "衣服，服装" },
    reading: "옷",
    romanization: "ot",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "새 옷을 사요.",
    exampleTranslations: { English: "I buy new clothes.", "Simplified Chinese": "我买新衣服。" },
  },
  {
    id: "ja-life-basic-11",
    targetLanguage: "Japanese",
    targetText: "お金",
    meanings: { English: "money, cash", "Simplified Chinese": "钱，现金" },
    reading: "おかね",
    romanization: "okane",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "お金を払います。",
    exampleTranslations: { English: "I pay money.", "Simplified Chinese": "我付钱。" },
  },
  {
    id: "ko-life-basic-11",
    targetLanguage: "Korean",
    targetText: "돈",
    meanings: { English: "money, cash", "Simplified Chinese": "钱，现金" },
    reading: "돈",
    romanization: "don",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "돈을 내요.",
    exampleTranslations: { English: "I pay money.", "Simplified Chinese": "我付钱。" },
  },
  {
    id: "ja-life-basic-12",
    targetLanguage: "Japanese",
    targetText: "時間",
    meanings: { English: "time, hour", "Simplified Chinese": "时间，时刻" },
    reading: "じかん",
    romanization: "jikan",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "時間があります。",
    exampleTranslations: { English: "I have time.", "Simplified Chinese": "我有时间。" },
  },
  {
    id: "ko-life-basic-12",
    targetLanguage: "Korean",
    targetText: "시간",
    meanings: { English: "time, hour", "Simplified Chinese": "时间，时刻" },
    reading: "시간",
    romanization: "sigan",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "시간이 있어요.",
    exampleTranslations: { English: "I have time.", "Simplified Chinese": "我有时间。" },
  },
  {
    id: "ja-life-basic-13",
    targetLanguage: "Japanese",
    targetText: "家族",
    meanings: { English: "family, relatives", "Simplified Chinese": "家人，亲人" },
    reading: "かぞく",
    romanization: "kazoku",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "家族と話します。",
    exampleTranslations: { English: "I talk with my family.", "Simplified Chinese": "我和家人说话。" },
  },
  {
    id: "ko-life-basic-13",
    targetLanguage: "Korean",
    targetText: "가족",
    meanings: { English: "family, relatives", "Simplified Chinese": "家人，亲人" },
    reading: "가족",
    romanization: "gajok",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "가족과 이야기해요.",
    exampleTranslations: { English: "I talk with my family.", "Simplified Chinese": "我和家人说话。" },
  },
  {
    id: "ja-life-basic-14",
    targetLanguage: "Japanese",
    targetText: "名前",
    meanings: { English: "name, given name", "Simplified Chinese": "名字，姓名" },
    reading: "なまえ",
    romanization: "namae",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "名前を書きます。",
    exampleTranslations: { English: "I write my name.", "Simplified Chinese": "我写名字。" },
  },
  {
    id: "ko-life-basic-14",
    targetLanguage: "Korean",
    targetText: "이름",
    meanings: { English: "name, given name", "Simplified Chinese": "名字，姓名" },
    reading: "이름",
    romanization: "ireum",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "이름을 써요.",
    exampleTranslations: { English: "I write my name.", "Simplified Chinese": "我写名字。" },
  },
  {
    id: "ja-numbers-basic-5",
    targetLanguage: "Japanese",
    targetText: "一",
    meanings: { English: "one, 1", "Simplified Chinese": "一，数字一" },
    reading: "いち",
    romanization: "ichi",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "一つあります。",
    exampleTranslations: { English: "There is one.", "Simplified Chinese": "有一个。" },
  },
  {
    id: "ko-numbers-basic-5",
    targetLanguage: "Korean",
    targetText: "하나",
    meanings: { English: "one, 1", "Simplified Chinese": "一，数字一" },
    reading: "하나",
    romanization: "hana",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "하나 있어요.",
    exampleTranslations: { English: "There is one.", "Simplified Chinese": "有一个。" },
  },
  {
    id: "ja-numbers-basic-6",
    targetLanguage: "Japanese",
    targetText: "二",
    meanings: { English: "two, 2", "Simplified Chinese": "二，数字二" },
    reading: "に",
    romanization: "ni",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "二つください。",
    exampleTranslations: { English: "Two, please.", "Simplified Chinese": "请给我两个。" },
  },
  {
    id: "ko-numbers-basic-6",
    targetLanguage: "Korean",
    targetText: "둘",
    meanings: { English: "two, 2", "Simplified Chinese": "二，数字二" },
    reading: "둘",
    romanization: "dul",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "둘 주세요.",
    exampleTranslations: { English: "Two, please.", "Simplified Chinese": "请给我两个。" },
  },
  {
    id: "ja-numbers-basic-7",
    targetLanguage: "Japanese",
    targetText: "三",
    meanings: { English: "three, 3", "Simplified Chinese": "三，数字三" },
    reading: "さん",
    romanization: "san",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "三人います。",
    exampleTranslations: { English: "There are three people.", "Simplified Chinese": "有三个人。" },
  },
  {
    id: "ko-numbers-basic-7",
    targetLanguage: "Korean",
    targetText: "셋",
    meanings: { English: "three, 3", "Simplified Chinese": "三，数字三" },
    reading: "셋",
    romanization: "set",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "셋이 있어요.",
    exampleTranslations: { English: "There are three people.", "Simplified Chinese": "有三个人。" },
  },
  {
    id: "ja-numbers-basic-8",
    targetLanguage: "Japanese",
    targetText: "四",
    meanings: { English: "four, 4", "Simplified Chinese": "四，数字四" },
    reading: "よん / し",
    romanization: "yon / shi",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "四時です。",
    exampleTranslations: { English: "It is four o'clock.", "Simplified Chinese": "现在四点。" },
  },
  {
    id: "ko-numbers-basic-8",
    targetLanguage: "Korean",
    targetText: "넷",
    meanings: { English: "four, 4", "Simplified Chinese": "四，数字四" },
    reading: "넷",
    romanization: "net",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "네 시예요.",
    exampleTranslations: { English: "It is four o'clock.", "Simplified Chinese": "现在四点。" },
  },
  {
    id: "ja-numbers-basic-9",
    targetLanguage: "Japanese",
    targetText: "五",
    meanings: { English: "five, 5", "Simplified Chinese": "五，数字五" },
    reading: "ご",
    romanization: "go",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "五分待ちます。",
    exampleTranslations: { English: "I wait five minutes.", "Simplified Chinese": "我等五分钟。" },
  },
  {
    id: "ko-numbers-basic-9",
    targetLanguage: "Korean",
    targetText: "다섯",
    meanings: { English: "five, 5", "Simplified Chinese": "五，数字五" },
    reading: "다섯",
    romanization: "daseot",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "다섯 분 기다려요.",
    exampleTranslations: { English: "I wait five minutes.", "Simplified Chinese": "我等五分钟。" },
  },
  {
    id: "ja-numbers-basic-10",
    targetLanguage: "Japanese",
    targetText: "六",
    meanings: { English: "six, 6", "Simplified Chinese": "六，数字六" },
    reading: "ろく",
    romanization: "roku",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "六時に起きます。",
    exampleTranslations: { English: "I get up at six.", "Simplified Chinese": "我六点起床。" },
  },
  {
    id: "ko-numbers-basic-10",
    targetLanguage: "Korean",
    targetText: "여섯",
    meanings: { English: "six, 6", "Simplified Chinese": "六，数字六" },
    reading: "여섯",
    romanization: "yeoseot",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "여섯 시에 일어나요.",
    exampleTranslations: { English: "I get up at six.", "Simplified Chinese": "我六点起床。" },
  },
  {
    id: "ja-numbers-basic-11",
    targetLanguage: "Japanese",
    targetText: "八",
    meanings: { English: "eight, 8", "Simplified Chinese": "八，数字八" },
    reading: "はち",
    romanization: "hachi",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "八時に出ます。",
    exampleTranslations: { English: "I leave at eight.", "Simplified Chinese": "我八点出门。" },
  },
  {
    id: "ko-numbers-basic-11",
    targetLanguage: "Korean",
    targetText: "여덟",
    meanings: { English: "eight, 8", "Simplified Chinese": "八，数字八" },
    reading: "여덟",
    romanization: "yeodeol",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "여덟 시에 나가요.",
    exampleTranslations: { English: "I leave at eight.", "Simplified Chinese": "我八点出门。" },
  },
  {
    id: "ja-numbers-basic-12",
    targetLanguage: "Japanese",
    targetText: "九",
    meanings: { English: "nine, 9", "Simplified Chinese": "九，数字九" },
    reading: "きゅう / く",
    romanization: "kyu / ku",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "九時に寝ます。",
    exampleTranslations: { English: "I sleep at nine.", "Simplified Chinese": "我九点睡觉。" },
  },
  {
    id: "ko-numbers-basic-12",
    targetLanguage: "Korean",
    targetText: "아홉",
    meanings: { English: "nine, 9", "Simplified Chinese": "九，数字九" },
    reading: "아홉",
    romanization: "ahop",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "아홉 시에 자요.",
    exampleTranslations: { English: "I sleep at nine.", "Simplified Chinese": "我九点睡觉。" },
  },
  {
    id: "ja-numbers-basic-13",
    targetLanguage: "Japanese",
    targetText: "十",
    meanings: { English: "ten, 10", "Simplified Chinese": "十，数字十" },
    reading: "じゅう",
    romanization: "ju",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "十個あります。",
    exampleTranslations: { English: "There are ten.", "Simplified Chinese": "有十个。" },
  },
  {
    id: "ko-numbers-basic-13",
    targetLanguage: "Korean",
    targetText: "열",
    meanings: { English: "ten, 10", "Simplified Chinese": "十，数字十" },
    reading: "열",
    romanization: "yeol",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "열 개 있어요.",
    exampleTranslations: { English: "There are ten.", "Simplified Chinese": "有十个。" },
  },
  {
    id: "ja-numbers-basic-14",
    targetLanguage: "Japanese",
    targetText: "たくさん",
    meanings: { English: "many, a lot", "Simplified Chinese": "很多，许多" },
    reading: "たくさん",
    romanization: "takusan",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "本がたくさんあります。",
    exampleTranslations: { English: "There are many books.", "Simplified Chinese": "有很多书。" },
  },
  {
    id: "ko-numbers-basic-14",
    targetLanguage: "Korean",
    targetText: "많이",
    meanings: { English: "many, a lot", "Simplified Chinese": "很多，许多" },
    reading: "많이",
    romanization: "mani",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "책이 많이 있어요.",
    exampleTranslations: { English: "There are many books.", "Simplified Chinese": "有很多书。" },
  },
  {
    id: "ja-verbs-basic-7",
    targetLanguage: "Japanese",
    targetText: "飲む",
    meanings: { English: "drink, have a drink", "Simplified Chinese": "喝，饮用" },
    reading: "のむ",
    romanization: "nomu",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "水を飲みます。",
    exampleTranslations: { English: "I drink water.", "Simplified Chinese": "我喝水。" },
  },
  {
    id: "ko-verbs-basic-7",
    targetLanguage: "Korean",
    targetText: "마시다",
    meanings: { English: "drink, have a drink", "Simplified Chinese": "喝，饮用" },
    reading: "마시다",
    romanization: "masida",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "물을 마셔요.",
    exampleTranslations: { English: "I drink water.", "Simplified Chinese": "我喝水。" },
  },
  {
    id: "ja-verbs-basic-8",
    targetLanguage: "Japanese",
    targetText: "読む",
    meanings: { English: "read, study", "Simplified Chinese": "读，阅读" },
    reading: "よむ",
    romanization: "yomu",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "本を読みます。",
    exampleTranslations: { English: "I read a book.", "Simplified Chinese": "我读书。" },
  },
  {
    id: "ko-verbs-basic-8",
    targetLanguage: "Korean",
    targetText: "읽다",
    meanings: { English: "read, study", "Simplified Chinese": "读，阅读" },
    reading: "읽다",
    romanization: "ikda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "책을 읽어요.",
    exampleTranslations: { English: "I read a book.", "Simplified Chinese": "我读书。" },
  },
  {
    id: "ja-verbs-basic-9",
    targetLanguage: "Japanese",
    targetText: "書く",
    meanings: { English: "write, compose", "Simplified Chinese": "写，书写" },
    reading: "かく",
    romanization: "kaku",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "手紙を書きます。",
    exampleTranslations: { English: "I write a letter.", "Simplified Chinese": "我写信。" },
  },
  {
    id: "ko-verbs-basic-9",
    targetLanguage: "Korean",
    targetText: "쓰다",
    meanings: { English: "write, compose", "Simplified Chinese": "写，书写" },
    reading: "쓰다",
    romanization: "sseuda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "편지를 써요.",
    exampleTranslations: { English: "I write a letter.", "Simplified Chinese": "我写信。" },
  },
  {
    id: "ja-verbs-basic-10",
    targetLanguage: "Japanese",
    targetText: "来る",
    meanings: { English: "come, arrive", "Simplified Chinese": "来，到来" },
    reading: "くる",
    romanization: "kuru",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "友達が来ます。",
    exampleTranslations: { English: "A friend comes.", "Simplified Chinese": "朋友来了。" },
  },
  {
    id: "ko-verbs-basic-10",
    targetLanguage: "Korean",
    targetText: "오다",
    meanings: { English: "come, arrive", "Simplified Chinese": "来，到来" },
    reading: "오다",
    romanization: "oda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "친구가 와요.",
    exampleTranslations: { English: "A friend comes.", "Simplified Chinese": "朋友来了。" },
  },
  {
    id: "ja-verbs-basic-11",
    targetLanguage: "Japanese",
    targetText: "帰る",
    meanings: { English: "return, go back", "Simplified Chinese": "回来，返回" },
    reading: "かえる",
    romanization: "kaeru",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "家に帰ります。",
    exampleTranslations: { English: "I return home.", "Simplified Chinese": "我回家。" },
  },
  {
    id: "ko-verbs-basic-11",
    targetLanguage: "Korean",
    targetText: "돌아가다",
    meanings: { English: "return, go back", "Simplified Chinese": "回来，返回" },
    reading: "돌아가다",
    romanization: "doragada",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "집에 돌아가요.",
    exampleTranslations: { English: "I return home.", "Simplified Chinese": "我回家。" },
  },
  {
    id: "ja-verbs-basic-12",
    targetLanguage: "Japanese",
    targetText: "開ける",
    meanings: { English: "open, unlock", "Simplified Chinese": "打开，开启" },
    reading: "あける",
    romanization: "akeru",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "窓を開けます。",
    exampleTranslations: { English: "I open the window.", "Simplified Chinese": "我打开窗户。" },
  },
  {
    id: "ko-verbs-basic-12",
    targetLanguage: "Korean",
    targetText: "열다",
    meanings: { English: "open, unlock", "Simplified Chinese": "打开，开启" },
    reading: "열다",
    romanization: "yeolda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "창문을 열어요.",
    exampleTranslations: { English: "I open the window.", "Simplified Chinese": "我打开窗户。" },
  },
  {
    id: "ja-verbs-basic-13",
    targetLanguage: "Japanese",
    targetText: "閉める",
    meanings: { English: "close, shut", "Simplified Chinese": "关上，关闭" },
    reading: "しめる",
    romanization: "shimeru",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "ドアを閉めます。",
    exampleTranslations: { English: "I close the door.", "Simplified Chinese": "我关门。" },
  },
  {
    id: "ko-verbs-basic-13",
    targetLanguage: "Korean",
    targetText: "닫다",
    meanings: { English: "close, shut", "Simplified Chinese": "关上，关闭" },
    reading: "닫다",
    romanization: "datda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "문을 닫아요.",
    exampleTranslations: { English: "I close the door.", "Simplified Chinese": "我关门。" },
  },
  {
    id: "ja-verbs-basic-14",
    targetLanguage: "Japanese",
    targetText: "使う",
    meanings: { English: "use, utilize", "Simplified Chinese": "使用，运用" },
    reading: "つかう",
    romanization: "tsukau",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "スマホを使います。",
    exampleTranslations: { English: "I use a phone.", "Simplified Chinese": "我使用手机。" },
  },
  {
    id: "ko-verbs-basic-14",
    targetLanguage: "Korean",
    targetText: "사용하다",
    meanings: { English: "use, utilize", "Simplified Chinese": "使用，运用" },
    reading: "사용하다",
    romanization: "sayonghada",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "휴대폰을 사용해요.",
    exampleTranslations: { English: "I use a phone.", "Simplified Chinese": "我使用手机。" },
  },
  {
    id: "ja-food-basic-15",
    targetLanguage: "Japanese",
    targetText: "お菓子",
    meanings: { English: "snack, light food", "Simplified Chinese": "零食，小吃" },
    reading: "おかし",
    romanization: "okashi",
    level: "Basic",
    topic: "food",
    exampleSentence: "お菓子を少し食べます。",
    exampleTranslations: { English: "I eat a small snack.", "Simplified Chinese": "我吃一点零食。" },
  },
  {
    id: "ko-food-basic-15",
    targetLanguage: "Korean",
    targetText: "과자",
    meanings: { English: "snack, light food", "Simplified Chinese": "零食，小吃" },
    reading: "과자",
    romanization: "gwaja",
    level: "Basic",
    topic: "food",
    exampleSentence: "과자를 조금 먹어요.",
    exampleTranslations: { English: "I eat a small snack.", "Simplified Chinese": "我吃一点零食。" },
  },
  {
    id: "ja-travel-basic-15",
    targetLanguage: "Japanese",
    targetText: "橋",
    meanings: { English: "bridge, overpass", "Simplified Chinese": "桥，桥梁" },
    reading: "はし",
    romanization: "hashi",
    level: "Basic",
    topic: "travel",
    exampleSentence: "橋を渡ります。",
    exampleTranslations: { English: "I cross the bridge.", "Simplified Chinese": "我过桥。" },
  },
  {
    id: "ko-travel-basic-15",
    targetLanguage: "Korean",
    targetText: "다리",
    meanings: { English: "bridge, overpass", "Simplified Chinese": "桥，桥梁" },
    reading: "다리",
    romanization: "dari",
    level: "Basic",
    topic: "travel",
    exampleSentence: "다리를 건너요.",
    exampleTranslations: { English: "I cross the bridge.", "Simplified Chinese": "我过桥。" },
  },
  {
    id: "ja-life-basic-15",
    targetLanguage: "Japanese",
    targetText: "鍵",
    meanings: { English: "key, house key", "Simplified Chinese": "钥匙，门钥匙" },
    reading: "かぎ",
    romanization: "kagi",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "鍵を持っています。",
    exampleTranslations: { English: "I have the key.", "Simplified Chinese": "我有钥匙。" },
  },
  {
    id: "ko-life-basic-15",
    targetLanguage: "Korean",
    targetText: "열쇠",
    meanings: { English: "key, house key", "Simplified Chinese": "钥匙，门钥匙" },
    reading: "열쇠",
    romanization: "yeolsoe",
    level: "Basic",
    topic: "daily life",
    exampleSentence: "열쇠를 가지고 있어요.",
    exampleTranslations: { English: "I have the key.", "Simplified Chinese": "我有钥匙。" },
  },
  {
    id: "ja-numbers-basic-15",
    targetLanguage: "Japanese",
    targetText: "零",
    meanings: { English: "zero, 0", "Simplified Chinese": "零，数字零" },
    reading: "れい",
    romanization: "rei",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "答えは零です。",
    exampleTranslations: { English: "The answer is zero.", "Simplified Chinese": "答案是零。" },
  },
  {
    id: "ko-numbers-basic-15",
    targetLanguage: "Korean",
    targetText: "영",
    meanings: { English: "zero, 0", "Simplified Chinese": "零，数字零" },
    reading: "영",
    romanization: "yeong",
    level: "Basic",
    topic: "numbers",
    exampleSentence: "답은 영이에요.",
    exampleTranslations: { English: "The answer is zero.", "Simplified Chinese": "答案是零。" },
  },
  {
    id: "ja-verbs-basic-15",
    targetLanguage: "Japanese",
    targetText: "洗う",
    meanings: { English: "wash, clean", "Simplified Chinese": "洗，清洗" },
    reading: "あらう",
    romanization: "arau",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "手を洗います。",
    exampleTranslations: { English: "I wash my hands.", "Simplified Chinese": "我洗手。" },
  },
  {
    id: "ko-verbs-basic-15",
    targetLanguage: "Korean",
    targetText: "씻다",
    meanings: { English: "wash, clean", "Simplified Chinese": "洗，清洗" },
    reading: "씻다",
    romanization: "ssitda",
    level: "Basic",
    topic: "common verbs",
    exampleSentence: "손을 씻어요.",
    exampleTranslations: { English: "I wash my hands.", "Simplified Chinese": "我洗手。" },
  }
];
