import type { Topic, VocabItem } from "./vocabulary";

type NounPair = [topic: Topic, en: string, zh: string, ja: string, jaReading: string, jaRomanization: string, ko: string];

const makePair = (level: "Intermediate" | "Advanced", index: number, [topic, en, zh, ja, jaReading, jaRomanization, ko]: NounPair): VocabItem[] => {
  const suffix = String(index + 1).padStart(3, "0");
  const levelKey = level === "Intermediate" ? "intermediate" : "advanced";
  return [
    { id: `ja-noun-${levelKey}-${suffix}`, targetLanguage: "Japanese", targetText: ja, meanings: { English: en, "Simplified Chinese": zh }, reading: jaReading, romanization: jaRomanization, level, topic, exampleSentence: `${ja}について確認します。`, exampleTranslations: { English: `We will review ${en}.`, "Simplified Chinese": `我们确认“${zh}”相关内容。` } },
    { id: `ko-noun-${levelKey}-${suffix}`, targetLanguage: "Korean", targetText: ko, meanings: { English: en, "Simplified Chinese": zh }, reading: ko, romanization: "", level, topic, exampleSentence: `${ko}에 대해 확인합니다.`, exampleTranslations: { English: `We will review ${en}.`, "Simplified Chinese": `我们确认“${zh}”相关内容。` } },
  ];
};

const intermediateNouns: NounPair[] = [
  ["work", "agenda", "议题", "議題", "ぎだい", "gidai", "안건"],
  ["work", "office supplies", "办公用品", "備品", "びひん", "bihin", "비품"],
  ["work", "internal approval", "内部审批", "稟議", "りんぎ", "ringi", "품의"],
  ["work", "invoice", "账单/发票", "請求書", "せいきゅうしょ", "seikyuusho", "청구서"],
  ["work", "quotation", "报价单", "見積書", "みつもりしょ", "mitsumorisho", "견적서"],
  ["work", "budget", "预算", "予算", "よさん", "yosan", "예산"],
  ["work", "revenue", "营业收入", "売上", "うりあげ", "uriage", "매출"],
  ["work", "profit", "利润", "利益", "りえき", "rieki", "이익"],
  ["work", "loss", "损失", "損失", "そんしつ", "sonshitsu", "손실"],
  ["work", "inventory", "库存", "在庫", "ざいこ", "zaiko", "재고"],
  ["work", "warehouse", "仓库", "倉庫", "そうこ", "souko", "창고"],
  ["work", "shipment", "出货", "出荷", "しゅっか", "shukka", "출하"],
  ["work", "supplier", "供应商", "仕入先", "しいれさき", "shiiresaki", "공급사"],
  ["work", "colleague", "同事", "同僚", "どうりょう", "douryou", "동료"],
  ["work", "supervisor", "上司", "上司", "じょうし", "joushi", "상사"],
  ["work", "subordinate", "下属", "部下", "ぶか", "buka", "부하"],
  ["work", "branch office", "分店/分公司", "支店", "してん", "shiten", "지점"],
  ["work", "headquarters", "总部", "本社", "ほんしゃ", "honsha", "본사"],
  ["work", "payroll", "工资单/薪资", "給与", "きゅうよ", "kyuuyo", "급여"],
  ["work", "allowance", "津贴", "手当", "てあて", "teate", "수당"],
  ["work", "expense", "经费", "経費", "けいひ", "keihi", "경비"],
  ["work", "receipt", "收据", "領収書", "りょうしゅうしょ", "ryoushuusho", "영수증"],
  ["work", "attachment", "附件", "添付", "てんぷ", "tenpu", "첨부"],
  ["work", "draft", "草案", "草案", "そうあん", "souan", "초안"],
  ["travel", "platform", "站台", "ホーム", "ほーむ", "hoomu", "승강장"],
  ["travel", "boarding", "登机", "搭乗", "とうじょう", "toujou", "탑승"],
  ["travel", "boarding pass", "登机牌", "搭乗券", "とうじょうけん", "toujouken", "탑승권"],
  ["travel", "baggage", "行李", "手荷物", "てにもつ", "tenimotsu", "수하물"],
  ["travel", "suitcase", "行李箱", "スーツケース", "すーつけーす", "suutsukeesu", "여행가방"],
  ["travel", "layover", "经停/中转", "乗継", "のりつぎ", "noritsugi", "경유"],
  ["travel", "visa", "签证", "ビザ", "びざ", "biza", "비자"],
  ["travel", "immigration control", "出入境", "出入国", "しゅつにゅうこく", "shutsunyuukoku", "출입국"],
  ["travel", "screening", "审查", "審査", "しんさ", "shinsa", "심사"],
  ["travel", "terminal", "航站楼", "ターミナル", "たーみなる", "taaminaru", "터미널"],
  ["travel", "runway", "跑道", "滑走路", "かっそうろ", "kassouro", "활주로"],
  ["travel", "information board", "信息牌", "案内板", "あんないばん", "annaiban", "안내판"],
  ["travel", "seat map", "座位图", "座席表", "ざせきひょう", "zasekihyou", "좌석표"],
  ["travel", "lobby", "大厅", "ロビー", "ろびー", "robii", "로비"],
  ["travel", "transfer station", "换乘站", "乗換駅", "のりかええき", "norikaeeki", "환승역"],
  ["travel", "itinerary", "行程", "旅程", "りょてい", "ryotei", "여정"],
  ["travel", "hostel", "青年旅舍", "ホステル", "ほすてる", "hosuteru", "호스텔"],
  ["travel", "mileage", "里程", "マイル", "まいる", "mairu", "마일리지"],
  ["travel", "guidebook", "旅行指南", "ガイドブック", "がいどぶっく", "gaidobukku", "안내책자"],
  ["travel", "currency", "货币", "通貨", "つうか", "tsuuka", "통화"],
  ["travel", "exchange rate", "汇率", "為替", "かわせ", "kawase", "환율"],
  ["travel", "deposit", "押金", "保証金", "ほしょうきん", "hoshoukin", "보증금"],
  ["travel", "cart", "手推车", "カート", "かーと", "kaato", "카트"],
  ["daily life", "maintenance fee", "管理费", "管理費", "かんりひ", "kanrihi", "관리비"],
  ["daily life", "electricity bill", "电费", "電気料金", "でんきりょうきん", "denkiryoukin", "전기요금"],
  ["daily life", "loan", "贷款", "ローン", "ろーん", "roon", "대출"],
  ["daily life", "appliance", "家电", "家電", "かでん", "kaden", "가전"],
  ["daily life", "laundry", "洗好的衣物", "洗濯物", "せんたくもの", "sentakumono", "빨래"],
  ["daily life", "trash", "垃圾", "ごみ", "ごみ", "gomi", "쓰레기"],
  ["daily life", "recycling", "回收利用", "再利用", "さいりよう", "sairiyou", "재활용"],
  ["daily life", "parcel", "包裹", "小包", "こづつみ", "kozutsumi", "택배"],
  ["daily life", "delivery", "配送", "配達", "はいたつ", "haitatsu", "배송"],
  ["daily life", "calendar", "日历", "カレンダー", "かれんだー", "karendaa", "달력"],
  ["daily life", "cash", "现金", "現金", "げんきん", "genkin", "현금"],
  ["daily life", "charger", "充电器", "充電器", "じゅうでんき", "juudenki", "충전기"],
  ["daily life", "adapter", "适配器", "アダプター", "あだぷたー", "adaputaa", "어댑터"],
  ["daily life", "raincoat", "雨衣", "レインコート", "れいんこーと", "reinkooto", "우비"],
  ["daily life", "handkerchief", "手帕", "ハンカチ", "はんかち", "hankachi", "손수건"],
  ["daily life", "residents association", "居民会", "自治会", "じちかい", "jichikai", "주민회"],
  ["daily life", "clinic", "诊所", "診療所", "しんりょうじょ", "shinryoujo", "의원"],
  ["school", "syllabus", "课程大纲", "シラバス", "しらばす", "shirabasu", "강의계획서"],
  ["school", "seminar", "研讨课", "ゼミ", "ぜみ", "zemi", "세미나"],
  ["school", "laboratory", "研究室", "研究室", "けんきゅうしつ", "kenkyuushitsu", "연구실"],
  ["school", "campus", "校园", "キャンパス", "きゃんぱす", "kyanpasu", "캠퍼스"],
  ["school", "dormitory", "宿舍", "寮", "りょう", "ryou", "기숙사"],
  ["school", "student status", "学籍", "学籍", "がくせき", "gakuseki", "학적"],
  ["school", "transcript", "成绩单", "成績証明書", "せいせきしょうめいしょ", "seisekishoumeisho", "성적증명서"],
  ["school", "diploma", "毕业证书", "卒業証書", "そつぎょうしょうしょ", "sotsugyoushousho", "졸업장"],
  ["school", "certificate", "证明书", "証明書", "しょうめいしょ", "shoumeisho", "증명서"],
  ["school", "faculty", "学部", "学部", "がくぶ", "gakubu", "학부"],
  ["school", "minor", "辅修", "副専攻", "ふくせんこう", "fukusenkou", "부전공"],
  ["school", "bibliography", "参考文献", "参考文献", "さんこうぶんけん", "sankoubunken", "참고문헌"],
  ["school", "citation", "引用", "引用", "いんよう", "inyou", "인용"],
  ["school", "plagiarism", "抄袭", "剽窃", "ひょうせつ", "hyousetsu", "표절"],
  ["school", "survey", "问卷调查", "調査", "ちょうさ", "chousa", "설문"],
  ["school", "questionnaire", "问卷", "質問票", "しつもんひょう", "shitsumonhyou", "설문지"],
  ["school", "internship", "实习", "インターン", "いんたーん", "intaan", "인턴십"],
  ["school", "mentor", "导师", "指導者", "しどうしゃ", "shidousha", "멘토"],
  ["school", "school regulations", "校规", "校則", "こうそく", "kousoku", "학칙"],
  ["school", "elective", "选修课", "選択科目", "せんたくかもく", "sentakukamoku", "선택과목"],
  ["school", "prerequisite", "先修条件", "前提科目", "ぜんていかもく", "zenteikamoku", "선수과목"],
  ["school", "course registration", "选课注册", "履修登録", "りしゅうとうろく", "rishuutouroku", "수강신청"],
  ["school", "alumni", "校友", "卒業生", "そつぎょうせい", "sotsugyousei", "동문"],
  ["anime/drama", "storyboard", "分镜", "絵コンテ", "えこんて", "ekonte", "스토리보드"],
  ["anime/drama", "plot", "剧情", "筋書き", "すじがき", "sujigaki", "줄거리"],
  ["anime/drama", "setting", "设定", "設定", "せってい", "settei", "설정"],
  ["anime/drama", "season", "季度/季", "シーズン", "しーずん", "shiizun", "시즌"],
  ["anime/drama", "cast", "演员阵容", "配役", "はいやく", "haiyaku", "배역"],
  ["anime/drama", "soundtrack", "原声带", "サントラ", "さんとら", "santora", "사운드트랙"],
  ["anime/drama", "key animation", "原画", "原画", "げんが", "genga", "원화"],
  ["anime/drama", "design", "设计", "デザイン", "でざいん", "dezain", "디자인"],
  ["anime/drama", "opening", "片头", "オープニング", "おーぷにんぐ", "oopuningu", "오프닝"],
  ["anime/drama", "ending", "片尾", "エンディング", "えんでぃんぐ", "endingu", "엔딩"],
  ["anime/drama", "bonus feature", "特典", "特典", "とくてん", "tokuten", "특전"],
  ["anime/drama", "fandom", "粉丝圈", "ファンダム", "ふぁんだむ", "fandamu", "팬덤"],
  ["anime/drama", "merchandise", "周边", "グッズ", "ぐっず", "guzzu", "굿즈"],
  ["anime/drama", "figure", "手办", "フィギュア", "ふぃぎゅあ", "figyua", "피규어"],
  ["anime/drama", "adaptation", "改编", "映像化", "えいぞうか", "eizouka", "영상화"],
  ["anime/drama", "remake", "重制版", "リメイク", "りめいく", "rimeiku", "리메이크"],
  ["anime/drama", "dubbing", "配音版", "吹替", "ふきかえ", "fukikae", "더빙"],
  ["anime/drama", "rating", "收视率", "視聴率", "しちょうりつ", "shichouritsu", "시청률"],
  ["anime/drama", "premiere", "首演", "初演", "しょえん", "shoen", "초연"],
  ["anime/drama", "cliffhanger", "悬念结尾", "クリフハンガー", "くりふはんがー", "kurifuhangaa", "클리프행어"],
  ["anime/drama", "genre", "类型", "ジャンル", "じゃんる", "janru", "장르"],
  ["anime/drama", "mystery", "悬疑", "ミステリー", "みすてりー", "misuterii", "미스터리"],
  ["anime/drama", "romance", "爱情题材", "恋愛", "れんあい", "ren'ai", "로맨스"],
  ["work", "billing", "请款", "請求", "せいきゅう", "seikyuu", "청구"],
  ["work", "operation", "运行", "稼働", "かどう", "kadou", "가동"],
  ["work", "guide", "指南", "手引", "てびき", "tebiki", "지침"],
  ["work", "branch office", "分公司", "支社", "ししゃ", "shisha", "지사"],
  ["work", "dispatch", "派遣", "派遣", "はけん", "haken", "파견"],
  ["work", "assignment", "担当", "担当", "たんとう", "tantou", "담당"],
  ["work", "duty", "勤務", "勤務", "きんむ", "kinmu", "근무"],
  ["work", "transaction", "交易", "取引", "とりひき", "torihiki", "거래"],
  ["work", "delivery", "交货", "納品", "のうひん", "nouhin", "납품"],
  ["work", "return", "退货", "返品", "へんぴん", "henpin", "반품"],
  ["work", "purchase", "采购", "仕入", "しいれ", "shiire", "매입"],
  ["work", "accounting", "财务", "経理", "けいり", "keiri", "경리"],
  ["work", "general affairs", "总务", "総務", "そうむ", "soumu", "총무"],
  ["work", "planning", "企划", "企画", "きかく", "kikaku", "기획"],
  ["work", "sales", "营业", "営業", "えいぎょう", "eigyou", "영업"],
];

const advancedNouns: NounPair[] = [
  ["work", "governance", "治理", "ガバナンス", "がばなんす", "gabanansu", "거버넌스"],
  ["work", "compliance", "合规", "コンプライアンス", "こんぷらいあんす", "konpuraiansu", "컴플라이언스"],
  ["work", "control", "管控", "統制", "とうせい", "tousei", "통제"],
  ["work", "procurement", "采购", "調達", "ちょうたつ", "choutatsu", "조달"],
  ["work", "stakeholder", "利益相关方", "利害関係者", "りがいかんけいしゃ", "rigaikankeisha", "이해관계자"],
  ["work", "approval", "认可/批准", "認可", "にんか", "ninka", "인가"],
  ["work", "delegation", "移交", "委譲", "いじょう", "ijou", "이양"],
  ["work", "escalation", "升级处理", "エスカレーション", "えすかれーしょん", "esukareeshon", "에스컬레이션"],
  ["work", "redundancy", "冗余", "冗長性", "じょうちょうせい", "jouchousei", "중복성"],
  ["work", "capacity", "容量", "容量", "ようりょう", "youryou", "용량"],
  ["work", "throughput", "吞吐量", "スループット", "するーぷっと", "suruuputto", "처리량"],
  ["work", "latency", "延迟", "レイテンシ", "れいてんし", "reitenshi", "레이턴시"],
  ["work", "bottleneck", "瓶颈", "ボトルネック", "ぼとるねっく", "botorunekku", "병목"],
  ["work", "outage", "服务中断", "障害", "しょうがい", "shougai", "장애"],
  ["work", "incident", "事故/事件", "インシデント", "いんしでんと", "inshidento", "인시던트"],
  ["work", "diagnosis", "诊断", "診断", "しんだん", "shindan", "진단"],
  ["work", "restoration", "恢复", "復旧", "ふっきゅう", "fukkyuu", "복구"],
  ["work", "resilience", "恢复力", "回復力", "かいふくりょく", "kaifukuryoku", "회복력"],
  ["work", "availability", "可用性", "可用性", "かようせい", "kayousei", "가용성"],
  ["work", "scalability", "可扩展性", "拡張性", "かくちょうせい", "kakuchousei", "확장성"],
  ["work", "dependency", "依赖关系", "依存関係", "いぞんかんけい", "izonkankei", "의존성"],
  ["work", "migration", "迁移", "移行", "いこう", "ikou", "마이그레이션"],
  ["work", "retention", "保持", "保持", "ほじ", "hoji", "유지"],
  ["work", "encryption", "加密", "暗号化", "あんごうか", "angouka", "암호화"],
  ["travel", "jurisdiction", "管辖权", "管轄", "かんかつ", "kankatsu", "관할"],
  ["travel", "expulsion", "驱逐", "追放", "ついほう", "tsuihou", "추방"],
  ["travel", "disallowance", "不许可", "不許可", "ふきょか", "fukyoka", "불허"],
  ["travel", "exile", "亡命", "亡命", "ぼうめい", "boumei", "망명"],
  ["travel", "refugee", "难民", "難民", "なんみん", "nanmin", "난민"],
  ["travel", "nationality", "国籍", "国籍", "こくせき", "kokuseki", "국적"],
  ["travel", "residence", "居住", "居住", "きょじゅう", "kyojuu", "거주"],
  ["travel", "permit", "许可证", "許可証", "きょかしょう", "kyokashou", "허가증"],
  ["travel", "guarantee", "担保", "保証", "ほしょう", "hoshou", "보증"],
  ["travel", "declaration", "申报", "申告", "しんこく", "shinkoku", "신고"],
  ["travel", "roster", "名册", "名簿", "めいぼ", "meibo", "명단"],
  ["travel", "contraband", "走私品", "密輸品", "みつゆひん", "mitsuyuhin", "밀수품"],
  ["travel", "customs duty", "关税", "関税", "かんぜい", "kanzei", "관세"],
  ["travel", "exemption", "豁免", "免除", "めんじょ", "menjo", "면제"],
  ["travel", "transit", "过境", "通過", "つうか", "tsuuka", "통과"],
  ["travel", "diversion", "备降/改降", "ダイバート", "だいばーと", "daibaato", "회항"],
  ["travel", "reserve", "备用", "予備", "よび", "yobi", "예비"],
  ["travel", "slot", "航班时刻", "発着枠", "はっちゃくわく", "hatchakuwaku", "슬롯"],
  ["travel", "congestion", "拥堵", "混雑", "こんざつ", "konzatsu", "혼잡"],
  ["travel", "turbulence", "湍流", "乱気流", "らんきりゅう", "rankiryuu", "난기류"],
  ["travel", "airspace", "领空", "領空", "りょうくう", "ryoukuu", "영공"],
  ["travel", "clearance", "许可", "許可", "きょか", "kyoka", "허가"],
  ["travel", "apron", "机坪", "駐機場", "ちゅうきじょう", "chuukijou", "계류장"],
  ["travel", "taxiway", "滑行道", "誘導路", "ゆうどうろ", "yuudouro", "유도로"],
  ["travel", "jet bridge", "廊桥", "ボーディングブリッジ", "ぼーでぃんぐぶりっじ", "boodinguburijji", "탑승교"],
  ["daily life", "welfare", "福利", "福祉", "ふくし", "fukushi", "복지"],
  ["daily life", "pension", "养老金", "年金", "ねんきん", "nenkin", "연금"],
  ["daily life", "subsidy", "补贴", "補助金", "ほじょきん", "hojokin", "보조금"],
  ["daily life", "taxation", "课税", "課税", "かぜい", "kazei", "과세"],
  ["daily life", "demography", "人口学", "人口学", "じんこうがく", "jinkougaku", "인구학"],
  ["daily life", "aging", "老龄化", "高齢化", "こうれいか", "koureika", "고령화"],
  ["daily life", "inequality", "不平等", "不平等", "ふびょうどう", "fubyoudou", "불평등"],
  ["daily life", "privacy", "隐私", "プライバシー", "ぷらいばしー", "puraibashii", "프라이버시"],
  ["daily life", "consent", "同意", "同意", "どうい", "doui", "동의"],
  ["daily life", "identity", "身份", "身元", "みもと", "mimoto", "신원"],
  ["daily life", "fraud", "欺诈", "詐欺", "さぎ", "sagi", "사기"],
  ["daily life", "compensation", "赔偿", "賠償", "ばいしょう", "baishou", "배상"],
  ["daily life", "dispute", "争议", "紛争", "ふんそう", "funsou", "분쟁"],
  ["daily life", "arbitration", "仲裁", "仲裁", "ちゅうさい", "chuusai", "중재"],
  ["daily life", "mediation", "调解", "調停", "ちょうてい", "choutei", "조정"],
  ["daily life", "complaint", "投诉", "苦情", "くじょう", "kujou", "민원"],
  ["daily life", "regulation", "法规/规制", "規制", "きせい", "kisei", "규제"],
  ["daily life", "ordinance", "条例", "条例", "じょうれい", "jourei", "조례"],
  ["daily life", "census", "人口普查", "センサス", "せんさす", "sensasu", "총조사"],
  ["daily life", "household", "家庭户", "世帯", "せたい", "setai", "가구"],
  ["daily life", "tenancy", "租赁关系", "賃貸借", "ちんたいしゃく", "chintaishaku", "임대차"],
  ["daily life", "inheritance", "继承", "相続", "そうぞく", "souzoku", "상속"],
  ["daily life", "guardianship", "监护", "後見", "こうけん", "kouken", "후견"],
  ["daily life", "citizenship", "公民身份", "市民権", "しみんけん", "shiminken", "시민권"],
  ["daily life", "litigation", "诉讼", "訴訟", "そしょう", "soshou", "소송"],
  ["school", "proposition", "命题", "命題", "めいだい", "meidai", "명제"],
  ["school", "methodology", "方法论", "方法論", "ほうほうろん", "houhouron", "방법론"],
  ["school", "variable", "变量", "変数", "へんすう", "hensuu", "변수"],
  ["school", "dataset", "数据集", "データセット", "でーたせっと", "deetasetto", "데이터셋"],
  ["school", "sample", "样本", "標本", "ひょうほん", "hyouhon", "표본"],
  ["school", "bias", "偏差", "偏り", "かたより", "katayori", "편향"],
  ["school", "correlation", "相关性", "相関", "そうかん", "soukan", "상관"],
  ["school", "confounding", "混杂因素", "交絡", "こうらく", "kouraku", "교란"],
  ["school", "reliability", "可靠性", "信頼性", "しんらいせい", "shinraisei", "신뢰도"],
  ["school", "replication", "重复验证", "再現", "さいげん", "saigen", "재현"],
  ["school", "abstract", "摘要", "要旨", "ようし", "youshi", "초록"],
  ["school", "appendix", "附录", "付録", "ふろく", "furoku", "부록"],
  ["school", "footnote", "脚注", "脚注", "きゃくちゅう", "kyakuchuu", "각주"],
  ["school", "metric", "指标", "指標", "しひょう", "shihyou", "지표"],
  ["school", "archive", "档案库", "アーカイブ", "あーかいぶ", "aakaibu", "아카이브"],
  ["school", "corpus", "语料库", "コーパス", "こーぱす", "koopasu", "말뭉치"],
  ["school", "framework", "框架", "枠組み", "わくぐみ", "wakugumi", "프레임워크"],
  ["school", "rubric", "评分量规", "ルーブリック", "るーぶりっく", "ruuburikku", "루브릭"],
  ["school", "accreditation", "认证", "認証", "にんしょう", "ninshou", "인증"],
  ["school", "research funding", "研究经费", "研究費", "けんきゅうひ", "kenkyuuhi", "연구비"],
  ["school", "fellowship", "研究奖学金", "フェローシップ", "ふぇろーしっぷ", "ferooshippu", "펠로십"],
  ["school", "tenure", "终身教职", "テニュア", "てにゅあ", "tenyua", "테뉴어"],
  ["school", "protocol", "研究规程", "プロトコル", "ぷろとこる", "purotokoru", "프로토콜"],
  ["school", "benchmark", "基准", "ベンチマーク", "べんちまーく", "benchimaaku", "벤치마크"],
  ["anime/drama", "cinematography", "摄影", "撮影", "さつえい", "satsuei", "촬영"],
  ["anime/drama", "editing", "剪辑", "編集", "へんしゅう", "henshuu", "편집"],
  ["anime/drama", "direction", "演出", "演出", "えんしゅつ", "enshutsu", "연출"],
  ["anime/drama", "choreography", "编舞", "振付", "ふりつけ", "furitsuke", "안무"],
  ["anime/drama", "costume", "服装", "衣装", "いしょう", "ishou", "의상"],
  ["anime/drama", "makeup", "化妆造型", "メイク", "めいく", "meiku", "분장"],
  ["anime/drama", "prop", "道具", "小道具", "こどうぐ", "kodougu", "소품"],
  ["anime/drama", "lighting", "灯光", "照明", "しょうめい", "shoumei", "조명"],
  ["anime/drama", "framing", "构图", "構図", "こうず", "kouzu", "구도"],
  ["anime/drama", "montage", "蒙太奇", "モンタージュ", "もんたーじゅ", "montaaju", "몽타주"],
  ["anime/drama", "narration", "旁白", "語り", "かたり", "katari", "내레이션"],
  ["anime/drama", "symbolism", "象征", "象徴", "しょうちょう", "shouchou", "상징"],
  ["anime/drama", "motif", "母题", "モチーフ", "もちーふ", "mochiifu", "모티프"],
  ["anime/drama", "archetype", "原型", "原型", "げんけい", "genkei", "원형"],
  ["anime/drama", "canon", "正史", "正史", "せいし", "seishi", "정사"],
  ["anime/drama", "myth", "神话", "神話", "しんわ", "shinwa", "신화"],
  ["anime/drama", "continuity", "连续性", "連続性", "れんぞくせい", "renzokusei", "연속성"],
  ["anime/drama", "pacing", "节奏", "テンポ", "てんぽ", "tenpo", "템포"],
  ["anime/drama", "hint", "暗示", "暗示", "あんじ", "anji", "암시"],
  ["anime/drama", "implication", "含意", "含意", "がんい", "gan'i", "함의"],
  ["anime/drama", "ensemble", "群像", "群像", "ぐんぞう", "gunzou", "군상"],
  ["anime/drama", "auteurism", "作者论", "作家主義", "さっかしゅぎ", "sakkashugi", "작가주의"],
  ["anime/drama", "series", "系列", "シリーズ", "しりーず", "shiriizu", "시리즈"],
  ["anime/drama", "censorship", "审查", "検閲", "けんえつ", "ken'etsu", "검열"],
  ["work", "privilege", "特权", "特権", "とっけん", "tokken", "특권"],
  ["work", "board", "理事会", "理事会", "りじかい", "rijikai", "이사회"],
  ["work", "continuity", "持续性", "継続性", "けいぞくせい", "keizokusei", "지속성"],
];

export const intermediateNounExpansion: VocabItem[] = intermediateNouns.flatMap((pair, index) => makePair("Intermediate", index, pair));
export const advancedNounExpansion: VocabItem[] = advancedNouns.flatMap((pair, index) => makePair("Advanced", index, pair));
