import type { Level, Topic, VocabItem } from "./vocabulary";

type BulkRow = [ja: string, jaReading: string, ko: string, en: string, zh: string, topic: Topic];

function japaneseExample(topic: Topic, word: string) {
  if (topic === "work") return `仕事の場面で「${word}」という表現を確認しました。`;
  if (topic === "travel") return `旅行の場面で「${word}」という表現を確認しました。`;
  if (topic === "school") return `授業で「${word}」という表現を確認しました。`;
  if (topic === "anime/drama") return `作品について話すときに「${word}」という表現を使います。`;
  return `日常生活で「${word}」という表現を確認しました。`;
}

function koreanExample(topic: Topic, word: string) {
  if (topic === "work") return `업무 상황에서 "${word}"라는 표현을 확인했어요.`;
  if (topic === "travel") return `여행 상황에서 "${word}"라는 표현을 확인했어요.`;
  if (topic === "school") return `수업에서 "${word}"라는 표현을 배웠어요.`;
  if (topic === "anime/drama") return `작품에 대해 이야기할 때 "${word}"라는 표현을 써요.`;
  return `일상생활에서 "${word}"라는 표현을 확인했어요.`;
}

function englishExample(topic: Topic, meaning: string) {
  const context =
    topic === "work" ? "a work context" :
    topic === "travel" ? "a travel context" :
    topic === "school" ? "an academic context" :
    topic === "anime/drama" ? "a media context" :
    "an everyday context";
  return `We reviewed "${meaning}" in ${context}.`;
}

function chineseExample(topic: Topic, meaning: string) {
  const context =
    topic === "work" ? "工作场景" :
    topic === "travel" ? "旅行场景" :
    topic === "school" ? "学习场景" :
    topic === "anime/drama" ? "影视动漫场景" :
    "日常场景";
  return `我们在${context}中复习了“${meaning}”。`;
}

function makePairs(rows: BulkRow[], level: Level, prefix: string): VocabItem[] {
  return rows.flatMap(([ja, jaReading, ko, en, zh, topic], index) => {
    const suffix = String(index + 1).padStart(3, "0");
    return [
      {
        id: `ja-bulk-${prefix}-${suffix}`,
        targetLanguage: "Japanese",
        targetText: ja,
        meanings: { English: en, "Simplified Chinese": zh },
        reading: jaReading,
        romanization: "",
        level,
        topic,
        exampleSentence: japaneseExample(topic, ja),
        exampleTranslations: {
          English: englishExample(topic, en),
          "Simplified Chinese": chineseExample(topic, zh),
        },
      },
      {
        id: `ko-bulk-${prefix}-${suffix}`,
        targetLanguage: "Korean",
        targetText: ko,
        meanings: { English: en, "Simplified Chinese": zh },
        reading: ko,
        romanization: "",
        level,
        topic,
        exampleSentence: koreanExample(topic, ko),
        exampleTranslations: {
          English: englishExample(topic, en),
          "Simplified Chinese": chineseExample(topic, zh),
        },
      },
    ];
  });
}

const intermediateRows: BulkRow[] = [
  ["議題", "ぎだい", "안건", "agenda item", "议题", "work"],
  ["進捗", "しんちょく", "진척", "progress", "进展", "work"],
  ["担当者", "たんとうしゃ", "담당자", "person in charge", "负责人", "work"],
  ["見積もり", "みつもり", "견적", "estimate", "估价", "work"],
  ["納期", "のうき", "납기", "delivery deadline", "交付期限", "work"],
  ["取引先", "とりひきさき", "거래처", "business partner", "业务往来单位", "work"],
  ["在庫", "ざいこ", "재고", "inventory", "库存", "work"],
  ["発注", "はっちゅう", "발주", "purchase order", "下单", "work"],
  ["請求書", "せいきゅうしょ", "청구서", "invoice", "账单", "work"],
  ["精算", "せいさん", "정산", "expense settlement", "结算", "work"],
  ["経費", "けいひ", "경비", "business expense", "经费", "work"],
  ["勤怠", "きんたい", "근태", "attendance record", "考勤", "work"],
  ["採用", "さいよう", "채용", "hiring", "招聘", "work"],
  ["応募", "おうぼ", "지원", "job application", "应聘", "work"],
  ["職歴", "しょくれき", "경력", "work history", "工作经历", "work"],
  ["役職", "やくしょく", "직급", "job title", "职位", "work"],
  ["配属", "はいぞく", "배치", "assignment to a team", "岗位分配", "work"],
  ["異動", "いどう", "인사이동", "personnel transfer", "岗位调动", "work"],
  ["在宅勤務", "ざいたくきんむ", "재택근무", "remote work", "居家办公", "work"],
  ["商談", "しょうだん", "협상", "business negotiation", "商务洽谈", "work"],
  ["合意", "ごうい", "합의", "agreement", "共识", "work"],
  ["保留", "ほりゅう", "보류", "on hold", "暂缓", "work"],
  ["差し戻し", "さしもどし", "반려", "returned for revision", "退回修改", "work"],
  ["修正案", "しゅうせいあん", "수정안", "revised proposal", "修订方案", "work"],
  ["優先順位", "ゆうせんじゅんい", "우선순위", "priority order", "优先级", "work"],
  ["入国審査", "にゅうこくしんさ", "입국 심사", "immigration inspection", "入境审查", "travel"],
  ["出国審査", "しゅっこくしんさ", "출국 심사", "departure immigration", "出境审查", "travel"],
  ["搭乗券", "とうじょうけん", "탑승권", "boarding pass", "登机牌", "travel"],
  ["手荷物", "てにもつ", "휴대 수하물", "carry-on baggage", "随身行李", "travel"],
  ["受託手荷物", "じゅたくてにもつ", "위탁 수하물", "checked baggage", "托运行李", "travel"],
  ["超過手荷物", "ちょうかてにもつ", "초과 수하물", "excess baggage", "超额行李", "travel"],
  ["遅延", "ちえん", "지연", "delay", "延误", "travel"],
  ["欠航", "けっこう", "결항", "flight cancellation", "航班取消", "travel"],
  ["振替便", "ふりかえびん", "대체편", "replacement flight", "替代航班", "travel"],
  ["乗り遅れ", "のりおくれ", "비행기 놓침", "missed flight", "误机", "travel"],
  ["片道", "かたみち", "편도", "one-way", "单程", "travel"],
  ["往復", "おうふく", "왕복", "round trip", "往返", "travel"],
  ["指定席", "していせき", "지정석", "reserved seat", "指定座位", "travel"],
  ["自由席", "じゆうせき", "자유석", "non-reserved seat", "自由席", "travel"],
  ["始発", "しはつ", "첫차", "first train", "首班车", "travel"],
  ["終電", "しゅうでん", "막차", "last train", "末班车", "travel"],
  ["運休", "うんきゅう", "운행 중단", "service suspension", "停运", "travel"],
  ["迂回", "うかい", "우회", "detour", "绕行", "travel"],
  ["渋滞", "じゅうたい", "교통 체증", "traffic jam", "交通拥堵", "travel"],
  ["国境", "こっきょう", "국경", "border", "国境", "travel"],
  ["査証", "さしょう", "사증", "visa", "签证", "travel"],
  ["滞在許可", "たいざいきょか", "체류 허가", "stay permit", "停留许可", "travel"],
  ["免税店", "めんぜいてん", "면세점", "duty-free shop", "免税店", "travel"],
  ["両替レート", "りょうがえれーと", "환율", "exchange rate", "汇率", "travel"],
  ["時差", "じさ", "시차", "time difference", "时差", "travel"],
  ["粗大ごみ", "そだいごみ", "대형 폐기물", "bulky waste", "大型垃圾", "daily life"],
  ["家事", "かじ", "집안일", "housework", "家务", "daily life"],
  ["洗濯物", "せんたくもの", "빨랫감", "laundry", "待洗衣物", "daily life"],
  ["乾燥機", "かんそうき", "건조기", "dryer", "烘干机", "daily life"],
  ["収納", "しゅうのう", "수납", "storage", "收纳", "daily life"],
  ["片付け", "かたづけ", "정리", "tidying up", "整理", "daily life"],
  ["断捨離", "だんしゃり", "정리정돈", "decluttering", "断舍离", "daily life"],
  ["家賃", "やちん", "월세", "rent", "房租", "daily life"],
  ["光熱費", "こうねつひ", "공과금", "utility costs", "水电燃气费", "daily life"],
  ["水道代", "すいどうだい", "수도 요금", "water bill", "水费", "daily life"],
  ["電気代", "でんきだい", "전기 요금", "electricity bill", "电费", "daily life"],
  ["契約更新", "けいやくこうしん", "계약 갱신", "contract renewal", "合同续签", "daily life"],
  ["宅配便", "たくはいびん", "택배", "courier delivery", "快递", "daily life"],
  ["不在票", "ふざいひょう", "부재중 안내문", "missed-delivery notice", "未投递通知", "daily life"],
  ["再配達", "さいはいたつ", "재배송", "redelivery", "再次配送", "daily life"],
  ["防災", "ぼうさい", "재난 대비", "disaster preparedness", "防灾", "daily life"],
  ["避難所", "ひなんじょ", "대피소", "evacuation shelter", "避难所", "daily life"],
  ["非常口", "ひじょうぐち", "비상구", "emergency exit", "紧急出口", "daily life"],
  ["防犯", "ぼうはん", "방범", "crime prevention", "防盗防范", "daily life"],
  ["騒音", "そうおん", "소음", "noise", "噪音", "daily life"],
  ["湿気", "しっけ", "습기", "humidity", "湿气", "daily life"],
  ["断水", "だんすい", "단수", "water outage", "停水", "daily life"],
  ["停電", "ていでん", "정전", "power outage", "停电", "daily life"],
  ["故障", "こしょう", "고장", "malfunction", "故障", "daily life"],
  ["保証期間", "ほしょうきかん", "보증 기간", "warranty period", "保修期", "daily life"],
  ["履修登録", "りしゅうとうろく", "수강 신청", "course registration", "选课登记", "school"],
  ["必修科目", "ひっしゅうかもく", "필수 과목", "required course", "必修课", "school"],
  ["選択科目", "せんたくかもく", "선택 과목", "elective course", "选修课", "school"],
  ["単位", "たんい", "학점", "academic credit", "学分", "school"],
  ["ゼミ", "ぜみ", "세미나", "seminar", "研讨课", "school"],
  ["実習", "じっしゅう", "실습", "practicum", "实习课程", "school"],
  ["インターンシップ", "いんたーんしっぷ", "인턴십", "internship", "实习", "school"],
  ["卒業論文", "そつぎょうろんぶん", "졸업 논문", "graduation thesis", "毕业论文", "school"],
  ["参考文献", "さんこうぶんけん", "참고 문헌", "references", "参考文献", "school"],
  ["引用", "いんよう", "인용", "citation", "引用", "school"],
  ["盗用", "とうよう", "표절", "plagiarism", "抄袭", "school"],
  ["成績証明書", "せいせきしょうめいしょ", "성적 증명서", "academic transcript", "成绩单", "school"],
  ["在籍証明書", "ざいせきしょうめいしょ", "재학 증명서", "enrollment certificate", "在读证明", "school"],
  ["再履修", "さいりしゅう", "재수강", "course retake", "重修", "school"],
  ["追試", "ついし", "추가 시험", "makeup exam", "补考", "school"],
  ["補講", "ほこう", "보강", "supplementary class", "补课", "school"],
  ["研究室", "けんきゅうしつ", "연구실", "research laboratory", "研究室", "school"],
  ["指導教員", "しどうきょういん", "지도 교수", "academic supervisor", "指导教师", "school"],
  ["出席率", "しゅっせきりつ", "출석률", "attendance rate", "出勤率", "school"],
  ["グループ課題", "ぐるーぷかだい", "조별 과제", "group assignment", "小组作业", "school"],
  ["相互評価", "そうごひょうか", "상호 평가", "peer assessment", "同伴互评", "school"],
  ["発表資料", "はっぴょうしりょう", "발표 자료", "presentation materials", "演示资料", "school"],
  ["締切日", "しめきりび", "마감일", "due date", "截止日", "school"],
  ["学期", "がっき", "학기", "semester", "学期", "school"],
  ["休講", "きゅうこう", "휴강", "class cancellation", "停课", "school"],
  ["作画", "さくが", "작화", "animation artwork", "作画", "anime/drama"],
  ["演出", "えんしゅつ", "연출", "direction", "演出", "anime/drama"],
  ["脚本", "きゃくほん", "각본", "screenplay", "剧本", "anime/drama"],
  ["原画", "げんが", "원화", "key drawing", "原画", "anime/drama"],
  ["動画", "どうが", "동화", "in-between animation", "动画中间帧", "anime/drama"],
  ["背景美術", "はいけいびじゅつ", "배경 미술", "background art", "背景美术", "anime/drama"],
  ["撮影", "さつえい", "촬영", "cinematography", "摄影", "anime/drama"],
  ["編集", "へんしゅう", "편집", "editing", "剪辑", "anime/drama"],
  ["音響", "おんきょう", "음향", "sound production", "音响制作", "anime/drama"],
  ["劇伴", "げきばん", "배경 음악", "background score", "配乐", "anime/drama"],
  ["挿入歌", "そうにゅうか", "삽입곡", "insert song", "插曲", "anime/drama"],
  ["配役", "はいやく", "배역", "casting", "角色分配", "anime/drama"],
  ["伏線", "ふくせん", "복선", "foreshadowing", "伏笔", "anime/drama"],
  ["伏線回収", "ふくせんかいしゅう", "복선 회수", "foreshadowing payoff", "伏笔回收", "anime/drama"],
  ["設定", "せってい", "설정", "setting and lore", "设定", "anime/drama"],
  ["世界観", "せかいかん", "세계관", "worldbuilding", "世界观", "anime/drama"],
  ["作風", "さくふう", "작풍", "artistic style", "作品风格", "anime/drama"],
  ["名場面", "めいばめん", "명장면", "memorable scene", "名场面", "anime/drama"],
  ["名台詞", "めいぜりふ", "명대사", "memorable line", "经典台词", "anime/drama"],
  ["ネタバレ", "ねたばれ", "스포일러", "spoiler", "剧透", "anime/drama"],
  ["考察", "こうさつ", "해석", "fan analysis", "剧情考察", "anime/drama"],
  ["推し", "おし", "최애", "favorite character", "最喜欢的角色", "anime/drama"],
  ["神回", "かみかい", "명에피소드", "outstanding episode", "神回", "anime/drama"],
  ["総集編", "そうしゅうへん", "총집편", "recap episode", "总集篇", "anime/drama"],
  ["番外編", "ばんがいへん", "외전", "side story", "番外篇", "anime/drama"],
];

const advancedRows: BulkRow[] = [
  ["ガバナンス", "がばなんす", "거버넌스", "governance", "治理机制", "work"],
  ["コンプライアンス", "こんぷらいあんす", "컴플라이언스", "compliance", "合规", "work"],
  ["内部監査", "ないぶかんさ", "내부 감사", "internal audit", "内部审计", "work"],
  ["説明責任", "せつめいせきにん", "책무성", "accountability", "问责责任", "work"],
  ["権限委譲", "けんげんいじょう", "권한 위임", "delegation of authority", "权限下放", "work"],
  ["裁量権", "さいりょうけん", "재량권", "discretionary authority", "裁量权", "work"],
  ["合意形成", "ごういけいせい", "합의 형성", "consensus building", "共识形成", "work"],
  ["エスカレーション", "えすかれーしょん", "에스컬레이션", "escalation", "升级处理", "work"],
  ["緊急対応計画", "きんきゅうたいおうけいかく", "비상 대응 계획", "contingency plan", "应急响应计划", "work"],
  ["冗長化", "じょうちょうか", "이중화", "redundancy", "冗余设计", "work"],
  ["耐障害性", "たいしょうがいせい", "내결함성", "fault tolerance", "容错性", "work"],
  ["回復力", "かいふくりょく", "회복 탄력성", "resilience", "恢复力", "work"],
  ["リスク軽減", "りすくけいげん", "위험 완화", "risk mitigation", "风险缓解", "work"],
  ["是正措置", "ぜせいそち", "시정 조치", "corrective action", "纠正措施", "work"],
  ["根本原因", "こんぽんげんいん", "근본 원인", "root cause", "根本原因", "work"],
  ["利害関係者", "りがいかんけいしゃ", "이해관계자", "stakeholder", "利益相关者", "work"],
  ["ボトルネック", "ぼとるねっく", "병목", "bottleneck", "瓶颈", "work"],
  ["処理能力", "しょりのうりょく", "처리량", "throughput capacity", "处理能力", "work"],
  ["調達", "ちょうたつ", "조달", "procurement", "采购", "work"],
  ["デューデリジェンス", "でゅーでりじぇんす", "실사", "due diligence", "尽职调查", "work"],
  ["実現可能性", "じつげんかのうせい", "실현 가능성", "feasibility", "可行性", "work"],
  ["基準値", "きじゅんち", "벤치마크", "benchmark", "基准值", "work"],
  ["ロードマップ", "ろーどまっぷ", "로드맵", "roadmap", "路线图", "work"],
  ["トレードオフ", "とれーどおふ", "상충 관계", "trade-off", "权衡", "work"],
  ["整合性", "せいごうせい", "정합성", "alignment and consistency", "一致性", "work"],
  ["入国管理", "にゅうこくかんり", "출입국 관리", "immigration control", "出入境管理", "travel"],
  ["通関", "つうかん", "통관", "customs clearance", "清关", "travel"],
  ["検疫", "けんえき", "검역", "quarantine inspection", "检疫", "travel"],
  ["入国拒否", "にゅうこくきょひ", "입국 거부", "refusal of entry", "拒绝入境", "travel"],
  ["強制送還", "きょうせいそうかん", "강제 송환", "deportation", "强制遣返", "travel"],
  ["送還", "そうかん", "송환", "repatriation", "遣返", "travel"],
  ["搭乗拒否", "とうじょうきょひ", "탑승 거부", "denied boarding", "拒绝登机", "travel"],
  ["過剰予約", "かじょうよやく", "초과 예약", "overbooking", "超售", "travel"],
  ["経路変更", "けいろへんこう", "경로 변경", "rerouting", "改道", "travel"],
  ["補償", "ほしょう", "보상", "compensation", "补偿", "travel"],
  ["不可抗力", "ふかこうりょく", "불가항력", "force majeure", "不可抗力", "travel"],
  ["共同運航", "きょうどううんこう", "공동 운항", "codeshare operation", "代码共享", "travel"],
  ["査証免除", "さしょうめんじょ", "비자 면제", "visa waiver", "免签", "travel"],
  ["通過査証", "つうかさしょう", "경유 비자", "transit visa", "过境签证", "travel"],
  ["生体認証", "せいたいにんしょう", "생체 인증", "biometric authentication", "生物识别认证", "travel"],
  ["渡航勧告", "とこうかんこく", "여행 경보", "travel advisory", "旅行警示", "travel"],
  ["領事支援", "りょうじしえん", "영사 지원", "consular assistance", "领事协助", "travel"],
  ["入国要件", "にゅうこくようけん", "입국 요건", "entry requirements", "入境要求", "travel"],
  ["滞在資格", "たいざいしかく", "체류 자격", "status of residence", "居留资格", "travel"],
  ["乗継保証", "のりつぎほしょう", "환승 보장", "protected connection", "受保护中转", "travel"],
  ["最低乗継時間", "さいていのりつぎじかん", "최소 환승 시간", "minimum connection time", "最短中转时间", "travel"],
  ["不定期便", "ふていきびん", "부정기편", "non-scheduled flight", "不定期航班", "travel"],
  ["臨時便", "りんじびん", "임시편", "extra flight", "临时航班", "travel"],
  ["代替空港", "だいたいくうこう", "대체 공항", "alternate airport", "备降机场", "travel"],
  ["運航制限", "うんこうせいげん", "운항 제한", "operational restriction", "运行限制", "travel"],
  ["社会保障", "しゃかいほしょう", "사회 보장", "social security", "社会保障", "daily life"],
  ["年金制度", "ねんきんせいど", "연금 제도", "pension system", "养老金制度", "daily life"],
  ["物価上昇", "ぶっかじょうしょう", "물가 상승", "rising prices", "物价上涨", "daily life"],
  ["住宅供給", "じゅうたくきょうきゅう", "주택 공급", "housing supply", "住房供应", "daily life"],
  ["都市再開発", "としさいかいはつ", "도시 재개발", "urban redevelopment", "城市再开发", "daily life"],
  ["ジェントリフィケーション", "じぇんとりふぃけーしょん", "젠트리피케이션", "gentrification", "绅士化", "daily life"],
  ["都市計画", "としけいかく", "도시 계획", "urban planning", "城市规划", "daily life"],
  ["アクセシビリティ", "あくせしびりてぃ", "접근성", "accessibility", "可达性", "daily life"],
  ["包摂性", "ほうせつせい", "포용성", "inclusivity", "包容性", "daily life"],
  ["個人情報", "こじんじょうほう", "개인정보", "personal information", "个人信息", "daily life"],
  ["詐欺対策", "さぎたいさく", "사기 방지", "fraud prevention", "防诈骗措施", "daily life"],
  ["消費者保護", "しょうひしゃほご", "소비자 보호", "consumer protection", "消费者保护", "daily life"],
  ["瑕疵担保", "かしたんぽ", "하자 보증", "defect warranty", "瑕疵担保", "daily life"],
  ["定期購読", "ていきこうどく", "구독", "subscription", "订阅", "daily life"],
  ["解約手続き", "かいやくてつづき", "해지 절차", "cancellation procedure", "解约手续", "daily life"],
  ["紛争調停", "ふんそうちょうてい", "분쟁 조정", "dispute mediation", "争议调解", "daily life"],
  ["防災計画", "ぼうさいけいかく", "재난 대응 계획", "disaster preparedness plan", "防灾计划", "daily life"],
  ["避難経路", "ひなんけいろ", "대피 경로", "evacuation route", "疏散路线", "daily life"],
  ["備蓄", "びちく", "비축", "stockpiling", "储备", "daily life"],
  ["省エネ", "しょうえね", "에너지 절약", "energy conservation", "节能", "daily life"],
  ["再生可能エネルギー", "さいせいかのうえねるぎー", "재생 에너지", "renewable energy", "可再生能源", "daily life"],
  ["廃棄物分別", "はいきぶつぶんべつ", "폐기물 분리", "waste sorting", "垃圾分类", "daily life"],
  ["生活インフラ", "せいかついんふら", "생활 인프라", "everyday infrastructure", "生活基础设施", "daily life"],
  ["地域格差", "ちいきかくさ", "지역 격차", "regional disparity", "地区差距", "daily life"],
  ["高齢化", "こうれいか", "고령화", "population aging", "人口老龄化", "daily life"],
  ["研究方法論", "けんきゅうほうほうろん", "연구 방법론", "research methodology", "研究方法论", "school"],
  ["仮説", "かせつ", "가설", "hypothesis", "假设", "school"],
  ["変数", "へんすう", "변수", "variable", "变量", "school"],
  ["相関", "そうかん", "상관", "correlation", "相关性", "school"],
  ["因果関係", "いんがかんけい", "인과 관계", "causality", "因果关系", "school"],
  ["再現性", "さいげんせい", "재현성", "reproducibility", "可重复性", "school"],
  ["査読", "さどく", "동료 심사", "peer review", "同行评审", "school"],
  ["文献レビュー", "ぶんけんれびゅー", "문헌 검토", "literature review", "文献综述", "school"],
  ["研究倫理", "けんきゅうりんり", "연구 윤리", "research ethics", "研究伦理", "school"],
  ["研究公正", "けんきゅうこうせい", "연구 진실성", "research integrity", "科研诚信", "school"],
  ["カリキュラム", "かりきゅらむ", "교육과정", "curriculum", "课程体系", "school"],
  ["教授法", "きょうじゅほう", "교수법", "pedagogy", "教学法", "school"],
  ["学際的", "がくさいてき", "학제간", "interdisciplinary", "跨学科", "school"],
  ["定性的", "ていせいてき", "정성적", "qualitative", "定性", "school"],
  ["定量的", "ていりょうてき", "정량적", "quantitative", "定量", "school"],
  ["標本抽出", "ひょうほんちゅうしゅつ", "표본 추출", "sampling", "抽样", "school"],
  ["標本偏り", "ひょうほんかたより", "표본 편향", "sampling bias", "抽样偏差", "school"],
  ["統計的有意性", "とうけいてきゆういせい", "통계적 유의성", "statistical significance", "统计显著性", "school"],
  ["妥当性", "だとうせい", "타당성", "validity", "有效性", "school"],
  ["信頼性", "しんらいせい", "신뢰도", "reliability", "信度", "school"],
  ["評価基準", "ひょうかきじゅん", "평가 기준", "rubric", "评分标准", "school"],
  ["認証評価", "にんしょうひょうか", "인증 평가", "accreditation", "认证评估", "school"],
  ["博士論文", "はくしろんぶん", "박사 논문", "doctoral dissertation", "博士论文", "school"],
  ["口頭試問", "こうとうしもん", "구술 심사", "oral defense", "口试答辩", "school"],
  ["研究助成金", "けんきゅうじょせいきん", "연구비", "research grant", "研究资助", "school"],
  ["人物造形", "じんぶつぞうけい", "인물 형상화", "characterization", "人物塑造", "anime/drama"],
  ["物語構成", "ものがたりこうせい", "서사 구조", "narrative structure", "叙事结构", "anime/drama"],
  ["伏線配置", "ふくせんはいち", "복선 배치", "foreshadowing design", "伏笔布局", "anime/drama"],
  ["象徴表現", "しょうちょうひょうげん", "상징 표현", "symbolism", "象征表达", "anime/drama"],
  ["寓意", "ぐうい", "우의", "allegory", "寓意", "anime/drama"],
  ["画面構成", "がめんこうせい", "미장센", "mise-en-scene", "场面调度", "anime/drama"],
  ["撮影技法", "さつえいぎほう", "촬영 기법", "cinematography technique", "摄影技法", "anime/drama"],
  ["テンポ", "てんぽ", "전개 속도", "pacing", "节奏", "anime/drama"],
  ["原作忠実度", "げんさくちゅうじつど", "원작 충실도", "adaptation fidelity", "原作还原度", "anime/drama"],
  ["連続性", "れんぞくせい", "연속성", "continuity", "连续性", "anime/drama"],
  ["後付け設定", "あとづけせってい", "설정 변경", "retcon", "后加设定", "anime/drama"],
  ["正史", "せいし", "정사", "canon", "正史", "anime/drama"],
  ["外伝", "がいでん", "외전", "spin-off", "外传", "anime/drama"],
  ["ファンサービス", "ふぁんさーびす", "팬서비스", "fan service", "粉丝福利", "anime/drama"],
  ["含意", "がんい", "함의", "subtext", "潜台词", "anime/drama"],
  ["モチーフ", "もちーふ", "모티프", "motif", "母题", "anime/drama"],
  ["類型", "るいけい", "유형", "archetype", "原型类型", "anime/drama"],
  ["アンチヒーロー", "あんちひーろー", "안티히어로", "antihero", "反英雄", "anime/drama"],
  ["信頼できない語り手", "しんらいできないかたりて", "신뢰할 수 없는 화자", "unreliable narrator", "不可靠叙述者", "anime/drama"],
  ["群像劇", "ぐんぞうげき", "군상극", "ensemble drama", "群像剧", "anime/drama"],
  ["製作委員会", "せいさくいいんかい", "제작위원회", "production committee", "制作委员会", "anime/drama"],
  ["絵コンテ", "えこんて", "콘티", "storyboard", "分镜", "anime/drama"],
  ["作画監督", "さくがかんとく", "작화 감독", "animation director", "作画监督", "anime/drama"],
  ["ローカライズ", "ろーからいず", "현지화", "localization", "本地化", "anime/drama"],
  ["吹き替え", "ふきかえ", "더빙", "dubbing", "配音", "anime/drama"],
];

export const bulkIntermediateExpansion: VocabItem[] = makePairs(intermediateRows, "Intermediate", "intermediate");
export const bulkAdvancedExpansion: VocabItem[] = makePairs(advancedRows, "Advanced", "advanced");
