import type { VocabItem } from "./vocabulary";

export const advancedVocab: VocabItem[] = [
  // --- JLPT 1–3 / TOPIK 1–3 ---
  {
    id: "ja-jlpt-advanced-1",
    targetLanguage: "Japanese",
    targetText: "恐縮",
    meanings: { English: "obliged, deeply sorry", "Simplified Chinese": "惶恐，不好意思" },
    reading: "きょうしゅく",
    romanization: "kyoshuku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "お手数をおかけして恐縮です。",
    exampleTranslations: {
      English: "I am terribly sorry to trouble you.",
      "Simplified Chinese": "给您添麻烦，我很不好意思。",
    },
  },
  {
    id: "ja-jlpt-advanced-2",
    targetLanguage: "Japanese",
    targetText: "曖昧",
    meanings: { English: "ambiguous, vague", "Simplified Chinese": "暧昧，含糊" },
    reading: "あいまい",
    romanization: "aimai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "曖昧な態度は誤解を招く。",
    exampleTranslations: { English: "An ambiguous attitude invites misunderstanding.", "Simplified Chinese": "含糊的态度会招致误解。" },
  },
  {
    id: "ja-jlpt-advanced-3",
    targetLanguage: "Japanese",
    targetText: "促す",
    meanings: { English: "to urge, to prompt", "Simplified Chinese": "催促，促使" },
    reading: "うながす",
    romanization: "unagasu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "先生は学生に発言を促しました。",
    exampleTranslations: {
      English: "The teacher urged the students to speak up.",
      "Simplified Chinese": "老师催促学生发言。",
    },
  },
  {
    id: "ko-topik-advanced-1",
    targetLanguage: "Korean",
    targetText: "촉구하다",
    meanings: { English: "to urge, to press for", "Simplified Chinese": "敦促，催促" },
    reading: "촉구하다",
    romanization: "chokguhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "전문가들은 즉각적인 대책을 촉구했습니다.",
    exampleTranslations: {
      English: "Experts urged immediate countermeasures.",
      "Simplified Chinese": "专家们敦促立即采取对策。",
    },
  },
  {
    id: "ko-topik-advanced-2",
    targetLanguage: "Korean",
    targetText: "현저하다",
    meanings: { English: "remarkable, conspicuous", "Simplified Chinese": "显著，明显" },
    reading: "현저하다",
    romanization: "hyeonjeohada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "두 집단 사이에 현저한 차이가 나타났다.",
    exampleTranslations: { English: "A remarkable difference appeared between the two groups.", "Simplified Chinese": "两组之间出现了显著差异。" },
  },
  {
    id: "ko-topik-advanced-3",
    targetLanguage: "Korean",
    targetText: "모호하다",
    meanings: { English: "vague, ambiguous", "Simplified Chinese": "模糊，含糊" },
    reading: "모호하다",
    romanization: "mohohada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "법률의 기준이 모호해서 논란이 일고 있다.",
    exampleTranslations: { English: "The legal standard is vague, causing controversy.", "Simplified Chinese": "法律标准模糊，引发了争议。" },
  },
  // --- JLPT 4–8 / TOPIK 4–8 ---
  {
    id: "ja-jlpt-advanced-4",
    targetLanguage: "Japanese",
    targetText: "著しい",
    meanings: { English: "remarkable, striking", "Simplified Chinese": "显著的，明显的" },
    reading: "いちじるしい",
    romanization: "ichijirushii",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "著しい進歩を遂げた。",
    exampleTranslations: { English: "Remarkable progress was achieved.", "Simplified Chinese": "取得了显著进步。" },
  },
  {
    id: "ja-jlpt-advanced-5",
    targetLanguage: "Japanese",
    targetText: "推移",
    meanings: { English: "transition, shift over time", "Simplified Chinese": "推移，变迁" },
    reading: "すいい",
    romanization: "suii",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "物価の推移をグラフで示す。",
    exampleTranslations: { English: "The price trends are shown in a graph.", "Simplified Chinese": "用图表显示物价的推移。" },
  },
  {
    id: "ja-jlpt-advanced-6",
    targetLanguage: "Japanese",
    targetText: "措置",
    meanings: { English: "measure, step (taken)", "Simplified Chinese": "措施，处置" },
    reading: "そち",
    romanization: "sochi",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "早急な措置を講じる必要がある。",
    exampleTranslations: { English: "Urgent measures need to be taken.", "Simplified Chinese": "有必要采取紧急措施。" },
  },
  {
    id: "ja-jlpt-advanced-7",
    targetLanguage: "Japanese",
    targetText: "懸念",
    meanings: { English: "concern, apprehension", "Simplified Chinese": "担忧，忧虑" },
    reading: "けねん",
    romanization: "kenen",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "安全に対する懸念が高まっている。",
    exampleTranslations: { English: "Concerns about safety are growing.", "Simplified Chinese": "对安全的担忧在增加。" },
  },
  {
    id: "ja-jlpt-advanced-8",
    targetLanguage: "Japanese",
    targetText: "是正",
    meanings: { English: "correction, rectification", "Simplified Chinese": "纠正，整改" },
    reading: "ぜせい",
    romanization: "zesei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "格差を是正する政策が求められている。",
    exampleTranslations: { English: "Policies to rectify inequality are demanded.", "Simplified Chinese": "人们要求制定纠正差距的政策。" },
  },
  {
    id: "ko-topik-advanced-4",
    targetLanguage: "Korean",
    targetText: "추이",
    meanings: { English: "trend, course of change", "Simplified Chinese": "趋势，变化" },
    reading: "추이",
    romanization: "chui",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "물가의 추이를 면밀히 관찰해야 한다.",
    exampleTranslations: { English: "Price trends must be closely observed.", "Simplified Chinese": "必须密切观察物价趋势。" },
  },
  {
    id: "ko-topik-advanced-5",
    targetLanguage: "Korean",
    targetText: "귀결",
    meanings: { English: "conclusion, consequence", "Simplified Chinese": "归结，结局" },
    reading: "귀결",
    romanization: "gwigyeol",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "모든 논의는 하나의 결론으로 귀결되었다.",
    exampleTranslations: { English: "All discussions converged on a single conclusion.", "Simplified Chinese": "所有讨论归结为一个结论。" },
  },
  {
    id: "ko-topik-advanced-6",
    targetLanguage: "Korean",
    targetText: "본질",
    meanings: { English: "essence, true nature", "Simplified Chinese": "本质，实质" },
    reading: "본질",
    romanization: "bonjil",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "문제의 본질을 파악해야 한다.",
    exampleTranslations: { English: "We must grasp the essence of the problem.", "Simplified Chinese": "必须把握问题的本质。" },
  },
  {
    id: "ko-topik-advanced-7",
    targetLanguage: "Korean",
    targetText: "논거",
    meanings: { English: "grounds for argument, basis", "Simplified Chinese": "论据，论点" },
    reading: "논거",
    romanization: "nongeo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "충분한 논거 없이 주장하면 설득력이 없다.",
    exampleTranslations: { English: "Arguing without sufficient grounds is not persuasive.", "Simplified Chinese": "没有充分论据的主张没有说服力。" },
  },
  {
    id: "ko-topik-advanced-8",
    targetLanguage: "Korean",
    targetText: "입증",
    meanings: { English: "proof, verification", "Simplified Chinese": "证实，证明" },
    reading: "입증",
    romanization: "ipjeung",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 이론은 실험을 통해 입증되었다.",
    exampleTranslations: { English: "The theory was verified through experiments.", "Simplified Chinese": "那个理论通过实验得到了证实。" },
  },
  // --- JLPT 9–15 / TOPIK 9–15 ---
  {
    id: "ja-jlpt-advanced-9",
    targetLanguage: "Japanese",
    targetText: "顕著",
    meanings: { English: "conspicuous, striking", "Simplified Chinese": "显著，突出" },
    reading: "けんちょ",
    romanization: "kencho",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "効果が顕著に現れた。",
    exampleTranslations: { English: "The effect manifested conspicuously.", "Simplified Chinese": "效果显著地呈现了。" },
  },
  {
    id: "ja-jlpt-advanced-10",
    targetLanguage: "Japanese",
    targetText: "網羅",
    meanings: { English: "to cover exhaustively, comprehensive inclusion", "Simplified Chinese": "网罗，涵盖" },
    reading: "もうら",
    romanization: "moura",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "全ての論点を網羅した報告書だ。",
    exampleTranslations: { English: "It is a report that covers all points exhaustively.", "Simplified Chinese": "这是涵盖所有论点的报告。" },
  },
  {
    id: "ja-jlpt-advanced-11",
    targetLanguage: "Japanese",
    targetText: "踏まえる",
    meanings: { English: "to be based on, to take into account", "Simplified Chinese": "基于，考虑到" },
    reading: "ふまえる",
    romanization: "fumaeru",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "前回の失敗を踏まえて計画を見直した。",
    exampleTranslations: { English: "We revised the plan based on the previous failure.", "Simplified Chinese": "基于上次的失败重新审视了计划。" },
  },
  {
    id: "ja-jlpt-advanced-12",
    targetLanguage: "Japanese",
    targetText: "趣旨",
    meanings: { English: "gist, purpose, intent", "Simplified Chinese": "宗旨，要旨" },
    reading: "しゅし",
    romanization: "shushi",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "この制度の趣旨を説明します。",
    exampleTranslations: { English: "I will explain the purpose of this system.", "Simplified Chinese": "我来说明这个制度的宗旨。" },
  },
  {
    id: "ja-jlpt-advanced-13",
    targetLanguage: "Japanese",
    targetText: "妥協",
    meanings: { English: "compromise, concession", "Simplified Chinese": "妥协，让步" },
    reading: "だきょう",
    romanization: "dakyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "双方が妥協点を見つけた。",
    exampleTranslations: { English: "Both sides found a point of compromise.", "Simplified Chinese": "双方找到了妥协点。" },
  },
  {
    id: "ja-jlpt-advanced-14",
    targetLanguage: "Japanese",
    targetText: "逸脱",
    meanings: { English: "deviation, departure from norm", "Simplified Chinese": "脱离，偏离" },
    reading: "いつだつ",
    romanization: "itsudatsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "基準から逸脱した行為は処分の対象となる。",
    exampleTranslations: { English: "Acts deviating from the standard are subject to disciplinary action.", "Simplified Chinese": "偏离标准的行为将受到处分。" },
  },
  {
    id: "ja-jlpt-advanced-15",
    targetLanguage: "Japanese",
    targetText: "抽象的",
    meanings: { English: "abstract", "Simplified Chinese": "抽象的" },
    reading: "ちゅうしょうてき",
    romanization: "chushouteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "議論が抽象的すぎて結論が出ない。",
    exampleTranslations: { English: "The discussion is too abstract to reach a conclusion.", "Simplified Chinese": "讨论太抽象了，得不出结论。" },
  },
  {
    id: "ko-topik-advanced-9",
    targetLanguage: "Korean",
    targetText: "반박",
    meanings: { English: "refutation, rebuttal", "Simplified Chinese": "反驳，驳斥" },
    reading: "반박",
    romanization: "banbak",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "상대방의 주장을 논리적으로 반박했다.",
    exampleTranslations: { English: "He logically refuted the opponent's argument.", "Simplified Chinese": "他逻辑严密地反驳了对方的主张。" },
  },
  {
    id: "ko-topik-advanced-10",
    targetLanguage: "Korean",
    targetText: "추론",
    meanings: { English: "inference, reasoning", "Simplified Chinese": "推论，推理" },
    reading: "추론",
    romanization: "churon",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "논리적 추론을 통해 결론에 도달했다.",
    exampleTranslations: { English: "A conclusion was reached through logical reasoning.", "Simplified Chinese": "通过逻辑推理得出了结论。" },
  },
  {
    id: "ko-topik-advanced-11",
    targetLanguage: "Korean",
    targetText: "시사하다",
    meanings: { English: "to suggest, to imply", "Simplified Chinese": "启示，暗示" },
    reading: "시사하다",
    romanization: "sisahada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 연구 결과는 중요한 사실을 시사한다.",
    exampleTranslations: { English: "These research results imply an important fact.", "Simplified Chinese": "这项研究结果暗示了重要的事实。" },
  },
  {
    id: "ko-topik-advanced-12",
    targetLanguage: "Korean",
    targetText: "간주하다",
    meanings: { English: "to regard as, to deem", "Simplified Chinese": "视为，看作" },
    reading: "간주하다",
    romanization: "ganjuhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "침묵은 동의로 간주됩니다.",
    exampleTranslations: { English: "Silence is regarded as consent.", "Simplified Chinese": "沉默被视为同意。" },
  },
  {
    id: "ko-topik-advanced-13",
    targetLanguage: "Korean",
    targetText: "수반하다",
    meanings: { English: "to accompany, to entail", "Simplified Chinese": "伴随，随之而来" },
    reading: "수반하다",
    romanization: "subanhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "경제 성장은 환경 문제를 수반한다.",
    exampleTranslations: { English: "Economic growth entails environmental problems.", "Simplified Chinese": "经济增长伴随着环境问题。" },
  },
  {
    id: "ko-topik-advanced-14",
    targetLanguage: "Korean",
    targetText: "초래하다",
    meanings: { English: "to cause, to bring about", "Simplified Chinese": "招致，引起" },
    reading: "초래하다",
    romanization: "choraehada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "무분별한 개발이 생태계 파괴를 초래했다.",
    exampleTranslations: { English: "Reckless development caused ecosystem destruction.", "Simplified Chinese": "无序开发导致了生态系统破坏。" },
  },
  {
    id: "ko-topik-advanced-15",
    targetLanguage: "Korean",
    targetText: "야기하다",
    meanings: { English: "to give rise to, to provoke", "Simplified Chinese": "引发，导致" },
    reading: "야기하다",
    romanization: "yagihada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 발언은 심각한 논란을 야기했다.",
    exampleTranslations: { English: "That remark provoked serious controversy.", "Simplified Chinese": "那番言论引发了严重的争议。" },
  },
  // --- JLPT 16–22 / TOPIK 16–22 ---
  {
    id: "ja-jlpt-advanced-16",
    targetLanguage: "Japanese",
    targetText: "普遍的",
    meanings: { English: "universal, ubiquitous", "Simplified Chinese": "普遍的" },
    reading: "ふへんてき",
    romanization: "fuhenteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "人権は普遍的な価値である。",
    exampleTranslations: { English: "Human rights are a universal value.", "Simplified Chinese": "人权是普遍的价值。" },
  },
  {
    id: "ja-jlpt-advanced-17",
    targetLanguage: "Japanese",
    targetText: "潜在的",
    meanings: { English: "potential, latent", "Simplified Chinese": "潜在的" },
    reading: "せんざいてき",
    romanization: "senzaiteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "潜在的なリスクを洗い出す必要がある。",
    exampleTranslations: { English: "We need to identify latent risks.", "Simplified Chinese": "有必要排查潜在风险。" },
  },
  {
    id: "ja-jlpt-advanced-18",
    targetLanguage: "Japanese",
    targetText: "画期的",
    meanings: { English: "groundbreaking, epoch-making", "Simplified Chinese": "划时代的" },
    reading: "かっきてき",
    romanization: "kakkiteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "画期的な治療法が開発された。",
    exampleTranslations: { English: "A groundbreaking treatment was developed.", "Simplified Chinese": "开发出了划时代的治疗方法。" },
  },
  {
    id: "ja-jlpt-advanced-19",
    targetLanguage: "Japanese",
    targetText: "蓄積",
    meanings: { English: "accumulation, buildup", "Simplified Chinese": "积累，蓄积" },
    reading: "ちくせき",
    romanization: "chikuseki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "長年の経験の蓄積が成果につながった。",
    exampleTranslations: { English: "Years of accumulated experience led to results.", "Simplified Chinese": "多年积累的经验促成了成果。" },
  },
  {
    id: "ja-jlpt-advanced-20",
    targetLanguage: "Japanese",
    targetText: "遂行",
    meanings: { English: "execution, carrying out", "Simplified Chinese": "执行，完成" },
    reading: "すいこう",
    romanization: "suiko",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "任務を遂行するために全力を尽くす。",
    exampleTranslations: { English: "I give my all to carry out the mission.", "Simplified Chinese": "为执行任务而全力以赴。" },
  },
  {
    id: "ja-jlpt-advanced-21",
    targetLanguage: "Japanese",
    targetText: "裁量",
    meanings: { English: "discretion, latitude", "Simplified Chinese": "裁量，酌情" },
    reading: "さいりょう",
    romanization: "sairyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "現場の裁量に委ねられている。",
    exampleTranslations: { English: "It is left to the discretion of those on site.", "Simplified Chinese": "交由现场酌情处理。" },
  },
  {
    id: "ja-jlpt-advanced-22",
    targetLanguage: "Japanese",
    targetText: "脆弱",
    meanings: { English: "fragile, vulnerable", "Simplified Chinese": "脆弱" },
    reading: "ぜいじゃく",
    romanization: "zeijaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "インフラの脆弱性が浮き彫りになった。",
    exampleTranslations: { English: "The fragility of the infrastructure was exposed.", "Simplified Chinese": "基础设施的脆弱性暴露出来了。" },
  },
  {
    id: "ko-topik-advanced-16",
    targetLanguage: "Korean",
    targetText: "여론",
    meanings: { English: "public opinion", "Simplified Chinese": "舆论，民意" },
    reading: "여론",
    romanization: "yeoron",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "여론 조사 결과가 정책에 반영되었다.",
    exampleTranslations: { English: "The results of the public opinion poll were reflected in the policy.", "Simplified Chinese": "舆论调查结果被纳入了政策。" },
  },
  {
    id: "ko-topik-advanced-17",
    targetLanguage: "Korean",
    targetText: "개혁",
    meanings: { English: "reform, reformation", "Simplified Chinese": "改革，革新" },
    reading: "개혁",
    romanization: "gaehyeok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "사회 구조의 근본적인 개혁이 필요하다.",
    exampleTranslations: { English: "Fundamental reform of social structure is needed.", "Simplified Chinese": "需要对社会结构进行根本性改革。" },
  },
  {
    id: "ko-topik-advanced-18",
    targetLanguage: "Korean",
    targetText: "인권",
    meanings: { English: "human rights", "Simplified Chinese": "人权" },
    reading: "인권",
    romanization: "ingwon",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "인권 보호는 국가의 기본적 의무이다.",
    exampleTranslations: { English: "Protecting human rights is a fundamental duty of the state.", "Simplified Chinese": "保护人权是国家的基本义务。" },
  },
  {
    id: "ko-topik-advanced-19",
    targetLanguage: "Korean",
    targetText: "혁신",
    meanings: { English: "innovation, breakthrough", "Simplified Chinese": "革新，创新" },
    reading: "혁신",
    romanization: "hyeoksin",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "기술 혁신이 산업 구조를 바꾸고 있다.",
    exampleTranslations: { English: "Technological innovation is transforming industrial structure.", "Simplified Chinese": "技术革新正在改变产业结构。" },
  },
  {
    id: "ko-topik-advanced-20",
    targetLanguage: "Korean",
    targetText: "은유",
    meanings: { English: "metaphor", "Simplified Chinese": "隐喻，比喻" },
    reading: "은유",
    romanization: "eunyu",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "문학에서 은유는 의미를 풍부하게 한다.",
    exampleTranslations: { English: "Metaphor enriches meaning in literature.", "Simplified Chinese": "文学中的隐喻使意义更加丰富。" },
  },
  {
    id: "ko-topik-advanced-21",
    targetLanguage: "Korean",
    targetText: "풍자",
    meanings: { English: "satire, irony", "Simplified Chinese": "讽刺，讥讽" },
    reading: "풍자",
    romanization: "pungja",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 소설은 사회를 신랄하게 풍자한다.",
    exampleTranslations: { English: "That novel sharply satirizes society.", "Simplified Chinese": "那部小说辛辣地讽刺了社会。" },
  },
  {
    id: "ko-topik-advanced-22",
    targetLanguage: "Korean",
    targetText: "윤리",
    meanings: { English: "ethics, morality", "Simplified Chinese": "伦理，道德" },
    reading: "윤리",
    romanization: "yulli",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "과학 연구에서 윤리적 기준을 준수해야 한다.",
    exampleTranslations: { English: "Ethical standards must be observed in scientific research.", "Simplified Chinese": "在科学研究中必须遵守伦理标准。" },
  },
  // --- JLPT 23–30 / TOPIK 23–30 ---
  {
    id: "ja-jlpt-advanced-23",
    targetLanguage: "Japanese",
    targetText: "膨大",
    meanings: { English: "enormous, vast", "Simplified Chinese": "庞大" },
    reading: "ぼうだい",
    romanization: "boudai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "膨大な量のデータを分析する必要がある。",
    exampleTranslations: { English: "An enormous amount of data needs to be analyzed.", "Simplified Chinese": "需要分析庞大的数据量。" },
  },
  {
    id: "ja-jlpt-advanced-24",
    targetLanguage: "Japanese",
    targetText: "微妙",
    meanings: { English: "subtle, delicate", "Simplified Chinese": "微妙" },
    reading: "びみょう",
    romanization: "bimyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "両者の間には微妙なニュアンスの違いがある。",
    exampleTranslations: { English: "There is a subtle nuance difference between the two.", "Simplified Chinese": "两者之间有微妙的语感差异。" },
  },
  {
    id: "ja-jlpt-advanced-25",
    targetLanguage: "Japanese",
    targetText: "斬新",
    meanings: { English: "novel, innovative", "Simplified Chinese": "新颖" },
    reading: "ざんしん",
    romanization: "zanshin",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "斬新な発想で業界を変えた。",
    exampleTranslations: { English: "A novel idea changed the industry.", "Simplified Chinese": "以新颖的构思改变了行业。" },
  },
  {
    id: "ja-jlpt-advanced-26",
    targetLanguage: "Japanese",
    targetText: "厳密",
    meanings: { English: "strict, rigorous, precise", "Simplified Chinese": "严密，精确" },
    reading: "げんみつ",
    romanization: "genmitsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "厳密に言えば、両者は異なる概念だ。",
    exampleTranslations: { English: "Strictly speaking, the two are different concepts.", "Simplified Chinese": "严格来说，两者是不同的概念。" },
  },
  {
    id: "ja-jlpt-advanced-27",
    targetLanguage: "Japanese",
    targetText: "一貫",
    meanings: { English: "consistency, coherence", "Simplified Chinese": "一贯，始终如一" },
    reading: "いっかん",
    romanization: "ikkan",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "一貫した姿勢を貫いた。",
    exampleTranslations: { English: "A consistent stance was maintained throughout.", "Simplified Chinese": "始终贯彻了一贯的立场。" },
  },
  {
    id: "ja-jlpt-advanced-28",
    targetLanguage: "Japanese",
    targetText: "唐突",
    meanings: { English: "abrupt, sudden", "Simplified Chinese": "唐突，冒昧" },
    reading: "とうとつ",
    romanization: "tototsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "唐突な質問で恐縮ですが。",
    exampleTranslations: { English: "Forgive the abrupt question, but...", "Simplified Chinese": "冒昧地问一下。" },
  },
  {
    id: "ja-jlpt-advanced-29",
    targetLanguage: "Japanese",
    targetText: "辞退",
    meanings: { English: "declining (an offer), withdrawal", "Simplified Chinese": "婉拒，辞退" },
    reading: "じたい",
    romanization: "jitai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "健康上の理由で出場を辞退した。",
    exampleTranslations: { English: "I withdrew from participation for health reasons.", "Simplified Chinese": "因健康原因辞退了参赛。" },
  },
  {
    id: "ja-jlpt-advanced-30",
    targetLanguage: "Japanese",
    targetText: "譲歩",
    meanings: { English: "concession, compromise", "Simplified Chinese": "让步" },
    reading: "じょうほ",
    romanization: "jouho",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "交渉の末、互いに譲歩した。",
    exampleTranslations: { English: "After negotiations, both sides made concessions.", "Simplified Chinese": "经过谈判，双方都做出了让步。" },
  },
  {
    id: "ko-topik-advanced-23",
    targetLanguage: "Korean",
    targetText: "가치관",
    meanings: { English: "values, worldview", "Simplified Chinese": "价值观" },
    reading: "가치관",
    romanization: "gachigwan",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "세대 간 가치관의 차이가 갈등을 유발한다.",
    exampleTranslations: { English: "Differences in values between generations cause conflict.", "Simplified Chinese": "代际价值观差异引发冲突。" },
  },
  {
    id: "ko-topik-advanced-24",
    targetLanguage: "Korean",
    targetText: "패러다임",
    meanings: { English: "paradigm", "Simplified Chinese": "范式，典范" },
    reading: "패러다임",
    romanization: "paereodaim",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "기존의 패러다임을 전환할 필요가 있다.",
    exampleTranslations: { English: "There is a need to shift the existing paradigm.", "Simplified Chinese": "有必要转换现有的范式。" },
  },
  {
    id: "ko-topik-advanced-25",
    targetLanguage: "Korean",
    targetText: "담론",
    meanings: { English: "discourse, discussion", "Simplified Chinese": "话语，论述" },
    reading: "담론",
    romanization: "damnon",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "사회적 담론이 정책 결정에 영향을 미친다.",
    exampleTranslations: { English: "Social discourse influences policy decisions.", "Simplified Chinese": "社会话语影响政策决定。" },
  },
  {
    id: "ko-topik-advanced-26",
    targetLanguage: "Korean",
    targetText: "맥락",
    meanings: { English: "context, thread", "Simplified Chinese": "脉络，语境" },
    reading: "맥락",
    romanization: "maengnak",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "발언의 맥락을 고려해야 정확히 이해할 수 있다.",
    exampleTranslations: { English: "You must consider the context to understand accurately.", "Simplified Chinese": "必须考虑发言的脉络才能准确理解。" },
  },
  {
    id: "ko-topik-advanced-27",
    targetLanguage: "Korean",
    targetText: "타당성",
    meanings: { English: "validity, legitimacy", "Simplified Chinese": "妥当性，合理性" },
    reading: "타당성",
    romanization: "tadangseong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 주장의 타당성을 검증해 보겠다.",
    exampleTranslations: { English: "I will verify the validity of this argument.", "Simplified Chinese": "我将验证这一主张的妥当性。" },
  },
  {
    id: "ko-topik-advanced-28",
    targetLanguage: "Korean",
    targetText: "객관성",
    meanings: { English: "objectivity, impartiality", "Simplified Chinese": "客观性" },
    reading: "객관성",
    romanization: "gaekgwanseong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "연구에서 객관성을 유지하는 것이 중요하다.",
    exampleTranslations: { English: "Maintaining objectivity in research is important.", "Simplified Chinese": "在研究中保持客观性很重要。" },
  },
  {
    id: "ko-topik-advanced-29",
    targetLanguage: "Korean",
    targetText: "보편적",
    meanings: { English: "universal, general", "Simplified Chinese": "普遍的" },
    reading: "보편적",
    romanization: "bopyeonjeok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "인권은 보편적 가치로 인정받는다.",
    exampleTranslations: { English: "Human rights are recognized as a universal value.", "Simplified Chinese": "人权被认可为普遍价值。" },
  },
  {
    id: "ko-topik-advanced-30",
    targetLanguage: "Korean",
    targetText: "괴리",
    meanings: { English: "discrepancy, gap", "Simplified Chinese": "隔阂，差距" },
    reading: "괴리",
    romanization: "goeri",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이상과 현실 사이에 괴리가 존재한다.",
    exampleTranslations: { English: "A discrepancy exists between ideals and reality.", "Simplified Chinese": "理想与现实之间存在隔阂。" },
  },
  // --- JLPT 31–38 / TOPIK 31–38 ---
  {
    id: "ja-jlpt-advanced-31",
    targetLanguage: "Japanese",
    targetText: "介入",
    meanings: { English: "intervention, involvement", "Simplified Chinese": "介入，干预" },
    reading: "かいにゅう",
    romanization: "kainyu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "政府が市場に介入した。",
    exampleTranslations: { English: "The government intervened in the market.", "Simplified Chinese": "政府介入了市场。" },
  },
  {
    id: "ja-jlpt-advanced-32",
    targetLanguage: "Japanese",
    targetText: "配慮",
    meanings: { English: "consideration, thoughtfulness", "Simplified Chinese": "关照，照顾" },
    reading: "はいりょ",
    romanization: "hairyo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "環境への配慮が求められている。",
    exampleTranslations: { English: "Consideration for the environment is required.", "Simplified Chinese": "人们要求顾及环境。" },
  },
  {
    id: "ja-jlpt-advanced-33",
    targetLanguage: "Japanese",
    targetText: "帰結",
    meanings: { English: "conclusion, consequence", "Simplified Chinese": "归结" },
    reading: "きけつ",
    romanization: "kiketsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "それは論理的な帰結に過ぎない。",
    exampleTranslations: { English: "That is merely a logical consequence.", "Simplified Chinese": "那不过是逻辑上的归结。" },
  },
  {
    id: "ja-jlpt-advanced-34",
    targetLanguage: "Japanese",
    targetText: "余儀なく",
    meanings: { English: "unavoidably, forced to", "Simplified Chinese": "不得不" },
    reading: "よぎなく",
    romanization: "yoginaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "台風で中止を余儀なくされた。",
    exampleTranslations: { English: "The typhoon forced us to cancel.", "Simplified Chinese": "因台风不得不取消。" },
  },
  {
    id: "ja-jlpt-advanced-35",
    targetLanguage: "Japanese",
    targetText: "辛うじて",
    meanings: { English: "barely, narrowly", "Simplified Chinese": "勉强" },
    reading: "かろうじて",
    romanization: "karoujite",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "辛うじて合格ラインに達した。",
    exampleTranslations: { English: "I barely reached the passing mark.", "Simplified Chinese": "勉强达到了及格线。" },
  },
  {
    id: "ja-jlpt-advanced-36",
    targetLanguage: "Japanese",
    targetText: "漠然と",
    meanings: { English: "vaguely", "Simplified Chinese": "模糊地，隐约" },
    reading: "ばくぜんと",
    romanization: "bakuzento",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "将来に漠然とした不安を抱えている。",
    exampleTranslations: { English: "I harbor a vague anxiety about the future.", "Simplified Chinese": "对未来怀着隐约的不安。" },
  },
  {
    id: "ja-jlpt-advanced-37",
    targetLanguage: "Japanese",
    targetText: "齟齬",
    meanings: { English: "discrepancy, disagreement", "Simplified Chinese": "龃龉，不一致" },
    reading: "そご",
    romanization: "sogo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "双方の認識に齟齬が生じた。",
    exampleTranslations: { English: "A discrepancy arose between both sides' understanding.", "Simplified Chinese": "双方的认识产生了龃龉。" },
  },
  {
    id: "ja-jlpt-advanced-38",
    targetLanguage: "Japanese",
    targetText: "不可欠",
    meanings: { English: "indispensable, essential", "Simplified Chinese": "不可或缺" },
    reading: "ふかけつ",
    romanization: "fukaketsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "国際協力は平和の実現に不可欠だ。",
    exampleTranslations: { English: "International cooperation is indispensable for achieving peace.", "Simplified Chinese": "国际合作对实现和平不可或缺。" },
  },
  {
    id: "ko-topik-advanced-31",
    targetLanguage: "Korean",
    targetText: "양극화",
    meanings: { English: "polarization", "Simplified Chinese": "两极化" },
    reading: "양극화",
    romanization: "yanggeukhwa",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "소득 양극화가 심화되고 있다.",
    exampleTranslations: { English: "Income polarization is intensifying.", "Simplified Chinese": "收入两极化正在加深。" },
  },
  {
    id: "ko-topik-advanced-32",
    targetLanguage: "Korean",
    targetText: "지양하다",
    meanings: { English: "to sublate, to avoid/overcome", "Simplified Chinese": "扬弃，避免" },
    reading: "지양하다",
    romanization: "jiyanghada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "단순한 이분법적 사고를 지양해야 한다.",
    exampleTranslations: { English: "We should move beyond simplistic binary thinking.", "Simplified Chinese": "应该扬弃简单的二元思维。" },
  },
  {
    id: "ko-topik-advanced-33",
    targetLanguage: "Korean",
    targetText: "지향하다",
    meanings: { English: "to aim for, to aspire to", "Simplified Chinese": "追求，指向" },
    reading: "지향하다",
    romanization: "jihyanghada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "우리 사회는 지속 가능한 발전을 지향한다.",
    exampleTranslations: { English: "Our society aspires to sustainable development.", "Simplified Chinese": "我们的社会追求可持续发展。" },
  },
  {
    id: "ko-topik-advanced-34",
    targetLanguage: "Korean",
    targetText: "도출하다",
    meanings: { English: "to derive, to draw out", "Simplified Chinese": "得出，推导出" },
    reading: "도출하다",
    romanization: "dochulhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "실험 결과로부터 결론을 도출했다.",
    exampleTranslations: { English: "A conclusion was derived from the experimental results.", "Simplified Chinese": "从实验结果中得出了结论。" },
  },
  {
    id: "ko-topik-advanced-35",
    targetLanguage: "Korean",
    targetText: "축적하다",
    meanings: { English: "to accumulate, to amass", "Simplified Chinese": "积累" },
    reading: "축적하다",
    romanization: "chukjeokhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "오랜 기간 경험을 축적해 왔다.",
    exampleTranslations: { English: "Experience has been accumulated over a long period.", "Simplified Chinese": "长期以来一直在积累经验。" },
  },
  {
    id: "ko-topik-advanced-36",
    targetLanguage: "Korean",
    targetText: "부각되다",
    meanings: { English: "to be highlighted, to come to the fore", "Simplified Chinese": "凸显，突出" },
    reading: "부각되다",
    romanization: "bugakdoeda",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "환경 문제가 국제적으로 부각되고 있다.",
    exampleTranslations: { English: "Environmental issues are being highlighted internationally.", "Simplified Chinese": "环境问题在国际上日益凸显。" },
  },
  {
    id: "ko-topik-advanced-37",
    targetLanguage: "Korean",
    targetText: "대두되다",
    meanings: { English: "to emerge, to rise (as an issue)", "Simplified Chinese": "涌现，抬头" },
    reading: "대두되다",
    romanization: "daedudoeda",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "새로운 사회 문제가 대두되고 있다.",
    exampleTranslations: { English: "New social problems are emerging.", "Simplified Chinese": "新的社会问题正在涌现。" },
  },
  {
    id: "ko-topik-advanced-38",
    targetLanguage: "Korean",
    targetText: "내재하다",
    meanings: { English: "to be inherent, to be latent", "Simplified Chinese": "内在，潜在" },
    reading: "내재하다",
    romanization: "naejaehada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "모든 제도에는 한계가 내재한다.",
    exampleTranslations: { English: "Limitations are inherent in all systems.", "Simplified Chinese": "所有制度都内在着局限性。" },
  },
  // --- JLPT 39–45 / TOPIK 39–45 ---
  {
    id: "ja-jlpt-advanced-39",
    targetLanguage: "Japanese",
    targetText: "精緻",
    meanings: { English: "elaborate, meticulous", "Simplified Chinese": "精致，精密" },
    reading: "せいち",
    romanization: "seichi",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "精緻な論理構造に感心した。",
    exampleTranslations: { English: "I was impressed by the meticulous logical structure.", "Simplified Chinese": "我对精密的逻辑结构深为赞叹。" },
  },
  {
    id: "ja-jlpt-advanced-40",
    targetLanguage: "Japanese",
    targetText: "瀬戸際",
    meanings: { English: "brink, critical moment", "Simplified Chinese": "紧要关头" },
    reading: "せとぎわ",
    romanization: "setogiwa",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "会社は倒産の瀬戸際に立たされている。",
    exampleTranslations: { English: "The company stands on the brink of bankruptcy.", "Simplified Chinese": "公司正处于破产的紧要关头。" },
  },
  {
    id: "ja-jlpt-advanced-41",
    targetLanguage: "Japanese",
    targetText: "折衷",
    meanings: { English: "compromise, blending", "Simplified Chinese": "折中" },
    reading: "せっちゅう",
    romanization: "setchu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "和洋折衷の建築が増えている。",
    exampleTranslations: { English: "Architecture blending Japanese and Western styles is increasing.", "Simplified Chinese": "和洋折中的建筑越来越多。" },
  },
  {
    id: "ja-jlpt-advanced-42",
    targetLanguage: "Japanese",
    targetText: "淘汰",
    meanings: { English: "weeding out, elimination", "Simplified Chinese": "淘汰" },
    reading: "とうた",
    romanization: "touta",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "競争力のない企業は淘汰される。",
    exampleTranslations: { English: "Uncompetitive companies will be weeded out.", "Simplified Chinese": "缺乏竞争力的企业会被淘汰。" },
  },
  {
    id: "ja-jlpt-advanced-43",
    targetLanguage: "Japanese",
    targetText: "自律",
    meanings: { English: "autonomy, self-discipline", "Simplified Chinese": "自律" },
    reading: "じりつ",
    romanization: "jiritsu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "自律的に行動できる人材が求められる。",
    exampleTranslations: { English: "Personnel who can act autonomously are in demand.", "Simplified Chinese": "需要能够自律行动的人才。" },
  },
  {
    id: "ja-jlpt-advanced-44",
    targetLanguage: "Japanese",
    targetText: "妨げる",
    meanings: { English: "to hinder, to obstruct", "Simplified Chinese": "妨碍，阻碍" },
    reading: "さまたげる",
    romanization: "samatageru",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "過度な規制が成長を妨げている。",
    exampleTranslations: { English: "Excessive regulation is hindering growth.", "Simplified Chinese": "过度的管制妨碍了成长。" },
  },
  {
    id: "ja-jlpt-advanced-45",
    targetLanguage: "Japanese",
    targetText: "覆す",
    meanings: { English: "to overturn, to reverse", "Simplified Chinese": "推翻，颠覆" },
    reading: "くつがえす",
    romanization: "kutsugaesu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "常識を覆す発見だった。",
    exampleTranslations: { English: "It was a discovery that overturned common sense.", "Simplified Chinese": "这是颠覆常识的发现。" },
  },
  {
    id: "ko-topik-advanced-39",
    targetLanguage: "Korean",
    targetText: "표방하다",
    meanings: { English: "to profess, to advocate", "Simplified Chinese": "标榜，倡导" },
    reading: "표방하다",
    romanization: "pyobanghada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 단체는 평화를 표방하고 있다.",
    exampleTranslations: { English: "That organization professes peace.", "Simplified Chinese": "那个团体标榜和平。" },
  },
  {
    id: "ko-topik-advanced-40",
    targetLanguage: "Korean",
    targetText: "상정하다",
    meanings: { English: "to assume, to presuppose", "Simplified Chinese": "假定，设想" },
    reading: "상정하다",
    romanization: "sangjeonghada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "최악의 시나리오를 상정하고 대비해야 한다.",
    exampleTranslations: { English: "We must assume the worst scenario and prepare.", "Simplified Chinese": "必须假定最坏的情况并做好准备。" },
  },
  {
    id: "ko-topik-advanced-41",
    targetLanguage: "Korean",
    targetText: "견지하다",
    meanings: { English: "to maintain (a position), to uphold", "Simplified Chinese": "坚持，维持" },
    reading: "견지하다",
    romanization: "gyeonjihada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "중립적 입장을 견지해야 한다.",
    exampleTranslations: { English: "A neutral stance must be upheld.", "Simplified Chinese": "必须坚持中立立场。" },
  },
  {
    id: "ko-topik-advanced-42",
    targetLanguage: "Korean",
    targetText: "포괄하다",
    meanings: { English: "to encompass, to cover broadly", "Simplified Chinese": "涵盖，包括" },
    reading: "포괄하다",
    romanization: "pogwalhada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 법안은 다양한 사회적 문제를 포괄한다.",
    exampleTranslations: { English: "This bill encompasses various social issues.", "Simplified Chinese": "这项法案涵盖了各种社会问题。" },
  },
  {
    id: "ko-topik-advanced-43",
    targetLanguage: "Korean",
    targetText: "상충하다",
    meanings: { English: "to conflict, to clash", "Simplified Chinese": "相冲突，相矛盾" },
    reading: "상충하다",
    romanization: "sangchunghada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "개인의 이익과 공공의 이익이 상충할 수 있다.",
    exampleTranslations: { English: "Individual and public interests can conflict.", "Simplified Chinese": "个人利益和公共利益可能相冲突。" },
  },
  {
    id: "ko-topik-advanced-44",
    targetLanguage: "Korean",
    targetText: "귀속되다",
    meanings: { English: "to be attributed to, to belong to", "Simplified Chinese": "归属，属于" },
    reading: "귀속되다",
    romanization: "gwisokdoeda",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 성과는 팀 전체에 귀속된다.",
    exampleTranslations: { English: "That achievement is attributed to the entire team.", "Simplified Chinese": "那项成果归属于整个团队。" },
  },
  {
    id: "ko-topik-advanced-45",
    targetLanguage: "Korean",
    targetText: "획일적",
    meanings: { English: "uniform, cookie-cutter", "Simplified Chinese": "划一的，千篇一律的" },
    reading: "획일적",
    romanization: "hoegiljeok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "획일적인 교육 방식은 창의성을 저해한다.",
    exampleTranslations: { English: "A cookie-cutter educational approach hinders creativity.", "Simplified Chinese": "千篇一律的教育方式妨碍创造性。" },
  },
  // --- JLPT 46–53 / TOPIK 46–53 ---
  {
    id: "ja-jlpt-advanced-46",
    targetLanguage: "Japanese",
    targetText: "培う",
    meanings: { English: "to cultivate, to foster", "Simplified Chinese": "培养，培育" },
    reading: "つちかう",
    romanization: "tsuchikau",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "信頼関係を培うには時間がかかる。",
    exampleTranslations: { English: "It takes time to cultivate a relationship of trust.", "Simplified Chinese": "培养信任关系需要时间。" },
  },
  {
    id: "ja-jlpt-advanced-47",
    targetLanguage: "Japanese",
    targetText: "携わる",
    meanings: { English: "to be involved in, to take part in", "Simplified Chinese": "从事，参与" },
    reading: "たずさわる",
    romanization: "tazusawaru",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "長年教育に携わってきた。",
    exampleTranslations: { English: "I have been involved in education for many years.", "Simplified Chinese": "多年来一直从事教育工作。" },
  },
  {
    id: "ja-jlpt-advanced-48",
    targetLanguage: "Japanese",
    targetText: "見なす",
    meanings: { English: "to regard as, to deem", "Simplified Chinese": "视为，认定" },
    reading: "みなす",
    romanization: "minasu",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "沈黙は同意と見なされる場合がある。",
    exampleTranslations: { English: "Silence may be deemed as consent.", "Simplified Chinese": "沉默有时会被视为同意。" },
  },
  {
    id: "ja-jlpt-advanced-49",
    targetLanguage: "Japanese",
    targetText: "免れる",
    meanings: { English: "to escape, to be exempt from", "Simplified Chinese": "免于，逃脱" },
    reading: "まぬがれる",
    romanization: "manugareru",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "責任を免れることはできない。",
    exampleTranslations: { English: "One cannot escape responsibility.", "Simplified Chinese": "不能免于承担责任。" },
  },
  {
    id: "ja-jlpt-advanced-50",
    targetLanguage: "Japanese",
    targetText: "凌駕",
    meanings: { English: "to surpass, to exceed", "Simplified Chinese": "凌驾，超越" },
    reading: "りょうが",
    romanization: "ryouga",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "AIの能力が人間を凌駕する日が来るかもしれない。",
    exampleTranslations: { English: "A day may come when AI's capabilities surpass humans.", "Simplified Chinese": "AI的能力凌驾于人类之上的一天或许会到来。" },
  },
  {
    id: "ja-jlpt-advanced-51",
    targetLanguage: "Japanese",
    targetText: "恣意的",
    meanings: { English: "arbitrary, random", "Simplified Chinese": "恣意的，随意的" },
    reading: "しいてき",
    romanization: "shiiteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "恣意的な解釈は避けるべきだ。",
    exampleTranslations: { English: "Arbitrary interpretation should be avoided.", "Simplified Chinese": "应当避免恣意的解释。" },
  },
  {
    id: "ja-jlpt-advanced-52",
    targetLanguage: "Japanese",
    targetText: "逆説的",
    meanings: { English: "paradoxical", "Simplified Chinese": "悖论的" },
    reading: "ぎゃくせつてき",
    romanization: "gyakusetsuteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "逆説的だが、失敗が成功の鍵だった。",
    exampleTranslations: { English: "Paradoxically, failure was the key to success.", "Simplified Chinese": "说来矛盾，但失败才是成功的关键。" },
  },
  {
    id: "ja-jlpt-advanced-53",
    targetLanguage: "Japanese",
    targetText: "不可逆",
    meanings: { English: "irreversible", "Simplified Chinese": "不可逆" },
    reading: "ふかぎゃく",
    romanization: "fukagyaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "気候変動は不可逆な段階に入りつつある。",
    exampleTranslations: { English: "Climate change is entering an irreversible stage.", "Simplified Chinese": "气候变化正在进入不可逆的阶段。" },
  },
  {
    id: "ko-topik-advanced-46",
    targetLanguage: "Korean",
    targetText: "묘사",
    meanings: { English: "depiction, description", "Simplified Chinese": "描写，描绘" },
    reading: "묘사",
    romanization: "myosa",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "작가는 인물의 심리를 섬세하게 묘사했다.",
    exampleTranslations: { English: "The author delicately depicted the character's psychology.", "Simplified Chinese": "作家细腻地描写了人物的心理。" },
  },
  {
    id: "ko-topik-advanced-47",
    targetLanguage: "Korean",
    targetText: "서사",
    meanings: { English: "narrative, epic", "Simplified Chinese": "叙事" },
    reading: "서사",
    romanization: "seosa",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 영화는 거대한 서사 구조를 가지고 있다.",
    exampleTranslations: { English: "This film has a grand narrative structure.", "Simplified Chinese": "这部电影具有宏大的叙事结构。" },
  },
  {
    id: "ko-topik-advanced-48",
    targetLanguage: "Korean",
    targetText: "인식론",
    meanings: { English: "epistemology, theory of knowledge", "Simplified Chinese": "认识论" },
    reading: "인식론",
    romanization: "insikron",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "인식론은 지식의 본질과 한계를 탐구한다.",
    exampleTranslations: { English: "Epistemology explores the nature and limits of knowledge.", "Simplified Chinese": "认识论探究知识的本质和局限。" },
  },
  {
    id: "ko-topik-advanced-49",
    targetLanguage: "Korean",
    targetText: "도덕",
    meanings: { English: "morality, moral principles", "Simplified Chinese": "道德，品德" },
    reading: "도덕",
    romanization: "dodeok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "도덕적 판단은 시대에 따라 변할 수 있다.",
    exampleTranslations: { English: "Moral judgments can change with the times.", "Simplified Chinese": "道德判断可能随时代而变化。" },
  },
  {
    id: "ko-topik-advanced-50",
    targetLanguage: "Korean",
    targetText: "배태하다",
    meanings: { English: "to conceive, to incubate", "Simplified Chinese": "孕育，酝酿" },
    reading: "배태하다",
    romanization: "baetaehada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "새로운 문화가 도시에서 배태되고 있다.",
    exampleTranslations: { English: "A new culture is being incubated in the city.", "Simplified Chinese": "新的文化正在城市中孕育。" },
  },
  {
    id: "ko-topik-advanced-51",
    targetLanguage: "Korean",
    targetText: "담지하다",
    meanings: { English: "to embody, to carry (meaning)", "Simplified Chinese": "承载" },
    reading: "담지하다",
    romanization: "damjihada",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "예술은 시대의 정신을 담지한다.",
    exampleTranslations: { English: "Art embodies the spirit of the era.", "Simplified Chinese": "艺术承载着时代的精神。" },
  },
  {
    id: "ko-topik-advanced-52",
    targetLanguage: "Korean",
    targetText: "민주주의",
    meanings: { English: "democracy", "Simplified Chinese": "民主主义" },
    reading: "민주주의",
    romanization: "minjujuui",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "민주주의의 핵심은 국민의 주권이다.",
    exampleTranslations: { English: "The core of democracy is the sovereignty of the people.", "Simplified Chinese": "民主主义的核心是国民主权。" },
  },
  {
    id: "ko-topik-advanced-53",
    targetLanguage: "Korean",
    targetText: "생태계",
    meanings: { English: "ecosystem", "Simplified Chinese": "生态系统" },
    reading: "생태계",
    romanization: "saengtaegye",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "도시 개발로 인해 생태계가 위협받고 있다.",
    exampleTranslations: { English: "Ecosystems are threatened due to urban development.", "Simplified Chinese": "由于城市开发，生态系统正受到威胁。" },
  },
  // --- JLPT 54–60 / TOPIK 54–60 ---
  {
    id: "ja-jlpt-advanced-54",
    targetLanguage: "Japanese",
    targetText: "冗長",
    meanings: { English: "verbose, redundant", "Simplified Chinese": "冗长" },
    reading: "じょうちょう",
    romanization: "joucho",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "冗長な説明は聞き手を疲れさせる。",
    exampleTranslations: { English: "Verbose explanations tire the listener.", "Simplified Chinese": "冗长的说明会让听者疲倦。" },
  },
  {
    id: "ja-jlpt-advanced-55",
    targetLanguage: "Japanese",
    targetText: "端的",
    meanings: { English: "straightforward, to the point", "Simplified Chinese": "直截了当" },
    reading: "たんてき",
    romanization: "tanteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "端的に言えば、計画は失敗だった。",
    exampleTranslations: { English: "To put it bluntly, the plan was a failure.", "Simplified Chinese": "直截了当地说，计划失败了。" },
  },
  {
    id: "ja-jlpt-advanced-56",
    targetLanguage: "Japanese",
    targetText: "暫定的",
    meanings: { English: "provisional, tentative", "Simplified Chinese": "暂定的" },
    reading: "ざんていてき",
    romanization: "zanteiteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "暫定的な措置として実施された。",
    exampleTranslations: { English: "It was implemented as a provisional measure.", "Simplified Chinese": "作为暂定措施实施了。" },
  },
  {
    id: "ja-jlpt-advanced-57",
    targetLanguage: "Japanese",
    targetText: "承諾",
    meanings: { English: "consent, agreement", "Simplified Chinese": "承诺，同意" },
    reading: "しょうだく",
    romanization: "shodaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "本人の承諾なく情報を公開してはならない。",
    exampleTranslations: { English: "Information must not be disclosed without consent.", "Simplified Chinese": "未经本人承诺不得公开信息。" },
  },
  {
    id: "ja-jlpt-advanced-58",
    targetLanguage: "Japanese",
    targetText: "催促",
    meanings: { English: "urging, pressing (for action)", "Simplified Chinese": "催促" },
    reading: "さいそく",
    romanization: "saisoku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "何度も返答を催促された。",
    exampleTranslations: { English: "I was repeatedly pressed for a reply.", "Simplified Chinese": "被多次催促回复。" },
  },
  {
    id: "ja-jlpt-advanced-59",
    targetLanguage: "Japanese",
    targetText: "排除",
    meanings: { English: "exclusion, elimination", "Simplified Chinese": "排除" },
    reading: "はいじょ",
    romanization: "haijo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "不正行為を排除するための仕組みが必要だ。",
    exampleTranslations: { English: "A mechanism to eliminate misconduct is needed.", "Simplified Chinese": "需要建立排除违规行为的机制。" },
  },
  {
    id: "ja-jlpt-advanced-60",
    targetLanguage: "Japanese",
    targetText: "補填",
    meanings: { English: "compensation, filling a gap", "Simplified Chinese": "填补，弥补" },
    reading: "ほてん",
    romanization: "hoten",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "赤字を補填するための策を講じた。",
    exampleTranslations: { English: "Measures were taken to compensate for the deficit.", "Simplified Chinese": "采取了填补赤字的措施。" },
  },
  {
    id: "ko-topik-advanced-54",
    targetLanguage: "Korean",
    targetText: "서술",
    meanings: { English: "narration, description", "Simplified Chinese": "叙述，描述" },
    reading: "서술",
    romanization: "seosul",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "사건의 경위를 객관적으로 서술하시오.",
    exampleTranslations: { English: "Describe the course of events objectively.", "Simplified Chinese": "请客观地叙述事件的经过。" },
  },
  {
    id: "ko-topik-advanced-55",
    targetLanguage: "Korean",
    targetText: "비유",
    meanings: { English: "analogy, simile", "Simplified Chinese": "比喻，类比" },
    reading: "비유",
    romanization: "biyu",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "복잡한 개념을 비유를 통해 설명했다.",
    exampleTranslations: { English: "Complex concepts were explained through analogy.", "Simplified Chinese": "通过比喻说明了复杂的概念。" },
  },
  {
    id: "ko-topik-advanced-56",
    targetLanguage: "Korean",
    targetText: "존재론",
    meanings: { English: "ontology, theory of existence", "Simplified Chinese": "存在论，本体论" },
    reading: "존재론",
    romanization: "jonjaeron",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "존재론은 철학의 근본적인 분야이다.",
    exampleTranslations: { English: "Ontology is a fundamental field of philosophy.", "Simplified Chinese": "存在论是哲学的根本领域。" },
  },
  {
    id: "ko-topik-advanced-57",
    targetLanguage: "Korean",
    targetText: "서정",
    meanings: { English: "lyricism, lyrical sentiment", "Simplified Chinese": "抒情" },
    reading: "서정",
    romanization: "seojeong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 시는 깊은 서정적 아름다움을 지닌다.",
    exampleTranslations: { English: "That poem possesses deep lyrical beauty.", "Simplified Chinese": "那首诗具有深沉的抒情之美。" },
  },
  {
    id: "ko-topik-advanced-58",
    targetLanguage: "Korean",
    targetText: "취지",
    meanings: { English: "purpose, intent, gist", "Simplified Chinese": "宗旨，用意" },
    reading: "취지",
    romanization: "chwiji",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 정책의 취지는 사회적 불평등을 줄이는 것이다.",
    exampleTranslations: { English: "The intent of this policy is to reduce social inequality.", "Simplified Chinese": "这项政策的宗旨是减少社会不平等。" },
  },
  {
    id: "ko-topik-advanced-59",
    targetLanguage: "Korean",
    targetText: "함축",
    meanings: { English: "implication, connotation", "Simplified Chinese": "含蓄，暗示" },
    reading: "함축",
    romanization: "hamchuk",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "이 표현에는 깊은 함축적 의미가 담겨 있다.",
    exampleTranslations: { English: "This expression carries deep connotative meaning.", "Simplified Chinese": "这个表达蕴含着深层的含蓄意义。" },
  },
  {
    id: "ko-topik-advanced-60",
    targetLanguage: "Korean",
    targetText: "여파",
    meanings: { English: "aftermath, repercussion", "Simplified Chinese": "余波，后果" },
    reading: "여파",
    romanization: "yeopa",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "경제 위기의 여파가 아직도 남아 있다.",
    exampleTranslations: { English: "The aftermath of the economic crisis still remains.", "Simplified Chinese": "经济危机的余波至今仍然存在。" },
  },
  // --- JLPT 61–68 / TOPIK 61–68 ---
  {
    id: "ja-jlpt-advanced-61",
    targetLanguage: "Japanese",
    targetText: "断片的",
    meanings: { English: "fragmentary, piecemeal", "Simplified Chinese": "片段的，零碎的" },
    reading: "だんぺんてき",
    romanization: "danpenteki",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "断片的な情報では全体像がつかめない。",
    exampleTranslations: { English: "A complete picture cannot be grasped from fragmentary information.", "Simplified Chinese": "从片段的信息无法把握全貌。" },
  },
  {
    id: "ja-jlpt-advanced-62",
    targetLanguage: "Japanese",
    targetText: "多様性",
    meanings: { English: "diversity", "Simplified Chinese": "多样性" },
    reading: "たようせい",
    romanization: "tayousei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "生物多様性の保全が急務だ。",
    exampleTranslations: { English: "Preserving biodiversity is an urgent task.", "Simplified Chinese": "保护生物多样性迫在眉睫。" },
  },
  {
    id: "ja-jlpt-advanced-63",
    targetLanguage: "Japanese",
    targetText: "的確",
    meanings: { English: "accurate, precise, apt", "Simplified Chinese": "准确，恰当" },
    reading: "てきかく",
    romanization: "tekikaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "的確な指摘で議論が前に進んだ。",
    exampleTranslations: { English: "An apt observation moved the discussion forward.", "Simplified Chinese": "准确的指出推动了讨论。" },
  },
  {
    id: "ja-jlpt-advanced-64",
    targetLanguage: "Japanese",
    targetText: "委託",
    meanings: { English: "commission, entrustment", "Simplified Chinese": "委托" },
    reading: "いたく",
    romanization: "itaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "調査を外部機関に委託した。",
    exampleTranslations: { English: "The investigation was commissioned to an outside agency.", "Simplified Chinese": "把调查委托给了外部机构。" },
  },
  {
    id: "ja-jlpt-advanced-65",
    targetLanguage: "Japanese",
    targetText: "撤回",
    meanings: { English: "withdrawal, retraction", "Simplified Chinese": "撤回" },
    reading: "てっかい",
    romanization: "tekkai",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "批判を受けて発言を撤回した。",
    exampleTranslations: { English: "Facing criticism, the remark was retracted.", "Simplified Chinese": "在批评声中撤回了发言。" },
  },
  {
    id: "ja-jlpt-advanced-66",
    targetLanguage: "Japanese",
    targetText: "削減",
    meanings: { English: "reduction, cutback", "Simplified Chinese": "削减" },
    reading: "さくげん",
    romanization: "sakugen",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "温室効果ガスの排出量を削減する。",
    exampleTranslations: { English: "We will cut greenhouse gas emissions.", "Simplified Chinese": "削减温室气体排放量。" },
  },
  {
    id: "ja-jlpt-advanced-67",
    targetLanguage: "Japanese",
    targetText: "統合",
    meanings: { English: "integration, unification", "Simplified Chinese": "统合，整合" },
    reading: "とうごう",
    romanization: "tougo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "複数の部署を統合して効率化を図る。",
    exampleTranslations: { English: "We aim for efficiency by integrating multiple departments.", "Simplified Chinese": "通过整合多个部门来提高效率。" },
  },
  {
    id: "ja-jlpt-advanced-68",
    targetLanguage: "Japanese",
    targetText: "考慮",
    meanings: { English: "consideration, deliberation", "Simplified Chinese": "考虑，斟酌" },
    reading: "こうりょ",
    romanization: "koryo",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "様々な要因を考慮した上で決定した。",
    exampleTranslations: { English: "The decision was made after considering various factors.", "Simplified Chinese": "在考虑了各种因素之后做出了决定。" },
  },
  {
    id: "ko-topik-advanced-61",
    targetLanguage: "Korean",
    targetText: "파장",
    meanings: { English: "ripple effect, repercussion", "Simplified Chinese": "波澜，影响" },
    reading: "파장",
    romanization: "pajang",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그 사건은 사회 전반에 큰 파장을 일으켰다.",
    exampleTranslations: { English: "The incident caused a big ripple effect across society.", "Simplified Chinese": "那起事件在社会各界引起了巨大波澜。" },
  },
  {
    id: "ko-topik-advanced-62",
    targetLanguage: "Korean",
    targetText: "인플레이션",
    meanings: { English: "inflation", "Simplified Chinese": "通货膨胀" },
    reading: "인플레이션",
    romanization: "inpeullreisyeon",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "인플레이션으로 인해 생활비가 급등했다.",
    exampleTranslations: { English: "Living costs surged due to inflation.", "Simplified Chinese": "由于通货膨胀，生活费急剧上涨。" },
  },
  {
    id: "ko-topik-advanced-63",
    targetLanguage: "Korean",
    targetText: "알고리즘",
    meanings: { English: "algorithm", "Simplified Chinese": "算法" },
    reading: "알고리즘",
    romanization: "algorijeum",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "추천 알고리즘이 사용자 경험을 결정한다.",
    exampleTranslations: { English: "Recommendation algorithms determine user experience.", "Simplified Chinese": "推荐算法决定用户体验。" },
  },
  {
    id: "ko-topik-advanced-64",
    targetLanguage: "Korean",
    targetText: "주관적",
    meanings: { English: "subjective, personal", "Simplified Chinese": "主观的" },
    reading: "주관적",
    romanization: "jugwanjeok",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "예술에 대한 평가는 주관적일 수밖에 없다.",
    exampleTranslations: { English: "Evaluation of art is inevitably subjective.", "Simplified Chinese": "对艺术的评价不可避免地是主观的。" },
  },
  {
    id: "ko-topik-advanced-65",
    targetLanguage: "Korean",
    targetText: "체제",
    meanings: { English: "system, regime", "Simplified Chinese": "体制" },
    reading: "체제",
    romanization: "cheje",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "정치 체제의 변화가 불가피하다.",
    exampleTranslations: { English: "Changes in the political system are inevitable.", "Simplified Chinese": "政治体制的变化不可避免。" },
  },
  {
    id: "ko-topik-advanced-66",
    targetLanguage: "Korean",
    targetText: "투자",
    meanings: { English: "investment", "Simplified Chinese": "投资" },
    reading: "투자",
    romanization: "tuja",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "장기적 관점에서 투자 전략을 수립해야 한다.",
    exampleTranslations: { English: "Investment strategies should be established from a long-term perspective.", "Simplified Chinese": "应该从长远角度制定投资战略。" },
  },
  {
    id: "ko-topik-advanced-67",
    targetLanguage: "Korean",
    targetText: "재정",
    meanings: { English: "finance, public finance", "Simplified Chinese": "财政" },
    reading: "재정",
    romanization: "jaejeong",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "국가 재정이 악화되고 있다.",
    exampleTranslations: { English: "National finances are deteriorating.", "Simplified Chinese": "国家财政正在恶化。" },
  },
  {
    id: "ko-topik-advanced-68",
    targetLanguage: "Korean",
    targetText: "불황",
    meanings: { English: "recession, depression", "Simplified Chinese": "不景气，萧条" },
    reading: "불황",
    romanization: "bulhwang",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "장기 불황으로 실업률이 높아졌다.",
    exampleTranslations: { English: "Unemployment rose due to the prolonged recession.", "Simplified Chinese": "由于长期不景气，失业率升高了。" },
  },
  // --- JLPT 69–75 / TOPIK 69–75 ---
  {
    id: "ja-jlpt-advanced-69",
    targetLanguage: "Japanese",
    targetText: "把握",
    meanings: { English: "to grasp, to ascertain", "Simplified Chinese": "掌握，把握" },
    reading: "はあく",
    romanization: "haaku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "現状を正確に把握することが第一歩だ。",
    exampleTranslations: { English: "Accurately grasping the current situation is the first step.", "Simplified Chinese": "准确掌握现状是第一步。" },
  },
  {
    id: "ja-jlpt-advanced-70",
    targetLanguage: "Japanese",
    targetText: "促進",
    meanings: { English: "promotion, acceleration", "Simplified Chinese": "促进" },
    reading: "そくしん",
    romanization: "sokushin",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "国際交流の促進が図られている。",
    exampleTranslations: { English: "The promotion of international exchange is being pursued.", "Simplified Chinese": "正在推动促进国际交流。" },
  },
  {
    id: "ja-jlpt-advanced-71",
    targetLanguage: "Japanese",
    targetText: "抑制",
    meanings: { English: "suppression, restraint", "Simplified Chinese": "抑制" },
    reading: "よくせい",
    romanization: "yokusei",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "インフレを抑制するための金融政策だ。",
    exampleTranslations: { English: "It is a monetary policy to curb inflation.", "Simplified Chinese": "这是抑制通胀的金融政策。" },
  },
  {
    id: "ja-jlpt-advanced-72",
    targetLanguage: "Japanese",
    targetText: "克服",
    meanings: { English: "overcoming, conquest", "Simplified Chinese": "克服" },
    reading: "こくふく",
    romanization: "kokufuku",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "言語の壁を克服して信頼関係を築いた。",
    exampleTranslations: { English: "I overcame the language barrier and built trust.", "Simplified Chinese": "克服了语言障碍，建立了信任关系。" },
  },
  {
    id: "ja-jlpt-advanced-73",
    targetLanguage: "Japanese",
    targetText: "柔軟",
    meanings: { English: "flexible, adaptable", "Simplified Chinese": "灵活" },
    reading: "じゅうなん",
    romanization: "junan",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "状況に応じた柔軟な対応が求められる。",
    exampleTranslations: { English: "Flexible responses suited to the situation are required.", "Simplified Chinese": "需要根据情况做出灵活应对。" },
  },
  {
    id: "ja-jlpt-advanced-74",
    targetLanguage: "Japanese",
    targetText: "拒否",
    meanings: { English: "refusal, rejection, veto", "Simplified Chinese": "拒绝，否决" },
    reading: "きょひ",
    romanization: "kyohi",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "安全保障理事会で拒否権が行使された。",
    exampleTranslations: { English: "A veto was exercised in the Security Council.", "Simplified Chinese": "在安理会行使了否决权。" },
  },
  {
    id: "ja-jlpt-advanced-75",
    targetLanguage: "Japanese",
    targetText: "慎重",
    meanings: { English: "cautious, prudent, discreet", "Simplified Chinese": "慎重，谨慎" },
    reading: "しんちょう",
    romanization: "shincho",
    level: "Advanced",
    topic: "JLPT",
    exampleSentence: "慎重な議論を重ねた結果、方針が決まった。",
    exampleTranslations: { English: "The policy was decided after repeated careful deliberation.", "Simplified Chinese": "经过反复慎重的讨论后确定了方针。" },
  },
  {
    id: "ko-topik-advanced-69",
    targetLanguage: "Korean",
    targetText: "고려",
    meanings: { English: "consideration, deliberation", "Simplified Chinese": "考虑，斟酌" },
    reading: "고려",
    romanization: "goryeo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "다양한 요인을 고려하여 결정을 내렸다.",
    exampleTranslations: { English: "A decision was made after considering various factors.", "Simplified Chinese": "在考虑了各种因素之后做出了决定。" },
  },
  {
    id: "ko-topik-advanced-70",
    targetLanguage: "Korean",
    targetText: "모순",
    meanings: { English: "contradiction, inconsistency", "Simplified Chinese": "矛盾" },
    reading: "모순",
    romanization: "mosun",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "그의 주장에는 명백한 모순이 있다.",
    exampleTranslations: { English: "There is an obvious contradiction in his argument.", "Simplified Chinese": "他的主张中存在明显的矛盾。" },
  },
  {
    id: "ko-topik-advanced-71",
    targetLanguage: "Korean",
    targetText: "전제",
    meanings: { English: "premise, precondition", "Simplified Chinese": "前提" },
    reading: "전제",
    romanization: "jeonje",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "민주주의는 시민의 참여를 전제로 한다.",
    exampleTranslations: { English: "Democracy is premised on citizen participation.", "Simplified Chinese": "民主主义以公民参与为前提。" },
  },
  {
    id: "ko-topik-advanced-72",
    targetLanguage: "Korean",
    targetText: "조치",
    meanings: { English: "measure, step (taken)", "Simplified Chinese": "措施，处置" },
    reading: "조치",
    romanization: "jochi",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "정부는 긴급 조치를 시행했다.",
    exampleTranslations: { English: "The government implemented emergency measures.", "Simplified Chinese": "政府实施了紧急措施。" },
  },
  {
    id: "ko-topik-advanced-73",
    targetLanguage: "Korean",
    targetText: "파악",
    meanings: { English: "to grasp, to ascertain", "Simplified Chinese": "把握，了解" },
    reading: "파악",
    romanization: "paak",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "사고 원인을 정확히 파악해야 한다.",
    exampleTranslations: { English: "The cause of the accident must be accurately ascertained.", "Simplified Chinese": "必须准确了解事故原因。" },
  },
  {
    id: "ko-topik-advanced-74",
    targetLanguage: "Korean",
    targetText: "수요",
    meanings: { English: "demand, need", "Simplified Chinese": "需求" },
    reading: "수요",
    romanization: "suyo",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "소비자 수요가 공급을 초과하고 있다.",
    exampleTranslations: { English: "Consumer demand is exceeding supply.", "Simplified Chinese": "消费者需求正在超过供给。" },
  },
  {
    id: "ko-topik-advanced-75",
    targetLanguage: "Korean",
    targetText: "공급",
    meanings: { English: "supply, provision", "Simplified Chinese": "供给，供应" },
    reading: "공급",
    romanization: "gonggeup",
    level: "Advanced",
    topic: "TOPIK",
    exampleSentence: "원자재 공급이 불안정하다.",
    exampleTranslations: { English: "The supply of raw materials is unstable.", "Simplified Chinese": "原材料供应不稳定。" },
  },
];
