-- Expand ko-travel-basic to 150 curated entries (16-150)
-- Topic: travel vocabulary for basic Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-travel-basic-16', 'ko', 'basic', 'travel', '비행기', '비행기', 'bihaenggi', 'airplane', '飞机', '비행기를 타요.', 'I ride an airplane.', '我坐飞机。'),
  ('ko-travel-basic-17', 'ko', 'basic', 'travel', '기차', '기차', 'gicha', 'train', '火车', '기차를 타요.', 'I take the train.', '我坐火车。'),
  ('ko-travel-basic-18', 'ko', 'basic', 'travel', '지하철', '지하철', 'jihacheol', 'subway', '地铁', '지하철을 타요.', 'I take the subway.', '我坐地铁。'),
  ('ko-travel-basic-19', 'ko', 'basic', 'travel', '배', '배', 'bae', 'ship, boat', '船', '배를 타요.', 'I ride a boat.', '我坐船。'),
  ('ko-travel-basic-20', 'ko', 'basic', 'travel', '자전거', '자전거', 'jajeongeo', 'bicycle', '自行车', '자전거를 타요.', 'I ride a bicycle.', '我骑自行车。'),
  ('ko-travel-basic-21', 'ko', 'basic', 'travel', '여행', '여행', 'yeohaeng', 'travel, trip', '旅行', '여행을 가요.', 'I go on a trip.', '我去旅行。'),
  ('ko-travel-basic-22', 'ko', 'basic', 'travel', '관광', '관광', 'gwangwang', 'sightseeing', '观光', '관광을 해요.', 'I go sightseeing.', '我去观光。'),
  ('ko-travel-basic-23', 'ko', 'basic', 'travel', '여권', '여권', 'yeogwon', 'passport', '护照', '여권을 가져가요.', 'I bring my passport.', '我带护照。'),
  ('ko-travel-basic-24', 'ko', 'basic', 'travel', '비자', '비자', 'bija', 'visa', '签证', '비자가 필요해요.', 'I need a visa.', '我需要签证。'),
  ('ko-travel-basic-25', 'ko', 'basic', 'travel', '탑승', '탑승', 'tapseung', 'boarding', '登机', '탑승 시간이에요.', 'It''s boarding time.', '登机时间到了。'),
  ('ko-travel-basic-26', 'ko', 'basic', 'travel', '출발', '출발', 'chulbal', 'departure', '出发', '출발합니다.', 'We depart now.', '出发了。'),
  ('ko-travel-basic-27', 'ko', 'basic', 'travel', '도착', '도착', 'dochak', 'arrival', '到达', '도착했어요.', 'I arrived.', '我到了。'),
  ('ko-travel-basic-28', 'ko', 'basic', 'travel', '환승', '환승', 'hwanseung', 'transfer', '换乘', '여기서 환승해요.', 'I transfer here.', '我在这里换乘。'),
  ('ko-travel-basic-29', 'ko', 'basic', 'travel', '노선', '노선', 'noseon', 'route, line', '线路', '몇 호선이에요?', 'Which line is it?', '是几号线？'),
  ('ko-travel-basic-30', 'ko', 'basic', 'travel', '정류장', '정류장', 'jeongnyujang', 'bus stop', '公交站', '정류장에서 기다려요.', 'I wait at the bus stop.', '我在公交站等。'),
  ('ko-travel-basic-31', 'ko', 'basic', 'travel', '택시 정류장', '택시 정류장', 'taeksi jeongnyujang', 'taxi stand', '出租车站', '택시 정류장이 어디예요?', 'Where is the taxi stand?', '出租车站在哪？'),
  ('ko-travel-basic-32', 'ko', 'basic', 'travel', '공항버스', '공항버스', 'gonghangbeoseu', 'airport bus', '机场大巴', '공항버스를 타요.', 'I take the airport bus.', '我坐机场大巴。'),
  ('ko-travel-basic-33', 'ko', 'basic', 'travel', '숙소', '숙소', 'sukso', 'accommodation', '住处', '숙소를 예약했어요.', 'I booked accommodation.', '我预订了住处。'),
  ('ko-travel-basic-34', 'ko', 'basic', 'travel', '호스텔', '호스텔', 'hoseutel', 'hostel', '青旅', '호스텔에 묵어요.', 'I stay at a hostel.', '我住青旅。'),
  ('ko-travel-basic-35', 'ko', 'basic', 'travel', '방', '방', 'bang', 'room', '房间', '방을 예약해요.', 'I book a room.', '我预订房间。'),
  ('ko-travel-basic-36', 'ko', 'basic', 'travel', '체크인', '체크인', 'chekein', 'check-in', '入住', '체크인해요.', 'I check in.', '我办入住。'),
  ('ko-travel-basic-37', 'ko', 'basic', 'travel', '체크아웃', '체크아웃', 'chekeaut', 'check-out', '退房', '체크아웃해요.', 'I check out.', '我退房。'),
  ('ko-travel-basic-38', 'ko', 'basic', 'travel', '열쇠', '열쇠', 'yeolsoe', 'key', '钥匙', '열쇠를 받아요.', 'I receive the key.', '我拿钥匙。'),
  ('ko-travel-basic-39', 'ko', 'basic', 'travel', '엘리베이터', '엘리베이터', 'ellibeiteo', 'elevator', '电梯', '엘리베이터를 타요.', 'I take the elevator.', '我坐电梯。'),
  ('ko-travel-basic-40', 'ko', 'basic', 'travel', '계단', '계단', 'gyedan', 'stairs', '楼梯', '계단으로 올라가요.', 'I go up the stairs.', '我走楼梯上去。'),
  ('ko-travel-basic-41', 'ko', 'basic', 'travel', '화장실', '화장실', 'hwajangsil', 'restroom', '洗手间', '화장실이 어디예요?', 'Where is the restroom?', '洗手间在哪？'),
  ('ko-travel-basic-42', 'ko', 'basic', 'travel', '안내소', '안내소', 'annaeso', 'information center', '咨询处', '안내소에서 물어봐요.', 'I ask at the information center.', '我在咨询处问。'),
  ('ko-travel-basic-43', 'ko', 'basic', 'travel', '지도', '지도', 'jido', 'map', '地图', '지도를 봐요.', 'I look at the map.', '我看地图。'),
  ('ko-travel-basic-44', 'ko', 'basic', 'travel', '네비게이션', '네비게이션', 'nebigeisyeon', 'navigation, GPS', '导航', '네비게이션을 켜요.', 'I turn on the GPS.', '我打开导航。'),
  ('ko-travel-basic-45', 'ko', 'basic', 'travel', '직진', '직진', 'jikjin', 'go straight', '直走', '직진하세요.', 'Please go straight.', '请直走。'),
  ('ko-travel-basic-46', 'ko', 'basic', 'travel', '좌회전', '좌회전', 'jwahoejeon', 'turn left', '左转', '좌회전하세요.', 'Please turn left.', '请左转。'),
  ('ko-travel-basic-47', 'ko', 'basic', 'travel', '우회전', '우회전', 'uhoejeon', 'turn right', '右转', '우회전하세요.', 'Please turn right.', '请右转。'),
  ('ko-travel-basic-48', 'ko', 'basic', 'travel', '횡단보도', '횡단보도', 'hoengdanbodo', 'crosswalk', '人行横道', '횡단보도를 건너요.', 'I cross the crosswalk.', '我过人行横道。'),
  ('ko-travel-basic-49', 'ko', 'basic', 'travel', '신호등', '신호등', 'sinhodeung', 'traffic light', '红绿灯', '신호등이 빨간색이에요.', 'The traffic light is red.', '红绿灯是红色的。'),
  ('ko-travel-basic-50', 'ko', 'basic', 'travel', '주차장', '주차장', 'juchajang', 'parking lot', '停车场', '주차장이 있어요?', 'Is there a parking lot?', '有停车场吗？'),
  ('ko-travel-basic-51', 'ko', 'basic', 'travel', '주유소', '주유소', 'juyuso', 'gas station', '加油站', '주유소에 가요.', 'I go to the gas station.', '我去加油站。'),
  ('ko-travel-basic-52', 'ko', 'basic', 'travel', '편도', '편도', 'pyeondo', 'one-way', '单程', '편도 표 주세요.', 'One-way ticket please.', '请给我单程票。'),
  ('ko-travel-basic-53', 'ko', 'basic', 'travel', '왕복', '왕복', 'wangbok', 'round trip', '往返', '왕복 표를 사요.', 'I buy a round-trip ticket.', '我买往返票。'),
  ('ko-travel-basic-54', 'ko', 'basic', 'travel', '무료', '무료', 'muryo', 'free (no charge)', '免费', '무료예요.', 'It''s free.', '免费的。'),
  ('ko-travel-basic-55', 'ko', 'basic', 'travel', '요금', '요금', 'yogeum', 'fare, fee', '费用', '요금이 얼마예요?', 'How much is the fare?', '费用多少？'),
  ('ko-travel-basic-56', 'ko', 'basic', 'travel', '교통카드', '교통카드', 'gyotongkadeu', 'transit card', '交通卡', '교통카드를 충전해요.', 'I charge my transit card.', '我充值交通卡。'),
  ('ko-travel-basic-57', 'ko', 'basic', 'travel', '매표소', '매표소', 'maepyoso', 'ticket office', '售票处', '매표소에서 사요.', 'I buy it at the ticket office.', '我在售票处买。'),
  ('ko-travel-basic-58', 'ko', 'basic', 'travel', '플랫폼', '플랫폼', 'peullaetpom', 'platform', '站台', '플랫폼에서 기다려요.', 'I wait on the platform.', '我在站台等。'),
  ('ko-travel-basic-59', 'ko', 'basic', 'travel', '시간표', '시간표', 'siganpyo', 'timetable', '时刻表', '시간표를 확인해요.', 'I check the timetable.', '我看时刻表。'),
  ('ko-travel-basic-60', 'ko', 'basic', 'travel', '좌석', '좌석', 'jwaseok', 'seat', '座位', '좌석을 예약해요.', 'I reserve a seat.', '我预订座位。'),
  ('ko-travel-basic-61', 'ko', 'basic', 'travel', '창문', '창문', 'changmun', 'window', '窗户', '창문 쪽 자리 주세요.', 'Window seat please.', '请给我靠窗的座位。'),
  ('ko-travel-basic-62', 'ko', 'basic', 'travel', '복도', '복도', 'bokdo', 'aisle', '过道', '복도 쪽 자리 주세요.', 'Aisle seat please.', '请给我靠过道的座位。'),
  ('ko-travel-basic-63', 'ko', 'basic', 'travel', '수하물', '수하물', 'suhamul', 'luggage', '行李', '수하물을 맡겨요.', 'I check my luggage.', '我托运行李。'),
  ('ko-travel-basic-64', 'ko', 'basic', 'travel', '캐리어', '캐리어', 'kaerieo', 'suitcase', '行李箱', '캐리어를 끌어요.', 'I pull my suitcase.', '我拉行李箱。'),
  ('ko-travel-basic-65', 'ko', 'basic', 'travel', '배낭', '배낭', 'baenang', 'backpack', '背包', '배낭을 메요.', 'I carry a backpack.', '我背背包。'),
  ('ko-travel-basic-66', 'ko', 'basic', 'travel', '관광지', '관광지', 'gwangwangji', 'tourist spot', '旅游景点', '관광지에 가요.', 'I go to a tourist spot.', '我去旅游景点。'),
  ('ko-travel-basic-67', 'ko', 'basic', 'travel', '박물관', '박물관', 'bangmulgwan', 'museum', '博物馆', '박물관에 가요.', 'I go to a museum.', '我去博物馆。'),
  ('ko-travel-basic-68', 'ko', 'basic', 'travel', '궁', '궁', 'gung', 'palace', '宫殿', '궁을 구경해요.', 'I visit the palace.', '我参观宫殿。'),
  ('ko-travel-basic-69', 'ko', 'basic', 'travel', '절', '절', 'jeol', 'temple', '寺庙', '절에 가요.', 'I go to a temple.', '我去寺庙。'),
  ('ko-travel-basic-70', 'ko', 'basic', 'travel', '공원', '공원', 'gongwon', 'park', '公园', '공원에서 쉬어요.', 'I rest in the park.', '我在公园休息。'),
  ('ko-travel-basic-71', 'ko', 'basic', 'travel', '해변', '해변', 'haebyeon', 'beach', '海边', '해변에 가요.', 'I go to the beach.', '我去海边。'),
  ('ko-travel-basic-72', 'ko', 'basic', 'travel', '산', '산', 'san', 'mountain', '山', '산에 올라가요.', 'I climb the mountain.', '我爬山。'),
  ('ko-travel-basic-73', 'ko', 'basic', 'travel', '강', '강', 'gang', 'river', '河', '강을 따라 걸어요.', 'I walk along the river.', '我沿着河走。'),
  ('ko-travel-basic-74', 'ko', 'basic', 'travel', '섬', '섬', 'seom', 'island', '岛', '섬에 가요.', 'I go to an island.', '我去岛上。'),
  ('ko-travel-basic-75', 'ko', 'basic', 'travel', '사진', '사진', 'sajin', 'photo', '照片', '사진을 찍어요.', 'I take a photo.', '我拍照。'),
  ('ko-travel-basic-76', 'ko', 'basic', 'travel', '카메라', '카메라', 'kamera', 'camera', '相机', '카메라를 가져가요.', 'I bring my camera.', '我带相机。'),
  ('ko-travel-basic-77', 'ko', 'basic', 'travel', '기념품', '기념품', 'ginyeompum', 'souvenir', '纪念品', '기념품을 사요.', 'I buy souvenirs.', '我买纪念品。'),
  ('ko-travel-basic-78', 'ko', 'basic', 'travel', '면세점', '면세점', 'myeonsejeom', 'duty-free shop', '免税店', '면세점에서 사요.', 'I buy at the duty-free shop.', '我在免税店买。'),
  ('ko-travel-basic-79', 'ko', 'basic', 'travel', '환전', '환전', 'hwanjeon', 'currency exchange', '换钱', '환전을 해요.', 'I exchange currency.', '我换钱。'),
  ('ko-travel-basic-80', 'ko', 'basic', 'travel', '현금', '현금', 'hyeongeum', 'cash', '现金', '현금이 필요해요.', 'I need cash.', '我需要现金。'),
  ('ko-travel-basic-81', 'ko', 'basic', 'travel', '카드', '카드', 'kadeu', 'card', '卡', '카드로 계산해요.', 'I pay by card.', '我刷卡。'),
  ('ko-travel-basic-82', 'ko', 'basic', 'travel', '와이파이', '와이파이', 'waipai', 'Wi-Fi', 'Wi-Fi', '와이파이 있어요?', 'Is there Wi-Fi?', '有Wi-Fi吗？'),
  ('ko-travel-basic-83', 'ko', 'basic', 'travel', '충전기', '충전기', 'chungjeongi', 'charger', '充电器', '충전기를 가져가요.', 'I bring a charger.', '我带充电器。'),
  ('ko-travel-basic-84', 'ko', 'basic', 'travel', '콘센트', '콘센트', 'konsenteu', 'power outlet', '插座', '콘센트가 어디예요?', 'Where is the outlet?', '插座在哪？'),
  ('ko-travel-basic-85', 'ko', 'basic', 'travel', '날씨', '날씨', 'nalssi', 'weather', '天气', '날씨가 좋아요.', 'The weather is nice.', '天气很好。'),
  ('ko-travel-basic-86', 'ko', 'basic', 'travel', '우산', '우산', 'usan', 'umbrella', '伞', '우산을 가져가요.', 'I bring an umbrella.', '我带伞。'),
  ('ko-travel-basic-87', 'ko', 'basic', 'travel', '덥다', '덥다', 'deopda', 'hot (weather)', '热', '오늘 더워요.', 'It''s hot today.', '今天很热。'),
  ('ko-travel-basic-88', 'ko', 'basic', 'travel', '춥다', '춥다', 'chupda', 'cold (weather)', '冷', '오늘 추워요.', 'It''s cold today.', '今天很冷。'),
  ('ko-travel-basic-89', 'ko', 'basic', 'travel', '비', '비', 'bi', 'rain', '雨', '비가 와요.', 'It''s raining.', '下雨了。'),
  ('ko-travel-basic-90', 'ko', 'basic', 'travel', '눈', '눈', 'nun', 'snow', '雪', '눈이 와요.', 'It''s snowing.', '下雪了。'),
  ('ko-travel-basic-91', 'ko', 'basic', 'travel', '약국', '약국', 'yakguk', 'pharmacy', '药店', '약국이 어디예요?', 'Where is the pharmacy?', '药店在哪？'),
  ('ko-travel-basic-92', 'ko', 'basic', 'travel', '경찰서', '경찰서', 'gyeongchalseo', 'police station', '警察局', '경찰서에 가요.', 'I go to the police station.', '我去警察局。'),
  ('ko-travel-basic-93', 'ko', 'basic', 'travel', '대사관', '대사관', 'daesagwan', 'embassy', '大使馆', '대사관에 연락해요.', 'I contact the embassy.', '我联系大使馆。'),
  ('ko-travel-basic-94', 'ko', 'basic', 'travel', '은행', '은행', 'eunhaeng', 'bank', '银行', '은행에 가요.', 'I go to the bank.', '我去银行。'),
  ('ko-travel-basic-95', 'ko', 'basic', 'travel', '우체국', '우체국', 'ucheguk', 'post office', '邮局', '우체국에서 보내요.', 'I send it at the post office.', '我在邮局寄。'),
  ('ko-travel-basic-96', 'ko', 'basic', 'travel', '편의점', '편의점', 'pyeonuijeom', 'convenience store', '便利店', '편의점에 가요.', 'I go to a convenience store.', '我去便利店。'),
  ('ko-travel-basic-97', 'ko', 'basic', 'travel', '백화점', '백화점', 'baekhwajeom', 'department store', '百货商店', '백화점에서 쇼핑해요.', 'I shop at the department store.', '我在百货商店逛。'),
  ('ko-travel-basic-98', 'ko', 'basic', 'travel', '시내', '시내', 'sinae', 'downtown', '市区', '시내에 가요.', 'I go downtown.', '我去市区。'),
  ('ko-travel-basic-99', 'ko', 'basic', 'travel', '교외', '교외', 'gyooe', 'suburb', '郊区', '교외에 살아요.', 'I live in the suburbs.', '我住郊区。'),
  ('ko-travel-basic-100', 'ko', 'basic', 'travel', '번화가', '번화가', 'beonhwaga', 'busy street', '繁华街', '번화가에서 놀아요.', 'I hang out on the busy street.', '我在繁华街玩。'),
  ('ko-travel-basic-101', 'ko', 'basic', 'travel', '골목', '골목', 'golmok', 'alley', '胡同', '골목을 걸어요.', 'I walk through the alley.', '我走胡同。'),
  ('ko-travel-basic-102', 'ko', 'basic', 'travel', '사거리', '사거리', 'sageori', 'intersection', '十字路口', '사거리에서 좌회전해요.', 'I turn left at the intersection.', '我在十字路口左转。'),
  ('ko-travel-basic-103', 'ko', 'basic', 'travel', '도보', '도보', 'dobo', 'on foot', '步行', '도보로 가요.', 'I go on foot.', '我步行去。'),
  ('ko-travel-basic-104', 'ko', 'basic', 'travel', '렌터카', '렌터카', 'renteoka', 'rental car', '租车', '렌터카를 빌려요.', 'I rent a car.', '我租车。'),
  ('ko-travel-basic-105', 'ko', 'basic', 'travel', '고속도로', '고속도로', 'gosokdoro', 'highway', '高速公路', '고속도로를 타요.', 'I take the highway.', '我上高速公路。'),
  ('ko-travel-basic-106', 'ko', 'basic', 'travel', '톨게이트', '톨게이트', 'tolgeiteu', 'toll gate', '收费站', '톨게이트를 지나요.', 'I pass through the toll gate.', '我经过收费站。'),
  ('ko-travel-basic-107', 'ko', 'basic', 'travel', '휴게소', '휴게소', 'hyugeso', 'rest area', '服务区', '휴게소에서 쉬어요.', 'I rest at the rest area.', '我在服务区休息。'),
  ('ko-travel-basic-108', 'ko', 'basic', 'travel', '일정', '일정', 'iljeong', 'itinerary, schedule', '行程', '일정을 짜요.', 'I plan the itinerary.', '我安排行程。'),
  ('ko-travel-basic-109', 'ko', 'basic', 'travel', '투어', '투어', 'tueo', 'tour', '旅游团', '투어에 참가해요.', 'I join a tour.', '我参加旅游团。'),
  ('ko-travel-basic-110', 'ko', 'basic', 'travel', '가이드', '가이드', 'gaideu', 'guide', '导游', '가이드가 설명해요.', 'The guide explains.', '导游讲解。'),
  ('ko-travel-basic-111', 'ko', 'basic', 'travel', '입장료', '입장료', 'ipjangnyo', 'admission fee', '门票费', '입장료가 얼마예요?', 'How much is admission?', '门票多少钱？'),
  ('ko-travel-basic-112', 'ko', 'basic', 'travel', '개장', '개장', 'gaejang', 'opening (time)', '开门', '개장 시간이 언제예요?', 'When does it open?', '几点开门？'),
  ('ko-travel-basic-113', 'ko', 'basic', 'travel', '폐장', '폐장', 'pyejang', 'closing (time)', '关门', '폐장 시간이 언제예요?', 'When does it close?', '几点关门？'),
  ('ko-travel-basic-114', 'ko', 'basic', 'travel', '전망대', '전망대', 'jeonmangdae', 'observation deck', '观景台', '전망대에 올라가요.', 'I go up to the observation deck.', '我上观景台。'),
  ('ko-travel-basic-115', 'ko', 'basic', 'travel', '다음 역', '다음 역', 'daeum yeok', 'next station', '下一站', '다음 역에서 내려요.', 'I get off at the next station.', '我下一站下车。'),
  ('ko-travel-basic-116', 'ko', 'basic', 'travel', '종점', '종점', 'jongjeom', 'last stop', '终点站', '종점까지 가요.', 'I go to the last stop.', '我坐到终点站。'),
  ('ko-travel-basic-117', 'ko', 'basic', 'travel', '내리다', '내리다', 'naerida', 'to get off', '下车', '여기서 내려요.', 'I get off here.', '我在这下车。'),
  ('ko-travel-basic-118', 'ko', 'basic', 'travel', '타다', '타다', 'tada', 'to ride, get on', '坐，乘', '버스를 타요.', 'I get on the bus.', '我上车。'),
  ('ko-travel-basic-119', 'ko', 'basic', 'travel', '걷다', '걷다', 'geotda', 'to walk', '走路', '걸어서 가요.', 'I walk there.', '我走路去。'),
  ('ko-travel-basic-120', 'ko', 'basic', 'travel', '달리다', '달리다', 'dallida', 'to run', '跑', '달려서 가요.', 'I run there.', '我跑过去。'),
  ('ko-travel-basic-121', 'ko', 'basic', 'travel', '길을 잃다', '길을 잃다', 'gireul ilta', 'to get lost', '迷路', '길을 잃었어요.', 'I got lost.', '我迷路了。'),
  ('ko-travel-basic-122', 'ko', 'basic', 'travel', '길을 묻다', '길을 묻다', 'gireul mutda', 'to ask for directions', '问路', '길을 물어봐요.', 'I ask for directions.', '我问路。'),
  ('ko-travel-basic-123', 'ko', 'basic', 'travel', '가깝다', '가깝다', 'gakkapda', 'close, near', '近', '여기서 가까워요.', 'It''s close from here.', '离这很近。'),
  ('ko-travel-basic-124', 'ko', 'basic', 'travel', '멀다', '멀다', 'meolda', 'far', '远', '좀 멀어요.', 'It''s a bit far.', '有点远。'),
  ('ko-travel-basic-125', 'ko', 'basic', 'travel', '빠르다', '빠르다', 'ppareuda', 'fast', '快', '기차가 빨라요.', 'The train is fast.', '火车很快。'),
  ('ko-travel-basic-126', 'ko', 'basic', 'travel', '느리다', '느리다', 'neurida', 'slow', '慢', '버스가 느려요.', 'The bus is slow.', '公交很慢。'),
  ('ko-travel-basic-127', 'ko', 'basic', 'travel', '안전', '안전', 'anjeon', 'safety', '安全', '안전벨트를 매요.', 'I fasten the seatbelt.', '我系安全带。'),
  ('ko-travel-basic-128', 'ko', 'basic', 'travel', '위험', '위험', 'wiheom', 'danger', '危险', '위험해요!', 'It''s dangerous!', '危险！'),
  ('ko-travel-basic-129', 'ko', 'basic', 'travel', '조심', '조심', 'josim', 'caution, be careful', '小心', '조심하세요.', 'Be careful.', '请小心。'),
  ('ko-travel-basic-130', 'ko', 'basic', 'travel', '분실', '분실', 'bunsil', 'lost (item)', '丢失', '여권을 분실했어요.', 'I lost my passport.', '我丢了护照。'),
  ('ko-travel-basic-131', 'ko', 'basic', 'travel', '도움', '도움', 'doum', 'help', '帮助', '도움이 필요해요.', 'I need help.', '我需要帮助。'),
  ('ko-travel-basic-132', 'ko', 'basic', 'travel', '예매', '예매', 'yemae', 'advance booking', '预购', '표를 예매해요.', 'I book tickets in advance.', '我预购票。'),
  ('ko-travel-basic-133', 'ko', 'basic', 'travel', '취소', '취소', 'chwiso', 'cancellation', '取消', '예약을 취소해요.', 'I cancel the reservation.', '我取消预订。'),
  ('ko-travel-basic-134', 'ko', 'basic', 'travel', '연착', '연착', 'yeonchak', 'delay', '晚点', '비행기가 연착했어요.', 'The flight is delayed.', '飞机晚点了。'),
  ('ko-travel-basic-135', 'ko', 'basic', 'travel', '결항', '결항', 'gyeolhang', 'flight cancellation', '取消航班', '비행기가 결항됐어요.', 'The flight was cancelled.', '航班取消了。'),
  ('ko-travel-basic-136', 'ko', 'basic', 'travel', '보험', '보험', 'boheom', 'insurance', '保险', '여행 보험에 가입해요.', 'I get travel insurance.', '我买旅行保险。'),
  ('ko-travel-basic-137', 'ko', 'basic', 'travel', '짐을 싸다', '짐을 싸다', 'jimeul ssada', 'to pack luggage', '收拾行李', '짐을 싸요.', 'I pack my luggage.', '我收拾行李。'),
  ('ko-travel-basic-138', 'ko', 'basic', 'travel', '출국', '출국', 'chulguk', 'departure (from country)', '出境', '출국 수속을 해요.', 'I do departure procedures.', '我办出境手续。'),
  ('ko-travel-basic-139', 'ko', 'basic', 'travel', '입국', '입국', 'ipguk', 'entry (to country)', '入境', '입국 심사를 받아요.', 'I go through immigration.', '我过入境审查。'),
  ('ko-travel-basic-140', 'ko', 'basic', 'travel', '세관', '세관', 'segwan', 'customs', '海关', '세관을 통과해요.', 'I pass through customs.', '我过海关。'),
  ('ko-travel-basic-141', 'ko', 'basic', 'travel', '신고', '신고', 'singo', 'declaration', '申报', '신고할 것이 있어요.', 'I have something to declare.', '我有东西要申报。'),
  ('ko-travel-basic-142', 'ko', 'basic', 'travel', '게이트', '게이트', 'geiteu', 'gate', '登机口', '게이트가 몇 번이에요?', 'What gate number is it?', '几号登机口？'),
  ('ko-travel-basic-143', 'ko', 'basic', 'travel', '탑승권', '탑승권', 'tapseunggwon', 'boarding pass', '登机牌', '탑승권을 보여 주세요.', 'Please show your boarding pass.', '请出示登机牌。'),
  ('ko-travel-basic-144', 'ko', 'basic', 'travel', '기내', '기내', 'ginae', 'in-flight, on board', '机舱内', '기내 식사를 먹어요.', 'I eat the in-flight meal.', '我吃机舱餐。'),
  ('ko-travel-basic-145', 'ko', 'basic', 'travel', '면세', '면세', 'myeonse', 'duty-free', '免税', '면세 물건을 사요.', 'I buy duty-free items.', '我买免税物品。'),
  ('ko-travel-basic-146', 'ko', 'basic', 'travel', '짐 찾는 곳', '짐 찾는 곳', 'jim channeun got', 'baggage claim', '行李领取处', '짐 찾는 곳에 가요.', 'I go to baggage claim.', '我去行李领取处。'),
  ('ko-travel-basic-147', 'ko', 'basic', 'travel', '리무진', '리무진', 'rimujin', 'limousine bus', '机场大巴', '리무진을 타요.', 'I take the limousine bus.', '我坐机场大巴。'),
  ('ko-travel-basic-148', 'ko', 'basic', 'travel', '숙박', '숙박', 'sukbak', 'lodging', '住宿', '숙박비가 비싸요.', 'Lodging is expensive.', '住宿费很贵。'),
  ('ko-travel-basic-149', 'ko', 'basic', 'travel', '조식', '조식', 'josik', 'breakfast (hotel)', '早餐', '조식이 포함돼요.', 'Breakfast is included.', '含早餐。'),
  ('ko-travel-basic-150', 'ko', 'basic', 'travel', '프런트', '프런트', 'peureonteu', 'front desk', '前台', '프런트에서 물어봐요.', 'I ask at the front desk.', '我在前台问。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
