-- Expand ko-topik-advanced to 150 curated entries (76-150)
-- Topic: TOPIK 5/6 level vocabulary for advanced Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-topik-advanced-76', 'ko', 'advanced', 'TOPIK', '모순', '모순', 'mosun', 'contradiction, inconsistency', '矛盾，不一致', '그의 주장에는 명백한 모순이 있다.', 'There is an obvious contradiction in his argument.', '他的主张中存在明显的矛盾。'),
  ('ko-topik-advanced-77', 'ko', 'advanced', 'TOPIK', '취지', '취지', 'chwiji', 'purpose, intent', '宗旨，目的', '이 정책의 취지는 사회적 불평등을 줄이는 것이다.', 'The purpose of this policy is to reduce social inequality.', '这项政策的宗旨是减少社会不平等。'),
  ('ko-topik-advanced-78', 'ko', 'advanced', 'TOPIK', '함축', '함축', 'hamchuk', 'implication, connotation', '含蓄，暗示', '이 표현에는 깊은 함축적 의미가 담겨 있다.', 'This expression carries deep connotative meaning.', '这个表达蕴含着深层的含蓄意义。'),
  ('ko-topik-advanced-79', 'ko', 'advanced', 'TOPIK', '여파', '여파', 'yeopa', 'aftermath, repercussion', '余波，后果', '경제 위기의 여파가 아직도 남아 있다.', 'The aftermath of the economic crisis still remains.', '经济危机的余波至今仍然存在。'),
  ('ko-topik-advanced-80', 'ko', 'advanced', 'TOPIK', '파장', '파장', 'pajang', 'ripple effect, repercussion', '波澜，影响', '그 사건은 사회 전반에 큰 파장을 일으켰다.', 'The incident caused a big ripple effect across society.', '那起事件在社会各界引起了巨大波澜。'),
  ('ko-topik-advanced-81', 'ko', 'advanced', 'TOPIK', '귀결', '귀결', 'gwigyeol', 'conclusion, consequence', '归结，结果', '모든 논의는 하나의 결론으로 귀결되었다.', 'All discussions concluded with one result.', '所有讨论归结为一个结论。'),
  ('ko-topik-advanced-82', 'ko', 'advanced', 'TOPIK', '전제', '전제', 'jeonje', 'premise, precondition', '前提，先决条件', '민주주의는 시민의 참여를 전제로 한다.', 'Democracy is premised on citizen participation.', '民主主义以公民参与为前提。'),
  ('ko-topik-advanced-83', 'ko', 'advanced', 'TOPIK', '본질', '본질', 'bonjil', 'essence, nature', '本质，实质', '문제의 본질을 파악해야 한다.', 'We must grasp the essence of the problem.', '必须把握问题的本质。'),
  ('ko-topik-advanced-84', 'ko', 'advanced', 'TOPIK', '논거', '논거', 'nongeo', 'argument, grounds for argument', '论据，论点', '충분한 논거 없이 주장하면 설득력이 없다.', 'Arguing without sufficient grounds is not persuasive.', '没有充分论据的主张没有说服力。'),
  ('ko-topik-advanced-85', 'ko', 'advanced', 'TOPIK', '입증', '입증', 'ipjeung', 'proof, verification', '证实，证明', '그 이론은 실험을 통해 입증되었다.', 'The theory was verified through experiments.', '那个理论通过实验得到了证实。'),
  ('ko-topik-advanced-86', 'ko', 'advanced', 'TOPIK', '반박', '반박', 'banbak', 'refutation, rebuttal', '反驳，驳斥', '상대방의 주장을 논리적으로 반박했다.', 'He logically refuted the opponent''s argument.', '他以逻辑性地反驳了对方的主张。'),
  ('ko-topik-advanced-87', 'ko', 'advanced', 'TOPIK', '서술', '서술', 'seosul', 'narration, description', '叙述，描述', '사건의 경위를 객관적으로 서술하시오.', 'Describe the course of events objectively.', '请客观地叙述事件的经过。'),
  ('ko-topik-advanced-88', 'ko', 'advanced', 'TOPIK', '근거', '근거', 'geungeo', 'basis, evidence', '根据，依据', '과학적 근거에 기반한 정책이 필요하다.', 'Policies based on scientific evidence are needed.', '需要基于科学根据的政策。'),
  ('ko-topik-advanced-89', 'ko', 'advanced', 'TOPIK', '분석', '분석', 'bunseok', 'analysis, examination', '分析，解析', '데이터를 심층적으로 분석한 결과를 발표했다.', 'They announced the results of in-depth data analysis.', '他们发表了深入分析数据的结果。'),
  ('ko-topik-advanced-90', 'ko', 'advanced', 'TOPIK', '해석', '해석', 'haeseok', 'interpretation, analysis', '解释，解读', '같은 현상을 다르게 해석할 수 있다.', 'The same phenomenon can be interpreted differently.', '同一现象可以做出不同的解读。'),
  ('ko-topik-advanced-91', 'ko', 'advanced', 'TOPIK', '추론', '추론', 'churon', 'inference, reasoning', '推论，推理', '논리적 추론을 통해 결론에 도달했다.', 'A conclusion was reached through logical reasoning.', '通过逻辑推理得出了结论。'),
  ('ko-topik-advanced-92', 'ko', 'advanced', 'TOPIK', '시사하다', '시사하다', 'sisahada', 'to suggest, to imply', '启示，暗示', '이 연구 결과는 중요한 사실을 시사한다.', 'These research results suggest an important fact.', '这项研究结果暗示了重要的事实。'),
  ('ko-topik-advanced-93', 'ko', 'advanced', 'TOPIK', '간주하다', '간주하다', 'ganjuhada', 'to regard as, to consider', '视为，看作', '침묵은 동의로 간주됩니다.', 'Silence is regarded as consent.', '沉默被视为同意。'),
  ('ko-topik-advanced-94', 'ko', 'advanced', 'TOPIK', '수반하다', '수반하다', 'subanhada', 'to accompany, to entail', '伴随，随之而来', '경제 성장은 환경 문제를 수반한다.', 'Economic growth entails environmental problems.', '经济增长伴随着环境问题。'),
  ('ko-topik-advanced-95', 'ko', 'advanced', 'TOPIK', '초래하다', '초래하다', 'choraehada', 'to cause, to bring about', '招致，引起', '무분별한 개발이 생태계 파괴를 초래했다.', 'Reckless development caused ecosystem destruction.', '无序开发招致了生态系统破坏。'),
  ('ko-topik-advanced-96', 'ko', 'advanced', 'TOPIK', '야기하다', '야기하다', 'yagihada', 'to give rise to, to provoke', '引发，导致', '그 발언은 심각한 논란을 야기했다.', 'That remark gave rise to serious controversy.', '那番言论引发了严重的争论。'),
  ('ko-topik-advanced-97', 'ko', 'advanced', 'TOPIK', '여론', '여론', 'yeoron', 'public opinion, consensus', '舆论，民意', '여론 조사 결과가 발표되었다.', 'The results of the public opinion poll were announced.', '舆论调查结果已经发布。'),
  ('ko-topik-advanced-98', 'ko', 'advanced', 'TOPIK', '체제', '체제', 'cheje', 'system, regime', '体制，制度', '정치 체제의 변화가 불가피하다.', 'Changes in the political system are inevitable.', '政治体制的变化不可避免。'),
  ('ko-topik-advanced-99', 'ko', 'advanced', 'TOPIK', '제도', '제도', 'jedo', 'system, institution', '制度，体制', '새로운 교육 제도가 시행되었다.', 'A new education system was implemented.', '新的教育制度已经实施。'),
  ('ko-topik-advanced-100', 'ko', 'advanced', 'TOPIK', '정책', '정책', 'jeongchaek', 'policy, measure', '政策，方针', '정부의 경제 정책에 대한 비판이 거세다.', 'Criticism of the government''s economic policy is fierce.', '对政府经济政策的批评十分强烈。'),
  ('ko-topik-advanced-101', 'ko', 'advanced', 'TOPIK', '개혁', '개혁', 'gaehyeok', 'reform, reformation', '改革，革新', '사회 구조의 근본적인 개혁이 필요하다.', 'Fundamental reform of social structure is needed.', '需要对社会结构进行根本性改革。'),
  ('ko-topik-advanced-102', 'ko', 'advanced', 'TOPIK', '민주주의', '민주주의', 'minjujuui', 'democracy, democratic system', '民主主义，民主制度', '민주주의의 핵심은 국민의 주권이다.', 'The core of democracy is the sovereignty of the people.', '民主主义的核心是国民主权。'),
  ('ko-topik-advanced-103', 'ko', 'advanced', 'TOPIK', '인권', '인권', 'ingwon', 'human rights, civil rights', '人权，公民权利', '인권 보호는 모든 국가의 의무이다.', 'Protecting human rights is the duty of every nation.', '保护人权是所有国家的义务。'),
  ('ko-topik-advanced-104', 'ko', 'advanced', 'TOPIK', '인플레이션', '인플레이션', 'inpeullreisyeon', 'inflation, price increase', '通货膨胀，物价上涨', '인플레이션으로 인해 생활비가 급등했다.', 'Living costs surged due to inflation.', '由于通货膨胀，生活费急剧上涨。'),
  ('ko-topik-advanced-105', 'ko', 'advanced', 'TOPIK', '불황', '불황', 'bulhwang', 'recession, depression', '不景气，萧条', '장기 불황으로 실업률이 높아졌다.', 'The unemployment rate rose due to the prolonged recession.', '由于长期不景气，失业率升高了。'),
  ('ko-topik-advanced-106', 'ko', 'advanced', 'TOPIK', '수요', '수요', 'suyo', 'demand, need', '需求，需要', '소비자 수요가 공급을 초과하고 있다.', 'Consumer demand is exceeding supply.', '消费者需求正在超过供给。'),
  ('ko-topik-advanced-107', 'ko', 'advanced', 'TOPIK', '공급', '공급', 'gonggeum', 'supply, provision', '供给，供应', '원자재 공급이 불안정하다.', 'The supply of raw materials is unstable.', '原材料供应不稳定。'),
  ('ko-topik-advanced-108', 'ko', 'advanced', 'TOPIK', '투자', '투자', 'tuja', 'investment, capital allocation', '投资，资本配置', '장기적 관점에서 투자 전략을 수립해야 한다.', 'Investment strategies should be established from a long-term perspective.', '应该从长远角度制定投资战略。'),
  ('ko-topik-advanced-109', 'ko', 'advanced', 'TOPIK', '재정', '재정', 'jaejeong', 'finance, public finance', '财政，财务', '국가 재정이 악화되고 있다.', 'National finances are deteriorating.', '国家财政正在恶化。'),
  ('ko-topik-advanced-110', 'ko', 'advanced', 'TOPIK', '혁신', '혁신', 'hyeoksin', 'innovation, breakthrough', '革新，创新', '기술 혁신이 산업 구조를 바꾸고 있다.', 'Technological innovation is changing industrial structure.', '技术革新正在改变产业结构。'),
  ('ko-topik-advanced-111', 'ko', 'advanced', 'TOPIK', '인공지능', '인공지능', 'ingongjineung', 'artificial intelligence, AI', '人工智能，AI', '인공지능이 의료 분야에 혁명을 가져오고 있다.', 'Artificial intelligence is revolutionizing the medical field.', '人工智能正在给医疗领域带来革命。'),
  ('ko-topik-advanced-112', 'ko', 'advanced', 'TOPIK', '알고리즘', '알고리즘', 'algorijeum', 'algorithm, procedure', '算法，程序', '추천 알고리즘이 사용자 경험을 결정한다.', 'Recommendation algorithms determine user experience.', '推荐算法决定用户体验。'),
  ('ko-topik-advanced-113', 'ko', 'advanced', 'TOPIK', '데이터', '데이터', 'deiteo', 'data, information', '数据，资料', '빅데이터 분석이 의사결정에 활용된다.', 'Big data analysis is used in decision-making.', '大数据分析被用于决策。'),
  ('ko-topik-advanced-114', 'ko', 'advanced', 'TOPIK', '생태계', '생태계', 'saengtaegye', 'ecosystem, ecological system', '生态系统，生态圈', '도시 개발로 인해 생태계가 위협받고 있다.', 'Ecosystems are threatened due to urban development.', '由于城市开发，生态系统正受到威胁。'),
  ('ko-topik-advanced-115', 'ko', 'advanced', 'TOPIK', '은유', '은유', 'eunyu', 'metaphor, figurative expression', '隐喻，比喻', '문학에서 은유는 의미를 풍부하게 한다.', 'Metaphor enriches meaning in literature.', '文学中的隐喻使意义更加丰富。'),
  ('ko-topik-advanced-116', 'ko', 'advanced', 'TOPIK', '서정', '서정', 'seojeong', 'lyricism, lyrical sentiment', '抒情，诗意', '그 시는 깊은 서정적 아름다움을 지닌다.', 'That poem possesses deep lyrical beauty.', '那首诗具有深沉的抒情之美。'),
  ('ko-topik-advanced-117', 'ko', 'advanced', 'TOPIK', '풍자', '풍자', 'pungja', 'satire, irony', '讽刺，讥讽', '그 소설은 사회를 신랄하게 풍자한다.', 'That novel sharply satirizes society.', '那部小说辛辣地讽刺了社会。'),
  ('ko-topik-advanced-118', 'ko', 'advanced', 'TOPIK', '묘사', '묘사', 'myosa', 'depiction, description', '描写，描绘', '작가는 인물의 심리를 섬세하게 묘사했다.', 'The author delicately depicted the character''s psychology.', '作家细腻地描写了人物的心理。'),
  ('ko-topik-advanced-119', 'ko', 'advanced', 'TOPIK', '서사', '서사', 'seosa', 'narrative, epic', '叙事，叙事诗', '이 영화는 거대한 서사 구조를 가지고 있다.', 'This film has a grand narrative structure.', '这部电影具有宏大的叙事结构。'),
  ('ko-topik-advanced-120', 'ko', 'advanced', 'TOPIK', '비유', '비유', 'biyu', 'analogy, simile', '比喻，类比', '복잡한 개념을 비유를 통해 설명했다.', 'Complex concepts were explained through analogy.', '通过比喻说明了复杂的概念。'),
  ('ko-topik-advanced-121', 'ko', 'advanced', 'TOPIK', '존재론', '존재론', 'jonjaeron', 'ontology, theory of existence', '存在论，本体论', '존재론은 철학의 근본적인 분야이다.', 'Ontology is a fundamental field of philosophy.', '存在论是哲学的根本领域。'),
  ('ko-topik-advanced-122', 'ko', 'advanced', 'TOPIK', '인식론', '인식론', 'insikron', 'epistemology, theory of knowledge', '认识论，知识论', '인식론은 지식의 본질과 한계를 탐구한다.', 'Epistemology explores the nature and limits of knowledge.', '认识论探究知识的本质和局限。'),
  ('ko-topik-advanced-123', 'ko', 'advanced', 'TOPIK', '윤리', '윤리', 'yulli', 'ethics, morality', '伦理，道德', '과학 연구에서 윤리적 기준을 준수해야 한다.', 'Ethical standards must be observed in scientific research.', '在科学研究中必须遵守伦理标准。'),
  ('ko-topik-advanced-124', 'ko', 'advanced', 'TOPIK', '도덕', '도덕', 'dodeok', 'morality, moral principles', '道德，品德', '도덕적 판단은 시대에 따라 변할 수 있다.', 'Moral judgments can change with the times.', '道德判断可能随时代而变化。'),
  ('ko-topik-advanced-125', 'ko', 'advanced', 'TOPIK', '가치관', '가치관', 'gachigwan', 'values, worldview', '价值观，世界观', '세대 간 가치관의 차이가 갈등을 유발한다.', 'Differences in values between generations cause conflict.', '代际价值观差异引发冲突。'),
  ('ko-topik-advanced-126', 'ko', 'advanced', 'TOPIK', '패러다임', '패러다임', 'paereodaim', 'paradigm, framework', '范式，典范', '기존의 패러다임을 전환할 필요가 있다.', 'There is a need to shift the existing paradigm.', '有必要转换现有的范式。'),
  ('ko-topik-advanced-127', 'ko', 'advanced', 'TOPIK', '담론', '담론', 'damnon', 'discourse, discussion', '话语，论述', '사회적 담론이 정책 결정에 영향을 미친다.', 'Social discourse influences policy decisions.', '社会话语影响政策决定。'),
  ('ko-topik-advanced-128', 'ko', 'advanced', 'TOPIK', '맥락', '맥락', 'maengnak', 'context, connection', '脉络，语境', '발언의 맥락을 고려해야 정확히 이해할 수 있다.', 'You must consider the context to understand accurately.', '必须考虑发言的脉络才能准确理解。'),
  ('ko-topik-advanced-129', 'ko', 'advanced', 'TOPIK', '타당성', '타당성', 'tadangseong', 'validity, legitimacy', '妥当性，合理性', '이 주장의 타당성을 검증해 보겠다.', 'I will verify the validity of this argument.', '我将验证这一主张的妥当性。'),
  ('ko-topik-advanced-130', 'ko', 'advanced', 'TOPIK', '객관성', '객관성', 'gaekgwanseong', 'objectivity, impartiality', '客观性，公正性', '연구에서 객관성을 유지하는 것이 중요하다.', 'Maintaining objectivity in research is important.', '在研究中保持客观性很重要。'),
  ('ko-topik-advanced-131', 'ko', 'advanced', 'TOPIK', '주관적', '주관적', 'jugwanjeok', 'subjective, personal', '主观的，个人的', '예술에 대한 평가는 주관적일 수밖에 없다.', 'Evaluation of art is inevitably subjective.', '对艺术的评价不可避免地是主观的。'),
  ('ko-topik-advanced-132', 'ko', 'advanced', 'TOPIK', '보편적', '보편적', 'bopyeonjeok', 'universal, general', '普遍的，一般的', '인권은 보편적 가치로 인정받는다.', 'Human rights are recognized as a universal value.', '人权被认可为普遍价值。'),
  ('ko-topik-advanced-133', 'ko', 'advanced', 'TOPIK', '획일적', '획일적', 'hoegiljeok', 'uniform, standardized', '划一的，千篇一律的', '획일적인 교육 방식은 창의성을 저해한다.', 'Uniform educational methods hinder creativity.', '千篇一律的教育方式妨碍创造性。'),
  ('ko-topik-advanced-134', 'ko', 'advanced', 'TOPIK', '괴리', '괴리', 'goeri', 'discrepancy, gap', '隔阂，差距', '이상과 현실 사이에 괴리가 존재한다.', 'A discrepancy exists between ideals and reality.', '理想与现实之间存在隔阂。'),
  ('ko-topik-advanced-135', 'ko', 'advanced', 'TOPIK', '양극화', '양극화', 'yanggeukhwa', 'polarization, bifurcation', '两极化，分化', '소득 양극화가 심화되고 있다.', 'Income polarization is intensifying.', '收入两极化正在加深。'),
  ('ko-topik-advanced-136', 'ko', 'advanced', 'TOPIK', '지양하다', '지양하다', 'jiyanghada', 'to sublate, to overcome', '扬弃，克服', '단순한 이분법적 사고를 지양해야 한다.', 'We should overcome simplistic binary thinking.', '应该扬弃简单的二元思维。'),
  ('ko-topik-advanced-137', 'ko', 'advanced', 'TOPIK', '지향하다', '지향하다', 'jihyanghada', 'to aim for, to aspire to', '指向，追求', '우리 사회는 지속 가능한 발전을 지향한다.', 'Our society aspires to sustainable development.', '我们的社会追求可持续发展。'),
  ('ko-topik-advanced-138', 'ko', 'advanced', 'TOPIK', '도출하다', '도출하다', 'dochulhada', 'to derive, to draw out', '得出，推导出', '실험 결과로부터 결론을 도출했다.', 'A conclusion was derived from the experimental results.', '从实验结果中得出了结论。'),
  ('ko-topik-advanced-139', 'ko', 'advanced', 'TOPIK', '축적하다', '축적하다', 'chukjeokhada', 'to accumulate, to amass', '积累，积蓄', '오랜 기간 경험을 축적해 왔다.', 'Experience has been accumulated over a long period.', '长期以来一直在积累经验。'),
  ('ko-topik-advanced-140', 'ko', 'advanced', 'TOPIK', '부각되다', '부각되다', 'bugakdoeda', 'to be highlighted, to emerge', '凸显，突出', '환경 문제가 국제적으로 부각되고 있다.', 'Environmental issues are being highlighted internationally.', '环境问题在国际上日益凸显。'),
  ('ko-topik-advanced-141', 'ko', 'advanced', 'TOPIK', '대두되다', '대두되다', 'daedudoeda', 'to emerge, to rise', '出现，抬头', '새로운 사회 문제가 대두되고 있다.', 'New social problems are emerging.', '新的社会问题正在涌现。'),
  ('ko-topik-advanced-142', 'ko', 'advanced', 'TOPIK', '내재하다', '내재하다', 'naejaehada', 'to be inherent, to be latent', '内在，潜在', '모든 제도에는 한계가 내재한다.', 'Limitations are inherent in all systems.', '所有制度都内在着局限性。'),
  ('ko-topik-advanced-143', 'ko', 'advanced', 'TOPIK', '표방하다', '표방하다', 'pyobanghada', 'to profess, to advocate', '标榜，倡导', '그 단체는 평화를 표방하고 있다.', 'That organization professes peace.', '那个团体标榜和平。'),
  ('ko-topik-advanced-144', 'ko', 'advanced', 'TOPIK', '배태하다', '배태하다', 'baetaehada', 'to conceive, to incubate', '孕育，酝酿', '새로운 문화가 도시에서 배태되고 있다.', 'A new culture is being incubated in the city.', '新的文化正在城市中孕育。'),
  ('ko-topik-advanced-145', 'ko', 'advanced', 'TOPIK', '담지하다', '담지하다', 'damjihada', 'to embody, to carry', '承载，承担', '예술은 시대의 정신을 담지한다.', 'Art embodies the spirit of the era.', '艺术承载着时代的精神。'),
  ('ko-topik-advanced-146', 'ko', 'advanced', 'TOPIK', '상정하다', '상정하다', 'sangjeonghada', 'to assume, to presuppose', '假定，设想', '최악의 시나리오를 상정하고 대비해야 한다.', 'We must assume the worst scenario and prepare.', '必须假定最坏的情况并做好准备。'),
  ('ko-topik-advanced-147', 'ko', 'advanced', 'TOPIK', '견지하다', '견지하다', 'gyeonjihada', 'to maintain, to uphold', '坚持，维持', '중립적 입장을 견지해야 한다.', 'A neutral stance must be maintained.', '必须坚持中立立场。'),
  ('ko-topik-advanced-148', 'ko', 'advanced', 'TOPIK', '포괄하다', '포괄하다', 'pogwalhada', 'to encompass, to cover broadly', '涵盖，包括', '이 법안은 다양한 사회적 문제를 포괄한다.', 'This bill encompasses various social issues.', '这项法案涵盖了各种社会问题。'),
  ('ko-topik-advanced-149', 'ko', 'advanced', 'TOPIK', '상충하다', '상충하다', 'sangchunghada', 'to conflict, to clash', '相冲突，相矛盾', '개인의 이익과 공공의 이익이 상충할 수 있다.', 'Individual interests and public interests can conflict.', '个人利益和公共利益可能相冲突。'),
  ('ko-topik-advanced-150', 'ko', 'advanced', 'TOPIK', '귀속되다', '귀속되다', 'gwisokdoeda', 'to be attributed to, to belong to', '归属，属于', '그 성과는 팀 전체에 귀속된다.', 'That achievement is attributed to the entire team.', '那项成果归属于整个团队。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
