-- Expand ja-travel-intermediate to 150 curated entries (8-150)
-- Topic: travel/transportation vocabulary for intermediate Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-travel-intermediate-8', 'ja', 'intermediate', 'travel', '新幹線', 'しんかんせん', 'shinkansen', 'bullet train, Shinkansen', '新干线，高速列车', '新幹線で東京から大阪まで行きます。', 'I will go from Tokyo to Osaka by bullet train.', '我坐新干线从东京到大阪。'),
  ('ja-travel-intermediate-9', 'ja', 'intermediate', 'travel', '特急', 'とっきゅう', 'tokkyuu', 'limited express, special express', '特快，特急列车', '特急に乗れば早く着きます。', 'If you take the limited express, you will arrive quickly.', '坐特急的话会很快到达。'),
  ('ja-travel-intermediate-10', 'ja', 'intermediate', 'travel', '各駅停車', 'かくえきていしゃ', 'kakuekiteisha', 'local train, all-stops train', '各站停车，慢车', '各駅停車は時間がかかります。', 'The local train takes a long time.', '各站停车需要很长时间。'),
  ('ja-travel-intermediate-11', 'ja', 'intermediate', 'travel', '快速', 'かいそく', 'kaisoku', 'rapid train, express', '快速列车', '快速電車に乗り換えてください。', 'Please transfer to the rapid train.', '请换乘快速列车。'),
  ('ja-travel-intermediate-12', 'ja', 'intermediate', 'travel', '準急', 'じゅんきゅう', 'junkyuu', 'semi-express', '准急列车', '準急は次の駅に停まります。', 'The semi-express stops at the next station.', '准急在下一站停车。'),
  ('ja-travel-intermediate-13', 'ja', 'intermediate', 'travel', 'フェリー', 'フェリー', 'ferii', 'ferry', '渡轮，轮渡', 'フェリーで島に渡ります。', 'I will cross to the island by ferry.', '我坐渡轮去岛上。'),
  ('ja-travel-intermediate-14', 'ja', 'intermediate', 'travel', '路線', 'ろせん', 'rosen', 'route, train line', '路线，线路', 'この路線は混みやすいです。', 'This line tends to get crowded.', '这条线路容易拥挤。'),
  ('ja-travel-intermediate-15', 'ja', 'intermediate', 'travel', '終電', 'しゅうでん', 'shuuden', 'last train', '末班车', '終電に間に合いませんでした。', 'I didn''t make it to the last train.', '我没赶上末班车。'),
  ('ja-travel-intermediate-16', 'ja', 'intermediate', 'travel', '始発', 'しはつ', 'shihatsu', 'first train, first departure', '首班车，始发', '始発に乗って空港に行きます。', 'I will take the first train to the airport.', '我坐首班车去机场。'),
  ('ja-travel-intermediate-17', 'ja', 'intermediate', 'travel', '時刻表', 'じこくひょう', 'jikokuhyou', 'timetable, schedule', '时刻表', '時刻表を確認してください。', 'Please check the timetable.', '请确认时刻表。'),
  ('ja-travel-intermediate-18', 'ja', 'intermediate', 'travel', '運賃', 'うんちん', 'unchin', 'fare, transportation fee', '车费，运费', '運賃はいくらですか。', 'How much is the fare?', '车费是多少？'),
  ('ja-travel-intermediate-19', 'ja', 'intermediate', 'travel', '片道', 'かたみち', 'katamichi', 'one-way', '单程', '片道切符を一枚ください。', 'One one-way ticket, please.', '请给我一张单程票。'),
  ('ja-travel-intermediate-20', 'ja', 'intermediate', 'travel', '往復', 'おうふく', 'oufuku', 'round trip', '往返', '往復切符の方が安いです。', 'A round-trip ticket is cheaper.', '往返票更便宜。'),
  ('ja-travel-intermediate-21', 'ja', 'intermediate', 'travel', '定期券', 'ていきけん', 'teikiken', 'commuter pass', '月票，定期券', '定期券を更新しました。', 'I renewed my commuter pass.', '我更新了月票。'),
  ('ja-travel-intermediate-22', 'ja', 'intermediate', 'travel', '乗車券', 'じょうしゃけん', 'joushaken', 'boarding ticket, rail ticket', '乘车券', '乗車券を購入してください。', 'Please purchase a boarding ticket.', '请购买乘车券。'),
  ('ja-travel-intermediate-23', 'ja', 'intermediate', 'travel', '指定席', 'していせき', 'shiteiseki', 'reserved seat', '对号座，指定席', '指定席を予約しました。', 'I reserved a designated seat.', '我预订了对号座。'),
  ('ja-travel-intermediate-24', 'ja', 'intermediate', 'travel', '自由席', 'じゆうせき', 'jiyuuseki', 'non-reserved seat, free seating', '自由席', '自由席は混んでいます。', 'The non-reserved seats are crowded.', '自由席很拥挤。'),
  ('ja-travel-intermediate-25', 'ja', 'intermediate', 'travel', 'グリーン車', 'グリーンしゃ', 'guriinsha', 'first-class car, Green Car', '头等车厢，绿色车厢', 'グリーン車は静かで快適です。', 'The Green Car is quiet and comfortable.', '头等车厢安静又舒适。'),
  ('ja-travel-intermediate-26', 'ja', 'intermediate', 'travel', '改札口', 'かいさつぐち', 'kaisatsuguchi', 'ticket gate', '检票口', '改札口で待ち合わせましょう。', 'Let''s meet at the ticket gate.', '我们在检票口见面吧。'),
  ('ja-travel-intermediate-27', 'ja', 'intermediate', 'travel', 'ホーム', 'ホーム', 'hoomu', 'platform', '站台', '3番ホームに電車が来ます。', 'The train is coming to platform 3.', '列车将到达3号站台。'),
  ('ja-travel-intermediate-28', 'ja', 'intermediate', 'travel', '車掌', 'しゃしょう', 'shashou', 'conductor', '列车长，乘务员', '車掌に切符を見せました。', 'I showed my ticket to the conductor.', '我向列车长出示了车票。'),
  ('ja-travel-intermediate-29', 'ja', 'intermediate', 'travel', '遅延', 'ちえん', 'chien', 'delay', '延误，晚点', '電車が遅延しています。', 'The train is delayed.', '电车晚点了。'),
  ('ja-travel-intermediate-30', 'ja', 'intermediate', 'travel', '運休', 'うんきゅう', 'unkyuu', 'service suspension, cancellation', '停运', '台風で電車が運休になりました。', 'The train service was suspended due to the typhoon.', '因台风电车停运了。'),
  ('ja-travel-intermediate-31', 'ja', 'intermediate', 'travel', '振替輸送', 'ふりかえゆそう', 'furikaeyusou', 'alternative transport, rerouted service', '替代交通', '振替輸送を利用できます。', 'You can use the alternative transport service.', '可以利用替代交通。'),
  ('ja-travel-intermediate-32', 'ja', 'intermediate', 'travel', '搭乗口', 'とうじょうぐち', 'toujouguchi', 'boarding gate', '登机口', '搭乗口は25番です。', 'The boarding gate is number 25.', '登机口是25号。'),
  ('ja-travel-intermediate-33', 'ja', 'intermediate', 'travel', '入国審査', 'にゅうこくしんさ', 'nyuukokushinsa', 'immigration inspection', '入境检查', '入国審査に時間がかかりました。', 'Immigration inspection took a long time.', '入境检查花了很长时间。'),
  ('ja-travel-intermediate-34', 'ja', 'intermediate', 'travel', '出国審査', 'しゅっこくしんさ', 'shukkokushinsa', 'departure immigration', '出境检查', '出国審査を通りました。', 'I passed through departure immigration.', '我通过了出境检查。'),
  ('ja-travel-intermediate-35', 'ja', 'intermediate', 'travel', '免税店', 'めんぜいてん', 'menzeiten', 'duty-free shop', '免税店', '免税店でお土産を買いました。', 'I bought souvenirs at the duty-free shop.', '我在免税店买了纪念品。'),
  ('ja-travel-intermediate-36', 'ja', 'intermediate', 'travel', '手荷物', 'てにもつ', 'tenimotsu', 'hand luggage, carry-on', '手提行李', '手荷物は一つまでです。', 'You can bring one piece of carry-on.', '手提行李限一件。'),
  ('ja-travel-intermediate-37', 'ja', 'intermediate', 'travel', '預け荷物', 'あずけにもつ', 'azukenimotsu', 'checked baggage', '托运行李', '預け荷物の重量制限は23キロです。', 'The checked baggage weight limit is 23 kg.', '托运行李限重23公斤。'),
  ('ja-travel-intermediate-38', 'ja', 'intermediate', 'travel', '税関', 'ぜいかん', 'zeikan', 'customs', '海关', '税関で荷物を検査されました。', 'My luggage was inspected at customs.', '在海关被检查了行李。'),
  ('ja-travel-intermediate-39', 'ja', 'intermediate', 'travel', '申告', 'しんこく', 'shinkoku', 'declaration (customs)', '申报', '申告するものはありますか。', 'Do you have anything to declare?', '有需要申报的东西吗？'),
  ('ja-travel-intermediate-40', 'ja', 'intermediate', 'travel', '搭乗券', 'とうじょうけん', 'toujouken', 'boarding pass', '登机牌', '搭乗券を見せてください。', 'Please show your boarding pass.', '请出示登机牌。'),
  ('ja-travel-intermediate-41', 'ja', 'intermediate', 'travel', '機内持ち込み', 'きないもちこみ', 'kinaimochikomi', 'carry-on (airplane)', '随身携带物品', '機内持ち込みのサイズを確認してください。', 'Please check the carry-on size restrictions.', '请确认随身携带物品的尺寸。'),
  ('ja-travel-intermediate-42', 'ja', 'intermediate', 'travel', '乗り継ぎ', 'のりつぎ', 'noritsugi', 'transit, connecting flight', '转机，中转', '乗り継ぎ時間は2時間です。', 'The transit time is 2 hours.', '转机时间是2小时。'),
  ('ja-travel-intermediate-43', 'ja', 'intermediate', 'travel', '直行便', 'ちょっこうびん', 'chokkoubin', 'direct flight', '直飞航班', '直行便の方が楽です。', 'A direct flight is easier.', '直飞航班更轻松。'),
  ('ja-travel-intermediate-44', 'ja', 'intermediate', 'travel', '経由', 'けいゆ', 'keiyu', 'via, transit through', '经由，途经', 'シンガポール経由で行きます。', 'I will go via Singapore.', '我经由新加坡去。'),
  ('ja-travel-intermediate-45', 'ja', 'intermediate', 'travel', '国内線', 'こくないせん', 'kokunaisen', 'domestic flight', '国内航线', '国内線のターミナルはどこですか。', 'Where is the domestic terminal?', '国内航线的航站楼在哪里？'),
  ('ja-travel-intermediate-46', 'ja', 'intermediate', 'travel', '国際線', 'こくさいせん', 'kokusaisen', 'international flight', '国际航线', '国際線は第2ターミナルです。', 'International flights are at Terminal 2.', '国际航线在第2航站楼。'),
  ('ja-travel-intermediate-47', 'ja', 'intermediate', 'travel', 'チェックイン', 'チェックイン', 'chekkuin', 'check-in', '入住，办理登记', 'チェックインは3時からです。', 'Check-in is from 3 o''clock.', '入住时间从3点开始。'),
  ('ja-travel-intermediate-48', 'ja', 'intermediate', 'travel', 'チェックアウト', 'チェックアウト', 'chekkuauto', 'check-out', '退房', 'チェックアウトは11時までです。', 'Check-out is by 11 o''clock.', '退房时间在11点之前。'),
  ('ja-travel-intermediate-49', 'ja', 'intermediate', 'travel', 'フロント', 'フロント', 'furonto', 'front desk, reception', '前台，服务台', 'フロントに荷物を預けました。', 'I left my luggage at the front desk.', '我把行李寄存在了前台。'),
  ('ja-travel-intermediate-50', 'ja', 'intermediate', 'travel', '予約', 'よやく', 'yoyaku', 'reservation, booking', '预约，预订', 'ホテルの予約を取りました。', 'I made a hotel reservation.', '我预订了酒店。'),
  ('ja-travel-intermediate-51', 'ja', 'intermediate', 'travel', '空室', 'くうしつ', 'kuushitsu', 'vacant room, availability', '空房', '空室はありますか。', 'Do you have any vacant rooms?', '有空房吗？'),
  ('ja-travel-intermediate-52', 'ja', 'intermediate', 'travel', '満室', 'まんしつ', 'manshitsu', 'fully booked, no vacancy', '客满，没有空房', '今日は満室です。', 'We are fully booked today.', '今天客满了。'),
  ('ja-travel-intermediate-53', 'ja', 'intermediate', 'travel', 'シングル', 'シングル', 'shinguru', 'single room', '单人间', 'シングルの部屋をお願いします。', 'A single room, please.', '请给我一间单人间。'),
  ('ja-travel-intermediate-54', 'ja', 'intermediate', 'travel', 'ツイン', 'ツイン', 'tsuin', 'twin room', '双床房', 'ツインの部屋に変更できますか。', 'Can I change to a twin room?', '可以换成双床房吗？'),
  ('ja-travel-intermediate-55', 'ja', 'intermediate', 'travel', '朝食付き', 'ちょうしょくつき', 'choushokutsuki', 'breakfast included', '含早餐', '朝食付きのプランにしました。', 'I chose the plan with breakfast included.', '我选了含早餐的方案。'),
  ('ja-travel-intermediate-56', 'ja', 'intermediate', 'travel', '素泊まり', 'すどまり', 'sudomari', 'room only, without meals', '不含餐住宿', '素泊まりの方が安いです。', 'Room only is cheaper.', '不含餐住宿更便宜。'),
  ('ja-travel-intermediate-57', 'ja', 'intermediate', 'travel', '宿泊', 'しゅくはく', 'shukuhaku', 'accommodation, staying overnight', '住宿', '宿泊先を探しています。', 'I am looking for accommodation.', '我在找住宿的地方。'),
  ('ja-travel-intermediate-58', 'ja', 'intermediate', 'travel', '旅館', 'りょかん', 'ryokan', 'Japanese-style inn', '日式旅馆', '旅館に泊まりたいです。', 'I want to stay at a Japanese inn.', '我想住日式旅馆。'),
  ('ja-travel-intermediate-59', 'ja', 'intermediate', 'travel', '民宿', 'みんしゅく', 'minshuku', 'guesthouse, B&B', '民宿', '民宿は地元の料理が出ます。', 'The guesthouse serves local cuisine.', '民宿提供当地料理。'),
  ('ja-travel-intermediate-60', 'ja', 'intermediate', 'travel', '交差点', 'こうさてん', 'kousaten', 'intersection, crossroads', '十字路口，交叉路口', '次の交差点を右に曲がってください。', 'Please turn right at the next intersection.', '请在下一个十字路口右转。'),
  ('ja-travel-intermediate-61', 'ja', 'intermediate', 'travel', '信号', 'しんごう', 'shingou', 'traffic light, signal', '红绿灯，信号灯', '信号が青になったら渡ります。', 'I will cross when the light turns green.', '绿灯亮了就过马路。'),
  ('ja-travel-intermediate-62', 'ja', 'intermediate', 'travel', '案内所', 'あんないじょ', 'annaijo', 'information center', '问讯处，服务中心', '案内所で地図をもらいました。', 'I got a map at the information center.', '我在问讯处拿了地图。'),
  ('ja-travel-intermediate-63', 'ja', 'intermediate', 'travel', '横断歩道', 'おうだんほどう', 'oudanhodou', 'pedestrian crossing, crosswalk', '人行横道', '横断歩道を渡ってください。', 'Please use the pedestrian crossing.', '请走人行横道。'),
  ('ja-travel-intermediate-64', 'ja', 'intermediate', 'travel', '一方通行', 'いっぽうつうこう', 'ippoutsuukou', 'one-way street', '单行道', 'この道は一方通行です。', 'This road is one-way.', '这条路是单行道。'),
  ('ja-travel-intermediate-65', 'ja', 'intermediate', 'travel', '歩道', 'ほどう', 'hodou', 'sidewalk, pavement', '人行道', '歩道を歩いてください。', 'Please walk on the sidewalk.', '请走人行道。'),
  ('ja-travel-intermediate-66', 'ja', 'intermediate', 'travel', '地下道', 'ちかどう', 'chikadou', 'underground passage', '地下通道', '地下道を通ると近いです。', 'It''s closer through the underground passage.', '走地下通道更近。'),
  ('ja-travel-intermediate-67', 'ja', 'intermediate', 'travel', '陸橋', 'りっきょう', 'rikkyou', 'pedestrian overpass, footbridge', '过街天桥', '陸橋を渡って向こう側に行きます。', 'Cross the overpass to get to the other side.', '走过街天桥到对面去。'),
  ('ja-travel-intermediate-68', 'ja', 'intermediate', 'travel', '突き当たり', 'つきあたり', 'tsukiatari', 'dead end, end of the road', '尽头', '突き当たりを左に曲がってください。', 'Turn left at the end of the road.', '到尽头后请左转。'),
  ('ja-travel-intermediate-69', 'ja', 'intermediate', 'travel', '角', 'かど', 'kado', 'corner', '拐角', 'あの角を曲がると駅があります。', 'If you turn at that corner, there''s a station.', '在那个拐角转弯就有车站。'),
  ('ja-travel-intermediate-70', 'ja', 'intermediate', 'travel', '観光地', 'かんこうち', 'kankouchi', 'tourist spot, sightseeing area', '旅游景点', '有名な観光地を巡りました。', 'I visited famous tourist spots.', '我游览了著名的旅游景点。'),
  ('ja-travel-intermediate-71', 'ja', 'intermediate', 'travel', '名所', 'めいしょ', 'meisho', 'famous place, attraction', '名胜', '京都は名所が多いです。', 'Kyoto has many famous places.', '京都有很多名胜。'),
  ('ja-travel-intermediate-72', 'ja', 'intermediate', 'travel', '世界遺産', 'せかいいさん', 'sekaiisan', 'World Heritage site', '世界遗产', '世界遺産を見に行きました。', 'I went to see a World Heritage site.', '我去看了世界遗产。'),
  ('ja-travel-intermediate-73', 'ja', 'intermediate', 'travel', '国宝', 'こくほう', 'kokuhou', 'national treasure', '国宝', 'この寺には国宝があります。', 'This temple has a national treasure.', '这座寺庙里有国宝。'),
  ('ja-travel-intermediate-74', 'ja', 'intermediate', 'travel', '史跡', 'しせき', 'shiseki', 'historic site, ruins', '古迹，遗址', '史跡を巡るツアーに参加しました。', 'I joined a tour of historic sites.', '我参加了古迹巡游。'),
  ('ja-travel-intermediate-75', 'ja', 'intermediate', 'travel', '土産', 'みやげ', 'miyage', 'souvenir', '纪念品，特产', 'お土産を買いたいです。', 'I want to buy souvenirs.', '我想买纪念品。'),
  ('ja-travel-intermediate-76', 'ja', 'intermediate', 'travel', '名物', 'めいぶつ', 'meibutsu', 'local specialty, famous product', '特产，名产', 'この地方の名物を食べました。', 'I ate the local specialty.', '我吃了这个地方的特产。'),
  ('ja-travel-intermediate-77', 'ja', 'intermediate', 'travel', '温泉', 'おんせん', 'onsen', 'hot spring', '温泉', '温泉に入りたいです。', 'I want to go in a hot spring.', '我想泡温泉。'),
  ('ja-travel-intermediate-78', 'ja', 'intermediate', 'travel', '露天風呂', 'ろてんぶろ', 'rotenburo', 'open-air bath', '露天温泉', '露天風呂からの景色が最高でした。', 'The view from the open-air bath was amazing.', '露天温泉的景色太棒了。'),
  ('ja-travel-intermediate-79', 'ja', 'intermediate', 'travel', '旅程', 'りょてい', 'ryotei', 'itinerary, travel schedule', '行程，旅程', '旅程を立てましょう。', 'Let''s plan our itinerary.', '我们来制定行程吧。'),
  ('ja-travel-intermediate-80', 'ja', 'intermediate', 'travel', '日程', 'にってい', 'nittei', 'schedule, itinerary dates', '日程，日程安排', '日程を変更したいです。', 'I want to change the schedule.', '我想更改日程安排。'),
  ('ja-travel-intermediate-81', 'ja', 'intermediate', 'travel', 'パスポート', 'パスポート', 'pasupooto', 'passport', '护照', 'パスポートの有効期限を確認しました。', 'I checked the passport''s expiration date.', '我确认了护照的有效期。'),
  ('ja-travel-intermediate-82', 'ja', 'intermediate', 'travel', 'ビザ', 'ビザ', 'biza', 'visa', '签证', 'ビザの申請に行きました。', 'I went to apply for a visa.', '我去申请了签证。'),
  ('ja-travel-intermediate-83', 'ja', 'intermediate', 'travel', '海外旅行', 'かいがいりょこう', 'kaigairyokou', 'overseas travel', '海外旅行', '海外旅行の準備をしています。', 'I am preparing for overseas travel.', '我在准备海外旅行。'),
  ('ja-travel-intermediate-84', 'ja', 'intermediate', 'travel', '国内旅行', 'こくないりょこう', 'kokunairyokou', 'domestic travel', '国内旅行', '国内旅行も楽しいです。', 'Domestic travel is also fun.', '国内旅行也很有趣。'),
  ('ja-travel-intermediate-85', 'ja', 'intermediate', 'travel', '添乗員', 'てんじょういん', 'tenjouin', 'tour conductor, tour guide', '导游，随团领队', '添乗員が説明してくれました。', 'The tour guide explained it for us.', '导游为我们做了说明。'),
  ('ja-travel-intermediate-86', 'ja', 'intermediate', 'travel', '団体旅行', 'だんたいりょこう', 'dantairyokou', 'group tour', '团体旅行', '団体旅行に参加しました。', 'I joined a group tour.', '我参加了团体旅行。'),
  ('ja-travel-intermediate-87', 'ja', 'intermediate', 'travel', '個人旅行', 'こじんりょこう', 'kojinryokou', 'independent travel', '自由行，个人旅行', '個人旅行の方が自由です。', 'Independent travel is freer.', '自由行更自在。'),
  ('ja-travel-intermediate-88', 'ja', 'intermediate', 'travel', '大使館', 'たいしかん', 'taishikan', 'embassy', '大使馆', '大使館に連絡してください。', 'Please contact the embassy.', '请联系大使馆。'),
  ('ja-travel-intermediate-89', 'ja', 'intermediate', 'travel', '領事館', 'りょうじかん', 'ryoujikan', 'consulate', '领事馆', '領事館でパスポートを再発行しました。', 'I had my passport reissued at the consulate.', '我在领事馆补办了护照。'),
  ('ja-travel-intermediate-90', 'ja', 'intermediate', 'travel', '保険', 'ほけん', 'hoken', 'insurance', '保险', '旅行保険に入りましたか。', 'Did you get travel insurance?', '你买旅行保险了吗？'),
  ('ja-travel-intermediate-91', 'ja', 'intermediate', 'travel', '紛失', 'ふんしつ', 'funshitsu', 'loss, losing something', '丢失，遗失', 'パスポートを紛失しました。', 'I lost my passport.', '我弄丢了护照。'),
  ('ja-travel-intermediate-92', 'ja', 'intermediate', 'travel', '盗難', 'とうなん', 'tounan', 'theft', '被盗，失窃', '盗難届を出しました。', 'I filed a theft report.', '我报了失窃案。'),
  ('ja-travel-intermediate-93', 'ja', 'intermediate', 'travel', '届け出', 'とどけで', 'todokede', 'report, notification (to police)', '报案，申报', '警察に届け出ました。', 'I reported it to the police.', '我向警察报了案。'),
  ('ja-travel-intermediate-94', 'ja', 'intermediate', 'travel', '両替', 'りょうがえ', 'ryougae', 'currency exchange', '换钱，兑换', '空港で両替しました。', 'I exchanged money at the airport.', '我在机场换了钱。'),
  ('ja-travel-intermediate-95', 'ja', 'intermediate', 'travel', '為替レート', 'かわせレート', 'kawase reeto', 'exchange rate', '汇率', '今日の為替レートを調べました。', 'I checked today''s exchange rate.', '我查了今天的汇率。'),
  ('ja-travel-intermediate-96', 'ja', 'intermediate', 'travel', '現地通貨', 'げんちつうか', 'genchitsuuka', 'local currency', '当地货币', '現地通貨に両替してください。', 'Please exchange to local currency.', '请换成当地货币。'),
  ('ja-travel-intermediate-97', 'ja', 'intermediate', 'travel', 'レンタカー', 'レンタカー', 'rentakaa', 'rental car', '租车', 'レンタカーを借りました。', 'I rented a car.', '我租了车。'),
  ('ja-travel-intermediate-98', 'ja', 'intermediate', 'travel', '国際免許', 'こくさいめんきょ', 'kokusaimenkyo', 'international driver''s license', '国际驾照', '国際免許を取りました。', 'I got an international driver''s license.', '我拿到了国际驾照。'),
  ('ja-travel-intermediate-99', 'ja', 'intermediate', 'travel', '高速道路', 'こうそくどうろ', 'kousokudouro', 'expressway, highway', '高速公路', '高速道路で3時間かかります。', 'It takes 3 hours on the expressway.', '走高速公路需要3小时。'),
  ('ja-travel-intermediate-100', 'ja', 'intermediate', 'travel', '料金所', 'りょうきんじょ', 'ryoukinjo', 'toll booth', '收费站', '料金所で通行料を払います。', 'You pay the toll at the toll booth.', '在收费站缴纳通行费。'),
  ('ja-travel-intermediate-101', 'ja', 'intermediate', 'travel', 'サービスエリア', 'サービスエリア', 'saabisu eria', 'service area, rest stop', '服务区', 'サービスエリアで休憩しましょう。', 'Let''s rest at the service area.', '我们在服务区休息一下吧。'),
  ('ja-travel-intermediate-102', 'ja', 'intermediate', 'travel', '駐車場', 'ちゅうしゃじょう', 'chuushajou', 'parking lot', '停车场', '駐車場は満車です。', 'The parking lot is full.', '停车场满了。'),
  ('ja-travel-intermediate-103', 'ja', 'intermediate', 'travel', 'ナビ', 'ナビ', 'nabi', 'GPS navigation', '导航', 'ナビを設定してください。', 'Please set the GPS navigation.', '请设置导航。'),
  ('ja-travel-intermediate-104', 'ja', 'intermediate', 'travel', '渋滞', 'じゅうたい', 'juutai', 'traffic jam, congestion', '堵车，交通拥堵', '渋滞で遅れました。', 'I was late because of traffic.', '因为堵车迟到了。'),
  ('ja-travel-intermediate-105', 'ja', 'intermediate', 'travel', '迂回', 'うかい', 'ukai', 'detour', '绕路，迂回', '工事中なので迂回してください。', 'Please detour because of construction.', '因施工中请绕路。'),
  ('ja-travel-intermediate-106', 'ja', 'intermediate', 'travel', '空港バス', 'くうこうバス', 'kuukou basu', 'airport bus, shuttle bus', '机场大巴', '空港バスで市内に行きます。', 'I will go to the city by airport bus.', '我坐机场大巴去市区。'),
  ('ja-travel-intermediate-107', 'ja', 'intermediate', 'travel', 'タクシー乗り場', 'タクシーのりば', 'takushii noriba', 'taxi stand', '出租车乘车点', 'タクシー乗り場はあちらです。', 'The taxi stand is over there.', '出租车乘车点在那边。'),
  ('ja-travel-intermediate-108', 'ja', 'intermediate', 'travel', '配車', 'はいしゃ', 'haisha', 'dispatching a car, ride hailing', '派车，叫车', 'アプリで配車を頼みました。', 'I ordered a ride through the app.', '我用应用叫了车。'),
  ('ja-travel-intermediate-109', 'ja', 'intermediate', 'travel', '乗車', 'じょうしゃ', 'jousha', 'boarding, getting on', '上车，乘车', '乗車位置はここです。', 'The boarding position is here.', '上车位置在这里。'),
  ('ja-travel-intermediate-110', 'ja', 'intermediate', 'travel', '下車', 'げしゃ', 'gesha', 'alighting, getting off', '下车', '次の駅で下車します。', 'I will get off at the next station.', '我在下一站下车。'),
  ('ja-travel-intermediate-111', 'ja', 'intermediate', 'travel', '乗り過ごす', 'のりすごす', 'norisugosu', 'to ride past one''s stop', '坐过站', '寝てしまって乗り過ごしました。', 'I fell asleep and missed my stop.', '我睡着了坐过了站。'),
  ('ja-travel-intermediate-112', 'ja', 'intermediate', 'travel', '忘れ物', 'わすれもの', 'wasuremono', 'lost item, forgotten belonging', '遗忘物品', '電車に忘れ物をしました。', 'I left something on the train.', '我把东西忘在电车上了。'),
  ('ja-travel-intermediate-113', 'ja', 'intermediate', 'travel', '遺失物取扱所', 'いしつぶつとりあつかいじょ', 'ishitsubutsu toriatsukaijo', 'lost and found office', '失物招领处', '遺失物取扱所に行きました。', 'I went to the lost and found office.', '我去了失物招领处。'),
  ('ja-travel-intermediate-114', 'ja', 'intermediate', 'travel', '案内板', 'あんないばん', 'annaiban', 'information board, sign', '指示牌，信息板', '案内板を見て行き先を確認しました。', 'I checked the destination on the information board.', '我看了指示牌确认了目的地。'),
  ('ja-travel-intermediate-115', 'ja', 'intermediate', 'travel', '発車', 'はっしゃ', 'hassha', 'departure (vehicle)', '发车', '発車時刻に注意してください。', 'Please pay attention to the departure time.', '请注意发车时间。'),
  ('ja-travel-intermediate-116', 'ja', 'intermediate', 'travel', '停車', 'ていしゃ', 'teisha', 'stopping (vehicle)', '停车', 'この電車は次の駅に停車しません。', 'This train does not stop at the next station.', '这趟电车不在下一站停车。'),
  ('ja-travel-intermediate-117', 'ja', 'intermediate', 'travel', '車両', 'しゃりょう', 'sharyou', 'train car, vehicle', '车厢', '前の車両に移動してください。', 'Please move to the front car.', '请移到前面的车厢。'),
  ('ja-travel-intermediate-118', 'ja', 'intermediate', 'travel', '連絡通路', 'れんらくつうろ', 'renrakutsuuro', 'connecting passage', '联络通道', '連絡通路で隣のビルに行けます。', 'You can go to the next building through the connecting passage.', '通过联络通道可以去隔壁大楼。'),
  ('ja-travel-intermediate-119', 'ja', 'intermediate', 'travel', '乗り場', 'のりば', 'noriba', 'boarding area, platform', '乘车处', 'バスの乗り場はどこですか。', 'Where is the bus boarding area?', '公交车的乘车处在哪里？'),
  ('ja-travel-intermediate-120', 'ja', 'intermediate', 'travel', '降り口', 'おりぐち', 'origuchi', 'exit, place to get off', '下车口', '降り口は前方です。', 'The exit is at the front.', '下车口在前方。'),
  ('ja-travel-intermediate-121', 'ja', 'intermediate', 'travel', '手配', 'てはい', 'tehai', 'arrangement, booking', '安排，准备', '旅行の手配をお願いしました。', 'I asked them to make the travel arrangements.', '我拜托他们安排了旅行。'),
  ('ja-travel-intermediate-122', 'ja', 'intermediate', 'travel', '手続き', 'てつづき', 'tetsuzuki', 'procedure, formalities', '手续，办理', '出国の手続きを済ませました。', 'I completed the departure procedures.', '我办好了出境手续。'),
  ('ja-travel-intermediate-123', 'ja', 'intermediate', 'travel', '観光案内', 'かんこうあんない', 'kankouannai', 'tourist information', '旅游咨询', '観光案内でパンフレットをもらいました。', 'I got a pamphlet at the tourist information.', '我在旅游咨询处拿了宣传册。'),
  ('ja-travel-intermediate-124', 'ja', 'intermediate', 'travel', '展望台', 'てんぼうだい', 'tenboudai', 'observation deck, lookout', '展望台，观景台', '展望台からの景色がきれいでした。', 'The view from the observation deck was beautiful.', '从展望台看的景色很漂亮。'),
  ('ja-travel-intermediate-125', 'ja', 'intermediate', 'travel', '遊覧船', 'ゆうらんせん', 'yuuransen', 'sightseeing boat, cruise boat', '观光船', '遊覧船に乗りました。', 'I rode the sightseeing boat.', '我坐了观光船。'),
  ('ja-travel-intermediate-126', 'ja', 'intermediate', 'travel', 'ロープウェイ', 'ロープウェイ', 'roopuwei', 'ropeway, cable car', '索道，缆车', 'ロープウェイで山頂に行きます。', 'I will go to the summit by ropeway.', '我坐缆车去山顶。'),
  ('ja-travel-intermediate-127', 'ja', 'intermediate', 'travel', '周遊', 'しゅうゆう', 'shuuyuu', 'tour, round trip sightseeing', '周游，环游', '周遊パスを買いました。', 'I bought a tour pass.', '我买了周游券。'),
  ('ja-travel-intermediate-128', 'ja', 'intermediate', 'travel', '日帰り', 'ひがえり', 'higaeri', 'day trip', '当天往返', '日帰りで温泉に行きました。', 'I went to a hot spring on a day trip.', '我当天往返去了温泉。'),
  ('ja-travel-intermediate-129', 'ja', 'intermediate', 'travel', '滞在', 'たいざい', 'taizai', 'stay, sojourn', '逗留，停留', '3日間滞在する予定です。', 'I plan to stay for 3 days.', '我打算逗留3天。'),
  ('ja-travel-intermediate-130', 'ja', 'intermediate', 'travel', '延泊', 'えんぱく', 'enpaku', 'extending one''s stay', '续住，延长住宿', '一泊延泊できますか。', 'Can I extend my stay by one night?', '可以续住一晚吗？'),
  ('ja-travel-intermediate-131', 'ja', 'intermediate', 'travel', '荷造り', 'にづくり', 'nizukuri', 'packing (luggage)', '打包行李', '荷造りを始めました。', 'I started packing.', '我开始打包行李了。'),
  ('ja-travel-intermediate-132', 'ja', 'intermediate', 'travel', 'スーツケース', 'スーツケース', 'suutsukeesu', 'suitcase', '行李箱', 'スーツケースが重すぎます。', 'The suitcase is too heavy.', '行李箱太重了。'),
  ('ja-travel-intermediate-133', 'ja', 'intermediate', 'travel', 'コインロッカー', 'コインロッカー', 'koin rokkaa', 'coin locker', '投币式储物柜', 'コインロッカーに荷物を入れました。', 'I put my luggage in a coin locker.', '我把行李放进了投币式储物柜。'),
  ('ja-travel-intermediate-134', 'ja', 'intermediate', 'travel', '宅配便', 'たくはいびん', 'takuhaibin', 'delivery service, parcel service', '快递，宅急便', '宅配便でホテルに荷物を送りました。', 'I sent my luggage to the hotel by delivery service.', '我用快递把行李寄到了酒店。'),
  ('ja-travel-intermediate-135', 'ja', 'intermediate', 'travel', '通訳', 'つうやく', 'tsuuyaku', 'interpreter, interpretation', '翻译，口译', '通訳をお願いできますか。', 'Can I request an interpreter?', '可以帮我找翻译吗？'),
  ('ja-travel-intermediate-136', 'ja', 'intermediate', 'travel', '外貨', 'がいか', 'gaika', 'foreign currency', '外币', '外貨を持っていますか。', 'Do you have foreign currency?', '你有外币吗？'),
  ('ja-travel-intermediate-137', 'ja', 'intermediate', 'travel', '出発ロビー', 'しゅっぱつロビー', 'shuppatsu robii', 'departure lobby', '出发大厅', '出発ロビーで集合してください。', 'Please gather at the departure lobby.', '请在出发大厅集合。'),
  ('ja-travel-intermediate-138', 'ja', 'intermediate', 'travel', '到着ロビー', 'とうちゃくロビー', 'touchaku robii', 'arrival lobby', '到达大厅', '到着ロビーで迎えを待ちます。', 'I will wait for the pickup at the arrival lobby.', '我在到达大厅等人来接。'),
  ('ja-travel-intermediate-139', 'ja', 'intermediate', 'travel', '欠航', 'けっこう', 'kekkou', 'flight cancellation', '航班取消', '悪天候で欠航になりました。', 'The flight was cancelled due to bad weather.', '因恶劣天气航班取消了。'),
  ('ja-travel-intermediate-140', 'ja', 'intermediate', 'travel', '遅延証明', 'ちえんしょうめい', 'chienshoumei', 'delay certificate', '延误证明', '遅延証明をもらいました。', 'I received a delay certificate.', '我拿到了延误证明。'),
  ('ja-travel-intermediate-141', 'ja', 'intermediate', 'travel', '乗車拒否', 'じょうしゃきょひ', 'joushakyohi', 'refusal to board, denial of ride', '拒载', '乗車拒否は違法です。', 'Refusal to board is illegal.', '拒载是违法的。'),
  ('ja-travel-intermediate-142', 'ja', 'intermediate', 'travel', '相乗り', 'あいのり', 'ainori', 'ride-sharing, carpooling', '拼车', '相乗りタクシーを利用しました。', 'I used a shared taxi.', '我用了拼车出租。'),
  ('ja-travel-intermediate-143', 'ja', 'intermediate', 'travel', '回数券', 'かいすうけん', 'kaisuuken', 'book of tickets, coupon tickets', '回数券', '回数券を買うとお得です。', 'Buying a book of tickets is a good deal.', '买回数券更划算。'),
  ('ja-travel-intermediate-144', 'ja', 'intermediate', 'travel', '精算', 'せいさん', 'seisan', 'fare adjustment', '补票，精算', '精算機で差額を払いました。', 'I paid the difference at the fare adjustment machine.', '我在精算机上补了差额。'),
  ('ja-travel-intermediate-145', 'ja', 'intermediate', 'travel', '途中下車', 'とちゅうげしゃ', 'tochuugesha', 'stopover, getting off midway', '中途下车', '途中下車して観光しました。', 'I got off midway and did some sightseeing.', '我中途下车观了光。'),
  ('ja-travel-intermediate-146', 'ja', 'intermediate', 'travel', '混雑', 'こんざつ', 'konzatsu', 'congestion, crowding', '拥挤，混杂', '朝の電車は混雑しています。', 'Morning trains are crowded.', '早上的电车很拥挤。'),
  ('ja-travel-intermediate-147', 'ja', 'intermediate', 'travel', '時差', 'じさ', 'jisa', 'time difference, jet lag', '时差', '時差ボケがひどいです。', 'My jet lag is terrible.', '时差反应很严重。'),
  ('ja-travel-intermediate-148', 'ja', 'intermediate', 'travel', '入場料', 'にゅうじょうりょう', 'nyuujouryou', 'admission fee, entrance fee', '门票，入场费', '入場料は大人800円です。', 'The admission fee is 800 yen for adults.', '成人入场费是800日元。'),
  ('ja-travel-intermediate-149', 'ja', 'intermediate', 'travel', '船着き場', 'ふなつきば', 'funatsukiba', 'pier, dock, wharf', '码头', '船着き場で船を待ちます。', 'I will wait for the boat at the pier.', '我在码头等船。'),
  ('ja-travel-intermediate-150', 'ja', 'intermediate', 'travel', '帰国', 'きこく', 'kikoku', 'returning to one''s country', '回国', '来週帰国する予定です。', 'I plan to return to my country next week.', '我计划下周回国。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
