-- Expand ko-life-basic to 150 curated entries (16-150)
-- Topic: daily life vocabulary for basic Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-life-basic-16', 'ko', 'basic', 'daily life', '학교', '학교', 'hakgyo', 'school', '学校', '학교에 가요.', 'I go to school.', '我去学校。'),
  ('ko-life-basic-17', 'ko', 'basic', 'daily life', '회사', '회사', 'hoesa', 'company', '公司', '회사에 가요.', 'I go to work.', '我去公司。'),
  ('ko-life-basic-18', 'ko', 'basic', 'daily life', '병원', '병원', 'byeongwon', 'hospital', '医院', '병원에 가요.', 'I go to the hospital.', '我去医院。'),
  ('ko-life-basic-19', 'ko', 'basic', 'daily life', '약', '약', 'yak', 'medicine', '药', '약을 먹어요.', 'I take medicine.', '我吃药。'),
  ('ko-life-basic-20', 'ko', 'basic', 'daily life', '몸', '몸', 'mom', 'body', '身体', '몸이 아파요.', 'My body hurts.', '身体不舒服。'),
  ('ko-life-basic-21', 'ko', 'basic', 'daily life', '머리', '머리', 'meori', 'head, hair', '头，头发', '머리가 아파요.', 'I have a headache.', '我头疼。'),
  ('ko-life-basic-22', 'ko', 'basic', 'daily life', '눈', '눈', 'nun', 'eye', '眼睛', '눈이 아파요.', 'My eyes hurt.', '眼睛疼。'),
  ('ko-life-basic-23', 'ko', 'basic', 'daily life', '코', '코', 'ko', 'nose', '鼻子', '코가 막혔어요.', 'My nose is blocked.', '鼻子堵了。'),
  ('ko-life-basic-24', 'ko', 'basic', 'daily life', '입', '입', 'ip', 'mouth', '嘴', '입을 다물어요.', 'I close my mouth.', '我闭嘴。'),
  ('ko-life-basic-25', 'ko', 'basic', 'daily life', '귀', '귀', 'gwi', 'ear', '耳朵', '귀가 아파요.', 'My ear hurts.', '耳朵疼。'),
  ('ko-life-basic-26', 'ko', 'basic', 'daily life', '손', '손', 'son', 'hand', '手', '손을 씻어요.', 'I wash my hands.', '我洗手。'),
  ('ko-life-basic-27', 'ko', 'basic', 'daily life', '발', '발', 'bal', 'foot', '脚', '발이 아파요.', 'My feet hurt.', '脚疼。'),
  ('ko-life-basic-28', 'ko', 'basic', 'daily life', '배', '배', 'bae', 'stomach', '肚子', '배가 아파요.', 'My stomach hurts.', '我肚子疼。'),
  ('ko-life-basic-29', 'ko', 'basic', 'daily life', '이', '이', 'i', 'tooth', '牙齿', '이를 닦아요.', 'I brush my teeth.', '我刷牙。'),
  ('ko-life-basic-30', 'ko', 'basic', 'daily life', '얼굴', '얼굴', 'eolgul', 'face', '脸', '얼굴을 씻어요.', 'I wash my face.', '我洗脸。'),
  ('ko-life-basic-31', 'ko', 'basic', 'daily life', '샤워', '샤워', 'syawo', 'shower', '淋浴', '샤워해요.', 'I take a shower.', '我洗淋浴。'),
  ('ko-life-basic-32', 'ko', 'basic', 'daily life', '목욕', '목욕', 'mogyok', 'bath', '洗澡', '목욕해요.', 'I take a bath.', '我洗澡。'),
  ('ko-life-basic-33', 'ko', 'basic', 'daily life', '세수', '세수', 'sesu', 'face washing', '洗脸', '세수해요.', 'I wash my face.', '我洗脸。'),
  ('ko-life-basic-34', 'ko', 'basic', 'daily life', '화장', '화장', 'hwajang', 'makeup', '化妆', '화장해요.', 'I put on makeup.', '我化妆。'),
  ('ko-life-basic-35', 'ko', 'basic', 'daily life', '머리를 감다', '머리를 감다', 'meorireul gamda', 'to wash hair', '洗头', '머리를 감아요.', 'I wash my hair.', '我洗头。'),
  ('ko-life-basic-36', 'ko', 'basic', 'daily life', '아버지', '아버지', 'abeoji', 'father', '爸爸', '아버지가 좋아요.', 'I love my father.', '我喜欢爸爸。'),
  ('ko-life-basic-37', 'ko', 'basic', 'daily life', '어머니', '어머니', 'eomeoni', 'mother', '妈妈', '어머니가 요리해요.', 'My mother cooks.', '妈妈做饭。'),
  ('ko-life-basic-38', 'ko', 'basic', 'daily life', '형', '형', 'hyeong', 'older brother (male)', '哥哥（男称）', '형이 있어요.', 'I have an older brother.', '我有哥哥。'),
  ('ko-life-basic-39', 'ko', 'basic', 'daily life', '누나', '누나', 'nuna', 'older sister (male)', '姐姐（男称）', '누나가 있어요.', 'I have an older sister.', '我有姐姐。'),
  ('ko-life-basic-40', 'ko', 'basic', 'daily life', '오빠', '오빠', 'oppa', 'older brother (female)', '哥哥（女称）', '오빠가 있어요.', 'I have an older brother.', '我有哥哥。'),
  ('ko-life-basic-41', 'ko', 'basic', 'daily life', '언니', '언니', 'eonni', 'older sister (female)', '姐姐（女称）', '언니가 있어요.', 'I have an older sister.', '我有姐姐。'),
  ('ko-life-basic-42', 'ko', 'basic', 'daily life', '동생', '동생', 'dongsaeng', 'younger sibling', '弟弟/妹妹', '동생이 있어요.', 'I have a younger sibling.', '我有弟弟/妹妹。'),
  ('ko-life-basic-43', 'ko', 'basic', 'daily life', '할머니', '할머니', 'halmeoni', 'grandmother', '奶奶', '할머니 댁에 가요.', 'I go to grandma''s house.', '我去奶奶家。'),
  ('ko-life-basic-44', 'ko', 'basic', 'daily life', '할아버지', '할아버지', 'harabeoji', 'grandfather', '爷爷', '할아버지가 건강해요.', 'Grandfather is healthy.', '爷爷很健康。'),
  ('ko-life-basic-45', 'ko', 'basic', 'daily life', '남편', '남편', 'nampyeon', 'husband', '丈夫', '남편이 일해요.', 'My husband works.', '丈夫在工作。'),
  ('ko-life-basic-46', 'ko', 'basic', 'daily life', '아내', '아내', 'anae', 'wife', '妻子', '아내가 예뻐요.', 'My wife is pretty.', '妻子很漂亮。'),
  ('ko-life-basic-47', 'ko', 'basic', 'daily life', '아이', '아이', 'ai', 'child', '孩子', '아이가 놀아요.', 'The child plays.', '孩子在玩。'),
  ('ko-life-basic-48', 'ko', 'basic', 'daily life', '아기', '아기', 'agi', 'baby', '婴儿', '아기가 자요.', 'The baby is sleeping.', '婴儿在睡。'),
  ('ko-life-basic-49', 'ko', 'basic', 'daily life', '강아지', '강아지', 'gangaji', 'puppy, dog', '小狗', '강아지가 귀여워요.', 'The puppy is cute.', '小狗很可爱。'),
  ('ko-life-basic-50', 'ko', 'basic', 'daily life', '고양이', '고양이', 'goyangi', 'cat', '猫', '고양이를 키워요.', 'I raise a cat.', '我养猫。'),
  ('ko-life-basic-51', 'ko', 'basic', 'daily life', '집', '집', 'jip', 'house, home', '家', '집에 가요.', 'I go home.', '我回家。'),
  ('ko-life-basic-52', 'ko', 'basic', 'daily life', '아파트', '아파트', 'apateu', 'apartment', '公寓', '아파트에 살아요.', 'I live in an apartment.', '我住公寓。'),
  ('ko-life-basic-53', 'ko', 'basic', 'daily life', '거실', '거실', 'geosil', 'living room', '客厅', '거실에서 쉬어요.', 'I relax in the living room.', '我在客厅休息。'),
  ('ko-life-basic-54', 'ko', 'basic', 'daily life', '부엌', '부엌', 'bueok', 'kitchen', '厨房', '부엌에서 요리해요.', 'I cook in the kitchen.', '我在厨房做饭。'),
  ('ko-life-basic-55', 'ko', 'basic', 'daily life', '침실', '침실', 'chimsil', 'bedroom', '卧室', '침실에서 자요.', 'I sleep in the bedroom.', '我在卧室睡觉。'),
  ('ko-life-basic-56', 'ko', 'basic', 'daily life', '화장실', '화장실', 'hwajangsil', 'bathroom', '卫生间', '화장실에 가요.', 'I go to the bathroom.', '我去卫生间。'),
  ('ko-life-basic-57', 'ko', 'basic', 'daily life', '문', '문', 'mun', 'door', '门', '문을 열어요.', 'I open the door.', '我开门。'),
  ('ko-life-basic-58', 'ko', 'basic', 'daily life', '창문', '창문', 'changmun', 'window', '窗户', '창문을 열어요.', 'I open the window.', '我开窗户。'),
  ('ko-life-basic-59', 'ko', 'basic', 'daily life', '의자', '의자', 'uija', 'chair', '椅子', '의자에 앉아요.', 'I sit on the chair.', '我坐椅子。'),
  ('ko-life-basic-60', 'ko', 'basic', 'daily life', '책상', '책상', 'chaeksang', 'desk', '桌子', '책상에서 공부해요.', 'I study at the desk.', '我在桌子上学习。'),
  ('ko-life-basic-61', 'ko', 'basic', 'daily life', '침대', '침대', 'chimdae', 'bed', '床', '침대에 누워요.', 'I lie on the bed.', '我躺在床上。'),
  ('ko-life-basic-62', 'ko', 'basic', 'daily life', '소파', '소파', 'sopa', 'sofa', '沙发', '소파에 앉아요.', 'I sit on the sofa.', '我坐沙发。'),
  ('ko-life-basic-63', 'ko', 'basic', 'daily life', '텔레비전', '텔레비전', 'tellebijeon', 'television', '电视', '텔레비전을 봐요.', 'I watch television.', '我看电视。'),
  ('ko-life-basic-64', 'ko', 'basic', 'daily life', '컴퓨터', '컴퓨터', 'keompyuteo', 'computer', '电脑', '컴퓨터를 써요.', 'I use the computer.', '我用电脑。'),
  ('ko-life-basic-65', 'ko', 'basic', 'daily life', '핸드폰', '핸드폰', 'haendeupon', 'cell phone', '手机', '핸드폰을 봐요.', 'I look at my phone.', '我看手机。'),
  ('ko-life-basic-66', 'ko', 'basic', 'daily life', '시계', '시계', 'sigye', 'clock, watch', '钟表', '시계를 봐요.', 'I check the clock.', '我看时间。'),
  ('ko-life-basic-67', 'ko', 'basic', 'daily life', '에어컨', '에어컨', 'eeokon', 'air conditioner', '空调', '에어컨을 켜요.', 'I turn on the AC.', '我开空调。'),
  ('ko-life-basic-68', 'ko', 'basic', 'daily life', '히터', '히터', 'hiteo', 'heater', '暖气', '히터를 켜요.', 'I turn on the heater.', '我开暖气。'),
  ('ko-life-basic-69', 'ko', 'basic', 'daily life', '전등', '전등', 'jeondeung', 'light', '灯', '전등을 켜요.', 'I turn on the light.', '我开灯。'),
  ('ko-life-basic-70', 'ko', 'basic', 'daily life', '세탁기', '세탁기', 'setakgi', 'washing machine', '洗衣机', '세탁기를 돌려요.', 'I run the washing machine.', '我开洗衣机。'),
  ('ko-life-basic-71', 'ko', 'basic', 'daily life', '청소기', '청소기', 'cheongsogi', 'vacuum cleaner', '吸尘器', '청소기를 돌려요.', 'I vacuum.', '我用吸尘器。'),
  ('ko-life-basic-72', 'ko', 'basic', 'daily life', '쓰레기', '쓰레기', 'sseuregi', 'trash, garbage', '垃圾', '쓰레기를 버려요.', 'I throw away trash.', '我扔垃圾。'),
  ('ko-life-basic-73', 'ko', 'basic', 'daily life', '분리수거', '분리수거', 'bunrisugo', 'recycling', '垃圾分类', '분리수거해요.', 'I do recycling.', '我做垃圾分类。'),
  ('ko-life-basic-74', 'ko', 'basic', 'daily life', '빨래', '빨래', 'ppallae', 'laundry', '洗衣服', '빨래를 해요.', 'I do laundry.', '我洗衣服。'),
  ('ko-life-basic-75', 'ko', 'basic', 'daily life', '청소', '청소', 'cheongso', 'cleaning', '打扫', '청소를 해요.', 'I clean.', '我打扫。'),
  ('ko-life-basic-76', 'ko', 'basic', 'daily life', '설거지', '설거지', 'seolgeoji', 'dishwashing', '洗碗', '설거지를 해요.', 'I wash the dishes.', '我洗碗。'),
  ('ko-life-basic-77', 'ko', 'basic', 'daily life', '요일', '요일', 'yoil', 'day of week', '星期', '오늘 무슨 요일이에요?', 'What day is today?', '今天星期几？'),
  ('ko-life-basic-78', 'ko', 'basic', 'daily life', '월요일', '월요일', 'woryoil', 'Monday', '星期一', '월요일에 일해요.', 'I work on Monday.', '我星期一工作。'),
  ('ko-life-basic-79', 'ko', 'basic', 'daily life', '주말', '주말', 'jumal', 'weekend', '周末', '주말에 쉬어요.', 'I rest on weekends.', '我周末休息。'),
  ('ko-life-basic-80', 'ko', 'basic', 'daily life', '오늘', '오늘', 'oneul', 'today', '今天', '오늘 바빠요.', 'I''m busy today.', '我今天很忙。'),
  ('ko-life-basic-81', 'ko', 'basic', 'daily life', '내일', '내일', 'naeil', 'tomorrow', '明天', '내일 만나요.', 'See you tomorrow.', '明天见。'),
  ('ko-life-basic-82', 'ko', 'basic', 'daily life', '어제', '어제', 'eoje', 'yesterday', '昨天', '어제 잘 잤어요.', 'I slept well yesterday.', '我昨天睡得好。'),
  ('ko-life-basic-83', 'ko', 'basic', 'daily life', '아침', '아침', 'achim', 'morning', '早上', '아침에 일어나요.', 'I wake up in the morning.', '我早上起床。'),
  ('ko-life-basic-84', 'ko', 'basic', 'daily life', '점심', '점심', 'jeomsim', 'noon, lunch', '中午', '점심에 밥을 먹어요.', 'I eat lunch at noon.', '我中午吃饭。'),
  ('ko-life-basic-85', 'ko', 'basic', 'daily life', '저녁', '저녁', 'jeonyeok', 'evening', '晚上', '저녁에 집에 가요.', 'I go home in the evening.', '我晚上回家。'),
  ('ko-life-basic-86', 'ko', 'basic', 'daily life', '일', '일', 'il', 'work, job', '工作', '일을 해요.', 'I work.', '我工作。'),
  ('ko-life-basic-87', 'ko', 'basic', 'daily life', '공부', '공부', 'gongbu', 'study', '学习', '공부해요.', 'I study.', '我学习。'),
  ('ko-life-basic-88', 'ko', 'basic', 'daily life', '운동', '운동', 'undong', 'exercise', '运动', '운동해요.', 'I exercise.', '我运动。'),
  ('ko-life-basic-89', 'ko', 'basic', 'daily life', '산책', '산책', 'sanchaek', 'walk, stroll', '散步', '산책해요.', 'I take a walk.', '我散步。'),
  ('ko-life-basic-90', 'ko', 'basic', 'daily life', '수영', '수영', 'suyeong', 'swimming', '游泳', '수영해요.', 'I swim.', '我游泳。'),
  ('ko-life-basic-91', 'ko', 'basic', 'daily life', '노래', '노래', 'norae', 'song, singing', '歌，唱歌', '노래를 해요.', 'I sing.', '我唱歌。'),
  ('ko-life-basic-92', 'ko', 'basic', 'daily life', '음악', '음악', 'eumak', 'music', '音乐', '음악을 들어요.', 'I listen to music.', '我听音乐。'),
  ('ko-life-basic-93', 'ko', 'basic', 'daily life', '영화', '영화', 'yeonghwa', 'movie', '电影', '영화를 봐요.', 'I watch a movie.', '我看电影。'),
  ('ko-life-basic-94', 'ko', 'basic', 'daily life', '책', '책', 'chaek', 'book', '书', '책을 읽어요.', 'I read a book.', '我看书。'),
  ('ko-life-basic-95', 'ko', 'basic', 'daily life', '게임', '게임', 'geim', 'game', '游戏', '게임을 해요.', 'I play a game.', '我玩游戏。'),
  ('ko-life-basic-96', 'ko', 'basic', 'daily life', '쇼핑', '쇼핑', 'syoping', 'shopping', '购物', '쇼핑을 해요.', 'I go shopping.', '我购物。'),
  ('ko-life-basic-97', 'ko', 'basic', 'daily life', '요리', '요리', 'yori', 'cooking', '做饭', '요리를 해요.', 'I cook.', '我做饭。'),
  ('ko-life-basic-98', 'ko', 'basic', 'daily life', '취미', '취미', 'chwimi', 'hobby', '爱好', '취미가 뭐예요?', 'What''s your hobby?', '你的爱好是什么？'),
  ('ko-life-basic-99', 'ko', 'basic', 'daily life', '약속', '약속', 'yaksok', 'appointment, promise', '约定', '약속이 있어요.', 'I have an appointment.', '我有约。'),
  ('ko-life-basic-100', 'ko', 'basic', 'daily life', '생일', '생일', 'saengil', 'birthday', '生日', '생일 축하해요!', 'Happy birthday!', '生日快乐！'),
  ('ko-life-basic-101', 'ko', 'basic', 'daily life', '선물', '선물', 'seonmul', 'gift', '礼物', '선물을 줘요.', 'I give a gift.', '我送礼物。'),
  ('ko-life-basic-102', 'ko', 'basic', 'daily life', '파티', '파티', 'pati', 'party', '聚会', '파티에 가요.', 'I go to a party.', '我去聚会。'),
  ('ko-life-basic-103', 'ko', 'basic', 'daily life', '휴일', '휴일', 'hyuil', 'holiday', '假日', '오늘은 휴일이에요.', 'Today is a holiday.', '今天是假日。'),
  ('ko-life-basic-104', 'ko', 'basic', 'daily life', '방학', '방학', 'banghak', 'vacation (school)', '假期', '방학이에요!', 'It''s vacation!', '放假了！'),
  ('ko-life-basic-105', 'ko', 'basic', 'daily life', '휴가', '휴가', 'hyuga', 'vacation (work)', '休假', '휴가를 받아요.', 'I get time off.', '我休假。'),
  ('ko-life-basic-106', 'ko', 'basic', 'daily life', '피곤하다', '피곤하다', 'pigonhada', 'tired', '累', '피곤해요.', 'I''m tired.', '我累了。'),
  ('ko-life-basic-107', 'ko', 'basic', 'daily life', '바쁘다', '바쁘다', 'bappeuda', 'busy', '忙', '요즘 바빠요.', 'I''m busy lately.', '最近很忙。'),
  ('ko-life-basic-108', 'ko', 'basic', 'daily life', '심심하다', '심심하다', 'simsimhada', 'bored', '无聊', '심심해요.', 'I''m bored.', '我无聊。'),
  ('ko-life-basic-109', 'ko', 'basic', 'daily life', '기쁘다', '기쁘다', 'gippeuda', 'happy, glad', '高兴', '기뻐요.', 'I''m happy.', '我高兴。'),
  ('ko-life-basic-110', 'ko', 'basic', 'daily life', '슬프다', '슬프다', 'seulpeuda', 'sad', '伤心', '슬퍼요.', 'I''m sad.', '我难过。'),
  ('ko-life-basic-111', 'ko', 'basic', 'daily life', '화나다', '화나다', 'hwanada', 'angry', '生气', '화가 나요.', 'I''m angry.', '我生气了。'),
  ('ko-life-basic-112', 'ko', 'basic', 'daily life', '걱정', '걱정', 'geokjeong', 'worry', '担心', '걱정하지 마세요.', 'Don''t worry.', '别担心。'),
  ('ko-life-basic-113', 'ko', 'basic', 'daily life', '행복하다', '행복하다', 'haengbokhada', 'happy, content', '幸福', '행복해요.', 'I''m happy.', '我很幸福。'),
  ('ko-life-basic-114', 'ko', 'basic', 'daily life', '편하다', '편하다', 'pyeonhada', 'comfortable', '舒适', '이 소파가 편해요.', 'This sofa is comfortable.', '这沙发很舒服。'),
  ('ko-life-basic-115', 'ko', 'basic', 'daily life', '불편하다', '불편하다', 'bulpyeonhada', 'uncomfortable', '不方便', '좀 불편해요.', 'It''s a bit uncomfortable.', '有点不方便。'),
  ('ko-life-basic-116', 'ko', 'basic', 'daily life', '이웃', '이웃', 'iut', 'neighbor', '邻居', '이웃을 만났어요.', 'I met my neighbor.', '我遇到了邻居。'),
  ('ko-life-basic-117', 'ko', 'basic', 'daily life', '택배', '택배', 'taekbae', 'delivery package', '快递', '택배가 왔어요.', 'A package arrived.', '快递到了。'),
  ('ko-life-basic-118', 'ko', 'basic', 'daily life', '우편', '우편', 'upyeon', 'mail', '邮件', '우편을 받았어요.', 'I received mail.', '我收到邮件了。'),
  ('ko-life-basic-119', 'ko', 'basic', 'daily life', '알람', '알람', 'allam', 'alarm', '闹钟', '알람을 맞춰요.', 'I set an alarm.', '我设闹钟。'),
  ('ko-life-basic-120', 'ko', 'basic', 'daily life', '일찍', '일찍', 'iljjik', 'early', '早', '일찍 일어나요.', 'I wake up early.', '我早起。'),
  ('ko-life-basic-121', 'ko', 'basic', 'daily life', '늦게', '늦게', 'neutge', 'late', '晚', '늦게 자요.', 'I go to bed late.', '我晚睡。'),
  ('ko-life-basic-122', 'ko', 'basic', 'daily life', '매일', '매일', 'maeil', 'every day', '每天', '매일 운동해요.', 'I exercise every day.', '我每天运动。'),
  ('ko-life-basic-123', 'ko', 'basic', 'daily life', '가끔', '가끔', 'gakkeum', 'sometimes', '偶尔', '가끔 외식해요.', 'I eat out sometimes.', '我偶尔外出吃饭。'),
  ('ko-life-basic-124', 'ko', 'basic', 'daily life', '항상', '항상', 'hangsang', 'always', '总是', '항상 감사해요.', 'I''m always grateful.', '我总是很感谢。'),
  ('ko-life-basic-125', 'ko', 'basic', 'daily life', '보통', '보통', 'botong', 'usually', '通常', '보통 7시에 일어나요.', 'I usually wake up at 7.', '我通常7点起床。'),
  ('ko-life-basic-126', 'ko', 'basic', 'daily life', '같이', '같이', 'gachi', 'together', '一起', '같이 가요.', 'Let''s go together.', '一起去吧。'),
  ('ko-life-basic-127', 'ko', 'basic', 'daily life', '혼자', '혼자', 'honja', 'alone', '独自', '혼자 살아요.', 'I live alone.', '我一个人住。'),
  ('ko-life-basic-128', 'ko', 'basic', 'daily life', '결혼', '결혼', 'gyeolhon', 'marriage', '结婚', '결혼했어요.', 'I''m married.', '我结婚了。'),
  ('ko-life-basic-129', 'ko', 'basic', 'daily life', '사랑', '사랑', 'sarang', 'love', '爱', '사랑해요.', 'I love you.', '我爱你。'),
  ('ko-life-basic-130', 'ko', 'basic', 'daily life', '전화하다', '전화하다', 'jeonhwahada', 'to call', '打电话', '전화해요.', 'I make a phone call.', '我打电话。'),
  ('ko-life-basic-131', 'ko', 'basic', 'daily life', '문자', '문자', 'munja', 'text message', '短信', '문자를 보내요.', 'I send a text.', '我发短信。'),
  ('ko-life-basic-132', 'ko', 'basic', 'daily life', '인터넷', '인터넷', 'inteonet', 'internet', '网络', '인터넷을 해요.', 'I use the internet.', '我上网。'),
  ('ko-life-basic-133', 'ko', 'basic', 'daily life', 'SNS', 'SNS', 'eseuenseu', 'social media', '社交媒体', 'SNS를 봐요.', 'I check social media.', '我看社交媒体。'),
  ('ko-life-basic-134', 'ko', 'basic', 'daily life', '사진', '사진', 'sajin', 'photo', '照片', '사진을 찍어요.', 'I take a photo.', '我拍照。'),
  ('ko-life-basic-135', 'ko', 'basic', 'daily life', '날짜', '날짜', 'nalija', 'date', '日期', '오늘 날짜가 뭐예요?', 'What''s today''s date?', '今天几号？'),
  ('ko-life-basic-136', 'ko', 'basic', 'daily life', '계절', '계절', 'gyejeol', 'season', '季节', '어떤 계절을 좋아해요?', 'What season do you like?', '你喜欢什么季节？'),
  ('ko-life-basic-137', 'ko', 'basic', 'daily life', '봄', '봄', 'bom', 'spring', '春天', '봄이 좋아요.', 'I like spring.', '我喜欢春天。'),
  ('ko-life-basic-138', 'ko', 'basic', 'daily life', '여름', '여름', 'yeoreum', 'summer', '夏天', '여름이 더워요.', 'Summer is hot.', '夏天很热。'),
  ('ko-life-basic-139', 'ko', 'basic', 'daily life', '가을', '가을', 'gaeul', 'autumn', '秋天', '가을이 좋아요.', 'I like autumn.', '我喜欢秋天。'),
  ('ko-life-basic-140', 'ko', 'basic', 'daily life', '겨울', '겨울', 'gyeoul', 'winter', '冬天', '겨울이 추워요.', 'Winter is cold.', '冬天很冷。'),
  ('ko-life-basic-141', 'ko', 'basic', 'daily life', '안경', '안경', 'angyeong', 'glasses', '眼镜', '안경을 써요.', 'I wear glasses.', '我戴眼镜。'),
  ('ko-life-basic-142', 'ko', 'basic', 'daily life', '신발', '신발', 'sinbal', 'shoes', '鞋', '신발을 신어요.', 'I put on shoes.', '我穿鞋。'),
  ('ko-life-basic-143', 'ko', 'basic', 'daily life', '모자', '모자', 'moja', 'hat', '帽子', '모자를 써요.', 'I wear a hat.', '我戴帽子。'),
  ('ko-life-basic-144', 'ko', 'basic', 'daily life', '가방', '가방', 'gabang', 'bag', '包', '가방을 메요.', 'I carry a bag.', '我背包。'),
  ('ko-life-basic-145', 'ko', 'basic', 'daily life', '우산', '우산', 'usan', 'umbrella', '伞', '우산을 가져가요.', 'I bring an umbrella.', '我带伞。'),
  ('ko-life-basic-146', 'ko', 'basic', 'daily life', '지갑', '지갑', 'jigap', 'wallet', '钱包', '지갑을 가져가요.', 'I bring my wallet.', '我带钱包。'),
  ('ko-life-basic-147', 'ko', 'basic', 'daily life', '열쇠', '열쇠', 'yeolsoe', 'key', '钥匙', '열쇠를 가져가요.', 'I bring my keys.', '我带钥匙。'),
  ('ko-life-basic-148', 'ko', 'basic', 'daily life', '이사', '이사', 'isa', 'moving (house)', '搬家', '이사를 해요.', 'I''m moving.', '我搬家。'),
  ('ko-life-basic-149', 'ko', 'basic', 'daily life', '월세', '월세', 'wolse', 'monthly rent', '月租', '월세를 내요.', 'I pay monthly rent.', '我交月租。'),
  ('ko-life-basic-150', 'ko', 'basic', 'daily life', '관리비', '관리비', 'gwanlibi', 'maintenance fee', '管理费', '관리비를 내요.', 'I pay the maintenance fee.', '我交管理费。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
