-- Expand ja-school-intermediate to 150 curated entries (17-150)
-- Topic: school/education vocabulary for intermediate Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-school-intermediate-17', 'ja', 'intermediate', 'school', '数学', 'すうがく', 'suugaku', 'mathematics, math', '数学，算数', '数学のテストは難しかったです。', 'The math test was difficult.', '数学考试很难。'),
  ('ja-school-intermediate-18', 'ja', 'intermediate', 'school', '物理', 'ぶつり', 'butsuri', 'physics, physical science', '物理，物理学', '物理の実験をしました。', 'We did a physics experiment.', '我们做了物理实验。'),
  ('ja-school-intermediate-19', 'ja', 'intermediate', 'school', '化学', 'かがく', 'kagaku', 'chemistry, chemical science', '化学，化学课', '化学の授業で元素を学びました。', 'We learned about elements in chemistry class.', '我们在化学课上学了元素。'),
  ('ja-school-intermediate-20', 'ja', 'intermediate', 'school', '生物', 'せいぶつ', 'seibutsu', 'biology, living things', '生物，生物学', '生物の教科書を開いてください。', 'Please open your biology textbook.', '请打开生物课本。'),
  ('ja-school-intermediate-21', 'ja', 'intermediate', 'school', '歴史', 'れきし', 'rekishi', 'history, historical studies', '历史，史学', '歴史の授業が一番好きです。', 'History class is my favorite.', '我最喜欢历史课。'),
  ('ja-school-intermediate-22', 'ja', 'intermediate', 'school', '地理', 'ちり', 'chiri', 'geography, geographical studies', '地理，地理学', '地理で世界の国を覚えます。', 'We memorize countries in geography.', '我们在地理课上记世界各国。'),
  ('ja-school-intermediate-23', 'ja', 'intermediate', 'school', '英語', 'えいご', 'eigo', 'English, English language', '英语，英文', '英語の発音が上手ですね。', 'Your English pronunciation is good.', '你的英语发音真好。'),
  ('ja-school-intermediate-24', 'ja', 'intermediate', 'school', '国語', 'こくご', 'kokugo', 'Japanese language, national language', '国语，语文', '国語の作文を書きました。', 'I wrote a composition in Japanese class.', '我写了语文作文。'),
  ('ja-school-intermediate-25', 'ja', 'intermediate', 'school', '図書館', 'としょかん', 'toshokan', 'library, book room', '图书馆，图书室', '図書館で勉強しています。', 'I am studying at the library.', '我在图书馆学习。'),
  ('ja-school-intermediate-26', 'ja', 'intermediate', 'school', '体育館', 'たいいくかん', 'taiikukan', 'gymnasium, sports hall', '体育馆，体育场', '体育館でバスケをしました。', 'We played basketball in the gymnasium.', '我们在体育馆打了篮球。'),
  ('ja-school-intermediate-27', 'ja', 'intermediate', 'school', '教室', 'きょうしつ', 'kyoushitsu', 'classroom, lecture room', '教室，课堂', '教室に忘れ物をしました。', 'I left something behind in the classroom.', '我把东西忘在教室了。'),
  ('ja-school-intermediate-28', 'ja', 'intermediate', 'school', '校庭', 'こうてい', 'koutei', 'schoolyard, school grounds', '校园，操场', '校庭で体育の授業があります。', 'We have PE class in the schoolyard.', '我们在操场上体育课。'),
  ('ja-school-intermediate-29', 'ja', 'intermediate', 'school', '実験室', 'じっけんしつ', 'jikkenshitsu', 'laboratory, experiment room', '实验室，实验房', '実験室の器具を片付けてください。', 'Please clean up the laboratory equipment.', '请收拾实验室的器材。'),
  ('ja-school-intermediate-30', 'ja', 'intermediate', 'school', '講義', 'こうぎ', 'kougi', 'lecture, academic talk', '讲座，讲义', '今日の講義は面白かったです。', 'Today''s lecture was interesting.', '今天的讲座很有趣。'),
  ('ja-school-intermediate-31', 'ja', 'intermediate', 'school', '実験', 'じっけん', 'jikken', 'experiment, practical test', '实验，试验', '化学の実験に成功しました。', 'The chemistry experiment was a success.', '化学实验成功了。'),
  ('ja-school-intermediate-32', 'ja', 'intermediate', 'school', '研究', 'けんきゅう', 'kenkyuu', 'research, study', '研究，钻研', '大学で言語学を研究しています。', 'I am researching linguistics at university.', '我在大学研究语言学。'),
  ('ja-school-intermediate-33', 'ja', 'intermediate', 'school', '論文', 'ろんぶん', 'ronbun', 'thesis, academic paper', '论文，学术论文', '卒業論文を書いています。', 'I am writing my graduation thesis.', '我在写毕业论文。'),
  ('ja-school-intermediate-34', 'ja', 'intermediate', 'school', 'レポート', 'れぽーと', 'repooto', 'report, paper', '报告，作业报告', 'レポートの締め切りは来週です。', 'The report deadline is next week.', '报告的截止日期是下周。'),
  ('ja-school-intermediate-35', 'ja', 'intermediate', 'school', '発表', 'はっぴょう', 'happyou', 'presentation, announcement', '发表，演讲', '来週クラスで発表します。', 'I will give a presentation in class next week.', '下周我要在班上做演讲。'),
  ('ja-school-intermediate-36', 'ja', 'intermediate', 'school', '先生', 'せんせい', 'sensei', 'teacher, instructor', '老师，教师', '先生に質問があります。', 'I have a question for the teacher.', '我有问题要问老师。'),
  ('ja-school-intermediate-37', 'ja', 'intermediate', 'school', '教授', 'きょうじゅ', 'kyouju', 'professor, full professor', '教授，大学教授', '教授の研究室を訪ねました。', 'I visited the professor''s office.', '我去了教授的研究室。'),
  ('ja-school-intermediate-38', 'ja', 'intermediate', 'school', '学生', 'がくせい', 'gakusei', 'student, university student', '学生，大学生', '学生証を見せてください。', 'Please show your student ID.', '请出示学生证。'),
  ('ja-school-intermediate-39', 'ja', 'intermediate', 'school', '生徒', 'せいと', 'seito', 'pupil, school student', '学生，中小学生', '生徒たちは静かに聞いていました。', 'The students were listening quietly.', '学生们安静地听着。'),
  ('ja-school-intermediate-40', 'ja', 'intermediate', 'school', '先輩', 'せんぱい', 'senpai', 'senior, upperclassman', '前辈，学长', '先輩にアドバイスをもらいました。', 'I received advice from my senior.', '我从学长那里得到了建议。'),
  ('ja-school-intermediate-41', 'ja', 'intermediate', 'school', '後輩', 'こうはい', 'kouhai', 'junior, underclassman', '后辈，学弟学妹', '後輩に勉強を教えています。', 'I am teaching my juniors.', '我在教学弟学妹学习。'),
  ('ja-school-intermediate-42', 'ja', 'intermediate', 'school', '点数', 'てんすう', 'tensuu', 'score, points', '分数，得分', '点数が上がりました。', 'My score went up.', '我的分数提高了。'),
  ('ja-school-intermediate-43', 'ja', 'intermediate', 'school', '合格', 'ごうかく', 'goukaku', 'passing, success', '合格，及格', '試験に合格しました。', 'I passed the exam.', '我考试合格了。'),
  ('ja-school-intermediate-44', 'ja', 'intermediate', 'school', '不合格', 'ふごうかく', 'fugoukaku', 'failure, not passing', '不合格，不及格', '不合格だったので再試験を受けます。', 'I failed so I will take a re-exam.', '因为不及格所以要补考。'),
  ('ja-school-intermediate-45', 'ja', 'intermediate', 'school', '単位', 'たんい', 'tan''i', 'credit, academic unit', '学分，单位', '今学期は20単位取ります。', 'I am taking 20 credits this semester.', '这学期我修20个学分。'),
  ('ja-school-intermediate-46', 'ja', 'intermediate', 'school', '部活', 'ぶかつ', 'bukatsu', 'club activity, extracurricular', '社团活动，课外活动', '部活は毎日放課後にあります。', 'Club activities are every day after school.', '社团活动每天放学后进行。'),
  ('ja-school-intermediate-47', 'ja', 'intermediate', 'school', 'サークル', 'さーくる', 'saakuru', 'circle, university club', '社团，兴趣小组', '大学でテニスサークルに入りました。', 'I joined a tennis circle at university.', '我在大学加入了网球社团。'),
  ('ja-school-intermediate-48', 'ja', 'intermediate', 'school', '文化祭', 'ぶんかさい', 'bunkasai', 'cultural festival, school festival', '文化节，校园祭', '文化祭で劇をやります。', 'We are performing a play at the cultural festival.', '我们在文化节演话剧。'),
  ('ja-school-intermediate-49', 'ja', 'intermediate', 'school', '体育祭', 'たいいくさい', 'taiikusai', 'sports festival, athletic meet', '运动会，体育节', '体育祭のリレーに出ます。', 'I will participate in the relay at the sports festival.', '我要参加运动会的接力赛。'),
  ('ja-school-intermediate-50', 'ja', 'intermediate', 'school', '進学', 'しんがく', 'shingaku', 'advancing to higher education, enrollment', '升学，进学', '大学に進学するつもりです。', 'I plan to advance to university.', '我打算升学上大学。'),
  ('ja-school-intermediate-51', 'ja', 'intermediate', 'school', '留学', 'りゅうがく', 'ryuugaku', 'study abroad, overseas study', '留学，出国学习', '来年アメリカに留学します。', 'I will study abroad in America next year.', '明年我要去美国留学。'),
  ('ja-school-intermediate-52', 'ja', 'intermediate', 'school', '奨学金', 'しょうがくきん', 'shougakukin', 'scholarship, financial aid', '奖学金，助学金', '奨学金をもらって留学します。', 'I will study abroad on a scholarship.', '我拿奖学金去留学。'),
  ('ja-school-intermediate-53', 'ja', 'intermediate', 'school', '受験', 'じゅけん', 'juken', 'taking an exam, entrance exam', '考试，应试', '来年大学を受験します。', 'I will take the university entrance exam next year.', '明年我要参加大学入学考试。'),
  ('ja-school-intermediate-54', 'ja', 'intermediate', 'school', '入試', 'にゅうし', 'nyuushi', 'entrance examination, admission test', '入学考试，招生考试', '入試の準備をしています。', 'I am preparing for the entrance exam.', '我在准备入学考试。'),
  ('ja-school-intermediate-55', 'ja', 'intermediate', 'school', '塾', 'じゅく', 'juku', 'cram school, tutoring school', '补习班，私塾', '毎週火曜日に塾に通っています。', 'I go to cram school every Tuesday.', '我每周二去补习班。'),
  ('ja-school-intermediate-56', 'ja', 'intermediate', 'school', '予備校', 'よびこう', 'yobikou', 'prep school, preparatory school', '预备校，考试补习学校', '予備校で受験対策をしています。', 'I am preparing for exams at prep school.', '我在预备校备考。'),
  ('ja-school-intermediate-57', 'ja', 'intermediate', 'school', '時間割', 'じかんわり', 'jikanwari', 'timetable, class schedule', '课程表，时间表', '時間割を確認してください。', 'Please check the timetable.', '请确认课程表。'),
  ('ja-school-intermediate-58', 'ja', 'intermediate', 'school', '科目', 'かもく', 'kamoku', 'subject, course', '科目，学科', '好きな科目は何ですか。', 'What is your favorite subject?', '你最喜欢什么科目？'),
  ('ja-school-intermediate-59', 'ja', 'intermediate', 'school', '必修', 'ひっしゅう', 'hisshuu', 'required course, compulsory', '必修，必修课', '英語は必修科目です。', 'English is a required subject.', '英语是必修课。'),
  ('ja-school-intermediate-60', 'ja', 'intermediate', 'school', '選択', 'せんたく', 'sentaku', 'elective, selection', '选修，选择', '選択科目を三つ選びました。', 'I chose three elective subjects.', '我选了三门选修课。'),
  ('ja-school-intermediate-61', 'ja', 'intermediate', 'school', '履修', 'りしゅう', 'rishuu', 'course registration, taking a course', '选课，修课', '今学期の履修登録をしました。', 'I completed course registration for this semester.', '我完成了这学期的选课。'),
  ('ja-school-intermediate-62', 'ja', 'intermediate', 'school', '出欠', 'しゅっけつ', 'shukketsu', 'attendance record, roll call', '出勤，出缺席', '出欠を取ります。', 'I will take attendance.', '我来点名。'),
  ('ja-school-intermediate-63', 'ja', 'intermediate', 'school', '遅刻', 'ちこく', 'chikoku', 'tardiness, being late', '迟到，晚到', '遅刻しないでください。', 'Please don''t be late.', '请不要迟到。'),
  ('ja-school-intermediate-64', 'ja', 'intermediate', 'school', '早退', 'そうたい', 'soutai', 'leaving early, early departure', '早退，提前离开', '体調が悪いので早退します。', 'I will leave early because I feel sick.', '因为身体不舒服所以早退。'),
  ('ja-school-intermediate-65', 'ja', 'intermediate', 'school', '中間試験', 'ちゅうかんしけん', 'chuukan shiken', 'midterm exam, mid-semester test', '期中考试，中间考试', '中間試験の範囲を教えてください。', 'Please tell me the midterm exam scope.', '请告诉我期中考试的范围。'),
  ('ja-school-intermediate-66', 'ja', 'intermediate', 'school', '期末試験', 'きまつしけん', 'kimatsu shiken', 'final exam, end-of-term test', '期末考试，末考', '期末試験が来週始まります。', 'Final exams start next week.', '期末考试下周开始。'),
  ('ja-school-intermediate-67', 'ja', 'intermediate', 'school', '追試', 'ついし', 'tsuishi', 'make-up exam, supplementary test', '补考，追加考试', '追試を受けることになりました。', 'I ended up having to take a make-up exam.', '我要参加补考了。'),
  ('ja-school-intermediate-68', 'ja', 'intermediate', 'school', '答案', 'とうあん', 'touan', 'answer sheet, solution', '答案，答卷', '答案を提出してください。', 'Please submit your answer sheet.', '请提交答卷。'),
  ('ja-school-intermediate-69', 'ja', 'intermediate', 'school', '採点', 'さいてん', 'saiten', 'grading, marking', '评分，打分', '先生が採点しています。', 'The teacher is grading.', '老师在评分。'),
  ('ja-school-intermediate-70', 'ja', 'intermediate', 'school', '通知表', 'つうちひょう', 'tsuuchihyou', 'report card, grade report', '成绩单，通知书', '通知表をもらいました。', 'I received my report card.', '我拿到了成绩单。'),
  ('ja-school-intermediate-71', 'ja', 'intermediate', 'school', '学年', 'がくねん', 'gakunen', 'school year, grade level', '学年，年级', '新しい学年が始まりました。', 'A new school year has started.', '新学年开始了。'),
  ('ja-school-intermediate-72', 'ja', 'intermediate', 'school', '学部', 'がくぶ', 'gakubu', 'faculty, department', '学院，系', '文学部に所属しています。', 'I belong to the Faculty of Literature.', '我属于文学院。'),
  ('ja-school-intermediate-73', 'ja', 'intermediate', 'school', '学科', 'がっか', 'gakka', 'department, course of study', '学科，专业', '経済学科を専攻しています。', 'I am majoring in economics.', '我主修经济学科。'),
  ('ja-school-intermediate-74', 'ja', 'intermediate', 'school', '専攻', 'せんこう', 'senkou', 'major, specialization', '专业，主修', '専攻は心理学です。', 'My major is psychology.', '我的专业是心理学。'),
  ('ja-school-intermediate-75', 'ja', 'intermediate', 'school', '卒論', 'そつろん', 'sotsuron', 'graduation thesis, senior thesis', '毕业论文，毕设', '卒論のテーマを決めました。', 'I decided on my graduation thesis topic.', '我确定了毕业论文的主题。'),
  ('ja-school-intermediate-76', 'ja', 'intermediate', 'school', '修士', 'しゅうし', 'shuushi', 'master''s degree, master''s student', '硕士，硕士生', '修士課程に進みます。', 'I will proceed to the master''s program.', '我要读硕士课程。'),
  ('ja-school-intermediate-77', 'ja', 'intermediate', 'school', '博士', 'はかせ', 'hakase', 'doctorate, PhD', '博士，博士生', '博士号を取得しました。', 'I obtained a PhD.', '我取得了博士学位。'),
  ('ja-school-intermediate-78', 'ja', 'intermediate', 'school', '教育', 'きょういく', 'kyouiku', 'education, teaching', '教育，教学', '教育の質を高めるべきです。', 'We should improve the quality of education.', '应该提高教育质量。'),
  ('ja-school-intermediate-79', 'ja', 'intermediate', 'school', '学習', 'がくしゅう', 'gakushuu', 'learning, study', '学习，研习', '学習の方法を工夫しています。', 'I am working on improving my study methods.', '我在改进学习方法。'),
  ('ja-school-intermediate-80', 'ja', 'intermediate', 'school', '暗記', 'あんき', 'anki', 'memorization, learning by heart', '背诵，记忆', '単語を暗記するのが大変です。', 'Memorizing vocabulary is tough.', '背单词很辛苦。'),
  ('ja-school-intermediate-81', 'ja', 'intermediate', 'school', '参考書', 'さんこうしょ', 'sankousho', 'reference book, study guide', '参考书，辅导书', '参考書を買いました。', 'I bought a reference book.', '我买了参考书。'),
  ('ja-school-intermediate-82', 'ja', 'intermediate', 'school', '辞書', 'じしょ', 'jisho', 'dictionary, lexicon', '字典，词典', '分からない言葉は辞書で調べます。', 'I look up unknown words in the dictionary.', '不懂的词我会查字典。'),
  ('ja-school-intermediate-83', 'ja', 'intermediate', 'school', '筆記', 'ひっき', 'hikki', 'note-taking, written exam', '笔记，笔试', '筆記試験があります。', 'There is a written exam.', '有笔试。'),
  ('ja-school-intermediate-84', 'ja', 'intermediate', 'school', '板書', 'ばんしょ', 'bansho', 'writing on the board, board notes', '板书，黑板上的内容', '板書をノートに写してください。', 'Please copy the board notes into your notebook.', '请把板书抄到笔记本上。'),
  ('ja-school-intermediate-85', 'ja', 'intermediate', 'school', 'チャイム', 'ちゃいむ', 'chaimu', 'chime, school bell', '铃声，上课铃', 'チャイムが鳴りました。', 'The bell rang.', '铃声响了。'),
  ('ja-school-intermediate-86', 'ja', 'intermediate', 'school', '休み時間', 'やすみじかん', 'yasumi jikan', 'break time, recess', '休息时间，课间', '休み時間に友達と話します。', 'I talk with friends during break time.', '课间我和朋友聊天。'),
  ('ja-school-intermediate-87', 'ja', 'intermediate', 'school', '放課後', 'ほうかご', 'houkago', 'after school, after class', '放学后，课后', '放課後に部活があります。', 'I have club activities after school.', '放学后有社团活动。'),
  ('ja-school-intermediate-88', 'ja', 'intermediate', 'school', '登校', 'とうこう', 'toukou', 'going to school, attending school', '上学，到校', '毎朝八時に登校します。', 'I go to school at 8 every morning.', '我每天早上八点上学。'),
  ('ja-school-intermediate-89', 'ja', 'intermediate', 'school', '下校', 'げこう', 'gekou', 'leaving school, going home', '放学，回家', '下校時間は四時です。', 'The time to leave school is 4 o''clock.', '放学时间是四点。'),
  ('ja-school-intermediate-90', 'ja', 'intermediate', 'school', '校長', 'こうちょう', 'kouchou', 'principal, headmaster', '校长，学校负责人', '校長先生が挨拶をしました。', 'The principal gave a greeting.', '校长致辞了。'),
  ('ja-school-intermediate-91', 'ja', 'intermediate', 'school', '担任', 'たんにん', 'tannin', 'homeroom teacher, class teacher', '班主任，负责老师', '担任の先生は優しいです。', 'Our homeroom teacher is kind.', '班主任老师很温柔。'),
  ('ja-school-intermediate-92', 'ja', 'intermediate', 'school', '同級生', 'どうきゅうせい', 'doukyuusei', 'classmate, same-year student', '同学，同班同学', '同級生と一緒に勉強します。', 'I study together with my classmates.', '我和同学一起学习。'),
  ('ja-school-intermediate-93', 'ja', 'intermediate', 'school', '留年', 'りゅうねん', 'ryuunen', 'repeating a year, being held back', '留级，重读', '単位が足りなくて留年しました。', 'I repeated a year because I didn''t have enough credits.', '因为学分不够留级了。'),
  ('ja-school-intermediate-94', 'ja', 'intermediate', 'school', '退学', 'たいがく', 'taigaku', 'dropping out, withdrawal', '退学，辍学', '大学を退学する人もいます。', 'Some people drop out of university.', '也有人从大学退学。'),
  ('ja-school-intermediate-95', 'ja', 'intermediate', 'school', '編入', 'へんにゅう', 'hennyuu', 'transfer admission, lateral entry', '编入，转入', '三年次に編入しました。', 'I transferred in at the third year.', '我在三年级转入了。'),
  ('ja-school-intermediate-96', 'ja', 'intermediate', 'school', '学費', 'がくひ', 'gakuhi', 'tuition, school fees', '学费，学杂费', '学費が高くて大変です。', 'The tuition is expensive and it''s tough.', '学费很高很辛苦。'),
  ('ja-school-intermediate-97', 'ja', 'intermediate', 'school', '教科', 'きょうか', 'kyouka', 'school subject, curriculum area', '学科，教学科目', '教科ごとに先生が違います。', 'Each subject has a different teacher.', '每个学科的老师不同。'),
  ('ja-school-intermediate-98', 'ja', 'intermediate', 'school', '美術', 'びじゅつ', 'bijutsu', 'art, fine arts', '美术，艺术', '美術の時間に絵を描きます。', 'We draw pictures in art class.', '美术课上画画。'),
  ('ja-school-intermediate-99', 'ja', 'intermediate', 'school', '音楽', 'おんがく', 'ongaku', 'music, musical studies', '音乐，音乐课', '音楽の授業でピアノを弾きました。', 'I played piano in music class.', '我在音乐课上弹了钢琴。'),
  ('ja-school-intermediate-100', 'ja', 'intermediate', 'school', '体育', 'たいいく', 'taiiku', 'physical education, PE', '体育，体育课', '体育の授業で走りました。', 'We ran in PE class.', '我们在体育课上跑步了。'),
  ('ja-school-intermediate-101', 'ja', 'intermediate', 'school', '家庭科', 'かていか', 'kateika', 'home economics, domestic science', '家政课，家庭课', '家庭科で料理を作りました。', 'We cooked in home economics class.', '我们在家政课上做了饭。'),
  ('ja-school-intermediate-102', 'ja', 'intermediate', 'school', '道徳', 'どうとく', 'doutoku', 'moral education, ethics', '道德，品德课', '道徳の時間にいじめについて話し合いました。', 'We discussed bullying in moral education class.', '我们在品德课上讨论了欺凌问题。'),
  ('ja-school-intermediate-103', 'ja', 'intermediate', 'school', '保健室', 'ほけんしつ', 'hokenshitsu', 'nurse''s office, infirmary', '保健室，医务室', '気分が悪いので保健室に行きます。', 'I feel sick so I''m going to the nurse''s office.', '我不舒服所以去保健室。'),
  ('ja-school-intermediate-104', 'ja', 'intermediate', 'school', '職員室', 'しょくいんしつ', 'shokuinshitsu', 'staff room, teachers'' office', '教师办公室，教员室', '職員室にノートを届けます。', 'I will deliver the notebook to the staff room.', '我把笔记本送到教师办公室。'),
  ('ja-school-intermediate-105', 'ja', 'intermediate', 'school', '下駄箱', 'げたばこ', 'getabako', 'shoe locker, shoe cabinet', '鞋柜，换鞋处', '下駄箱に靴を入れてください。', 'Please put your shoes in the shoe locker.', '请把鞋放进鞋柜。'),
  ('ja-school-intermediate-106', 'ja', 'intermediate', 'school', '掃除', 'そうじ', 'souji', 'cleaning, tidying up', '打扫，清扫', '放課後に教室の掃除をします。', 'We clean the classroom after school.', '放学后打扫教室。'),
  ('ja-school-intermediate-107', 'ja', 'intermediate', 'school', '日直', 'にっちょく', 'nicchoku', 'day duty, class monitor for the day', '值日，当天值班', '今日は私が日直です。', 'Today I am on day duty.', '今天轮到我值日。'),
  ('ja-school-intermediate-108', 'ja', 'intermediate', 'school', '委員', 'いいん', 'iin', 'committee member, class representative', '委员，班委', '図書委員をしています。', 'I am a library committee member.', '我是图书委员。'),
  ('ja-school-intermediate-109', 'ja', 'intermediate', 'school', '生徒会', 'せいとかい', 'seitokai', 'student council, student government', '学生会，学生组织', '生徒会の選挙があります。', 'There is a student council election.', '有学生会选举。'),
  ('ja-school-intermediate-110', 'ja', 'intermediate', 'school', '会長', 'かいちょう', 'kaichou', 'president, chairperson', '会长，主席', '生徒会長に立候補しました。', 'I ran for student council president.', '我竞选了学生会主席。'),
  ('ja-school-intermediate-111', 'ja', 'intermediate', 'school', '修学旅行', 'しゅうがくりょこう', 'shuugaku ryokou', 'school trip, educational excursion', '修学旅行，研学旅行', '修学旅行で京都に行きます。', 'We are going to Kyoto on our school trip.', '修学旅行去京都。'),
  ('ja-school-intermediate-112', 'ja', 'intermediate', 'school', '遠足', 'えんそく', 'ensoku', 'field trip, excursion', '远足，郊游', '遠足で山に登りました。', 'We climbed a mountain on our field trip.', '远足时爬了山。'),
  ('ja-school-intermediate-113', 'ja', 'intermediate', 'school', '運動会', 'うんどうかい', 'undoukai', 'sports day, athletic meeting', '运动会，校运会', '運動会のリレーで一位になりました。', 'We came first in the sports day relay.', '我们在运动会接力赛中得了第一。'),
  ('ja-school-intermediate-114', 'ja', 'intermediate', 'school', '入学式', 'にゅうがくしき', 'nyuugakushiki', 'entrance ceremony, matriculation', '入学典礼，开学式', '入学式に両親が来ました。', 'My parents came to the entrance ceremony.', '父母来参加了入学典礼。'),
  ('ja-school-intermediate-115', 'ja', 'intermediate', 'school', '卒業式', 'そつぎょうしき', 'sotsugyoushiki', 'graduation ceremony, commencement', '毕业典礼，毕业式', '卒業式で涙が出ました。', 'I cried at the graduation ceremony.', '在毕业典礼上我哭了。'),
  ('ja-school-intermediate-116', 'ja', 'intermediate', 'school', '始業式', 'しぎょうしき', 'shigyoushiki', 'opening ceremony, term start ceremony', '开学典礼，始业式', '始業式は四月にあります。', 'The opening ceremony is in April.', '开学典礼在四月。'),
  ('ja-school-intermediate-117', 'ja', 'intermediate', 'school', '終業式', 'しゅうぎょうしき', 'shuugyoushiki', 'closing ceremony, end-of-term ceremony', '结业典礼，终业式', '終業式の後に夏休みが始まります。', 'Summer vacation starts after the closing ceremony.', '结业典礼后暑假开始。'),
  ('ja-school-intermediate-118', 'ja', 'intermediate', 'school', '夏休み', 'なつやすみ', 'natsuyasumi', 'summer vacation, summer break', '暑假，夏天假期', '夏休みに宿題がたくさんあります。', 'There is a lot of homework during summer vacation.', '暑假作业很多。'),
  ('ja-school-intermediate-119', 'ja', 'intermediate', 'school', '春休み', 'はるやすみ', 'haruyasumi', 'spring break, spring vacation', '春假，春天假期', '春休みに旅行します。', 'I will travel during spring break.', '春假去旅行。'),
  ('ja-school-intermediate-120', 'ja', 'intermediate', 'school', '冬休み', 'ふゆやすみ', 'fuyuyasumi', 'winter break, winter vacation', '寒假，冬天假期', '冬休みは短いです。', 'Winter break is short.', '寒假很短。'),
  ('ja-school-intermediate-121', 'ja', 'intermediate', 'school', '課外', 'かがい', 'kagai', 'extracurricular, outside class', '课外，校外', '課外活動に参加しています。', 'I am participating in extracurricular activities.', '我在参加课外活动。'),
  ('ja-school-intermediate-122', 'ja', 'intermediate', 'school', '提出', 'ていしゅつ', 'teishutsu', 'submission, handing in', '提交，上交', 'レポートを提出しました。', 'I submitted my report.', '我提交了报告。'),
  ('ja-school-intermediate-123', 'ja', 'intermediate', 'school', '締め切り', 'しめきり', 'shimekiri', 'deadline, due date', '截止日期，到期', '締め切りに間に合いました。', 'I made it by the deadline.', '赶上了截止日期。'),
  ('ja-school-intermediate-124', 'ja', 'intermediate', 'school', '質問', 'しつもん', 'shitsumon', 'question, inquiry', '问题，提问', '授業中に質問しました。', 'I asked a question during class.', '上课时我提了问。'),
  ('ja-school-intermediate-125', 'ja', 'intermediate', 'school', '回答', 'かいとう', 'kaitou', 'answer, response', '回答，答复', '正しい回答を書いてください。', 'Please write the correct answer.', '请写出正确答案。'),
  ('ja-school-intermediate-126', 'ja', 'intermediate', 'school', '解答', 'かいとう', 'kaitou', 'solution, worked answer', '解答，解题', '解答を確認しましょう。', 'Let''s check the solution.', '我们来确认一下解答。'),
  ('ja-school-intermediate-127', 'ja', 'intermediate', 'school', '問題', 'もんだい', 'mondai', 'problem, question', '问题，题目', 'この問題が分かりません。', 'I don''t understand this problem.', '我不懂这道题。'),
  ('ja-school-intermediate-128', 'ja', 'intermediate', 'school', '正解', 'せいかい', 'seikai', 'correct answer, right solution', '正确答案，正解', '正解は三番です。', 'The correct answer is number three.', '正确答案是第三个。'),
  ('ja-school-intermediate-129', 'ja', 'intermediate', 'school', '間違い', 'まちがい', 'machigai', 'mistake, error', '错误，失误', '間違いを直してください。', 'Please correct the mistakes.', '请改正错误。'),
  ('ja-school-intermediate-130', 'ja', 'intermediate', 'school', '教壇', 'きょうだん', 'kyoudan', 'podium, teacher''s platform', '讲台，教坛', '先生が教壇に立ちました。', 'The teacher stood at the podium.', '老师站到了讲台上。'),
  ('ja-school-intermediate-131', 'ja', 'intermediate', 'school', 'プリント', 'ぷりんと', 'purinto', 'handout, printed material', '讲义，打印材料', 'プリントを配ります。', 'I will hand out the printouts.', '我来发讲义。'),
  ('ja-school-intermediate-132', 'ja', 'intermediate', 'school', '黒板消し', 'こくばんけし', 'kokubankeshi', 'blackboard eraser, board eraser', '黑板擦，板擦', '黒板消しを使って消してください。', 'Please erase it with the board eraser.', '请用黑板擦擦掉。'),
  ('ja-school-intermediate-133', 'ja', 'intermediate', 'school', 'チョーク', 'ちょーく', 'chooku', 'chalk, writing chalk', '粉笔，板书笔', '先生がチョークで書いています。', 'The teacher is writing with chalk.', '老师用粉笔在写。'),
  ('ja-school-intermediate-134', 'ja', 'intermediate', 'school', '出席番号', 'しゅっせきばんごう', 'shusseki bangou', 'attendance number, student number', '学号，出席号', '出席番号順に並んでください。', 'Please line up in order of your attendance number.', '请按学号排队。'),
  ('ja-school-intermediate-135', 'ja', 'intermediate', 'school', '班', 'はん', 'han', 'group, squad', '班，小组', '班ごとに話し合います。', 'We will discuss in groups.', '按小组讨论。'),
  ('ja-school-intermediate-136', 'ja', 'intermediate', 'school', '組', 'くみ', 'kumi', 'class section, homeroom group', '班级，组', '私は二年三組です。', 'I am in year 2, class 3.', '我是二年三班的。'),
  ('ja-school-intermediate-137', 'ja', 'intermediate', 'school', '席替え', 'せきがえ', 'sekigae', 'seat change, desk rearrangement', '换座位，调座', '来週席替えがあります。', 'There will be a seat change next week.', '下周要换座位。'),
  ('ja-school-intermediate-138', 'ja', 'intermediate', 'school', '給食', 'きゅうしょく', 'kyuushoku', 'school lunch, provided meal', '学校配餐，午餐', '今日の給食はカレーです。', 'Today''s school lunch is curry.', '今天的配餐是咖喱。'),
  ('ja-school-intermediate-139', 'ja', 'intermediate', 'school', '弁当', 'べんとう', 'bentou', 'packed lunch, lunchbox', '便当，盒饭', '母が弁当を作ってくれました。', 'My mother made me a packed lunch.', '妈妈给我做了便当。'),
  ('ja-school-intermediate-140', 'ja', 'intermediate', 'school', '制服', 'せいふく', 'seifuku', 'uniform, school uniform', '校服，制服', '制服を着て登校します。', 'I go to school wearing my uniform.', '穿校服上学。'),
  ('ja-school-intermediate-141', 'ja', 'intermediate', 'school', '上履き', 'うわばき', 'uwabaki', 'indoor shoes, school slippers', '室内鞋，学校鞋', '上履きに履き替えてください。', 'Please change into your indoor shoes.', '请换上室内鞋。'),
  ('ja-school-intermediate-142', 'ja', 'intermediate', 'school', '通学', 'つうがく', 'tsuugaku', 'commuting to school, school commute', '上学，通学', '電車で通学しています。', 'I commute to school by train.', '我坐电车上学。'),
  ('ja-school-intermediate-143', 'ja', 'intermediate', 'school', '学割', 'がくわり', 'gakuwari', 'student discount, academic discount', '学生优惠，学生折扣', '学割で電車に乗れます。', 'I can ride the train with a student discount.', '可以用学生优惠坐电车。'),
  ('ja-school-intermediate-144', 'ja', 'intermediate', 'school', '自習', 'じしゅう', 'jishuu', 'self-study, independent study', '自习，自学', '先生がいないので自習です。', 'The teacher is absent so it''s self-study.', '老师不在所以自习。'),
  ('ja-school-intermediate-145', 'ja', 'intermediate', 'school', '補習', 'ほしゅう', 'hoshuu', 'supplementary lesson, extra class', '补习，补课', '放課後に補習があります。', 'There is a supplementary lesson after school.', '放学后有补课。'),
  ('ja-school-intermediate-146', 'ja', 'intermediate', 'school', '面談', 'めんだん', 'mendan', 'interview, consultation', '面谈，谈话', '先生との面談があります。', 'I have an interview with the teacher.', '我有和老师的面谈。'),
  ('ja-school-intermediate-147', 'ja', 'intermediate', 'school', '進路', 'しんろ', 'shinro', 'future path, career direction', '前途，出路', '進路について相談しました。', 'I consulted about my future path.', '我咨询了关于前途的事。'),
  ('ja-school-intermediate-148', 'ja', 'intermediate', 'school', '推薦', 'すいせん', 'suisen', 'recommendation, endorsement', '推荐，推荐信', '先生に推薦をもらいました。', 'I received a recommendation from the teacher.', '我拿到了老师的推荐。'),
  ('ja-school-intermediate-149', 'ja', 'intermediate', 'school', '内申', 'ないしん', 'naishin', 'school report, internal evaluation', '内申，在校评价', '内申点を上げたいです。', 'I want to raise my internal evaluation score.', '我想提高内申分。'),
  ('ja-school-intermediate-150', 'ja', 'intermediate', 'school', '偏差値', 'へんさち', 'hensachi', 'deviation score, academic rank', '偏差值，学力排名', '偏差値が高い大学を目指します。', 'I aim for a university with a high deviation score.', '我的目标是偏差值高的大学。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
