-- Expand ja-numbers-basic to 150 curated entries (16-150)
-- Topic: numbers, counting, and quantifier vocabulary for basic Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-numbers-basic-16', 'ja', 'basic', 'numbers', '一', 'いち', 'ichi', 'one, 1', '一, 1', '一から始めましょう。', 'Let''s start from one.', '从一开始吧。'),
  ('ja-numbers-basic-17', 'ja', 'basic', 'numbers', '二', 'に', 'ni', 'two, 2', '二, 2', '二つ目の駅で降ります。', 'I''ll get off at the second station.', '在第二个站下车。'),
  ('ja-numbers-basic-18', 'ja', 'basic', 'numbers', '三', 'さん', 'san', 'three, 3', '三, 3', '三人で行きます。', 'Three of us will go.', '三个人去。'),
  ('ja-numbers-basic-19', 'ja', 'basic', 'numbers', '四', 'し/よん', 'shi/yon', 'four, 4', '四, 4', '四時に会いましょう。', 'Let''s meet at four o''clock.', '四点见吧。'),
  ('ja-numbers-basic-20', 'ja', 'basic', 'numbers', '五', 'ご', 'go', 'five, 5', '五, 5', '五分待ってください。', 'Please wait five minutes.', '请等五分钟。'),
  ('ja-numbers-basic-21', 'ja', 'basic', 'numbers', '六', 'ろく', 'roku', 'six, 6', '六, 6', '六時に起きます。', 'I wake up at six.', '我六点起床。'),
  ('ja-numbers-basic-22', 'ja', 'basic', 'numbers', '八', 'はち', 'hachi', 'eight, 8', '八, 8', '八月は暑いです。', 'August is hot.', '八月很热。'),
  ('ja-numbers-basic-23', 'ja', 'basic', 'numbers', '九', 'きゅう/く', 'kyuu/ku', 'nine, 9', '九, 9', '九時に寝ます。', 'I go to bed at nine.', '我九点睡觉。'),
  ('ja-numbers-basic-24', 'ja', 'basic', 'numbers', '二十', 'にじゅう', 'nijuu', 'twenty, 20', '二十, 20', '二十歳になりました。', 'I turned twenty.', '我满二十岁了。'),
  ('ja-numbers-basic-25', 'ja', 'basic', 'numbers', '三十', 'さんじゅう', 'sanjuu', 'thirty, 30', '三十, 30', '三十分かかります。', 'It takes thirty minutes.', '需要三十分钟。'),
  ('ja-numbers-basic-26', 'ja', 'basic', 'numbers', '四十', 'よんじゅう', 'yonjuu', 'forty, 40', '四十, 40', '四十人います。', 'There are forty people.', '有四十个人。'),
  ('ja-numbers-basic-27', 'ja', 'basic', 'numbers', '五十', 'ごじゅう', 'gojuu', 'fifty, 50', '五十, 50', '五十円です。', 'It''s fifty yen.', '五十日元。'),
  ('ja-numbers-basic-28', 'ja', 'basic', 'numbers', '六十', 'ろくじゅう', 'rokujuu', 'sixty, 60', '六十, 60', '六十分は一時間です。', 'Sixty minutes is one hour.', '六十分钟是一个小时。'),
  ('ja-numbers-basic-29', 'ja', 'basic', 'numbers', '七十', 'ななじゅう', 'nanajuu', 'seventy, 70', '七十, 70', '七十点でした。', 'It was seventy points.', '是七十分。'),
  ('ja-numbers-basic-30', 'ja', 'basic', 'numbers', '八十', 'はちじゅう', 'hachijuu', 'eighty, 80', '八十, 80', '八十パーセントです。', 'It''s eighty percent.', '百分之八十。'),
  ('ja-numbers-basic-31', 'ja', 'basic', 'numbers', '九十', 'きゅうじゅう', 'kyuujuu', 'ninety, 90', '九十, 90', '九十点を取りました。', 'I got ninety points.', '我得了九十分。'),
  ('ja-numbers-basic-32', 'ja', 'basic', 'numbers', '一個', 'いっこ', 'ikko', 'one (small object), 1 piece', '一个（小物品）, 1个', 'りんごを一個ください。', 'Please give me one apple.', '请给我一个苹果。'),
  ('ja-numbers-basic-33', 'ja', 'basic', 'numbers', '二個', 'にこ', 'niko', 'two (small objects), 2 pieces', '两个（小物品）, 2个', '卵を二個買いました。', 'I bought two eggs.', '我买了两个鸡蛋。'),
  ('ja-numbers-basic-34', 'ja', 'basic', 'numbers', '三個', 'さんこ', 'sanko', 'three (small objects), 3 pieces', '三个（小物品）, 3个', 'みかんが三個あります。', 'There are three tangerines.', '有三个橘子。'),
  ('ja-numbers-basic-35', 'ja', 'basic', 'numbers', '一人', 'ひとり', 'hitori', 'one person, alone', '一个人, 独自', '一人で住んでいます。', 'I live alone.', '我一个人住。'),
  ('ja-numbers-basic-36', 'ja', 'basic', 'numbers', '二人', 'ふたり', 'futari', 'two people, pair', '两个人, 一对', '二人で食べましょう。', 'Let''s eat together (two of us).', '我们两个人一起吃吧。'),
  ('ja-numbers-basic-37', 'ja', 'basic', 'numbers', '三人', 'さんにん', 'sannin', 'three people', '三个人', '三人家族です。', 'It''s a family of three.', '三口之家。'),
  ('ja-numbers-basic-38', 'ja', 'basic', 'numbers', '四人', 'よにん', 'yonin', 'four people', '四个人', '四人で遊びました。', 'Four of us hung out.', '四个人一起玩了。'),
  ('ja-numbers-basic-39', 'ja', 'basic', 'numbers', '五人', 'ごにん', 'gonin', 'five people', '五个人', '五人グループです。', 'It''s a group of five.', '五人一组。'),
  ('ja-numbers-basic-40', 'ja', 'basic', 'numbers', '一匹', 'いっぴき', 'ippiki', 'one (small animal)', '一只（小动物）', '猫が一匹います。', 'There is one cat.', '有一只猫。'),
  ('ja-numbers-basic-41', 'ja', 'basic', 'numbers', '二匹', 'にひき', 'nihiki', 'two (small animals)', '两只（小动物）', '犬が二匹います。', 'There are two dogs.', '有两只狗。'),
  ('ja-numbers-basic-42', 'ja', 'basic', 'numbers', '三匹', 'さんびき', 'sanbiki', 'three (small animals)', '三只（小动物）', '魚を三匹釣りました。', 'I caught three fish.', '钓了三条鱼。'),
  ('ja-numbers-basic-43', 'ja', 'basic', 'numbers', '一本', 'いっぽん', 'ippon', 'one (long object)', '一根/一瓶', '傘を一本持っています。', 'I have one umbrella.', '我有一把伞。'),
  ('ja-numbers-basic-44', 'ja', 'basic', 'numbers', '二本', 'にほん', 'nihon', 'two (long objects)', '两根/两瓶', 'ペンが二本あります。', 'There are two pens.', '有两支笔。'),
  ('ja-numbers-basic-45', 'ja', 'basic', 'numbers', '三本', 'さんぼん', 'sanbon', 'three (long objects)', '三根/三瓶', '水を三本買いました。', 'I bought three bottles of water.', '我买了三瓶水。'),
  ('ja-numbers-basic-46', 'ja', 'basic', 'numbers', '一枚', 'いちまい', 'ichimai', 'one (flat object), one sheet', '一张/一片', '紙を一枚ください。', 'Please give me one sheet of paper.', '请给我一张纸。'),
  ('ja-numbers-basic-47', 'ja', 'basic', 'numbers', '二枚', 'にまい', 'nimai', 'two (flat objects), two sheets', '两张/两片', '写真が二枚あります。', 'There are two photos.', '有两张照片。'),
  ('ja-numbers-basic-48', 'ja', 'basic', 'numbers', '三枚', 'さんまい', 'sanmai', 'three (flat objects), three sheets', '三张/三片', '切符を三枚買いました。', 'I bought three tickets.', '我买了三张票。'),
  ('ja-numbers-basic-49', 'ja', 'basic', 'numbers', '一台', 'いちだい', 'ichidai', 'one (machine/vehicle)', '一台（机器/车辆）', '車が一台あります。', 'There is one car.', '有一辆车。'),
  ('ja-numbers-basic-50', 'ja', 'basic', 'numbers', '二台', 'にだい', 'nidai', 'two (machines/vehicles)', '两台（机器/车辆）', 'パソコンが二台あります。', 'There are two computers.', '有两台电脑。'),
  ('ja-numbers-basic-51', 'ja', 'basic', 'numbers', '一冊', 'いっさつ', 'issatsu', 'one (book/volume)', '一本（书）', '本を一冊読みました。', 'I read one book.', '我读了一本书。'),
  ('ja-numbers-basic-52', 'ja', 'basic', 'numbers', '二冊', 'にさつ', 'nisatsu', 'two (books/volumes)', '两本（书）', '辞書が二冊あります。', 'There are two dictionaries.', '有两本词典。'),
  ('ja-numbers-basic-53', 'ja', 'basic', 'numbers', '三冊', 'さんさつ', 'sansatsu', 'three (books/volumes)', '三本（书）', '漫画を三冊買いました。', 'I bought three manga.', '我买了三本漫画。'),
  ('ja-numbers-basic-54', 'ja', 'basic', 'numbers', '一杯', 'いっぱい', 'ippai', 'one cup/glass, full', '一杯, 满', 'コーヒーを一杯飲みます。', 'I''ll drink one cup of coffee.', '我喝一杯咖啡。'),
  ('ja-numbers-basic-55', 'ja', 'basic', 'numbers', '二杯', 'にはい', 'nihai', 'two cups/glasses', '两杯', 'ビールを二杯ください。', 'Two beers please.', '请给我两杯啤酒。'),
  ('ja-numbers-basic-56', 'ja', 'basic', 'numbers', '一階', 'いっかい', 'ikkai', 'first floor, ground floor', '一楼, 一层', 'トイレは一階です。', 'The toilet is on the first floor.', '卫生间在一楼。'),
  ('ja-numbers-basic-57', 'ja', 'basic', 'numbers', '二階', 'にかい', 'nikai', 'second floor', '二楼, 二层', '部屋は二階にあります。', 'The room is on the second floor.', '房间在二楼。'),
  ('ja-numbers-basic-58', 'ja', 'basic', 'numbers', '三階', 'さんがい', 'sangai', 'third floor', '三楼, 三层', 'レストランは三階です。', 'The restaurant is on the third floor.', '餐厅在三楼。'),
  ('ja-numbers-basic-59', 'ja', 'basic', 'numbers', '一回', 'いっかい', 'ikkai', 'one time, once', '一次, 一回', '一回だけ行きました。', 'I went only once.', '只去了一次。'),
  ('ja-numbers-basic-60', 'ja', 'basic', 'numbers', '二回', 'にかい', 'nikai', 'two times, twice', '两次, 两回', '二回見ました。', 'I watched it twice.', '看了两次。'),
  ('ja-numbers-basic-61', 'ja', 'basic', 'numbers', '一番', 'いちばん', 'ichiban', 'number one, the most', '第一, 最', '一番好きな食べ物は何ですか。', 'What is your favorite food?', '你最喜欢的食物是什么？'),
  ('ja-numbers-basic-62', 'ja', 'basic', 'numbers', '二番', 'にばん', 'niban', 'number two, second', '第二, 二号', '二番のバスに乗ります。', 'I''ll take bus number two.', '我坐二号公交车。'),
  ('ja-numbers-basic-63', 'ja', 'basic', 'numbers', '一番目', 'いちばんめ', 'ichibanme', 'first (ordinal)', '第一个', '一番目の問題は簡単です。', 'The first question is easy.', '第一个问题很简单。'),
  ('ja-numbers-basic-64', 'ja', 'basic', 'numbers', '二番目', 'にばんめ', 'nibanme', 'second (ordinal)', '第二个', '二番目の駅で降ります。', 'I''ll get off at the second station.', '在第二个站下车。'),
  ('ja-numbers-basic-65', 'ja', 'basic', 'numbers', '三番目', 'さんばんめ', 'sanbanme', 'third (ordinal)', '第三个', '三番目の子どもです。', 'I''m the third child.', '我是第三个孩子。'),
  ('ja-numbers-basic-66', 'ja', 'basic', 'numbers', '一歳', 'いっさい', 'issai', 'one year old', '一岁', '赤ちゃんは一歳です。', 'The baby is one year old.', '宝宝一岁了。'),
  ('ja-numbers-basic-67', 'ja', 'basic', 'numbers', '二十歳', 'はたち', 'hatachi', 'twenty years old', '二十岁', '二十歳になりました。', 'I turned twenty years old.', '我二十岁了。'),
  ('ja-numbers-basic-68', 'ja', 'basic', 'numbers', '何歳', 'なんさい', 'nansai', 'how old', '几岁', '何歳ですか。', 'How old are you?', '你几岁了？'),
  ('ja-numbers-basic-69', 'ja', 'basic', 'numbers', '一時', 'いちじ', 'ichiji', 'one o''clock', '一点钟', '一時に会いましょう。', 'Let''s meet at one o''clock.', '一点见吧。'),
  ('ja-numbers-basic-70', 'ja', 'basic', 'numbers', '二時', 'にじ', 'niji', 'two o''clock', '两点钟', '二時に帰ります。', 'I''ll go home at two.', '我两点回去。'),
  ('ja-numbers-basic-71', 'ja', 'basic', 'numbers', '三時', 'さんじ', 'sanji', 'three o''clock', '三点钟', '三時におやつを食べます。', 'I eat a snack at three.', '三点吃点心。'),
  ('ja-numbers-basic-72', 'ja', 'basic', 'numbers', '四時', 'よじ', 'yoji', 'four o''clock', '四点钟', '四時に終わります。', 'It ends at four.', '四点结束。'),
  ('ja-numbers-basic-73', 'ja', 'basic', 'numbers', '五時', 'ごじ', 'goji', 'five o''clock', '五点钟', '五時に帰ります。', 'I go home at five.', '五点回家。'),
  ('ja-numbers-basic-74', 'ja', 'basic', 'numbers', '六時', 'ろくじ', 'rokuji', 'six o''clock', '六点钟', '六時に起きます。', 'I wake up at six.', '我六点起床。'),
  ('ja-numbers-basic-75', 'ja', 'basic', 'numbers', '七時', 'しちじ', 'shichiji', 'seven o''clock', '七点钟', '七時に朝ごはんを食べます。', 'I eat breakfast at seven.', '我七点吃早饭。'),
  ('ja-numbers-basic-76', 'ja', 'basic', 'numbers', '八時', 'はちじ', 'hachiji', 'eight o''clock', '八点钟', '八時に学校に行きます。', 'I go to school at eight.', '我八点去学校。'),
  ('ja-numbers-basic-77', 'ja', 'basic', 'numbers', '九時', 'くじ', 'kuji', 'nine o''clock', '九点钟', '九時に寝ます。', 'I go to bed at nine.', '我九点睡觉。'),
  ('ja-numbers-basic-78', 'ja', 'basic', 'numbers', '十時', 'じゅうじ', 'juuji', 'ten o''clock', '十点钟', '十時に届きます。', 'It will arrive at ten.', '十点到。'),
  ('ja-numbers-basic-79', 'ja', 'basic', 'numbers', '十一時', 'じゅういちじ', 'juuichiji', 'eleven o''clock', '十一点钟', '十一時に昼ごはんです。', 'Lunch is at eleven.', '十一点吃午饭。'),
  ('ja-numbers-basic-80', 'ja', 'basic', 'numbers', '十二時', 'じゅうにじ', 'juuniji', 'twelve o''clock', '十二点钟', '十二時にお昼休みです。', 'Lunch break is at twelve.', '十二点午休。'),
  ('ja-numbers-basic-81', 'ja', 'basic', 'numbers', '一分', 'いっぷん', 'ippun', 'one minute', '一分钟', '一分待ってください。', 'Please wait one minute.', '请等一分钟。'),
  ('ja-numbers-basic-82', 'ja', 'basic', 'numbers', '五分', 'ごふん', 'gofun', 'five minutes', '五分钟', '五分で着きます。', 'I''ll arrive in five minutes.', '五分钟就到。'),
  ('ja-numbers-basic-83', 'ja', 'basic', 'numbers', '十分', 'じゅっぷん', 'juppun', 'ten minutes', '十分钟', '十分遅れます。', 'I''ll be ten minutes late.', '我会迟到十分钟。'),
  ('ja-numbers-basic-84', 'ja', 'basic', 'numbers', '一秒', 'いちびょう', 'ichibyou', 'one second', '一秒', '一秒も無駄にしません。', 'I won''t waste even one second.', '一秒都不浪费。'),
  ('ja-numbers-basic-85', 'ja', 'basic', 'numbers', '一時間', 'いちじかん', 'ichijikan', 'one hour', '一个小时', '一時間かかります。', 'It takes one hour.', '需要一个小时。'),
  ('ja-numbers-basic-86', 'ja', 'basic', 'numbers', '二時間', 'にじかん', 'nijikan', 'two hours', '两个小时', '二時間勉強しました。', 'I studied for two hours.', '学习了两个小时。'),
  ('ja-numbers-basic-87', 'ja', 'basic', 'numbers', '半', 'はん', 'han', 'half, half past', '半, 半点', '三時半に会いましょう。', 'Let''s meet at three thirty.', '三点半见吧。'),
  ('ja-numbers-basic-88', 'ja', 'basic', 'numbers', '一月', 'いちがつ', 'ichigatsu', 'January', '一月', '一月は寒いです。', 'January is cold.', '一月很冷。'),
  ('ja-numbers-basic-89', 'ja', 'basic', 'numbers', '二月', 'にがつ', 'nigatsu', 'February', '二月', '二月は短いです。', 'February is short.', '二月很短。'),
  ('ja-numbers-basic-90', 'ja', 'basic', 'numbers', '三月', 'さんがつ', 'sangatsu', 'March', '三月', '三月に卒業します。', 'I graduate in March.', '三月毕业。'),
  ('ja-numbers-basic-91', 'ja', 'basic', 'numbers', '四月', 'しがつ', 'shigatsu', 'April', '四月', '四月に入学します。', 'I enter school in April.', '四月入学。'),
  ('ja-numbers-basic-92', 'ja', 'basic', 'numbers', '五月', 'ごがつ', 'gogatsu', 'May', '五月', '五月は気持ちいいです。', 'May is pleasant.', '五月很舒服。'),
  ('ja-numbers-basic-93', 'ja', 'basic', 'numbers', '六月', 'ろくがつ', 'rokugatsu', 'June', '六月', '六月は雨が多いです。', 'June has a lot of rain.', '六月雨多。'),
  ('ja-numbers-basic-94', 'ja', 'basic', 'numbers', '七月', 'しちがつ', 'shichigatsu', 'July', '七月', '七月は暑いです。', 'July is hot.', '七月很热。'),
  ('ja-numbers-basic-95', 'ja', 'basic', 'numbers', '八月', 'はちがつ', 'hachigatsu', 'August', '八月', '八月に旅行します。', 'I travel in August.', '八月去旅行。'),
  ('ja-numbers-basic-96', 'ja', 'basic', 'numbers', '九月', 'くがつ', 'kugatsu', 'September', '九月', '九月から学校が始まります。', 'School starts in September.', '九月开学。'),
  ('ja-numbers-basic-97', 'ja', 'basic', 'numbers', '十月', 'じゅうがつ', 'juugatsu', 'October', '十月', '十月は涼しいです。', 'October is cool.', '十月很凉爽。'),
  ('ja-numbers-basic-98', 'ja', 'basic', 'numbers', '十一月', 'じゅういちがつ', 'juuichigatsu', 'November', '十一月', '十一月に紅葉を見ます。', 'I see autumn leaves in November.', '十一月看红叶。'),
  ('ja-numbers-basic-99', 'ja', 'basic', 'numbers', '十二月', 'じゅうにがつ', 'juunigatsu', 'December', '十二月', '十二月はクリスマスです。', 'December is Christmas.', '十二月是圣诞节。'),
  ('ja-numbers-basic-100', 'ja', 'basic', 'numbers', '一日', 'ついたち', 'tsuitachi', 'first day (of month)', '一号, 一日', '一日に届きます。', 'It will arrive on the first.', '一号到。'),
  ('ja-numbers-basic-101', 'ja', 'basic', 'numbers', '二日', 'ふつか', 'futsuka', 'second day, two days', '二号, 两天', '二日間休みます。', 'I''ll rest for two days.', '休息两天。'),
  ('ja-numbers-basic-102', 'ja', 'basic', 'numbers', '三日', 'みっか', 'mikka', 'third day, three days', '三号, 三天', '三日かかります。', 'It takes three days.', '需要三天。'),
  ('ja-numbers-basic-103', 'ja', 'basic', 'numbers', '四日', 'よっか', 'yokka', 'fourth day, four days', '四号, 四天', '四日に会議があります。', 'There is a meeting on the fourth.', '四号有会议。'),
  ('ja-numbers-basic-104', 'ja', 'basic', 'numbers', '五日', 'いつか', 'itsuka', 'fifth day, five days', '五号, 五天', '五日に届きます。', 'It will arrive on the fifth.', '五号到。'),
  ('ja-numbers-basic-105', 'ja', 'basic', 'numbers', '六日', 'むいか', 'muika', 'sixth day, six days', '六号, 六天', '六日から旅行です。', 'The trip starts on the sixth.', '六号开始旅行。'),
  ('ja-numbers-basic-106', 'ja', 'basic', 'numbers', '七日', 'なのか', 'nanoka', 'seventh day, seven days', '七号, 七天', '一週間は七日です。', 'One week is seven days.', '一周是七天。'),
  ('ja-numbers-basic-107', 'ja', 'basic', 'numbers', '八日', 'ようか', 'youka', 'eighth day, eight days', '八号, 八天', '八日に出発します。', 'I depart on the eighth.', '八号出发。'),
  ('ja-numbers-basic-108', 'ja', 'basic', 'numbers', '九日', 'ここのか', 'kokonoka', 'ninth day, nine days', '九号, 九天', '九日に届きます。', 'It will arrive on the ninth.', '九号到。'),
  ('ja-numbers-basic-109', 'ja', 'basic', 'numbers', '十日', 'とおか', 'tooka', 'tenth day, ten days', '十号, 十天', '十日間日本にいます。', 'I''ll be in Japan for ten days.', '在日本待十天。'),
  ('ja-numbers-basic-110', 'ja', 'basic', 'numbers', '二十日', 'はつか', 'hatsuka', 'twentieth day, twenty days', '二十号, 二十天', '二十日に締め切りです。', 'The deadline is on the twentieth.', '二十号截止。'),
  ('ja-numbers-basic-111', 'ja', 'basic', 'numbers', '一年', 'いちねん', 'ichinen', 'one year', '一年', '日本に一年住みました。', 'I lived in Japan for one year.', '在日本住了一年。'),
  ('ja-numbers-basic-112', 'ja', 'basic', 'numbers', '月曜日', 'げつようび', 'getsuyoubi', 'Monday', '星期一', '月曜日は忙しいです。', 'Monday is busy.', '星期一很忙。'),
  ('ja-numbers-basic-113', 'ja', 'basic', 'numbers', '火曜日', 'かようび', 'kayoubi', 'Tuesday', '星期二', '火曜日にテストがあります。', 'There is a test on Tuesday.', '星期二有考试。'),
  ('ja-numbers-basic-114', 'ja', 'basic', 'numbers', '水曜日', 'すいようび', 'suiyoubi', 'Wednesday', '星期三', '水曜日は休みです。', 'Wednesday is a day off.', '星期三休息。'),
  ('ja-numbers-basic-115', 'ja', 'basic', 'numbers', '木曜日', 'もくようび', 'mokuyoubi', 'Thursday', '星期四', '木曜日に映画を見ます。', 'I watch a movie on Thursday.', '星期四看电影。'),
  ('ja-numbers-basic-116', 'ja', 'basic', 'numbers', '金曜日', 'きんようび', 'kinyoubi', 'Friday', '星期五', '金曜日が好きです。', 'I like Friday.', '我喜欢星期五。'),
  ('ja-numbers-basic-117', 'ja', 'basic', 'numbers', '土曜日', 'どようび', 'doyoubi', 'Saturday', '星期六', '土曜日に買い物をします。', 'I go shopping on Saturday.', '星期六购物。'),
  ('ja-numbers-basic-118', 'ja', 'basic', 'numbers', '日曜日', 'にちようび', 'nichiyoubi', 'Sunday', '星期日', '日曜日はゆっくりします。', 'I relax on Sunday.', '星期日放松。'),
  ('ja-numbers-basic-119', 'ja', 'basic', 'numbers', '百円', 'ひゃくえん', 'hyakuen', 'one hundred yen, 100 yen', '一百日元, 100日元', 'これは百円です。', 'This is one hundred yen.', '这是一百日元。'),
  ('ja-numbers-basic-120', 'ja', 'basic', 'numbers', '千円', 'せんえん', 'sen''en', 'one thousand yen, 1000 yen', '一千日元, 1000日元', '千円札がありますか。', 'Do you have a thousand yen bill?', '有一千日元纸币吗？'),
  ('ja-numbers-basic-121', 'ja', 'basic', 'numbers', '一万円', 'いちまんえん', 'ichiman''en', 'ten thousand yen, 10000 yen', '一万日元, 10000日元', '一万円は高いです。', 'Ten thousand yen is expensive.', '一万日元很贵。'),
  ('ja-numbers-basic-122', 'ja', 'basic', 'numbers', '何時', 'なんじ', 'nanji', 'what time', '几点', '今何時ですか。', 'What time is it now?', '现在几点了？'),
  ('ja-numbers-basic-123', 'ja', 'basic', 'numbers', '何分', 'なんぷん', 'nanpun', 'how many minutes', '几分钟', '何分かかりますか。', 'How many minutes does it take?', '需要几分钟？'),
  ('ja-numbers-basic-124', 'ja', 'basic', 'numbers', '何日', 'なんにち', 'nannichi', 'what day (of month), how many days', '几号, 几天', '今日は何日ですか。', 'What day of the month is it today?', '今天几号？'),
  ('ja-numbers-basic-125', 'ja', 'basic', 'numbers', '何月', 'なんがつ', 'nangatsu', 'what month', '几月', '誕生日は何月ですか。', 'What month is your birthday?', '你生日是几月？'),
  ('ja-numbers-basic-126', 'ja', 'basic', 'numbers', '何年', 'なんねん', 'nannen', 'what year, how many years', '哪年, 几年', '何年生まれですか。', 'What year were you born?', '你是哪年出生的？'),
  ('ja-numbers-basic-127', 'ja', 'basic', 'numbers', '何人', 'なんにん', 'nannin', 'how many people', '几个人', '何人家族ですか。', 'How many people are in your family?', '你家有几口人？'),
  ('ja-numbers-basic-128', 'ja', 'basic', 'numbers', '何個', 'なんこ', 'nanko', 'how many (small objects)', '几个', '何個要りますか。', 'How many do you need?', '需要几个？'),
  ('ja-numbers-basic-129', 'ja', 'basic', 'numbers', '全部', 'ぜんぶ', 'zenbu', 'all, everything, total', '全部, 所有', '全部で千円です。', 'The total is one thousand yen.', '一共一千日元。'),
  ('ja-numbers-basic-130', 'ja', 'basic', 'numbers', '半分', 'はんぶん', 'hanbun', 'half, half portion', '一半, 半份', '半分に分けましょう。', 'Let''s split it in half.', '分一半吧。'),
  ('ja-numbers-basic-131', 'ja', 'basic', 'numbers', '少し', 'すこし', 'sukoshi', 'a little, a few', '一点, 少量', '少し休みましょう。', 'Let''s rest a little.', '稍微休息一下吧。'),
  ('ja-numbers-basic-132', 'ja', 'basic', 'numbers', 'たくさん', 'たくさん', 'takusan', 'many, a lot, much', '很多, 大量', 'たくさん食べました。', 'I ate a lot.', '吃了很多。'),
  ('ja-numbers-basic-133', 'ja', 'basic', 'numbers', '足す', 'たす', 'tasu', 'to add, plus', '加, 加上', '二足す三は五です。', 'Two plus three is five.', '二加三等于五。'),
  ('ja-numbers-basic-134', 'ja', 'basic', 'numbers', '引く', 'ひく', 'hiku', 'to subtract, minus', '减, 减去', '十引く三は七です。', 'Ten minus three is seven.', '十减三等于七。'),
  ('ja-numbers-basic-135', 'ja', 'basic', 'numbers', '掛ける', 'かける', 'kakeru', 'to multiply, times', '乘, 乘以', '三掛ける四は十二です。', 'Three times four is twelve.', '三乘四等于十二。'),
  ('ja-numbers-basic-136', 'ja', 'basic', 'numbers', '割る', 'わる', 'waru', 'to divide, divided by', '除, 除以', '十割る二は五です。', 'Ten divided by two is five.', '十除以二等于五。'),
  ('ja-numbers-basic-137', 'ja', 'basic', 'numbers', '番号', 'ばんごう', 'bangou', 'number (assigned), ID number', '号码, 编号', '電話番号を教えてください。', 'Please tell me your phone number.', '请告诉我你的电话号码。'),
  ('ja-numbers-basic-138', 'ja', 'basic', 'numbers', '数', 'かず', 'kazu', 'number, quantity, count', '数量, 数目', '人の数が多いです。', 'The number of people is large.', '人数很多。'),
  ('ja-numbers-basic-139', 'ja', 'basic', 'numbers', '数える', 'かぞえる', 'kazoeru', 'to count', '数, 计数', '十まで数えてください。', 'Please count to ten.', '请数到十。'),
  ('ja-numbers-basic-140', 'ja', 'basic', 'numbers', '最初', 'さいしょ', 'saisho', 'first, beginning', '最初, 开始', '最初は難しかったです。', 'It was difficult at first.', '一开始很难。'),
  ('ja-numbers-basic-141', 'ja', 'basic', 'numbers', '最後', 'さいご', 'saigo', 'last, final', '最后, 最终', '最後の問題です。', 'This is the last question.', '这是最后一个问题。'),
  ('ja-numbers-basic-142', 'ja', 'basic', 'numbers', '次', 'つぎ', 'tsugi', 'next, following', '下一个, 接下来', '次は何ですか。', 'What''s next?', '接下来是什么？'),
  ('ja-numbers-basic-143', 'ja', 'basic', 'numbers', '前', 'まえ', 'mae', 'before, in front, ago', '前, 以前', '三日前に来ました。', 'I came three days ago.', '三天前来的。'),
  ('ja-numbers-basic-144', 'ja', 'basic', 'numbers', '後', 'あと', 'ato', 'after, later, remaining', '后, 之后, 剩余', 'あと五分です。', 'Five more minutes.', '还有五分钟。'),
  ('ja-numbers-basic-145', 'ja', 'basic', 'numbers', '毎日', 'まいにち', 'mainichi', 'every day, daily', '每天, 每日', '毎日勉強します。', 'I study every day.', '每天学习。'),
  ('ja-numbers-basic-146', 'ja', 'basic', 'numbers', '毎週', 'まいしゅう', 'maishuu', 'every week, weekly', '每周, 每星期', '毎週テストがあります。', 'There is a test every week.', '每周有考试。'),
  ('ja-numbers-basic-147', 'ja', 'basic', 'numbers', '毎月', 'まいつき', 'maitsuki', 'every month, monthly', '每月, 每个月', '毎月映画を見ます。', 'I watch a movie every month.', '每个月看电影。'),
  ('ja-numbers-basic-148', 'ja', 'basic', 'numbers', '毎年', 'まいとし', 'maitoshi', 'every year, annually', '每年', '毎年旅行します。', 'I travel every year.', '每年旅行。'),
  ('ja-numbers-basic-149', 'ja', 'basic', 'numbers', '何回', 'なんかい', 'nankai', 'how many times', '几次, 多少次', '何回行きましたか。', 'How many times have you been?', '去了几次？'),
  ('ja-numbers-basic-150', 'ja', 'basic', 'numbers', '何曜日', 'なんようび', 'nanyoubi', 'what day of the week', '星期几', '今日は何曜日ですか。', 'What day of the week is today?', '今天星期几？')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
