-- Expand ja-travel-basic to 150 curated entries (16-150)
-- Topic: travel vocabulary for basic Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-travel-basic-16', 'ja', 'basic', 'travel', '荷物', 'にもつ', 'nimotsu', 'luggage, baggage', '行李, 包裹', '荷物はどこですか。', 'Where is the luggage?', '行李在哪里？'),
  ('ja-travel-basic-17', 'ja', 'basic', 'travel', '予約', 'よやく', 'yoyaku', 'reservation, booking', '预约, 预订', '予約をしたいです。', 'I would like to make a reservation.', '我想预约。'),
  ('ja-travel-basic-18', 'ja', 'basic', 'travel', 'パスポート', 'ぱすぽーと', 'pasupooto', 'passport, travel document', '护照, 旅行证件', 'パスポートを見せてください。', 'Please show your passport.', '请出示护照。'),
  ('ja-travel-basic-19', 'ja', 'basic', 'travel', '時刻表', 'じこくひょう', 'jikokuhyou', 'timetable, schedule', '时刻表, 班次表', '時刻表を見ましょう。', 'Let us check the timetable.', '我们看看时刻表吧。'),
  ('ja-travel-basic-20', 'ja', 'basic', 'travel', '片道', 'かたみち', 'katamichi', 'one-way, single trip', '单程, 单趟', '片道切符をください。', 'A one-way ticket please.', '请给我一张单程票。'),
  ('ja-travel-basic-21', 'ja', 'basic', 'travel', '往復', 'おうふく', 'oufuku', 'round trip, return', '往返, 来回', '往復切符はいくらですか。', 'How much is a round-trip ticket?', '往返票多少钱？'),
  ('ja-travel-basic-22', 'ja', 'basic', 'travel', '乗り場', 'のりば', 'noriba', 'boarding area, platform', '乘车处, 站台', 'バスの乗り場はどこですか。', 'Where is the bus stop?', '公交车站在哪里？'),
  ('ja-travel-basic-23', 'ja', 'basic', 'travel', '改札', 'かいさつ', 'kaisatsu', 'ticket gate, barrier', '检票口, 闸口', '改札を通ってください。', 'Please go through the ticket gate.', '请通过检票口。'),
  ('ja-travel-basic-24', 'ja', 'basic', 'travel', 'ホーム', 'ほーむ', 'hoomu', 'platform, track', '站台, 月台', '三番ホームに行きます。', 'I am going to platform three.', '我去三号站台。'),
  ('ja-travel-basic-25', 'ja', 'basic', 'travel', '乗り換え', 'のりかえ', 'norikae', 'transfer, change trains', '换乘, 转车', '東京で乗り換えます。', 'I will transfer at Tokyo.', '我在东京换乘。'),
  ('ja-travel-basic-26', 'ja', 'basic', 'travel', '運賃', 'うんちん', 'unchin', 'fare, ticket price', '车费, 票价', '運賃はいくらですか。', 'How much is the fare?', '车费多少钱？'),
  ('ja-travel-basic-27', 'ja', 'basic', 'travel', '案内', 'あんない', 'annai', 'guide, information', '指南, 引导', '案内所はどこですか。', 'Where is the information desk?', '咨询处在哪里？'),
  ('ja-travel-basic-28', 'ja', 'basic', 'travel', '観光', 'かんこう', 'kankou', 'sightseeing, tourism', '观光, 旅游', '観光で来ました。', 'I came for sightseeing.', '我来观光的。'),
  ('ja-travel-basic-29', 'ja', 'basic', 'travel', '旅行', 'りょこう', 'ryokou', 'travel, trip', '旅行, 旅途', '日本を旅行しています。', 'I am traveling in Japan.', '我在日本旅行。'),
  ('ja-travel-basic-30', 'ja', 'basic', 'travel', '出発', 'しゅっぱつ', 'shuppatsu', 'departure, leaving', '出发, 启程', '出発は何時ですか。', 'What time is the departure?', '几点出发？'),
  ('ja-travel-basic-31', 'ja', 'basic', 'travel', '到着', 'とうちゃく', 'touchaku', 'arrival, reaching', '到达, 抵达', '到着は十時です。', 'The arrival is at ten o clock.', '十点到达。'),
  ('ja-travel-basic-32', 'ja', 'basic', 'travel', '遅れる', 'おくれる', 'okureru', 'to be late, to be delayed', '迟到, 晚点', '電車が遅れています。', 'The train is delayed.', '电车晚点了。'),
  ('ja-travel-basic-33', 'ja', 'basic', 'travel', '乗る', 'のる', 'noru', 'to ride, to board', '乘坐, 搭乘', '電車に乗ります。', 'I will board the train.', '我坐电车。'),
  ('ja-travel-basic-34', 'ja', 'basic', 'travel', '降りる', 'おりる', 'oriru', 'to get off, to disembark', '下车, 下来', '次の駅で降ります。', 'I will get off at the next station.', '我在下一站下车。'),
  ('ja-travel-basic-35', 'ja', 'basic', 'travel', '待つ', 'まつ', 'matsu', 'to wait, to await', '等待, 等候', 'ここで待ってください。', 'Please wait here.', '请在这里等。'),
  ('ja-travel-basic-36', 'ja', 'basic', 'travel', '歩く', 'あるく', 'aruku', 'to walk, to go on foot', '走路, 步行', '駅まで歩きます。', 'I will walk to the station.', '我步行去车站。'),
  ('ja-travel-basic-37', 'ja', 'basic', 'travel', '曲がる', 'まがる', 'magaru', 'to turn, to curve', '转弯, 拐弯', '右に曲がってください。', 'Please turn right.', '请向右转。'),
  ('ja-travel-basic-38', 'ja', 'basic', 'travel', '渡る', 'わたる', 'wataru', 'to cross, to go across', '过, 横穿', '橋を渡ります。', 'I will cross the bridge.', '我过桥。'),
  ('ja-travel-basic-39', 'ja', 'basic', 'travel', '止まる', 'とまる', 'tomaru', 'to stop, to halt', '停止, 停下', 'バスが止まりました。', 'The bus stopped.', '公交车停了。'),
  ('ja-travel-basic-40', 'ja', 'basic', 'travel', '泊まる', 'とまる', 'tomaru', 'to stay overnight, to lodge', '住宿, 留宿', 'ホテルに泊まります。', 'I will stay at a hotel.', '我住酒店。'),
  ('ja-travel-basic-41', 'ja', 'basic', 'travel', '着く', 'つく', 'tsuku', 'to arrive, to reach', '到达, 抵达', '空港に着きました。', 'I arrived at the airport.', '我到了机场。'),
  ('ja-travel-basic-42', 'ja', 'basic', 'travel', '帰る', 'かえる', 'kaeru', 'to return, to go back', '回去, 返回', '明日帰ります。', 'I will return tomorrow.', '我明天回去。'),
  ('ja-travel-basic-43', 'ja', 'basic', 'travel', '北', 'きた', 'kita', 'north, northern', '北, 北方', '北に行ってください。', 'Please go north.', '请往北走。'),
  ('ja-travel-basic-44', 'ja', 'basic', 'travel', '南', 'みなみ', 'minami', 'south, southern', '南, 南方', '南口はどこですか。', 'Where is the south exit?', '南出口在哪里？'),
  ('ja-travel-basic-45', 'ja', 'basic', 'travel', '東', 'ひがし', 'higashi', 'east, eastern', '东, 东方', '東に進んでください。', 'Please go east.', '请往东走。'),
  ('ja-travel-basic-46', 'ja', 'basic', 'travel', '西', 'にし', 'nishi', 'west, western', '西, 西方', '西口で待っています。', 'I am waiting at the west exit.', '我在西出口等着。'),
  ('ja-travel-basic-47', 'ja', 'basic', 'travel', 'まっすぐ', 'まっすぐ', 'massugu', 'straight ahead, directly', '一直, 笔直', 'まっすぐ行ってください。', 'Please go straight ahead.', '请一直走。'),
  ('ja-travel-basic-48', 'ja', 'basic', 'travel', '近い', 'ちかい', 'chikai', 'near, close', '近, 附近', '駅は近いですか。', 'Is the station nearby?', '车站近吗？'),
  ('ja-travel-basic-49', 'ja', 'basic', 'travel', '遠い', 'とおい', 'tooi', 'far, distant', '远, 遥远', '空港は遠いです。', 'The airport is far.', '机场很远。'),
  ('ja-travel-basic-50', 'ja', 'basic', 'travel', '前', 'まえ', 'mae', 'front, before', '前面, 之前', '駅の前にいます。', 'I am in front of the station.', '我在车站前面。'),
  ('ja-travel-basic-51', 'ja', 'basic', 'travel', '後ろ', 'うしろ', 'ushiro', 'behind, back', '后面, 背后', 'ホテルの後ろに公園があります。', 'There is a park behind the hotel.', '酒店后面有公园。'),
  ('ja-travel-basic-52', 'ja', 'basic', 'travel', '隣', 'となり', 'tonari', 'next to, neighboring', '旁边, 隔壁', 'コンビニの隣です。', 'It is next to the convenience store.', '在便利店旁边。'),
  ('ja-travel-basic-53', 'ja', 'basic', 'travel', '向こう', 'むこう', 'mukou', 'over there, opposite side', '对面, 那边', '向こうにレストランがあります。', 'There is a restaurant over there.', '对面有餐厅。'),
  ('ja-travel-basic-54', 'ja', 'basic', 'travel', '角', 'かど', 'kado', 'corner, intersection', '拐角, 角落', '角を左に曲がってください。', 'Please turn left at the corner.', '请在拐角处左转。'),
  ('ja-travel-basic-55', 'ja', 'basic', 'travel', '交差点', 'こうさてん', 'kousaten', 'intersection, crossroads', '十字路口, 交叉路口', '交差点を渡ります。', 'I will cross the intersection.', '我过十字路口。'),
  ('ja-travel-basic-56', 'ja', 'basic', 'travel', '信号', 'しんごう', 'shingou', 'traffic light, signal', '信号灯, 红绿灯', '信号が赤です。', 'The traffic light is red.', '信号灯是红色的。'),
  ('ja-travel-basic-57', 'ja', 'basic', 'travel', '橋', 'はし', 'hashi', 'bridge, overpass', '桥, 天桥', '橋を渡ってください。', 'Please cross the bridge.', '请过桥。'),
  ('ja-travel-basic-58', 'ja', 'basic', 'travel', '坂', 'さか', 'saka', 'slope, hill', '坡, 斜坡', 'この坂を上ります。', 'I will go up this hill.', '我爬这个坡。'),
  ('ja-travel-basic-59', 'ja', 'basic', 'travel', '通り', 'とおり', 'toori', 'street, avenue', '大街, 马路', 'この通りを歩きます。', 'I will walk along this street.', '我沿着这条街走。'),
  ('ja-travel-basic-60', 'ja', 'basic', 'travel', '部屋', 'へや', 'heya', 'room, chamber', '房间, 屋子', '部屋の鍵をください。', 'Please give me the room key.', '请给我房间钥匙。'),
  ('ja-travel-basic-61', 'ja', 'basic', 'travel', 'チェックイン', 'ちぇっくいん', 'chekkuin', 'check-in, registration', '入住, 登记', 'チェックインをお願いします。', 'I would like to check in please.', '我想办理入住。'),
  ('ja-travel-basic-62', 'ja', 'basic', 'travel', 'チェックアウト', 'ちぇっくあうと', 'chekkuauto', 'check-out, departure', '退房, 结账', 'チェックアウトは何時ですか。', 'What time is check-out?', '退房时间是几点？'),
  ('ja-travel-basic-63', 'ja', 'basic', 'travel', '鍵', 'かぎ', 'kagi', 'key, lock', '钥匙, 锁', '鍵を忘れました。', 'I forgot the key.', '我忘了钥匙。'),
  ('ja-travel-basic-64', 'ja', 'basic', 'travel', 'フロント', 'ふろんと', 'furonto', 'front desk, reception', '前台, 接待处', 'フロントに聞いてください。', 'Please ask at the front desk.', '请问前台。'),
  ('ja-travel-basic-65', 'ja', 'basic', 'travel', 'エレベーター', 'えれべーたー', 'erebeetaa', 'elevator, lift', '电梯, 升降机', 'エレベーターはどこですか。', 'Where is the elevator?', '电梯在哪里？'),
  ('ja-travel-basic-66', 'ja', 'basic', 'travel', '階段', 'かいだん', 'kaidan', 'stairs, staircase', '楼梯, 台阶', '階段を上がってください。', 'Please go up the stairs.', '请上楼梯。'),
  ('ja-travel-basic-67', 'ja', 'basic', 'travel', '両替', 'りょうがえ', 'ryougae', 'currency exchange, money change', '兑换, 换钱', '両替したいです。', 'I would like to exchange money.', '我想换钱。'),
  ('ja-travel-basic-68', 'ja', 'basic', 'travel', '現金', 'げんきん', 'genkin', 'cash, money', '现金, 现钞', '現金で払います。', 'I will pay with cash.', '我用现金付。'),
  ('ja-travel-basic-69', 'ja', 'basic', 'travel', 'カード', 'かーど', 'kaado', 'card, credit card', '卡, 信用卡', 'カードは使えますか。', 'Can I use a card?', '可以用卡吗？'),
  ('ja-travel-basic-70', 'ja', 'basic', 'travel', 'お土産', 'おみやげ', 'omiyage', 'souvenir, gift', '特产, 纪念品', 'お土産を買いたいです。', 'I want to buy souvenirs.', '我想买纪念品。'),
  ('ja-travel-basic-71', 'ja', 'basic', 'travel', '写真', 'しゃしん', 'shashin', 'photo, picture', '照片, 相片', '写真を撮ってください。', 'Please take a photo.', '请帮我拍照。'),
  ('ja-travel-basic-72', 'ja', 'basic', 'travel', '天気', 'てんき', 'tenki', 'weather, climate', '天气, 气候', '明日の天気はどうですか。', 'How is the weather tomorrow?', '明天天气怎么样？'),
  ('ja-travel-basic-73', 'ja', 'basic', 'travel', '雨', 'あめ', 'ame', 'rain, rainfall', '雨, 下雨', '雨が降っています。', 'It is raining.', '在下雨。'),
  ('ja-travel-basic-74', 'ja', 'basic', 'travel', '晴れ', 'はれ', 'hare', 'sunny, clear weather', '晴天, 晴朗', '今日は晴れです。', 'Today is sunny.', '今天是晴天。'),
  ('ja-travel-basic-75', 'ja', 'basic', 'travel', '暑い', 'あつい', 'atsui', 'hot, warm weather', '热, 炎热', '今日は暑いです。', 'Today is hot.', '今天很热。'),
  ('ja-travel-basic-76', 'ja', 'basic', 'travel', '寒い', 'さむい', 'samui', 'cold, chilly', '冷, 寒冷', '外は寒いです。', 'It is cold outside.', '外面很冷。'),
  ('ja-travel-basic-77', 'ja', 'basic', 'travel', '傘', 'かさ', 'kasa', 'umbrella, parasol', '伞, 雨伞', '傘を持っていますか。', 'Do you have an umbrella?', '你有伞吗？'),
  ('ja-travel-basic-78', 'ja', 'basic', 'travel', '朝', 'あさ', 'asa', 'morning, dawn', '早上, 早晨', '朝早く出発します。', 'I will depart early in the morning.', '我一早出发。'),
  ('ja-travel-basic-79', 'ja', 'basic', 'travel', '昼', 'ひる', 'hiru', 'noon, daytime', '中午, 白天', '昼にホテルに戻ります。', 'I will return to the hotel at noon.', '中午回酒店。'),
  ('ja-travel-basic-80', 'ja', 'basic', 'travel', '夜', 'よる', 'yoru', 'night, evening', '晚上, 夜晚', '夜は何をしますか。', 'What will you do at night?', '晚上做什么？'),
  ('ja-travel-basic-81', 'ja', 'basic', 'travel', '今日', 'きょう', 'kyou', 'today, this day', '今天, 本日', '今日はどこに行きますか。', 'Where are you going today?', '今天去哪里？'),
  ('ja-travel-basic-82', 'ja', 'basic', 'travel', '明日', 'あした', 'ashita', 'tomorrow, next day', '明天, 翌日', '明日は京都に行きます。', 'I will go to Kyoto tomorrow.', '明天去京都。'),
  ('ja-travel-basic-83', 'ja', 'basic', 'travel', '昨日', 'きのう', 'kinou', 'yesterday, previous day', '昨天, 前一天', '昨日は奈良に行きました。', 'I went to Nara yesterday.', '昨天去了奈良。'),
  ('ja-travel-basic-84', 'ja', 'basic', 'travel', '何時', 'なんじ', 'nanji', 'what time, when', '几点, 什么时候', '何時に出発しますか。', 'What time do we depart?', '几点出发？'),
  ('ja-travel-basic-85', 'ja', 'basic', 'travel', '分', 'ふん', 'fun', 'minute, minutes', '分钟, 分', '十分かかります。', 'It takes ten minutes.', '要十分钟。'),
  ('ja-travel-basic-86', 'ja', 'basic', 'travel', '時間', 'じかん', 'jikan', 'time, hours', '时间, 小时', '二時間かかります。', 'It takes two hours.', '要两个小时。'),
  ('ja-travel-basic-87', 'ja', 'basic', 'travel', '神社', 'じんじゃ', 'jinja', 'shrine, Shinto shrine', '神社, 神殿', '神社を見たいです。', 'I want to see a shrine.', '我想看神社。'),
  ('ja-travel-basic-88', 'ja', 'basic', 'travel', 'お寺', 'おてら', 'otera', 'temple, Buddhist temple', '寺庙, 佛寺', 'お寺に行きましょう。', 'Let us go to a temple.', '我们去寺庙吧。'),
  ('ja-travel-basic-89', 'ja', 'basic', 'travel', '城', 'しろ', 'shiro', 'castle, fortress', '城, 城堡', '大阪城はきれいです。', 'Osaka Castle is beautiful.', '大阪城很漂亮。'),
  ('ja-travel-basic-90', 'ja', 'basic', 'travel', '公園', 'こうえん', 'kouen', 'park, garden', '公园, 花园', '公園で休みましょう。', 'Let us rest in the park.', '我们在公园休息吧。'),
  ('ja-travel-basic-91', 'ja', 'basic', 'travel', '美術館', 'びじゅつかん', 'bijutsukan', 'art museum, gallery', '美术馆, 画廊', '美術館に行きたいです。', 'I want to go to an art museum.', '我想去美术馆。'),
  ('ja-travel-basic-92', 'ja', 'basic', 'travel', '博物館', 'はくぶつかん', 'hakubutsukan', 'museum, exhibition hall', '博物馆, 展览馆', '博物館は何時までですか。', 'Until what time is the museum open?', '博物馆开到几点？'),
  ('ja-travel-basic-93', 'ja', 'basic', 'travel', '温泉', 'おんせん', 'onsen', 'hot spring, spa', '温泉, 泡汤', '温泉に入りたいです。', 'I want to go to a hot spring.', '我想泡温泉。'),
  ('ja-travel-basic-94', 'ja', 'basic', 'travel', '海', 'うみ', 'umi', 'sea, ocean', '海, 大海', '海が見えます。', 'I can see the sea.', '可以看到海。'),
  ('ja-travel-basic-95', 'ja', 'basic', 'travel', '山', 'やま', 'yama', 'mountain, hill', '山, 大山', '山に登りたいです。', 'I want to climb a mountain.', '我想爬山。'),
  ('ja-travel-basic-96', 'ja', 'basic', 'travel', '川', 'かわ', 'kawa', 'river, stream', '河, 河流', '川がきれいです。', 'The river is beautiful.', '河很漂亮。'),
  ('ja-travel-basic-97', 'ja', 'basic', 'travel', '島', 'しま', 'shima', 'island, isle', '岛, 岛屿', '島に行きたいです。', 'I want to go to an island.', '我想去岛上。'),
  ('ja-travel-basic-98', 'ja', 'basic', 'travel', '店', 'みせ', 'mise', 'shop, store', '商店, 店铺', 'あの店に入りましょう。', 'Let us go into that shop.', '我们进那家店吧。'),
  ('ja-travel-basic-99', 'ja', 'basic', 'travel', 'コンビニ', 'こんびに', 'konbini', 'convenience store, corner shop', '便利店, 小卖部', 'コンビニはどこですか。', 'Where is the convenience store?', '便利店在哪里？'),
  ('ja-travel-basic-100', 'ja', 'basic', 'travel', 'レストラン', 'れすとらん', 'resutoran', 'restaurant, dining place', '餐厅, 饭店', 'レストランを探しています。', 'I am looking for a restaurant.', '我在找餐厅。'),
  ('ja-travel-basic-101', 'ja', 'basic', 'travel', 'トイレ', 'といれ', 'toire', 'toilet, restroom', '厕所, 卫生间', 'トイレはどこですか。', 'Where is the restroom?', '厕所在哪里？'),
  ('ja-travel-basic-102', 'ja', 'basic', 'travel', '病院', 'びょういん', 'byouin', 'hospital, clinic', '医院, 诊所', '近くに病院はありますか。', 'Is there a hospital nearby?', '附近有医院吗？'),
  ('ja-travel-basic-103', 'ja', 'basic', 'travel', '薬局', 'やっきょく', 'yakkyoku', 'pharmacy, drugstore', '药店, 药局', '薬局で薬を買います。', 'I will buy medicine at the pharmacy.', '我在药店买药。'),
  ('ja-travel-basic-104', 'ja', 'basic', 'travel', '銀行', 'ぎんこう', 'ginkou', 'bank, financial institution', '银行, 金融机构', '銀行はどこですか。', 'Where is the bank?', '银行在哪里？'),
  ('ja-travel-basic-105', 'ja', 'basic', 'travel', '郵便局', 'ゆうびんきょく', 'yuubinkyoku', 'post office, mail office', '邮局, 邮政局', '郵便局からハガキを送ります。', 'I will send a postcard from the post office.', '我从邮局寄明信片。'),
  ('ja-travel-basic-106', 'ja', 'basic', 'travel', 'デパート', 'でぱーと', 'depaato', 'department store, mall', '百货商店, 商场', 'デパートで買い物します。', 'I will shop at the department store.', '我在百货商店购物。'),
  ('ja-travel-basic-107', 'ja', 'basic', 'travel', '市場', 'いちば', 'ichiba', 'market, marketplace', '市场, 集市', '市場に行きましょう。', 'Let us go to the market.', '我们去市场吧。'),
  ('ja-travel-basic-108', 'ja', 'basic', 'travel', '食べる', 'たべる', 'taberu', 'to eat, to dine', '吃, 用餐', '何か食べたいです。', 'I want to eat something.', '我想吃点东西。'),
  ('ja-travel-basic-109', 'ja', 'basic', 'travel', '飲む', 'のむ', 'nomu', 'to drink, to have a beverage', '喝, 饮', '水を飲みたいです。', 'I want to drink water.', '我想喝水。'),
  ('ja-travel-basic-110', 'ja', 'basic', 'travel', '買う', 'かう', 'kau', 'to buy, to purchase', '买, 购买', 'お土産を買います。', 'I will buy souvenirs.', '我买纪念品。'),
  ('ja-travel-basic-111', 'ja', 'basic', 'travel', '見る', 'みる', 'miru', 'to see, to look', '看, 观看', '景色を見ましょう。', 'Let us see the scenery.', '我们看看风景吧。'),
  ('ja-travel-basic-112', 'ja', 'basic', 'travel', '聞く', 'きく', 'kiku', 'to ask, to listen', '问, 听', '道を聞きます。', 'I will ask for directions.', '我问路。'),
  ('ja-travel-basic-113', 'ja', 'basic', 'travel', '話す', 'はなす', 'hanasu', 'to speak, to talk', '说, 讲话', '日本語を少し話します。', 'I speak a little Japanese.', '我会说一点日语。'),
  ('ja-travel-basic-114', 'ja', 'basic', 'travel', '分かる', 'わかる', 'wakaru', 'to understand, to know', '明白, 理解', '日本語が分かりません。', 'I do not understand Japanese.', '我不懂日语。'),
  ('ja-travel-basic-115', 'ja', 'basic', 'travel', '教える', 'おしえる', 'oshieru', 'to teach, to tell', '教, 告诉', '道を教えてください。', 'Please tell me the way.', '请告诉我怎么走。'),
  ('ja-travel-basic-116', 'ja', 'basic', 'travel', '助ける', 'たすける', 'tasukeru', 'to help, to assist', '帮助, 救助', '助けてください。', 'Please help me.', '请帮帮我。'),
  ('ja-travel-basic-117', 'ja', 'basic', 'travel', '迷う', 'まよう', 'mayou', 'to get lost, to be confused', '迷路, 迷惑', '道に迷いました。', 'I got lost.', '我迷路了。'),
  ('ja-travel-basic-118', 'ja', 'basic', 'travel', '探す', 'さがす', 'sagasu', 'to search, to look for', '找, 寻找', 'ホテルを探しています。', 'I am looking for a hotel.', '我在找酒店。'),
  ('ja-travel-basic-119', 'ja', 'basic', 'travel', '予定', 'よてい', 'yotei', 'plan, schedule', '计划, 安排', '明日の予定は何ですか。', 'What is the plan for tomorrow?', '明天有什么安排？'),
  ('ja-travel-basic-120', 'ja', 'basic', 'travel', '地下鉄', 'ちかてつ', 'chikatetsu', 'subway, metro', '地铁, 地下铁', '地下鉄で行きます。', 'I will go by subway.', '我坐地铁去。'),
  ('ja-travel-basic-121', 'ja', 'basic', 'travel', '新幹線', 'しんかんせん', 'shinkansen', 'bullet train, shinkansen', '新干线, 高铁', '新幹線に乗りたいです。', 'I want to ride the bullet train.', '我想坐新干线。'),
  ('ja-travel-basic-122', 'ja', 'basic', 'travel', '船', 'ふね', 'fune', 'ship, boat', '船, 轮船', '船で島に行きます。', 'I will go to the island by boat.', '我坐船去岛上。'),
  ('ja-travel-basic-123', 'ja', 'basic', 'travel', '自転車', 'じてんしゃ', 'jitensha', 'bicycle, bike', '自行车, 单车', '自転車を借りたいです。', 'I want to rent a bicycle.', '我想借自行车。'),
  ('ja-travel-basic-124', 'ja', 'basic', 'travel', 'レンタカー', 'れんたかー', 'rentakaa', 'rental car, hire car', '租车, 租赁汽车', 'レンタカーを借りました。', 'I rented a car.', '我租了一辆车。'),
  ('ja-travel-basic-125', 'ja', 'basic', 'travel', '駐車場', 'ちゅうしゃじょう', 'chuushajou', 'parking lot, car park', '停车场, 车库', '駐車場はありますか。', 'Is there a parking lot?', '有停车场吗？'),
  ('ja-travel-basic-126', 'ja', 'basic', 'travel', 'ガソリンスタンド', 'がそりんすたんど', 'gasorinsutando', 'gas station, petrol station', '加油站, 油站', 'ガソリンスタンドはどこですか。', 'Where is the gas station?', '加油站在哪里？'),
  ('ja-travel-basic-127', 'ja', 'basic', 'travel', '高速道路', 'こうそくどうろ', 'kousokudouro', 'highway, expressway', '高速公路, 快速路', '高速道路を使います。', 'I will use the highway.', '我走高速公路。'),
  ('ja-travel-basic-128', 'ja', 'basic', 'travel', '席', 'せき', 'seki', 'seat, spot', '座位, 位子', '窓の席がいいです。', 'I prefer a window seat.', '我想要靠窗的座位。'),
  ('ja-travel-basic-129', 'ja', 'basic', 'travel', '指定席', 'していせき', 'shiteiseki', 'reserved seat, assigned seat', '指定席, 对号座', '指定席を取りたいです。', 'I want a reserved seat.', '我想要指定席。'),
  ('ja-travel-basic-130', 'ja', 'basic', 'travel', '自由席', 'じゆうせき', 'jiyuuseki', 'non-reserved seat, free seat', '自由席, 非指定座', '自由席でいいです。', 'A non-reserved seat is fine.', '自由席就行。'),
  ('ja-travel-basic-131', 'ja', 'basic', 'travel', '禁煙', 'きんえん', 'kinen', 'no smoking, non-smoking', '禁烟, 无烟', 'ここは禁煙です。', 'This is a non-smoking area.', '这里禁烟。'),
  ('ja-travel-basic-132', 'ja', 'basic', 'travel', 'Wi-Fi', 'わいふぁい', 'waifai', 'Wi-Fi, wireless internet', '无线网, 无线网络', 'Wi-Fiはありますか。', 'Is there Wi-Fi?', '有Wi-Fi吗？'),
  ('ja-travel-basic-133', 'ja', 'basic', 'travel', '充電', 'じゅうでん', 'juuden', 'charging, recharging', '充电, 蓄电', '携帯を充電したいです。', 'I want to charge my phone.', '我想给手机充电。'),
  ('ja-travel-basic-134', 'ja', 'basic', 'travel', '忘れ物', 'わすれもの', 'wasuremono', 'lost item, forgotten thing', '失物, 遗忘物品', '忘れ物をしました。', 'I left something behind.', '我忘了东西。'),
  ('ja-travel-basic-135', 'ja', 'basic', 'travel', '落とし物', 'おとしもの', 'otoshimono', 'dropped item, lost property', '丢失物, 拾遗物', '落とし物センターはどこですか。', 'Where is the lost and found?', '失物招领处在哪里？'),
  ('ja-travel-basic-136', 'ja', 'basic', 'travel', '窓口', 'まどぐち', 'madoguchi', 'counter, service window', '窗口, 服务台', '窓口で聞いてください。', 'Please ask at the counter.', '请去窗口问。'),
  ('ja-travel-basic-137', 'ja', 'basic', 'travel', '自動販売機', 'じどうはんばいき', 'jidouhanbaiki', 'vending machine, automatic machine', '自动售货机, 贩卖机', '自動販売機で水を買います。', 'I will buy water from the vending machine.', '我在自动售货机买水。'),
  ('ja-travel-basic-138', 'ja', 'basic', 'travel', 'コインロッカー', 'こいんろっかー', 'koinrokkaa', 'coin locker, luggage locker', '投币寄存柜, 储物柜', 'コインロッカーに荷物を入れます。', 'I will put my luggage in a coin locker.', '我把行李放进寄存柜。'),
  ('ja-travel-basic-139', 'ja', 'basic', 'travel', 'エスカレーター', 'えすかれーたー', 'esukareetaa', 'escalator, moving stairs', '自动扶梯, 电扶梯', 'エスカレーターで上がります。', 'I will go up by escalator.', '我坐自动扶梯上去。'),
  ('ja-travel-basic-140', 'ja', 'basic', 'travel', '終電', 'しゅうでん', 'shuuden', 'last train, final service', '末班车, 最后一班', '終電は何時ですか。', 'What time is the last train?', '末班车几点？'),
  ('ja-travel-basic-141', 'ja', 'basic', 'travel', '始発', 'しはつ', 'shihatsu', 'first train, first service', '首班车, 第一班', '始発に乗ります。', 'I will take the first train.', '我坐首班车。'),
  ('ja-travel-basic-142', 'ja', 'basic', 'travel', '快速', 'かいそく', 'kaisoku', 'rapid train, express', '快速, 快车', '快速電車に乗ります。', 'I will take the rapid train.', '我坐快速电车。'),
  ('ja-travel-basic-143', 'ja', 'basic', 'travel', '各駅停車', 'かくえきていしゃ', 'kakuekiteisha', 'local train, all-stops service', '各站停车, 慢车', '各駅停車で行きます。', 'I will go by local train.', '我坐各站停车。'),
  ('ja-travel-basic-144', 'ja', 'basic', 'travel', '混む', 'こむ', 'komu', 'to be crowded, to be packed', '拥挤, 混杂', '朝は電車が混みます。', 'The train is crowded in the morning.', '早上电车很挤。'),
  ('ja-travel-basic-145', 'ja', 'basic', 'travel', '空く', 'すく', 'suku', 'to be empty, to be uncrowded', '空, 不拥挤', '昼は電車が空いています。', 'The train is uncrowded during the day.', '白天电车不挤。'),
  ('ja-travel-basic-146', 'ja', 'basic', 'travel', '景色', 'けしき', 'keshiki', 'scenery, view', '景色, 风景', '景色がきれいです。', 'The scenery is beautiful.', '景色很美。'),
  ('ja-travel-basic-147', 'ja', 'basic', 'travel', '入場料', 'にゅうじょうりょう', 'nyuujouryou', 'admission fee, entrance fee', '门票, 入场费', '入場料はいくらですか。', 'How much is the admission fee?', '门票多少钱？'),
  ('ja-travel-basic-148', 'ja', 'basic', 'travel', '無料', 'むりょう', 'muryou', 'free of charge, complimentary', '免费, 不收费', 'ここは無料です。', 'This place is free.', '这里免费。'),
  ('ja-travel-basic-149', 'ja', 'basic', 'travel', '営業時間', 'えいぎょうじかん', 'eigyoujikan', 'business hours, opening hours', '营业时间, 开放时间', '営業時間は何時ですか。', 'What are the business hours?', '营业时间是几点？'),
  ('ja-travel-basic-150', 'ja', 'basic', 'travel', '閉まる', 'しまる', 'shimaru', 'to close, to shut', '关门, 关闭', '店が閉まりました。', 'The shop has closed.', '店关门了。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
