-- Expand ko-anime-intermediate to 150 curated entries (1-150)
-- Topic: K-drama/variety show/anime vocabulary for intermediate Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-anime-intermediate-1', 'ko', 'intermediate', 'anime/drama', '드라마', '드라마', 'deurama', 'drama, TV series', '电视剧，连续剧', '이 드라마 정말 재미있어요.', 'This drama is really interesting.', '这部电视剧真的很有趣。'),
  ('ko-anime-intermediate-2', 'ko', 'intermediate', 'anime/drama', '배우', '배우', 'baeu', 'actor, actress', '演员，男/女演员', '그 배우의 연기가 정말 좋아요.', 'That actor''s acting is really good.', '那个演员的演技真的很好。'),
  ('ko-anime-intermediate-3', 'ko', 'intermediate', 'anime/drama', '주인공', '주인공', 'juingong', 'protagonist, main character', '主人公，主角', '주인공이 정말 멋있어요.', 'The protagonist is really cool.', '主角真的很帅。'),
  ('ko-anime-intermediate-4', 'ko', 'intermediate', 'anime/drama', '악역', '악역', 'akyeok', 'villain, antagonist', '反派，坏人', '악역 배우가 연기를 잘해요.', 'The villain actor acts well.', '反派演员演技很好。'),
  ('ko-anime-intermediate-5', 'ko', 'intermediate', 'anime/drama', '조연', '조연', 'joyeon', 'supporting role, supporting actor', '配角，助演', '조연도 인기가 많아요.', 'The supporting actors are also popular.', '配角也很受欢迎。'),
  ('ko-anime-intermediate-6', 'ko', 'intermediate', 'anime/drama', '감독', '감독', 'gamdok', 'director, filmmaker', '导演，监督', '이 감독의 작품을 좋아해요.', 'I like this director''s works.', '我喜欢这个导演的作品。'),
  ('ko-anime-intermediate-7', 'ko', 'intermediate', 'anime/drama', '작가', '작가', 'jakga', 'writer, screenwriter', '作家，编剧', '작가가 대본을 잘 썼어요.', 'The writer wrote the script well.', '编剧把剧本写得很好。'),
  ('ko-anime-intermediate-8', 'ko', 'intermediate', 'anime/drama', '대본', '대본', 'daebon', 'script, screenplay', '剧本，台本', '대본 리딩이 시작됐어요.', 'The script reading has begun.', '剧本围读开始了。'),
  ('ko-anime-intermediate-9', 'ko', 'intermediate', 'anime/drama', '촬영', '촬영', 'chwaryeong', 'filming, shooting', '拍摄，摄影', '오늘 촬영이 끝났어요.', 'Today''s filming is done.', '今天的拍摄结束了。'),
  ('ko-anime-intermediate-10', 'ko', 'intermediate', 'anime/drama', '시청률', '시청률', 'sicheongnyul', 'viewership rating, ratings', '收视率，收视', '시청률이 계속 오르고 있어요.', 'The ratings keep going up.', '收视率一直在上升。'),
  ('ko-anime-intermediate-11', 'ko', 'intermediate', 'anime/drama', '명장면', '명장면', 'myeongjangmyeon', 'famous scene, iconic scene', '名场面，经典画面', '이 드라마의 명장면을 모았어요.', 'I collected the iconic scenes from this drama.', '我收集了这部剧的名场面。'),
  ('ko-anime-intermediate-12', 'ko', 'intermediate', 'anime/drama', '명대사', '명대사', 'myeongdaesa', 'famous line, iconic quote', '名台词，经典台词', '명대사가 많은 드라마예요.', 'It''s a drama with many famous lines.', '这是一部有很多名台词的电视剧。'),
  ('ko-anime-intermediate-13', 'ko', 'intermediate', 'anime/drama', '가수', '가수', 'gasu', 'singer, vocalist', '歌手，歌唱家', '좋아하는 가수의 콘서트에 갔어요.', 'I went to my favorite singer''s concert.', '我去了喜欢的歌手的演唱会。'),
  ('ko-anime-intermediate-14', 'ko', 'intermediate', 'anime/drama', '아이돌', '아이돌', 'aidol', 'idol, K-pop idol', '偶像，爱豆', '아이돌 그룹이 데뷔했어요.', 'The idol group debuted.', '偶像组合出道了。'),
  ('ko-anime-intermediate-15', 'ko', 'intermediate', 'anime/drama', '팬', '팬', 'paen', 'fan, supporter', '粉丝，支持者', '팬들이 공항에서 기다리고 있어요.', 'Fans are waiting at the airport.', '粉丝们在机场等着。'),
  ('ko-anime-intermediate-16', 'ko', 'intermediate', 'anime/drama', '콘서트', '콘서트', 'konseoteu', 'concert, live show', '演唱会，音乐会', '콘서트 티켓을 예매했어요.', 'I reserved concert tickets.', '我预订了演唱会门票。'),
  ('ko-anime-intermediate-17', 'ko', 'intermediate', 'anime/drama', '앨범', '앨범', 'aelbeom', 'album, music album', '专辑，唱片', '새 앨범이 나왔어요.', 'A new album came out.', '新专辑出来了。'),
  ('ko-anime-intermediate-18', 'ko', 'intermediate', 'anime/drama', '노래', '노래', 'norae', 'song, music', '歌曲，歌', '이 노래가 요즘 인기 많아요.', 'This song is popular these days.', '这首歌最近很流行。'),
  ('ko-anime-intermediate-19', 'ko', 'intermediate', 'anime/drama', '뮤직비디오', '뮤직비디오', 'myujikbideo', 'music video, MV', '音乐视频，MV', '뮤직비디오 조회수가 1억을 넘었어요.', 'The music video views exceeded 100 million.', '音乐视频播放量超过了一亿。'),
  ('ko-anime-intermediate-20', 'ko', 'intermediate', 'anime/drama', '안무', '안무', 'anmu', 'choreography, dance routine', '编舞，舞蹈', '안무가 정말 어려워 보여요.', 'The choreography looks really difficult.', '编舞看起来真的很难。'),
  ('ko-anime-intermediate-21', 'ko', 'intermediate', 'anime/drama', '데뷔', '데뷔', 'debwi', 'debut, first appearance', '出道，首次亮相', '그 그룹은 작년에 데뷔했어요.', 'That group debuted last year.', '那个组合去年出道了。'),
  ('ko-anime-intermediate-22', 'ko', 'intermediate', 'anime/drama', '예능', '예능', 'yeneung', 'variety show, entertainment', '综艺，娱乐节目', '예능 프로그램에 출연했어요.', 'They appeared on a variety show.', '他们上了综艺节目。'),
  ('ko-anime-intermediate-23', 'ko', 'intermediate', 'anime/drama', '게스트', '게스트', 'geseuteu', 'guest, guest appearance', '嘉宾，客人', '오늘 게스트가 누구예요?', 'Who is today''s guest?', '今天的嘉宾是谁？'),
  ('ko-anime-intermediate-24', 'ko', 'intermediate', 'anime/drama', '녹화', '녹화', 'nokhwa', 'recording, taping', '录制，录像', '녹화가 새벽까지 이어졌어요.', 'The recording continued until dawn.', '录制一直持续到凌晨。'),
  ('ko-anime-intermediate-25', 'ko', 'intermediate', 'anime/drama', '생방송', '생방송', 'saengbangsong', 'live broadcast, live show', '直播，现场直播', '생방송으로 진행됩니다.', 'It will be broadcast live.', '将以直播形式进行。'),
  ('ko-anime-intermediate-26', 'ko', 'intermediate', 'anime/drama', '재방송', '재방송', 'jaebangsong', 'rerun, rebroadcast', '重播，再播', '재방송으로 다시 봤어요.', 'I watched it again as a rerun.', '我看了重播。'),
  ('ko-anime-intermediate-27', 'ko', 'intermediate', 'anime/drama', '구독', '구독', 'gudok', 'subscription, subscribe', '订阅，关注', '채널을 구독하고 있어요.', 'I''m subscribed to the channel.', '我订阅了这个频道。'),
  ('ko-anime-intermediate-28', 'ko', 'intermediate', 'anime/drama', '스트리밍', '스트리밍', 'seuteuriming', 'streaming, online streaming', '流媒体，串流', '스트리밍으로 드라마를 봐요.', 'I watch dramas via streaming.', '我通过流媒体看电视剧。'),
  ('ko-anime-intermediate-29', 'ko', 'intermediate', 'anime/drama', '원작', '원작', 'wonjak', 'original work, source material', '原作，原著', '원작 소설을 먼저 읽었어요.', 'I read the original novel first.', '我先读了原作小说。'),
  ('ko-anime-intermediate-30', 'ko', 'intermediate', 'anime/drama', '시즌', '시즌', 'sijeun', 'season, series', '季，第几季', '시즌 2가 곧 나와요.', 'Season 2 is coming soon.', '第二季快出了。'),
  ('ko-anime-intermediate-31', 'ko', 'intermediate', 'anime/drama', '에피소드', '에피소드', 'episodeu', 'episode, installment', '集，单集', '에피소드마다 반전이 있어요.', 'There''s a twist in every episode.', '每集都有反转。'),
  ('ko-anime-intermediate-32', 'ko', 'intermediate', 'anime/drama', '자막', '자막', 'jamak', 'subtitles, captions', '字幕，副标题', '한국어 자막으로 보고 있어요.', 'I''m watching with Korean subtitles.', '我在看韩语字幕版。'),
  ('ko-anime-intermediate-33', 'ko', 'intermediate', 'anime/drama', '감동', '감동', 'gamdong', 'being moved, touching emotion', '感动，触动', '마지막 장면에서 감동받았어요.', 'I was moved by the last scene.', '我被最后一幕感动了。'),
  ('ko-anime-intermediate-34', 'ko', 'intermediate', 'anime/drama', '웃기다', '웃기다', 'utgida', 'to be funny, hilarious', '搞笑，好笑', '이 예능 정말 웃겨요.', 'This variety show is really funny.', '这个综艺真的很搞笑。'),
  ('ko-anime-intermediate-35', 'ko', 'intermediate', 'anime/drama', '울다', '울다', 'ulda', 'to cry, to weep', '哭，流泪', '드라마 보면서 울었어요.', 'I cried while watching the drama.', '看电视剧的时候哭了。'),
  ('ko-anime-intermediate-36', 'ko', 'intermediate', 'anime/drama', '설레다', '설레다', 'seolleda', 'to flutter, to feel excited', '心动，激动', '로맨스 장면에서 설레었어요.', 'I felt butterflies during the romance scene.', '看到浪漫场面心动了。'),
  ('ko-anime-intermediate-37', 'ko', 'intermediate', 'anime/drama', '떨리다', '떨리다', 'tteollida', 'to tremble, to be nervous', '颤抖，紧张', '결과 발표 전에 떨렸어요.', 'I was trembling before the results announcement.', '公布结果前很紧张。'),
  ('ko-anime-intermediate-38', 'ko', 'intermediate', 'anime/drama', '소름', '소름', 'soreum', 'goosebumps, chills', '鸡皮疙瘩，起鸡皮', '반전 장면에서 소름 돋았어요.', 'I got goosebumps at the twist scene.', '看到反转场面起了鸡皮疙瘩。'),
  ('ko-anime-intermediate-39', 'ko', 'intermediate', 'anime/drama', '반전', '반전', 'banjeon', 'plot twist, reversal', '反转，逆转', '마지막에 반전이 있었어요.', 'There was a twist at the end.', '最后有一个反转。'),
  ('ko-anime-intermediate-40', 'ko', 'intermediate', 'anime/drama', '팬덤', '팬덤', 'paendeom', 'fandom, fan community', '粉丝圈，饭圈', '이 그룹의 팬덤이 정말 커요.', 'This group''s fandom is really big.', '这个组合的粉丝圈真的很大。'),
  ('ko-anime-intermediate-41', 'ko', 'intermediate', 'anime/drama', '덕후', '덕후', 'deokhu', 'superfan, otaku', '死忠粉，宅', '저는 이 배우의 덕후예요.', 'I''m a superfan of this actor.', '我是这个演员的死忠粉。'),
  ('ko-anime-intermediate-42', 'ko', 'intermediate', 'anime/drama', '최애', '최애', 'choeae', 'ultimate favorite, bias', '最爱，本命', '최애 캐릭터가 바뀌었어요.', 'My favorite character changed.', '我的最爱角色换了。'),
  ('ko-anime-intermediate-43', 'ko', 'intermediate', 'anime/drama', '굿즈', '굿즈', 'gutjeu', 'merchandise, goods', '周边，商品', '콘서트 굿즈를 샀어요.', 'I bought concert merchandise.', '我买了演唱会周边。'),
  ('ko-anime-intermediate-44', 'ko', 'intermediate', 'anime/drama', '컴백', '컴백', 'keombaek', 'comeback, return', '回归，复出', '다음 달에 컴백한다고 해요.', 'They say they''re coming back next month.', '听说下个月回归。'),
  ('ko-anime-intermediate-45', 'ko', 'intermediate', 'anime/drama', '인기', '인기', 'ingi', 'popularity, fame', '人气，受欢迎', '이 드라마가 인기 많아요.', 'This drama is very popular.', '这部剧很受欢迎。'),
  ('ko-anime-intermediate-46', 'ko', 'intermediate', 'anime/drama', '화제', '화제', 'hwaje', 'hot topic, trending', '话题，热议', '이 장면이 화제가 됐어요.', 'This scene became a hot topic.', '这个场面成了热议话题。'),
  ('ko-anime-intermediate-47', 'ko', 'intermediate', 'anime/drama', '제작', '제작', 'jejak', 'production, making', '制作，制造', '제작비가 많이 들었어요.', 'The production cost was high.', '制作费花了很多。'),
  ('ko-anime-intermediate-48', 'ko', 'intermediate', 'anime/drama', '후편', '후편', 'hupyeon', 'sequel, second part', '后篇，续集', '후편이 내년에 나와요.', 'The sequel comes out next year.', '后篇明年出。'),
  ('ko-anime-intermediate-49', 'ko', 'intermediate', 'anime/drama', '전편', '전편', 'jeonpyeon', 'prequel, first part', '前篇，前传', '전편을 먼저 보세요.', 'Watch the first part first.', '先看前篇。'),
  ('ko-anime-intermediate-50', 'ko', 'intermediate', 'anime/drama', '특별편', '특별편', 'teukbyeolpyeon', 'special episode, special edition', '特别篇，番外', '크리스마스 특별편이 방영됐어요.', 'A Christmas special episode aired.', '圣诞特别篇播出了。'),
  ('ko-anime-intermediate-51', 'ko', 'intermediate', 'anime/drama', '예고편', '예고편', 'yegopyeon', 'preview, trailer', '预告片，预告', '예고편만 봐도 기대돼요.', 'Even just watching the trailer makes me excited.', '光看预告片就很期待。'),
  ('ko-anime-intermediate-52', 'ko', 'intermediate', 'anime/drama', '연기', '연기', 'yeongi', 'acting, performance', '演技，表演', '연기가 자연스러워요.', 'The acting is natural.', '演技很自然。'),
  ('ko-anime-intermediate-53', 'ko', 'intermediate', 'anime/drama', '대사', '대사', 'daesa', 'dialogue, lines', '台词，对白', '대사를 외우는 게 어려워요.', 'Memorizing lines is difficult.', '背台词很难。'),
  ('ko-anime-intermediate-54', 'ko', 'intermediate', 'anime/drama', '결말', '결말', 'gyeolmal', 'ending, conclusion', '结局，结尾', '결말이 아쉬웠어요.', 'The ending was disappointing.', '结局有点遗憾。'),
  ('ko-anime-intermediate-55', 'ko', 'intermediate', 'anime/drama', '해피엔딩', '해피엔딩', 'haepiendig', 'happy ending, good ending', '大团圆结局，好结局', '해피엔딩이어서 좋았어요.', 'I''m glad it was a happy ending.', '因为是大团圆结局所以很开心。'),
  ('ko-anime-intermediate-56', 'ko', 'intermediate', 'anime/drama', '새드엔딩', '새드엔딩', 'saedeuendig', 'sad ending, tragic ending', '悲伤结局，坏结局', '새드엔딩이라 많이 울었어요.', 'It was a sad ending so I cried a lot.', '因为是悲伤结局哭了很多。'),
  ('ko-anime-intermediate-57', 'ko', 'intermediate', 'anime/drama', '로맨스', '로맨스', 'romaenseu', 'romance, love story', '爱情，浪漫', '로맨스 드라마를 좋아해요.', 'I like romance dramas.', '我喜欢爱情剧。'),
  ('ko-anime-intermediate-58', 'ko', 'intermediate', 'anime/drama', '스릴러', '스릴러', 'seurilleo', 'thriller, suspense', '惊悚，悬疑', '스릴러 장르를 즐겨 봐요.', 'I enjoy watching the thriller genre.', '我喜欢看惊悚类型。'),
  ('ko-anime-intermediate-59', 'ko', 'intermediate', 'anime/drama', '코미디', '코미디', 'komidi', 'comedy, humor', '喜剧，搞笑', '코미디 예능이 스트레스 해소에 좋아요.', 'Comedy variety shows are good for stress relief.', '搞笑综艺对解压很好。'),
  ('ko-anime-intermediate-60', 'ko', 'intermediate', 'anime/drama', '사극', '사극', 'sageuk', 'historical drama, period piece', '古装剧，历史剧', '사극에서 한복이 멋있어요.', 'Hanbok looks great in historical dramas.', '古装剧里的韩服很好看。'),
  ('ko-anime-intermediate-61', 'ko', 'intermediate', 'anime/drama', '출연', '출연', 'churyeon', 'appearance, starring in', '出演，参演', '인기 배우가 출연해요.', 'A popular actor is starring.', '人气演员出演了。'),
  ('ko-anime-intermediate-62', 'ko', 'intermediate', 'anime/drama', '캐스팅', '캐스팅', 'kaeseutig', 'casting, role assignment', '选角，卡司', '캐스팅이 완벽해요.', 'The casting is perfect.', '选角很完美。'),
  ('ko-anime-intermediate-63', 'ko', 'intermediate', 'anime/drama', '시놉시스', '시놉시스', 'sinopsiseu', 'synopsis, plot summary', '剧情简介，梗概', '시놉시스만 읽어도 재미있어 보여요.', 'It looks interesting just reading the synopsis.', '光看剧情简介就觉得有趣。'),
  ('ko-anime-intermediate-64', 'ko', 'intermediate', 'anime/drama', '방영', '방영', 'bangyeong', 'broadcasting, airing', '播出，放映', '매주 월요일에 방영돼요.', 'It airs every Monday.', '每周一播出。'),
  ('ko-anime-intermediate-65', 'ko', 'intermediate', 'anime/drama', '본방', '본방', 'bonbang', 'first airing, premiere broadcast', '首播，正播', '본방을 놓쳤어요.', 'I missed the first airing.', '我错过了首播。'),
  ('ko-anime-intermediate-66', 'ko', 'intermediate', 'anime/drama', '회차', '회차', 'hoecha', 'episode number, installment', '集数，话数', '몇 회차까지 봤어요?', 'How many episodes have you watched?', '你看到第几集了？'),
  ('ko-anime-intermediate-67', 'ko', 'intermediate', 'anime/drama', '최종회', '최종회', 'choejonghoe', 'final episode, finale', '最终集，大结局', '최종회가 다음 주예요.', 'The finale is next week.', '大结局是下周。'),
  ('ko-anime-intermediate-68', 'ko', 'intermediate', 'anime/drama', '클리프행어', '클리프행어', 'keullipeuhaengeo', 'cliffhanger, suspenseful ending', '悬念结尾，挖坑', '매 회 클리프행어로 끝나요.', 'Every episode ends with a cliffhanger.', '每集都以悬念结尾。'),
  ('ko-anime-intermediate-69', 'ko', 'intermediate', 'anime/drama', '떡밥', '떡밥', 'tteokbap', 'plot hint, foreshadowing bait', '伏笔，悬念', '떡밥을 회수했어요.', 'They resolved the foreshadowing.', '伏笔回收了。'),
  ('ko-anime-intermediate-70', 'ko', 'intermediate', 'anime/drama', '복선', '복선', 'bokseon', 'foreshadowing, setup', '伏笔，铺垫', '복선이 잘 깔려 있어요.', 'The foreshadowing is well laid out.', '伏笔铺垫得很好。'),
  ('ko-anime-intermediate-71', 'ko', 'intermediate', 'anime/drama', '몰입', '몰입', 'morip', 'immersion, being engrossed', '沉浸，投入', '몰입감이 높은 드라마예요.', 'It''s a drama with high immersion.', '这是一部沉浸感很强的剧。'),
  ('ko-anime-intermediate-72', 'ko', 'intermediate', 'anime/drama', '전개', '전개', 'jeongae', 'development, progression', '展开，发展', '스토리 전개가 빨라요.', 'The story progresses quickly.', '剧情展开很快。'),
  ('ko-anime-intermediate-73', 'ko', 'intermediate', 'anime/drama', '케미', '케미', 'kemi', 'chemistry, on-screen chemistry', '化学反应，CP感', '두 배우의 케미가 좋아요.', 'The two actors have great chemistry.', '两个演员的CP感很强。'),
  ('ko-anime-intermediate-74', 'ko', 'intermediate', 'anime/drama', '커플', '커플', 'keopeul', 'couple, pairing', '情侣，CP', '이 커플 정말 좋아요.', 'I really like this couple.', '我真的很喜欢这对CP。'),
  ('ko-anime-intermediate-75', 'ko', 'intermediate', 'anime/drama', '삼각관계', '삼각관계', 'samgakgwangye', 'love triangle, three-way relationship', '三角关系，三角恋', '삼각관계가 복잡해요.', 'The love triangle is complicated.', '三角关系很复杂。'),
  ('ko-anime-intermediate-76', 'ko', 'intermediate', 'anime/drama', '고백', '고백', 'gobaek', 'confession, declaring love', '告白，表白', '고백 장면이 설레었어요.', 'The confession scene was heart-fluttering.', '告白场面让人心动。'),
  ('ko-anime-intermediate-77', 'ko', 'intermediate', 'anime/drama', '키스신', '키스신', 'kiseusin', 'kiss scene, kissing scene', '吻戏，亲吻场面', '키스신이 화제가 됐어요.', 'The kiss scene became a hot topic.', '吻戏成了热议话题。'),
  ('ko-anime-intermediate-78', 'ko', 'intermediate', 'anime/drama', '엔딩', '엔딩', 'ending', 'ending, finale', '结尾，片尾', '엔딩 크레딧까지 봤어요.', 'I watched until the ending credits.', '我看到了片尾字幕。'),
  ('ko-anime-intermediate-79', 'ko', 'intermediate', 'anime/drama', '오프닝', '오프닝', 'opeuning', 'opening, intro', '片头，开场', '오프닝 곡이 좋아요.', 'The opening song is good.', '片头曲很好听。'),
  ('ko-anime-intermediate-80', 'ko', 'intermediate', 'anime/drama', '캐릭터', '캐릭터', 'kaerikteo', 'character, persona', '角色，人物', '캐릭터가 매력적이에요.', 'The characters are charming.', '角色很有魅力。'),
  ('ko-anime-intermediate-81', 'ko', 'intermediate', 'anime/drama', '빌런', '빌런', 'billeon', 'villain, bad character', '反派，恶人', '빌런이 너무 잘 만들어졌어요.', 'The villain is so well-crafted.', '反派塑造得太好了。'),
  ('ko-anime-intermediate-82', 'ko', 'intermediate', 'anime/drama', '성장', '성장', 'seongjang', 'growth, development', '成长，发展', '주인공의 성장이 인상적이에요.', 'The protagonist''s growth is impressive.', '主角的成长令人印象深刻。'),
  ('ko-anime-intermediate-83', 'ko', 'intermediate', 'anime/drama', '우정', '우정', 'ujeong', 'friendship, bond', '友情，友谊', '우정이 감동적인 드라마예요.', 'It''s a drama with touching friendship.', '这是一部友情感人的剧。'),
  ('ko-anime-intermediate-84', 'ko', 'intermediate', 'anime/drama', '복수', '복수', 'boksu', 'revenge, vengeance', '复仇，报复', '복수극이 인기 있어요.', 'Revenge dramas are popular.', '复仇剧很受欢迎。'),
  ('ko-anime-intermediate-85', 'ko', 'intermediate', 'anime/drama', '미스터리', '미스터리', 'miseuteori', 'mystery, enigma', '悬疑，谜团', '미스터리 장르를 좋아해요.', 'I like the mystery genre.', '我喜欢悬疑类型。'),
  ('ko-anime-intermediate-86', 'ko', 'intermediate', 'anime/drama', '추리', '추리', 'churi', 'deduction, reasoning', '推理，推断', '추리 드라마가 재미있어요.', 'Detective dramas are interesting.', '推理剧很有趣。'),
  ('ko-anime-intermediate-87', 'ko', 'intermediate', 'anime/drama', '스포일러', '스포일러', 'seupoineo', 'spoiler, plot reveal', '剧透，剧情泄露', '스포일러 하지 마세요!', 'Don''t give spoilers!', '不要剧透！'),
  ('ko-anime-intermediate-88', 'ko', 'intermediate', 'anime/drama', '리뷰', '리뷰', 'ribyu', 'review, critique', '评论，点评', '드라마 리뷰를 올렸어요.', 'I posted a drama review.', '我发了电视剧评论。'),
  ('ko-anime-intermediate-89', 'ko', 'intermediate', 'anime/drama', '평점', '평점', 'pyeongjeom', 'rating score, grade', '评分，打分', '평점이 9점 이상이에요.', 'The rating is above 9 points.', '评分在9分以上。'),
  ('ko-anime-intermediate-90', 'ko', 'intermediate', 'anime/drama', '추천', '추천', 'chucheon', 'recommendation, suggestion', '推荐，建议', '이 드라마를 추천해요.', 'I recommend this drama.', '我推荐这部剧。'),
  ('ko-anime-intermediate-91', 'ko', 'intermediate', 'anime/drama', '정주행', '정주행', 'jeongjuhaeng', 'binge-watching, marathon viewing', '追剧，刷剧', '주말에 정주행했어요.', 'I binge-watched over the weekend.', '周末追剧了。'),
  ('ko-anime-intermediate-92', 'ko', 'intermediate', 'anime/drama', '밤새', '밤새', 'bamsae', 'all night, overnight', '通宵，一整夜', '밤새 드라마를 봤어요.', 'I watched dramas all night.', '通宵看了电视剧。'),
  ('ko-anime-intermediate-93', 'ko', 'intermediate', 'anime/drama', '몰아보기', '몰아보기', 'morabogi', 'binge-watching, watching consecutively', '连看，一口气看', '10회를 몰아봤어요.', 'I binge-watched 10 episodes.', '一口气看了10集。'),
  ('ko-anime-intermediate-94', 'ko', 'intermediate', 'anime/drama', '음원', '음원', 'eumwon', 'music source, digital single', '音源，数字单曲', '음원 차트 1위를 했어요.', 'It reached number 1 on the music chart.', '在音源榜拿了第一名。'),
  ('ko-anime-intermediate-95', 'ko', 'intermediate', 'anime/drama', '차트', '차트', 'chateu', 'chart, ranking', '排行榜，榜单', '차트에 진입했어요.', 'It entered the charts.', '进了排行榜。'),
  ('ko-anime-intermediate-96', 'ko', 'intermediate', 'anime/drama', '음악방송', '음악방송', 'eumakbangsong', 'music show, music program', '音乐节目，打歌节目', '음악방송에서 1위를 했어요.', 'They got first place on a music show.', '在音乐节目上得了第一名。'),
  ('ko-anime-intermediate-97', 'ko', 'intermediate', 'anime/drama', '무대', '무대', 'mudae', 'stage, performance', '舞台，表演', '무대가 정말 화려해요.', 'The stage is really spectacular.', '舞台真的很华丽。'),
  ('ko-anime-intermediate-98', 'ko', 'intermediate', 'anime/drama', '팬미팅', '팬미팅', 'paenmiting', 'fan meeting, fan event', '粉丝见面会，粉丝活动', '팬미팅에 당첨됐어요.', 'I won tickets to the fan meeting.', '我中了粉丝见面会的签。'),
  ('ko-anime-intermediate-99', 'ko', 'intermediate', 'anime/drama', '사인회', '사인회', 'sainhoe', 'autograph session, signing event', '签名会，签售会', '사인회에 참여했어요.', 'I participated in the autograph session.', '我参加了签名会。'),
  ('ko-anime-intermediate-100', 'ko', 'intermediate', 'anime/drama', '총회', '총회', 'chonghoe', 'general meeting, fan assembly', '总会，全体会议', '팬클럽 총회에 갔어요.', 'I went to the fan club general meeting.', '我去了粉丝俱乐部的总会。'),
  ('ko-anime-intermediate-101', 'ko', 'intermediate', 'anime/drama', '응원', '응원', 'eungwon', 'cheering, support', '应援，支持', '콘서트에서 응원했어요.', 'I cheered at the concert.', '在演唱会上应援了。'),
  ('ko-anime-intermediate-102', 'ko', 'intermediate', 'anime/drama', '응원봉', '응원봉', 'eungwonbong', 'light stick, cheering stick', '应援棒，手灯', '응원봉을 흔들었어요.', 'I waved the light stick.', '我挥了应援棒。'),
  ('ko-anime-intermediate-103', 'ko', 'intermediate', 'anime/drama', '포토카드', '포토카드', 'potokadeu', 'photo card, collectible card', '小卡，写真卡', '포토카드를 교환했어요.', 'I traded photo cards.', '我交换了小卡。'),
  ('ko-anime-intermediate-104', 'ko', 'intermediate', 'anime/drama', '앙코르', '앙코르', 'angkoreu', 'encore, additional performance', '安可，返场', '앙코르 공연이 있었어요.', 'There was an encore performance.', '有安可表演。'),
  ('ko-anime-intermediate-105', 'ko', 'intermediate', 'anime/drama', '떼창', '떼창', 'ttechang', 'group singing, fan chanting together', '大合唱，全场合唱', '떼창이 정말 감동이었어요.', 'The group singing was really moving.', '全场合唱真的很感动。'),
  ('ko-anime-intermediate-106', 'ko', 'intermediate', 'anime/drama', '직캠', '직캠', 'jikcam', 'fancam, direct camera', '直拍，饭拍', '직캠 조회수가 엄청 높아요.', 'The fancam views are incredibly high.', '直拍的播放量非常高。'),
  ('ko-anime-intermediate-107', 'ko', 'intermediate', 'anime/drama', '브이로그', '브이로그', 'beuirogeu', 'vlog, video blog', '视频日志，Vlog', '배우의 브이로그를 봤어요.', 'I watched the actor''s vlog.', '我看了演员的Vlog。'),
  ('ko-anime-intermediate-108', 'ko', 'intermediate', 'anime/drama', '비하인드', '비하인드', 'bihaindeu', 'behind-the-scenes, making of', '幕后，花絮', '촬영 비하인드가 재미있어요.', 'The behind-the-scenes of filming is fun.', '拍摄花絮很有意思。'),
  ('ko-anime-intermediate-109', 'ko', 'intermediate', 'anime/drama', '메이킹', '메이킹', 'meiking', 'making film, production diary', '拍摄花絮，制作日志', '메이킹 영상이 올라왔어요.', 'The making-of video was uploaded.', '制作花絮视频上传了。'),
  ('ko-anime-intermediate-110', 'ko', 'intermediate', 'anime/drama', '티저', '티저', 'tijeo', 'teaser, preview clip', '预告片，先导片', '티저가 공개됐어요.', 'The teaser was released.', '预告片公开了。'),
  ('ko-anime-intermediate-111', 'ko', 'intermediate', 'anime/drama', '포스터', '포스터', 'poseuteo', 'poster, promotional image', '海报，宣传画', '공식 포스터가 나왔어요.', 'The official poster is out.', '官方海报出来了。'),
  ('ko-anime-intermediate-112', 'ko', 'intermediate', 'anime/drama', '제작발표회', '제작발표회', 'jejakbalpyohoe', 'production press conference, launch event', '制作发布会，开播发布会', '제작발표회를 열었어요.', 'They held a production press conference.', '召开了制作发布会。'),
  ('ko-anime-intermediate-113', 'ko', 'intermediate', 'anime/drama', '시사회', '시사회', 'sisahoe', 'premiere screening, preview event', '试映会，首映', '시사회에 초대받았어요.', 'I was invited to the premiere screening.', '我受邀参加了试映会。'),
  ('ko-anime-intermediate-114', 'ko', 'intermediate', 'anime/drama', '수상', '수상', 'susang', 'winning an award, receiving a prize', '获奖，得奖', '대상을 수상했어요.', 'They won the grand prize.', '获得了大奖。'),
  ('ko-anime-intermediate-115', 'ko', 'intermediate', 'anime/drama', '시상식', '시상식', 'sisangsik', 'awards ceremony, award show', '颁奖典礼，颁奖仪式', '시상식에서 울었어요.', 'They cried at the awards ceremony.', '在颁奖典礼上哭了。'),
  ('ko-anime-intermediate-116', 'ko', 'intermediate', 'anime/drama', '후보', '후보', 'hubo', 'nominee, candidate', '候选人，提名', '올해 대상 후보예요.', 'They''re nominees for this year''s grand prize.', '是今年大奖的候选人。'),
  ('ko-anime-intermediate-117', 'ko', 'intermediate', 'anime/drama', '연출', '연출', 'yeonchul', 'directing, direction style', '导演手法，演出', '연출이 독특해요.', 'The directing style is unique.', '导演手法很独特。'),
  ('ko-anime-intermediate-118', 'ko', 'intermediate', 'anime/drama', '편집', '편집', 'pyeonjip', 'editing, post-production', '剪辑，编辑', '편집이 깔끔해요.', 'The editing is clean.', '剪辑很干净利落。'),
  ('ko-anime-intermediate-119', 'ko', 'intermediate', 'anime/drama', '자체제작', '자체제작', 'jachejejak', 'self-produced, in-house production', '自制，自主制作', '자체제작 콘텐츠가 많아요.', 'There are many self-produced contents.', '有很多自制内容。'),
  ('ko-anime-intermediate-120', 'ko', 'intermediate', 'anime/drama', '웹드라마', '웹드라마', 'webdeurama', 'web drama, short-form drama', '网剧，网络短剧', '웹드라마가 요즘 인기예요.', 'Web dramas are popular these days.', '网剧最近很受欢迎。'),
  ('ko-anime-intermediate-121', 'ko', 'intermediate', 'anime/drama', '웹툰', '웹툰', 'weptun', 'webtoon, digital comic', '网漫，网络漫画', '웹툰 원작 드라마가 많아요.', 'There are many dramas based on webtoons.', '很多电视剧改编自网漫。'),
  ('ko-anime-intermediate-122', 'ko', 'intermediate', 'anime/drama', '원작자', '원작자', 'wonjakcja', 'original creator, original author', '原作者，原著作者', '원작자가 직접 각색했어요.', 'The original author adapted it themselves.', '原作者亲自改编了。'),
  ('ko-anime-intermediate-123', 'ko', 'intermediate', 'anime/drama', '각색', '각색', 'gaksaek', 'adaptation, dramatization', '改编，脚色', '원작을 잘 각색했어요.', 'They adapted the original well.', '原作改编得很好。'),
  ('ko-anime-intermediate-124', 'ko', 'intermediate', 'anime/drama', '더빙', '더빙', 'deobing', 'dubbing, voice-over', '配音，译制', '한국어 더빙으로 봤어요.', 'I watched with Korean dubbing.', '我看了韩语配音版。'),
  ('ko-anime-intermediate-125', 'ko', 'intermediate', 'anime/drama', '성우', '성우', 'seongwu', 'voice actor, voice actress', '声优，配音演员', '성우의 목소리가 좋아요.', 'The voice actor''s voice is nice.', '声优的声音很好听。'),
  ('ko-anime-intermediate-126', 'ko', 'intermediate', 'anime/drama', '애니메이션', '애니메이션', 'aenimeisyeon', 'animation, animated work', '动画，动画片', '한국 애니메이션이 발전했어요.', 'Korean animation has developed.', '韩国动画发展了。'),
  ('ko-anime-intermediate-127', 'ko', 'intermediate', 'anime/drama', '만화', '만화', 'manhwa', 'comic, manga/manhwa', '漫画，连环画', '만화를 읽는 게 취미예요.', 'Reading comics is my hobby.', '看漫画是我的爱好。'),
  ('ko-anime-intermediate-128', 'ko', 'intermediate', 'anime/drama', '실검', '실검', 'silgeom', 'real-time search ranking, trending', '实时热搜，热搜榜', '실검 1위에 올랐어요.', 'It reached number 1 on trending.', '上了热搜第一名。'),
  ('ko-anime-intermediate-129', 'ko', 'intermediate', 'anime/drama', '댓글', '댓글', 'daetgeul', 'comment, online reply', '评论，留言', '댓글이 10만 개 넘었어요.', 'Comments exceeded 100,000.', '评论超过了10万条。'),
  ('ko-anime-intermediate-130', 'ko', 'intermediate', 'anime/drama', '조회수', '조회수', 'johoisu', 'view count, number of views', '播放量，点击量', '조회수가 천만을 돌파했어요.', 'Views broke through 10 million.', '播放量突破了一千万。'),
  ('ko-anime-intermediate-131', 'ko', 'intermediate', 'anime/drama', '좋아요', '좋아요', 'joayo', 'like, thumbs up', '点赞，喜欢', '좋아요를 눌렀어요.', 'I pressed like.', '我点了赞。'),
  ('ko-anime-intermediate-132', 'ko', 'intermediate', 'anime/drama', '공유', '공유', 'gongyu', 'sharing, repost', '分享，共享', '친구에게 공유했어요.', 'I shared it with a friend.', '我分享给朋友了。'),
  ('ko-anime-intermediate-133', 'ko', 'intermediate', 'anime/drama', '해시태그', '해시태그', 'haesitaegeu', 'hashtag, tag', '话题标签，井号标签', '해시태그가 유행이에요.', 'The hashtag is trending.', '话题标签很流行。'),
  ('ko-anime-intermediate-134', 'ko', 'intermediate', 'anime/drama', '밈', '밈', 'mim', 'meme, viral joke', '梗，表情包', '이 장면이 밈이 됐어요.', 'This scene became a meme.', '这个场面变成了梗。'),
  ('ko-anime-intermediate-135', 'ko', 'intermediate', 'anime/drama', '짤', '짤', 'jjal', 'meme image, reaction GIF', '表情包，动图', '드라마 짤이 많이 퍼졌어요.', 'Drama meme images spread a lot.', '电视剧的表情包传播了很多。'),
  ('ko-anime-intermediate-136', 'ko', 'intermediate', 'anime/drama', '입덕', '입덕', 'ipdeok', 'becoming a fan, joining a fandom', '入坑，成为粉丝', '이 드라마로 입덕했어요.', 'I became a fan through this drama.', '我因为这部剧入坑了。'),
  ('ko-anime-intermediate-137', 'ko', 'intermediate', 'anime/drama', '탈덕', '탈덕', 'taldeok', 'leaving a fandom, unstanning', '脱粉，退坑', '탈덕하려고 했는데 못 했어요.', 'I tried to leave the fandom but couldn''t.', '想脱粉但没成功。'),
  ('ko-anime-intermediate-138', 'ko', 'intermediate', 'anime/drama', '올킬', '올킬', 'olkil', 'all-kill, sweeping all charts', '屠榜，横扫榜单', '음원 차트 올킬했어요.', 'They swept all the music charts.', '音源榜屠榜了。'),
  ('ko-anime-intermediate-139', 'ko', 'intermediate', 'anime/drama', '총공', '총공', 'chonggong', 'mass streaming, coordinated fan effort', '总攻，集中打榜', '팬들이 총공을 준비했어요.', 'Fans prepared a mass streaming effort.', '粉丝们准备了集中打榜。'),
  ('ko-anime-intermediate-140', 'ko', 'intermediate', 'anime/drama', '역조공', '역조공', 'yeokjogong', 'idol giving back to fans, reverse support', '反向应援，爱豆反馈粉丝', '아이돌이 역조공을 했어요.', 'The idol gave back to fans.', '爱豆给粉丝做了反向应援。'),
  ('ko-anime-intermediate-141', 'ko', 'intermediate', 'anime/drama', '팬레터', '팬레터', 'paenreteo', 'fan letter, fan mail', '粉丝信，饭信', '팬레터를 써서 보냈어요.', 'I wrote and sent a fan letter.', '我写了粉丝信寄出去了。'),
  ('ko-anime-intermediate-142', 'ko', 'intermediate', 'anime/drama', '영상통화', '영상통화', 'yeongsangtonghwa', 'video call, video fan sign', '视频通话，视频签售', '영상통화 팬사인회에 당첨됐어요.', 'I won the video call fan sign event.', '我中了视频签售会。'),
  ('ko-anime-intermediate-143', 'ko', 'intermediate', 'anime/drama', '컨셉', '컨셉', 'keonsep', 'concept, theme', '概念，风格', '이번 컨셉이 독특해요.', 'This concept is unique.', '这次的概念很独特。'),
  ('ko-anime-intermediate-144', 'ko', 'intermediate', 'anime/drama', '티켓팅', '티켓팅', 'tiketing', 'ticketing, getting tickets', '抢票，购票', '티켓팅 경쟁이 치열해요.', 'The ticketing competition is fierce.', '抢票竞争很激烈。'),
  ('ko-anime-intermediate-145', 'ko', 'intermediate', 'anime/drama', '매진', '매진', 'maejin', 'sold out, completely sold', '售罄，卖完', '콘서트가 3분 만에 매진됐어요.', 'The concert sold out in 3 minutes.', '演唱会3分钟就售罄了。'),
  ('ko-anime-intermediate-146', 'ko', 'intermediate', 'anime/drama', '앵콜콘서트', '앵콜콘서트', 'aengkolkonseoteu', 'encore concert, additional concert', '安可演唱会，加场演唱会', '앵콜콘서트가 확정됐어요.', 'An encore concert has been confirmed.', '安可演唱会确定了。'),
  ('ko-anime-intermediate-147', 'ko', 'intermediate', 'anime/drama', '월드투어', '월드투어', 'woldeuthueo', 'world tour, global tour', '世界巡演，全球巡回', '월드투어 일정이 발표됐어요.', 'The world tour schedule was announced.', '世界巡演日程公布了。'),
  ('ko-anime-intermediate-148', 'ko', 'intermediate', 'anime/drama', '셋리스트', '셋리스트', 'setriseuteu', 'setlist, song lineup', '歌单，演出曲目', '셋리스트가 완벽했어요.', 'The setlist was perfect.', '歌单很完美。'),
  ('ko-anime-intermediate-149', 'ko', 'intermediate', 'anime/drama', '떡상', '떡상', 'tteoksang', 'sudden rise in popularity, blowing up', '暴涨，突然火了', '이 배우가 갑자기 떡상했어요.', 'This actor suddenly blew up in popularity.', '这个演员突然爆红了。'),
  ('ko-anime-intermediate-150', 'ko', 'intermediate', 'anime/drama', '역주행', '역주행', 'yeokjuhaeng', 'chart reversal, delayed hit', '逆袭，逆行', '이 노래가 역주행하고 있어요.', 'This song is making a chart comeback.', '这首歌在逆袭上升。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
