-- Expand ja-life-basic to 150 curated entries (16-150)
-- Topic: daily life vocabulary for basic Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-life-basic-16', 'ja', 'basic', 'daily life', '椅子', 'いす', 'isu', 'chair, seat', '椅子, 座位', '椅子に座ってください。', 'Please sit on the chair.', '请坐在椅子上。'),
  ('ja-life-basic-17', 'ja', 'basic', 'daily life', '机', 'つくえ', 'tsukue', 'desk, table', '桌子, 书桌', '机の上に本があります。', 'There is a book on the desk.', '桌子上有一本书。'),
  ('ja-life-basic-18', 'ja', 'basic', 'daily life', '窓', 'まど', 'mado', 'window, opening', '窗户, 窗口', '窓を開けてもいいですか。', 'May I open the window?', '我可以开窗吗？'),
  ('ja-life-basic-19', 'ja', 'basic', 'daily life', 'ドア', 'どあ', 'doa', 'door, entrance', '门, 入口', 'ドアを閉めてください。', 'Please close the door.', '请关门。'),
  ('ja-life-basic-20', 'ja', 'basic', 'daily life', '部屋', 'へや', 'heya', 'room, space', '房间, 空间', '私の部屋は広いです。', 'My room is spacious.', '我的房间很宽敞。'),
  ('ja-life-basic-21', 'ja', 'basic', 'daily life', '台所', 'だいどころ', 'daidokoro', 'kitchen, cookroom', '厨房, 灶间', '台所で料理を作ります。', 'I cook in the kitchen.', '我在厨房做饭。'),
  ('ja-life-basic-22', 'ja', 'basic', 'daily life', 'お風呂', 'おふろ', 'ofuro', 'bath, bathtub', '浴缸, 洗澡', 'お風呂に入ります。', 'I take a bath.', '我去洗澡。'),
  ('ja-life-basic-23', 'ja', 'basic', 'daily life', 'トイレ', 'といれ', 'toire', 'toilet, restroom', '厕所, 洗手间', 'トイレはどこですか。', 'Where is the restroom?', '厕所在哪里？'),
  ('ja-life-basic-24', 'ja', 'basic', 'daily life', '玄関', 'げんかん', 'genkan', 'entrance, front door', '玄关, 门口', '玄関で靴を脱ぎます。', 'I take off my shoes at the entrance.', '我在玄关脱鞋。'),
  ('ja-life-basic-25', 'ja', 'basic', 'daily life', '庭', 'にわ', 'niwa', 'garden, yard', '院子, 花园', '庭に花が咲いています。', 'Flowers are blooming in the garden.', '院子里花开了。'),
  ('ja-life-basic-26', 'ja', 'basic', 'daily life', '冷蔵庫', 'れいぞうこ', 'reizouko', 'refrigerator, fridge', '冰箱, 冷藏柜', '冷蔵庫に牛乳があります。', 'There is milk in the fridge.', '冰箱里有牛奶。'),
  ('ja-life-basic-27', 'ja', 'basic', 'daily life', '洗濯機', 'せんたくき', 'sentakuki', 'washing machine, washer', '洗衣机, 洗涤机', '洗濯機を使います。', 'I use the washing machine.', '我用洗衣机。'),
  ('ja-life-basic-28', 'ja', 'basic', 'daily life', 'エアコン', 'えあこん', 'eakon', 'air conditioner, AC', '空调, 冷气', 'エアコンをつけてください。', 'Please turn on the air conditioner.', '请打开空调。'),
  ('ja-life-basic-29', 'ja', 'basic', 'daily life', 'テレビ', 'てれび', 'terebi', 'television, TV', '电视, 电视机', 'テレビを見ます。', 'I watch TV.', '我看电视。'),
  ('ja-life-basic-30', 'ja', 'basic', 'daily life', '電気', 'でんき', 'denki', 'electricity, light', '电, 电灯', '電気を消してください。', 'Please turn off the light.', '请关灯。'),
  ('ja-life-basic-31', 'ja', 'basic', 'daily life', '時計', 'とけい', 'tokei', 'clock, watch', '钟表, 手表', '時計を見てください。', 'Please look at the clock.', '请看看钟。'),
  ('ja-life-basic-32', 'ja', 'basic', 'daily life', '鍵', 'かぎ', 'kagi', 'key, lock', '钥匙, 锁', '鍵をなくしました。', 'I lost my key.', '我把钥匙弄丢了。'),
  ('ja-life-basic-33', 'ja', 'basic', 'daily life', '傘', 'かさ', 'kasa', 'umbrella, parasol', '伞, 雨伞', '傘を持っていきます。', 'I will bring an umbrella.', '我带上伞。'),
  ('ja-life-basic-34', 'ja', 'basic', 'daily life', '財布', 'さいふ', 'saifu', 'wallet, purse', '钱包, 皮夹', '財布を忘れました。', 'I forgot my wallet.', '我忘带钱包了。'),
  ('ja-life-basic-35', 'ja', 'basic', 'daily life', '携帯', 'けいたい', 'keitai', 'cellphone, mobile', '手机, 移动电话', '携帯が鳴っています。', 'The cellphone is ringing.', '手机在响。'),
  ('ja-life-basic-36', 'ja', 'basic', 'daily life', 'シャツ', 'しゃつ', 'shatsu', 'shirt, blouse', '衬衫, 上衣', '白いシャツを着ます。', 'I wear a white shirt.', '我穿白衬衫。'),
  ('ja-life-basic-37', 'ja', 'basic', 'daily life', 'ズボン', 'ずぼん', 'zubon', 'pants, trousers', '裤子, 长裤', '新しいズボンを買いました。', 'I bought new pants.', '我买了新裤子。'),
  ('ja-life-basic-38', 'ja', 'basic', 'daily life', 'スカート', 'すかーと', 'sukaato', 'skirt, dress', '裙子, 短裙', 'スカートが好きです。', 'I like skirts.', '我喜欢裙子。'),
  ('ja-life-basic-39', 'ja', 'basic', 'daily life', '靴', 'くつ', 'kutsu', 'shoes, footwear', '鞋子, 鞋', '靴を履きます。', 'I put on shoes.', '我穿鞋。'),
  ('ja-life-basic-40', 'ja', 'basic', 'daily life', '帽子', 'ぼうし', 'boushi', 'hat, cap', '帽子, 礼帽', '帽子をかぶります。', 'I wear a hat.', '我戴帽子。'),
  ('ja-life-basic-41', 'ja', 'basic', 'daily life', 'コート', 'こーと', 'kooto', 'coat, overcoat', '外套, 大衣', '寒いのでコートを着ます。', 'I wear a coat because it is cold.', '因为冷所以穿外套。'),
  ('ja-life-basic-42', 'ja', 'basic', 'daily life', '眼鏡', 'めがね', 'megane', 'glasses, spectacles', '眼镜, 眼睛', '眼鏡をかけています。', 'I am wearing glasses.', '我戴着眼镜。'),
  ('ja-life-basic-43', 'ja', 'basic', 'daily life', '頭', 'あたま', 'atama', 'head, brain', '头, 脑袋', '頭が痛いです。', 'I have a headache.', '我头疼。'),
  ('ja-life-basic-44', 'ja', 'basic', 'daily life', '目', 'め', 'me', 'eye, sight', '眼睛, 视力', '目が大きいです。', 'The eyes are big.', '眼睛很大。'),
  ('ja-life-basic-45', 'ja', 'basic', 'daily life', '耳', 'みみ', 'mimi', 'ear, hearing', '耳朵, 听力', '耳が痛いです。', 'My ear hurts.', '我耳朵疼。'),
  ('ja-life-basic-46', 'ja', 'basic', 'daily life', '口', 'くち', 'kuchi', 'mouth, opening', '嘴, 口', '口を大きく開けてください。', 'Please open your mouth wide.', '请把嘴张大。'),
  ('ja-life-basic-47', 'ja', 'basic', 'daily life', '鼻', 'はな', 'hana', 'nose, nasal', '鼻子, 鼻', '鼻が高いです。', 'The nose is tall.', '鼻子很挺。'),
  ('ja-life-basic-48', 'ja', 'basic', 'daily life', '手', 'て', 'te', 'hand, arm', '手, 手臂', '手を洗いましょう。', 'Let us wash our hands.', '我们洗手吧。'),
  ('ja-life-basic-49', 'ja', 'basic', 'daily life', '足', 'あし', 'ashi', 'foot, leg', '脚, 腿', '足が疲れました。', 'My legs are tired.', '我的腿累了。'),
  ('ja-life-basic-50', 'ja', 'basic', 'daily life', 'お腹', 'おなか', 'onaka', 'stomach, belly', '肚子, 腹部', 'お腹が空きました。', 'I am hungry.', '我饿了。'),
  ('ja-life-basic-51', 'ja', 'basic', 'daily life', '背中', 'せなか', 'senaka', 'back, spine', '背部, 后背', '背中が痛いです。', 'My back hurts.', '我背疼。'),
  ('ja-life-basic-52', 'ja', 'basic', 'daily life', '顔', 'かお', 'kao', 'face, expression', '脸, 表情', '顔を洗います。', 'I wash my face.', '我洗脸。'),
  ('ja-life-basic-53', 'ja', 'basic', 'daily life', '春', 'はる', 'haru', 'spring, springtime', '春天, 春季', '春は暖かいです。', 'Spring is warm.', '春天很暖和。'),
  ('ja-life-basic-54', 'ja', 'basic', 'daily life', '夏', 'なつ', 'natsu', 'summer, summertime', '夏天, 夏季', '夏は暑いです。', 'Summer is hot.', '夏天很热。'),
  ('ja-life-basic-55', 'ja', 'basic', 'daily life', '秋', 'あき', 'aki', 'autumn, fall', '秋天, 秋季', '秋は涼しいです。', 'Autumn is cool.', '秋天很凉爽。'),
  ('ja-life-basic-56', 'ja', 'basic', 'daily life', '冬', 'ふゆ', 'fuyu', 'winter, wintertime', '冬天, 冬季', '冬は寒いです。', 'Winter is cold.', '冬天很冷。'),
  ('ja-life-basic-57', 'ja', 'basic', 'daily life', '雨', 'あめ', 'ame', 'rain, rainfall', '雨, 下雨', '今日は雨です。', 'Today is rainy.', '今天下雨。'),
  ('ja-life-basic-58', 'ja', 'basic', 'daily life', '雪', 'ゆき', 'yuki', 'snow, snowfall', '雪, 下雪', '雪が降っています。', 'It is snowing.', '在下雪。'),
  ('ja-life-basic-59', 'ja', 'basic', 'daily life', '風', 'かぜ', 'kaze', 'wind, breeze', '风, 微风', '今日は風が強いです。', 'The wind is strong today.', '今天风很大。'),
  ('ja-life-basic-60', 'ja', 'basic', 'daily life', '空', 'そら', 'sora', 'sky, heavens', '天空, 天', '空がきれいです。', 'The sky is beautiful.', '天空很美。'),
  ('ja-life-basic-61', 'ja', 'basic', 'daily life', '曇り', 'くもり', 'kumori', 'cloudy, overcast', '阴天, 多云', '明日は曇りです。', 'Tomorrow will be cloudy.', '明天是阴天。'),
  ('ja-life-basic-62', 'ja', 'basic', 'daily life', '父', 'ちち', 'chichi', 'father, dad', '父亲, 爸爸', '父は会社員です。', 'My father is an office worker.', '我父亲是公司职员。'),
  ('ja-life-basic-63', 'ja', 'basic', 'daily life', '母', 'はは', 'haha', 'mother, mom', '母亲, 妈妈', '母は料理が上手です。', 'My mother is good at cooking.', '我母亲做饭很好吃。'),
  ('ja-life-basic-64', 'ja', 'basic', 'daily life', '兄', 'あに', 'ani', 'older brother, big brother', '哥哥, 兄长', '兄は大学生です。', 'My older brother is a college student.', '我哥哥是大学生。'),
  ('ja-life-basic-65', 'ja', 'basic', 'daily life', '姉', 'あね', 'ane', 'older sister, big sister', '姐姐, 姊姊', '姉は先生です。', 'My older sister is a teacher.', '我姐姐是老师。'),
  ('ja-life-basic-66', 'ja', 'basic', 'daily life', '弟', 'おとうと', 'otouto', 'younger brother, little brother', '弟弟, 小弟', '弟は高校生です。', 'My younger brother is a high school student.', '我弟弟是高中生。'),
  ('ja-life-basic-67', 'ja', 'basic', 'daily life', '妹', 'いもうと', 'imouto', 'younger sister, little sister', '妹妹, 小妹', '妹は中学生です。', 'My younger sister is a middle school student.', '我妹妹是初中生。'),
  ('ja-life-basic-68', 'ja', 'basic', 'daily life', '家族', 'かぞく', 'kazoku', 'family, household', '家人, 家庭', '家族は五人です。', 'My family has five people.', '我家有五口人。'),
  ('ja-life-basic-69', 'ja', 'basic', 'daily life', '友達', 'ともだち', 'tomodachi', 'friend, companion', '朋友, 伙伴', '友達と遊びます。', 'I hang out with friends.', '我和朋友玩。'),
  ('ja-life-basic-70', 'ja', 'basic', 'daily life', '赤', 'あか', 'aka', 'red, crimson', '红色, 赤色', '赤いりんごが好きです。', 'I like red apples.', '我喜欢红苹果。'),
  ('ja-life-basic-71', 'ja', 'basic', 'daily life', '青', 'あお', 'ao', 'blue, green', '蓝色, 青色', '空は青いです。', 'The sky is blue.', '天空是蓝色的。'),
  ('ja-life-basic-72', 'ja', 'basic', 'daily life', '白', 'しろ', 'shiro', 'white, blank', '白色, 洁白', '白い雲が見えます。', 'I can see white clouds.', '我能看到白云。'),
  ('ja-life-basic-73', 'ja', 'basic', 'daily life', '黒', 'くろ', 'kuro', 'black, dark', '黑色, 黑暗', '黒い猫がいます。', 'There is a black cat.', '有一只黑猫。'),
  ('ja-life-basic-74', 'ja', 'basic', 'daily life', '黄色', 'きいろ', 'kiiro', 'yellow, golden', '黄色, 金色', '黄色い花がきれいです。', 'The yellow flowers are beautiful.', '黄色的花很漂亮。'),
  ('ja-life-basic-75', 'ja', 'basic', 'daily life', '緑', 'みどり', 'midori', 'green, verdant', '绿色, 翠绿', '緑の木がたくさんあります。', 'There are many green trees.', '有很多绿色的树。'),
  ('ja-life-basic-76', 'ja', 'basic', 'daily life', '嬉しい', 'うれしい', 'ureshii', 'happy, glad', '高兴, 开心', 'プレゼントをもらって嬉しいです。', 'I am happy to receive a present.', '收到礼物很高兴。'),
  ('ja-life-basic-77', 'ja', 'basic', 'daily life', '悲しい', 'かなしい', 'kanashii', 'sad, sorrowful', '悲伤, 难过', '映画を見て悲しくなりました。', 'I became sad watching the movie.', '看了电影觉得难过。'),
  ('ja-life-basic-78', 'ja', 'basic', 'daily life', '楽しい', 'たのしい', 'tanoshii', 'fun, enjoyable', '快乐, 有趣', '旅行は楽しいです。', 'Traveling is fun.', '旅行很快乐。'),
  ('ja-life-basic-79', 'ja', 'basic', 'daily life', '怖い', 'こわい', 'kowai', 'scary, frightening', '可怕, 恐怖', 'あの映画は怖いです。', 'That movie is scary.', '那部电影很可怕。'),
  ('ja-life-basic-80', 'ja', 'basic', 'daily life', '疲れる', 'つかれる', 'tsukareru', 'tired, exhausted', '累, 疲倦', '今日は疲れました。', 'I am tired today.', '今天累了。'),
  ('ja-life-basic-81', 'ja', 'basic', 'daily life', '朝', 'あさ', 'asa', 'morning, dawn', '早上, 清晨', '朝ごはんを食べます。', 'I eat breakfast.', '我吃早饭。'),
  ('ja-life-basic-82', 'ja', 'basic', 'daily life', '昼', 'ひる', 'hiru', 'noon, daytime', '中午, 白天', '昼ごはんはカレーです。', 'Lunch is curry.', '午饭是咖喱。'),
  ('ja-life-basic-83', 'ja', 'basic', 'daily life', '夜', 'よる', 'yoru', 'night, evening', '晚上, 夜晚', '夜は静かです。', 'The night is quiet.', '晚上很安静。'),
  ('ja-life-basic-84', 'ja', 'basic', 'daily life', '今日', 'きょう', 'kyou', 'today, this day', '今天, 今日', '今日は天気がいいです。', 'The weather is nice today.', '今天天气很好。'),
  ('ja-life-basic-85', 'ja', 'basic', 'daily life', '明日', 'あした', 'ashita', 'tomorrow, next day', '明天, 明日', '明日は学校があります。', 'I have school tomorrow.', '明天有学校。'),
  ('ja-life-basic-86', 'ja', 'basic', 'daily life', '昨日', 'きのう', 'kinou', 'yesterday, previous day', '昨天, 昨日', '昨日は雨でした。', 'It was rainy yesterday.', '昨天下雨了。'),
  ('ja-life-basic-87', 'ja', 'basic', 'daily life', '先週', 'せんしゅう', 'senshuu', 'last week, previous week', '上周, 上星期', '先週映画を見ました。', 'I watched a movie last week.', '上周看了电影。'),
  ('ja-life-basic-88', 'ja', 'basic', 'daily life', '来週', 'らいしゅう', 'raishuu', 'next week, coming week', '下周, 下星期', '来週テストがあります。', 'There is a test next week.', '下周有考试。'),
  ('ja-life-basic-89', 'ja', 'basic', 'daily life', '毎日', 'まいにち', 'mainichi', 'every day, daily', '每天, 天天', '毎日運動します。', 'I exercise every day.', '我每天运动。'),
  ('ja-life-basic-90', 'ja', 'basic', 'daily life', '学校', 'がっこう', 'gakkou', 'school, academy', '学校, 学院', '学校まで歩きます。', 'I walk to school.', '我步行去学校。'),
  ('ja-life-basic-91', 'ja', 'basic', 'daily life', '会社', 'かいしゃ', 'kaisha', 'company, office', '公司, 单位', '会社に電車で行きます。', 'I go to the office by train.', '我坐电车去公司。'),
  ('ja-life-basic-92', 'ja', 'basic', 'daily life', '病院', 'びょういん', 'byouin', 'hospital, clinic', '医院, 诊所', '病院に行きます。', 'I go to the hospital.', '我去医院。'),
  ('ja-life-basic-93', 'ja', 'basic', 'daily life', '駅', 'えき', 'eki', 'station, stop', '车站, 站台', '駅はどこですか。', 'Where is the station?', '车站在哪里？'),
  ('ja-life-basic-94', 'ja', 'basic', 'daily life', '店', 'みせ', 'mise', 'shop, store', '店铺, 商店', 'あの店は安いです。', 'That shop is cheap.', '那家店很便宜。'),
  ('ja-life-basic-95', 'ja', 'basic', 'daily life', '公園', 'こうえん', 'kouen', 'park, garden', '公园, 花园', '公園で遊びます。', 'I play in the park.', '我在公园玩。'),
  ('ja-life-basic-96', 'ja', 'basic', 'daily life', '図書館', 'としょかん', 'toshokan', 'library, reading room', '图书馆, 书馆', '図書館で本を借ります。', 'I borrow books from the library.', '我在图书馆借书。'),
  ('ja-life-basic-97', 'ja', 'basic', 'daily life', '銀行', 'ぎんこう', 'ginkou', 'bank, financial institution', '银行, 金融机构', '銀行でお金をおろします。', 'I withdraw money at the bank.', '我在银行取钱。'),
  ('ja-life-basic-98', 'ja', 'basic', 'daily life', '映画', 'えいが', 'eiga', 'movie, film', '电影, 影片', '映画を見に行きます。', 'I go to watch a movie.', '我去看电影。'),
  ('ja-life-basic-99', 'ja', 'basic', 'daily life', '音楽', 'おんがく', 'ongaku', 'music, melody', '音乐, 乐曲', '音楽を聴きます。', 'I listen to music.', '我听音乐。'),
  ('ja-life-basic-100', 'ja', 'basic', 'daily life', '写真', 'しゃしん', 'shashin', 'photo, picture', '照片, 相片', '写真を撮ります。', 'I take a photo.', '我拍照。'),
  ('ja-life-basic-101', 'ja', 'basic', 'daily life', '旅行', 'りょこう', 'ryokou', 'travel, trip', '旅行, 旅游', '来月旅行に行きます。', 'I will go on a trip next month.', '下个月去旅行。'),
  ('ja-life-basic-102', 'ja', 'basic', 'daily life', 'スポーツ', 'すぽーつ', 'supootsu', 'sports, athletics', '运动, 体育', 'スポーツが好きです。', 'I like sports.', '我喜欢运动。'),
  ('ja-life-basic-103', 'ja', 'basic', 'daily life', '読む', 'よむ', 'yomu', 'read, recite', '读, 阅读', '毎晩本を読みます。', 'I read a book every night.', '我每晚读书。'),
  ('ja-life-basic-104', 'ja', 'basic', 'daily life', '書く', 'かく', 'kaku', 'write, draw', '写, 画', '日記を書きます。', 'I write a diary.', '我写日记。'),
  ('ja-life-basic-105', 'ja', 'basic', 'daily life', '聞く', 'きく', 'kiku', 'listen, ask', '听, 问', '先生に聞きます。', 'I ask the teacher.', '我问老师。'),
  ('ja-life-basic-106', 'ja', 'basic', 'daily life', '見る', 'みる', 'miru', 'see, watch', '看, 观看', '花火を見ます。', 'I watch fireworks.', '我看烟花。'),
  ('ja-life-basic-107', 'ja', 'basic', 'daily life', '走る', 'はしる', 'hashiru', 'run, dash', '跑, 奔跑', '公園で走ります。', 'I run in the park.', '我在公园跑步。'),
  ('ja-life-basic-108', 'ja', 'basic', 'daily life', '泳ぐ', 'およぐ', 'oyogu', 'swim, bathe', '游泳, 游', 'プールで泳ぎます。', 'I swim in the pool.', '我在游泳池游泳。'),
  ('ja-life-basic-109', 'ja', 'basic', 'daily life', '歌う', 'うたう', 'utau', 'sing, chant', '唱歌, 吟唱', 'カラオケで歌います。', 'I sing at karaoke.', '我在卡拉OK唱歌。'),
  ('ja-life-basic-110', 'ja', 'basic', 'daily life', '踊る', 'おどる', 'odoru', 'dance, move', '跳舞, 舞蹈', '一緒に踊りましょう。', 'Let us dance together.', '我们一起跳舞吧。'),
  ('ja-life-basic-111', 'ja', 'basic', 'daily life', '遊ぶ', 'あそぶ', 'asobu', 'play, have fun', '玩, 玩耍', '友達と遊びます。', 'I play with friends.', '我和朋友玩。'),
  ('ja-life-basic-112', 'ja', 'basic', 'daily life', '待つ', 'まつ', 'matsu', 'wait, expect', '等, 等待', 'ここで待ってください。', 'Please wait here.', '请在这里等。'),
  ('ja-life-basic-113', 'ja', 'basic', 'daily life', '座る', 'すわる', 'suwaru', 'sit, sit down', '坐, 坐下', 'ここに座ってください。', 'Please sit here.', '请坐在这里。'),
  ('ja-life-basic-114', 'ja', 'basic', 'daily life', '立つ', 'たつ', 'tatsu', 'stand, rise', '站, 站起来', 'まっすぐ立ってください。', 'Please stand up straight.', '请站直。'),
  ('ja-life-basic-115', 'ja', 'basic', 'daily life', '寝坊', 'ねぼう', 'nebou', 'oversleeping, sleeping in', '睡过头, 睡懒觉', '今朝寝坊しました。', 'I overslept this morning.', '我今早睡过头了。'),
  ('ja-life-basic-116', 'ja', 'basic', 'daily life', '大きい', 'おおきい', 'ookii', 'big, large', '大, 巨大', 'この犬は大きいです。', 'This dog is big.', '这只狗很大。'),
  ('ja-life-basic-117', 'ja', 'basic', 'daily life', '小さい', 'ちいさい', 'chiisai', 'small, little', '小, 微小', 'この猫は小さいです。', 'This cat is small.', '这只猫很小。'),
  ('ja-life-basic-118', 'ja', 'basic', 'daily life', '新しい', 'あたらしい', 'atarashii', 'new, fresh', '新, 崭新', '新しい靴を買いました。', 'I bought new shoes.', '我买了新鞋。'),
  ('ja-life-basic-119', 'ja', 'basic', 'daily life', '古い', 'ふるい', 'furui', 'old, ancient', '旧, 古老', 'この建物は古いです。', 'This building is old.', '这栋建筑很旧。'),
  ('ja-life-basic-120', 'ja', 'basic', 'daily life', '暑い', 'あつい', 'atsui', 'hot, warm', '热, 炎热', '今日は暑いです。', 'Today is hot.', '今天很热。'),
  ('ja-life-basic-121', 'ja', 'basic', 'daily life', '寒い', 'さむい', 'samui', 'cold, chilly', '冷, 寒冷', '外は寒いです。', 'It is cold outside.', '外面很冷。'),
  ('ja-life-basic-122', 'ja', 'basic', 'daily life', '暖かい', 'あたたかい', 'atatakai', 'warm, mild', '温暖, 暖和', '今日は暖かいです。', 'Today is warm.', '今天很暖和。'),
  ('ja-life-basic-123', 'ja', 'basic', 'daily life', '涼しい', 'すずしい', 'suzushii', 'cool, refreshing', '凉爽, 清凉', '秋は涼しくて気持ちいいです。', 'Autumn is cool and pleasant.', '秋天凉爽舒适。'),
  ('ja-life-basic-124', 'ja', 'basic', 'daily life', '高い', 'たかい', 'takai', 'expensive, tall', '贵, 高', 'この鞄は高いです。', 'This bag is expensive.', '这个包很贵。'),
  ('ja-life-basic-125', 'ja', 'basic', 'daily life', '安い', 'やすい', 'yasui', 'cheap, inexpensive', '便宜, 廉价', 'このTシャツは安いです。', 'This T-shirt is cheap.', '这件T恤很便宜。'),
  ('ja-life-basic-126', 'ja', 'basic', 'daily life', '近い', 'ちかい', 'chikai', 'near, close', '近, 靠近', '駅は近いです。', 'The station is close.', '车站很近。'),
  ('ja-life-basic-127', 'ja', 'basic', 'daily life', '遠い', 'とおい', 'tooi', 'far, distant', '远, 遥远', '空港は遠いです。', 'The airport is far.', '机场很远。'),
  ('ja-life-basic-128', 'ja', 'basic', 'daily life', '早い', 'はやい', 'hayai', 'early, fast', '早, 快', '朝早く起きます。', 'I wake up early in the morning.', '我早上很早起。'),
  ('ja-life-basic-129', 'ja', 'basic', 'daily life', '遅い', 'おそい', 'osoi', 'late, slow', '晚, 慢', '電車が遅いです。', 'The train is late.', '电车晚了。'),
  ('ja-life-basic-130', 'ja', 'basic', 'daily life', '元気', 'げんき', 'genki', 'healthy, energetic', '精神好, 健康', 'お元気ですか。', 'How are you?', '你好吗？'),
  ('ja-life-basic-131', 'ja', 'basic', 'daily life', '大丈夫', 'だいじょうぶ', 'daijoubu', 'okay, alright', '没关系, 没问题', '大丈夫ですか。', 'Are you okay?', '你没事吧？'),
  ('ja-life-basic-132', 'ja', 'basic', 'daily life', 'おはよう', 'おはよう', 'ohayou', 'good morning, morning greeting', '早上好, 早安', 'おはようございます。', 'Good morning.', '早上好。'),
  ('ja-life-basic-133', 'ja', 'basic', 'daily life', 'こんにちは', 'こんにちは', 'konnichiwa', 'hello, good afternoon', '你好, 午安', 'こんにちは、お元気ですか。', 'Hello, how are you?', '你好，你还好吗？'),
  ('ja-life-basic-134', 'ja', 'basic', 'daily life', 'こんばんは', 'こんばんは', 'konbanwa', 'good evening, evening greeting', '晚上好, 晚安', 'こんばんは、寒いですね。', 'Good evening, it is cold.', '晚上好，好冷啊。'),
  ('ja-life-basic-135', 'ja', 'basic', 'daily life', 'おやすみ', 'おやすみ', 'oyasumi', 'good night, sleep well', '晚安, 好梦', 'おやすみなさい。', 'Good night.', '晚安。'),
  ('ja-life-basic-136', 'ja', 'basic', 'daily life', 'ありがとう', 'ありがとう', 'arigatou', 'thank you, thanks', '谢谢, 感谢', 'ありがとうございます。', 'Thank you very much.', '非常感谢。'),
  ('ja-life-basic-137', 'ja', 'basic', 'daily life', 'すみません', 'すみません', 'sumimasen', 'excuse me, sorry', '对不起, 不好意思', 'すみません、道を教えてください。', 'Excuse me, please tell me the way.', '不好意思，请告诉我怎么走。'),
  ('ja-life-basic-138', 'ja', 'basic', 'daily life', '水', 'みず', 'mizu', 'water, cold water', '水, 冷水', '水を飲みます。', 'I drink water.', '我喝水。'),
  ('ja-life-basic-139', 'ja', 'basic', 'daily life', 'お茶', 'おちゃ', 'ocha', 'tea, green tea', '茶, 绿茶', 'お茶を飲みましょう。', 'Let us drink tea.', '我们喝茶吧。'),
  ('ja-life-basic-140', 'ja', 'basic', 'daily life', 'ご飯', 'ごはん', 'gohan', 'rice, meal', '米饭, 饭', 'ご飯を食べましょう。', 'Let us eat a meal.', '我们吃饭吧。'),
  ('ja-life-basic-141', 'ja', 'basic', 'daily life', 'パン', 'ぱん', 'pan', 'bread, bun', '面包, 包', '朝パンを食べます。', 'I eat bread in the morning.', '我早上吃面包。'),
  ('ja-life-basic-142', 'ja', 'basic', 'daily life', '卵', 'たまご', 'tamago', 'egg, ovum', '鸡蛋, 蛋', '卵を二つ買いました。', 'I bought two eggs.', '我买了两个鸡蛋。'),
  ('ja-life-basic-143', 'ja', 'basic', 'daily life', '肉', 'にく', 'niku', 'meat, flesh', '肉, 肉类', '肉が好きです。', 'I like meat.', '我喜欢吃肉。'),
  ('ja-life-basic-144', 'ja', 'basic', 'daily life', '魚', 'さかな', 'sakana', 'fish, seafood', '鱼, 海鲜', '魚を焼きます。', 'I grill fish.', '我烤鱼。'),
  ('ja-life-basic-145', 'ja', 'basic', 'daily life', '野菜', 'やさい', 'yasai', 'vegetable, greens', '蔬菜, 青菜', '野菜をたくさん食べます。', 'I eat a lot of vegetables.', '我吃很多蔬菜。'),
  ('ja-life-basic-146', 'ja', 'basic', 'daily life', '果物', 'くだもの', 'kudamono', 'fruit, produce', '水果, 果品', '果物が好きです。', 'I like fruit.', '我喜欢水果。'),
  ('ja-life-basic-147', 'ja', 'basic', 'daily life', '薬', 'くすり', 'kusuri', 'medicine, drug', '药, 药物', '薬を飲みます。', 'I take medicine.', '我吃药。'),
  ('ja-life-basic-148', 'ja', 'basic', 'daily life', '石鹸', 'せっけん', 'sekken', 'soap, cleanser', '肥皂, 香皂', '石鹸で手を洗います。', 'I wash my hands with soap.', '我用肥皂洗手。'),
  ('ja-life-basic-149', 'ja', 'basic', 'daily life', '歯ブラシ', 'はぶらし', 'haburashi', 'toothbrush, dental brush', '牙刷, 刷牙工具', '歯ブラシを買います。', 'I buy a toothbrush.', '我买牙刷。'),
  ('ja-life-basic-150', 'ja', 'basic', 'daily life', 'タオル', 'たおる', 'taoru', 'towel, cloth', '毛巾, 浴巾', 'タオルを使います。', 'I use a towel.', '我用毛巾。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
