-- Expand ko-verbs-basic to 150 curated entries (16-150)
-- Topic: common verbs for basic Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-verbs-basic-16', 'ko', 'basic', 'common verbs', '먹다', '먹다', 'meokda', 'to eat', '吃', '밥을 먹어요.', 'I eat rice.', '我吃饭。'),
  ('ko-verbs-basic-17', 'ko', 'basic', 'common verbs', '자다', '자다', 'jada', 'to sleep', '睡', '일찍 자요.', 'I go to bed early.', '我早睡。'),
  ('ko-verbs-basic-18', 'ko', 'basic', 'common verbs', '일어나다', '일어나다', 'ireonada', 'to wake up', '起来', '아침에 일어나요.', 'I wake up in the morning.', '我早上起来。'),
  ('ko-verbs-basic-19', 'ko', 'basic', 'common verbs', '하다', '하다', 'hada', 'to do', '做', '공부를 해요.', 'I study.', '我学习。'),
  ('ko-verbs-basic-20', 'ko', 'basic', 'common verbs', '있다', '있다', 'itda', 'to exist, to have', '有，在', '시간이 있어요.', 'I have time.', '我有时间。'),
  ('ko-verbs-basic-21', 'ko', 'basic', 'common verbs', '없다', '없다', 'eopda', 'to not exist', '没有', '돈이 없어요.', 'I don''t have money.', '我没有钱。'),
  ('ko-verbs-basic-22', 'ko', 'basic', 'common verbs', '알다', '알다', 'alda', 'to know', '知道', '이름을 알아요.', 'I know the name.', '我知道名字。'),
  ('ko-verbs-basic-23', 'ko', 'basic', 'common verbs', '모르다', '모르다', 'moreuda', 'to not know', '不知道', '잘 모르겠어요.', 'I don''t really know.', '我不太清楚。'),
  ('ko-verbs-basic-24', 'ko', 'basic', 'common verbs', '주다', '주다', 'juda', 'to give', '给', '선물을 줘요.', 'I give a gift.', '我送礼物。'),
  ('ko-verbs-basic-25', 'ko', 'basic', 'common verbs', '받다', '받다', 'batda', 'to receive', '收到', '선물을 받았어요.', 'I received a gift.', '我收到了礼物。'),
  ('ko-verbs-basic-26', 'ko', 'basic', 'common verbs', '만나다', '만나다', 'mannada', 'to meet', '见面', '친구를 만나요.', 'I meet a friend.', '我见朋友。'),
  ('ko-verbs-basic-27', 'ko', 'basic', 'common verbs', '좋아하다', '좋아하다', 'joahada', 'to like', '喜欢', '음악을 좋아해요.', 'I like music.', '我喜欢音乐。'),
  ('ko-verbs-basic-28', 'ko', 'basic', 'common verbs', '싫어하다', '싫어하다', 'sireohada', 'to dislike', '讨厌', '더운 날씨를 싫어해요.', 'I dislike hot weather.', '我讨厌热天。'),
  ('ko-verbs-basic-29', 'ko', 'basic', 'common verbs', '앉다', '앉다', 'anda', 'to sit', '坐', '여기 앉아요.', 'I sit here.', '我坐这儿。'),
  ('ko-verbs-basic-30', 'ko', 'basic', 'common verbs', '서다', '서다', 'seoda', 'to stand', '站', '줄에 서요.', 'I stand in line.', '我站队。'),
  ('ko-verbs-basic-31', 'ko', 'basic', 'common verbs', '걷다', '걷다', 'geotda', 'to walk', '走', '걸어서 가요.', 'I walk there.', '我走路去。'),
  ('ko-verbs-basic-32', 'ko', 'basic', 'common verbs', '달리다', '달리다', 'dallida', 'to run', '跑', '매일 달려요.', 'I run every day.', '我每天跑步。'),
  ('ko-verbs-basic-33', 'ko', 'basic', 'common verbs', '타다', '타다', 'tada', 'to ride', '坐，骑', '버스를 타요.', 'I ride the bus.', '我坐公交。'),
  ('ko-verbs-basic-34', 'ko', 'basic', 'common verbs', '내리다', '내리다', 'naerida', 'to get off', '下车', '여기서 내려요.', 'I get off here.', '我在这下车。'),
  ('ko-verbs-basic-35', 'ko', 'basic', 'common verbs', '놀다', '놀다', 'nolda', 'to play, hang out', '玩', '주말에 놀아요.', 'I hang out on weekends.', '我周末玩。'),
  ('ko-verbs-basic-36', 'ko', 'basic', 'common verbs', '쉬다', '쉬다', 'swida', 'to rest', '休息', '좀 쉬어요.', 'I rest a bit.', '我休息一下。'),
  ('ko-verbs-basic-37', 'ko', 'basic', 'common verbs', '일하다', '일하다', 'ilhada', 'to work', '工作', '매일 일해요.', 'I work every day.', '我每天工作。'),
  ('ko-verbs-basic-38', 'ko', 'basic', 'common verbs', '배우다', '배우다', 'baeuda', 'to learn', '学', '한국어를 배워요.', 'I learn Korean.', '我学韩语。'),
  ('ko-verbs-basic-39', 'ko', 'basic', 'common verbs', '가르치다', '가르치다', 'gareuchida', 'to teach', '教', '영어를 가르쳐요.', 'I teach English.', '我教英语。'),
  ('ko-verbs-basic-40', 'ko', 'basic', 'common verbs', '생각하다', '생각하다', 'saenggakhada', 'to think', '想', '좀 생각해 볼게요.', 'I''ll think about it.', '我想想。'),
  ('ko-verbs-basic-41', 'ko', 'basic', 'common verbs', '찾다', '찾다', 'chatda', 'to find, look for', '找', '열쇠를 찾아요.', 'I look for the keys.', '我找钥匙。'),
  ('ko-verbs-basic-42', 'ko', 'basic', 'common verbs', '물어보다', '물어보다', 'mureoboda', 'to ask', '问', '선생님에게 물어봐요.', 'I ask the teacher.', '我问老师。'),
  ('ko-verbs-basic-43', 'ko', 'basic', 'common verbs', '대답하다', '대답하다', 'daedaphada', 'to answer', '回答', '질문에 대답해요.', 'I answer the question.', '我回答问题。'),
  ('ko-verbs-basic-44', 'ko', 'basic', 'common verbs', '도와주다', '도와주다', 'dowajuda', 'to help', '帮忙', '좀 도와주세요.', 'Please help me.', '请帮帮我。'),
  ('ko-verbs-basic-45', 'ko', 'basic', 'common verbs', '보내다', '보내다', 'bonaeda', 'to send', '发送', '문자를 보내요.', 'I send a text.', '我发短信。'),
  ('ko-verbs-basic-46', 'ko', 'basic', 'common verbs', '전화하다', '전화하다', 'jeonhwahada', 'to call', '打电话', '친구에게 전화해요.', 'I call my friend.', '我给朋友打电话。'),
  ('ko-verbs-basic-47', 'ko', 'basic', 'common verbs', '입다', '입다', 'ipda', 'to wear (clothes)', '穿', '옷을 입어요.', 'I put on clothes.', '我穿衣服。'),
  ('ko-verbs-basic-48', 'ko', 'basic', 'common verbs', '벗다', '벗다', 'beotda', 'to take off', '脱', '코트를 벗어요.', 'I take off my coat.', '我脱外套。'),
  ('ko-verbs-basic-49', 'ko', 'basic', 'common verbs', '신다', '신다', 'sinda', 'to wear (shoes)', '穿（鞋）', '신발을 신어요.', 'I put on shoes.', '我穿鞋。'),
  ('ko-verbs-basic-50', 'ko', 'basic', 'common verbs', '쓰다', '쓰다', 'sseuda', 'to wear (hat/glasses)', '戴', '모자를 써요.', 'I wear a hat.', '我戴帽子。'),
  ('ko-verbs-basic-51', 'ko', 'basic', 'common verbs', '만들다', '만들다', 'mandeulda', 'to make', '做，制作', '음식을 만들어요.', 'I make food.', '我做食物。'),
  ('ko-verbs-basic-52', 'ko', 'basic', 'common verbs', '고치다', '고치다', 'gochida', 'to fix, repair', '修理', '컴퓨터를 고쳐요.', 'I fix the computer.', '我修电脑。'),
  ('ko-verbs-basic-53', 'ko', 'basic', 'common verbs', '바꾸다', '바꾸다', 'bakkuda', 'to change, exchange', '换', '옷을 바꿔요.', 'I change clothes.', '我换衣服。'),
  ('ko-verbs-basic-54', 'ko', 'basic', 'common verbs', '넣다', '넣다', 'neota', 'to put in', '放进去', '가방에 넣어요.', 'I put it in the bag.', '我放进包里。'),
  ('ko-verbs-basic-55', 'ko', 'basic', 'common verbs', '꺼내다', '꺼내다', 'kkeonaeda', 'to take out', '拿出来', '지갑을 꺼내요.', 'I take out my wallet.', '我拿出钱包。'),
  ('ko-verbs-basic-56', 'ko', 'basic', 'common verbs', '켜다', '켜다', 'kyeoda', 'to turn on', '打开', '전등을 켜요.', 'I turn on the light.', '我开灯。'),
  ('ko-verbs-basic-57', 'ko', 'basic', 'common verbs', '끄다', '끄다', 'kkeuda', 'to turn off', '关', '불을 꺼요.', 'I turn off the light.', '我关灯。'),
  ('ko-verbs-basic-58', 'ko', 'basic', 'common verbs', '잡다', '잡다', 'japda', 'to grab, catch', '抓', '손을 잡아요.', 'I hold hands.', '我牵手。'),
  ('ko-verbs-basic-59', 'ko', 'basic', 'common verbs', '놓다', '놓다', 'nota', 'to put down, release', '放下', '책상에 놓아요.', 'I put it on the desk.', '我放在桌子上。'),
  ('ko-verbs-basic-60', 'ko', 'basic', 'common verbs', '들다', '들다', 'deulda', 'to hold, lift', '拿，提', '짐을 들어요.', 'I carry the luggage.', '我提行李。'),
  ('ko-verbs-basic-61', 'ko', 'basic', 'common verbs', '던지다', '던지다', 'deonjida', 'to throw', '扔', '공을 던져요.', 'I throw a ball.', '我扔球。'),
  ('ko-verbs-basic-62', 'ko', 'basic', 'common verbs', '밀다', '밀다', 'milda', 'to push', '推', '문을 밀어요.', 'I push the door.', '我推门。'),
  ('ko-verbs-basic-63', 'ko', 'basic', 'common verbs', '당기다', '당기다', 'danggida', 'to pull', '拉', '문을 당겨요.', 'I pull the door.', '我拉门。'),
  ('ko-verbs-basic-64', 'ko', 'basic', 'common verbs', '올라가다', '올라가다', 'ollagada', 'to go up', '上去', '계단을 올라가요.', 'I go up the stairs.', '我上楼梯。'),
  ('ko-verbs-basic-65', 'ko', 'basic', 'common verbs', '내려가다', '내려가다', 'naeryeogada', 'to go down', '下去', '계단을 내려가요.', 'I go down the stairs.', '我下楼梯。'),
  ('ko-verbs-basic-66', 'ko', 'basic', 'common verbs', '들어가다', '들어가다', 'deureogada', 'to enter', '进去', '방에 들어가요.', 'I enter the room.', '我进房间。'),
  ('ko-verbs-basic-67', 'ko', 'basic', 'common verbs', '나가다', '나가다', 'nagada', 'to go out', '出去', '밖에 나가요.', 'I go outside.', '我出去。'),
  ('ko-verbs-basic-68', 'ko', 'basic', 'common verbs', '나오다', '나오다', 'naoda', 'to come out', '出来', '집에서 나와요.', 'I come out of the house.', '我从家出来。'),
  ('ko-verbs-basic-69', 'ko', 'basic', 'common verbs', '들어오다', '들어오다', 'deureoda', 'to come in', '进来', '안으로 들어오세요.', 'Please come in.', '请进来。'),
  ('ko-verbs-basic-70', 'ko', 'basic', 'common verbs', '지나다', '지나다', 'jinada', 'to pass', '经过', '시간이 지나요.', 'Time passes.', '时间过去了。'),
  ('ko-verbs-basic-71', 'ko', 'basic', 'common verbs', '건너다', '건너다', 'geonneoda', 'to cross', '过（马路）', '길을 건너요.', 'I cross the street.', '我过马路。'),
  ('ko-verbs-basic-72', 'ko', 'basic', 'common verbs', '움직이다', '움직이다', 'umjigida', 'to move', '动', '움직이지 마세요.', 'Please don''t move.', '请别动。'),
  ('ko-verbs-basic-73', 'ko', 'basic', 'common verbs', '멈추다', '멈추다', 'meomchuda', 'to stop', '停', '여기서 멈춰요.', 'I stop here.', '我在这停。'),
  ('ko-verbs-basic-74', 'ko', 'basic', 'common verbs', '시작하다', '시작하다', 'sijakhada', 'to start', '开始', '일을 시작해요.', 'I start work.', '我开始工作。'),
  ('ko-verbs-basic-75', 'ko', 'basic', 'common verbs', '끝나다', '끝나다', 'kkeutnada', 'to end', '结束', '수업이 끝났어요.', 'Class is over.', '课结束了。'),
  ('ko-verbs-basic-76', 'ko', 'basic', 'common verbs', '웃다', '웃다', 'utda', 'to laugh, smile', '笑', '크게 웃어요.', 'I laugh out loud.', '我大笑。'),
  ('ko-verbs-basic-77', 'ko', 'basic', 'common verbs', '울다', '울다', 'ulda', 'to cry', '哭', '아기가 울어요.', 'The baby is crying.', '宝宝在哭。'),
  ('ko-verbs-basic-78', 'ko', 'basic', 'common verbs', '노래하다', '노래하다', 'noraehada', 'to sing', '唱歌', '노래를 해요.', 'I sing.', '我唱歌。'),
  ('ko-verbs-basic-79', 'ko', 'basic', 'common verbs', '춤추다', '춤추다', 'chumchuda', 'to dance', '跳舞', '춤을 춰요.', 'I dance.', '我跳舞。'),
  ('ko-verbs-basic-80', 'ko', 'basic', 'common verbs', '그리다', '그리다', 'geurida', 'to draw', '画', '그림을 그려요.', 'I draw a picture.', '我画画。'),
  ('ko-verbs-basic-81', 'ko', 'basic', 'common verbs', '요리하다', '요리하다', 'yorihada', 'to cook', '做饭', '맛있게 요리해요.', 'I cook deliciously.', '我做得好吃。'),
  ('ko-verbs-basic-82', 'ko', 'basic', 'common verbs', '청소하다', '청소하다', 'cheongsohada', 'to clean', '打扫', '방을 청소해요.', 'I clean the room.', '我打扫房间。'),
  ('ko-verbs-basic-83', 'ko', 'basic', 'common verbs', '빨래하다', '빨래하다', 'ppallaehada', 'to do laundry', '洗衣服', '빨래를 해요.', 'I do laundry.', '我洗衣服。'),
  ('ko-verbs-basic-84', 'ko', 'basic', 'common verbs', '운동하다', '운동하다', 'undonghada', 'to exercise', '运动', '매일 운동해요.', 'I exercise every day.', '我每天运动。'),
  ('ko-verbs-basic-85', 'ko', 'basic', 'common verbs', '사랑하다', '사랑하다', 'saranghada', 'to love', '爱', '사랑해요.', 'I love you.', '我爱你。'),
  ('ko-verbs-basic-86', 'ko', 'basic', 'common verbs', '필요하다', '필요하다', 'piryohada', 'to need', '需要', '도움이 필요해요.', 'I need help.', '我需要帮助。'),
  ('ko-verbs-basic-87', 'ko', 'basic', 'common verbs', '원하다', '원하다', 'wonhada', 'to want', '想要', '이것을 원해요.', 'I want this.', '我想要这个。'),
  ('ko-verbs-basic-88', 'ko', 'basic', 'common verbs', '싶다', '싶다', 'sipda', 'to wish (want to)', '想（做某事）', '가고 싶어요.', 'I want to go.', '我想去。'),
  ('ko-verbs-basic-89', 'ko', 'basic', 'common verbs', '되다', '되다', 'doeda', 'to become', '成为', '의사가 되고 싶어요.', 'I want to become a doctor.', '我想成为医生。'),
  ('ko-verbs-basic-90', 'ko', 'basic', 'common verbs', '살다', '살다', 'salda', 'to live', '住', '서울에 살아요.', 'I live in Seoul.', '我住首尔。'),
  ('ko-verbs-basic-91', 'ko', 'basic', 'common verbs', '죽다', '죽다', 'jukda', 'to die', '死', '꽃이 죽었어요.', 'The flower died.', '花死了。'),
  ('ko-verbs-basic-92', 'ko', 'basic', 'common verbs', '나다', '나다', 'nada', 'to occur, happen', '出现', '소리가 나요.', 'A sound occurs.', '有声音。'),
  ('ko-verbs-basic-93', 'ko', 'basic', 'common verbs', '내다', '내다', 'naeda', 'to produce, pay', '出，交', '돈을 내요.', 'I pay.', '我付钱。'),
  ('ko-verbs-basic-94', 'ko', 'basic', 'common verbs', '타다', '타다', 'tada', 'to burn', '烧', '불이 타요.', 'The fire burns.', '火在烧。'),
  ('ko-verbs-basic-95', 'ko', 'basic', 'common verbs', '끓이다', '끓이다', 'kkeurida', 'to boil', '煮', '물을 끓여요.', 'I boil water.', '我烧水。'),
  ('ko-verbs-basic-96', 'ko', 'basic', 'common verbs', '자르다', '자르다', 'jareuda', 'to cut', '切', '종이를 잘라요.', 'I cut the paper.', '我切纸。'),
  ('ko-verbs-basic-97', 'ko', 'basic', 'common verbs', '붙이다', '붙이다', 'buchida', 'to stick, attach', '贴', '스티커를 붙여요.', 'I stick a sticker.', '我贴贴纸。'),
  ('ko-verbs-basic-98', 'ko', 'basic', 'common verbs', '빌리다', '빌리다', 'billida', 'to borrow', '借', '책을 빌려요.', 'I borrow a book.', '我借书。'),
  ('ko-verbs-basic-99', 'ko', 'basic', 'common verbs', '빌려주다', '빌려주다', 'billyeojuda', 'to lend', '借出', '우산을 빌려줘요.', 'I lend an umbrella.', '我借出伞。'),
  ('ko-verbs-basic-100', 'ko', 'basic', 'common verbs', '잃어버리다', '잃어버리다', 'ireobeorida', 'to lose', '丢失', '지갑을 잃어버렸어요.', 'I lost my wallet.', '我丢了钱包。'),
  ('ko-verbs-basic-101', 'ko', 'basic', 'common verbs', '찾아보다', '찾아보다', 'chajaboda', 'to look up, search', '查找', '인터넷에서 찾아봐요.', 'I look it up online.', '我在网上查。'),
  ('ko-verbs-basic-102', 'ko', 'basic', 'common verbs', '확인하다', '확인하다', 'hwaginhada', 'to confirm, check', '确认', '일정을 확인해요.', 'I check the schedule.', '我确认日程。'),
  ('ko-verbs-basic-103', 'ko', 'basic', 'common verbs', '준비하다', '준비하다', 'junbihada', 'to prepare', '准备', '내일을 준비해요.', 'I prepare for tomorrow.', '我为明天做准备。'),
  ('ko-verbs-basic-104', 'ko', 'basic', 'common verbs', '정리하다', '정리하다', 'jeongrihada', 'to organize, tidy', '整理', '방을 정리해요.', 'I tidy the room.', '我整理房间。'),
  ('ko-verbs-basic-105', 'ko', 'basic', 'common verbs', '예약하다', '예약하다', 'yeyakhada', 'to reserve', '预约', '식당을 예약해요.', 'I reserve a restaurant.', '我预约餐厅。'),
  ('ko-verbs-basic-106', 'ko', 'basic', 'common verbs', '취소하다', '취소하다', 'chwisohada', 'to cancel', '取消', '예약을 취소해요.', 'I cancel the reservation.', '我取消预约。'),
  ('ko-verbs-basic-107', 'ko', 'basic', 'common verbs', '결정하다', '결정하다', 'gyeoljeonghada', 'to decide', '决定', '빨리 결정해요.', 'I decide quickly.', '我快决定。'),
  ('ko-verbs-basic-108', 'ko', 'basic', 'common verbs', '선택하다', '선택하다', 'seontaekhada', 'to choose', '选择', '하나를 선택해요.', 'I choose one.', '我选一个。'),
  ('ko-verbs-basic-109', 'ko', 'basic', 'common verbs', '약속하다', '약속하다', 'yaksokhada', 'to promise', '约定', '내일 만나기로 약속해요.', 'I promise to meet tomorrow.', '我约好明天见面。'),
  ('ko-verbs-basic-110', 'ko', 'basic', 'common verbs', '기억하다', '기억하다', 'gieokhada', 'to remember', '记得', '이름을 기억해요.', 'I remember the name.', '我记得名字。'),
  ('ko-verbs-basic-111', 'ko', 'basic', 'common verbs', '잊다', '잊다', 'itda', 'to forget', '忘记', '비밀번호를 잊었어요.', 'I forgot the password.', '我忘了密码。'),
  ('ko-verbs-basic-112', 'ko', 'basic', 'common verbs', '이해하다', '이해하다', 'ihaehada', 'to understand', '理解', '잘 이해해요.', 'I understand well.', '我理解。'),
  ('ko-verbs-basic-113', 'ko', 'basic', 'common verbs', '설명하다', '설명하다', 'seolmyeonghada', 'to explain', '解释', '다시 설명해 주세요.', 'Please explain again.', '请再解释一下。'),
  ('ko-verbs-basic-114', 'ko', 'basic', 'common verbs', '인사하다', '인사하다', 'insahada', 'to greet', '打招呼', '이웃에게 인사해요.', 'I greet my neighbor.', '我跟邻居打招呼。'),
  ('ko-verbs-basic-115', 'ko', 'basic', 'common verbs', '소개하다', '소개하다', 'sogaehada', 'to introduce', '介绍', '친구를 소개해요.', 'I introduce my friend.', '我介绍朋友。'),
  ('ko-verbs-basic-116', 'ko', 'basic', 'common verbs', '초대하다', '초대하다', 'chodaehada', 'to invite', '邀请', '집에 초대해요.', 'I invite them home.', '我邀请到家里。'),
  ('ko-verbs-basic-117', 'ko', 'basic', 'common verbs', '축하하다', '축하하다', 'chukhahada', 'to congratulate', '祝贺', '생일을 축하해요.', 'I congratulate on the birthday.', '我祝贺生日。'),
  ('ko-verbs-basic-118', 'ko', 'basic', 'common verbs', '감사하다', '감사하다', 'gamsahada', 'to thank', '感谢', '정말 감사해요.', 'Thank you very much.', '非常感谢。'),
  ('ko-verbs-basic-119', 'ko', 'basic', 'common verbs', '사과하다', '사과하다', 'sagwahada', 'to apologize', '道歉', '진심으로 사과해요.', 'I sincerely apologize.', '我真心道歉。'),
  ('ko-verbs-basic-120', 'ko', 'basic', 'common verbs', '부탁하다', '부탁하다', 'butakhada', 'to request', '拜托', '부탁해요.', 'I ask you a favor.', '拜托了。'),
  ('ko-verbs-basic-121', 'ko', 'basic', 'common verbs', '포기하다', '포기하다', 'pogihada', 'to give up', '放弃', '포기하지 마세요.', 'Don''t give up.', '别放弃。'),
  ('ko-verbs-basic-122', 'ko', 'basic', 'common verbs', '노력하다', '노력하다', 'noryeokhada', 'to make effort', '努力', '열심히 노력해요.', 'I try hard.', '我努力。'),
  ('ko-verbs-basic-123', 'ko', 'basic', 'common verbs', '성공하다', '성공하다', 'seonggonghada', 'to succeed', '成功', '드디어 성공했어요.', 'I finally succeeded.', '终于成功了。'),
  ('ko-verbs-basic-124', 'ko', 'basic', 'common verbs', '실패하다', '실패하다', 'silpaehada', 'to fail', '失败', '시험에 실패했어요.', 'I failed the test.', '考试失败了。'),
  ('ko-verbs-basic-125', 'ko', 'basic', 'common verbs', '걸리다', '걸리다', 'geollida', 'to take (time)', '花（时间）', '한 시간 걸려요.', 'It takes one hour.', '需要一个小时。'),
  ('ko-verbs-basic-126', 'ko', 'basic', 'common verbs', '늦다', '늦다', 'neutda', 'to be late', '迟到', '늦었어요.', 'I''m late.', '我迟到了。'),
  ('ko-verbs-basic-127', 'ko', 'basic', 'common verbs', '서두르다', '서두르다', 'seodureuda', 'to hurry', '赶紧', '서둘러요!', 'Hurry up!', '快点！'),
  ('ko-verbs-basic-128', 'ko', 'basic', 'common verbs', '기다리다', '기다리다', 'gidarida', 'to wait', '等', '잠깐 기다려요.', 'Wait a moment.', '等一下。'),
  ('ko-verbs-basic-129', 'ko', 'basic', 'common verbs', '도착하다', '도착하다', 'dochakhada', 'to arrive', '到达', '공항에 도착했어요.', 'I arrived at the airport.', '我到机场了。'),
  ('ko-verbs-basic-130', 'ko', 'basic', 'common verbs', '출발하다', '출발하다', 'chulbalhada', 'to depart', '出发', '지금 출발해요.', 'I depart now.', '我现在出发。'),
  ('ko-verbs-basic-131', 'ko', 'basic', 'common verbs', '돌아오다', '돌아오다', 'doraoda', 'to come back', '回来', '집에 돌아왔어요.', 'I came back home.', '我回来了。'),
  ('ko-verbs-basic-132', 'ko', 'basic', 'common verbs', '데려가다', '데려가다', 'deryeogada', 'to take (person)', '带去', '병원에 데려가요.', 'I take them to the hospital.', '我带去医院。'),
  ('ko-verbs-basic-133', 'ko', 'basic', 'common verbs', '가져가다', '가져가다', 'gajyeogada', 'to take (thing)', '带走', '우산을 가져가요.', 'I take the umbrella.', '我带伞走。'),
  ('ko-verbs-basic-134', 'ko', 'basic', 'common verbs', '가져오다', '가져오다', 'gajyeooda', 'to bring (thing)', '带来', '물을 가져와요.', 'I bring water.', '我带水来。'),
  ('ko-verbs-basic-135', 'ko', 'basic', 'common verbs', '놀라다', '놀라다', 'nollada', 'to be surprised', '吃惊', '깜짝 놀랐어요.', 'I was startled.', '我吓了一跳。'),
  ('ko-verbs-basic-136', 'ko', 'basic', 'common verbs', '걱정하다', '걱정하다', 'geokjeonghada', 'to worry', '担心', '걱정하지 마세요.', 'Don''t worry.', '别担心。'),
  ('ko-verbs-basic-137', 'ko', 'basic', 'common verbs', '믿다', '믿다', 'mitda', 'to believe', '相信', '당신을 믿어요.', 'I believe you.', '我相信你。'),
  ('ko-verbs-basic-138', 'ko', 'basic', 'common verbs', '보이다', '보이다', 'boida', 'to be visible', '看得见', '바다가 보여요.', 'The sea is visible.', '能看到大海。'),
  ('ko-verbs-basic-139', 'ko', 'basic', 'common verbs', '들리다', '들리다', 'deullida', 'to be heard', '听得见', '음악이 들려요.', 'I can hear music.', '能听到音乐。'),
  ('ko-verbs-basic-140', 'ko', 'basic', 'common verbs', '느끼다', '느끼다', 'neukkida', 'to feel', '感觉', '행복을 느껴요.', 'I feel happiness.', '我感到幸福。'),
  ('ko-verbs-basic-141', 'ko', 'basic', 'common verbs', '냄새 나다', '냄새 나다', 'naemsae nada', 'to smell', '有味道', '꽃 냄새가 나요.', 'I can smell flowers.', '有花香。'),
  ('ko-verbs-basic-142', 'ko', 'basic', 'common verbs', '맛보다', '맛보다', 'matboda', 'to taste', '尝', '한번 맛봐요.', 'Try a taste.', '尝尝看。'),
  ('ko-verbs-basic-143', 'ko', 'basic', 'common verbs', '피하다', '피하다', 'pihada', 'to avoid', '避开', '비를 피해요.', 'I avoid the rain.', '我避雨。'),
  ('ko-verbs-basic-144', 'ko', 'basic', 'common verbs', '참다', '참다', 'chamda', 'to endure', '忍', '참을 수 없어요.', 'I can''t endure it.', '我忍不了。'),
  ('ko-verbs-basic-145', 'ko', 'basic', 'common verbs', '쉬다', '쉬다', 'swida', 'to rest, breathe', '休息', '좀 쉬세요.', 'Please rest.', '请休息一下。'),
  ('ko-verbs-basic-146', 'ko', 'basic', 'common verbs', '졸다', '졸다', 'jolda', 'to doze off', '打瞌睡', '수업 중에 졸아요.', 'I doze off during class.', '我上课打瞌睡。'),
  ('ko-verbs-basic-147', 'ko', 'basic', 'common verbs', '꿈꾸다', '꿈꾸다', 'kkumkkuda', 'to dream', '做梦', '좋은 꿈을 꿔요.', 'I have a good dream.', '我做了个好梦。'),
  ('ko-verbs-basic-148', 'ko', 'basic', 'common verbs', '깨다', '깨다', 'kkaeda', 'to wake, break', '醒来', '일찍 깼어요.', 'I woke up early.', '我早醒了。'),
  ('ko-verbs-basic-149', 'ko', 'basic', 'common verbs', '전하다', '전하다', 'jeonhada', 'to convey', '转告', '인사를 전해 주세요.', 'Please convey my greetings.', '请代我问好。'),
  ('ko-verbs-basic-150', 'ko', 'basic', 'common verbs', '지키다', '지키다', 'jikida', 'to protect, keep', '守护', '약속을 지켜요.', 'I keep my promise.', '我遵守约定。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
