-- Expand ja-food-intermediate to 150 curated entries (10-150)
-- Topic: food/cooking/cuisine vocabulary for intermediate Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-food-intermediate-10', 'ja', 'intermediate', 'food', '炒める', 'いためる', 'itameru', 'to stir-fry, to sauté', '炒，翻炒', '野菜を強火で炒めます。', 'I stir-fry the vegetables on high heat.', '用大火炒蔬菜。'),
  ('ja-food-intermediate-11', 'ja', 'intermediate', 'food', '蒸す', 'むす', 'musu', 'to steam, to steam-cook', '蒸，蒸煮', '魚を蒸して食べます。', 'I eat the fish steamed.', '把鱼蒸着吃。'),
  ('ja-food-intermediate-12', 'ja', 'intermediate', 'food', '揚げる', 'あげる', 'ageru', 'to deep-fry, to fry', '炸，油炸', 'エビを揚げて天ぷらにします。', 'I deep-fry the shrimp to make tempura.', '把虾炸成天妇罗。'),
  ('ja-food-intermediate-13', 'ja', 'intermediate', 'food', '煮込む', 'にこむ', 'nikomu', 'to simmer, to stew', '炖，焖煮', 'カレーを三時間煮込みました。', 'I simmered the curry for three hours.', '把咖喱炖了三个小时。'),
  ('ja-food-intermediate-14', 'ja', 'intermediate', 'food', '茹でる', 'ゆでる', 'yuderu', 'to boil, to blanch', '煮，焯', 'パスタを茹でます。', 'I boil the pasta.', '煮意大利面。'),
  ('ja-food-intermediate-15', 'ja', 'intermediate', 'food', '和える', 'あえる', 'aeru', 'to dress, to mix with sauce', '拌，调拌', 'ほうれん草をごまで和えます。', 'I dress the spinach with sesame.', '用芝麻拌菠菜。'),
  ('ja-food-intermediate-16', 'ja', 'intermediate', 'food', '漬ける', 'つける', 'tsukeru', 'to pickle, to marinate', '腌，浸泡', '大根を漬けて漬物にします。', 'I pickle the radish to make pickled vegetables.', '把萝卜腌成泡菜。'),
  ('ja-food-intermediate-17', 'ja', 'intermediate', 'food', '刻む', 'きざむ', 'kizamu', 'to chop finely, to mince', '切碎，剁碎', 'ネギを細かく刻みます。', 'I chop the green onion finely.', '把葱切碎。'),
  ('ja-food-intermediate-18', 'ja', 'intermediate', 'food', '下ごしらえ', 'したごしらえ', 'shitagoshirae', 'preparation, prep work', '预处理，准备工作', '下ごしらえをしっかりすると料理がおいしくなります。', 'Proper preparation makes the dish taste better.', '充分做好准备工作，菜会更好吃。'),
  ('ja-food-intermediate-19', 'ja', 'intermediate', 'food', '味付け', 'あじつけ', 'ajitsuke', 'seasoning, flavoring', '调味，调料', '味付けは薄めにしました。', 'I seasoned it lightly.', '调味做得比较清淡。'),
  ('ja-food-intermediate-20', 'ja', 'intermediate', 'food', '盛り付け', 'もりつけ', 'moritsuke', 'plating, presentation', '摆盘，装盘', '盛り付けを工夫すると食欲が増します。', 'Creative plating increases appetite.', '巧妙地摆盘可以增加食欲。'),
  ('ja-food-intermediate-21', 'ja', 'intermediate', 'food', '小麦粉', 'こむぎこ', 'komugiko', 'wheat flour, flour', '面粉，小麦粉', '小麦粉でパンを焼きます。', 'I bake bread with flour.', '用面粉烤面包。'),
  ('ja-food-intermediate-22', 'ja', 'intermediate', 'food', '片栗粉', 'かたくりこ', 'katakuriko', 'potato starch, cornstarch', '淀粉，太白粉', '片栗粉でとろみをつけます。', 'I thicken it with starch.', '用淀粉勾芡。'),
  ('ja-food-intermediate-23', 'ja', 'intermediate', 'food', '酢', 'す', 'su', 'vinegar, rice vinegar', '醋，米醋', '酢を少し加えてさっぱりさせます。', 'I add a little vinegar to make it refreshing.', '加一点醋使其更清爽。'),
  ('ja-food-intermediate-24', 'ja', 'intermediate', 'food', '味噌', 'みそ', 'miso', 'miso, soybean paste', '味噌，豆酱', '毎朝味噌汁を飲みます。', 'I drink miso soup every morning.', '每天早上喝味噌汤。'),
  ('ja-food-intermediate-25', 'ja', 'intermediate', 'food', '醤油', 'しょうゆ', 'shouyu', 'soy sauce', '酱油', '刺身に醤油をつけて食べます。', 'I eat sashimi with soy sauce.', '蘸酱油吃生鱼片。'),
  ('ja-food-intermediate-26', 'ja', 'intermediate', 'food', 'みりん', 'みりん', 'mirin', 'mirin, sweet rice wine', '味淋，料理酒', 'みりんを入れると甘みが出ます。', 'Adding mirin brings out sweetness.', '加入味淋会产生甜味。'),
  ('ja-food-intermediate-27', 'ja', 'intermediate', 'food', '出汁', 'だし', 'dashi', 'soup stock, broth', '高汤，汤底', '昆布と鰹節で出汁をとります。', 'I make stock from kelp and bonito flakes.', '用昆布和柴鱼片熬高汤。'),
  ('ja-food-intermediate-28', 'ja', 'intermediate', 'food', '和食', 'わしょく', 'washoku', 'Japanese cuisine, Japanese food', '日本料理，和食', '和食はユネスコの無形文化遺産です。', 'Japanese cuisine is a UNESCO intangible cultural heritage.', '日本料理是联合国教科文组织非物质文化遗产。'),
  ('ja-food-intermediate-29', 'ja', 'intermediate', 'food', '洋食', 'ようしょく', 'youshoku', 'Western-style food, Western cuisine', '西餐，洋食', '今日は洋食が食べたいです。', 'I want to eat Western food today.', '今天想吃西餐。'),
  ('ja-food-intermediate-30', 'ja', 'intermediate', 'food', '中華', 'ちゅうか', 'chuuka', 'Chinese cuisine, Chinese food', '中餐，中华料理', '中華料理が大好きです。', 'I love Chinese food.', '我非常喜欢中餐。'),
  ('ja-food-intermediate-31', 'ja', 'intermediate', 'food', '定食', 'ていしょく', 'teishoku', 'set meal, fixed menu', '套餐，定食', '今日のランチは焼き魚定食にしました。', 'I had the grilled fish set meal for lunch today.', '今天午餐吃了烤鱼套餐。'),
  ('ja-food-intermediate-32', 'ja', 'intermediate', 'food', '注文', 'ちゅうもん', 'chuumon', 'order, ordering food', '点餐，订单', '注文はお決まりですか。', 'Are you ready to order?', '您决定好点什么了吗？'),
  ('ja-food-intermediate-33', 'ja', 'intermediate', 'food', 'お会計', 'おかいけい', 'okaikei', 'bill, check', '结账，买单', 'お会計をお願いします。', 'The bill please.', '请结账。'),
  ('ja-food-intermediate-34', 'ja', 'intermediate', 'food', '包丁', 'ほうちょう', 'houchou', 'kitchen knife, chef''s knife', '菜刀，料理刀', '包丁を研ぎます。', 'I sharpen the kitchen knife.', '磨菜刀。'),
  ('ja-food-intermediate-35', 'ja', 'intermediate', 'food', 'まな板', 'まないた', 'manaita', 'cutting board, chopping board', '砧板，切菜板', 'まな板を消毒します。', 'I disinfect the cutting board.', '给砧板消毒。'),
  ('ja-food-intermediate-36', 'ja', 'intermediate', 'food', 'フライパン', 'ふらいぱん', 'furaipan', 'frying pan, skillet', '平底锅，煎锅', 'フライパンを熱します。', 'I heat the frying pan.', '加热平底锅。'),
  ('ja-food-intermediate-37', 'ja', 'intermediate', 'food', '鍋', 'なべ', 'nabe', 'pot, hot pot', '锅，火锅', '冬は鍋料理が人気です。', 'Hot pot is popular in winter.', '冬天火锅很受欢迎。'),
  ('ja-food-intermediate-38', 'ja', 'intermediate', 'food', 'おたま', 'おたま', 'otama', 'ladle, soup ladle', '汤勺，勺子', 'おたまでスープをすくいます。', 'I scoop soup with a ladle.', '用汤勺舀汤。'),
  ('ja-food-intermediate-39', 'ja', 'intermediate', 'food', 'さっぱり', 'さっぱり', 'sappari', 'refreshing, light-tasting', '清爽，清淡', 'さっぱりした味が好きです。', 'I like refreshing flavors.', '我喜欢清爽的味道。'),
  ('ja-food-intermediate-40', 'ja', 'intermediate', 'food', 'こってり', 'こってり', 'kotteri', 'rich, heavy, thick', '浓厚，油腻', 'こってりしたラーメンが食べたいです。', 'I want to eat rich ramen.', '想吃浓厚的拉面。'),
  ('ja-food-intermediate-41', 'ja', 'intermediate', 'food', 'もちもち', 'もちもち', 'mochimochi', 'chewy, glutinous texture', '软糯，有嚼劲', 'もちもちした食感が好きです。', 'I like chewy textures.', '我喜欢软糯的口感。'),
  ('ja-food-intermediate-42', 'ja', 'intermediate', 'food', 'カリカリ', 'かりかり', 'karikari', 'crispy, crunchy', '酥脆，脆脆的', 'カリカリに焼いたベーコンが好きです。', 'I like bacon cooked crispy.', '我喜欢煎得酥脆的培根。'),
  ('ja-food-intermediate-43', 'ja', 'intermediate', 'food', 'とろとろ', 'とろとろ', 'torotoro', 'melty, smooth, creamy', '浓稠，入口即化', 'とろとろのオムライスを作りました。', 'I made a melty omurice.', '做了入口即化的蛋包饭。'),
  ('ja-food-intermediate-44', 'ja', 'intermediate', 'food', '栄養', 'えいよう', 'eiyou', 'nutrition, nourishment', '营养，营养素', '栄養バランスを考えて食べます。', 'I eat considering nutritional balance.', '考虑营养均衡来吃饭。'),
  ('ja-food-intermediate-45', 'ja', 'intermediate', 'food', 'カロリー', 'かろりー', 'karorii', 'calorie, energy content', '卡路里，热量', 'カロリーを気にしています。', 'I watch my calorie intake.', '我在注意卡路里。'),
  ('ja-food-intermediate-46', 'ja', 'intermediate', 'food', 'アレルギー', 'あれるぎー', 'arerugii', 'allergy, food allergy', '过敏，食物过敏', '卵アレルギーがあります。', 'I have an egg allergy.', '我对鸡蛋过敏。'),
  ('ja-food-intermediate-47', 'ja', 'intermediate', 'food', '食物繊維', 'しょくもつせんい', 'shokumotsuseni', 'dietary fiber', '膳食纤维，食物纤维', '食物繊維が豊富な食品を選びます。', 'I choose foods rich in dietary fiber.', '我选择富含膳食纤维的食品。'),
  ('ja-food-intermediate-48', 'ja', 'intermediate', 'food', '糖質', 'とうしつ', 'toushitsu', 'carbohydrate, sugar content', '糖分，碳水化合物', '糖質制限ダイエットをしています。', 'I am on a low-carb diet.', '我在进行限糖饮食。'),
  ('ja-food-intermediate-49', 'ja', 'intermediate', 'food', '居酒屋', 'いざかや', 'izakaya', 'Japanese pub, tavern', '居酒屋，日式酒馆', '居酒屋で同僚と飲みます。', 'I drink with colleagues at an izakaya.', '在居酒屋和同事喝酒。'),
  ('ja-food-intermediate-50', 'ja', 'intermediate', 'food', '食べ放題', 'たべほうだい', 'tabehoudai', 'all-you-can-eat, buffet', '自助餐，无限量供应', '焼肉の食べ放題に行きました。', 'I went to an all-you-can-eat BBQ.', '去了烤肉自助餐。'),
  ('ja-food-intermediate-51', 'ja', 'intermediate', 'food', '割り勘', 'わりかん', 'warikan', 'splitting the bill, going Dutch', '均摊，AA制', '今日は割り勘にしましょう。', 'Let''s split the bill today.', '今天我们AA吧。'),
  ('ja-food-intermediate-52', 'ja', 'intermediate', 'food', '予約', 'よやく', 'yoyaku', 'reservation, booking', '预约，预订', 'レストランを予約しました。', 'I made a restaurant reservation.', '预约了餐厅。'),
  ('ja-food-intermediate-53', 'ja', 'intermediate', 'food', 'テイクアウト', 'ていくあうと', 'teikuauto', 'takeout, to-go', '外带，打包', 'テイクアウトでお願いします。', 'For takeout please.', '请打包。'),
  ('ja-food-intermediate-54', 'ja', 'intermediate', 'food', '弁当', 'べんとう', 'bentou', 'lunch box, bento', '便当，盒饭', '毎日弁当を作っています。', 'I make a bento every day.', '每天做便当。'),
  ('ja-food-intermediate-55', 'ja', 'intermediate', 'food', '惣菜', 'そうざい', 'souzai', 'side dish, deli food', '熟食，配菜', 'スーパーで惣菜を買いました。', 'I bought side dishes at the supermarket.', '在超市买了熟食。'),
  ('ja-food-intermediate-56', 'ja', 'intermediate', 'food', '缶詰', 'かんづめ', 'kandume', 'canned food, tinned food', '罐头，罐装食品', '非常食として缶詰を備蓄しています。', 'I stock canned food for emergencies.', '储备罐头作为应急食品。'),
  ('ja-food-intermediate-57', 'ja', 'intermediate', 'food', '冷凍食品', 'れいとうしょくひん', 'reitou shokuhin', 'frozen food', '冷冻食品', '冷凍食品は便利です。', 'Frozen food is convenient.', '冷冻食品很方便。'),
  ('ja-food-intermediate-58', 'ja', 'intermediate', 'food', '賞味期限', 'しょうみきげん', 'shoumikigen', 'best-before date, expiration date', '保质期，赏味期限', '賞味期限を確認してください。', 'Please check the best-before date.', '请确认保质期。'),
  ('ja-food-intermediate-59', 'ja', 'intermediate', 'food', '添加物', 'てんかぶつ', 'tenkabutsu', 'food additive, preservative', '添加剂，食品添加物', '添加物の少ない食品を選びます。', 'I choose foods with fewer additives.', '我选择添加剂少的食品。'),
  ('ja-food-intermediate-60', 'ja', 'intermediate', 'food', '有機', 'ゆうき', 'yuuki', 'organic, natural', '有机，天然', '有機野菜を買っています。', 'I buy organic vegetables.', '我买有机蔬菜。'),
  ('ja-food-intermediate-61', 'ja', 'intermediate', 'food', '産地', 'さんち', 'sanchi', 'place of origin, production area', '产地，产区', '野菜の産地を気にします。', 'I pay attention to where vegetables come from.', '我注意蔬菜的产地。'),
  ('ja-food-intermediate-62', 'ja', 'intermediate', 'food', '旬', 'しゅん', 'shun', 'in season, seasonal', '时令，当季', '旬の果物は甘くておいしいです。', 'Seasonal fruits are sweet and delicious.', '时令水果又甜又好吃。'),
  ('ja-food-intermediate-63', 'ja', 'intermediate', 'food', '大さじ', 'おおさじ', 'oosaji', 'tablespoon', '大勺，汤匙', '砂糖を大さじ二杯入れます。', 'Add two tablespoons of sugar.', '加入两大勺糖。'),
  ('ja-food-intermediate-64', 'ja', 'intermediate', 'food', '小さじ', 'こさじ', 'kosaji', 'teaspoon', '小勺，茶匙', '塩を小さじ一杯加えます。', 'Add one teaspoon of salt.', '加入一小勺盐。'),
  ('ja-food-intermediate-65', 'ja', 'intermediate', 'food', '適量', 'てきりょう', 'tekiryou', 'appropriate amount, to taste', '适量，适当的量', '胡椒を適量振りかけます。', 'Sprinkle pepper to taste.', '撒适量胡椒粉。'),
  ('ja-food-intermediate-66', 'ja', 'intermediate', 'food', '強火', 'つよび', 'tsuyobi', 'high heat, strong flame', '大火，强火', '強火で一気に焼きます。', 'I cook it quickly on high heat.', '用大火快速烤。'),
  ('ja-food-intermediate-67', 'ja', 'intermediate', 'food', '弱火', 'よわび', 'yowabi', 'low heat, gentle flame', '小火，弱火', '弱火でじっくり煮ます。', 'I simmer it slowly on low heat.', '用小火慢慢炖。'),
  ('ja-food-intermediate-68', 'ja', 'intermediate', 'food', '中火', 'ちゅうび', 'chuubi', 'medium heat', '中火', '中火で五分炒めます。', 'Stir-fry on medium heat for five minutes.', '用中火炒五分钟。'),
  ('ja-food-intermediate-69', 'ja', 'intermediate', 'food', '沸騰', 'ふっとう', 'futtou', 'boiling, to boil', '沸腾，烧开', 'お湯が沸騰したらパスタを入れます。', 'When the water boils, add the pasta.', '水沸腾后放入意面。'),
  ('ja-food-intermediate-70', 'ja', 'intermediate', 'food', '灰汁', 'あく', 'aku', 'scum, foam from boiling', '浮沫，杂质', '灰汁を丁寧に取り除きます。', 'I carefully remove the scum.', '仔细去除浮沫。'),
  ('ja-food-intermediate-71', 'ja', 'intermediate', 'food', '隠し味', 'かくしあじ', 'kakushiaji', 'secret ingredient, hidden flavor', '提味，秘诀调料', '隠し味にチョコレートを入れました。', 'I added chocolate as a secret ingredient.', '加了巧克力作为提味。'),
  ('ja-food-intermediate-72', 'ja', 'intermediate', 'food', '食感', 'しょっかん', 'shokkan', 'texture, mouthfeel', '口感，食感', 'この料理は食感が良いです。', 'This dish has a good texture.', '这道菜口感很好。'),
  ('ja-food-intermediate-73', 'ja', 'intermediate', 'food', '薄味', 'うすあじ', 'usuaji', 'mild flavor, lightly seasoned', '清淡，味道淡', '薄味の料理が体に良いです。', 'Lightly seasoned food is good for health.', '清淡的菜对身体好。'),
  ('ja-food-intermediate-74', 'ja', 'intermediate', 'food', '濃い味', 'こいあじ', 'koiaji', 'strong flavor, rich taste', '味道浓，重口味', '濃い味のラーメンが好きです。', 'I like ramen with a strong flavor.', '我喜欢味道浓的拉面。'),
  ('ja-food-intermediate-75', 'ja', 'intermediate', 'food', '甘口', 'あまくち', 'amakuchi', 'sweet, mild (spice)', '甜口，不辣', '子供には甘口のカレーを作ります。', 'I make mild curry for children.', '给孩子做甜口咖喱。'),
  ('ja-food-intermediate-76', 'ja', 'intermediate', 'food', '辛口', 'からくち', 'karakuchi', 'spicy, hot, dry', '辣口，辛辣', '辛口のカレーが好みです。', 'I prefer spicy curry.', '我偏好辣口咖喱。'),
  ('ja-food-intermediate-77', 'ja', 'intermediate', 'food', '酸味', 'さんみ', 'sanmi', 'sourness, acidity', '酸味，酸度', '酸味が効いたドレッシングです。', 'It''s a dressing with pronounced sourness.', '这是酸味突出的调味汁。'),
  ('ja-food-intermediate-78', 'ja', 'intermediate', 'food', '苦味', 'にがみ', 'nigami', 'bitterness, bitter taste', '苦味，涩味', 'ゴーヤの苦味が好きです。', 'I like the bitterness of bitter melon.', '我喜欢苦瓜的苦味。'),
  ('ja-food-intermediate-79', 'ja', 'intermediate', 'food', '旨味', 'うまみ', 'umami', 'umami, savory taste', '鲜味，旨味', '昆布には旨味成分が豊富です。', 'Kelp is rich in umami components.', '昆布富含鲜味成分。'),
  ('ja-food-intermediate-80', 'ja', 'intermediate', 'food', '塩味', 'しおあじ', 'shioaji', 'salty taste, salt flavor', '咸味，盐味', '塩味のラーメンを注文しました。', 'I ordered salt-flavored ramen.', '点了盐味拉面。'),
  ('ja-food-intermediate-81', 'ja', 'intermediate', 'food', '刺身', 'さしみ', 'sashimi', 'sashimi, raw fish slices', '刺身，生鱼片', '新鮮な刺身を食べました。', 'I ate fresh sashimi.', '吃了新鲜的生鱼片。'),
  ('ja-food-intermediate-82', 'ja', 'intermediate', 'food', '天ぷら', 'てんぷら', 'tenpura', 'tempura, deep-fried food', '天妇罗，炸物', '天ぷらをカラッと揚げるコツがあります。', 'There are tricks to frying tempura crispy.', '有把天妇罗炸得酥脆的技巧。'),
  ('ja-food-intermediate-83', 'ja', 'intermediate', 'food', '丼', 'どんぶり', 'donburi', 'rice bowl, donburi', '盖饭，丼', '牛丼を昼食に食べます。', 'I eat gyudon for lunch.', '午餐吃牛肉盖饭。'),
  ('ja-food-intermediate-84', 'ja', 'intermediate', 'food', 'おにぎり', 'おにぎり', 'onigiri', 'rice ball, onigiri', '饭团，御握', 'おにぎりを三つ作りました。', 'I made three rice balls.', '做了三个饭团。'),
  ('ja-food-intermediate-85', 'ja', 'intermediate', 'food', '味見', 'あじみ', 'ajimi', 'tasting, sampling', '试味，品尝', '味見をしてから塩を加えます。', 'I taste before adding salt.', '先试味再加盐。'),
  ('ja-food-intermediate-86', 'ja', 'intermediate', 'food', '薬味', 'やくみ', 'yakumi', 'condiment, garnish', '佐料，配料', '薬味にネギとわさびを添えます。', 'I add green onion and wasabi as condiments.', '添加葱和芥末作为佐料。'),
  ('ja-food-intermediate-87', 'ja', 'intermediate', 'food', '付け合わせ', 'つけあわせ', 'tsukeawase', 'side dish, garnish', '配菜，装饰', '付け合わせにサラダを添えます。', 'I add a salad as a side dish.', '配上沙拉作为配菜。'),
  ('ja-food-intermediate-88', 'ja', 'intermediate', 'food', '前菜', 'ぜんさい', 'zensai', 'appetizer, starter', '前菜，开胃菜', '前菜にカルパッチョを頼みました。', 'I ordered carpaccio as an appetizer.', '点了意式生肉片作为前菜。'),
  ('ja-food-intermediate-89', 'ja', 'intermediate', 'food', 'デザート', 'でざーと', 'dezaato', 'dessert, sweet', '甜点，甜品', 'デザートにケーキを食べました。', 'I had cake for dessert.', '甜点吃了蛋糕。'),
  ('ja-food-intermediate-90', 'ja', 'intermediate', 'food', '食欲', 'しょくよく', 'shokuyoku', 'appetite, desire to eat', '食欲，胃口', '夏は食欲が落ちます。', 'Appetite decreases in summer.', '夏天食欲下降。'),
  ('ja-food-intermediate-91', 'ja', 'intermediate', 'food', '満腹', 'まんぷく', 'manpuku', 'full stomach, satiated', '饱腹，吃饱', '満腹でもう食べられません。', 'I''m full and can''t eat anymore.', '吃饱了，吃不下了。'),
  ('ja-food-intermediate-92', 'ja', 'intermediate', 'food', '空腹', 'くうふく', 'kuufuku', 'empty stomach, hungry', '空腹，饥饿', '空腹で集中できません。', 'I can''t concentrate on an empty stomach.', '肚子饿了无法集中。'),
  ('ja-food-intermediate-93', 'ja', 'intermediate', 'food', '好き嫌い', 'すききらい', 'sukikirai', 'likes and dislikes, picky eating', '挑食，好恶', '好き嫌いが多い子供です。', 'The child is a picky eater.', '是个挑食的孩子。'),
  ('ja-food-intermediate-94', 'ja', 'intermediate', 'food', '作り置き', 'つくりおき', 'tsukurioki', 'meal prep, prepared in advance', '预制菜，提前做好', '週末に作り置きをしています。', 'I do meal prep on weekends.', '周末提前做好菜。'),
  ('ja-food-intermediate-95', 'ja', 'intermediate', 'food', '自炊', 'じすい', 'jisui', 'cooking for oneself, self-catering', '自己做饭，自炊', '一人暮らしで自炊を始めました。', 'I started cooking for myself living alone.', '独自生活后开始自己做饭。'),
  ('ja-food-intermediate-96', 'ja', 'intermediate', 'food', '外食', 'がいしょく', 'gaishoku', 'eating out, dining out', '外食，在外吃饭', '外食が多いと体に悪いです。', 'Eating out too much is bad for health.', '经常外食对身体不好。'),
  ('ja-food-intermediate-97', 'ja', 'intermediate', 'food', '食べ残し', 'たべのこし', 'tabenokoshi', 'leftovers, uneaten food', '剩菜，吃剩的', '食べ残しを減らしましょう。', 'Let''s reduce food waste.', '让我们减少剩菜。'),
  ('ja-food-intermediate-98', 'ja', 'intermediate', 'food', '食品ロス', 'しょくひんろす', 'shokuhin rosu', 'food waste, food loss', '食品浪费，食物损失', '食品ロスは社会問題です。', 'Food waste is a social issue.', '食品浪费是社会问题。'),
  ('ja-food-intermediate-99', 'ja', 'intermediate', 'food', '発酵', 'はっこう', 'hakkou', 'fermentation, fermenting', '发酵，酿造', '納豆は大豆を発酵させた食品です。', 'Natto is fermented soybean food.', '纳豆是发酵大豆食品。'),
  ('ja-food-intermediate-100', 'ja', 'intermediate', 'food', '保存', 'ほぞん', 'hozon', 'preservation, storage', '保存，储存', '冷蔵庫で保存してください。', 'Please store in the refrigerator.', '请在冰箱中保存。'),
  ('ja-food-intermediate-101', 'ja', 'intermediate', 'food', '解凍', 'かいとう', 'kaitou', 'thawing, defrosting', '解冻，化冻', '肉を電子レンジで解凍します。', 'I thaw meat in the microwave.', '用微波炉解冻肉。'),
  ('ja-food-intermediate-102', 'ja', 'intermediate', 'food', '常温', 'じょうおん', 'jouon', 'room temperature', '常温，室温', '常温で保存できます。', 'It can be stored at room temperature.', '可以在常温下保存。'),
  ('ja-food-intermediate-103', 'ja', 'intermediate', 'food', 'コンロ', 'こんろ', 'konro', 'stove, burner, cooktop', '灶台，炉子', 'ガスコンロで料理します。', 'I cook on a gas stove.', '用燃气灶做菜。'),
  ('ja-food-intermediate-104', 'ja', 'intermediate', 'food', '電子レンジ', 'でんしれんじ', 'denshi renji', 'microwave oven', '微波炉', '電子レンジで温めます。', 'I heat it in the microwave.', '用微波炉加热。'),
  ('ja-food-intermediate-105', 'ja', 'intermediate', 'food', 'オーブン', 'おーぶん', 'oobun', 'oven', '烤箱，烤炉', 'オーブンでケーキを焼きます。', 'I bake a cake in the oven.', '用烤箱烤蛋糕。'),
  ('ja-food-intermediate-106', 'ja', 'intermediate', 'food', '炊飯器', 'すいはんき', 'suihanki', 'rice cooker', '电饭煲，电饭锅', '炊飯器でご飯を炊きます。', 'I cook rice in the rice cooker.', '用电饭煲煮饭。'),
  ('ja-food-intermediate-107', 'ja', 'intermediate', 'food', 'ざる', 'ざる', 'zaru', 'colander, strainer, bamboo sieve', '竹筛，漏勺', 'ざるに野菜をあげて水を切ります。', 'I drain the vegetables in a colander.', '用竹筛沥干蔬菜的水。'),
  ('ja-food-intermediate-108', 'ja', 'intermediate', 'food', '泡立て器', 'あわだてき', 'awadateki', 'whisk, egg beater', '打蛋器，搅拌器', '泡立て器で卵を混ぜます。', 'I mix eggs with a whisk.', '用打蛋器搅拌鸡蛋。'),
  ('ja-food-intermediate-109', 'ja', 'intermediate', 'food', '計量カップ', 'けいりょうかっぷ', 'keiryou kappu', 'measuring cup', '量杯', '計量カップで水を量ります。', 'I measure water with a measuring cup.', '用量杯量水。'),
  ('ja-food-intermediate-110', 'ja', 'intermediate', 'food', '乳製品', 'にゅうせいひん', 'nyuuseihin', 'dairy products, milk products', '乳制品，奶制品', '乳製品でカルシウムを摂ります。', 'I get calcium from dairy products.', '通过乳制品摄取钙。'),
  ('ja-food-intermediate-111', 'ja', 'intermediate', 'food', '穀物', 'こくもつ', 'kokumotsu', 'grain, cereal', '谷物，粮食', '穀物は主要なエネルギー源です。', 'Grains are a primary energy source.', '谷物是主要的能量来源。'),
  ('ja-food-intermediate-112', 'ja', 'intermediate', 'food', '豆腐', 'とうふ', 'toufu', 'tofu, bean curd', '豆腐', '豆腐はたんぱく質が豊富です。', 'Tofu is rich in protein.', '豆腐富含蛋白质。'),
  ('ja-food-intermediate-113', 'ja', 'intermediate', 'food', '海藻', 'かいそう', 'kaisou', 'seaweed, marine algae', '海藻，海带', '海藻にはミネラルが多いです。', 'Seaweed is rich in minerals.', '海藻含有丰富的矿物质。'),
  ('ja-food-intermediate-114', 'ja', 'intermediate', 'food', '香辛料', 'こうしんりょう', 'koushinryou', 'spice, seasoning', '香辛料，调味料', '香辛料を使って本格的な味にします。', 'I use spices for authentic flavor.', '使用香辛料做出正宗的味道。'),
  ('ja-food-intermediate-115', 'ja', 'intermediate', 'food', '薄力粉', 'はくりきこ', 'hakurikiko', 'cake flour, soft flour', '低筋面粉，薄力粉', '薄力粉でクッキーを作ります。', 'I make cookies with cake flour.', '用低筋面粉做饼干。'),
  ('ja-food-intermediate-116', 'ja', 'intermediate', 'food', '強力粉', 'きょうりきこ', 'kyourikiko', 'bread flour, strong flour', '高筋面粉，强力粉', '強力粉はパン作りに向いています。', 'Bread flour is suitable for making bread.', '高筋面粉适合做面包。'),
  ('ja-food-intermediate-117', 'ja', 'intermediate', 'food', 'ベーキングパウダー', 'べーきんぐぱうだー', 'beekingu paudaa', 'baking powder', '泡打粉，发酵粉', 'ベーキングパウダーで生地を膨らませます。', 'I make the dough rise with baking powder.', '用泡打粉让面团膨胀。'),
  ('ja-food-intermediate-118', 'ja', 'intermediate', 'food', '生クリーム', 'なまくりーむ', 'nama kuriimu', 'fresh cream, whipping cream', '鲜奶油，生奶油', '生クリームを泡立てます。', 'I whip the fresh cream.', '打发鲜奶油。'),
  ('ja-food-intermediate-119', 'ja', 'intermediate', 'food', 'バター', 'ばたー', 'bataa', 'butter', '黄油，奶油', 'バターを溶かしてソースを作ります。', 'I melt butter to make a sauce.', '融化黄油做酱汁。'),
  ('ja-food-intermediate-120', 'ja', 'intermediate', 'food', '生地', 'きじ', 'kiji', 'dough, batter, fabric', '面团，面糊', '生地を三十分寝かせます。', 'Let the dough rest for thirty minutes.', '让面团静置三十分钟。'),
  ('ja-food-intermediate-121', 'ja', 'intermediate', 'food', '食中毒', 'しょくちゅうどく', 'shokuchuudoku', 'food poisoning', '食物中毒', '夏は食中毒に注意が必要です。', 'You need to be careful of food poisoning in summer.', '夏天需要注意食物中毒。'),
  ('ja-food-intermediate-122', 'ja', 'intermediate', 'food', '衛生', 'えいせい', 'eisei', 'hygiene, sanitation', '卫生，清洁', '調理前に手を洗って衛生に気をつけます。', 'I wash my hands before cooking for hygiene.', '做菜前洗手注意卫生。'),
  ('ja-food-intermediate-123', 'ja', 'intermediate', 'food', '食器', 'しょっき', 'shokki', 'tableware, dishes', '餐具，碗碟', '食器を洗ってから片付けます。', 'I wash the dishes and put them away.', '洗完餐具后收好。'),
  ('ja-food-intermediate-124', 'ja', 'intermediate', 'food', '箸', 'はし', 'hashi', 'chopsticks', '筷子', '箸の使い方にはマナーがあります。', 'There are manners for using chopsticks.', '使用筷子有讲究。'),
  ('ja-food-intermediate-125', 'ja', 'intermediate', 'food', 'お茶碗', 'おちゃわん', 'ochawan', 'rice bowl, tea cup', '饭碗，茶碗', 'お茶碗にご飯をよそいます。', 'I serve rice into the bowl.', '把饭盛到碗里。'),
  ('ja-food-intermediate-126', 'ja', 'intermediate', 'food', '湯呑み', 'ゆのみ', 'yunomi', 'teacup, tea mug', '茶杯，茶碗', '湯呑みでお茶を飲みます。', 'I drink tea from a teacup.', '用茶杯喝茶。'),
  ('ja-food-intermediate-127', 'ja', 'intermediate', 'food', '取り皿', 'とりざら', 'torizara', 'serving plate, individual plate', '取盘，小碟', '取り皿を使って取り分けます。', 'Use a serving plate to divide the food.', '用小碟分餐。'),
  ('ja-food-intermediate-128', 'ja', 'intermediate', 'food', '食品表示', 'しょくひんひょうじ', 'shokuhin hyouji', 'food label, nutrition label', '食品标签，营养标示', '食品表示をよく読みます。', 'I read food labels carefully.', '仔细阅读食品标签。'),
  ('ja-food-intermediate-129', 'ja', 'intermediate', 'food', 'グルテンフリー', 'ぐるてんふりー', 'guruten furii', 'gluten-free', '无麸质', 'グルテンフリーの食品を探しています。', 'I am looking for gluten-free foods.', '我在找无麸质食品。'),
  ('ja-food-intermediate-130', 'ja', 'intermediate', 'food', 'ビーガン', 'びーがん', 'biigan', 'vegan', '纯素食，维根', 'ビーガンのレストランが増えています。', 'Vegan restaurants are increasing.', '纯素食餐厅越来越多。'),
  ('ja-food-intermediate-131', 'ja', 'intermediate', 'food', '食事制限', 'しょくじせいげん', 'shokuji seigen', 'dietary restriction, diet limitation', '饮食限制，忌口', '食事制限がある方はお知らせください。', 'Please let us know if you have dietary restrictions.', '如有饮食限制请告知。'),
  ('ja-food-intermediate-132', 'ja', 'intermediate', 'food', '減塩', 'げんえん', 'gen''en', 'low salt, reduced salt', '减盐，低盐', '健康のために減塩を心がけています。', 'I try to reduce salt for my health.', '为了健康注意减盐。'),
  ('ja-food-intermediate-133', 'ja', 'intermediate', 'food', '食物連鎖', 'しょくもつれんさ', 'shokumotsurensa', 'food chain', '食物链', '食物連鎖は生態系の基本です。', 'The food chain is fundamental to ecosystems.', '食物链是生态系统的基础。'),
  ('ja-food-intermediate-134', 'ja', 'intermediate', 'food', '朝食', 'ちょうしょく', 'choushoku', 'breakfast, morning meal', '早餐，早饭', '朝食を毎日食べるようにしています。', 'I try to eat breakfast every day.', '我尽量每天吃早餐。'),
  ('ja-food-intermediate-135', 'ja', 'intermediate', 'food', '昼食', 'ちゅうしょく', 'chuushoku', 'lunch, midday meal', '午餐，午饭', '昼食は社員食堂で食べます。', 'I eat lunch at the company cafeteria.', '在员工食堂吃午饭。'),
  ('ja-food-intermediate-136', 'ja', 'intermediate', 'food', '夕食', 'ゆうしょく', 'yuushoku', 'dinner, evening meal', '晚餐，晚饭', '夕食は家族と一緒に食べます。', 'I eat dinner together with my family.', '和家人一起吃晚饭。'),
  ('ja-food-intermediate-137', 'ja', 'intermediate', 'food', '間食', 'かんしょく', 'kanshoku', 'snack, between-meal food', '零食，加餐', '間食を控えるようにしています。', 'I try to limit snacking.', '我尽量控制吃零食。'),
  ('ja-food-intermediate-138', 'ja', 'intermediate', 'food', '夜食', 'やしょく', 'yashoku', 'late-night snack, midnight snack', '夜宵，宵夜', '夜食は太る原因になります。', 'Late-night snacks are a cause of weight gain.', '夜宵会导致发胖。'),
  ('ja-food-intermediate-139', 'ja', 'intermediate', 'food', '飲み物', 'のみもの', 'nomimono', 'beverage, drink', '饮料，饮品', '飲み物は何にしますか。', 'What would you like to drink?', '请问您要什么饮料？'),
  ('ja-food-intermediate-140', 'ja', 'intermediate', 'food', '水分補給', 'すいぶんほきゅう', 'suibun hokyuu', 'hydration, fluid intake', '补水，水分补充', '運動後は水分補給が大切です。', 'Hydration is important after exercise.', '运动后补水很重要。'),
  ('ja-food-intermediate-141', 'ja', 'intermediate', 'food', '市場', 'いちば', 'ichiba', 'market, marketplace', '市场，集市', '市場で新鮮な魚を買います。', 'I buy fresh fish at the market.', '在市场买新鲜的鱼。'),
  ('ja-food-intermediate-142', 'ja', 'intermediate', 'food', '試食', 'ししょく', 'shishoku', 'food sample, tasting', '试吃，品尝', 'スーパーで試食をもらいました。', 'I got a food sample at the supermarket.', '在超市试吃了。'),
  ('ja-food-intermediate-143', 'ja', 'intermediate', 'food', '特売', 'とくばい', 'tokubai', 'special sale, bargain', '特卖，特价', '特売の食品をまとめ買いしました。', 'I bulk-bought food on sale.', '大量购买了特价食品。'),
  ('ja-food-intermediate-144', 'ja', 'intermediate', 'food', '食料品', 'しょくりょうひん', 'shokuryouhin', 'groceries, food items', '食品，杂货', '食料品の買い出しに行きます。', 'I''m going grocery shopping.', '去买食品杂货。'),
  ('ja-food-intermediate-145', 'ja', 'intermediate', 'food', '地元産', 'じもとさん', 'jimotosan', 'locally produced, local product', '本地产，当地产', '地元産の野菜を使います。', 'I use locally produced vegetables.', '使用本地产的蔬菜。'),
  ('ja-food-intermediate-146', 'ja', 'intermediate', 'food', '名物', 'めいぶつ', 'meibutsu', 'local specialty, famous product', '名产，特产', 'この地域の名物は蕎麦です。', 'The local specialty of this area is soba.', '这个地区的特产是荞麦面。'),
  ('ja-food-intermediate-147', 'ja', 'intermediate', 'food', 'お取り寄せ', 'おとりよせ', 'otoriyose', 'mail order food, online food delivery', '邮购美食，网上订购', 'お取り寄せグルメが人気です。', 'Mail-order gourmet food is popular.', '邮购美食很受欢迎。'),
  ('ja-food-intermediate-148', 'ja', 'intermediate', 'food', '手作り', 'てづくり', 'tedukuri', 'handmade, homemade', '手工制作，自制', '手作りのジャムをもらいました。', 'I received homemade jam.', '收到了手工果酱。'),
  ('ja-food-intermediate-149', 'ja', 'intermediate', 'food', '盛り合わせ', 'もりあわせ', 'moriawase', 'assorted plate, platter', '拼盘，什锦', '刺身の盛り合わせを注文しました。', 'I ordered an assorted sashimi platter.', '点了刺身拼盘。'),
  ('ja-food-intermediate-150', 'ja', 'intermediate', 'food', 'おかわり', 'おかわり', 'okawari', 'second helping, refill', '续碗，再来一份', 'ご飯のおかわりをお願いします。', 'I''d like a second helping of rice please.', '请再给我添一碗饭。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
