-- Expand ko-travel-intermediate to 150 curated entries (8-150)
-- Topic: travel/transportation vocabulary for intermediate Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-travel-intermediate-8', 'ko', 'intermediate', 'travel', 'KTX', 'KTX', 'KTX', 'KTX, Korean high-speed train', '韩国高铁，KTX', 'KTX로 부산까지 2시간 반이면 가요.', 'It takes 2.5 hours to Busan by KTX.', '坐KTX到釜山两个半小时。'),
  ('ko-travel-intermediate-9', 'ko', 'intermediate', 'travel', '무궁화호', '무궁화호', 'mugunghwaho', 'Mugunghwa train, regular express', '无穷花号，普通快车', '무궁화호는 KTX보다 느리지만 싸요.', 'Mugunghwa is slower than KTX but cheaper.', '无穷花号比KTX慢但便宜。'),
  ('ko-travel-intermediate-10', 'ko', 'intermediate', 'travel', '지하철', '지하철', 'jihacheol', 'subway, metro', '地铁', '서울 지하철은 편리해요.', 'Seoul''s subway is convenient.', '首尔地铁很方便。'),
  ('ko-travel-intermediate-11', 'ko', 'intermediate', 'travel', '버스 정류장', '버스 정류장', 'beoseu jeongnyujang', 'bus stop, bus station', '公交站，巴士站', '다음 버스 정류장에서 내려요.', 'I get off at the next bus stop.', '在下一站下车。'),
  ('ko-travel-intermediate-12', 'ko', 'intermediate', 'travel', '택시', '택시', 'taeksi', 'taxi, cab', '出租车，的士', '택시를 잡기 어려워요.', 'It''s hard to catch a taxi.', '很难打到出租车。'),
  ('ko-travel-intermediate-13', 'ko', 'intermediate', 'travel', '렌터카', '렌터카', 'renteoka', 'rental car, car rental', '租车，租赁汽车', '제주도에서 렌터카를 빌렸어요.', 'I rented a car in Jeju.', '在济州岛租了车。'),
  ('ko-travel-intermediate-14', 'ko', 'intermediate', 'travel', '페리', '페리', 'peri', 'ferry, boat', '渡轮，客船', '페리로 섬에 갔어요.', 'I went to the island by ferry.', '坐渡轮去了岛上。'),
  ('ko-travel-intermediate-15', 'ko', 'intermediate', 'travel', '탑승구', '탑승구', 'tapseunggu', 'boarding gate, gate', '登机口，乘机口', '탑승구가 변경되었어요.', 'The boarding gate has changed.', '登机口变更了。'),
  ('ko-travel-intermediate-16', 'ko', 'intermediate', 'travel', '입국심사', '입국심사', 'ipguksimsa', 'immigration, passport control', '入境审查，入境检查', '입국심사가 오래 걸렸어요.', 'Immigration took a long time.', '入境审查花了很久。'),
  ('ko-travel-intermediate-17', 'ko', 'intermediate', 'travel', '출국심사', '출국심사', 'chulguksimsa', 'departure inspection, exit control', '出境审查，出境检查', '출국심사를 받았어요.', 'I went through departure inspection.', '办了出境检查。'),
  ('ko-travel-intermediate-18', 'ko', 'intermediate', 'travel', '면세점', '면세점', 'myeonsejeom', 'duty-free shop', '免税店', '면세점에서 화장품을 샀어요.', 'I bought cosmetics at the duty-free shop.', '在免税店买了化妆品。'),
  ('ko-travel-intermediate-19', 'ko', 'intermediate', 'travel', '수하물', '수하물', 'suhamul', 'luggage, baggage', '行李，托运物', '수하물을 찾으러 갔어요.', 'I went to pick up my luggage.', '去取行李了。'),
  ('ko-travel-intermediate-20', 'ko', 'intermediate', 'travel', '위탁 수하물', '위탁 수하물', 'witak suhamul', 'checked baggage, checked luggage', '托运行李', '위탁 수하물은 23kg까지 가능해요.', 'Checked baggage can be up to 23kg.', '托运行李限重23公斤。'),
  ('ko-travel-intermediate-21', 'ko', 'intermediate', 'travel', '기내 반입', '기내 반입', 'ginae banip', 'carry-on, cabin luggage', '随身携带，机内带入', '기내 반입 가능한 크기를 확인해요.', 'I check the carry-on size limit.', '确认可以带上飞机的尺寸。'),
  ('ko-travel-intermediate-22', 'ko', 'intermediate', 'travel', '세관', '세관', 'segwan', 'customs, customs office', '海关', '세관에서 검사를 받았어요.', 'I was inspected at customs.', '在海关接受了检查。'),
  ('ko-travel-intermediate-23', 'ko', 'intermediate', 'travel', '탑승권', '탑승권', 'tapseunggwon', 'boarding pass', '登机牌', '탑승권을 보여 주세요.', 'Please show your boarding pass.', '请出示登机牌。'),
  ('ko-travel-intermediate-24', 'ko', 'intermediate', 'travel', '체크인', '체크인', 'chekein', 'check-in', '办理入住，值机', '호텔에 체크인했어요.', 'I checked into the hotel.', '办理了酒店入住。'),
  ('ko-travel-intermediate-25', 'ko', 'intermediate', 'travel', '체크아웃', '체크아웃', 'chekeaut', 'check-out', '退房', '체크아웃은 11시까지예요.', 'Check-out is by 11 o''clock.', '退房时间截止到11点。'),
  ('ko-travel-intermediate-26', 'ko', 'intermediate', 'travel', '프런트', '프런트', 'pereonteu', 'front desk, reception', '前台，接待处', '프런트에서 열쇠를 받았어요.', 'I received the key at the front desk.', '在前台拿了钥匙。'),
  ('ko-travel-intermediate-27', 'ko', 'intermediate', 'travel', '객실', '객실', 'gaeksil', 'guest room, hotel room', '客房，房间', '객실이 깨끗해요.', 'The room is clean.', '客房很干净。'),
  ('ko-travel-intermediate-28', 'ko', 'intermediate', 'travel', '빈방', '빈방', 'binbang', 'vacant room, available room', '空房', '빈방이 있나요?', 'Do you have a vacant room?', '有空房吗？'),
  ('ko-travel-intermediate-29', 'ko', 'intermediate', 'travel', '만실', '만실', 'mansil', 'no vacancy, fully booked', '满房，客满', '호텔이 만실이에요.', 'The hotel is fully booked.', '酒店满房了。'),
  ('ko-travel-intermediate-30', 'ko', 'intermediate', 'travel', '민박', '민박', 'minbak', 'homestay, guesthouse', '民宿，民居住宿', '시골에서 민박을 했어요.', 'I stayed at a homestay in the countryside.', '在乡下住了民宿。'),
  ('ko-travel-intermediate-31', 'ko', 'intermediate', 'travel', '게스트하우스', '게스트하우스', 'geseuteuhauseu', 'guesthouse, hostel', '青旅，客栈', '게스트하우스에서 여행자를 만났어요.', 'I met travelers at the guesthouse.', '在青旅遇到了旅行者。'),
  ('ko-travel-intermediate-32', 'ko', 'intermediate', 'travel', '교차로', '교차로', 'gyocharo', 'intersection, crossroads', '十字路口，交叉路口', '교차로에서 좌회전하세요.', 'Turn left at the intersection.', '在十字路口左转。'),
  ('ko-travel-intermediate-33', 'ko', 'intermediate', 'travel', '신호등', '신호등', 'sinhodeung', 'traffic light, signal', '红绿灯，信号灯', '신호등이 바뀔 때까지 기다려요.', 'Wait until the traffic light changes.', '等红绿灯变了再走。'),
  ('ko-travel-intermediate-34', 'ko', 'intermediate', 'travel', '안내소', '안내소', 'annaeso', 'information center, help desk', '问讯处，咨询台', '관광 안내소에서 지도를 받았어요.', 'I got a map at the tourist information center.', '在旅游咨询处拿了地图。'),
  ('ko-travel-intermediate-35', 'ko', 'intermediate', 'travel', '횡단보도', '횡단보도', 'hoengdanbodo', 'crosswalk, pedestrian crossing', '人行横道，斑马线', '횡단보도에서 건너세요.', 'Cross at the crosswalk.', '在人行横道过马路。'),
  ('ko-travel-intermediate-36', 'ko', 'intermediate', 'travel', '일방통행', '일방통행', 'ilbangtonghaeng', 'one-way street', '单行道', '이 길은 일방통행이에요.', 'This street is one-way.', '这条路是单行道。'),
  ('ko-travel-intermediate-37', 'ko', 'intermediate', 'travel', '막다른 길', '막다른 길', 'makdareun gil', 'dead end, cul-de-sac', '死胡同，尽头路', '이 길은 막다른 길이에요.', 'This is a dead end.', '这是条死胡同。'),
  ('ko-travel-intermediate-38', 'ko', 'intermediate', 'travel', '편도', '편도', 'pyeondo', 'one-way ticket', '单程', '편도 표를 샀어요.', 'I bought a one-way ticket.', '买了单程票。'),
  ('ko-travel-intermediate-39', 'ko', 'intermediate', 'travel', '왕복', '왕복', 'wangbok', 'round trip, return ticket', '往返，来回', '왕복 표가 더 싸요.', 'A round-trip ticket is cheaper.', '往返票更便宜。'),
  ('ko-travel-intermediate-40', 'ko', 'intermediate', 'travel', '정기권', '정기권', 'jeonggigwon', 'commuter pass, season ticket', '月票，定期票', '정기권을 사면 할인돼요.', 'If you buy a commuter pass, you get a discount.', '买月票有折扣。'),
  ('ko-travel-intermediate-41', 'ko', 'intermediate', 'travel', '교통카드', '교통카드', 'gyotongkadeu', 'transit card, transportation card', '交通卡，公交卡', '교통카드를 충전해요.', 'I recharge my transit card.', '给交通卡充值。'),
  ('ko-travel-intermediate-42', 'ko', 'intermediate', 'travel', '지정석', '지정석', 'jijeongseok', 'reserved seat, assigned seat', '对号座，指定席', '지정석을 예약했어요.', 'I reserved a seat.', '预订了对号座。'),
  ('ko-travel-intermediate-43', 'ko', 'intermediate', 'travel', '자유석', '자유석', 'jayuseok', 'unreserved seat, free seating', '自由席，非对号', '자유석은 먼저 오는 사람 순이에요.', 'Unreserved seats are first come, first served.', '自由席先到先得。'),
  ('ko-travel-intermediate-44', 'ko', 'intermediate', 'travel', '관광지', '관광지', 'gwangwangji', 'tourist spot, sightseeing place', '旅游景点，观光地', '유명한 관광지에 갔어요.', 'I went to a famous tourist spot.', '去了著名的旅游景点。'),
  ('ko-travel-intermediate-45', 'ko', 'intermediate', 'travel', '명소', '명소', 'myeongso', 'famous place, attraction', '名胜，名所', '서울의 명소를 둘러봤어요.', 'I visited Seoul''s famous places.', '游览了首尔的名胜。'),
  ('ko-travel-intermediate-46', 'ko', 'intermediate', 'travel', '유적지', '유적지', 'yujeokji', 'historic site, ruins', '遗迹，古迹', '유적지를 방문했어요.', 'I visited the historic site.', '参观了遗迹。'),
  ('ko-travel-intermediate-47', 'ko', 'intermediate', 'travel', '세계유산', '세계유산', 'segyeyusan', 'World Heritage, UNESCO site', '世界遗产', '한국에도 세계유산이 많아요.', 'Korea also has many World Heritage sites.', '韩国也有很多世界遗产。'),
  ('ko-travel-intermediate-48', 'ko', 'intermediate', 'travel', '온천', '온천', 'oncheon', 'hot spring, spa', '温泉', '온천에서 피로를 풀었어요.', 'I relieved fatigue at the hot spring.', '在温泉消除了疲劳。'),
  ('ko-travel-intermediate-49', 'ko', 'intermediate', 'travel', '전망대', '전망대', 'jeonmangdae', 'observation deck, lookout point', '观景台，展望台', '전망대에서 경치를 봤어요.', 'I saw the view from the observation deck.', '在观景台看了风景。'),
  ('ko-travel-intermediate-50', 'ko', 'intermediate', 'travel', '유람선', '유람선', 'yuramseon', 'cruise ship, excursion boat', '游览船，观光船', '한강 유람선을 탔어요.', 'I rode a Han River cruise.', '坐了汉江游览船。'),
  ('ko-travel-intermediate-51', 'ko', 'intermediate', 'travel', '일정', '일정', 'iljeong', 'itinerary, schedule', '日程，行程', '여행 일정을 짰어요.', 'I planned the travel itinerary.', '制定了旅行日程。'),
  ('ko-travel-intermediate-52', 'ko', 'intermediate', 'travel', '여권', '여권', 'yeogwon', 'passport', '护照', '여권 유효기간을 확인해요.', 'I check the passport validity.', '确认护照有效期。'),
  ('ko-travel-intermediate-53', 'ko', 'intermediate', 'travel', '비자', '비자', 'bija', 'visa', '签证', '비자 신청을 했어요.', 'I applied for a visa.', '申请了签证。'),
  ('ko-travel-intermediate-54', 'ko', 'intermediate', 'travel', '해외여행', '해외여행', 'haeoe yeohaeng', 'overseas travel, international trip', '出国旅行，海外旅游', '해외여행을 계획하고 있어요.', 'I''m planning an overseas trip.', '正在计划出国旅行。'),
  ('ko-travel-intermediate-55', 'ko', 'intermediate', 'travel', '국내여행', '국내여행', 'gungnae yeohaeng', 'domestic travel, local trip', '国内旅行', '주말에 국내여행을 가요.', 'I go on a domestic trip on weekends.', '周末去国内旅行。'),
  ('ko-travel-intermediate-56', 'ko', 'intermediate', 'travel', '배낭여행', '배낭여행', 'baenang yeohaeng', 'backpacking, backpack trip', '背包旅行', '대학생 때 유럽 배낭여행을 했어요.', 'I went backpacking in Europe as a college student.', '大学时去欧洲背包旅行了。'),
  ('ko-travel-intermediate-57', 'ko', 'intermediate', 'travel', '패키지여행', '패키지여행', 'paekiji yeohaeng', 'package tour, group tour', '跟团旅行，旅行团', '패키지여행이 편해요.', 'Package tours are convenient.', '跟团旅行很方便。'),
  ('ko-travel-intermediate-58', 'ko', 'intermediate', 'travel', '자유여행', '자유여행', 'jayu yeohaeng', 'independent travel, free trip', '自由行', '자유여행으로 일본에 갔어요.', 'I went to Japan as an independent traveler.', '自由行去了日本。'),
  ('ko-travel-intermediate-59', 'ko', 'intermediate', 'travel', '대사관', '대사관', 'daesagwan', 'embassy', '大使馆', '대사관에 연락했어요.', 'I contacted the embassy.', '联系了大使馆。'),
  ('ko-travel-intermediate-60', 'ko', 'intermediate', 'travel', '영사관', '영사관', 'yeongsagwan', 'consulate', '领事馆', '가까운 영사관을 찾았어요.', 'I found the nearest consulate.', '找到了最近的领事馆。'),
  ('ko-travel-intermediate-61', 'ko', 'intermediate', 'travel', '여행자 보험', '여행자 보험', 'yeohaengja boheom', 'travel insurance', '旅行保险', '여행자 보험에 가입했어요.', 'I signed up for travel insurance.', '买了旅行保险。'),
  ('ko-travel-intermediate-62', 'ko', 'intermediate', 'travel', '분실', '분실', 'bunsil', 'loss, lost item', '丢失，遗失', '여권을 분실했어요.', 'I lost my passport.', '护照丢了。'),
  ('ko-travel-intermediate-63', 'ko', 'intermediate', 'travel', '도난', '도난', 'donan', 'theft, stolen', '被盗，盗窃', '가방을 도난당했어요.', 'My bag was stolen.', '包被偷了。'),
  ('ko-travel-intermediate-64', 'ko', 'intermediate', 'travel', '신고', '신고', 'singo', 'report, filing a report', '报案，申报', '경찰에 도난 신고를 했어요.', 'I filed a theft report with the police.', '向警察报了案。'),
  ('ko-travel-intermediate-65', 'ko', 'intermediate', 'travel', '환전', '환전', 'hwanjeon', 'currency exchange', '换汇，兑换', '공항에서 환전했어요.', 'I exchanged currency at the airport.', '在机场换了钱。'),
  ('ko-travel-intermediate-66', 'ko', 'intermediate', 'travel', '환율', '환율', 'hwanyul', 'exchange rate', '汇率', '오늘 환율이 어떻게 되나요?', 'What is today''s exchange rate?', '今天汇率是多少？'),
  ('ko-travel-intermediate-67', 'ko', 'intermediate', 'travel', '짐', '짐', 'jim', 'luggage, baggage, load', '行李，包裹', '짐을 호텔에 맡겼어요.', 'I left my luggage at the hotel.', '把行李寄存在酒店了。'),
  ('ko-travel-intermediate-68', 'ko', 'intermediate', 'travel', '캐리어', '캐리어', 'kaerieo', 'suitcase, carry-on bag', '行李箱，拉杆箱', '캐리어가 무거워요.', 'The suitcase is heavy.', '行李箱很重。'),
  ('ko-travel-intermediate-69', 'ko', 'intermediate', 'travel', '배편', '배편', 'baepyeon', 'boat service, ship route', '船班，航班', '배편으로 제주도에 가요.', 'I go to Jeju by boat.', '坐船去济州岛。'),
  ('ko-travel-intermediate-70', 'ko', 'intermediate', 'travel', '항공편', '항공편', 'hanggongpyeon', 'flight, air service', '航班，飞机', '항공편을 예약했어요.', 'I booked a flight.', '预订了航班。'),
  ('ko-travel-intermediate-71', 'ko', 'intermediate', 'travel', '직항', '직항', 'jikhang', 'direct flight, nonstop', '直航，直飞', '직항이 없어서 경유해야 해요.', 'There is no direct flight, so I need to transfer.', '没有直航，需要转机。'),
  ('ko-travel-intermediate-72', 'ko', 'intermediate', 'travel', '경유', '경유', 'gyeongyu', 'layover, transit, stopover', '经停，转机', '도쿄를 경유해서 가요.', 'I go via Tokyo.', '经东京转机。'),
  ('ko-travel-intermediate-73', 'ko', 'intermediate', 'travel', '지연', '지연', 'jiyeon', 'delay, postponement', '延误，延迟', '비행기가 2시간 지연됐어요.', 'The flight was delayed 2 hours.', '飞机延误了2小时。'),
  ('ko-travel-intermediate-74', 'ko', 'intermediate', 'travel', '결항', '결항', 'gyeolhang', 'flight cancellation', '航班取消', '태풍으로 결항됐어요.', 'The flight was cancelled due to a typhoon.', '因台风航班取消了。'),
  ('ko-travel-intermediate-75', 'ko', 'intermediate', 'travel', '좌석', '좌석', 'jwaseok', 'seat, seating', '座位', '창가 좌석을 원해요.', 'I want a window seat.', '我想要靠窗的座位。'),
  ('ko-travel-intermediate-76', 'ko', 'intermediate', 'travel', '통로석', '통로석', 'tongnoseok', 'aisle seat', '过道座位', '통로석으로 바꿔 주세요.', 'Please change me to an aisle seat.', '请帮我换成过道座位。'),
  ('ko-travel-intermediate-77', 'ko', 'intermediate', 'travel', '내비게이션', '내비게이션', 'naebige-isyeon', 'GPS navigation, car nav', '导航，GPS', '내비게이션을 켜고 운전해요.', 'I drive with navigation on.', '开着导航开车。'),
  ('ko-travel-intermediate-78', 'ko', 'intermediate', 'travel', '고속도로', '고속도로', 'gosokdoro', 'expressway, highway', '高速公路', '고속도로가 막혀요.', 'The highway is jammed.', '高速公路堵车了。'),
  ('ko-travel-intermediate-79', 'ko', 'intermediate', 'travel', '휴게소', '휴게소', 'hyugeso', 'rest area, service area', '服务区，休息站', '휴게소에서 쉬어 갔어요.', 'I rested at the service area.', '在服务区休息了一下。'),
  ('ko-travel-intermediate-80', 'ko', 'intermediate', 'travel', '톨게이트', '톨게이트', 'tolgeiteu', 'toll gate, toll booth', '收费站', '톨게이트에서 통행료를 냈어요.', 'I paid the toll at the toll gate.', '在收费站交了通行费。'),
  ('ko-travel-intermediate-81', 'ko', 'intermediate', 'travel', '주차장', '주차장', 'juchajang', 'parking lot, car park', '停车场', '주차장이 만차예요.', 'The parking lot is full.', '停车场满了。'),
  ('ko-travel-intermediate-82', 'ko', 'intermediate', 'travel', '짐칸', '짐칸', 'jimkan', 'luggage compartment, trunk', '行李舱，后备箱', '짐칸에 캐리어를 넣었어요.', 'I put the suitcase in the luggage compartment.', '把行李箱放进了后备箱。'),
  ('ko-travel-intermediate-83', 'ko', 'intermediate', 'travel', '노선도', '노선도', 'noseondo', 'route map, transit map', '路线图，线路图', '지하철 노선도를 확인해요.', 'I check the subway route map.', '查看地铁路线图。'),
  ('ko-travel-intermediate-84', 'ko', 'intermediate', 'travel', '막차', '막차', 'makcha', 'last train/bus, final service', '末班车', '막차를 놓쳤어요.', 'I missed the last train.', '错过了末班车。'),
  ('ko-travel-intermediate-85', 'ko', 'intermediate', 'travel', '첫차', '첫차', 'cheotcha', 'first train/bus, first service', '首班车', '첫차는 몇 시예요?', 'What time is the first train?', '首班车几点？'),
  ('ko-travel-intermediate-86', 'ko', 'intermediate', 'travel', '배차 간격', '배차 간격', 'baecha gangyeok', 'service interval, frequency', '发车间隔', '배차 간격이 10분이에요.', 'The service interval is 10 minutes.', '发车间隔是10分钟。'),
  ('ko-travel-intermediate-87', 'ko', 'intermediate', 'travel', '출구', '출구', 'chulgu', 'exit, way out', '出口', '3번 출구로 나오세요.', 'Come out through exit 3.', '从3号出口出来。'),
  ('ko-travel-intermediate-88', 'ko', 'intermediate', 'travel', '입구', '입구', 'ipgu', 'entrance, entry', '入口', '입구가 어디예요?', 'Where is the entrance?', '入口在哪里？'),
  ('ko-travel-intermediate-89', 'ko', 'intermediate', 'travel', '개찰구', '개찰구', 'gaechalgu', 'ticket gate, turnstile', '检票口，闸机', '개찰구에 카드를 대요.', 'I tap my card at the ticket gate.', '在检票口刷卡。'),
  ('ko-travel-intermediate-90', 'ko', 'intermediate', 'travel', '플랫폼', '플랫폼', 'peullaetpom', 'platform, station platform', '站台，月台', '2번 플랫폼에서 타세요.', 'Board at platform 2.', '在2号站台乘车。'),
  ('ko-travel-intermediate-91', 'ko', 'intermediate', 'travel', '여행사', '여행사', 'yeohaengsa', 'travel agency', '旅行社', '여행사에서 상담 받았어요.', 'I got consulted at the travel agency.', '在旅行社咨询了。'),
  ('ko-travel-intermediate-92', 'ko', 'intermediate', 'travel', '관광 안내', '관광 안내', 'gwangwang annae', 'tourist information, sightseeing guide', '旅游指南，观光介绍', '관광 안내 책자를 받았어요.', 'I got a tourist information brochure.', '拿了旅游指南小册子。'),
  ('ko-travel-intermediate-93', 'ko', 'intermediate', 'travel', '숙박', '숙박', 'sukbak', 'accommodation, lodging', '住宿，留宿', '숙박 예약을 했어요.', 'I made a lodging reservation.', '预订了住宿。'),
  ('ko-travel-intermediate-94', 'ko', 'intermediate', 'travel', '조식', '조식', 'josik', 'breakfast (hotel), morning meal', '早餐（酒店）', '조식이 포함된 객실이에요.', 'It''s a room with breakfast included.', '是含早餐的客房。'),
  ('ko-travel-intermediate-95', 'ko', 'intermediate', 'travel', '룸서비스', '룸서비스', 'rumseobisheu', 'room service', '客房服务', '룸서비스를 주문했어요.', 'I ordered room service.', '叫了客房服务。'),
  ('ko-travel-intermediate-96', 'ko', 'intermediate', 'travel', '짐 보관', '짐 보관', 'jim bogwan', 'luggage storage, baggage hold', '行李寄存', '역에서 짐 보관을 했어요.', 'I stored my luggage at the station.', '在车站寄存了行李。'),
  ('ko-travel-intermediate-97', 'ko', 'intermediate', 'travel', '투어', '투어', 'tueo', 'tour, guided tour', '旅游团，观光', '시티 투어 버스를 탔어요.', 'I rode the city tour bus.', '坐了城市观光巴士。'),
  ('ko-travel-intermediate-98', 'ko', 'intermediate', 'travel', '가이드', '가이드', 'gaideu', 'guide, tour guide', '导游，向导', '현지 가이드가 설명해 줬어요.', 'The local guide explained for us.', '当地导游给我们讲解了。'),
  ('ko-travel-intermediate-99', 'ko', 'intermediate', 'travel', '기념품', '기념품', 'ginyeompum', 'souvenir, memento', '纪念品，伴手礼', '기념품을 샀어요.', 'I bought souvenirs.', '买了纪念品。'),
  ('ko-travel-intermediate-100', 'ko', 'intermediate', 'travel', '면세', '면세', 'myeonse', 'duty-free, tax-free', '免税', '면세 한도를 확인해요.', 'I check the duty-free limit.', '确认免税额度。'),
  ('ko-travel-intermediate-101', 'ko', 'intermediate', 'travel', '출발 시간', '출발 시간', 'chulbal sigan', 'departure time', '出发时间', '출발 시간을 확인했어요.', 'I confirmed the departure time.', '确认了出发时间。'),
  ('ko-travel-intermediate-102', 'ko', 'intermediate', 'travel', '도착 시간', '도착 시간', 'dochak sigan', 'arrival time', '到达时间', '도착 시간이 늦어졌어요.', 'The arrival time was delayed.', '到达时间推迟了。'),
  ('ko-travel-intermediate-103', 'ko', 'intermediate', 'travel', '시차', '시차', 'sicha', 'time difference, jet lag', '时差', '시차 적응이 힘들어요.', 'It''s hard to adjust to the time difference.', '倒时差很辛苦。'),
  ('ko-travel-intermediate-104', 'ko', 'intermediate', 'travel', '로밍', '로밍', 'roming', 'roaming, international roaming', '漫游，国际漫游', '로밍 서비스를 신청했어요.', 'I applied for roaming service.', '申请了漫游服务。'),
  ('ko-travel-intermediate-105', 'ko', 'intermediate', 'travel', '유심', '유심', 'yusim', 'SIM card, USIM', 'SIM卡', '현지 유심을 샀어요.', 'I bought a local SIM card.', '买了当地SIM卡。'),
  ('ko-travel-intermediate-106', 'ko', 'intermediate', 'travel', '와이파이', '와이파이', 'waipai', 'Wi-Fi, wireless internet', 'WiFi，无线网', '호텔 와이파이가 느려요.', 'The hotel Wi-Fi is slow.', '酒店WiFi很慢。'),
  ('ko-travel-intermediate-107', 'ko', 'intermediate', 'travel', '예방접종', '예방접종', 'yebangjeoljong', 'vaccination, immunization', '预防接种，打疫苗', '여행 전에 예방접종을 받았어요.', 'I got vaccinated before the trip.', '旅行前接种了疫苗。'),
  ('ko-travel-intermediate-108', 'ko', 'intermediate', 'travel', '약국', '약국', 'yakguk', 'pharmacy, drugstore', '药店，药房', '근처 약국을 찾고 있어요.', 'I''m looking for a nearby pharmacy.', '在找附近的药店。'),
  ('ko-travel-intermediate-109', 'ko', 'intermediate', 'travel', '길을 잃다', '길을 잃다', 'gireul ilta', 'to get lost, to lose one''s way', '迷路，走丢', '길을 잃어서 지도를 봤어요.', 'I got lost and looked at the map.', '迷路了看了地图。'),
  ('ko-travel-intermediate-110', 'ko', 'intermediate', 'travel', '길을 묻다', '길을 묻다', 'gireul mutda', 'to ask for directions', '问路', '현지인에게 길을 물었어요.', 'I asked a local for directions.', '向当地人问了路。'),
  ('ko-travel-intermediate-111', 'ko', 'intermediate', 'travel', '표지판', '표지판', 'pyojipan', 'sign, signboard', '标志牌，路牌', '표지판을 보고 방향을 확인해요.', 'I check directions by looking at signs.', '看标志牌确认方向。'),
  ('ko-travel-intermediate-112', 'ko', 'intermediate', 'travel', '지도 앱', '지도 앱', 'jido aep', 'map app, navigation app', '地图APP', '지도 앱으로 찾아갔어요.', 'I found it using a map app.', '用地图APP找到的。'),
  ('ko-travel-intermediate-113', 'ko', 'intermediate', 'travel', '야경', '야경', 'yagyeong', 'night view, nightscape', '夜景', '서울 야경이 아름다워요.', 'Seoul''s night view is beautiful.', '首尔夜景很漂亮。'),
  ('ko-travel-intermediate-114', 'ko', 'intermediate', 'travel', '사진 찍다', '사진 찍다', 'sajin jjikda', 'to take a photo', '拍照', '사진 찍어 주실 수 있어요?', 'Could you take a photo for me?', '能帮我拍张照吗？'),
  ('ko-travel-intermediate-115', 'ko', 'intermediate', 'travel', '포토존', '포토존', 'potojon', 'photo spot, photo zone', '拍照点，打卡点', '포토존에서 사진을 찍었어요.', 'I took photos at the photo spot.', '在拍照点拍了照。'),
  ('ko-travel-intermediate-116', 'ko', 'intermediate', 'travel', '산책로', '산책로', 'sanchaengno', 'walking trail, promenade', '散步道，步行道', '해변 산책로를 걸었어요.', 'I walked the beachside promenade.', '走了海边散步道。'),
  ('ko-travel-intermediate-117', 'ko', 'intermediate', 'travel', '등산로', '등산로', 'deungsanno', 'hiking trail, mountain path', '登山道，山路', '등산로가 잘 정비되어 있어요.', 'The hiking trail is well-maintained.', '登山道维护得很好。'),
  ('ko-travel-intermediate-118', 'ko', 'intermediate', 'travel', '해수욕장', '해수욕장', 'haesuyokjang', 'beach, swimming beach', '海水浴场，海滨浴场', '해수욕장에서 수영했어요.', 'I swam at the beach.', '在海水浴场游了泳。'),
  ('ko-travel-intermediate-119', 'ko', 'intermediate', 'travel', '펜션', '펜션', 'pensyeon', 'pension, vacation rental', '度假别墅，民宿', '바닷가 근처 펜션을 잡았어요.', 'I booked a pension near the beach.', '订了海边的度假别墅。'),
  ('ko-travel-intermediate-120', 'ko', 'intermediate', 'travel', '리조트', '리조트', 'rijoteu', 'resort', '度假村，度假酒店', '가족과 리조트에 갔어요.', 'I went to a resort with my family.', '和家人去了度假村。'),
  ('ko-travel-intermediate-121', 'ko', 'intermediate', 'travel', '할인 항공권', '할인 항공권', 'harin hanggonggwon', 'discount airfare, cheap flight', '打折机票，廉价航班', '할인 항공권을 찾고 있어요.', 'I''m looking for a cheap flight.', '在找打折机票。'),
  ('ko-travel-intermediate-122', 'ko', 'intermediate', 'travel', '저가 항공', '저가 항공', 'jeoga hanggong', 'low-cost airline, budget carrier', '廉价航空，低成本航空', '저가 항공으로 예약했어요.', 'I booked with a low-cost airline.', '用廉价航空预订了。'),
  ('ko-travel-intermediate-123', 'ko', 'intermediate', 'travel', '좌석 업그레이드', '좌석 업그레이드', 'jwaseok eopgeureideu', 'seat upgrade', '座位升舱', '좌석 업그레이드가 가능한가요?', 'Is a seat upgrade possible?', '可以升舱吗？'),
  ('ko-travel-intermediate-124', 'ko', 'intermediate', 'travel', '기내식', '기내식', 'ginaesik', 'in-flight meal, airplane food', '飞机餐，机内餐', '기내식으로 한식을 선택했어요.', 'I chose Korean food for the in-flight meal.', '飞机餐选了韩餐。'),
  ('ko-travel-intermediate-125', 'ko', 'intermediate', 'travel', '안전벨트', '안전벨트', 'anjeonbelteu', 'seatbelt, safety belt', '安全带', '안전벨트를 매 주세요.', 'Please fasten your seatbelt.', '请系好安全带。'),
  ('ko-travel-intermediate-126', 'ko', 'intermediate', 'travel', '이륙', '이륙', 'iryuk', 'takeoff, departure', '起飞', '비행기가 이륙해요.', 'The airplane is taking off.', '飞机起飞了。'),
  ('ko-travel-intermediate-127', 'ko', 'intermediate', 'travel', '착륙', '착륙', 'changnyuk', 'landing, touchdown', '着陆，降落', '곧 착륙합니다.', 'We will be landing shortly.', '即将着陆。'),
  ('ko-travel-intermediate-128', 'ko', 'intermediate', 'travel', '난기류', '난기류', 'nangiryu', 'turbulence, air turbulence', '颠簸，气流', '난기류가 심했어요.', 'The turbulence was severe.', '颠簸很严重。'),
  ('ko-travel-intermediate-129', 'ko', 'intermediate', 'travel', '입국 신고서', '입국 신고서', 'ipguk singoseo', 'arrival card, entry form', '入境申报卡', '입국 신고서를 작성해요.', 'I fill out the arrival card.', '填写入境申报卡。'),
  ('ko-travel-intermediate-130', 'ko', 'intermediate', 'travel', '세관 신고', '세관 신고', 'segwan singo', 'customs declaration', '海关申报', '세관 신고할 물건이 없어요.', 'I have nothing to declare at customs.', '没有需要海关申报的物品。'),
  ('ko-travel-intermediate-131', 'ko', 'intermediate', 'travel', '현지 음식', '현지 음식', 'hyeonji eumsik', 'local food, local cuisine', '当地美食', '현지 음식을 꼭 먹어 봐요.', 'Be sure to try the local food.', '一定要尝尝当地美食。'),
  ('ko-travel-intermediate-132', 'ko', 'intermediate', 'travel', '현지인', '현지인', 'hyeondiin', 'local person, local resident', '当地人', '현지인이 추천한 식당에 갔어요.', 'I went to a restaurant recommended by a local.', '去了当地人推荐的餐厅。'),
  ('ko-travel-intermediate-133', 'ko', 'intermediate', 'travel', '여행 경비', '여행 경비', 'yeohaeng gyeongbi', 'travel expenses, trip budget', '旅费，旅行经费', '여행 경비를 계산해 봤어요.', 'I calculated the travel expenses.', '算了一下旅费。'),
  ('ko-travel-intermediate-134', 'ko', 'intermediate', 'travel', '카드 결제', '카드 결제', 'kadeu gyeolje', 'card payment, paying by card', '刷卡，卡支付', '카드 결제 되나요?', 'Can I pay by card?', '可以刷卡吗？'),
  ('ko-travel-intermediate-135', 'ko', 'intermediate', 'travel', '현금', '현금', 'hyeongeum', 'cash', '现金', '현금만 받는 가게예요.', 'It''s a cash-only shop.', '这家店只收现金。'),
  ('ko-travel-intermediate-136', 'ko', 'intermediate', 'travel', '영수증', '영수증', 'yeongsujeung', 'receipt', '收据，发票', '영수증 주세요.', 'Please give me a receipt.', '请给我收据。'),
  ('ko-travel-intermediate-137', 'ko', 'intermediate', 'travel', '만원', '만원', 'manwon', 'full capacity, crowded', '满员，爆满', '버스가 만원이에요.', 'The bus is packed.', '公交车满员了。'),
  ('ko-travel-intermediate-138', 'ko', 'intermediate', 'travel', '정체', '정체', 'jeongche', 'traffic jam, congestion', '堵车，交通拥堵', '도로가 정체되고 있어요.', 'The road is congested.', '道路正在堵车。'),
  ('ko-travel-intermediate-139', 'ko', 'intermediate', 'travel', '우회', '우회', 'uhoe', 'detour, roundabout', '绕路，迂回', '공사 중이라 우회해야 해요.', 'There''s construction so we need to detour.', '正在施工，需要绕路。'),
  ('ko-travel-intermediate-140', 'ko', 'intermediate', 'travel', '도보', '도보', 'dobo', 'on foot, walking', '步行，徒步', '역에서 도보 5분 거리예요.', 'It''s a 5-minute walk from the station.', '离车站步行5分钟。'),
  ('ko-travel-intermediate-141', 'ko', 'intermediate', 'travel', '자전거', '자전거', 'jajeongeo', 'bicycle, bike', '自行车', '자전거를 빌려서 타요.', 'I rent and ride a bicycle.', '租自行车骑。'),
  ('ko-travel-intermediate-142', 'ko', 'intermediate', 'travel', '전동 킥보드', '전동 킥보드', 'jeondong kikbodeu', 'electric scooter, e-kickboard', '电动滑板车', '전동 킥보드로 이동해요.', 'I get around by electric scooter.', '骑电动滑板车出行。'),
  ('ko-travel-intermediate-143', 'ko', 'intermediate', 'travel', '출입국', '출입국', 'churipguk', 'immigration, entry and exit', '出入境', '출입국 관리소에 갔어요.', 'I went to the immigration office.', '去了出入境管理处。'),
  ('ko-travel-intermediate-144', 'ko', 'intermediate', 'travel', '세금 환급', '세금 환급', 'segeum hwangeup', 'tax refund', '退税', '세금 환급을 받았어요.', 'I got a tax refund.', '拿到了退税。'),
  ('ko-travel-intermediate-145', 'ko', 'intermediate', 'travel', '면세 한도', '면세 한도', 'myeonse hando', 'duty-free allowance, exemption limit', '免税额度', '면세 한도를 초과했어요.', 'I exceeded the duty-free allowance.', '超过了免税额度。'),
  ('ko-travel-intermediate-146', 'ko', 'intermediate', 'travel', '여행 후기', '여행 후기', 'yeohaeng hugi', 'travel review, trip report', '游记，旅行评价', '여행 후기를 블로그에 올렸어요.', 'I posted a travel review on my blog.', '在博客上发了游记。'),
  ('ko-travel-intermediate-147', 'ko', 'intermediate', 'travel', '출발 게이트', '출발 게이트', 'chulbal geiteu', 'departure gate', '出发登机口', '출발 게이트가 바뀌었어요.', 'The departure gate has changed.', '出发登机口变了。'),
  ('ko-travel-intermediate-148', 'ko', 'intermediate', 'travel', '수화물 벨트', '수화물 벨트', 'suhwamul belteu', 'baggage carousel, luggage belt', '行李传送带', '수화물 벨트에서 짐을 찾아요.', 'I pick up luggage at the baggage carousel.', '在行李传送带取行李。'),
  ('ko-travel-intermediate-149', 'ko', 'intermediate', 'travel', '환승역', '환승역', 'hwanseungyeok', 'transfer station, connecting station', '换乘站', '다음 역이 환승역이에요.', 'The next station is a transfer station.', '下一站是换乘站。'),
  ('ko-travel-intermediate-150', 'ko', 'intermediate', 'travel', '귀국', '귀국', 'gwiguk', 'return to home country, going back', '回国，归国', '다음 주에 귀국해요.', 'I return home next week.', '下周回国。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
