-- Expand ko-food-intermediate to 150 curated entries (10-150)
-- Topic: food/cooking/cuisine vocabulary for intermediate Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-food-intermediate-10', 'ko', 'intermediate', 'food', '볶다', '볶다', 'bokda', 'to stir-fry, to roast', '炒，翻炒', '야채를 센 불에서 볶아요.', 'I stir-fry vegetables on high heat.', '用大火炒蔬菜。'),
  ('ko-food-intermediate-11', 'ko', 'intermediate', 'food', '찌다', '찌다', 'jjida', 'to steam, to steam-cook', '蒸，蒸煮', '생선을 찜기에 쪄요.', 'I steam fish in a steamer.', '用蒸锅蒸鱼。'),
  ('ko-food-intermediate-12', 'ko', 'intermediate', 'food', '튀기다', '튀기다', 'twigida', 'to deep-fry, to fry', '炸，油炸', '새우를 바삭하게 튀겨요.', 'I deep-fry shrimp until crispy.', '把虾炸得酥脆。'),
  ('ko-food-intermediate-13', 'ko', 'intermediate', 'food', '끓이다', '끓이다', 'kkeurita', 'to boil, to simmer', '煮，炖', '찌개를 오래 끓여요.', 'I simmer the stew for a long time.', '把汤炖很久。'),
  ('ko-food-intermediate-14', 'ko', 'intermediate', 'food', '데치다', '데치다', 'dechida', 'to blanch, to parboil', '焯，过水', '시금치를 데쳐서 나물을 만들어요.', 'I blanch spinach to make namul.', '焯菠菜做凉拌菜。'),
  ('ko-food-intermediate-15', 'ko', 'intermediate', 'food', '무치다', '무치다', 'muchida', 'to dress, to season (vegetables)', '拌，调拌', '콩나물을 참기름으로 무쳐요.', 'I dress bean sprouts with sesame oil.', '用香油拌豆芽。'),
  ('ko-food-intermediate-16', 'ko', 'intermediate', 'food', '담그다', '담그다', 'damgeuda', 'to pickle, to soak', '腌，浸泡', '김치를 직접 담가요.', 'I make kimchi myself.', '自己腌泡菜。'),
  ('ko-food-intermediate-17', 'ko', 'intermediate', 'food', '다지다', '다지다', 'dajida', 'to chop finely, to mince', '切碎，剁碎', '마늘을 곱게 다져요.', 'I mince garlic finely.', '把蒜切碎。'),
  ('ko-food-intermediate-18', 'ko', 'intermediate', 'food', '밑간', '밑간', 'mitgan', 'pre-seasoning, base seasoning', '底味，腌味', '고기에 밑간을 해 둬요.', 'I pre-season the meat.', '给肉提前腌入底味。'),
  ('ko-food-intermediate-19', 'ko', 'intermediate', 'food', '양념', '양념', 'yangnyeom', 'seasoning, sauce, marinade', '调料，酱料', '양념을 만들어서 재워요.', 'I make the sauce and marinate.', '做好调料腌制。'),
  ('ko-food-intermediate-20', 'ko', 'intermediate', 'food', '담음새', '담음새', 'dameumsae', 'plating, food presentation', '摆盘，装盘', '담음새가 예쁘면 식욕이 생겨요.', 'Beautiful plating stimulates appetite.', '摆盘漂亮会增加食欲。'),
  ('ko-food-intermediate-21', 'ko', 'intermediate', 'food', '밀가루', '밀가루', 'milgaru', 'wheat flour, flour', '面粉，小麦粉', '밀가루로 수제비를 만들어요.', 'I make sujebi with flour.', '用面粉做水煎饼。'),
  ('ko-food-intermediate-22', 'ko', 'intermediate', 'food', '전분', '전분', 'jeonbun', 'starch, cornstarch', '淀粉，生粉', '전분으로 소스에 농도를 내요.', 'I thicken the sauce with starch.', '用淀粉给酱汁勾芡。'),
  ('ko-food-intermediate-23', 'ko', 'intermediate', 'food', '식초', '식초', 'sikcho', 'vinegar', '醋，食醋', '식초를 넣으면 상큼해져요.', 'Adding vinegar makes it tangy.', '加醋会变得清爽。'),
  ('ko-food-intermediate-24', 'ko', 'intermediate', 'food', '된장', '된장', 'doenjang', 'soybean paste, doenjang', '大酱，豆酱', '된장찌개는 한국의 대표 음식이에요.', 'Doenjang jjigae is a representative Korean dish.', '大酱汤是韩国代表性食物。'),
  ('ko-food-intermediate-25', 'ko', 'intermediate', 'food', '간장', '간장', 'ganjang', 'soy sauce', '酱油', '간장으로 간을 맞춰요.', 'I adjust the seasoning with soy sauce.', '用酱油调味。'),
  ('ko-food-intermediate-26', 'ko', 'intermediate', 'food', '고추장', '고추장', 'gochujang', 'red pepper paste, gochujang', '辣椒酱，辣酱', '비빔밥에 고추장을 넣어요.', 'I add gochujang to bibimbap.', '在拌饭里加辣椒酱。'),
  ('ko-food-intermediate-27', 'ko', 'intermediate', 'food', '참기름', '참기름', 'chamgireum', 'sesame oil', '香油，芝麻油', '참기름을 마지막에 뿌려요.', 'I drizzle sesame oil at the end.', '最后淋上香油。'),
  ('ko-food-intermediate-28', 'ko', 'intermediate', 'food', '육수', '육수', 'yuksu', 'broth, stock', '高汤，汤底', '멸치로 육수를 내요.', 'I make broth from anchovies.', '用小银鱼熬高汤。'),
  ('ko-food-intermediate-29', 'ko', 'intermediate', 'food', '한식', '한식', 'hansik', 'Korean cuisine, Korean food', '韩餐，韩国料理', '한식은 건강에 좋아요.', 'Korean food is good for health.', '韩餐对健康好。'),
  ('ko-food-intermediate-30', 'ko', 'intermediate', 'food', '양식', '양식', 'yangsik', 'Western food, Western cuisine', '西餐，洋食', '오늘은 양식이 먹고 싶어요.', 'I want to eat Western food today.', '今天想吃西餐。'),
  ('ko-food-intermediate-31', 'ko', 'intermediate', 'food', '분식', '분식', 'bunsik', 'flour-based snacks, Korean street food', '粉食，面食小吃', '분식집에서 떡볶이를 먹었어요.', 'I ate tteokbokki at a snack shop.', '在小吃店吃了炒年糕。'),
  ('ko-food-intermediate-32', 'ko', 'intermediate', 'food', '정식', '정식', 'jeongsik', 'set meal, full course', '套餐，定食', '오늘의 정식은 불고기예요.', 'Today''s set meal is bulgogi.', '今天的套餐是烤肉。'),
  ('ko-food-intermediate-33', 'ko', 'intermediate', 'food', '주문', '주문', 'jumun', 'order, ordering', '点餐，订单', '주문하시겠어요?', 'Would you like to order?', '您要点餐吗？'),
  ('ko-food-intermediate-34', 'ko', 'intermediate', 'food', '계산', '계산', 'gyesan', 'bill, payment', '结账，买单', '계산은 카드로 할게요.', 'I''ll pay by card.', '用卡结账。'),
  ('ko-food-intermediate-35', 'ko', 'intermediate', 'food', '칼', '칼', 'kal', 'knife, kitchen knife', '刀，菜刀', '칼을 갈아서 사용해요.', 'I sharpen the knife before using.', '磨好刀再用。'),
  ('ko-food-intermediate-36', 'ko', 'intermediate', 'food', '도마', '도마', 'doma', 'cutting board, chopping board', '砧板，切菜板', '도마를 소독해요.', 'I disinfect the cutting board.', '给砧板消毒。'),
  ('ko-food-intermediate-37', 'ko', 'intermediate', 'food', '프라이팬', '프라이팬', 'peuraipan', 'frying pan, skillet', '平底锅，煎锅', '프라이팬을 달궈요.', 'I heat up the frying pan.', '加热平底锅。'),
  ('ko-food-intermediate-38', 'ko', 'intermediate', 'food', '냄비', '냄비', 'naembi', 'pot, saucepan', '锅，汤锅', '냄비에 물을 끓여요.', 'I boil water in the pot.', '在锅里烧开水。'),
  ('ko-food-intermediate-39', 'ko', 'intermediate', 'food', '국자', '국자', 'gukja', 'ladle, soup scoop', '汤勺，勺子', '국자로 국을 떠요.', 'I scoop soup with a ladle.', '用汤勺舀汤。'),
  ('ko-food-intermediate-40', 'ko', 'intermediate', 'food', '담백하다', '담백하다', 'dambaekada', 'light, plain, mild taste', '清淡，淡雅', '이 요리는 담백해서 좋아요.', 'I like this dish because it''s light.', '这道菜清淡，我喜欢。'),
  ('ko-food-intermediate-41', 'ko', 'intermediate', 'food', '느끼하다', '느끼하다', 'neukkihada', 'greasy, oily, heavy', '油腻，腻', '치즈가 너무 많아서 느끼해요.', 'There''s too much cheese, it''s greasy.', '奶酪太多，太油腻了。'),
  ('ko-food-intermediate-42', 'ko', 'intermediate', 'food', '쫄깃하다', '쫄깃하다', 'jjolgitada', 'chewy, springy', '有嚼劲，筋道', '면이 쫄깃해서 맛있어요.', 'The noodles are chewy and delicious.', '面条筋道好吃。'),
  ('ko-food-intermediate-43', 'ko', 'intermediate', 'food', '바삭하다', '바삭하다', 'basakada', 'crispy, crunchy', '酥脆，脆', '치킨이 바삭해요.', 'The chicken is crispy.', '炸鸡很酥脆。'),
  ('ko-food-intermediate-44', 'ko', 'intermediate', 'food', '부드럽다', '부드럽다', 'budeureopda', 'soft, tender, smooth', '柔软，嫩', '스테이크가 부드러워요.', 'The steak is tender.', '牛排很嫩。'),
  ('ko-food-intermediate-45', 'ko', 'intermediate', 'food', '영양', '영양', 'yeongyang', 'nutrition, nourishment', '营养，营养素', '영양 균형을 생각해서 먹어요.', 'I eat thinking about nutritional balance.', '考虑营养均衡来吃饭。'),
  ('ko-food-intermediate-46', 'ko', 'intermediate', 'food', '칼로리', '칼로리', 'kallori', 'calorie, energy content', '卡路里，热量', '칼로리를 신경 쓰고 있어요.', 'I''m watching my calories.', '我在注意卡路里。'),
  ('ko-food-intermediate-47', 'ko', 'intermediate', 'food', '알레르기', '알레르기', 'allereugi', 'allergy, food allergy', '过敏，食物过敏', '땅콩 알레르기가 있어요.', 'I have a peanut allergy.', '我对花生过敏。'),
  ('ko-food-intermediate-48', 'ko', 'intermediate', 'food', '식이섬유', '식이섬유', 'sigiseomnyu', 'dietary fiber', '膳食纤维，食物纤维', '식이섬유가 풍부한 음식을 먹어요.', 'I eat food rich in dietary fiber.', '我吃富含膳食纤维的食物。'),
  ('ko-food-intermediate-49', 'ko', 'intermediate', 'food', '탄수화물', '탄수화물', 'tansuhwamul', 'carbohydrate, carbs', '碳水化合物，糖类', '탄수화물 섭취를 줄이고 있어요.', 'I''m reducing my carb intake.', '我在减少碳水摄入。'),
  ('ko-food-intermediate-50', 'ko', 'intermediate', 'food', '포장마차', '포장마차', 'pojangmacha', 'food stall, street food cart', '路边摊，大排档', '포장마차에서 떡볶이를 먹었어요.', 'I ate tteokbokki at a street food stall.', '在路边摊吃了炒年糕。'),
  ('ko-food-intermediate-51', 'ko', 'intermediate', 'food', '뷔페', '뷔페', 'bwipe', 'buffet, all-you-can-eat', '自助餐', '생일에 뷔페에 갔어요.', 'I went to a buffet for my birthday.', '生日去了自助餐。'),
  ('ko-food-intermediate-52', 'ko', 'intermediate', 'food', '더치페이', '더치페이', 'deochipei', 'going Dutch, splitting the bill', '均摊，AA制', '오늘은 더치페이로 해요.', 'Let''s split the bill today.', '今天我们AA吧。'),
  ('ko-food-intermediate-53', 'ko', 'intermediate', 'food', '예약', '예약', 'yeyak', 'reservation, booking', '预约，预订', '식당을 예약했어요.', 'I made a restaurant reservation.', '预约了餐厅。'),
  ('ko-food-intermediate-54', 'ko', 'intermediate', 'food', '포장', '포장', 'pojang', 'takeout, packaging', '外带，打包', '포장해 주세요.', 'For takeout please.', '请打包。'),
  ('ko-food-intermediate-55', 'ko', 'intermediate', 'food', '도시락', '도시락', 'dosirak', 'lunch box, packed meal', '便当，盒饭', '매일 도시락을 싸요.', 'I pack a lunch every day.', '每天带便当。'),
  ('ko-food-intermediate-56', 'ko', 'intermediate', 'food', '반찬', '반찬', 'banchan', 'side dish, Korean side dishes', '小菜，配菜', '반찬을 여러 가지 만들었어요.', 'I made various side dishes.', '做了各种小菜。'),
  ('ko-food-intermediate-57', 'ko', 'intermediate', 'food', '밑반찬', '밑반찬', 'mitbanchan', 'basic side dishes, everyday sides', '常备小菜，下饭菜', '주말에 밑반찬을 만들어 둬요.', 'I prepare basic side dishes on weekends.', '周末提前做好常备小菜。'),
  ('ko-food-intermediate-58', 'ko', 'intermediate', 'food', '유통기한', '유통기한', 'yutonggihan', 'expiration date, best-before date', '保质期，有效期', '유통기한을 확인해 주세요.', 'Please check the expiration date.', '请确认保质期。'),
  ('ko-food-intermediate-59', 'ko', 'intermediate', 'food', '첨가물', '첨가물', 'cheomgamul', 'additive, food additive', '添加剂，添加物', '첨가물이 적은 음식을 선택해요.', 'I choose food with fewer additives.', '我选择添加剂少的食物。'),
  ('ko-food-intermediate-60', 'ko', 'intermediate', 'food', '유기농', '유기농', 'yuginong', 'organic, organic farming', '有机，有机农业', '유기농 채소를 사요.', 'I buy organic vegetables.', '我买有机蔬菜。'),
  ('ko-food-intermediate-61', 'ko', 'intermediate', 'food', '산지', '산지', 'sanji', 'place of origin, production area', '产地，产区', '식재료의 산지를 확인해요.', 'I check the origin of ingredients.', '我确认食材的产地。'),
  ('ko-food-intermediate-62', 'ko', 'intermediate', 'food', '제철', '제철', 'jecheol', 'in season, seasonal', '时令，当季', '제철 과일이 제일 맛있어요.', 'Seasonal fruit is the most delicious.', '时令水果最好吃。'),
  ('ko-food-intermediate-63', 'ko', 'intermediate', 'food', '큰술', '큰술', 'keunsul', 'tablespoon', '大勺，汤匙', '설탕 큰술 두 개를 넣어요.', 'Add two tablespoons of sugar.', '加入两大勺糖。'),
  ('ko-food-intermediate-64', 'ko', 'intermediate', 'food', '작은술', '작은술', 'jageunsul', 'teaspoon', '小勺，茶匙', '소금 작은술 하나를 넣어요.', 'Add one teaspoon of salt.', '加入一小勺盐。'),
  ('ko-food-intermediate-65', 'ko', 'intermediate', 'food', '적당량', '적당량', 'jeokdangnyang', 'appropriate amount, to taste', '适量，适当的量', '후추를 적당량 뿌려요.', 'Sprinkle pepper to taste.', '撒适量胡椒。'),
  ('ko-food-intermediate-66', 'ko', 'intermediate', 'food', '센 불', '센 불', 'sen bul', 'high heat, strong fire', '大火，强火', '센 불에서 빨리 볶아요.', 'Stir-fry quickly on high heat.', '用大火快速翻炒。'),
  ('ko-food-intermediate-67', 'ko', 'intermediate', 'food', '약한 불', '약한 불', 'yakhan bul', 'low heat, gentle fire', '小火，弱火', '약한 불에서 천천히 끓여요.', 'Simmer slowly on low heat.', '用小火慢慢炖。'),
  ('ko-food-intermediate-68', 'ko', 'intermediate', 'food', '중간 불', '중간 불', 'junggan bul', 'medium heat', '中火', '중간 불에서 5분 볶아요.', 'Stir-fry on medium heat for 5 minutes.', '用中火炒5分钟。'),
  ('ko-food-intermediate-69', 'ko', 'intermediate', 'food', '끓다', '끓다', 'kkeulta', 'to boil, to bubble', '沸腾，烧开', '물이 끓으면 면을 넣어요.', 'When the water boils, add noodles.', '水开了就下面条。'),
  ('ko-food-intermediate-70', 'ko', 'intermediate', 'food', '거품', '거품', 'geopum', 'foam, scum, bubbles', '泡沫，浮沫', '거품을 걷어내요.', 'I skim off the foam.', '撇去浮沫。'),
  ('ko-food-intermediate-71', 'ko', 'intermediate', 'food', '감칠맛', '감칠맛', 'gamchilmat', 'umami, savory taste', '鲜味，旨味', '된장에는 감칠맛이 있어요.', 'Doenjang has umami flavor.', '大酱有鲜味。'),
  ('ko-food-intermediate-72', 'ko', 'intermediate', 'food', '식감', '식감', 'sikgam', 'texture, mouthfeel', '口感，食感', '이 떡은 식감이 좋아요.', 'This rice cake has good texture.', '这个年糕口感好。'),
  ('ko-food-intermediate-73', 'ko', 'intermediate', 'food', '싱겁다', '싱겁다', 'singeopda', 'bland, not salty enough', '淡，味道不够', '국이 좀 싱거워요.', 'The soup is a bit bland.', '汤有点淡。'),
  ('ko-food-intermediate-74', 'ko', 'intermediate', 'food', '짜다', '짜다', 'jjada', 'salty, too salty', '咸，太咸', '이 음식은 좀 짜요.', 'This food is a bit salty.', '这个菜有点咸。'),
  ('ko-food-intermediate-75', 'ko', 'intermediate', 'food', '순한 맛', '순한 맛', 'sunhan mat', 'mild flavor, not spicy', '不辣，温和的味道', '아이에게는 순한 맛으로 만들어요.', 'I make it mild for the child.', '给孩子做不辣的。'),
  ('ko-food-intermediate-76', 'ko', 'intermediate', 'food', '매운 맛', '매운 맛', 'maeun mat', 'spicy flavor, hot taste', '辣味，辛辣', '매운 맛을 좋아해요.', 'I like spicy food.', '我喜欢辣味。'),
  ('ko-food-intermediate-77', 'ko', 'intermediate', 'food', '신맛', '신맛', 'sinmat', 'sourness, sour taste', '酸味，酸', '신맛이 나는 드레싱이에요.', 'It''s a sour dressing.', '这是有酸味的调味汁。'),
  ('ko-food-intermediate-78', 'ko', 'intermediate', 'food', '쓴맛', '쓴맛', 'sseunmat', 'bitterness, bitter taste', '苦味，涩味', '이 차는 쓴맛이 나요.', 'This tea has a bitter taste.', '这茶有苦味。'),
  ('ko-food-intermediate-79', 'ko', 'intermediate', 'food', '단맛', '단맛', 'danmat', 'sweetness, sweet taste', '甜味，甜', '과일에서 단맛이 나요.', 'The fruit has sweetness.', '水果有甜味。'),
  ('ko-food-intermediate-80', 'ko', 'intermediate', 'food', '짠맛', '짠맛', 'jjanmat', 'salty taste, saltiness', '咸味', '짠맛이 강해요.', 'The salty taste is strong.', '咸味很重。'),
  ('ko-food-intermediate-81', 'ko', 'intermediate', 'food', '삼겹살', '삼겹살', 'samgyeopsal', 'pork belly, Korean BBQ pork', '五花肉，三层肉', '삼겹살을 구워 먹어요.', 'I grill and eat pork belly.', '烤五花肉吃。'),
  ('ko-food-intermediate-82', 'ko', 'intermediate', 'food', '찌개', '찌개', 'jjigae', 'stew, thick soup', '汤，炖菜', '김치찌개를 끓여요.', 'I make kimchi stew.', '煮泡菜汤。'),
  ('ko-food-intermediate-83', 'ko', 'intermediate', 'food', '비빔밥', '비빔밥', 'bibimbap', 'bibimbap, mixed rice', '拌饭，石锅拌饭', '비빔밥에 야채를 많이 넣어요.', 'I put lots of vegetables in bibimbap.', '拌饭里加很多蔬菜。'),
  ('ko-food-intermediate-84', 'ko', 'intermediate', 'food', '김밥', '김밥', 'gimbap', 'gimbap, Korean rice roll', '紫菜包饭，海苔卷', '소풍 때 김밥을 싸 갔어요.', 'I packed gimbap for the picnic.', '去郊游带了紫菜包饭。'),
  ('ko-food-intermediate-85', 'ko', 'intermediate', 'food', '간보다', '간보다', 'ganboda', 'to taste, to check seasoning', '试味，品尝', '간을 보고 소금을 더 넣어요.', 'I taste and add more salt.', '试味后再加盐。'),
  ('ko-food-intermediate-86', 'ko', 'intermediate', 'food', '고명', '고명', 'gomyeong', 'garnish, topping', '配料，浇头', '국 위에 고명을 올려요.', 'I put garnish on top of the soup.', '在汤上面放配料。'),
  ('ko-food-intermediate-87', 'ko', 'intermediate', 'food', '곁들이다', '곁들이다', 'gyeotdeurida', 'to serve alongside, to accompany', '搭配，配菜', '스테이크에 샐러드를 곁들여요.', 'I serve salad alongside steak.', '牛排搭配沙拉。'),
  ('ko-food-intermediate-88', 'ko', 'intermediate', 'food', '전채', '전채', 'jeonchae', 'appetizer, starter', '前菜，开胃菜', '전채로 수프를 시켰어요.', 'I ordered soup as an appetizer.', '点了汤作为前菜。'),
  ('ko-food-intermediate-89', 'ko', 'intermediate', 'food', '후식', '후식', 'husik', 'dessert, after-meal treat', '甜点，餐后甜品', '후식으로 커피를 마셨어요.', 'I had coffee for dessert.', '餐后喝了咖啡。'),
  ('ko-food-intermediate-90', 'ko', 'intermediate', 'food', '식욕', '식욕', 'sigyok', 'appetite, desire to eat', '食欲，胃口', '더위에 식욕이 없어요.', 'I have no appetite in the heat.', '天热没有食欲。'),
  ('ko-food-intermediate-91', 'ko', 'intermediate', 'food', '배부르다', '배부르다', 'baebureuda', 'to be full, satiated', '饱，吃饱了', '배불러서 더 못 먹겠어요.', 'I''m full and can''t eat more.', '吃饱了，吃不下了。'),
  ('ko-food-intermediate-92', 'ko', 'intermediate', 'food', '배고프다', '배고프다', 'baegopeda', 'to be hungry', '饿，肚子饿', '배고파서 집중이 안 돼요.', 'I can''t concentrate because I''m hungry.', '饿了无法集中。'),
  ('ko-food-intermediate-93', 'ko', 'intermediate', 'food', '편식', '편식', 'pyeonsik', 'picky eating, unbalanced diet', '偏食，挑食', '편식하면 건강에 안 좋아요.', 'Picky eating is bad for health.', '偏食对健康不好。'),
  ('ko-food-intermediate-94', 'ko', 'intermediate', 'food', '밀프렙', '밀프렙', 'milpeurep', 'meal prep, meal preparation', '预制餐，备餐', '주말에 밀프렙을 해요.', 'I do meal prep on weekends.', '周末做预制餐。'),
  ('ko-food-intermediate-95', 'ko', 'intermediate', 'food', '자취', '자취', 'jachwi', 'living alone, self-catering', '独居，自己生活', '자취하면서 요리를 배웠어요.', 'I learned to cook while living alone.', '独居时学会了做饭。'),
  ('ko-food-intermediate-96', 'ko', 'intermediate', 'food', '외식', '외식', 'oesik', 'eating out, dining out', '外食，在外吃饭', '외식을 줄이려고 해요.', 'I''m trying to eat out less.', '我在努力减少外食。'),
  ('ko-food-intermediate-97', 'ko', 'intermediate', 'food', '음식물 쓰레기', '음식물 쓰레기', 'eumsigmul sseuregi', 'food waste, kitchen waste', '厨余垃圾，食物残渣', '음식물 쓰레기를 줄여요.', 'I reduce food waste.', '减少厨余垃圾。'),
  ('ko-food-intermediate-98', 'ko', 'intermediate', 'food', '발효', '발효', 'balhyo', 'fermentation, fermenting', '发酵，酿造', '김치는 발효 식품이에요.', 'Kimchi is a fermented food.', '泡菜是发酵食品。'),
  ('ko-food-intermediate-99', 'ko', 'intermediate', 'food', '보관', '보관', 'bogwan', 'storage, preservation', '保管，存放', '냉장고에 보관해 주세요.', 'Please store in the refrigerator.', '请放冰箱保管。'),
  ('ko-food-intermediate-100', 'ko', 'intermediate', 'food', '해동', '해동', 'haedong', 'thawing, defrosting', '解冻，化冻', '고기를 전자레인지로 해동해요.', 'I thaw meat in the microwave.', '用微波炉解冻肉。'),
  ('ko-food-intermediate-101', 'ko', 'intermediate', 'food', '실온', '실온', 'siron', 'room temperature', '常温，室温', '실온에서 보관 가능해요.', 'It can be stored at room temperature.', '可以在常温下保管。'),
  ('ko-food-intermediate-102', 'ko', 'intermediate', 'food', '가스레인지', '가스레인지', 'gaseureinji', 'gas stove, gas range', '燃气灶，煤气灶', '가스레인지로 요리해요.', 'I cook on a gas stove.', '用燃气灶做菜。'),
  ('ko-food-intermediate-103', 'ko', 'intermediate', 'food', '전자레인지', '전자레인지', 'jeonjare-inji', 'microwave oven', '微波炉', '전자레인지로 데워요.', 'I heat it in the microwave.', '用微波炉加热。'),
  ('ko-food-intermediate-104', 'ko', 'intermediate', 'food', '오븐', '오븐', 'obeun', 'oven', '烤箱，烤炉', '오븐에서 빵을 구워요.', 'I bake bread in the oven.', '用烤箱烤面包。'),
  ('ko-food-intermediate-105', 'ko', 'intermediate', 'food', '밥솥', '밥솥', 'bapsot', 'rice cooker', '电饭锅', '밥솥으로 밥을 해요.', 'I cook rice in the rice cooker.', '用电饭锅做饭。'),
  ('ko-food-intermediate-106', 'ko', 'intermediate', 'food', '체', '체', 'che', 'sieve, strainer', '筛子，滤网', '체에 밀가루를 쳐요.', 'I sift flour through a sieve.', '用筛子筛面粉。'),
  ('ko-food-intermediate-107', 'ko', 'intermediate', 'food', '거품기', '거품기', 'geopumgi', 'whisk, egg beater', '打蛋器，搅拌器', '거품기로 달걀을 풀어요.', 'I beat eggs with a whisk.', '用打蛋器打鸡蛋。'),
  ('ko-food-intermediate-108', 'ko', 'intermediate', 'food', '계량컵', '계량컵', 'gyeryangkeop', 'measuring cup', '量杯', '계량컵으로 물을 재요.', 'I measure water with a measuring cup.', '用量杯量水。'),
  ('ko-food-intermediate-109', 'ko', 'intermediate', 'food', '유제품', '유제품', 'yujepum', 'dairy products, milk products', '乳制品，奶制品', '유제품으로 칼슘을 섭취해요.', 'I get calcium from dairy products.', '通过乳制品摄取钙。'),
  ('ko-food-intermediate-110', 'ko', 'intermediate', 'food', '곡물', '곡물', 'gokmul', 'grain, cereal', '谷物，粮食', '곡물은 주요 에너지원이에요.', 'Grains are a primary energy source.', '谷物是主要的能量来源。'),
  ('ko-food-intermediate-111', 'ko', 'intermediate', 'food', '두부', '두부', 'dubu', 'tofu, bean curd', '豆腐', '두부는 단백질이 풍부해요.', 'Tofu is rich in protein.', '豆腐富含蛋白质。'),
  ('ko-food-intermediate-112', 'ko', 'intermediate', 'food', '해조류', '해조류', 'haejoryu', 'seaweed, marine algae', '海藻类，海带类', '해조류에는 미네랄이 많아요.', 'Seaweed is rich in minerals.', '海藻类含有丰富的矿物质。'),
  ('ko-food-intermediate-113', 'ko', 'intermediate', 'food', '향신료', '향신료', 'hyangsinnyo', 'spice, seasoning', '香辛料，调味料', '향신료를 넣으면 풍미가 좋아져요.', 'Adding spices improves the flavor.', '加香辛料会让风味更好。'),
  ('ko-food-intermediate-114', 'ko', 'intermediate', 'food', '식중독', '식중독', 'sikjungdok', 'food poisoning', '食物中毒', '여름에는 식중독 조심해야 해요.', 'You need to be careful of food poisoning in summer.', '夏天要小心食物中毒。'),
  ('ko-food-intermediate-115', 'ko', 'intermediate', 'food', '위생', '위생', 'wisaeng', 'hygiene, sanitation', '卫生，清洁', '요리할 때 위생에 신경 써요.', 'I pay attention to hygiene when cooking.', '做菜时注意卫生。'),
  ('ko-food-intermediate-116', 'ko', 'intermediate', 'food', '식기', '식기', 'sikgi', 'tableware, dishes', '餐具，碗碟', '식기를 설거지해요.', 'I wash the dishes.', '洗餐具。'),
  ('ko-food-intermediate-117', 'ko', 'intermediate', 'food', '젓가락', '젓가락', 'jeotgarak', 'chopsticks', '筷子', '한국 젓가락은 금속이에요.', 'Korean chopsticks are metal.', '韩国筷子是金属的。'),
  ('ko-food-intermediate-118', 'ko', 'intermediate', 'food', '숟가락', '숟가락', 'sutgarak', 'spoon', '勺子，汤匙', '숟가락으로 국을 먹어요.', 'I eat soup with a spoon.', '用勺子喝汤。'),
  ('ko-food-intermediate-119', 'ko', 'intermediate', 'food', '그릇', '그릇', 'geureut', 'bowl, dish, vessel', '碗，器皿', '그릇에 밥을 담아요.', 'I serve rice in a bowl.', '把饭盛到碗里。'),
  ('ko-food-intermediate-120', 'ko', 'intermediate', 'food', '식품 표시', '식품 표시', 'sikpum pyosi', 'food label, nutrition label', '食品标签，营养标示', '식품 표시를 잘 읽어요.', 'I read food labels carefully.', '仔细阅读食品标签。'),
  ('ko-food-intermediate-121', 'ko', 'intermediate', 'food', '글루텐 프리', '글루텐 프리', 'geulluten peuri', 'gluten-free', '无麸质', '글루텐 프리 식품을 찾고 있어요.', 'I''m looking for gluten-free foods.', '我在找无麸质食品。'),
  ('ko-food-intermediate-122', 'ko', 'intermediate', 'food', '비건', '비건', 'bigeon', 'vegan', '纯素食，维根', '비건 식당이 많아지고 있어요.', 'Vegan restaurants are increasing.', '纯素食餐厅越来越多。'),
  ('ko-food-intermediate-123', 'ko', 'intermediate', 'food', '식이 제한', '식이 제한', 'sigi jehan', 'dietary restriction', '饮食限制，忌口', '식이 제한이 있으시면 말씀해 주세요.', 'Please let us know if you have dietary restrictions.', '如有饮食限制请告知。'),
  ('ko-food-intermediate-124', 'ko', 'intermediate', 'food', '저염', '저염', 'jeoyeom', 'low salt, reduced salt', '低盐，减盐', '건강을 위해 저염 식단을 해요.', 'I follow a low-salt diet for health.', '为了健康吃低盐饮食。'),
  ('ko-food-intermediate-125', 'ko', 'intermediate', 'food', '아침식사', '아침식사', 'achim siksa', 'breakfast, morning meal', '早餐，早饭', '아침식사를 꼭 먹어요.', 'I always eat breakfast.', '我一定吃早餐。'),
  ('ko-food-intermediate-126', 'ko', 'intermediate', 'food', '점심식사', '점심식사', 'jeomsim siksa', 'lunch, midday meal', '午餐，午饭', '점심식사는 회사 근처에서 해요.', 'I eat lunch near the office.', '午餐在公司附近吃。'),
  ('ko-food-intermediate-127', 'ko', 'intermediate', 'food', '저녁식사', '저녁식사', 'jeonyeok siksa', 'dinner, evening meal', '晚餐，晚饭', '가족과 저녁식사를 해요.', 'I have dinner with my family.', '和家人一起吃晚饭。'),
  ('ko-food-intermediate-128', 'ko', 'intermediate', 'food', '간식', '간식', 'gansik', 'snack, between-meal food', '零食，点心', '간식을 줄이려고 노력해요.', 'I try to reduce snacking.', '我努力减少吃零食。'),
  ('ko-food-intermediate-129', 'ko', 'intermediate', 'food', '야식', '야식', 'yasik', 'late-night snack, midnight snack', '夜宵，宵夜', '야식은 살찌는 원인이에요.', 'Late-night snacks cause weight gain.', '夜宵是发胖的原因。'),
  ('ko-food-intermediate-130', 'ko', 'intermediate', 'food', '음료', '음료', 'eumnyo', 'beverage, drink', '饮料，饮品', '음료는 뭘로 하시겠어요?', 'What would you like to drink?', '请问您要什么饮料？'),
  ('ko-food-intermediate-131', 'ko', 'intermediate', 'food', '수분 섭취', '수분 섭취', 'subun seobchwi', 'hydration, fluid intake', '补水，水分摄取', '운동 후에 수분 섭취가 중요해요.', 'Hydration is important after exercise.', '运动后补水很重要。'),
  ('ko-food-intermediate-132', 'ko', 'intermediate', 'food', '시장', '시장', 'sijang', 'market, marketplace', '市场，集市', '시장에서 신선한 생선을 사요.', 'I buy fresh fish at the market.', '在市场买新鲜的鱼。'),
  ('ko-food-intermediate-133', 'ko', 'intermediate', 'food', '시식', '시식', 'sisik', 'food tasting, sampling', '试吃，品尝', '마트에서 시식을 했어요.', 'I sampled food at the mart.', '在超市试吃了。'),
  ('ko-food-intermediate-134', 'ko', 'intermediate', 'food', '특가', '특가', 'teukga', 'special price, sale', '特价，优惠', '특가 상품을 많이 샀어요.', 'I bought a lot of sale items.', '买了很多特价商品。'),
  ('ko-food-intermediate-135', 'ko', 'intermediate', 'food', '식료품', '식료품', 'singnyopum', 'groceries, food items', '食品，杂货', '식료품을 사러 마트에 가요.', 'I go to the mart to buy groceries.', '去超市买食品杂货。'),
  ('ko-food-intermediate-136', 'ko', 'intermediate', 'food', '지역 특산물', '지역 특산물', 'jiyeok teuksanmul', 'local specialty product', '地方特产', '지역 특산물을 선물로 샀어요.', 'I bought local specialties as gifts.', '买了地方特产当礼物。'),
  ('ko-food-intermediate-137', 'ko', 'intermediate', 'food', '배달', '배달', 'baedal', 'delivery, food delivery', '外卖，配送', '배달 음식을 시켰어요.', 'I ordered delivery food.', '叫了外卖。'),
  ('ko-food-intermediate-138', 'ko', 'intermediate', 'food', '배달 앱', '배달 앱', 'baedal aep', 'delivery app, food ordering app', '外卖软件，配送APP', '배달 앱으로 주문해요.', 'I order through a delivery app.', '通过外卖APP点餐。'),
  ('ko-food-intermediate-139', 'ko', 'intermediate', 'food', '손맛', '손맛', 'sonmat', 'homemade taste, cooking touch', '手艺，家的味道', '엄마의 손맛이 그리워요.', 'I miss my mom''s cooking touch.', '想念妈妈的手艺。'),
  ('ko-food-intermediate-140', 'ko', 'intermediate', 'food', '맛집', '맛집', 'matjip', 'famous restaurant, good eatery', '美食店，好吃的店', '이 근처에 맛집이 있어요.', 'There''s a good restaurant nearby.', '这附近有家好吃的店。'),
  ('ko-food-intermediate-141', 'ko', 'intermediate', 'food', '먹방', '먹방', 'meokbang', 'eating broadcast, mukbang', '吃播，美食直播', '먹방을 보면 배가 고파져요.', 'Watching mukbang makes me hungry.', '看吃播就觉得饿了。'),
  ('ko-food-intermediate-142', 'ko', 'intermediate', 'food', '집밥', '집밥', 'jipbap', 'home-cooked meal, home food', '家常饭，家里的饭', '집밥이 제일 맛있어요.', 'Home-cooked meals are the best.', '家常饭最好吃。'),
  ('ko-food-intermediate-143', 'ko', 'intermediate', 'food', '국물', '국물', 'gungmul', 'broth, soup liquid', '汤汁，汤水', '국물이 시원해요.', 'The broth is refreshing.', '汤汁很爽口。'),
  ('ko-food-intermediate-144', 'ko', 'intermediate', 'food', '건더기', '건더기', 'geondeogi', 'solid ingredients in soup, chunks', '汤里的配料，汤料', '건더기가 많아서 좋아요.', 'I like that there are lots of solid ingredients.', '配料多，很好。'),
  ('ko-food-intermediate-145', 'ko', 'intermediate', 'food', '불맛', '불맛', 'bulmat', 'wok hei, smoky flame flavor', '锅气，火味', '중국집 볶음밥은 불맛이 나요.', 'Chinese restaurant fried rice has wok hei.', '中餐馆炒饭有锅气。'),
  ('ko-food-intermediate-146', 'ko', 'intermediate', 'food', '숙성', '숙성', 'sukseong', 'aging, maturing, ripening', '熟成，陈酿', '고기를 숙성시키면 더 맛있어요.', 'Aging meat makes it more delicious.', '肉熟成后更好吃。'),
  ('ko-food-intermediate-147', 'ko', 'intermediate', 'food', '코스 요리', '코스 요리', 'koseu yori', 'course meal, full course dinner', '套餐，全套料理', '기념일에 코스 요리를 먹었어요.', 'I had a course meal on our anniversary.', '纪念日吃了套餐。'),
  ('ko-food-intermediate-148', 'ko', 'intermediate', 'food', '리필', '리필', 'ripil', 'refill, free refill', '续杯，免费续', '반찬은 리필 가능해요.', 'Side dishes can be refilled.', '小菜可以免费续。'),
  ('ko-food-intermediate-149', 'ko', 'intermediate', 'food', '1인분', '일인분', 'irinbun', 'one serving, single portion', '一人份', '1인분에 얼마예요?', 'How much is one serving?', '一人份多少钱？'),
  ('ko-food-intermediate-150', 'ko', 'intermediate', 'food', '추가 주문', '추가 주문', 'chuga jumun', 'additional order, extra order', '加点，追加点餐', '고기 추가 주문할게요.', 'I''d like to order more meat.', '我要再加点肉。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
