-- Expand ko-work-intermediate to 150 curated entries (17-150)
-- Topic: work/business vocabulary for intermediate Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-work-intermediate-17', 'ko', 'intermediate', 'work', '과장', '과장', 'gwajang', 'section chief, manager', '科长, 课长', '과장님이 회의 시간을 변경하셨습니다.', 'The section chief changed the meeting time.', '科长更改了会议时间。'),
  ('ko-work-intermediate-18', 'ko', 'intermediate', 'work', '부장', '부장', 'bujang', 'department head, general manager', '部长, 部门经理', '부장님께 보고서를 제출해야 합니다.', 'I need to submit the report to the department head.', '我需要向部长提交报告。'),
  ('ko-work-intermediate-19', 'ko', 'intermediate', 'work', '대리', '대리', 'daeri', 'assistant manager, deputy', '代理, 副主任', '김 대리가 이번 프로젝트를 맡았습니다.', 'Assistant Manager Kim took charge of this project.', '金代理负责了这个项目。'),
  ('ko-work-intermediate-20', 'ko', 'intermediate', 'work', '사원', '사원', 'sawon', 'staff member, employee', '职员, 社员', '신입 사원 교육이 다음 주에 있습니다.', 'New employee training is next week.', '新员工培训在下周。'),
  ('ko-work-intermediate-21', 'ko', 'intermediate', 'work', '차장', '차장', 'chajang', 'deputy department head, senior manager', '次长, 副部长', '차장님이 출장 중이라 연락이 안 됩니다.', 'The deputy head is on a business trip and unreachable.', '次长正在出差，联系不上。'),
  ('ko-work-intermediate-22', 'ko', 'intermediate', 'work', '이사', '이사', 'isa', 'director, executive', '理事, 董事', '이사님이 새로운 전략을 발표하셨습니다.', 'The director announced a new strategy.', '董事发布了新的战略。'),
  ('ko-work-intermediate-23', 'ko', 'intermediate', 'work', '상무', '상무', 'sangmu', 'managing director, executive director', '常务, 常务董事', '상무님이 해외 지사를 방문하셨습니다.', 'The managing director visited the overseas branch.', '常务董事访问了海外分公司。'),
  ('ko-work-intermediate-24', 'ko', 'intermediate', 'work', '전무', '전무', 'jeonmu', 'senior managing director, executive VP', '专务, 高级常务', '전무님이 내일 본사에 오십니다.', 'The senior managing director is coming to headquarters tomorrow.', '专务明天来总部。'),
  ('ko-work-intermediate-25', 'ko', 'intermediate', 'work', '인사부', '인사부', 'insabu', 'HR department, personnel department', '人事部, 人力资源部', '인사부에서 채용 공고를 올렸습니다.', 'The HR department posted a job listing.', '人事部发布了招聘公告。'),
  ('ko-work-intermediate-26', 'ko', 'intermediate', 'work', '영업부', '영업부', 'yeongeopbu', 'sales department, business division', '营业部, 销售部', '영업부 실적이 이번 분기에 좋았습니다.', 'The sales department''s performance was good this quarter.', '营业部这个季度的业绩很好。'),
  ('ko-work-intermediate-27', 'ko', 'intermediate', 'work', '기획부', '기획부', 'gihoekbu', 'planning department, strategy division', '企划部, 策划部', '기획부에서 새로운 사업 계획을 세웠습니다.', 'The planning department created a new business plan.', '企划部制定了新的事业计划。'),
  ('ko-work-intermediate-28', 'ko', 'intermediate', 'work', '총무부', '총무부', 'chongmubu', 'general affairs department, admin department', '总务部, 行政部', '총무부에 사무용품을 신청했습니다.', 'I requested office supplies from the general affairs department.', '我向总务部申请了办公用品。'),
  ('ko-work-intermediate-29', 'ko', 'intermediate', 'work', '재무부', '재무부', 'jaemubu', 'finance department, treasury', '财务部, 财政部', '재무부에서 예산을 검토하고 있습니다.', 'The finance department is reviewing the budget.', '财务部正在审核预算。'),
  ('ko-work-intermediate-30', 'ko', 'intermediate', 'work', '개발부', '개발부', 'gaebalbu', 'development department, R&D division', '开发部, 研发部', '개발부에서 신제품을 만들고 있습니다.', 'The development department is creating a new product.', '开发部正在制作新产品。'),
  ('ko-work-intermediate-31', 'ko', 'intermediate', 'work', '마케팅부', '마케팅부', 'maketingbu', 'marketing department, marketing division', '市场部, 营销部', '마케팅부에서 광고 캠페인을 기획했습니다.', 'The marketing department planned an advertising campaign.', '市场部策划了广告活动。'),
  ('ko-work-intermediate-32', 'ko', 'intermediate', 'work', '결재하다', '결재하다', 'gyeoljaehada', 'to approve, to authorize', '批准, 审批', '부장님이 서류를 결재해 주셨습니다.', 'The department head approved the documents.', '部长批准了文件。'),
  ('ko-work-intermediate-33', 'ko', 'intermediate', 'work', '보고하다', '보고하다', 'bogohada', 'to report, to brief', '报告, 汇报', '매주 월요일에 진행 상황을 보고합니다.', 'I report the progress every Monday.', '每周一汇报进展情况。'),
  ('ko-work-intermediate-34', 'ko', 'intermediate', 'work', '제출하다', '제출하다', 'jechulhada', 'to submit, to hand in', '提交, 递交', '보고서를 금요일까지 제출해야 합니다.', 'The report must be submitted by Friday.', '报告必须在周五之前提交。'),
  ('ko-work-intermediate-35', 'ko', 'intermediate', 'work', '회의하다', '회의하다', 'hoeuihada', 'to hold a meeting, to discuss', '开会, 讨论', '오후에 팀원들과 회의합니다.', 'I have a meeting with team members in the afternoon.', '下午和团队成员开会。'),
  ('ko-work-intermediate-36', 'ko', 'intermediate', 'work', '회식', '회식', 'hoesik', 'company dinner, team dinner', '聚餐, 会餐', '이번 주 금요일에 회식이 있습니다.', 'There is a company dinner this Friday.', '这周五有聚餐。'),
  ('ko-work-intermediate-37', 'ko', 'intermediate', 'work', '연차', '연차', 'yeoncha', 'annual leave, paid vacation', '年假, 带薪休假', '다음 주에 연차를 쓰려고 합니다.', 'I plan to use annual leave next week.', '我打算下周请年假。'),
  ('ko-work-intermediate-38', 'ko', 'intermediate', 'work', '복리후생', '복리후생', 'bokrikusaeng', 'employee benefits, welfare', '福利待遇, 员工福利', '이 회사는 복리후생이 좋습니다.', 'This company has good employee benefits.', '这家公司的福利待遇好。'),
  ('ko-work-intermediate-39', 'ko', 'intermediate', 'work', '성과급', '성과급', 'seonggwageup', 'performance bonus, incentive pay', '绩效奖金, 绩效工资', '이번 분기 성과급이 나왔습니다.', 'The performance bonus for this quarter has been issued.', '这个季度的绩效奖金发了。'),
  ('ko-work-intermediate-40', 'ko', 'intermediate', 'work', '상여금', '상여금', 'sangyeogeum', 'bonus, extra pay', '奖金, 额外报酬', '연말에 상여금을 받을 수 있습니다.', 'You can receive a bonus at the end of the year.', '年末可以拿到奖金。'),
  ('ko-work-intermediate-41', 'ko', 'intermediate', 'work', '수당', '수당', 'sudang', 'allowance, extra pay', '津贴, 补贴', '야근 수당이 제대로 지급되고 있습니다.', 'Overtime allowance is being paid properly.', '加班津贴正常发放中。'),
  ('ko-work-intermediate-42', 'ko', 'intermediate', 'work', '연봉', '연봉', 'yeonbong', 'annual salary, yearly pay', '年薪, 年收入', '연봉 협상을 할 시기가 되었습니다.', 'It''s time for salary negotiation.', '到了年薪协商的时候了。'),
  ('ko-work-intermediate-43', 'ko', 'intermediate', 'work', '퇴직금', '퇴직금', 'toejiggeum', 'severance pay, retirement allowance', '退职金, 离职补偿金', '퇴직금은 1년 이상 근무해야 받을 수 있습니다.', 'You must work more than one year to receive severance pay.', '必须工作一年以上才能拿到退职金。'),
  ('ko-work-intermediate-44', 'ko', 'intermediate', 'work', '근무하다', '근무하다', 'geunmuhada', 'to work, to be on duty', '工作, 上班', '저는 이 회사에서 5년째 근무하고 있습니다.', 'I have been working at this company for 5 years.', '我在这家公司已经工作了五年。'),
  ('ko-work-intermediate-45', 'ko', 'intermediate', 'work', '출근하다', '출근하다', 'chulgeunhada', 'to go to work, to commute', '上班, 出勤', '매일 아침 8시에 출근합니다.', 'I go to work at 8 AM every morning.', '每天早上八点上班。'),
  ('ko-work-intermediate-46', 'ko', 'intermediate', 'work', '퇴근하다', '퇴근하다', 'toegeunhada', 'to leave work, to get off work', '下班, 退勤', '오늘은 일찍 퇴근할 수 있을 것 같습니다.', 'I think I can leave work early today.', '今天好像能早点下班。'),
  ('ko-work-intermediate-47', 'ko', 'intermediate', 'work', '야근하다', '야근하다', 'yageunhada', 'to work overtime, to work late', '加班, 加夜班', '이번 주에 세 번이나 야근했습니다.', 'I worked overtime three times this week.', '这周加了三次班。'),
  ('ko-work-intermediate-48', 'ko', 'intermediate', 'work', '재택근무', '재택근무', 'jaetaekgeunmu', 'remote work, work from home', '居家办公, 远程办公', '주 2회 재택근무가 가능합니다.', 'Working from home is possible twice a week.', '每周可以居家办公两次。'),
  ('ko-work-intermediate-49', 'ko', 'intermediate', 'work', '유연근무제', '유연근무제', 'yuyeongeunmuje', 'flexible work system, flextime', '弹性工作制, 灵活工作制', '우리 회사는 유연근무제를 시행하고 있습니다.', 'Our company implements a flexible work system.', '我们公司实行弹性工作制。'),
  ('ko-work-intermediate-50', 'ko', 'intermediate', 'work', '업무', '업무', 'eommu', 'work task, duties', '业务, 工作任务', '오늘 업무가 많아서 바쁩니다.', 'I''m busy because I have a lot of work tasks today.', '今天工作任务多，很忙。'),
  ('ko-work-intermediate-51', 'ko', 'intermediate', 'work', '담당자', '담당자', 'damdangja', 'person in charge, responsible person', '负责人, 经办人', '이 프로젝트의 담당자가 누구입니까?', 'Who is the person in charge of this project?', '这个项目的负责人是谁？'),
  ('ko-work-intermediate-52', 'ko', 'intermediate', 'work', '담당하다', '담당하다', 'damdanghada', 'to be in charge of, to handle', '负责, 担当', '저는 해외 영업을 담당하고 있습니다.', 'I am in charge of overseas sales.', '我负责海外营销。'),
  ('ko-work-intermediate-53', 'ko', 'intermediate', 'work', '프로젝트', '프로젝트', 'peurojekteu', 'project, initiative', '项目, 工程', '새로운 프로젝트가 다음 달에 시작됩니다.', 'A new project starts next month.', '新项目下个月开始。'),
  ('ko-work-intermediate-54', 'ko', 'intermediate', 'work', '기한', '기한', 'gihan', 'deadline, due date', '期限, 截止日期', '제출 기한을 꼭 지켜 주세요.', 'Please make sure to meet the submission deadline.', '请务必遵守提交期限。'),
  ('ko-work-intermediate-55', 'ko', 'intermediate', 'work', '마감일', '마감일', 'magamil', 'deadline, closing date', '截止日, 截稿日', '마감일이 이틀 앞으로 다가왔습니다.', 'The deadline is approaching in two days.', '截止日还有两天。'),
  ('ko-work-intermediate-56', 'ko', 'intermediate', 'work', '일정', '일정', 'iljeong', 'schedule, timetable', '日程, 安排', '이번 주 일정을 확인해 주세요.', 'Please check this week''s schedule.', '请确认一下这周的日程。'),
  ('ko-work-intermediate-57', 'ko', 'intermediate', 'work', '회의록', '회의록', 'hoeuirok', 'meeting minutes, meeting record', '会议纪要, 会议记录', '회의록을 정리해서 공유해 주세요.', 'Please organize the meeting minutes and share them.', '请整理会议纪要并分享。'),
  ('ko-work-intermediate-58', 'ko', 'intermediate', 'work', '안건', '안건', 'angeon', 'agenda item, matter for discussion', '议题, 案件', '오늘 회의 안건은 세 가지입니다.', 'There are three agenda items for today''s meeting.', '今天会议的议题有三个。'),
  ('ko-work-intermediate-59', 'ko', 'intermediate', 'work', '발표하다', '발표하다', 'balpyohada', 'to present, to announce', '发表, 宣布', '내일 회의에서 결과를 발표합니다.', 'I will present the results at tomorrow''s meeting.', '明天会议上发表结果。'),
  ('ko-work-intermediate-60', 'ko', 'intermediate', 'work', '협의하다', '협의하다', 'hyeopuihada', 'to discuss, to consult', '协商, 商议', '관련 부서와 협의가 필요합니다.', 'Consultation with the related department is needed.', '需要和相关部门协商。'),
  ('ko-work-intermediate-61', 'ko', 'intermediate', 'work', '승인하다', '승인하다', 'seunginhada', 'to approve, to authorize', '批准, 认可', '팀장님이 휴가를 승인해 주셨습니다.', 'The team leader approved the vacation.', '组长批准了休假。'),
  ('ko-work-intermediate-62', 'ko', 'intermediate', 'work', '검토하다', '검토하다', 'geomtohada', 'to review, to examine', '审查, 检讨', '계약서를 한번 더 검토해 주세요.', 'Please review the contract one more time.', '请再审查一下合同。'),
  ('ko-work-intermediate-63', 'ko', 'intermediate', 'work', '처리하다', '처리하다', 'cheorihada', 'to process, to handle', '处理, 办理', '이 건은 오늘 중으로 처리하겠습니다.', 'I will handle this matter by the end of today.', '这件事我今天之内处理。'),
  ('ko-work-intermediate-64', 'ko', 'intermediate', 'work', '확인하다', '확인하다', 'hwaginhada', 'to confirm, to verify', '确认, 核实', '이메일을 확인해 주시겠습니까?', 'Could you please check the email?', '能请您确认一下邮件吗？'),
  ('ko-work-intermediate-65', 'ko', 'intermediate', 'work', '요청하다', '요청하다', 'yocheonghada', 'to request, to ask for', '请求, 要求', '자료를 요청드려도 될까요?', 'May I request the materials?', '我可以请求您提供资料吗？'),
  ('ko-work-intermediate-66', 'ko', 'intermediate', 'work', '진행하다', '진행하다', 'jinhaenghada', 'to proceed, to carry out', '进行, 推进', '계획대로 진행하겠습니다.', 'I will proceed as planned.', '我会按计划进行。'),
  ('ko-work-intermediate-67', 'ko', 'intermediate', 'work', '완료하다', '완료하다', 'wallyohada', 'to complete, to finish', '完成, 完了', '작업을 모두 완료했습니다.', 'I have completed all the work.', '工作全部完成了。'),
  ('ko-work-intermediate-68', 'ko', 'intermediate', 'work', '수정하다', '수정하다', 'sujeonghada', 'to revise, to modify', '修改, 修正', '기획안을 수정해서 다시 보내 주세요.', 'Please revise the proposal and send it again.', '请修改企划方案后重新发送。'),
  ('ko-work-intermediate-69', 'ko', 'intermediate', 'work', '작성하다', '작성하다', 'jakseonghada', 'to write up, to draft', '撰写, 编写', '보고서를 작성하는 데 시간이 걸립니다.', 'It takes time to draft the report.', '撰写报告需要时间。'),
  ('ko-work-intermediate-70', 'ko', 'intermediate', 'work', '전달하다', '전달하다', 'jeondalhada', 'to convey, to deliver', '传达, 转告', '이 내용을 팀원들에게 전달해 주세요.', 'Please convey this information to the team members.', '请把这个内容传达给团队成员。'),
  ('ko-work-intermediate-71', 'ko', 'intermediate', 'work', '공유하다', '공유하다', 'gongyuhada', 'to share, to distribute', '共享, 分享', '파일을 메일로 공유하겠습니다.', 'I will share the file via email.', '我会通过邮件共享文件。'),
  ('ko-work-intermediate-72', 'ko', 'intermediate', 'work', '협력하다', '협력하다', 'hyeomnyeokhada', 'to cooperate, to collaborate', '合作, 协力', '다른 팀과 협력해서 일해야 합니다.', 'We need to work in cooperation with other teams.', '需要和其他团队合作完成工作。'),
  ('ko-work-intermediate-73', 'ko', 'intermediate', 'work', '지시하다', '지시하다', 'jisihada', 'to instruct, to direct', '指示, 指令', '팀장님이 업무를 지시하셨습니다.', 'The team leader gave work instructions.', '组长下达了工作指示。'),
  ('ko-work-intermediate-74', 'ko', 'intermediate', 'work', '위임하다', '위임하다', 'wiimhada', 'to delegate, to entrust', '委任, 委托', '이 업무를 후배에게 위임했습니다.', 'I delegated this task to a junior colleague.', '我把这个工作委托给了后辈。'),
  ('ko-work-intermediate-75', 'ko', 'intermediate', 'work', '채용하다', '채용하다', 'chaeyonghada', 'to hire, to recruit', '录用, 招聘', '이번에 신입 사원 다섯 명을 채용했습니다.', 'We hired five new employees this time.', '这次录用了五名新员工。'),
  ('ko-work-intermediate-76', 'ko', 'intermediate', 'work', '해고하다', '해고하다', 'haegohada', 'to fire, to dismiss', '解雇, 开除', '회사가 경영난으로 직원을 해고했습니다.', 'The company fired employees due to financial difficulties.', '公司因经营困难解雇了员工。'),
  ('ko-work-intermediate-77', 'ko', 'intermediate', 'work', '사직서', '사직서', 'sajikseo', 'resignation letter, letter of resignation', '辞职信, 辞呈', '사직서를 제출할 생각입니다.', 'I am thinking of submitting my resignation letter.', '我打算提交辞职信。'),
  ('ko-work-intermediate-78', 'ko', 'intermediate', 'work', '인수인계', '인수인계', 'insuingye', 'handover, job transition', '交接, 工作交接', '퇴사 전에 인수인계를 잘 해야 합니다.', 'You must do a proper handover before leaving the company.', '离职前必须做好工作交接。'),
  ('ko-work-intermediate-79', 'ko', 'intermediate', 'work', '수습기간', '수습기간', 'suseupgigan', 'probation period, trial period', '试用期, 实习期', '수습기간은 3개월입니다.', 'The probation period is 3 months.', '试用期是三个月。'),
  ('ko-work-intermediate-80', 'ko', 'intermediate', 'work', '정규직', '정규직', 'jeonggyujik', 'full-time position, permanent employee', '正式工, 正式职位', '수습 후 정규직으로 전환됩니다.', 'After probation, you will be converted to full-time.', '试用期后转为正式员工。'),
  ('ko-work-intermediate-81', 'ko', 'intermediate', 'work', '계약직', '계약직', 'gyeyakjik', 'contract position, temporary employee', '合同工, 合同制', '계약직으로 1년간 근무할 예정입니다.', 'I will work as a contract employee for one year.', '将以合同制工作一年。'),
  ('ko-work-intermediate-82', 'ko', 'intermediate', 'work', '인턴', '인턴', 'inteon', 'intern, internship', '实习生, 实习', '대학생 인턴을 모집하고 있습니다.', 'We are recruiting college interns.', '正在招募大学生实习生。'),
  ('ko-work-intermediate-83', 'ko', 'intermediate', 'work', '이력서', '이력서', 'iryeokseo', 'resume, curriculum vitae', '简历, 履历', '이력서를 업데이트해야 합니다.', 'I need to update my resume.', '我需要更新简历。'),
  ('ko-work-intermediate-84', 'ko', 'intermediate', 'work', '자기소개서', '자기소개서', 'jagisogaeseo', 'cover letter, self-introduction letter', '自我介绍信, 自荐信', '자기소개서를 쓰는 데 일주일이 걸렸습니다.', 'It took a week to write the cover letter.', '写自我介绍信花了一周。'),
  ('ko-work-intermediate-85', 'ko', 'intermediate', 'work', '지원하다', '지원하다', 'jiwonhada', 'to apply for, to support', '申请, 应聘', '이 회사에 지원하고 싶습니다.', 'I want to apply to this company.', '我想申请这家公司。'),
  ('ko-work-intermediate-86', 'ko', 'intermediate', 'work', '합격하다', '합격하다', 'hapgyeokhada', 'to pass, to be accepted', '合格, 通过', '서류 심사에 합격했습니다.', 'I passed the document screening.', '通过了简历审核。'),
  ('ko-work-intermediate-87', 'ko', 'intermediate', 'work', '불합격', '불합격', 'bulhapgyeok', 'failure, rejection', '不合格, 未通过', '면접에서 불합격 통보를 받았습니다.', 'I received a rejection notice from the interview.', '收到了面试未通过的通知。'),
  ('ko-work-intermediate-88', 'ko', 'intermediate', 'work', '경력', '경력', 'gyeongnyeok', 'career, work experience', '经历, 工作经验', '이 분야에서 10년 경력이 있습니다.', 'I have 10 years of experience in this field.', '在这个领域有十年的工作经验。'),
  ('ko-work-intermediate-89', 'ko', 'intermediate', 'work', '신입', '신입', 'sinip', 'new hire, newcomer', '新人, 新入职', '신입 사원 환영회를 열었습니다.', 'We held a welcome party for the new hires.', '举办了新员工欢迎会。'),
  ('ko-work-intermediate-90', 'ko', 'intermediate', 'work', '선배', '선배', 'seonbae', 'senior colleague, mentor', '前辈, 学长', '선배가 업무를 가르쳐 주었습니다.', 'My senior colleague taught me the work.', '前辈教了我工作内容。'),
  ('ko-work-intermediate-91', 'ko', 'intermediate', 'work', '후배', '후배', 'hubae', 'junior colleague, junior', '后辈, 学弟', '후배를 잘 이끌어 주세요.', 'Please guide your juniors well.', '请好好带领后辈。'),
  ('ko-work-intermediate-92', 'ko', 'intermediate', 'work', '동료', '동료', 'dongnyo', 'colleague, coworker', '同事, 同僚', '동료들과 점심을 함께 먹었습니다.', 'I had lunch together with my colleagues.', '和同事们一起吃了午饭。'),
  ('ko-work-intermediate-93', 'ko', 'intermediate', 'work', '거래처', '거래처', 'georaecheo', 'business client, trading partner', '客户, 交易方', '거래처에 견적서를 보냈습니다.', 'I sent a quotation to the business client.', '向客户发送了报价单。'),
  ('ko-work-intermediate-94', 'ko', 'intermediate', 'work', '견적서', '견적서', 'gyeonjeokseo', 'quotation, estimate', '报价单, 估价单', '견적서를 내일까지 보내 드리겠습니다.', 'I will send the quotation by tomorrow.', '我明天之前把报价单发给您。'),
  ('ko-work-intermediate-95', 'ko', 'intermediate', 'work', '계약서', '계약서', 'gyeyakseo', 'contract document, agreement', '合同书, 协议书', '계약서에 서명해 주십시오.', 'Please sign the contract.', '请在合同上签名。'),
  ('ko-work-intermediate-96', 'ko', 'intermediate', 'work', '청구서', '청구서', 'cheongguseo', 'invoice, bill', '账单, 请款单', '청구서를 월말에 발행합니다.', 'We issue invoices at the end of the month.', '月底开具账单。'),
  ('ko-work-intermediate-97', 'ko', 'intermediate', 'work', '영수증', '영수증', 'yeongsujeung', 'receipt, proof of payment', '收据, 发票', '영수증을 경리부에 제출하세요.', 'Please submit the receipt to the accounting department.', '请把收据交给财务部。'),
  ('ko-work-intermediate-98', 'ko', 'intermediate', 'work', '매출', '매출', 'maechul', 'sales revenue, turnover', '销售额, 营业额', '이번 달 매출이 크게 증가했습니다.', 'This month''s sales revenue increased significantly.', '这个月的销售额大幅增长了。'),
  ('ko-work-intermediate-99', 'ko', 'intermediate', 'work', '이익', '이익', 'iik', 'profit, benefit', '利润, 利益', '올해 이익이 작년보다 늘었습니다.', 'This year''s profit increased compared to last year.', '今年的利润比去年增加了。'),
  ('ko-work-intermediate-100', 'ko', 'intermediate', 'work', '손실', '손실', 'sonsil', 'loss, deficit', '损失, 亏损', '이번 분기에 큰 손실이 발생했습니다.', 'A large loss occurred this quarter.', '这个季度发生了较大的亏损。'),
  ('ko-work-intermediate-101', 'ko', 'intermediate', 'work', '예산', '예산', 'yesan', 'budget, estimate', '预算, 经费', '내년도 예산을 편성하고 있습니다.', 'We are preparing next year''s budget.', '正在编制明年的预算。'),
  ('ko-work-intermediate-102', 'ko', 'intermediate', 'work', '투자하다', '투자하다', 'tujahada', 'to invest, to put money into', '投资, 投入资金', '새로운 사업에 투자하기로 했습니다.', 'We decided to invest in a new business.', '决定投资新事业。'),
  ('ko-work-intermediate-103', 'ko', 'intermediate', 'work', '실적', '실적', 'siljeok', 'performance results, achievements', '业绩, 实绩', '이번 분기 실적이 목표를 초과했습니다.', 'This quarter''s performance exceeded the target.', '这个季度的业绩超过了目标。'),
  ('ko-work-intermediate-104', 'ko', 'intermediate', 'work', '목표', '목표', 'mokpyo', 'goal, target', '目标, 指标', '올해 매출 목표를 세웠습니다.', 'We set this year''s sales target.', '制定了今年的销售目标。'),
  ('ko-work-intermediate-105', 'ko', 'intermediate', 'work', '전략', '전략', 'jeollyak', 'strategy, strategic plan', '战略, 策略', '새로운 마케팅 전략을 수립했습니다.', 'We established a new marketing strategy.', '制定了新的营销战略。'),
  ('ko-work-intermediate-106', 'ko', 'intermediate', 'work', '기획안', '기획안', 'gihoegan', 'project proposal, planning document', '企划案, 策划方案', '기획안을 내일까지 완성해야 합니다.', 'The project proposal must be completed by tomorrow.', '企划案必须明天之前完成。'),
  ('ko-work-intermediate-107', 'ko', 'intermediate', 'work', '제안하다', '제안하다', 'jeanhada', 'to propose, to suggest', '提议, 建议', '새로운 방법을 제안드립니다.', 'I would like to propose a new method.', '我提议一个新的方法。'),
  ('ko-work-intermediate-108', 'ko', 'intermediate', 'work', '피드백', '피드백', 'pideubaek', 'feedback, evaluation', '反馈, 评价', '상사에게 피드백을 받았습니다.', 'I received feedback from my supervisor.', '收到了上司的反馈。'),
  ('ko-work-intermediate-109', 'ko', 'intermediate', 'work', '평가하다', '평가하다', 'pyeonggahada', 'to evaluate, to assess', '评价, 评估', '직원들의 업무 능력을 평가합니다.', 'We evaluate employees'' work abilities.', '对员工的工作能力进行评估。'),
  ('ko-work-intermediate-110', 'ko', 'intermediate', 'work', '인사고과', '인사고과', 'insagogwa', 'performance review, personnel evaluation', '人事考核, 绩效评估', '인사고과가 곧 시작됩니다.', 'Performance reviews are starting soon.', '人事考核即将开始。'),
  ('ko-work-intermediate-111', 'ko', 'intermediate', 'work', '출퇴근', '출퇴근', 'chultoegeun', 'commuting, going to and from work', '通勤, 上下班', '출퇴근 시간이 한 시간 걸립니다.', 'The commuting time takes one hour.', '通勤时间要一个小时。'),
  ('ko-work-intermediate-112', 'ko', 'intermediate', 'work', '교통비', '교통비', 'gyotongbi', 'transportation expenses, commuting cost', '交通费, 通勤费', '회사에서 교통비를 지원해 줍니다.', 'The company supports transportation expenses.', '公司报销交通费。'),
  ('ko-work-intermediate-113', 'ko', 'intermediate', 'work', '명함', '명함', 'myeongham', 'business card, name card', '名片, 名帖', '명함을 교환합시다.', 'Let''s exchange business cards.', '我们交换一下名片吧。'),
  ('ko-work-intermediate-114', 'ko', 'intermediate', 'work', '복사기', '복사기', 'boksagi', 'photocopier, copy machine', '复印机, 影印机', '복사기가 고장 났습니다.', 'The photocopier is broken.', '复印机坏了。'),
  ('ko-work-intermediate-115', 'ko', 'intermediate', 'work', '프린터', '프린터', 'peurinteo', 'printer, printing machine', '打印机, 印刷机', '프린터 용지가 떨어졌습니다.', 'The printer is out of paper.', '打印机没纸了。'),
  ('ko-work-intermediate-116', 'ko', 'intermediate', 'work', '사무실', '사무실', 'samusil', 'office, workplace', '办公室, 事务所', '사무실을 새로 이사했습니다.', 'We moved to a new office.', '搬到了新的办公室。'),
  ('ko-work-intermediate-117', 'ko', 'intermediate', 'work', '회의실', '회의실', 'hoeuisil', 'meeting room, conference room', '会议室, 议事厅', '회의실을 예약해 주세요.', 'Please reserve the meeting room.', '请预约会议室。'),
  ('ko-work-intermediate-118', 'ko', 'intermediate', 'work', '탕비실', '탕비실', 'tangbisil', 'break room, pantry', '茶水间, 休息室', '탕비실에 커피가 있습니다.', 'There is coffee in the break room.', '茶水间有咖啡。'),
  ('ko-work-intermediate-119', 'ko', 'intermediate', 'work', '출입증', '출입증', 'churipjeung', 'access card, ID badge', '出入证, 门禁卡', '출입증을 항상 착용하세요.', 'Please always wear your access card.', '请随时佩戴出入证。'),
  ('ko-work-intermediate-120', 'ko', 'intermediate', 'work', '비품', '비품', 'bipum', 'office supplies, equipment', '办公用品, 备品', '비품 신청서를 작성해 주세요.', 'Please fill out the supply request form.', '请填写办公用品申请单。'),
  ('ko-work-intermediate-121', 'ko', 'intermediate', 'work', '문서', '문서', 'munseo', 'document, paperwork', '文件, 文书', '중요한 문서는 잠금 장치에 보관하세요.', 'Please keep important documents in a locked storage.', '重要文件请保管在锁柜里。'),
  ('ko-work-intermediate-122', 'ko', 'intermediate', 'work', '결제', '결제', 'gyeolje', 'payment, settlement', '结算, 付款', '거래처 결제가 완료되었습니다.', 'Payment to the business partner has been completed.', '向客户的付款已完成。'),
  ('ko-work-intermediate-123', 'ko', 'intermediate', 'work', '납품하다', '납품하다', 'nappumhada', 'to deliver goods, to supply', '交货, 供货', '다음 주까지 납품해야 합니다.', 'We need to deliver the goods by next week.', '必须在下周之前交货。'),
  ('ko-work-intermediate-124', 'ko', 'intermediate', 'work', '발주하다', '발주하다', 'baljuhada', 'to place an order, to order', '下订单, 订购', '원자재를 발주했습니다.', 'I placed an order for raw materials.', '下了原材料的订单。'),
  ('ko-work-intermediate-125', 'ko', 'intermediate', 'work', '재고', '재고', 'jaego', 'inventory, stock', '库存, 存货', '재고가 부족해서 추가 주문이 필요합니다.', 'Additional orders are needed because inventory is low.', '库存不足，需要追加订购。'),
  ('ko-work-intermediate-126', 'ko', 'intermediate', 'work', '납기', '납기', 'napgi', 'delivery deadline, due date for delivery', '交货期, 纳期', '납기를 맞추기 어려울 것 같습니다.', 'It seems difficult to meet the delivery deadline.', '可能很难赶上交货期。'),
  ('ko-work-intermediate-127', 'ko', 'intermediate', 'work', '품질', '품질', 'pumjil', 'quality, product quality', '品质, 质量', '품질 관리에 더 신경 써야 합니다.', 'We need to pay more attention to quality control.', '需要更加注意品质管理。'),
  ('ko-work-intermediate-128', 'ko', 'intermediate', 'work', '출시하다', '출시하다', 'chulsihada', 'to launch, to release', '上市, 发布', '신제품을 다음 달에 출시합니다.', 'We will launch the new product next month.', '下个月发布新产品。'),
  ('ko-work-intermediate-129', 'ko', 'intermediate', 'work', '경쟁사', '경쟁사', 'gyeongjaengsa', 'competitor, rival company', '竞争对手, 竞争公司', '경쟁사의 동향을 파악해야 합니다.', 'We need to understand the competitor''s trends.', '需要了解竞争对手的动态。'),
  ('ko-work-intermediate-130', 'ko', 'intermediate', 'work', '시장', '시장', 'sijang', 'market, marketplace', '市场, 市集', '해외 시장에 진출할 계획입니다.', 'We plan to enter the overseas market.', '计划进军海外市场。'),
  ('ko-work-intermediate-131', 'ko', 'intermediate', 'work', '고객', '고객', 'gogaek', 'customer, client', '顾客, 客户', '고객 만족도 조사를 실시했습니다.', 'We conducted a customer satisfaction survey.', '进行了顾客满意度调查。'),
  ('ko-work-intermediate-132', 'ko', 'intermediate', 'work', '클레임', '클레임', 'keulleim', 'complaint, claim', '投诉, 索赔', '고객으로부터 클레임이 들어왔습니다.', 'A complaint came in from a customer.', '收到了顾客的投诉。'),
  ('ko-work-intermediate-133', 'ko', 'intermediate', 'work', '대응하다', '대응하다', 'daeunghada', 'to respond, to deal with', '应对, 对应', '고객 클레임에 신속히 대응해야 합니다.', 'We must respond quickly to customer complaints.', '必须迅速应对顾客投诉。'),
  ('ko-work-intermediate-134', 'ko', 'intermediate', 'work', '워크숍', '워크숍', 'wokeuswop', 'workshop, seminar', '研讨会, 工作坊', '다음 주에 팀 워크숍이 있습니다.', 'There is a team workshop next week.', '下周有团队研讨会。'),
  ('ko-work-intermediate-135', 'ko', 'intermediate', 'work', '브리핑', '브리핑', 'beuriping', 'briefing, short presentation', '简报, 情况说明', '아침에 브리핑이 있으니 준비하세요.', 'There is a briefing in the morning, so please prepare.', '早上有简报会，请做好准备。'),
  ('ko-work-intermediate-136', 'ko', 'intermediate', 'work', '보안', '보안', 'boan', 'security, information security', '安保, 信息安全', '회사 보안 규정을 지켜 주세요.', 'Please follow the company security regulations.', '请遵守公司安保规定。'),
  ('ko-work-intermediate-137', 'ko', 'intermediate', 'work', '기밀', '기밀', 'gimil', 'confidential information, classified', '机密, 保密', '이 자료는 기밀이니 외부에 유출하지 마세요.', 'This material is confidential, so do not leak it externally.', '这份资料是机密，请勿外泄。'),
  ('ko-work-intermediate-138', 'ko', 'intermediate', 'work', '복지', '복지', 'bokji', 'welfare, well-being', '福利, 福祉', '직원 복지를 위해 헬스장을 운영합니다.', 'We operate a gym for employee welfare.', '为了员工福利运营健身房。'),
  ('ko-work-intermediate-139', 'ko', 'intermediate', 'work', '휴게실', '휴게실', 'hyugesil', 'lounge, rest area', '休息室, 休憩室', '휴게실에서 잠깐 쉬겠습니다.', 'I will take a short break in the lounge.', '我在休息室稍微休息一下。'),
  ('ko-work-intermediate-140', 'ko', 'intermediate', 'work', '야근수당', '야근수당', 'yageunsudang', 'overtime pay, night work allowance', '加班费, 加班津贴', '야근수당이 제대로 나오나요?', 'Is overtime pay being given properly?', '加班费正常发放吗？'),
  ('ko-work-intermediate-141', 'ko', 'intermediate', 'work', '직급', '직급', 'jikgeup', 'job rank, position level', '职级, 级别', '직급에 따라 업무 범위가 다릅니다.', 'The scope of work differs by job rank.', '根据职级，工作范围不同。'),
  ('ko-work-intermediate-142', 'ko', 'intermediate', 'work', '직책', '직책', 'jikchaek', 'job title, position', '职务, 职责', '새로운 직책을 맡게 되었습니다.', 'I have been assigned a new position.', '被委派了新的职务。'),
  ('ko-work-intermediate-143', 'ko', 'intermediate', 'work', '부서', '부서', 'buseo', 'department, division', '部门, 部署', '다른 부서로 이동하고 싶습니다.', 'I want to transfer to a different department.', '我想调到其他部门。'),
  ('ko-work-intermediate-144', 'ko', 'intermediate', 'work', '본사', '본사', 'bonsa', 'headquarters, main office', '总部, 总公司', '본사는 서울에 있습니다.', 'The headquarters is located in Seoul.', '总部位于首尔。'),
  ('ko-work-intermediate-145', 'ko', 'intermediate', 'work', '지사', '지사', 'jisa', 'branch office, subsidiary', '分公司, 支社', '부산 지사에 출장을 갑니다.', 'I am going on a business trip to the Busan branch.', '去釜山分公司出差。'),
  ('ko-work-intermediate-146', 'ko', 'intermediate', 'work', '법인', '법인', 'beobin', 'corporation, legal entity', '法人, 公司法人', '해외 법인을 설립할 계획입니다.', 'We plan to establish an overseas corporation.', '计划设立海外法人。'),
  ('ko-work-intermediate-147', 'ko', 'intermediate', 'work', '사업계획서', '사업계획서', 'saeopgyehoekseo', 'business plan, proposal document', '事业计划书, 商业计划书', '사업계획서를 투자자에게 보냈습니다.', 'I sent the business plan to the investor.', '把事业计划书发给了投资者。'),
  ('ko-work-intermediate-148', 'ko', 'intermediate', 'work', '회계', '회계', 'hoegye', 'accounting, finance', '会计, 财务', '회계 부서에서 감사를 진행합니다.', 'The accounting department is conducting an audit.', '会计部门正在进行审计。'),
  ('ko-work-intermediate-149', 'ko', 'intermediate', 'work', '감사', '감사', 'gamsa', 'audit, inspection', '审计, 监查', '이번 달에 외부 감사가 있습니다.', 'There is an external audit this month.', '这个月有外部审计。'),
  ('ko-work-intermediate-150', 'ko', 'intermediate', 'work', '규정', '규정', 'gyujeong', 'regulation, rule', '规定, 条例', '회사 규정을 반드시 준수해야 합니다.', 'You must strictly follow company regulations.', '必须遵守公司规定。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
