-- Expand ja-jlpt-advanced to 150 curated entries (76-150)
-- Topic: JLPT N1/N2 level vocabulary for advanced Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-jlpt-advanced-76', 'ja', 'advanced', 'JLPT', '趣旨', 'しゅし', 'shushi', 'purpose, gist', '宗旨，要旨', '説明の趣旨を理解しました。', 'I understood the gist of the explanation.', '我理解了说明的要旨。'),
  ('ja-jlpt-advanced-77', 'ja', 'advanced', 'JLPT', '一概に', 'いちがいに', 'ichigaini', 'unconditionally, sweepingly', '一概地', '一概には言えません。', 'You cannot say it unconditionally.', '不能一概而论。'),
  ('ja-jlpt-advanced-78', 'ja', 'advanced', 'JLPT', '見解', 'けんかい', 'kenkai', 'opinion, view', '见解，看法', '専門家の見解を聞きました。', 'I listened to the expert''s opinion.', '我听了专家的见解。'),
  ('ja-jlpt-advanced-79', 'ja', 'advanced', 'JLPT', '懸念', 'けねん', 'kenen', 'concern, apprehension', '担忧，忧虑', '安全に対する懸念が高まっています。', 'Concerns about safety are growing.', '对安全的担忧在增加。'),
  ('ja-jlpt-advanced-80', 'ja', 'advanced', 'JLPT', '是正', 'ぜせい', 'zesei', 'correction, rectification', '纠正', '問題を是正する必要があります。', 'We need to rectify the problem.', '有必要纠正问题。'),
  ('ja-jlpt-advanced-81', 'ja', 'advanced', 'JLPT', '顕著', 'けんちょ', 'kencho', 'remarkable, striking', '显著', '効果が顕著に現れました。', 'The effect appeared remarkably.', '效果显著地呈现了。'),
  ('ja-jlpt-advanced-82', 'ja', 'advanced', 'JLPT', '網羅', 'もうら', 'moura', 'comprehensive coverage', '网罗，涵盖', '全ての情報を網羅しています。', 'It covers all the information comprehensively.', '涵盖了所有信息。'),
  ('ja-jlpt-advanced-83', 'ja', 'advanced', 'JLPT', '踏まえる', 'ふまえる', 'fumaeru', 'to be based on, considering', '基于，考虑到', '現状を踏まえて判断します。', 'I will judge based on the current situation.', '基于现状来判断。'),
  ('ja-jlpt-advanced-84', 'ja', 'advanced', 'JLPT', '妥協', 'だきょう', 'dakyo', 'compromise', '妥协', '双方が妥協しました。', 'Both sides compromised.', '双方做出了妥协。'),
  ('ja-jlpt-advanced-85', 'ja', 'advanced', 'JLPT', '逸脱', 'いつだつ', 'itsudatsu', 'deviation, departure', '脱离，偏离', '規則から逸脱しています。', 'It deviates from the rules.', '偏离了规则。'),
  ('ja-jlpt-advanced-86', 'ja', 'advanced', 'JLPT', '簡潔', 'かんけつ', 'kanketsu', 'concise, brief', '简洁', '簡潔に説明してください。', 'Please explain concisely.', '请简洁地说明。'),
  ('ja-jlpt-advanced-87', 'ja', 'advanced', 'JLPT', '抽象的', 'ちゅうしょうてき', 'chushouteki', 'abstract', '抽象的', '話が抽象的すぎます。', 'The discussion is too abstract.', '话题太抽象了。'),
  ('ja-jlpt-advanced-88', 'ja', 'advanced', 'JLPT', '具体的', 'ぐたいてき', 'gutaiteki', 'concrete, specific', '具体的', '具体的な例を挙げてください。', 'Please give a specific example.', '请举具体的例子。'),
  ('ja-jlpt-advanced-89', 'ja', 'advanced', 'JLPT', '普遍的', 'ふへんてき', 'fuhenteki', 'universal', '普遍的', '普遍的な価値観です。', 'It is a universal value.', '这是普遍的价值观。'),
  ('ja-jlpt-advanced-90', 'ja', 'advanced', 'JLPT', '暫定的', 'ざんていてき', 'zanteiteki', 'provisional, tentative', '暂定的', '暫定的な計画です。', 'It''s a tentative plan.', '这是暂定的计划。'),
  ('ja-jlpt-advanced-91', 'ja', 'advanced', 'JLPT', '潜在的', 'せんざいてき', 'senzaiteki', 'potential, latent', '潜在的', '潜在的なリスクがあります。', 'There is a potential risk.', '存在潜在风险。'),
  ('ja-jlpt-advanced-92', 'ja', 'advanced', 'JLPT', '画期的', 'かっきてき', 'kakkiteki', 'groundbreaking, epoch-making', '划时代的', '画期的な発明です。', 'It is a groundbreaking invention.', '这是划时代的发明。'),
  ('ja-jlpt-advanced-93', 'ja', 'advanced', 'JLPT', '克服', 'こくふく', 'kokufuku', 'overcoming', '克服', '困難を克服しました。', 'I overcame the difficulty.', '我克服了困难。'),
  ('ja-jlpt-advanced-94', 'ja', 'advanced', 'JLPT', '促進', 'そくしん', 'sokushin', 'promotion, acceleration', '促进', '交流を促進します。', 'We promote exchange.', '我们促进交流。'),
  ('ja-jlpt-advanced-95', 'ja', 'advanced', 'JLPT', '抑制', 'よくせい', 'yokusei', 'suppression, restraint', '抑制', '感情を抑制します。', 'I suppress my emotions.', '我抑制情绪。'),
  ('ja-jlpt-advanced-96', 'ja', 'advanced', 'JLPT', '蓄積', 'ちくせき', 'chikuseki', 'accumulation', '积累', '経験を蓄積しています。', 'I am accumulating experience.', '我在积累经验。'),
  ('ja-jlpt-advanced-97', 'ja', 'advanced', 'JLPT', '遂行', 'すいこう', 'suiko', 'execution, carrying out', '执行', '任務を遂行します。', 'I carry out the mission.', '我执行任务。'),
  ('ja-jlpt-advanced-98', 'ja', 'advanced', 'JLPT', '裁量', 'さいりょう', 'sairyo', 'discretion', '裁量，酌情', '裁量に任せます。', 'I leave it to your discretion.', '交由你酌情处理。'),
  ('ja-jlpt-advanced-99', 'ja', 'advanced', 'JLPT', '脆弱', 'ぜいじゃく', 'zeijaku', 'fragile, vulnerable', '脆弱', 'システムが脆弱です。', 'The system is vulnerable.', '系统很脆弱。'),
  ('ja-jlpt-advanced-100', 'ja', 'advanced', 'JLPT', '頑丈', 'がんじょう', 'ganjo', 'sturdy, robust', '坚固', '頑丈な建物です。', 'It''s a sturdy building.', '这是坚固的建筑。'),
  ('ja-jlpt-advanced-101', 'ja', 'advanced', 'JLPT', '膨大', 'ぼうだい', 'boudai', 'enormous, vast', '庞大', '膨大なデータを処理します。', 'We process an enormous amount of data.', '我们处理庞大的数据。'),
  ('ja-jlpt-advanced-102', 'ja', 'advanced', 'JLPT', '微妙', 'びみょう', 'bimyo', 'subtle, delicate', '微妙', '微妙な違いがあります。', 'There is a subtle difference.', '有微妙的区别。'),
  ('ja-jlpt-advanced-103', 'ja', 'advanced', 'JLPT', '斬新', 'ざんしん', 'zanshin', 'novel, innovative', '新颖', '斬新なアイデアです。', 'It''s a novel idea.', '这是新颖的想法。'),
  ('ja-jlpt-advanced-104', 'ja', 'advanced', 'JLPT', '厳密', 'げんみつ', 'genmitsu', 'strict, rigorous', '严密', '厳密に言えば違います。', 'Strictly speaking, it''s different.', '严格来说不一样。'),
  ('ja-jlpt-advanced-105', 'ja', 'advanced', 'JLPT', '多様性', 'たようせい', 'tayousei', 'diversity', '多样性', '多様性を尊重します。', 'We respect diversity.', '我们尊重多样性。'),
  ('ja-jlpt-advanced-106', 'ja', 'advanced', 'JLPT', '一貫', 'いっかん', 'ikkan', 'consistency', '一贯', '一貫した方針です。', 'It''s a consistent policy.', '这是一贯的方针。'),
  ('ja-jlpt-advanced-107', 'ja', 'advanced', 'JLPT', '迅速', 'じんそく', 'jinsoku', 'swift, prompt', '迅速', '迅速に対応します。', 'We respond promptly.', '我们迅速应对。'),
  ('ja-jlpt-advanced-108', 'ja', 'advanced', 'JLPT', '慎重', 'しんちょう', 'shincho', 'cautious, prudent', '慎重', '慎重に検討します。', 'We will consider it carefully.', '我们慎重考虑。'),
  ('ja-jlpt-advanced-109', 'ja', 'advanced', 'JLPT', '柔軟', 'じゅうなん', 'junan', 'flexible', '灵活', '柔軟に対応します。', 'We respond flexibly.', '我们灵活应对。'),
  ('ja-jlpt-advanced-110', 'ja', 'advanced', 'JLPT', '的確', 'てきかく', 'tekikaku', 'accurate, precise', '准确', '的確な判断です。', 'It''s an accurate judgment.', '这是准确的判断。'),
  ('ja-jlpt-advanced-111', 'ja', 'advanced', 'JLPT', '唐突', 'とうとつ', 'tototsu', 'abrupt, sudden', '唐突', '唐突な質問ですが。', 'This is an abrupt question, but...', '冒昧问一下。'),
  ('ja-jlpt-advanced-112', 'ja', 'advanced', 'JLPT', '委託', 'いたく', 'itaku', 'commission, entrust', '委托', '業務を委託します。', 'We commission the work.', '我们委托业务。'),
  ('ja-jlpt-advanced-113', 'ja', 'advanced', 'JLPT', '撤回', 'てっかい', 'tekkai', 'withdrawal, retraction', '撤回', '提案を撤回します。', 'I retract the proposal.', '我撤回提案。'),
  ('ja-jlpt-advanced-114', 'ja', 'advanced', 'JLPT', '催促', 'さいそく', 'saisoku', 'urging, pressing', '催促', '返事を催促します。', 'I press for a reply.', '我催促回复。'),
  ('ja-jlpt-advanced-115', 'ja', 'advanced', 'JLPT', '辞退', 'じたい', 'jitai', 'declining, withdrawal', '婉拒', '招待を辞退しました。', 'I declined the invitation.', '我婉拒了邀请。'),
  ('ja-jlpt-advanced-116', 'ja', 'advanced', 'JLPT', '承諾', 'しょうだく', 'shodaku', 'consent, agreement', '承诺', '承諾を得ました。', 'I obtained consent.', '我获得了承诺。'),
  ('ja-jlpt-advanced-117', 'ja', 'advanced', 'JLPT', '拒否', 'きょひ', 'kyohi', 'refusal, rejection', '拒绝', '要求を拒否しました。', 'I refused the demand.', '我拒绝了要求。'),
  ('ja-jlpt-advanced-118', 'ja', 'advanced', 'JLPT', '譲歩', 'じょうほ', 'jouho', 'concession', '让步', '相手に譲歩しました。', 'I made a concession to the other party.', '我向对方让步了。'),
  ('ja-jlpt-advanced-119', 'ja', 'advanced', 'JLPT', '介入', 'かいにゅう', 'kainyu', 'intervention', '介入', '第三者が介入しました。', 'A third party intervened.', '第三方介入了。'),
  ('ja-jlpt-advanced-120', 'ja', 'advanced', 'JLPT', '排除', 'はいじょ', 'haijo', 'exclusion, elimination', '排除', 'リスクを排除します。', 'We eliminate the risk.', '我们排除风险。'),
  ('ja-jlpt-advanced-121', 'ja', 'advanced', 'JLPT', '統合', 'とうごう', 'tougo', 'integration, unification', '统合', 'システムを統合します。', 'We integrate the systems.', '我们整合系统。'),
  ('ja-jlpt-advanced-122', 'ja', 'advanced', 'JLPT', '分離', 'ぶんり', 'bunri', 'separation', '分离', '権限を分離します。', 'We separate the authorities.', '我们分离权限。'),
  ('ja-jlpt-advanced-123', 'ja', 'advanced', 'JLPT', '補填', 'ほてん', 'hoten', 'compensation, filling a gap', '填补', '損失を補填します。', 'We compensate for the loss.', '我们填补损失。'),
  ('ja-jlpt-advanced-124', 'ja', 'advanced', 'JLPT', '削減', 'さくげん', 'sakugen', 'reduction, cut', '削减', '経費を削減します。', 'We reduce expenses.', '我们削减经费。'),
  ('ja-jlpt-advanced-125', 'ja', 'advanced', 'JLPT', '配慮', 'はいりょ', 'hairyo', 'consideration, care', '照顾，关照', '環境に配慮します。', 'We show consideration for the environment.', '我们考虑环境。'),
  ('ja-jlpt-advanced-126', 'ja', 'advanced', 'JLPT', '帰結', 'きけつ', 'kiketsu', 'conclusion, consequence', '归结', '論理的な帰結です。', 'It''s a logical conclusion.', '这是逻辑上的归结。'),
  ('ja-jlpt-advanced-127', 'ja', 'advanced', 'JLPT', '余儀なく', 'よぎなく', 'yoginaku', 'unavoidably, forced to', '不得不', '変更を余儀なくされました。', 'We were forced to make changes.', '我们不得不做出改变。'),
  ('ja-jlpt-advanced-128', 'ja', 'advanced', 'JLPT', '著しく', 'いちじるしく', 'ichijirushiku', 'remarkably, significantly', '显著地', '成績が著しく向上しました。', 'Performance improved significantly.', '成绩显著提高了。'),
  ('ja-jlpt-advanced-129', 'ja', 'advanced', 'JLPT', '辛うじて', 'かろうじて', 'karoujite', 'barely, narrowly', '勉强', '辛うじて合格しました。', 'I barely passed.', '我勉强通过了。'),
  ('ja-jlpt-advanced-130', 'ja', 'advanced', 'JLPT', '漠然と', 'ばくぜんと', 'bakuzento', 'vaguely', '模糊地', '漠然とした不安を感じます。', 'I feel a vague anxiety.', '我感到模糊的不安。'),
  ('ja-jlpt-advanced-131', 'ja', 'advanced', 'JLPT', '断片的', 'だんぺんてき', 'danpenteki', 'fragmentary', '片段的', '断片的な情報しかありません。', 'We only have fragmentary information.', '只有片段的信息。'),
  ('ja-jlpt-advanced-132', 'ja', 'advanced', 'JLPT', '恣意的', 'しいてき', 'shiiteki', 'arbitrary', '恣意的', '恣意的な解釈は避けるべきです。', 'We should avoid arbitrary interpretation.', '应该避免恣意的解释。'),
  ('ja-jlpt-advanced-133', 'ja', 'advanced', 'JLPT', '齟齬', 'そご', 'sogo', 'discrepancy, disagreement', '龃龉，不一致', '意見に齟齬があります。', 'There is a discrepancy in opinions.', '意见有分歧。'),
  ('ja-jlpt-advanced-134', 'ja', 'advanced', 'JLPT', '逆説的', 'ぎゃくせつてき', 'gyakusetsuteki', 'paradoxical', '悖论的', '逆説的に聞こえます。', 'It sounds paradoxical.', '听起来像悖论。'),
  ('ja-jlpt-advanced-135', 'ja', 'advanced', 'JLPT', '不可欠', 'ふかけつ', 'fukaketsu', 'indispensable', '不可或缺', '努力は不可欠です。', 'Effort is indispensable.', '努力是不可或缺的。'),
  ('ja-jlpt-advanced-136', 'ja', 'advanced', 'JLPT', '不可逆', 'ふかぎゃく', 'fukagyaku', 'irreversible', '不可逆', '不可逆な変化です。', 'It''s an irreversible change.', '这是不可逆的变化。'),
  ('ja-jlpt-advanced-137', 'ja', 'advanced', 'JLPT', '冗長', 'じょうちょう', 'joucho', 'verbose, redundant', '冗长', '説明が冗長です。', 'The explanation is verbose.', '说明太冗长了。'),
  ('ja-jlpt-advanced-138', 'ja', 'advanced', 'JLPT', '端的', 'たんてき', 'tanteki', 'straightforward, direct', '直截了当', '端的に言えば失敗です。', 'To put it bluntly, it''s a failure.', '直截了当地说就是失败。'),
  ('ja-jlpt-advanced-139', 'ja', 'advanced', 'JLPT', '精緻', 'せいち', 'seichi', 'elaborate, meticulous', '精致', '精緻な分析です。', 'It''s a meticulous analysis.', '这是精致的分析。'),
  ('ja-jlpt-advanced-140', 'ja', 'advanced', 'JLPT', '瀬戸際', 'せとぎわ', 'setogiwa', 'brink, critical moment', '紧要关头', '瀬戸際に立たされています。', 'We are standing on the brink.', '我们正处于紧要关头。'),
  ('ja-jlpt-advanced-141', 'ja', 'advanced', 'JLPT', '折衷', 'せっちゅう', 'setchu', 'compromise, blending', '折中', '折衷案を出しました。', 'I proposed a compromise.', '我提出了折中方案。'),
  ('ja-jlpt-advanced-142', 'ja', 'advanced', 'JLPT', '淘汰', 'とうた', 'touta', 'weeding out, elimination', '淘汰', '自然淘汰されます。', 'It will be naturally eliminated.', '会被自然淘汰。'),
  ('ja-jlpt-advanced-143', 'ja', 'advanced', 'JLPT', '自律', 'じりつ', 'jiritsu', 'autonomy, self-discipline', '自律', '自律的に行動します。', 'I act with self-discipline.', '我自律地行动。'),
  ('ja-jlpt-advanced-144', 'ja', 'advanced', 'JLPT', '妨げる', 'さまたげる', 'samatageru', 'to hinder, obstruct', '妨碍', '成長を妨げてはいけません。', 'You must not hinder growth.', '不能妨碍成长。'),
  ('ja-jlpt-advanced-145', 'ja', 'advanced', 'JLPT', '覆す', 'くつがえす', 'kutsugaesu', 'to overturn, reverse', '推翻', '判決を覆しました。', 'The verdict was overturned.', '推翻了判决。'),
  ('ja-jlpt-advanced-146', 'ja', 'advanced', 'JLPT', '培う', 'つちかう', 'tsuchikau', 'to cultivate, foster', '培养', '信頼関係を培います。', 'We cultivate a relationship of trust.', '我们培养信任关系。'),
  ('ja-jlpt-advanced-147', 'ja', 'advanced', 'JLPT', '携わる', 'たずさわる', 'tazusawaru', 'to be involved in', '从事', '研究に携わっています。', 'I am involved in research.', '我从事研究工作。'),
  ('ja-jlpt-advanced-148', 'ja', 'advanced', 'JLPT', '見なす', 'みなす', 'minasu', 'to regard as, deem', '视为', '合格と見なします。', 'It is deemed as passing.', '视为合格。'),
  ('ja-jlpt-advanced-149', 'ja', 'advanced', 'JLPT', '免れる', 'まぬがれる', 'manugareru', 'to escape, avoid', '免于', '責任を免れません。', 'You cannot escape responsibility.', '不能免于责任。'),
  ('ja-jlpt-advanced-150', 'ja', 'advanced', 'JLPT', '凌駕', 'りょうが', 'ryouga', 'surpassing, exceeding', '凌驾', '期待を凌駕する結果です。', 'The result surpasses expectations.', '结果凌驾于期待之上。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
