-- Expand ko-drama-intermediate to 150 curated entries (14-150)
-- Topic: K-drama/variety show/entertainment vocabulary for intermediate Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-drama-intermediate-14', 'ko', 'intermediate', 'anime/drama', '로맨스', '로맨스', 'romaenseu', 'romance, love story', '爱情，浪漫', '로맨스 드라마를 좋아해요.', 'I like romance dramas.', '我喜欢爱情剧。'),
  ('ko-drama-intermediate-15', 'ko', 'intermediate', 'anime/drama', '스릴러', '스릴러', 'seurilleo', 'thriller, suspense', '惊悚，悬疑', '이번 신작은 스릴러 장르예요.', 'This new release is a thriller genre.', '这部新作是惊悚题材。'),
  ('ko-drama-intermediate-16', 'ko', 'intermediate', 'anime/drama', '사극', '사극', 'sageuk', 'historical drama, period drama', '古装剧，历史剧', '사극을 보면 역사를 배울 수 있어요.', 'You can learn history by watching historical dramas.', '看古装剧可以学历史。'),
  ('ko-drama-intermediate-17', 'ko', 'intermediate', 'anime/drama', '멜로', '멜로', 'mello', 'melodrama, romance drama', '情感剧，文艺爱情', '멜로 드라마를 보면 눈물이 나요.', 'I cry when watching melodramas.', '看情感剧会流泪。'),
  ('ko-drama-intermediate-18', 'ko', 'intermediate', 'anime/drama', '판타지', '판타지', 'pantaji', 'fantasy, fantasy genre', '奇幻，幻想', '판타지 드라마가 요즘 인기예요.', 'Fantasy dramas are popular these days.', '奇幻剧最近很受欢迎。'),
  ('ko-drama-intermediate-19', 'ko', 'intermediate', 'anime/drama', '액션', '액션', 'aeksyeon', 'action, action genre', '动作，动作片', '액션 장면이 정말 멋있었어요.', 'The action scenes were really cool.', '动作场面真的很帅。'),
  ('ko-drama-intermediate-20', 'ko', 'intermediate', 'anime/drama', '코미디', '코미디', 'komidi', 'comedy, humor', '喜剧，搞笑', '코미디 드라마를 보면 스트레스가 풀려요.', 'Watching comedy dramas relieves stress.', '看喜剧可以缓解压力。'),
  ('ko-drama-intermediate-21', 'ko', 'intermediate', 'anime/drama', '미스터리', '미스터리', 'miseuteori', 'mystery, whodunit', '悬疑，推理', '미스터리 드라마는 추리하는 재미가 있어요.', 'Mystery dramas have the fun of deduction.', '悬疑剧有推理的乐趣。'),
  ('ko-drama-intermediate-22', 'ko', 'intermediate', 'anime/drama', '시청률', '시청률', 'sicheongnyul', 'viewership rating, ratings', '收视率，收视', '이 드라마 시청률이 20%를 넘었어요.', 'This drama''s ratings exceeded 20%.', '这部剧的收视率超过了20%。'),
  ('ko-drama-intermediate-23', 'ko', 'intermediate', 'anime/drama', '방영', '방영', 'bangyeong', 'airing, broadcast', '播出，放映', '다음 주부터 방영을 시작해요.', 'It starts airing from next week.', '下周开始播出。'),
  ('ko-drama-intermediate-24', 'ko', 'intermediate', 'anime/drama', '재방송', '재방송', 'jaebangsong', 'rerun, rebroadcast', '重播，再播', '재방송으로 다시 봤어요.', 'I watched it again on the rerun.', '我通过重播又看了一遍。'),
  ('ko-drama-intermediate-25', 'ko', 'intermediate', 'anime/drama', '생방송', '생방송', 'saengbangsong', 'live broadcast, live show', '直播，实况', '생방송으로 시상식을 봤어요.', 'I watched the awards ceremony live.', '我看了颁奖典礼的直播。'),
  ('ko-drama-intermediate-26', 'ko', 'intermediate', 'anime/drama', '본방', '본방', 'bonbang', 'first run, original broadcast', '首播，原放送', '본방 사수할 거예요.', 'I''m going to watch the first broadcast.', '我要守着首播看。'),
  ('ko-drama-intermediate-27', 'ko', 'intermediate', 'anime/drama', '주연', '주연', 'juyeon', 'lead role, starring', '主演，主角', '주연 배우가 누구예요?', 'Who is the lead actor?', '主演是谁？'),
  ('ko-drama-intermediate-28', 'ko', 'intermediate', 'anime/drama', '엑스트라', '엑스트라', 'ekseuteura', 'extra, background actor', '群众演员，临时演员', '엑스트라로 촬영에 참여했어요.', 'I participated in filming as an extra.', '我作为群众演员参加了拍摄。'),
  ('ko-drama-intermediate-29', 'ko', 'intermediate', 'anime/drama', '카메오', '카메오', 'kameo', 'cameo, guest appearance', '客串，特别出演', '유명 배우가 카메오로 나왔어요.', 'A famous actor appeared as a cameo.', '著名演员客串出演了。'),
  ('ko-drama-intermediate-30', 'ko', 'intermediate', 'anime/drama', '반전', '반전', 'banjeon', 'plot twist, reversal', '反转，逆转', '마지막에 반전이 있어서 놀랐어요.', 'I was surprised by the twist at the end.', '最后有反转让我很惊讶。'),
  ('ko-drama-intermediate-31', 'ko', 'intermediate', 'anime/drama', '클리프행어', '클리프행어', 'keullipeuhaengeo', 'cliffhanger, suspenseful ending', '悬念，扣人心弦的结尾', '매회 클리프행어로 끝나서 다음 회가 기대돼요.', 'It ends with a cliffhanger every episode so I look forward to the next.', '每集都以悬念结尾，让人期待下一集。'),
  ('ko-drama-intermediate-32', 'ko', 'intermediate', 'anime/drama', '떡밥', '떡밥', 'tteokbap', 'foreshadowing hint, plot bait', '伏笔，暗示', '1화에 뿌린 떡밥을 마지막에 회수했어요.', 'They resolved the foreshadowing from episode 1 at the end.', '第一集埋下的伏笔在最后回收了。'),
  ('ko-drama-intermediate-33', 'ko', 'intermediate', 'anime/drama', '복선', '복선', 'bokseon', 'foreshadowing, setup', '伏笔，预兆', '이 장면이 복선이었어요.', 'This scene was foreshadowing.', '这个场面是伏笔。'),
  ('ko-drama-intermediate-34', 'ko', 'intermediate', 'anime/drama', '해피엔딩', '해피엔딩', 'haepiendings', 'happy ending, good ending', '大团圆结局，美好结局', '해피엔딩이라서 기분이 좋았어요.', 'I felt good because it was a happy ending.', '因为是大团圆结局所以心情很好。'),
  ('ko-drama-intermediate-35', 'ko', 'intermediate', 'anime/drama', '새드엔딩', '새드엔딩', 'saedeuending', 'sad ending, tragic ending', '悲伤结局，悲剧', '새드엔딩이라서 많이 울었어요.', 'I cried a lot because it was a sad ending.', '因为是悲剧结局哭了很多。'),
  ('ko-drama-intermediate-36', 'ko', 'intermediate', 'anime/drama', '열린 결말', '열린 결말', 'yeollin gyeolmal', 'open ending, ambiguous ending', '开放式结局，未定结局', '열린 결말이라서 해석이 다양해요.', 'Since it''s an open ending, there are various interpretations.', '因为是开放式结局所以有各种解读。'),
  ('ko-drama-intermediate-37', 'ko', 'intermediate', 'anime/drama', '각본', '각본', 'gakbon', 'screenplay, scenario', '剧本，脚本', '각본이 탄탄한 드라마예요.', 'It''s a drama with a solid screenplay.', '这是一部剧本扎实的电视剧。'),
  ('ko-drama-intermediate-38', 'ko', 'intermediate', 'anime/drama', '연출', '연출', 'yeonchul', 'directing, production', '导演，演出', '연출이 세련됐어요.', 'The directing is sophisticated.', '导演手法很精致。'),
  ('ko-drama-intermediate-39', 'ko', 'intermediate', 'anime/drama', '촬영지', '촬영지', 'chwaryeongji', 'filming location, set location', '拍摄地，取景地', '드라마 촬영지를 방문했어요.', 'I visited the drama filming location.', '我参观了电视剧的拍摄地。'),
  ('ko-drama-intermediate-40', 'ko', 'intermediate', 'anime/drama', '제작비', '제작비', 'jejakbi', 'production cost, budget', '制作费，预算', '이 드라마는 제작비가 높아요.', 'This drama has a high production budget.', '这部剧制作费很高。'),
  ('ko-drama-intermediate-41', 'ko', 'intermediate', 'anime/drama', '제작사', '제작사', 'jejaksa', 'production company, studio', '制作公司，制片方', '유명한 제작사에서 만들었어요.', 'It was made by a famous production company.', '由著名的制作公司制作。'),
  ('ko-drama-intermediate-42', 'ko', 'intermediate', 'anime/drama', '편성', '편성', 'pyeonseong', 'scheduling, programming', '编排，排期', '금요일 밤으로 편성됐어요.', 'It was scheduled for Friday night.', '被安排在周五晚上播出。'),
  ('ko-drama-intermediate-43', 'ko', 'intermediate', 'anime/drama', '시즌', '시즌', 'sijeun', 'season, series', '季，系列', '시즌 2가 확정됐어요.', 'Season 2 has been confirmed.', '第二季已确定。'),
  ('ko-drama-intermediate-44', 'ko', 'intermediate', 'anime/drama', '회차', '회차', 'hoecha', 'episode number, installment', '集数，回次', '총 16회차로 방영돼요.', 'It airs for a total of 16 episodes.', '共播出16集。'),
  ('ko-drama-intermediate-45', 'ko', 'intermediate', 'anime/drama', 'MC', 'MC', 'emsi', 'MC, host, emcee', '主持人，MC', 'MC가 분위기를 잘 이끌어요.', 'The MC leads the atmosphere well.', '主持人把气氛带得很好。'),
  ('ko-drama-intermediate-46', 'ko', 'intermediate', 'anime/drama', '게스트', '게스트', 'geseuteu', 'guest, guest star', '嘉宾，客人', '이번 게스트가 정말 재미있어요.', 'This week''s guest is really fun.', '这次的嘉宾真的很有趣。'),
  ('ko-drama-intermediate-47', 'ko', 'intermediate', 'anime/drama', '출연', '출연', 'churyeon', 'appearance, starring in', '出演，出场', '새 예능에 출연하기로 했어요.', 'They decided to appear on a new variety show.', '决定出演新的综艺节目。'),
  ('ko-drama-intermediate-48', 'ko', 'intermediate', 'anime/drama', '예능', '예능', 'yeneung', 'variety show, entertainment', '综艺，娱乐节目', '예능 프로그램이 인기 많아요.', 'Variety shows are very popular.', '综艺节目很受欢迎。'),
  ('ko-drama-intermediate-49', 'ko', 'intermediate', 'anime/drama', '토크쇼', '토크쇼', 'tokeusyo', 'talk show, chat show', '脱口秀，访谈节目', '토크쇼에서 비하인드 스토리를 들었어요.', 'I heard behind-the-scenes stories on the talk show.', '在访谈节目上听到了幕后故事。'),
  ('ko-drama-intermediate-50', 'ko', 'intermediate', 'anime/drama', '리얼리티', '리얼리티', 'rieolli ti', 'reality show, reality TV', '真人秀，现实节目', '리얼리티 프로그램에서 일상을 보여줬어요.', 'They showed daily life on the reality show.', '在真人秀中展示了日常生活。'),
  ('ko-drama-intermediate-51', 'ko', 'intermediate', 'anime/drama', '오디션', '오디션', 'odisyeon', 'audition, tryout', '试镜，选拔', '오디션 프로그램에서 1등을 했어요.', 'They won first place on the audition show.', '在选秀节目中获得了第一名。'),
  ('ko-drama-intermediate-52', 'ko', 'intermediate', 'anime/drama', '팬덤', '팬덤', 'paendeom', 'fandom, fan community', '粉丝群体，饭圈', '팬덤의 힘이 대단해요.', 'The power of the fandom is amazing.', '粉丝群体的力量很强大。'),
  ('ko-drama-intermediate-53', 'ko', 'intermediate', 'anime/drama', '덕질', '덕질', 'deokjil', 'fangirling/fanboying, stan activities', '追星，饭圈活动', '요즘 덕질에 빠져 있어요.', 'I''m into fangirling these days.', '最近沉迷于追星。'),
  ('ko-drama-intermediate-54', 'ko', 'intermediate', 'anime/drama', '굿즈', '굿즈', 'gutjeu', 'merchandise, goods', '周边商品，周边', '새 굿즈가 나와서 샀어요.', 'New merchandise came out so I bought it.', '出了新周边商品就买了。'),
  ('ko-drama-intermediate-55', 'ko', 'intermediate', 'anime/drama', '팬미팅', '팬미팅', 'paenmiting', 'fan meeting, fan event', '粉丝见面会，粉丝活动', '팬미팅에서 사인을 받았어요.', 'I got an autograph at the fan meeting.', '在粉丝见面会上得到了签名。'),
  ('ko-drama-intermediate-56', 'ko', 'intermediate', 'anime/drama', '최애', '최애', 'choeae', 'ultimate bias, favorite', '最爱，本命', '최애 배우가 새 드라마에 나와요.', 'My favorite actor is in a new drama.', '最爱的演员出演了新剧。'),
  ('ko-drama-intermediate-57', 'ko', 'intermediate', 'anime/drama', '입덕', '입덕', 'ipdeok', 'becoming a fan, joining a fandom', '入坑，成为粉丝', '이 드라마 보고 입덕했어요.', 'I became a fan after watching this drama.', '看了这部剧就入坑了。'),
  ('ko-drama-intermediate-58', 'ko', 'intermediate', 'anime/drama', '탈덕', '탈덕', 'taldeok', 'leaving a fandom, unfanning', '脱粉，退坑', '실망해서 탈덕했어요.', 'I left the fandom because I was disappointed.', '因为失望所以脱粉了。'),
  ('ko-drama-intermediate-59', 'ko', 'intermediate', 'anime/drama', '아이돌', '아이돌', 'aidol', 'idol, K-pop idol', '偶像，爱豆', '아이돌이 드라마에 도전했어요.', 'The idol tried acting in a drama.', '偶像挑战了电视剧演技。'),
  ('ko-drama-intermediate-60', 'ko', 'intermediate', 'anime/drama', '컴백', '컴백', 'keombaek', 'comeback, return', '回归，复出', '컴백 무대가 화제예요.', 'The comeback stage is a hot topic.', '回归舞台成为热门话题。'),
  ('ko-drama-intermediate-61', 'ko', 'intermediate', 'anime/drama', '뮤직비디오', '뮤직비디오', 'myujikbideo', 'music video, MV', '音乐视频，MV', '뮤직비디오가 영화처럼 아름다워요.', 'The music video is beautiful like a movie.', '音乐视频像电影一样美。'),
  ('ko-drama-intermediate-62', 'ko', 'intermediate', 'anime/drama', '음원', '음원', 'eumwon', 'music source, digital single', '音源，数字单曲', '음원 차트 1위를 했어요.', 'It reached number 1 on the music charts.', '登上了音源榜第一。'),
  ('ko-drama-intermediate-63', 'ko', 'intermediate', 'anime/drama', '스트리밍', '스트리밍', 'seutriming', 'streaming, online streaming', '流媒体，在线播放', '스트리밍으로 드라마를 봐요.', 'I watch dramas through streaming.', '通过流媒体看电视剧。'),
  ('ko-drama-intermediate-64', 'ko', 'intermediate', 'anime/drama', '구독', '구독', 'gudok', 'subscription, subscribe', '订阅，关注', '채널을 구독하고 알림을 켜세요.', 'Subscribe to the channel and turn on notifications.', '订阅频道并打开通知。'),
  ('ko-drama-intermediate-65', 'ko', 'intermediate', 'anime/drama', '자막', '자막', 'jamak', 'subtitles, captions', '字幕，字幕组', '한국어 자막을 켜고 봐요.', 'I watch with Korean subtitles on.', '打开韩语字幕看。'),
  ('ko-drama-intermediate-66', 'ko', 'intermediate', 'anime/drama', 'OTT', 'OTT', 'otiiti', 'OTT platform, streaming service', 'OTT平台，流媒体服务', 'OTT에서 독점 공개됐어요.', 'It was exclusively released on OTT.', '在OTT平台独家上线了。'),
  ('ko-drama-intermediate-67', 'ko', 'intermediate', 'anime/drama', '시상식', '시상식', 'sisangsik', 'awards ceremony, award show', '颁奖典礼，颁奖仪式', '시상식에서 대상을 받았어요.', 'They won the grand prize at the awards ceremony.', '在颁奖典礼上获得了大奖。'),
  ('ko-drama-intermediate-68', 'ko', 'intermediate', 'anime/drama', '수상', '수상', 'susang', 'winning an award, receiving a prize', '获奖，得奖', '수상 소감이 감동적이었어요.', 'The acceptance speech was touching.', '获奖感言很感人。'),
  ('ko-drama-intermediate-69', 'ko', 'intermediate', 'anime/drama', '후보', '후보', 'hubo', 'nominee, candidate', '候选人，提名', '올해 후보에 올랐어요.', 'They were nominated this year.', '今年被提名了。'),
  ('ko-drama-intermediate-70', 'ko', 'intermediate', 'anime/drama', '대상', '대상', 'daesang', 'grand prize, top award', '大奖，大赏', '대상을 받을 자격이 있어요.', 'They deserve to win the grand prize.', '他们有资格获得大奖。'),
  ('ko-drama-intermediate-71', 'ko', 'intermediate', 'anime/drama', '신인상', '신인상', 'sininsang', 'rookie award, best new actor', '新人奖，最佳新人', '신인상을 받고 유명해졌어요.', 'They became famous after winning the rookie award.', '获得新人奖后出名了。'),
  ('ko-drama-intermediate-72', 'ko', 'intermediate', 'anime/drama', '연기', '연기', 'yeongi', 'acting, performance', '演技，表演', '연기력이 정말 뛰어나요.', 'Their acting skills are truly outstanding.', '演技真的很出色。'),
  ('ko-drama-intermediate-73', 'ko', 'intermediate', 'anime/drama', '감정 표현', '감정 표현', 'gamjeong pyohyeon', 'emotional expression, showing emotions', '情感表达，情绪表现', '감정 표현이 섬세해요.', 'The emotional expression is delicate.', '情感表达很细腻。'),
  ('ko-drama-intermediate-74', 'ko', 'intermediate', 'anime/drama', '대사', '대사', 'daesa', 'dialogue, lines', '台词，对白', '대사 전달력이 좋아요.', 'The delivery of lines is good.', '台词表达力很好。'),
  ('ko-drama-intermediate-75', 'ko', 'intermediate', 'anime/drama', '즉흥 연기', '즉흥 연기', 'jeukheung yeongi', 'improvisation, ad-lib acting', '即兴表演，即兴演技', '즉흥 연기로 웃음을 줬어요.', 'They made people laugh with improvised acting.', '用即兴表演逗笑了大家。'),
  ('ko-drama-intermediate-76', 'ko', 'intermediate', 'anime/drama', '몰입', '몰입', 'morip', 'immersion, getting absorbed', '沉浸，投入', '배우의 몰입도가 대단해요.', 'The actor''s level of immersion is amazing.', '演员的沉浸度很了不起。'),
  ('ko-drama-intermediate-77', 'ko', 'intermediate', 'anime/drama', 'OST', 'OST', 'ositi', 'OST, original soundtrack', '原声带，OST', 'OST가 드라마 분위기를 잘 살려요.', 'The OST really captures the drama''s atmosphere.', 'OST很好地烘托了剧的氛围。'),
  ('ko-drama-intermediate-78', 'ko', 'intermediate', 'anime/drama', '삽입곡', '삽입곡', 'sabipgok', 'insert song, featured track', '插曲，插入歌曲', '삽입곡이 장면과 잘 어울려요.', 'The insert song goes well with the scene.', '插曲和场景很搭配。'),
  ('ko-drama-intermediate-79', 'ko', 'intermediate', 'anime/drama', '배경음악', '배경음악', 'baegyeong eumak', 'background music, BGM', '背景音乐，配乐', '배경음악이 긴장감을 높여요.', 'The background music increases the tension.', '背景音乐增加了紧张感。'),
  ('ko-drama-intermediate-80', 'ko', 'intermediate', 'anime/drama', '엔딩곡', '엔딩곡', 'endinggok', 'ending song, credits song', '片尾曲，结尾曲', '엔딩곡을 들으면 여운이 남아요.', 'Hearing the ending song leaves a lingering feeling.', '听到片尾曲会留下余韵。'),
  ('ko-drama-intermediate-81', 'ko', 'intermediate', 'anime/drama', '케미', '케미', 'kemi', 'chemistry, on-screen chemistry', '化学反应，默契', '두 배우의 케미가 좋아요.', 'The two actors have good chemistry.', '两个演员之间很有默契。'),
  ('ko-drama-intermediate-82', 'ko', 'intermediate', 'anime/drama', '커플', '커플', 'keopeul', 'couple, on-screen pair', '情侣，CP', '이 커플을 응원해요.', 'I root for this couple.', '我支持这对情侣。'),
  ('ko-drama-intermediate-83', 'ko', 'intermediate', 'anime/drama', '삼각관계', '삼각관계', 'samgakgwangye', 'love triangle, three-way relationship', '三角关系，三角恋', '삼각관계가 점점 복잡해져요.', 'The love triangle gets more complicated.', '三角关系越来越复杂了。'),
  ('ko-drama-intermediate-84', 'ko', 'intermediate', 'anime/drama', '비하인드', '비하인드', 'bihaindeu', 'behind-the-scenes, making-of', '幕后，花絮', '비하인드 영상이 재미있어요.', 'The behind-the-scenes video is fun.', '幕后花絮视频很有趣。'),
  ('ko-drama-intermediate-85', 'ko', 'intermediate', 'anime/drama', '메이킹', '메이킹', 'meiking', 'making film, production footage', '制作花絮，拍摄幕后', '메이킹 필름을 공개했어요.', 'They released the making film.', '公开了制作花絮。'),
  ('ko-drama-intermediate-86', 'ko', 'intermediate', 'anime/drama', '스포일러', '스포일러', 'seupailleo', 'spoiler, giving away plot', '剧透，泄露剧情', '스포일러하지 마세요!', 'Don''t give spoilers!', '不要剧透！'),
  ('ko-drama-intermediate-87', 'ko', 'intermediate', 'anime/drama', '정주행', '정주행', 'jeongjuhaeng', 'binge-watching, marathon viewing', '追剧，一口气看完', '주말에 정주행했어요.', 'I binge-watched it over the weekend.', '周末一口气追完了。'),
  ('ko-drama-intermediate-88', 'ko', 'intermediate', 'anime/drama', '밤새다', '밤새다', 'bamsaeda', 'stay up all night, pull an all-nighter', '熬夜，通宵', '드라마 보느라 밤새웠어요.', 'I stayed up all night watching the drama.', '因为看电视剧熬了一晚上。'),
  ('ko-drama-intermediate-89', 'ko', 'intermediate', 'anime/drama', '몰아보기', '몰아보기', 'morabogi', 'binge-watching, watching all at once', '一次看完，集中观看', '시즌 1을 몰아보기 했어요.', 'I binge-watched season 1.', '一口气看完了第一季。'),
  ('ko-drama-intermediate-90', 'ko', 'intermediate', 'anime/drama', '후속작', '후속작', 'husokjak', 'sequel, follow-up work', '续作，续集', '후속작이 나올 예정이에요.', 'A sequel is planned.', '续集即将推出。'),
  ('ko-drama-intermediate-91', 'ko', 'intermediate', 'anime/drama', '리메이크', '리메이크', 'rimeikeu', 'remake, reboot', '翻拍，重制', '일본 드라마를 리메이크했어요.', 'They remade a Japanese drama.', '翻拍了一部日剧。'),
  ('ko-drama-intermediate-92', 'ko', 'intermediate', 'anime/drama', '원작', '원작', 'wonjak', 'original work, source material', '原作，原著', '원작 소설도 읽어 봤어요.', 'I also read the original novel.', '我也看了原著小说。'),
  ('ko-drama-intermediate-93', 'ko', 'intermediate', 'anime/drama', '웹툰', '웹툰', 'weptun', 'webtoon, web comic', '网络漫画，条漫', '웹툰 원작 드라마가 많아요.', 'There are many dramas based on webtoons.', '改编自网漫的电视剧很多。'),
  ('ko-drama-intermediate-94', 'ko', 'intermediate', 'anime/drama', '캐스팅', '캐스팅', 'kaeseutin', 'casting, role assignment', '选角，卡司', '캐스팅이 완벽해요.', 'The casting is perfect.', '选角太完美了。'),
  ('ko-drama-intermediate-95', 'ko', 'intermediate', 'anime/drama', '촬영장', '촬영장', 'chwaryeongjang', 'filming set, shooting location', '拍摄现场，片场', '촬영장 분위기가 좋았대요.', 'I heard the atmosphere on set was good.', '据说片场的气氛很好。'),
  ('ko-drama-intermediate-96', 'ko', 'intermediate', 'anime/drama', '대본 리딩', '대본 리딩', 'daebon riding', 'script reading, table read', '剧本围读，读本', '대본 리딩 현장이 공개됐어요.', 'The script reading session was revealed.', '剧本围读现场被公开了。'),
  ('ko-drama-intermediate-97', 'ko', 'intermediate', 'anime/drama', '크랭크인', '크랭크인', 'keuraengkeu in', 'crank-in, start of filming', '开机，开拍', '다음 달에 크랭크인해요.', 'Filming starts next month.', '下个月开机。'),
  ('ko-drama-intermediate-98', 'ko', 'intermediate', 'anime/drama', '크랭크업', '크랭크업', 'keuraengkeu eop', 'crank-up, wrap of filming', '杀青，拍摄结束', '6개월 만에 크랭크업했어요.', 'They wrapped filming after 6 months.', '经过6个月杀青了。'),
  ('ko-drama-intermediate-99', 'ko', 'intermediate', 'anime/drama', '티저', '티저', 'tijeo', 'teaser, preview trailer', '预告片，先导', '티저가 공개되자마자 화제가 됐어요.', 'It became a hot topic as soon as the teaser was released.', '预告片一公开就成了话题。'),
  ('ko-drama-intermediate-100', 'ko', 'intermediate', 'anime/drama', '예고편', '예고편', 'yegopyeon', 'trailer, preview', '预告，预告片', '다음 회 예고편을 봤어요.', 'I watched the next episode preview.', '我看了下一集的预告。'),
  ('ko-drama-intermediate-101', 'ko', 'intermediate', 'anime/drama', '하이라이트', '하이라이트', 'hairaiteu', 'highlight, best moments', '精彩片段，高光时刻', '하이라이트 영상을 편집했어요.', 'I edited a highlight video.', '剪辑了精彩片段的视频。'),
  ('ko-drama-intermediate-102', 'ko', 'intermediate', 'anime/drama', '인물 관계도', '인물 관계도', 'inmul gwangyedo', 'character relationship chart, character map', '人物关系图，角色关系', '인물 관계도를 보면 이해가 쉬워요.', 'It''s easier to understand if you look at the character chart.', '看人物关系图的话更容易理解。'),
  ('ko-drama-intermediate-103', 'ko', 'intermediate', 'anime/drama', '시놉시스', '시놉시스', 'sinopsiseu', 'synopsis, plot summary', '故事梗概，简介', '시놉시스를 읽고 볼지 결정해요.', 'I decide whether to watch after reading the synopsis.', '看了简介再决定要不要看。'),
  ('ko-drama-intermediate-104', 'ko', 'intermediate', 'anime/drama', '첫방', '첫방', 'cheotbang', 'premiere, first episode', '首播，第一集', '첫방 시청률이 높았어요.', 'The premiere ratings were high.', '首播收视率很高。'),
  ('ko-drama-intermediate-105', 'ko', 'intermediate', 'anime/drama', '종영', '종영', 'jongyeong', 'series finale, end of airing', '完结，收官', '아쉽지만 다음 주에 종영해요.', 'It''s sad but it ends next week.', '虽然不舍但下周就完结了。'),
  ('ko-drama-intermediate-106', 'ko', 'intermediate', 'anime/drama', '연장', '연장', 'yeonjang', 'extension, additional episodes', '延长，加集', '인기가 많아서 2회 연장됐어요.', 'It was extended by 2 episodes due to popularity.', '因为人气高所以延长了两集。'),
  ('ko-drama-intermediate-107', 'ko', 'intermediate', 'anime/drama', '동시간대', '동시간대', 'dongsigandae', 'same time slot, competing slot', '同时段，同时间段', '동시간대 시청률 1위예요.', 'It''s number 1 in the same time slot ratings.', '同时段收视率第一。'),
  ('ko-drama-intermediate-108', 'ko', 'intermediate', 'anime/drama', '화제성', '화제성', 'hwajeseong', 'buzz, topicality', '话题性，热度', '화제성이 높은 드라마예요.', 'It''s a drama with high buzz.', '这是一部话题性很高的剧。'),
  ('ko-drama-intermediate-109', 'ko', 'intermediate', 'anime/drama', '명작', '명작', 'myeongjak', 'masterpiece, classic work', '名作，经典之作', '한국 드라마 명작 목록에 있어요.', 'It''s on the list of Korean drama masterpieces.', '在韩剧名作榜单上。'),
  ('ko-drama-intermediate-110', 'ko', 'intermediate', 'anime/drama', '흑역사', '흑역사', 'heugyeoksa', 'dark history, embarrassing past work', '黑历史，不堪回首的过去', '그 드라마는 배우의 흑역사예요.', 'That drama is the actor''s dark history.', '那部剧是那个演员的黑历史。'),
  ('ko-drama-intermediate-111', 'ko', 'intermediate', 'anime/drama', '완결', '완결', 'wangyeol', 'completion, finished series', '完结，完结篇', '원작이 아직 완결되지 않았어요.', 'The original work hasn''t been completed yet.', '原作还没有完结。'),
  ('ko-drama-intermediate-112', 'ko', 'intermediate', 'anime/drama', '연기파', '연기파', 'yeongipa', 'method actor, acting-focused star', '演技派，实力派', '연기파 배우들이 많이 나와요.', 'Many method actors appear in it.', '很多演技派演员出演。'),
  ('ko-drama-intermediate-113', 'ko', 'intermediate', 'anime/drama', '아역', '아역', 'ayeok', 'child actor, child role', '童星，儿童角色', '아역 배우의 연기가 대단해요.', 'The child actor''s performance is amazing.', '小演员的演技很了不起。'),
  ('ko-drama-intermediate-114', 'ko', 'intermediate', 'anime/drama', '악플', '악플', 'akpeul', 'malicious comment, hate comment', '恶评，恶意评论', '악플 때문에 힘들어하고 있어요.', 'They are struggling because of hate comments.', '因为恶评很辛苦。'),
  ('ko-drama-intermediate-115', 'ko', 'intermediate', 'anime/drama', '실검', '실검', 'silgeom', 'real-time search ranking, trending', '实时搜索，热搜', '드라마 방영 후 실검에 올랐어요.', 'It trended after the drama aired.', '电视剧播出后上了热搜。'),
  ('ko-drama-intermediate-116', 'ko', 'intermediate', 'anime/drama', '화제', '화제', 'hwaje', 'hot topic, trending issue', '话题，热门', '이 장면이 온라인에서 화제예요.', 'This scene is a hot topic online.', '这个场面在网上成了话题。'),
  ('ko-drama-intermediate-117', 'ko', 'intermediate', 'anime/drama', '입소문', '입소문', 'ipsomun', 'word of mouth, buzz', '口碑，口口相传', '입소문으로 시청률이 올랐어요.', 'The ratings went up through word of mouth.', '通过口碑收视率上升了。'),
  ('ko-drama-intermediate-118', 'ko', 'intermediate', 'anime/drama', '떡상', '떡상', 'tteoksang', 'skyrocketing, sudden rise', '暴涨，突然爆红', '시청률이 떡상했어요.', 'The ratings skyrocketed.', '收视率暴涨了。'),
  ('ko-drama-intermediate-119', 'ko', 'intermediate', 'anime/drama', '캐릭터', '캐릭터', 'kaerikteo', 'character, persona', '角色，人物形象', '캐릭터가 매력적이에요.', 'The character is charming.', '角色很有魅力。'),
  ('ko-drama-intermediate-120', 'ko', 'intermediate', 'anime/drama', '빌런', '빌런', 'billeon', 'villain, antagonist character', '反派角色，恶人', '이 드라마의 빌런이 무서워요.', 'The villain in this drama is scary.', '这部剧的反派很可怕。'),
  ('ko-drama-intermediate-121', 'ko', 'intermediate', 'anime/drama', '성장물', '성장물', 'seongjangmul', 'coming-of-age story, growth story', '成长剧，成长故事', '청춘 성장물 드라마예요.', 'It''s a youth coming-of-age drama.', '这是一部青春成长剧。'),
  ('ko-drama-intermediate-122', 'ko', 'intermediate', 'anime/drama', '수목드라마', '수목드라마', 'sumok deurama', 'Wed-Thu drama, midweek drama', '水木剧，周三周四剧', '이번 수목드라마가 재미있어요.', 'This Wed-Thu drama is interesting.', '这次的水木剧很有趣。'),
  ('ko-drama-intermediate-123', 'ko', 'intermediate', 'anime/drama', '월화드라마', '월화드라마', 'wolhwa deurama', 'Mon-Tue drama, early week drama', '月火剧，周一周二剧', '월화드라마를 빠짐없이 봐요.', 'I watch the Mon-Tue drama without missing any.', '月火剧一集不落地看。'),
  ('ko-drama-intermediate-124', 'ko', 'intermediate', 'anime/drama', '주말드라마', '주말드라마', 'jumal deurama', 'weekend drama, family drama', '周末剧，家庭剧', '주말드라마는 보통 길어요.', 'Weekend dramas are usually long.', '周末剧通常比较长。'),
  ('ko-drama-intermediate-125', 'ko', 'intermediate', 'anime/drama', '미니시리즈', '미니시리즈', 'minisirijeu', 'mini-series, short series', '迷你剧，短篇剧集', '16부작 미니시리즈예요.', 'It''s a 16-episode mini-series.', '这是16集的迷你剧。'),
  ('ko-drama-intermediate-126', 'ko', 'intermediate', 'anime/drama', '특별출연', '특별출연', 'teukbyeol churyeon', 'special appearance, special guest', '特别出演，友情客串', '특별출연이라서 깜짝 놀랐어요.', 'I was surprised because it was a special appearance.', '因为是特别出演所以吓了一跳。'),
  ('ko-drama-intermediate-127', 'ko', 'intermediate', 'anime/drama', '엔딩 크레딧', '엔딩 크레딧', 'ending keuredit', 'ending credits, end credits', '片尾字幕，演职员表', '엔딩 크레딧까지 꼭 보세요.', 'Make sure to watch until the end credits.', '一定要看到片尾字幕。'),
  ('ko-drama-intermediate-128', 'ko', 'intermediate', 'anime/drama', '후반부', '후반부', 'hubanbu', 'latter half, second half', '后半部分，后半段', '후반부 전개가 아쉬워요.', 'The development in the latter half is disappointing.', '后半段的展开让人遗憾。'),
  ('ko-drama-intermediate-129', 'ko', 'intermediate', 'anime/drama', '전반부', '전반부', 'jeonbanbu', 'first half, earlier part', '前半部分，前半段', '전반부는 정말 재미있었어요.', 'The first half was really fun.', '前半段真的很有趣。'),
  ('ko-drama-intermediate-130', 'ko', 'intermediate', 'anime/drama', '흥행', '흥행', 'heunghaeng', 'box office success, popularity', '票房，大热', '드라마가 흥행에 성공했어요.', 'The drama was a commercial success.', '这部剧大获成功。'),
  ('ko-drama-intermediate-131', 'ko', 'intermediate', 'anime/drama', '안방극장', '안방극장', 'anbang geukjang', 'living room theater, home TV', '客厅影院，家庭电视', '안방극장을 사로잡은 드라마예요.', 'It''s a drama that captivated home viewers.', '这是一部抓住家庭观众的电视剧。'),
  ('ko-drama-intermediate-132', 'ko', 'intermediate', 'anime/drama', '독점', '독점', 'dokjeom', 'exclusive, exclusive rights', '独家，独占', '넷플릭스 독점 공개예요.', 'It''s a Netflix exclusive release.', '是Netflix独家公开。'),
  ('ko-drama-intermediate-133', 'ko', 'intermediate', 'anime/drama', '동시 방영', '동시 방영', 'dongsi bangyeong', 'simultaneous broadcast, simulcast', '同步播出，同时放映', '한국과 동시 방영해요.', 'It airs simultaneously with Korea.', '和韩国同步播出。'),
  ('ko-drama-intermediate-134', 'ko', 'intermediate', 'anime/drama', '총감독', '총감독', 'chonggamdok', 'chief director, executive director', '总导演，总监督', '총감독이 직접 연출했어요.', 'The chief director directed it personally.', '总导演亲自执导了。'),
  ('ko-drama-intermediate-135', 'ko', 'intermediate', 'anime/drama', '작품성', '작품성', 'jakpumseong', 'artistic quality, production value', '作品性，艺术价值', '작품성이 높다는 평가를 받았어요.', 'It received praise for its high artistic quality.', '获得了作品性很高的评价。'),
  ('ko-drama-intermediate-136', 'ko', 'intermediate', 'anime/drama', '완성도', '완성도', 'wanseongdo', 'completeness, level of polish', '完成度，完善程度', '완성도가 높은 작품이에요.', 'It''s a highly polished work.', '这是完成度很高的作品。'),
  ('ko-drama-intermediate-137', 'ko', 'intermediate', 'anime/drama', '몰입감', '몰입감', 'moripgam', 'sense of immersion, engrossing quality', '沉浸感，代入感', '몰입감이 뛰어난 드라마예요.', 'It''s a drama with excellent immersion.', '这是沉浸感很强的电视剧。'),
  ('ko-drama-intermediate-138', 'ko', 'intermediate', 'anime/drama', '클립', '클립', 'keullip', 'clip, video clip', '片段，视频剪辑', '명장면 클립을 공유했어요.', 'I shared a clip of the iconic scene.', '分享了名场面的片段。'),
  ('ko-drama-intermediate-139', 'ko', 'intermediate', 'anime/drama', '댓글', '댓글', 'daetgeul', 'comment, online reply', '评论，留言', '댓글에서 다음 내용을 예측하고 있어요.', 'People are predicting the next plot in the comments.', '评论区在预测接下来的内容。'),
  ('ko-drama-intermediate-140', 'ko', 'intermediate', 'anime/drama', '조회수', '조회수', 'johoisu', 'view count, number of views', '点击量，播放量', '조회수가 천만을 넘었어요.', 'The view count exceeded 10 million.', '播放量超过了一千万。'),
  ('ko-drama-intermediate-141', 'ko', 'intermediate', 'anime/drama', '인기 검색어', '인기 검색어', 'ingi geomsaekeo', 'popular search term, trending keyword', '热门搜索词，热搜词', '배우 이름이 인기 검색어에 올랐어요.', 'The actor''s name appeared in trending searches.', '演员名字上了热搜。'),
  ('ko-drama-intermediate-142', 'ko', 'intermediate', 'anime/drama', '팬아트', '팬아트', 'paen ateu', 'fan art, fan-created artwork', '同人画，粉丝画作', '팬아트를 그려서 올렸어요.', 'I drew fan art and posted it.', '画了同人画上传了。'),
  ('ko-drama-intermediate-143', 'ko', 'intermediate', 'anime/drama', '성덕', '성덕', 'seongdeok', 'successful fan, fan who met their idol', '成功追星的人，圆梦粉丝', '팬미팅에 가서 성덕했어요.', 'I went to the fan meeting and succeeded as a fan.', '去了粉丝见面会圆梦了。'),
  ('ko-drama-intermediate-144', 'ko', 'intermediate', 'anime/drama', '총몇부작', '총몇부작', 'chong myeot bujak', 'total number of episodes, how many parts', '总共几集，多少集', '이 드라마는 총 20부작이에요.', 'This drama is 20 episodes in total.', '这部剧总共20集。'),
  ('ko-drama-intermediate-145', 'ko', 'intermediate', 'anime/drama', '극본', '극본', 'geukbon', 'drama script, playbook', '剧本，戏剧脚本', '극본가가 바뀌어서 걱정이에요.', 'I''m worried because the scriptwriter changed.', '因为编剧换了所以很担心。'),
  ('ko-drama-intermediate-146', 'ko', 'intermediate', 'anime/drama', '시사회', '시사회', 'sisahoe', 'preview screening, press screening', '试映会，首映式', '시사회에 초대받았어요.', 'I was invited to the preview screening.', '被邀请去了试映会。'),
  ('ko-drama-intermediate-147', 'ko', 'intermediate', 'anime/drama', '제작 발표회', '제작 발표회', 'jejak balpyohoe', 'production press conference, launch event', '制作发布会，开机发布会', '제작 발표회에서 출연진을 공개했어요.', 'They revealed the cast at the production press conference.', '在制作发布会上公开了演员阵容。'),
  ('ko-drama-intermediate-148', 'ko', 'intermediate', 'anime/drama', '포스터', '포스터', 'poseuteo', 'poster, promotional image', '海报，宣传照', '공식 포스터가 드디어 나왔어요.', 'The official poster is finally out.', '官方海报终于出来了。'),
  ('ko-drama-intermediate-149', 'ko', 'intermediate', 'anime/drama', '하차', '하차', 'hacha', 'leaving a show, dropping out', '下车，退出节目', '개인 사정으로 프로그램에서 하차했어요.', 'They left the show due to personal reasons.', '因为个人原因退出了节目。'),
  ('ko-drama-intermediate-150', 'ko', 'intermediate', 'anime/drama', '합류', '합류', 'hamryu', 'joining, coming on board', '加入，合流', '새 멤버가 다음 시즌에 합류해요.', 'A new member joins next season.', '新成员下一季加入。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
