-- Expand ja-food-basic to 150 curated entries (16-150)
-- Topic: food and drink vocabulary for basic Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-food-basic-16', 'ja', 'basic', 'food', 'りんご', 'りんご', 'ringo', 'apple, fruit', '苹果，水果', 'りんごを一つ買いました。', 'I bought one apple.', '我买了一个苹果。'),
  ('ja-food-basic-17', 'ja', 'basic', 'food', 'みかん', 'みかん', 'mikan', 'mandarin orange, tangerine', '橘子，柑橘', '冬にみかんを食べます。', 'I eat mandarins in winter.', '冬天吃橘子。'),
  ('ja-food-basic-18', 'ja', 'basic', 'food', 'ぶどう', 'ぶどう', 'budou', 'grape, grapes', '葡萄，提子', 'ぶどうが甘いです。', 'The grapes are sweet.', '葡萄很甜。'),
  ('ja-food-basic-19', 'ja', 'basic', 'food', 'バナナ', 'ばなな', 'banana', 'banana, tropical fruit', '香蕉，热带水果', '毎朝バナナを食べます。', 'I eat a banana every morning.', '我每天早上吃香蕉。'),
  ('ja-food-basic-20', 'ja', 'basic', 'food', 'いちご', 'いちご', 'ichigo', 'strawberry, berry', '草莓，浆果', 'いちごのケーキが好きです。', 'I like strawberry cake.', '我喜欢草莓蛋糕。'),
  ('ja-food-basic-21', 'ja', 'basic', 'food', 'もも', 'もも', 'momo', 'peach, stone fruit', '桃子，桃', '夏にももを食べます。', 'I eat peaches in summer.', '夏天吃桃子。'),
  ('ja-food-basic-22', 'ja', 'basic', 'food', 'すいか', 'すいか', 'suika', 'watermelon, summer fruit', '西瓜，夏季水果', 'すいかが冷たくておいしいです。', 'The watermelon is cold and delicious.', '西瓜又凉又好吃。'),
  ('ja-food-basic-23', 'ja', 'basic', 'food', 'メロン', 'めろん', 'meron', 'melon, cantaloupe', '蜜瓜，哈密瓜', 'メロンは高いです。', 'Melons are expensive.', '蜜瓜很贵。'),
  ('ja-food-basic-24', 'ja', 'basic', 'food', 'レモン', 'れもん', 'remon', 'lemon, citrus', '柠檬，柑橘', 'レモンを絞ります。', 'I squeeze a lemon.', '我挤柠檬。'),
  ('ja-food-basic-25', 'ja', 'basic', 'food', '梨', 'なし', 'nashi', 'pear, Japanese pear', '梨，日本梨', '梨がみずみずしいです。', 'The pear is juicy.', '梨很多汁。'),
  ('ja-food-basic-26', 'ja', 'basic', 'food', '人参', 'にんじん', 'ninjin', 'carrot, root vegetable', '胡萝卜，根菜', '人参を切ります。', 'I cut the carrot.', '我切胡萝卜。'),
  ('ja-food-basic-27', 'ja', 'basic', 'food', '玉ねぎ', 'たまねぎ', 'tamanegi', 'onion, bulb vegetable', '洋葱，葱头', '玉ねぎを炒めます。', 'I stir-fry the onion.', '我炒洋葱。'),
  ('ja-food-basic-28', 'ja', 'basic', 'food', 'じゃがいも', 'じゃがいも', 'jagaimo', 'potato, tuber', '土豆，马铃薯', 'じゃがいもを茹でます。', 'I boil the potatoes.', '我煮土豆。'),
  ('ja-food-basic-29', 'ja', 'basic', 'food', 'トマト', 'とまと', 'tomato', 'tomato, red vegetable', '番茄，西红柿', 'トマトが赤いです。', 'The tomato is red.', '番茄是红色的。'),
  ('ja-food-basic-30', 'ja', 'basic', 'food', 'キャベツ', 'きゃべつ', 'kyabetsu', 'cabbage, leafy green', '卷心菜，包菜', 'キャベツを千切りにします。', 'I shred the cabbage.', '我把卷心菜切丝。'),
  ('ja-food-basic-31', 'ja', 'basic', 'food', 'きゅうり', 'きゅうり', 'kyuuri', 'cucumber, green vegetable', '黄瓜，青瓜', 'きゅうりをサラダに入れます。', 'I put cucumber in the salad.', '我把黄瓜放进沙拉里。'),
  ('ja-food-basic-32', 'ja', 'basic', 'food', 'なす', 'なす', 'nasu', 'eggplant, aubergine', '茄子，紫茄', 'なすを焼きます。', 'I grill the eggplant.', '我烤茄子。'),
  ('ja-food-basic-33', 'ja', 'basic', 'food', 'ほうれん草', 'ほうれんそう', 'hourensou', 'spinach, leafy green', '菠菜，叶菜', 'ほうれん草のおひたしを作ります。', 'I make boiled spinach.', '我做凉拌菠菜。'),
  ('ja-food-basic-34', 'ja', 'basic', 'food', '大根', 'だいこん', 'daikon', 'daikon radish, white radish', '萝卜，白萝卜', '大根をおろします。', 'I grate the daikon.', '我磨萝卜泥。'),
  ('ja-food-basic-35', 'ja', 'basic', 'food', 'ピーマン', 'ぴーまん', 'piiman', 'green pepper, bell pepper', '青椒，甜椒', 'ピーマンが苦いです。', 'The green pepper is bitter.', '青椒是苦的。'),
  ('ja-food-basic-36', 'ja', 'basic', 'food', 'ねぎ', 'ねぎ', 'negi', 'green onion, scallion', '大葱，葱', 'ねぎを刻みます。', 'I chop the green onion.', '我切葱花。'),
  ('ja-food-basic-37', 'ja', 'basic', 'food', 'にんにく', 'にんにく', 'ninniku', 'garlic, seasoning', '大蒜，蒜', 'にんにくを入れます。', 'I add garlic.', '我放大蒜。'),
  ('ja-food-basic-38', 'ja', 'basic', 'food', 'しょうが', 'しょうが', 'shouga', 'ginger, spice', '姜，生姜', 'しょうがをすります。', 'I grate ginger.', '我磨姜。'),
  ('ja-food-basic-39', 'ja', 'basic', 'food', 'きのこ', 'きのこ', 'kinoko', 'mushroom, fungi', '蘑菇，菌类', 'きのこのスープを作ります。', 'I make mushroom soup.', '我做蘑菇汤。'),
  ('ja-food-basic-40', 'ja', 'basic', 'food', '豆腐', 'とうふ', 'toufu', 'tofu, bean curd', '豆腐，豆制品', '豆腐を味噌汁に入れます。', 'I put tofu in miso soup.', '我把豆腐放进味噌汤。'),
  ('ja-food-basic-41', 'ja', 'basic', 'food', '鶏肉', 'とりにく', 'toriniku', 'chicken, poultry', '鸡肉，禽肉', '鶏肉を焼きます。', 'I grill the chicken.', '我烤鸡肉。'),
  ('ja-food-basic-42', 'ja', 'basic', 'food', '豚肉', 'ぶたにく', 'butaniku', 'pork, pig meat', '猪肉，豚肉', '豚肉のしょうが焼きを作ります。', 'I make ginger pork.', '我做姜汁猪肉。'),
  ('ja-food-basic-43', 'ja', 'basic', 'food', '牛肉', 'ぎゅうにく', 'gyuuniku', 'beef, cow meat', '牛肉，牛', '牛肉が高いです。', 'Beef is expensive.', '牛肉很贵。'),
  ('ja-food-basic-44', 'ja', 'basic', 'food', 'えび', 'えび', 'ebi', 'shrimp, prawn', '虾，大虾', 'えびの天ぷらが好きです。', 'I like shrimp tempura.', '我喜欢虾天妇罗。'),
  ('ja-food-basic-45', 'ja', 'basic', 'food', 'いか', 'いか', 'ika', 'squid, calamari', '鱿鱼，乌贼', 'いかを焼きます。', 'I grill the squid.', '我烤鱿鱼。'),
  ('ja-food-basic-46', 'ja', 'basic', 'food', 'たこ', 'たこ', 'tako', 'octopus, sea creature', '章鱼，八爪鱼', 'たこ焼きを食べます。', 'I eat takoyaki.', '我吃章鱼烧。'),
  ('ja-food-basic-47', 'ja', 'basic', 'food', '鮭', 'さけ', 'sake', 'salmon, fish', '三文鱼，鲑鱼', '鮭のおにぎりを買いました。', 'I bought a salmon rice ball.', '我买了三文鱼饭团。'),
  ('ja-food-basic-48', 'ja', 'basic', 'food', 'まぐろ', 'まぐろ', 'maguro', 'tuna, sashimi fish', '金枪鱼，吞拿鱼', 'まぐろの刺身を食べます。', 'I eat tuna sashimi.', '我吃金枪鱼刺身。'),
  ('ja-food-basic-49', 'ja', 'basic', 'food', 'コーヒー', 'こーひー', 'koohii', 'coffee, hot drink', '咖啡，热饮', '毎朝コーヒーを飲みます。', 'I drink coffee every morning.', '我每天早上喝咖啡。'),
  ('ja-food-basic-50', 'ja', 'basic', 'food', 'ジュース', 'じゅーす', 'juusu', 'juice, soft drink', '果汁，饮料', 'オレンジジュースをください。', 'Orange juice, please.', '请给我橙汁。'),
  ('ja-food-basic-51', 'ja', 'basic', 'food', 'ビール', 'びーる', 'biiru', 'beer, alcohol', '啤酒，酒精饮料', '冷たいビールを飲みたいです。', 'I want to drink a cold beer.', '我想喝冰啤酒。'),
  ('ja-food-basic-52', 'ja', 'basic', 'food', 'ワイン', 'わいん', 'wain', 'wine, grape alcohol', '葡萄酒，红酒', '赤ワインが好きです。', 'I like red wine.', '我喜欢红酒。'),
  ('ja-food-basic-53', 'ja', 'basic', 'food', '日本酒', 'にほんしゅ', 'nihonshu', 'sake, Japanese rice wine', '日本清酒，米酒', '日本酒を温めます。', 'I warm up the sake.', '我温日本清酒。'),
  ('ja-food-basic-54', 'ja', 'basic', 'food', '紅茶', 'こうちゃ', 'koucha', 'black tea, English tea', '红茶，英式茶', '紅茶にミルクを入れます。', 'I add milk to black tea.', '我在红茶里加牛奶。'),
  ('ja-food-basic-55', 'ja', 'basic', 'food', '緑茶', 'りょくちゃ', 'ryokucha', 'green tea, Japanese tea', '绿茶，日本茶', '緑茶は体にいいです。', 'Green tea is good for you.', '绿茶对身体好。'),
  ('ja-food-basic-56', 'ja', 'basic', 'food', 'ラーメン', 'らーめん', 'raamen', 'ramen, noodle soup', '拉面，面条汤', 'ラーメンを食べに行きます。', 'I am going to eat ramen.', '我去吃拉面。'),
  ('ja-food-basic-57', 'ja', 'basic', 'food', 'カレー', 'かれー', 'karee', 'curry, curry rice', '咖喱，咖喱饭', 'カレーを作りましょう。', 'Let us make curry.', '我们做咖喱吧。'),
  ('ja-food-basic-58', 'ja', 'basic', 'food', 'すし', 'すし', 'sushi', 'sushi, vinegared rice', '寿司，日式料理', 'すしを食べたいです。', 'I want to eat sushi.', '我想吃寿司。'),
  ('ja-food-basic-59', 'ja', 'basic', 'food', 'そば', 'そば', 'soba', 'buckwheat noodles, soba', '荞麦面，日式面条', '冷たいそばを食べます。', 'I eat cold soba.', '我吃冷荞麦面。'),
  ('ja-food-basic-60', 'ja', 'basic', 'food', 'うどん', 'うどん', 'udon', 'udon noodles, thick noodles', '乌冬面，粗面条', '温かいうどんを注文します。', 'I order hot udon.', '我点热乌冬面。'),
  ('ja-food-basic-61', 'ja', 'basic', 'food', '天ぷら', 'てんぷら', 'tenpura', 'tempura, deep-fried food', '天妇罗，油炸食品', '天ぷらがサクサクです。', 'The tempura is crispy.', '天妇罗很酥脆。'),
  ('ja-food-basic-62', 'ja', 'basic', 'food', '刺身', 'さしみ', 'sashimi', 'sashimi, raw fish', '刺身，生鱼片', '新鮮な刺身を食べます。', 'I eat fresh sashimi.', '我吃新鲜的刺身。'),
  ('ja-food-basic-63', 'ja', 'basic', 'food', '焼き鳥', 'やきとり', 'yakitori', 'grilled chicken skewer, yakitori', '烤鸡串，烧鸟', '焼き鳥を五本ください。', 'Five chicken skewers, please.', '请给我五串烤鸡串。'),
  ('ja-food-basic-64', 'ja', 'basic', 'food', '丼', 'どんぶり', 'donburi', 'rice bowl, bowl dish', '盖饭，丼饭', '牛丼を注文しました。', 'I ordered a beef bowl.', '我点了牛肉盖饭。'),
  ('ja-food-basic-65', 'ja', 'basic', 'food', 'おにぎり', 'おにぎり', 'onigiri', 'rice ball, hand-pressed rice', '饭团，御握', 'おにぎりを二つ買います。', 'I buy two rice balls.', '我买两个饭团。'),
  ('ja-food-basic-66', 'ja', 'basic', 'food', '味噌汁', 'みそしる', 'misoshiru', 'miso soup, Japanese soup', '味噌汤，日式汤', '味噌汁が温かいです。', 'The miso soup is warm.', '味噌汤很热。'),
  ('ja-food-basic-67', 'ja', 'basic', 'food', 'サラダ', 'さらだ', 'sarada', 'salad, vegetable dish', '沙拉，蔬菜拼盘', 'サラダを作ります。', 'I make a salad.', '我做沙拉。'),
  ('ja-food-basic-68', 'ja', 'basic', 'food', 'スープ', 'すーぷ', 'suupu', 'soup, broth', '汤，浓汤', 'スープが熱いです。', 'The soup is hot.', '汤很烫。'),
  ('ja-food-basic-69', 'ja', 'basic', 'food', 'パスタ', 'ぱすた', 'pasuta', 'pasta, Italian noodles', '意大利面，意面', 'パスタを茹でます。', 'I boil pasta.', '我煮意大利面。'),
  ('ja-food-basic-70', 'ja', 'basic', 'food', 'ピザ', 'ぴざ', 'piza', 'pizza, Italian food', '披萨，比萨', 'ピザを注文しましょう。', 'Let us order pizza.', '我们点披萨吧。'),
  ('ja-food-basic-71', 'ja', 'basic', 'food', 'ハンバーガー', 'はんばーがー', 'hanbaagaa', 'hamburger, burger', '汉堡，汉堡包', 'ハンバーガーとポテトをください。', 'A hamburger and fries, please.', '请给我汉堡和薯条。'),
  ('ja-food-basic-72', 'ja', 'basic', 'food', 'サンドイッチ', 'さんどいっち', 'sandoicchi', 'sandwich, bread snack', '三明治，夹心面包', 'サンドイッチを持って行きます。', 'I bring a sandwich.', '我带三明治去。'),
  ('ja-food-basic-73', 'ja', 'basic', 'food', 'ケーキ', 'けーき', 'keeki', 'cake, dessert', '蛋糕，甜点', '誕生日にケーキを食べます。', 'I eat cake on my birthday.', '生日吃蛋糕。'),
  ('ja-food-basic-74', 'ja', 'basic', 'food', 'アイスクリーム', 'あいすくりーむ', 'aisukuriimu', 'ice cream, frozen dessert', '冰淇淋，冰激凌', 'アイスクリームが溶けます。', 'The ice cream is melting.', '冰淇淋要化了。'),
  ('ja-food-basic-75', 'ja', 'basic', 'food', 'チョコレート', 'ちょこれーと', 'chokoreeto', 'chocolate, candy', '巧克力，甜食', 'チョコレートをもらいました。', 'I received chocolate.', '我收到了巧克力。'),
  ('ja-food-basic-76', 'ja', 'basic', 'food', 'クッキー', 'くっきー', 'kukkii', 'cookie, biscuit', '饼干，曲奇', 'クッキーを焼きました。', 'I baked cookies.', '我烤了饼干。'),
  ('ja-food-basic-77', 'ja', 'basic', 'food', '酢', 'す', 'su', 'vinegar, sour seasoning', '醋，酸味调料', '酢を少し入れます。', 'I add a little vinegar.', '我加一点醋。'),
  ('ja-food-basic-78', 'ja', 'basic', 'food', 'こしょう', 'こしょう', 'koshou', 'pepper, black pepper', '胡椒，黑胡椒', 'こしょうをかけます。', 'I sprinkle pepper.', '我撒胡椒。'),
  ('ja-food-basic-79', 'ja', 'basic', 'food', 'バター', 'ばたー', 'bataa', 'butter, dairy spread', '黄油，奶油', 'パンにバターを塗ります。', 'I spread butter on bread.', '我在面包上涂黄油。'),
  ('ja-food-basic-80', 'ja', 'basic', 'food', 'マヨネーズ', 'まよねーず', 'mayoneezu', 'mayonnaise, condiment', '蛋黄酱，美乃滋', 'マヨネーズをかけますか。', 'Do you want mayonnaise?', '要加蛋黄酱吗？'),
  ('ja-food-basic-81', 'ja', 'basic', 'food', 'ケチャップ', 'けちゃっぷ', 'kechappu', 'ketchup, tomato sauce', '番茄酱，茄汁', 'ケチャップをつけます。', 'I put ketchup on it.', '我蘸番茄酱。'),
  ('ja-food-basic-82', 'ja', 'basic', 'food', 'ソース', 'そーす', 'soosu', 'sauce, Worcestershire sauce', '酱汁，调味汁', 'ソースをかけてください。', 'Please put sauce on it.', '请淋上酱汁。'),
  ('ja-food-basic-83', 'ja', 'basic', 'food', '油', 'あぶら', 'abura', 'oil, cooking oil', '油，食用油', 'フライパンに油をひきます。', 'I put oil in the frying pan.', '我在平底锅里倒油。'),
  ('ja-food-basic-84', 'ja', 'basic', 'food', '味', 'あじ', 'aji', 'taste, flavor', '味道，口味', 'この料理は味がいいです。', 'This dish tastes good.', '这道菜味道好。'),
  ('ja-food-basic-85', 'ja', 'basic', 'food', '甘い', 'あまい', 'amai', 'sweet, sugary', '甜的，甜味', 'このケーキは甘いです。', 'This cake is sweet.', '这个蛋糕很甜。'),
  ('ja-food-basic-86', 'ja', 'basic', 'food', '辛い', 'からい', 'karai', 'spicy, hot', '辣的，辛辣', 'このカレーは辛いです。', 'This curry is spicy.', '这个咖喱很辣。'),
  ('ja-food-basic-87', 'ja', 'basic', 'food', '酸っぱい', 'すっぱい', 'suppai', 'sour, acidic', '酸的，酸味', 'レモンは酸っぱいです。', 'Lemons are sour.', '柠檬是酸的。'),
  ('ja-food-basic-88', 'ja', 'basic', 'food', '苦い', 'にがい', 'nigai', 'bitter, astringent', '苦的，苦味', 'このコーヒーは苦いです。', 'This coffee is bitter.', '这杯咖啡很苦。'),
  ('ja-food-basic-89', 'ja', 'basic', 'food', 'しょっぱい', 'しょっぱい', 'shoppai', 'salty, briny', '咸的，盐味', 'このスープはしょっぱいです。', 'This soup is salty.', '这汤很咸。'),
  ('ja-food-basic-90', 'ja', 'basic', 'food', '焼く', 'やく', 'yaku', 'to grill, to bake', '烤，烘焙', '魚を焼きます。', 'I grill fish.', '我烤鱼。'),
  ('ja-food-basic-91', 'ja', 'basic', 'food', '煮る', 'にる', 'niru', 'to boil, to simmer', '煮，炖', '野菜を煮ます。', 'I simmer the vegetables.', '我炖蔬菜。'),
  ('ja-food-basic-92', 'ja', 'basic', 'food', '揚げる', 'あげる', 'ageru', 'to deep-fry, to fry', '炸，油炸', 'チキンを揚げます。', 'I deep-fry chicken.', '我炸鸡。'),
  ('ja-food-basic-93', 'ja', 'basic', 'food', '炒める', 'いためる', 'itameru', 'to stir-fry, to sauté', '炒，翻炒', '野菜を炒めます。', 'I stir-fry vegetables.', '我炒蔬菜。'),
  ('ja-food-basic-94', 'ja', 'basic', 'food', '蒸す', 'むす', 'musu', 'to steam, to steam-cook', '蒸，蒸煮', '肉まんを蒸します。', 'I steam meat buns.', '我蒸肉包子。'),
  ('ja-food-basic-95', 'ja', 'basic', 'food', '茹でる', 'ゆでる', 'yuderu', 'to boil, to parboil', '煮，焯水', '卵を茹でます。', 'I boil eggs.', '我煮鸡蛋。'),
  ('ja-food-basic-96', 'ja', 'basic', 'food', '切る', 'きる', 'kiru', 'to cut, to slice', '切，切片', '野菜を細かく切ります。', 'I cut vegetables finely.', '我把蔬菜切碎。'),
  ('ja-food-basic-97', 'ja', 'basic', 'food', '混ぜる', 'まぜる', 'mazeru', 'to mix, to stir', '搅拌，混合', 'よく混ぜてください。', 'Please mix well.', '请搅拌均匀。'),
  ('ja-food-basic-98', 'ja', 'basic', 'food', '箸', 'はし', 'hashi', 'chopsticks, eating utensil', '筷子，餐具', '箸を使って食べます。', 'I eat with chopsticks.', '我用筷子吃饭。'),
  ('ja-food-basic-99', 'ja', 'basic', 'food', '皿', 'さら', 'sara', 'plate, dish', '盘子，碟子', 'お皿を洗います。', 'I wash the plates.', '我洗盘子。'),
  ('ja-food-basic-100', 'ja', 'basic', 'food', 'コップ', 'こっぷ', 'koppu', 'glass, cup', '杯子，玻璃杯', 'コップに水を入れます。', 'I pour water into a glass.', '我往杯子里倒水。'),
  ('ja-food-basic-101', 'ja', 'basic', 'food', 'フォーク', 'ふぉーく', 'fooku', 'fork, eating utensil', '叉子，餐叉', 'フォークで食べます。', 'I eat with a fork.', '我用叉子吃。'),
  ('ja-food-basic-102', 'ja', 'basic', 'food', 'スプーン', 'すぷーん', 'supuun', 'spoon, eating utensil', '勺子，汤匙', 'スプーンでスープを飲みます。', 'I drink soup with a spoon.', '我用勺子喝汤。'),
  ('ja-food-basic-103', 'ja', 'basic', 'food', 'ナイフ', 'ないふ', 'naifu', 'knife, cutting utensil', '刀，餐刀', 'ナイフで肉を切ります。', 'I cut meat with a knife.', '我用刀切肉。'),
  ('ja-food-basic-104', 'ja', 'basic', 'food', '茶碗', 'ちゃわん', 'chawan', 'rice bowl, tea cup', '饭碗，茶碗', '茶碗にご飯を入れます。', 'I put rice in a bowl.', '我把饭盛到碗里。'),
  ('ja-food-basic-105', 'ja', 'basic', 'food', '鍋', 'なべ', 'nabe', 'pot, hot pot', '锅，火锅', '鍋で料理します。', 'I cook in a pot.', '我用锅做饭。'),
  ('ja-food-basic-106', 'ja', 'basic', 'food', 'フライパン', 'ふらいぱん', 'furaipan', 'frying pan, skillet', '平底锅，煎锅', 'フライパンで焼きます。', 'I cook in a frying pan.', '我用平底锅煎。'),
  ('ja-food-basic-107', 'ja', 'basic', 'food', 'メニュー', 'めにゅー', 'menyuu', 'menu, food list', '菜单，菜谱', 'メニューを見せてください。', 'Please show me the menu.', '请给我看菜单。'),
  ('ja-food-basic-108', 'ja', 'basic', 'food', '注文', 'ちゅうもん', 'chuumon', 'order, ordering', '点餐，订单', '注文してもいいですか。', 'May I order?', '可以点餐吗？'),
  ('ja-food-basic-109', 'ja', 'basic', 'food', '会計', 'かいけい', 'kaikei', 'bill, payment', '结账，付款', '会計をお願いします。', 'The bill, please.', '请结账。'),
  ('ja-food-basic-110', 'ja', 'basic', 'food', 'レシート', 'れしーと', 'reshiito', 'receipt, proof of purchase', '收据，小票', 'レシートをください。', 'Please give me a receipt.', '请给我收据。'),
  ('ja-food-basic-111', 'ja', 'basic', 'food', '予約', 'よやく', 'yoyaku', 'reservation, booking', '预约，预订', 'レストランを予約しました。', 'I made a restaurant reservation.', '我预约了餐厅。'),
  ('ja-food-basic-112', 'ja', 'basic', 'food', '席', 'せき', 'seki', 'seat, table', '座位，席位', '窓側の席がいいです。', 'I prefer a window seat.', '我想要靠窗的座位。'),
  ('ja-food-basic-113', 'ja', 'basic', 'food', '店員', 'てんいん', 'tenin', 'shop staff, waiter', '店员，服务员', '店員を呼びます。', 'I call the waiter.', '我叫服务员。'),
  ('ja-food-basic-114', 'ja', 'basic', 'food', 'おすすめ', 'おすすめ', 'osusume', 'recommendation, special', '推荐，特色菜', 'おすすめは何ですか。', 'What do you recommend?', '有什么推荐的？'),
  ('ja-food-basic-115', 'ja', 'basic', 'food', '定食', 'ていしょく', 'teishoku', 'set meal, combo', '套餐，定食', '魚の定食を頼みます。', 'I order a fish set meal.', '我点鱼套餐。'),
  ('ja-food-basic-116', 'ja', 'basic', 'food', 'おかわり', 'おかわり', 'okawari', 'refill, second helping', '续杯，再来一碗', 'ご飯のおかわりをください。', 'A refill of rice, please.', '请再给我一碗饭。'),
  ('ja-food-basic-117', 'ja', 'basic', 'food', 'テイクアウト', 'ていくあうと', 'teikuauto', 'takeout, to-go', '外带，打包', 'テイクアウトでお願いします。', 'Takeout, please.', '请打包。'),
  ('ja-food-basic-118', 'ja', 'basic', 'food', '朝ご飯', 'あさごはん', 'asagohan', 'breakfast, morning meal', '早饭，早餐', '朝ご飯を食べましたか。', 'Did you eat breakfast?', '你吃早饭了吗？'),
  ('ja-food-basic-119', 'ja', 'basic', 'food', '昼ご飯', 'ひるごはん', 'hirugohan', 'lunch, midday meal', '午饭，午餐', '昼ご飯に何を食べますか。', 'What will you eat for lunch?', '午饭吃什么？'),
  ('ja-food-basic-120', 'ja', 'basic', 'food', '晩ご飯', 'ばんごはん', 'bangohan', 'dinner, evening meal', '晚饭，晚餐', '晩ご飯を一緒に食べましょう。', 'Let us eat dinner together.', '一起吃晚饭吧。'),
  ('ja-food-basic-121', 'ja', 'basic', 'food', 'おやつ', 'おやつ', 'oyatsu', 'snack, treat', '零食，点心', '三時におやつを食べます。', 'I eat a snack at three.', '三点吃零食。'),
  ('ja-food-basic-122', 'ja', 'basic', 'food', '料理', 'りょうり', 'ryouri', 'cooking, cuisine', '做饭，料理', '料理が上手です。', 'You are good at cooking.', '你做饭很好。'),
  ('ja-food-basic-123', 'ja', 'basic', 'food', '食べ物', 'たべもの', 'tabemono', 'food, things to eat', '食物，吃的东西', '好きな食べ物は何ですか。', 'What is your favorite food?', '你喜欢的食物是什么？'),
  ('ja-food-basic-124', 'ja', 'basic', 'food', '飲み物', 'のみもの', 'nomimono', 'drink, beverage', '饮料，喝的东西', '飲み物は何にしますか。', 'What would you like to drink?', '你要喝什么？'),
  ('ja-food-basic-125', 'ja', 'basic', 'food', 'デザート', 'でざーと', 'dezaato', 'dessert, sweet course', '甜品，甜点', 'デザートを注文しますか。', 'Shall we order dessert?', '要点甜品吗？'),
  ('ja-food-basic-126', 'ja', 'basic', 'food', 'お腹がすいた', 'おなかがすいた', 'onaka ga suita', 'hungry, starving', '饿了，肚子饿了', 'お腹がすいたので食べましょう。', 'I am hungry so let us eat.', '我饿了，吃饭吧。'),
  ('ja-food-basic-127', 'ja', 'basic', 'food', 'お腹がいっぱい', 'おなかがいっぱい', 'onaka ga ippai', 'full, stuffed', '吃饱了，肚子很撑', 'お腹がいっぱいです。', 'I am full.', '我吃饱了。'),
  ('ja-food-basic-128', 'ja', 'basic', 'food', 'おいしい', 'おいしい', 'oishii', 'delicious, tasty', '好吃的，美味的', 'この料理はおいしいです。', 'This dish is delicious.', '这道菜很好吃。'),
  ('ja-food-basic-129', 'ja', 'basic', 'food', 'まずい', 'まずい', 'mazui', 'bad-tasting, unpleasant', '难吃的，不好吃', 'この店はまずいです。', 'This restaurant is bad.', '这家店不好吃。'),
  ('ja-food-basic-130', 'ja', 'basic', 'food', '冷たい', 'つめたい', 'tsumetai', 'cold, chilled', '冷的，凉的', '冷たい水をください。', 'Cold water, please.', '请给我冷水。'),
  ('ja-food-basic-131', 'ja', 'basic', 'food', '温かい', 'あたたかい', 'atatakai', 'warm, lukewarm', '温的，温热的', '温かいお茶が飲みたいです。', 'I want to drink warm tea.', '我想喝热茶。'),
  ('ja-food-basic-132', 'ja', 'basic', 'food', '熱い', 'あつい', 'atsui', 'hot, scalding', '烫的，热的', 'スープが熱いです。', 'The soup is hot.', '汤很烫。'),
  ('ja-food-basic-133', 'ja', 'basic', 'food', '新鮮', 'しんせん', 'shinsen', 'fresh, just-caught', '新鲜的，鲜嫩', 'この魚は新鮮です。', 'This fish is fresh.', '这条鱼很新鲜。'),
  ('ja-food-basic-134', 'ja', 'basic', 'food', '冷蔵庫', 'れいぞうこ', 'reizouko', 'refrigerator, fridge', '冰箱，冷藏柜', '冷蔵庫に入れてください。', 'Please put it in the fridge.', '请放进冰箱。'),
  ('ja-food-basic-135', 'ja', 'basic', 'food', '電子レンジ', 'でんしれんじ', 'denshi renji', 'microwave, microwave oven', '微波炉，电子炉', '電子レンジで温めます。', 'I warm it in the microwave.', '我用微波炉加热。'),
  ('ja-food-basic-136', 'ja', 'basic', 'food', 'お弁当箱', 'おべんとうばこ', 'obentoubako', 'lunch box, bento container', '便当盒，饭盒', 'お弁当箱を洗いました。', 'I washed the lunch box.', '我洗了便当盒。'),
  ('ja-food-basic-137', 'ja', 'basic', 'food', 'カップ', 'かっぷ', 'kappu', 'cup, mug', '杯子，马克杯', 'カップにお茶を注ぎます。', 'I pour tea into a cup.', '我往杯子里倒茶。'),
  ('ja-food-basic-138', 'ja', 'basic', 'food', 'ストロー', 'すとろー', 'sutoroo', 'straw, drinking straw', '吸管，饮料管', 'ストローで飲みます。', 'I drink with a straw.', '我用吸管喝。'),
  ('ja-food-basic-139', 'ja', 'basic', 'food', 'お菓子', 'おかし', 'okashi', 'sweets, confectionery', '糖果，点心', 'お菓子を買いました。', 'I bought sweets.', '我买了点心。'),
  ('ja-food-basic-140', 'ja', 'basic', 'food', 'せんべい', 'せんべい', 'senbei', 'rice cracker, senbei', '煎饼，仙贝', 'せんべいをおやつに食べます。', 'I eat rice crackers as a snack.', '我把仙贝当零食吃。'),
  ('ja-food-basic-141', 'ja', 'basic', 'food', '餃子', 'ぎょうざ', 'gyouza', 'dumplings, pot stickers', '饺子，锅贴', '餃子を焼きます。', 'I pan-fry dumplings.', '我煎饺子。'),
  ('ja-food-basic-142', 'ja', 'basic', 'food', 'チャーハン', 'ちゃーはん', 'chaahan', 'fried rice, stir-fried rice', '炒饭，炒米饭', 'チャーハンを作ります。', 'I make fried rice.', '我做炒饭。'),
  ('ja-food-basic-143', 'ja', 'basic', 'food', 'みりん', 'みりん', 'mirin', 'mirin, sweet rice wine', '味醂，甜料酒', 'みりんを少し加えます。', 'I add a little mirin.', '我加一点味醂。'),
  ('ja-food-basic-144', 'ja', 'basic', 'food', '出汁', 'だし', 'dashi', 'soup stock, broth base', '高汤，出汁', '出汁を取ります。', 'I make soup stock.', '我熬高汤。'),
  ('ja-food-basic-145', 'ja', 'basic', 'food', '食べ放題', 'たべほうだい', 'tabehoudai', 'all-you-can-eat, buffet', '自助餐，吃到饱', '食べ放題のお店に行きます。', 'I go to an all-you-can-eat place.', '我去吃自助餐。'),
  ('ja-food-basic-146', 'ja', 'basic', 'food', '飲み放題', 'のみほうだい', 'nomihoudai', 'all-you-can-drink, open bar', '畅饮，喝到饱', '飲み放題がついています。', 'All-you-can-drink is included.', '包含畅饮。'),
  ('ja-food-basic-147', 'ja', 'basic', 'food', '居酒屋', 'いざかや', 'izakaya', 'izakaya, Japanese pub', '居酒屋，日式酒馆', '居酒屋で飲みましょう。', 'Let us drink at an izakaya.', '去居酒屋喝酒吧。'),
  ('ja-food-basic-148', 'ja', 'basic', 'food', 'コンビニ', 'こんびに', 'konbini', 'convenience store, corner shop', '便利店，小卖部', 'コンビニでおにぎりを買います。', 'I buy a rice ball at the convenience store.', '我在便利店买饭团。'),
  ('ja-food-basic-149', 'ja', 'basic', 'food', 'スーパー', 'すーぱー', 'suupaa', 'supermarket, grocery store', '超市，杂货店', 'スーパーで野菜を買います。', 'I buy vegetables at the supermarket.', '我在超市买蔬菜。'),
  ('ja-food-basic-150', 'ja', 'basic', 'food', 'いただきます', 'いただきます', 'itadakimasu', 'bon appétit, thank you for the food', '我开动了，感谢款待', '食べる前にいただきますと言います。', 'I say itadakimasu before eating.', '吃饭前说我开动了。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
