-- Expand ko-life-intermediate to 150 curated entries (9-150)
-- Topic: daily life vocabulary for intermediate Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-life-intermediate-9', 'ko', 'intermediate', 'life', '월세', '월세', 'wolse', 'monthly rent', '月租，房租', '월세를 매달 내요.', 'I pay rent every month.', '每月交房租。'),
  ('ko-life-intermediate-10', 'ko', 'intermediate', 'life', '전세', '전세', 'jeonse', 'lump-sum deposit lease', '全租，押金租房', '전세 계약이 곧 만료돼요.', 'My jeonse contract expires soon.', '全租合同快到期了。'),
  ('ko-life-intermediate-11', 'ko', 'intermediate', 'life', '이사', '이사', 'isa', 'moving, relocation', '搬家，搬迁', '다음 달에 이사해요.', 'I''m moving next month.', '下个月搬家。'),
  ('ko-life-intermediate-12', 'ko', 'intermediate', 'life', '부동산', '부동산', 'budongsan', 'real estate, realtor office', '房地产，中介', '부동산에서 집을 알아보고 있어요.', 'I''m looking for a place at the realtor.', '在中介那里找房子。'),
  ('ko-life-intermediate-13', 'ko', 'intermediate', 'life', '보증금', '보증금', 'bojeunggeum', 'security deposit', '保证金，押金', '보증금을 돌려받았어요.', 'I got my deposit back.', '拿回了押金。'),
  ('ko-life-intermediate-14', 'ko', 'intermediate', 'life', '계약', '계약', 'gyeyak', 'contract, agreement', '合同，契约', '임대 계약서에 서명했어요.', 'I signed the lease contract.', '签了租赁合同。'),
  ('ko-life-intermediate-15', 'ko', 'intermediate', 'life', '집주인', '집주인', 'jipjuin', 'landlord, homeowner', '房东，房主', '집주인이 친절해요.', 'The landlord is kind.', '房东很亲切。'),
  ('ko-life-intermediate-16', 'ko', 'intermediate', 'life', '세입자', '세입자', 'seipja', 'tenant, renter', '租客，承租人', '세입자 권리를 알아야 해요.', 'You should know your tenant rights.', '应该了解租客的权利。'),
  ('ko-life-intermediate-17', 'ko', 'intermediate', 'life', '관리비', '관리비', 'gwanlibi', 'maintenance fee, management fee', '管理费，物业费', '관리비가 매달 10만 원이에요.', 'The maintenance fee is 100,000 won per month.', '管理费每月十万韩元。'),
  ('ko-life-intermediate-18', 'ko', 'intermediate', 'life', '입주', '입주', 'ipju', 'move-in, occupancy', '入住，搬入', '다음 주에 입주할 수 있어요.', 'I can move in next week.', '下周可以入住。'),
  ('ko-life-intermediate-19', 'ko', 'intermediate', 'life', '퇴거', '퇴거', 'toegeo', 'eviction, move-out', '搬出，退房', '퇴거 날짜를 정했어요.', 'We set the move-out date.', '确定了搬出日期。'),
  ('ko-life-intermediate-20', 'ko', 'intermediate', 'life', '원룸', '원룸', 'wonrum', 'studio apartment', '单间，一居室', '대학 근처에 원룸을 구했어요.', 'I found a studio near the university.', '在大学附近找到了单间。'),
  ('ko-life-intermediate-21', 'ko', 'intermediate', 'life', '병원', '병원', 'byeongwon', 'hospital, clinic', '医院，诊所', '배가 아파서 병원에 갔어요.', 'I went to the hospital because my stomach hurt.', '肚子疼去了医院。'),
  ('ko-life-intermediate-22', 'ko', 'intermediate', 'life', '처방전', '처방전', 'cheobangjon', 'prescription', '处方，药方', '의사가 처방전을 써 줬어요.', 'The doctor wrote a prescription.', '医生开了处方。'),
  ('ko-life-intermediate-23', 'ko', 'intermediate', 'life', '증상', '증상', 'jeungsang', 'symptom', '症状', '증상이 어떻게 되세요?', 'What are your symptoms?', '您有什么症状？'),
  ('ko-life-intermediate-24', 'ko', 'intermediate', 'life', '진료', '진료', 'jillyo', 'medical treatment, consultation', '诊疗，看病', '오늘 진료 예약이 있어요.', 'I have a medical appointment today.', '今天有预约看诊。'),
  ('ko-life-intermediate-25', 'ko', 'intermediate', 'life', '건강검진', '건강검진', 'geongangggeomjin', 'health checkup', '体检，健康检查', '매년 건강검진을 받아요.', 'I get a health checkup every year.', '每年做体检。'),
  ('ko-life-intermediate-26', 'ko', 'intermediate', 'life', '약국', '약국', 'yakguk', 'pharmacy, drugstore', '药店，药局', '처방전을 들고 약국에 갔어요.', 'I went to the pharmacy with a prescription.', '拿着处方去了药店。'),
  ('ko-life-intermediate-27', 'ko', 'intermediate', 'life', '주사', '주사', 'jusa', 'injection, shot', '注射，打针', '독감 주사를 맞았어요.', 'I got a flu shot.', '打了流感疫苗。'),
  ('ko-life-intermediate-28', 'ko', 'intermediate', 'life', '입원', '입원', 'ibwon', 'hospitalization', '住院', '할머니가 입원하셨어요.', 'My grandmother was hospitalized.', '奶奶住院了。'),
  ('ko-life-intermediate-29', 'ko', 'intermediate', 'life', '퇴원', '퇴원', 'toewon', 'discharge from hospital', '出院', '내일 퇴원할 수 있대요.', 'They said I can be discharged tomorrow.', '说明天可以出院。'),
  ('ko-life-intermediate-30', 'ko', 'intermediate', 'life', '수술', '수술', 'susul', 'surgery, operation', '手术', '간단한 수술을 받았어요.', 'I had a minor surgery.', '做了一个小手术。'),
  ('ko-life-intermediate-31', 'ko', 'intermediate', 'life', '진단서', '진단서', 'jindanseo', 'medical certificate, diagnosis', '诊断书，诊断证明', '회사에 진단서를 제출했어요.', 'I submitted a medical certificate to the company.', '向公司提交了诊断书。'),
  ('ko-life-intermediate-32', 'ko', 'intermediate', 'life', '보험', '보험', 'boheom', 'insurance', '保险', '건강보험이 적용돼요.', 'Health insurance covers it.', '可以用健康保险。'),
  ('ko-life-intermediate-33', 'ko', 'intermediate', 'life', '계산대', '계산대', 'gyesandae', 'checkout counter, cashier', '收银台，结账处', '계산대에서 줄을 섰어요.', 'I stood in line at the checkout.', '在收银台排队了。'),
  ('ko-life-intermediate-34', 'ko', 'intermediate', 'life', '할인', '할인', 'harin', 'discount, sale', '折扣，打折', '이 옷 할인 중이에요.', 'These clothes are on sale.', '这件衣服在打折。'),
  ('ko-life-intermediate-35', 'ko', 'intermediate', 'life', '세일', '세일', 'seil', 'sale, clearance', '促销，大减价', '백화점에서 세일해요.', 'The department store is having a sale.', '百货商店在搞促销。'),
  ('ko-life-intermediate-36', 'ko', 'intermediate', 'life', '환불', '환불', 'hwanbul', 'refund', '退款，退钱', '이 물건 환불할 수 있어요?', 'Can I get a refund for this item?', '这个东西可以退款吗？'),
  ('ko-life-intermediate-37', 'ko', 'intermediate', 'life', '교환', '교환', 'gyohwan', 'exchange, swap', '换货，交换', '사이즈가 안 맞아서 교환했어요.', 'I exchanged it because the size didn''t fit.', '尺码不对换了货。'),
  ('ko-life-intermediate-38', 'ko', 'intermediate', 'life', '영수증', '영수증', 'yeongsujeung', 'receipt', '收据，小票', '영수증 필요하세요?', 'Do you need a receipt?', '需要收据吗？'),
  ('ko-life-intermediate-39', 'ko', 'intermediate', 'life', '장바구니', '장바구니', 'jangbaguni', 'shopping cart, basket', '购物篮，购物车', '장바구니에 넣어 두세요.', 'Put it in the shopping cart.', '放在购物车里吧。'),
  ('ko-life-intermediate-40', 'ko', 'intermediate', 'life', '포인트', '포인트', 'pointeu', 'loyalty points, rewards points', '积分，点数', '포인트 적립할게요.', 'I''ll earn points.', '我要攒积分。'),
  ('ko-life-intermediate-41', 'ko', 'intermediate', 'life', '계좌', '계좌', 'gyejwa', 'bank account', '银行账户，账号', '새 계좌를 개설했어요.', 'I opened a new bank account.', '开了新的银行账户。'),
  ('ko-life-intermediate-42', 'ko', 'intermediate', 'life', '송금', '송금', 'songgeum', 'money transfer, remittance', '汇款，转账', '해외 송금 수수료가 비싸요.', 'International transfer fees are expensive.', '海外汇款手续费很贵。'),
  ('ko-life-intermediate-43', 'ko', 'intermediate', 'life', '이체', '이체', 'iche', 'bank transfer', '转账', '월세를 이체했어요.', 'I transferred the rent.', '转了房租。'),
  ('ko-life-intermediate-44', 'ko', 'intermediate', 'life', '출금', '출금', 'chulgeum', 'withdrawal', '取款，提现', 'ATM에서 출금했어요.', 'I made a withdrawal at the ATM.', '在ATM取了钱。'),
  ('ko-life-intermediate-45', 'ko', 'intermediate', 'life', '입금', '입금', 'ipgeum', 'deposit', '存款，入账', '월급이 입금됐어요.', 'My salary was deposited.', '工资到账了。'),
  ('ko-life-intermediate-46', 'ko', 'intermediate', 'life', '잔액', '잔액', 'janaek', 'account balance', '余额', '잔액이 부족해요.', 'The balance is insufficient.', '余额不足。'),
  ('ko-life-intermediate-47', 'ko', 'intermediate', 'life', '수수료', '수수료', 'susuryo', 'service fee, commission', '手续费，佣金', '이체 수수료가 면제돼요.', 'The transfer fee is waived.', '转账手续费免除了。'),
  ('ko-life-intermediate-48', 'ko', 'intermediate', 'life', '대출', '대출', 'daechul', 'loan, borrowing', '贷款，借款', '학자금 대출을 갚고 있어요.', 'I''m repaying my student loan.', '在还学生贷款。'),
  ('ko-life-intermediate-49', 'ko', 'intermediate', 'life', '저축', '저축', 'jeochuk', 'savings, saving money', '储蓄，存钱', '매달 저축하고 있어요.', 'I save money every month.', '每月在存钱。'),
  ('ko-life-intermediate-50', 'ko', 'intermediate', 'life', '이자', '이자', 'ija', 'interest', '利息', '예금 이자가 낮아요.', 'Deposit interest rates are low.', '存款利息很低。'),
  ('ko-life-intermediate-51', 'ko', 'intermediate', 'life', '소포', '소포', 'sopo', 'parcel, package', '包裹，邮包', '외국에서 소포가 왔어요.', 'A parcel came from abroad.', '从国外寄来了包裹。'),
  ('ko-life-intermediate-52', 'ko', 'intermediate', 'life', '등기', '등기', 'deunggi', 'registered mail', '挂号信，挂号邮件', '등기로 보내 주세요.', 'Please send it by registered mail.', '请用挂号邮件寄。'),
  ('ko-life-intermediate-53', 'ko', 'intermediate', 'life', '우편번호', '우편번호', 'upyeonbeonho', 'postal code, zip code', '邮编，邮政编码', '우편번호를 확인해 주세요.', 'Please check the postal code.', '请确认邮编。'),
  ('ko-life-intermediate-54', 'ko', 'intermediate', 'life', '택배', '택배', 'taekbae', 'courier delivery, parcel delivery', '快递，速递', '택배가 언제 오나요?', 'When will the delivery arrive?', '快递什么时候到？'),
  ('ko-life-intermediate-55', 'ko', 'intermediate', 'life', '배송', '배송', 'baesong', 'shipping, delivery', '配送，送货', '배송 기간이 얼마나 걸려요?', 'How long does shipping take?', '配送需要多长时间？'),
  ('ko-life-intermediate-56', 'ko', 'intermediate', 'life', '운송장', '운송장', 'unsongjang', 'waybill, tracking slip', '运单，快递单', '운송장 번호로 조회할 수 있어요.', 'You can track it with the waybill number.', '可以用运单号查询。'),
  ('ko-life-intermediate-57', 'ko', 'intermediate', 'life', '반품', '반품', 'banpum', 'product return', '退货', '반품 신청을 했어요.', 'I applied for a return.', '申请了退货。'),
  ('ko-life-intermediate-58', 'ko', 'intermediate', 'life', '주민등록증', '주민등록증', 'jumindeungnokcheung', 'resident registration card, ID card', '身份证，居民登录证', '주민등록증을 갱신해야 해요.', 'I need to renew my ID card.', '需要更新身份证。'),
  ('ko-life-intermediate-59', 'ko', 'intermediate', 'life', '신고', '신고', 'singo', 'report, declaration', '申报，报案', '분실 신고를 했어요.', 'I filed a loss report.', '报了遗失。'),
  ('ko-life-intermediate-60', 'ko', 'intermediate', 'life', '운전면허증', '운전면허증', 'unjeonmyeonheojeung', 'driver''s license', '驾照，驾驶证', '운전면허증을 취득했어요.', 'I got my driver''s license.', '拿到了驾照。'),
  ('ko-life-intermediate-61', 'ko', 'intermediate', 'life', '여권', '여권', 'yeogwon', 'passport', '护照', '여권 유효기간을 확인하세요.', 'Check your passport''s expiration date.', '请确认护照有效期。'),
  ('ko-life-intermediate-62', 'ko', 'intermediate', 'life', '비자', '비자', 'bija', 'visa', '签证', '비자 연장 신청을 했어요.', 'I applied for a visa extension.', '申请了签证延期。'),
  ('ko-life-intermediate-63', 'ko', 'intermediate', 'life', '전입신고', '전입신고', 'jeonipsingo', 'residence registration, move-in report', '迁入申报，转入登记', '이사 후에 전입신고를 해야 해요.', 'You need to register your new address after moving.', '搬家后需要办迁入登记。'),
  ('ko-life-intermediate-64', 'ko', 'intermediate', 'life', '인감', '인감', 'ingam', 'registered seal, personal stamp', '印鉴，印章', '인감증명서가 필요해요.', 'I need a seal certificate.', '需要印鉴证明。'),
  ('ko-life-intermediate-65', 'ko', 'intermediate', 'life', '등본', '등본', 'deungbon', 'certified copy, registry', '副本，登记簿', '주민등록등본을 떼 왔어요.', 'I got a certified copy of my resident registration.', '开了居民登录副本。'),
  ('ko-life-intermediate-66', 'ko', 'intermediate', 'life', '전기세', '전기세', 'jeongise', 'electricity bill', '电费', '여름에 전기세가 많이 나와요.', 'The electricity bill is high in summer.', '夏天电费很高。'),
  ('ko-life-intermediate-67', 'ko', 'intermediate', 'life', '가스비', '가스비', 'gaseu bi', 'gas bill', '燃气费，煤气费', '겨울에 가스비가 올라요.', 'Gas bills go up in winter.', '冬天燃气费上涨。'),
  ('ko-life-intermediate-68', 'ko', 'intermediate', 'life', '수도세', '수도세', 'sudose', 'water bill', '水费', '수도세를 아끼려고 노력해요.', 'I try to save on water bills.', '尽量节省水费。'),
  ('ko-life-intermediate-69', 'ko', 'intermediate', 'life', '인터넷 요금', '인터넷 요금', 'inteonet yogeum', 'internet fee, internet bill', '网费，上网费', '인터넷 요금이 자동이체돼요.', 'The internet bill is auto-debited.', '网费自动扣款。'),
  ('ko-life-intermediate-70', 'ko', 'intermediate', 'life', '난방비', '난방비', 'nanbangbi', 'heating bill, heating cost', '暖气费，取暖费', '난방비가 부담이 돼요.', 'The heating bill is a burden.', '暖气费是负担。'),
  ('ko-life-intermediate-71', 'ko', 'intermediate', 'life', '자동이체', '자동이체', 'jadongiche', 'automatic transfer, direct debit', '自动转账，自动扣款', '공과금을 자동이체로 내요.', 'I pay utility bills by auto-debit.', '公共费用用自动扣款交。'),
  ('ko-life-intermediate-72', 'ko', 'intermediate', 'life', '고지서', '고지서', 'gojiseo', 'bill notice, payment notice', '缴费通知单，账单', '고지서가 우편함에 왔어요.', 'The bill notice came in the mailbox.', '缴费通知单放在了信箱里。'),
  ('ko-life-intermediate-73', 'ko', 'intermediate', 'life', '분리수거', '분리수거', 'bullisugeo', 'recycling sorting, waste separation', '分类回收，垃圾分类', '분리수거를 제대로 해야 해요.', 'You must sort recyclables properly.', '必须正确进行垃圾分类。'),
  ('ko-life-intermediate-74', 'ko', 'intermediate', 'life', '재활용', '재활용', 'jaehwalyong', 'recycling, reuse', '回收利用，再利用', '재활용품은 따로 모아요.', 'I collect recyclables separately.', '回收物品分开收集。'),
  ('ko-life-intermediate-75', 'ko', 'intermediate', 'life', '음식물 쓰레기', '음식물 쓰레기', 'eumsingmul sseuregi', 'food waste', '厨余垃圾，食物垃圾', '음식물 쓰레기는 전용 봉투에 넣어요.', 'Food waste goes in the designated bag.', '厨余垃圾放在专用袋里。'),
  ('ko-life-intermediate-76', 'ko', 'intermediate', 'life', '반상회', '반상회', 'bansanghoe', 'neighborhood meeting', '居民会议，班常会', '반상회에서 주차 문제를 논의했어요.', 'We discussed parking at the neighborhood meeting.', '在居民会议上讨论了停车问题。'),
  ('ko-life-intermediate-77', 'ko', 'intermediate', 'life', '소음', '소음', 'soeum', 'noise, sound pollution', '噪音，噪声', '층간 소음 때문에 힘들어요.', 'Inter-floor noise is really tough.', '楼层间噪音很烦。'),
  ('ko-life-intermediate-78', 'ko', 'intermediate', 'life', '경비실', '경비실', 'gyeongbisil', 'security office, guard room', '警卫室，保安室', '택배를 경비실에 맡겼어요.', 'I left the delivery at the security office.', '把快递放在了警卫室。'),
  ('ko-life-intermediate-79', 'ko', 'intermediate', 'life', '주차', '주차', 'jucha', 'parking', '停车', '주차 공간이 부족해요.', 'There isn''t enough parking space.', '停车位不够。'),
  ('ko-life-intermediate-80', 'ko', 'intermediate', 'life', '장마', '장마', 'jangma', 'monsoon season, rainy season', '梅雨季，雨季', '장마철에 비가 많이 와요.', 'It rains a lot during the monsoon season.', '梅雨季下很多雨。'),
  ('ko-life-intermediate-81', 'ko', 'intermediate', 'life', '태풍', '태풍', 'taepung', 'typhoon', '台风', '태풍이 내일 오래요.', 'They say a typhoon is coming tomorrow.', '说明天有台风来。'),
  ('ko-life-intermediate-82', 'ko', 'intermediate', 'life', '자외선', '자외선', 'jawoeseon', 'UV rays, ultraviolet', '紫外线', '자외선 차단제를 발라요.', 'I put on sunscreen.', '涂了防晒霜。'),
  ('ko-life-intermediate-83', 'ko', 'intermediate', 'life', '미세먼지', '미세먼지', 'misemeonji', 'fine dust, air pollution', '雾霾，细颗粒物', '미세먼지가 심해서 마스크를 써요.', 'I wear a mask because the fine dust is bad.', '雾霾严重所以戴口罩。'),
  ('ko-life-intermediate-84', 'ko', 'intermediate', 'life', '폭염', '폭염', 'pogyeom', 'heatwave, extreme heat', '酷暑，热浪', '올여름 폭염이 심했어요.', 'This summer''s heatwave was severe.', '今年夏天酷暑很严重。'),
  ('ko-life-intermediate-85', 'ko', 'intermediate', 'life', '한파', '한파', 'hanpa', 'cold wave, cold snap', '寒潮，寒流', '한파 주의보가 내려졌어요.', 'A cold wave advisory was issued.', '发布了寒潮预警。'),
  ('ko-life-intermediate-86', 'ko', 'intermediate', 'life', '습도', '습도', 'seupdo', 'humidity', '湿度', '습도가 높아서 불쾌해요.', 'It''s uncomfortable because the humidity is high.', '湿度高很难受。'),
  ('ko-life-intermediate-87', 'ko', 'intermediate', 'life', '일기예보', '일기예보', 'ilgiyebo', 'weather forecast', '天气预报', '일기예보를 확인했어요.', 'I checked the weather forecast.', '查了天气预报。'),
  ('ko-life-intermediate-88', 'ko', 'intermediate', 'life', '취미', '취미', 'chwimi', 'hobby, pastime', '爱好，兴趣', '취미로 요리를 해요.', 'I cook as a hobby.', '爱好是做饭。'),
  ('ko-life-intermediate-89', 'ko', 'intermediate', 'life', '학원', '학원', 'hagwon', 'academy, private institute', '补习班，学院', '영어 학원에 다녀요.', 'I attend an English academy.', '在上英语补习班。'),
  ('ko-life-intermediate-90', 'ko', 'intermediate', 'life', '헬스장', '헬스장', 'helseujang', 'gym, fitness center', '健身房', '퇴근 후에 헬스장에 가요.', 'I go to the gym after work.', '下班后去健身房。'),
  ('ko-life-intermediate-91', 'ko', 'intermediate', 'life', '동호회', '동호회', 'donghohoe', 'club, hobby group', '社团，兴趣小组', '등산 동호회에 가입했어요.', 'I joined a hiking club.', '加入了登山社团。'),
  ('ko-life-intermediate-92', 'ko', 'intermediate', 'life', '독서', '독서', 'dokseo', 'reading books', '读书，阅读', '주말에 독서를 즐겨요.', 'I enjoy reading on weekends.', '周末喜欢看书。'),
  ('ko-life-intermediate-93', 'ko', 'intermediate', 'life', '산책', '산책', 'sanchaek', 'walk, stroll', '散步', '저녁에 산책을 해요.', 'I take a walk in the evening.', '晚上去散步。'),
  ('ko-life-intermediate-94', 'ko', 'intermediate', 'life', '자격증', '자격증', 'jagyeokjeung', 'certificate, qualification', '资格证，证书', '자격증 시험을 준비하고 있어요.', 'I''m preparing for a certification exam.', '在准备资格证考试。'),
  ('ko-life-intermediate-95', 'ko', 'intermediate', 'life', '출퇴근', '출퇴근', 'chultoegeun', 'commuting', '上下班，通勤', '출퇴근 시간이 길어요.', 'My commute is long.', '通勤时间很长。'),
  ('ko-life-intermediate-96', 'ko', 'intermediate', 'life', '지하철', '지하철', 'jihacheol', 'subway, metro', '地铁', '지하철로 출근해요.', 'I commute by subway.', '坐地铁上班。'),
  ('ko-life-intermediate-97', 'ko', 'intermediate', 'life', '교통비', '교통비', 'gyotongbi', 'transportation cost, fare', '交通费', '교통비가 매달 많이 들어요.', 'Transportation costs a lot every month.', '每月交通费花很多。'),
  ('ko-life-intermediate-98', 'ko', 'intermediate', 'life', '교통카드', '교통카드', 'gyotongkadeu', 'transit card, T-money', '交通卡', '교통카드를 충전했어요.', 'I recharged my transit card.', '给交通卡充了值。'),
  ('ko-life-intermediate-99', 'ko', 'intermediate', 'life', '정류장', '정류장', 'jeongnyujang', 'bus stop, station', '站台，车站', '다음 정류장에서 내려요.', 'I get off at the next stop.', '在下一站下车。'),
  ('ko-life-intermediate-100', 'ko', 'intermediate', 'life', '환승', '환승', 'hwanseung', 'transfer (transportation)', '换乘，转车', '2호선으로 환승하세요.', 'Transfer to Line 2.', '请换乘2号线。'),
  ('ko-life-intermediate-101', 'ko', 'intermediate', 'life', '출구', '출구', 'chulgu', 'exit', '出口', '3번 출구로 나오세요.', 'Come out through Exit 3.', '请从3号出口出来。'),
  ('ko-life-intermediate-102', 'ko', 'intermediate', 'life', '배차 간격', '배차 간격', 'baecha gangyeok', 'bus/train frequency, headway', '发车间隔，班次间隔', '출퇴근 시간에 배차 간격이 짧아요.', 'The headway is short during rush hour.', '上下班时间发车间隔短。'),
  ('ko-life-intermediate-103', 'ko', 'intermediate', 'life', '카드', '카드', 'kadeu', 'credit card, debit card', '信用卡，银行卡', '카드로 결제할게요.', 'I''ll pay by card.', '用卡付款。'),
  ('ko-life-intermediate-104', 'ko', 'intermediate', 'life', '현금', '현금', 'hyeongeum', 'cash', '现金', '현금으로 내도 돼요?', 'Can I pay in cash?', '可以付现金吗？'),
  ('ko-life-intermediate-105', 'ko', 'intermediate', 'life', '할부', '할부', 'halbu', 'installment payment', '分期付款', '3개월 할부로 결제했어요.', 'I paid in 3-month installments.', '用三个月分期付的。'),
  ('ko-life-intermediate-106', 'ko', 'intermediate', 'life', '연체', '연체', 'yeonche', 'overdue payment, delinquency', '逾期，欠费', '카드 대금을 연체하면 안 돼요.', 'You shouldn''t be late on credit card payments.', '信用卡不能逾期。'),
  ('ko-life-intermediate-107', 'ko', 'intermediate', 'life', '신용등급', '신용등급', 'sinyongdeunggeup', 'credit score, credit rating', '信用等级，信用评分', '신용등급이 높아야 대출이 쉬워요.', 'A high credit score makes borrowing easier.', '信用等级高贷款容易。'),
  ('ko-life-intermediate-108', 'ko', 'intermediate', 'life', '적금', '적금', 'jeokgeum', 'installment savings, fixed deposit', '定期存款，定存', '적금 만기가 돌아왔어요.', 'My fixed deposit matured.', '定期存款到期了。'),
  ('ko-life-intermediate-109', 'ko', 'intermediate', 'life', '세금', '세금', 'segeum', 'tax', '税，税金', '소득세 신고를 해야 해요.', 'I need to file my income tax.', '需要申报所得税。'),
  ('ko-life-intermediate-110', 'ko', 'intermediate', 'life', '연말정산', '연말정산', 'yeonmaljeongsan', 'year-end tax settlement', '年终结算，年终清算', '연말정산 서류를 준비했어요.', 'I prepared the year-end tax documents.', '准备了年终结算材料。'),
  ('ko-life-intermediate-111', 'ko', 'intermediate', 'life', '월급', '월급', 'wolgeup', 'monthly salary, paycheck', '月薪，工资', '월급날이 기다려져요.', 'I look forward to payday.', '期待发工资的日子。'),
  ('ko-life-intermediate-112', 'ko', 'intermediate', 'life', '야근', '야근', 'yageun', 'overtime work', '加班', '요즘 야근이 많아요.', 'I''ve been working overtime a lot lately.', '最近加班很多。'),
  ('ko-life-intermediate-113', 'ko', 'intermediate', 'life', '연차', '연차', 'yeoncha', 'annual leave, paid vacation', '年假，带薪休假', '연차를 내고 여행 갈 거예요.', 'I''ll take annual leave and go on a trip.', '请年假去旅行。'),
  ('ko-life-intermediate-114', 'ko', 'intermediate', 'life', '퇴근', '퇴근', 'toegeun', 'leaving work, clocking out', '下班', '오늘 일찍 퇴근했어요.', 'I left work early today.', '今天提前下班了。'),
  ('ko-life-intermediate-115', 'ko', 'intermediate', 'life', '회식', '회식', 'hoesik', 'company dinner, team dinner', '聚餐，公司聚餐', '내일 부서 회식이 있어요.', 'There''s a team dinner tomorrow.', '明天有部门聚餐。'),
  ('ko-life-intermediate-116', 'ko', 'intermediate', 'life', '명절', '명절', 'myeongjeol', 'holiday, national holiday', '节日，传统节日', '명절에 고향에 가요.', 'I go to my hometown on holidays.', '节日回老家。'),
  ('ko-life-intermediate-117', 'ko', 'intermediate', 'life', '설날', '설날', 'seollal', 'Lunar New Year', '春节，新年', '설날에 떡국을 먹어요.', 'We eat rice cake soup on New Year''s.', '春节吃年糕汤。'),
  ('ko-life-intermediate-118', 'ko', 'intermediate', 'life', '추석', '추석', 'chuseok', 'Chuseok, Korean Thanksgiving', '中秋节，秋夕', '추석에 송편을 만들어요.', 'We make songpyeon on Chuseok.', '秋夕做松饼。'),
  ('ko-life-intermediate-119', 'ko', 'intermediate', 'life', '세탁기', '세탁기', 'setakgi', 'washing machine', '洗衣机', '세탁기를 돌려야 해요.', 'I need to run the washing machine.', '得开洗衣机。'),
  ('ko-life-intermediate-120', 'ko', 'intermediate', 'life', '건조기', '건조기', 'geonjogi', 'dryer', '烘干机，干衣机', '비 오는 날은 건조기를 써요.', 'I use the dryer on rainy days.', '下雨天用烘干机。'),
  ('ko-life-intermediate-121', 'ko', 'intermediate', 'life', '에어컨', '에어컨', 'eeokon', 'air conditioner', '空调', '에어컨을 틀어도 돼요?', 'Can I turn on the AC?', '可以开空调吗？'),
  ('ko-life-intermediate-122', 'ko', 'intermediate', 'life', '보일러', '보일러', 'boilleo', 'boiler, heater', '锅炉，暖气', '보일러를 켜 주세요.', 'Please turn on the heater.', '请开暖气。'),
  ('ko-life-intermediate-123', 'ko', 'intermediate', 'life', '정수기', '정수기', 'jeongsuggi', 'water purifier', '净水器', '정수기 필터를 교체했어요.', 'I replaced the water purifier filter.', '换了净水器滤芯。'),
  ('ko-life-intermediate-124', 'ko', 'intermediate', 'life', '청소기', '청소기', 'cheongsogi', 'vacuum cleaner', '吸尘器', '로봇 청소기를 샀어요.', 'I bought a robot vacuum.', '买了扫地机器人。'),
  ('ko-life-intermediate-125', 'ko', 'intermediate', 'life', '쓰레기봉투', '쓰레기봉투', 'sseuregibongtu', 'garbage bag, trash bag', '垃圾袋', '쓰레기봉투를 사야 해요.', 'I need to buy garbage bags.', '需要买垃圾袋。'),
  ('ko-life-intermediate-126', 'ko', 'intermediate', 'life', '민원', '민원', 'minwon', 'civil complaint, public service request', '民事诉求，投诉', '인터넷으로 민원 신청했어요.', 'I filed a public service request online.', '在网上提交了民事申请。'),
  ('ko-life-intermediate-127', 'ko', 'intermediate', 'life', '주민센터', '주민센터', 'juminsenteo', 'community service center', '居民中心，社区中心', '주민센터에서 서류를 발급받았어요.', 'I got documents issued at the community center.', '在居民中心开了证明。'),
  ('ko-life-intermediate-128', 'ko', 'intermediate', 'life', '전출', '전출', 'jeonchul', 'moving out registration', '迁出登记', '전출 신고를 먼저 해야 해요.', 'You need to file the move-out registration first.', '需要先办迁出登记。'),
  ('ko-life-intermediate-129', 'ko', 'intermediate', 'life', '국민연금', '국민연금', 'gungmin yeongeum', 'national pension', '国民年金，养老保险', '국민연금을 매달 납부해요.', 'I pay national pension every month.', '每月缴纳国民年金。'),
  ('ko-life-intermediate-130', 'ko', 'intermediate', 'life', '건강보험', '건강보험', 'geongang boheom', 'health insurance', '健康保险，医疗保险', '건강보험료가 올랐어요.', 'Health insurance premiums went up.', '健康保险费涨了。'),
  ('ko-life-intermediate-131', 'ko', 'intermediate', 'life', '통장', '통장', 'tongjang', 'bankbook, passbook', '存折，银行簿', '통장을 새로 만들었어요.', 'I got a new bankbook.', '办了新存折。'),
  ('ko-life-intermediate-132', 'ko', 'intermediate', 'life', '공과금', '공과금', 'gonggwageum', 'utility bills', '公共费用，水电费', '공과금을 한꺼번에 냈어요.', 'I paid all the utility bills at once.', '一次性交了水电费。'),
  ('ko-life-intermediate-133', 'ko', 'intermediate', 'life', '인터넷 뱅킹', '인터넷 뱅킹', 'inteonet baenking', 'internet banking, online banking', '网上银行，网银', '인터넷 뱅킹으로 이체했어요.', 'I transferred money via online banking.', '通过网银转了账。'),
  ('ko-life-intermediate-134', 'ko', 'intermediate', 'life', '편의점', '편의점', 'pyeonuijeom', 'convenience store', '便利店', '편의점에서 도시락을 샀어요.', 'I bought a lunchbox at the convenience store.', '在便利店买了便当。'),
  ('ko-life-intermediate-135', 'ko', 'intermediate', 'life', '대형마트', '대형마트', 'daehyeongmateu', 'supermarket, hypermarket', '大型超市', '주말에 대형마트에서 장을 봐요.', 'I do grocery shopping at the supermarket on weekends.', '周末在大超市买菜。'),
  ('ko-life-intermediate-136', 'ko', 'intermediate', 'life', '장보기', '장보기', 'jangbogi', 'grocery shopping', '买菜，采购', '퇴근 후에 장보기를 했어요.', 'I did grocery shopping after work.', '下班后去买了菜。'),
  ('ko-life-intermediate-137', 'ko', 'intermediate', 'life', '배달', '배달', 'baedal', 'delivery (food)', '外卖，送餐', '오늘은 배달 시켜 먹자.', 'Let''s order delivery today.', '今天叫外卖吃吧。'),
  ('ko-life-intermediate-138', 'ko', 'intermediate', 'life', '예약', '예약', 'yeyak', 'reservation, appointment', '预约，预定', '식당 예약을 했어요.', 'I made a restaurant reservation.', '预约了餐厅。'),
  ('ko-life-intermediate-139', 'ko', 'intermediate', 'life', '대기', '대기', 'daegi', 'waiting, standby', '等待，排队', '대기 시간이 30분이에요.', 'The wait time is 30 minutes.', '等待时间30分钟。'),
  ('ko-life-intermediate-140', 'ko', 'intermediate', 'life', '주문', '주문', 'jumun', 'order (food/goods)', '点单，下单', '키오스크로 주문했어요.', 'I ordered via the kiosk.', '用自助点餐机点了单。'),
  ('ko-life-intermediate-141', 'ko', 'intermediate', 'life', '알레르기', '알레르기', 'allereugi', 'allergy', '过敏', '땅콩 알레르기가 있어요.', 'I have a peanut allergy.', '我对花生过敏。'),
  ('ko-life-intermediate-142', 'ko', 'intermediate', 'life', '체력', '체력', 'cheryeok', 'stamina, physical strength', '体力', '체력이 많이 떨어졌어요.', 'My stamina has dropped a lot.', '体力下降了很多。'),
  ('ko-life-intermediate-143', 'ko', 'intermediate', 'life', '스트레스', '스트레스', 'seuteureseu', 'stress', '压力', '요즘 스트레스를 많이 받아요.', 'I''m under a lot of stress lately.', '最近压力很大。'),
  ('ko-life-intermediate-144', 'ko', 'intermediate', 'life', '불면증', '불면증', 'bulmyeonjeung', 'insomnia', '失眠症', '불면증 때문에 힘들어요.', 'I''m struggling with insomnia.', '因为失眠很痛苦。'),
  ('ko-life-intermediate-145', 'ko', 'intermediate', 'life', '다이어트', '다이어트', 'daieoteu', 'diet, weight loss', '减肥，节食', '다이어트를 시작했어요.', 'I started a diet.', '开始减肥了。'),
  ('ko-life-intermediate-146', 'ko', 'intermediate', 'life', '운동', '운동', 'undong', 'exercise, sports', '运动，锻炼', '매일 운동하려고 노력해요.', 'I try to exercise every day.', '尽量每天锻炼。'),
  ('ko-life-intermediate-147', 'ko', 'intermediate', 'life', '요가', '요가', 'yoga', 'yoga', '瑜伽', '아침에 요가를 해요.', 'I do yoga in the morning.', '早上做瑜伽。'),
  ('ko-life-intermediate-148', 'ko', 'intermediate', 'life', '캠핑', '캠핑', 'kaemping', 'camping', '露营', '주말에 캠핑 가요.', 'I go camping on weekends.', '周末去露营。'),
  ('ko-life-intermediate-149', 'ko', 'intermediate', 'life', '등산', '등산', 'deungsan', 'hiking, mountain climbing', '爬山，登山', '주말마다 등산을 해요.', 'I go hiking every weekend.', '每个周末都去爬山。'),
  ('ko-life-intermediate-150', 'ko', 'intermediate', 'life', '자전거', '자전거', 'jajeongeo', 'bicycle, bike', '自行车', '자전거로 출근해요.', 'I commute by bicycle.', '骑自行车上班。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
