-- Expand ko-numbers-basic to 150 curated entries (16-150)
-- Topic: numbers, counting, quantities for basic Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-numbers-basic-16', 'ko', 'basic', 'numbers', '만', '만', 'man', 'ten thousand', '万', '만 원이에요.', 'It''s 10,000 won.', '一万韩元。'),
  ('ko-numbers-basic-17', 'ko', 'basic', 'numbers', '스물', '스물', 'seumul', 'twenty (native)', '二十', '스물 살이에요.', 'I''m twenty years old.', '我二十岁。'),
  ('ko-numbers-basic-18', 'ko', 'basic', 'numbers', '서른', '서른', 'seoreun', 'thirty (native)', '三十', '서른 살이에요.', 'I''m thirty years old.', '我三十岁。'),
  ('ko-numbers-basic-19', 'ko', 'basic', 'numbers', '마흔', '마흔', 'maheun', 'forty (native)', '四十', '마흔 살이에요.', 'I''m forty years old.', '我四十岁。'),
  ('ko-numbers-basic-20', 'ko', 'basic', 'numbers', '쉰', '쉰', 'swin', 'fifty (native)', '五十', '쉰 살이에요.', 'I''m fifty years old.', '我五十岁。'),
  ('ko-numbers-basic-21', 'ko', 'basic', 'numbers', '이십', '이십', 'isip', 'twenty (sino)', '二十', '이십 분 걸려요.', 'It takes twenty minutes.', '需要二十分钟。'),
  ('ko-numbers-basic-22', 'ko', 'basic', 'numbers', '삼십', '삼십', 'samsip', 'thirty (sino)', '三十', '삼십 분이에요.', 'It''s thirty minutes.', '三十分钟。'),
  ('ko-numbers-basic-23', 'ko', 'basic', 'numbers', '사십', '사십', 'sasip', 'forty (sino)', '四十', '사십 분이에요.', 'It''s forty minutes.', '四十分钟。'),
  ('ko-numbers-basic-24', 'ko', 'basic', 'numbers', '오십', '오십', 'osip', 'fifty (sino)', '五十', '오십 퍼센트예요.', 'It''s fifty percent.', '百分之五十。'),
  ('ko-numbers-basic-25', 'ko', 'basic', 'numbers', '육십', '육십', 'yuksip', 'sixty (sino)', '六十', '육십 분은 한 시간이에요.', 'Sixty minutes is one hour.', '六十分钟是一个小时。'),
  ('ko-numbers-basic-26', 'ko', 'basic', 'numbers', '칠십', '칠십', 'chilsip', 'seventy (sino)', '七十', '칠십 점이에요.', 'It''s seventy points.', '七十分。'),
  ('ko-numbers-basic-27', 'ko', 'basic', 'numbers', '팔십', '팔십', 'palsip', 'eighty (sino)', '八十', '팔십 퍼센트예요.', 'It''s eighty percent.', '百分之八十。'),
  ('ko-numbers-basic-28', 'ko', 'basic', 'numbers', '구십', '구십', 'gusip', 'ninety (sino)', '九十', '구십 점이에요.', 'It''s ninety points.', '九十分。'),
  ('ko-numbers-basic-29', 'ko', 'basic', 'numbers', '일', '일', 'il', 'one (sino)', '一', '일 번이에요.', 'It''s number one.', '是一号。'),
  ('ko-numbers-basic-30', 'ko', 'basic', 'numbers', '이', '이', 'i', 'two (sino)', '二', '이 층이에요.', 'It''s the second floor.', '是二楼。'),
  ('ko-numbers-basic-31', 'ko', 'basic', 'numbers', '삼', '삼', 'sam', 'three (sino)', '三', '삼 번이에요.', 'It''s number three.', '是三号。'),
  ('ko-numbers-basic-32', 'ko', 'basic', 'numbers', '사', '사', 'sa', 'four (sino)', '四', '사 월이에요.', 'It''s April.', '是四月。'),
  ('ko-numbers-basic-33', 'ko', 'basic', 'numbers', '오', '오', 'o', 'five (sino)', '五', '오 분 걸려요.', 'It takes five minutes.', '需要五分钟。'),
  ('ko-numbers-basic-34', 'ko', 'basic', 'numbers', '육', '육', 'yuk', 'six (sino)', '六', '육 월이에요.', 'It''s June.', '是六月。'),
  ('ko-numbers-basic-35', 'ko', 'basic', 'numbers', '칠', '칠', 'chil', 'seven (sino)', '七', '칠 월이에요.', 'It''s July.', '是七月。'),
  ('ko-numbers-basic-36', 'ko', 'basic', 'numbers', '팔', '팔', 'pal', 'eight (sino)', '八', '팔 시에 일어나요.', 'I wake up at eight.', '我八点起床。'),
  ('ko-numbers-basic-37', 'ko', 'basic', 'numbers', '구', '구', 'gu', 'nine (sino)', '九', '구 시에 자요.', 'I sleep at nine.', '我九点睡。'),
  ('ko-numbers-basic-38', 'ko', 'basic', 'numbers', '십', '십', 'sip', 'ten (sino)', '十', '십 분이에요.', 'It''s ten minutes.', '十分钟。'),
  ('ko-numbers-basic-39', 'ko', 'basic', 'numbers', '한 개', '한 개', 'han gae', 'one (counter)', '一个', '한 개 주세요.', 'Please give me one.', '请给我一个。'),
  ('ko-numbers-basic-40', 'ko', 'basic', 'numbers', '두 개', '두 개', 'du gae', 'two (counter)', '两个', '두 개 주세요.', 'Please give me two.', '请给我两个。'),
  ('ko-numbers-basic-41', 'ko', 'basic', 'numbers', '세 개', '세 개', 'se gae', 'three (counter)', '三个', '세 개 있어요.', 'There are three.', '有三个。'),
  ('ko-numbers-basic-42', 'ko', 'basic', 'numbers', '네 개', '네 개', 'ne gae', 'four (counter)', '四个', '네 개 살게요.', 'I''ll buy four.', '我买四个。'),
  ('ko-numbers-basic-43', 'ko', 'basic', 'numbers', '다섯 개', '다섯 개', 'daseot gae', 'five (counter)', '五个', '다섯 개 있어요.', 'There are five.', '有五个。'),
  ('ko-numbers-basic-44', 'ko', 'basic', 'numbers', '한 명', '한 명', 'han myeong', 'one person', '一个人', '한 명이에요.', 'It''s one person.', '一个人。'),
  ('ko-numbers-basic-45', 'ko', 'basic', 'numbers', '두 명', '두 명', 'du myeong', 'two people', '两个人', '두 명이에요.', 'It''s two people.', '两个人。'),
  ('ko-numbers-basic-46', 'ko', 'basic', 'numbers', '세 명', '세 명', 'se myeong', 'three people', '三个人', '세 명이 왔어요.', 'Three people came.', '来了三个人。'),
  ('ko-numbers-basic-47', 'ko', 'basic', 'numbers', '한 잔', '한 잔', 'han jan', 'one cup/glass', '一杯', '커피 한 잔 주세요.', 'One cup of coffee please.', '请给我一杯咖啡。'),
  ('ko-numbers-basic-48', 'ko', 'basic', 'numbers', '한 병', '한 병', 'han byeong', 'one bottle', '一瓶', '물 한 병 주세요.', 'One bottle of water please.', '请给我一瓶水。'),
  ('ko-numbers-basic-49', 'ko', 'basic', 'numbers', '한 그릇', '한 그릇', 'han geureut', 'one bowl', '一碗', '밥 한 그릇 주세요.', 'One bowl of rice please.', '请给我一碗饭。'),
  ('ko-numbers-basic-50', 'ko', 'basic', 'numbers', '한 장', '한 장', 'han jang', 'one sheet/ticket', '一张', '표 한 장 주세요.', 'One ticket please.', '请给我一张票。'),
  ('ko-numbers-basic-51', 'ko', 'basic', 'numbers', '한 권', '한 권', 'han gwon', 'one book/volume', '一本', '책 한 권 샀어요.', 'I bought one book.', '我买了一本书。'),
  ('ko-numbers-basic-52', 'ko', 'basic', 'numbers', '한 마리', '한 마리', 'han mari', 'one animal', '一只', '강아지 한 마리 있어요.', 'I have one dog.', '我有一只狗。'),
  ('ko-numbers-basic-53', 'ko', 'basic', 'numbers', '한 대', '한 대', 'han dae', 'one machine/vehicle', '一辆/一台', '차 한 대 있어요.', 'I have one car.', '我有一辆车。'),
  ('ko-numbers-basic-54', 'ko', 'basic', 'numbers', '한 벌', '한 벌', 'han beol', 'one set of clothes', '一套', '옷 한 벌 샀어요.', 'I bought one set of clothes.', '我买了一套衣服。'),
  ('ko-numbers-basic-55', 'ko', 'basic', 'numbers', '한 켤레', '한 켤레', 'han kyeolle', 'one pair (shoes)', '一双', '신발 한 켤레 샀어요.', 'I bought a pair of shoes.', '我买了一双鞋。'),
  ('ko-numbers-basic-56', 'ko', 'basic', 'numbers', '한 시', '한 시', 'han si', 'one o''clock', '一点', '한 시에 만나요.', 'Let''s meet at one.', '一点见。'),
  ('ko-numbers-basic-57', 'ko', 'basic', 'numbers', '두 시', '두 시', 'du si', 'two o''clock', '两点', '두 시에 끝나요.', 'It ends at two.', '两点结束。'),
  ('ko-numbers-basic-58', 'ko', 'basic', 'numbers', '세 시', '세 시', 'se si', 'three o''clock', '三点', '세 시에 시작해요.', 'It starts at three.', '三点开始。'),
  ('ko-numbers-basic-59', 'ko', 'basic', 'numbers', '열두 시', '열두 시', 'yeoldu si', 'twelve o''clock', '十二点', '열두 시에 점심 먹어요.', 'I eat lunch at twelve.', '十二点吃午饭。'),
  ('ko-numbers-basic-60', 'ko', 'basic', 'numbers', '시간', '시간', 'sigan', 'hour, time', '小时，时间', '한 시간 걸려요.', 'It takes one hour.', '需要一个小时。'),
  ('ko-numbers-basic-61', 'ko', 'basic', 'numbers', '분', '분', 'bun', 'minute', '分钟', '십 분 기다려요.', 'I wait ten minutes.', '我等十分钟。'),
  ('ko-numbers-basic-62', 'ko', 'basic', 'numbers', '초', '초', 'cho', 'second', '秒', '삼십 초 기다려요.', 'I wait thirty seconds.', '我等三十秒。'),
  ('ko-numbers-basic-63', 'ko', 'basic', 'numbers', '일월', '일월', 'irwol', 'January', '一月', '일월은 추워요.', 'January is cold.', '一月很冷。'),
  ('ko-numbers-basic-64', 'ko', 'basic', 'numbers', '이월', '이월', 'iwol', 'February', '二月', '이월에 눈이 와요.', 'It snows in February.', '二月下雪。'),
  ('ko-numbers-basic-65', 'ko', 'basic', 'numbers', '삼월', '삼월', 'samwol', 'March', '三月', '삼월에 봄이 와요.', 'Spring comes in March.', '三月春天来了。'),
  ('ko-numbers-basic-66', 'ko', 'basic', 'numbers', '사월', '사월', 'sawol', 'April', '四月', '사월에 꽃이 피어요.', 'Flowers bloom in April.', '四月花开了。'),
  ('ko-numbers-basic-67', 'ko', 'basic', 'numbers', '오월', '오월', 'owol', 'May', '五月', '오월에 여행가요.', 'I travel in May.', '五月去旅行。'),
  ('ko-numbers-basic-68', 'ko', 'basic', 'numbers', '유월', '유월', 'yuwol', 'June', '六月', '유월에 비가 와요.', 'It rains in June.', '六月下雨。'),
  ('ko-numbers-basic-69', 'ko', 'basic', 'numbers', '칠월', '칠월', 'chirwol', 'July', '七月', '칠월은 더워요.', 'July is hot.', '七月很热。'),
  ('ko-numbers-basic-70', 'ko', 'basic', 'numbers', '팔월', '팔월', 'parwol', 'August', '八月', '팔월에 방학이에요.', 'It''s vacation in August.', '八月放假。'),
  ('ko-numbers-basic-71', 'ko', 'basic', 'numbers', '구월', '구월', 'guwol', 'September', '九月', '구월에 학교 시작해요.', 'School starts in September.', '九月开学。'),
  ('ko-numbers-basic-72', 'ko', 'basic', 'numbers', '시월', '시월', 'siwol', 'October', '十月', '시월에 단풍이 예뻐요.', 'The fall leaves are pretty in October.', '十月红叶很美。'),
  ('ko-numbers-basic-73', 'ko', 'basic', 'numbers', '십일월', '십일월', 'sibirwol', 'November', '十一月', '십일월에 추워져요.', 'It gets cold in November.', '十一月变冷了。'),
  ('ko-numbers-basic-74', 'ko', 'basic', 'numbers', '십이월', '십이월', 'sibiwol', 'December', '十二月', '십이월에 크리스마스예요.', 'Christmas is in December.', '十二月是圣诞节。'),
  ('ko-numbers-basic-75', 'ko', 'basic', 'numbers', '첫 번째', '첫 번째', 'cheot beonjjae', 'first', '第一', '첫 번째예요.', 'It''s the first.', '是第一个。'),
  ('ko-numbers-basic-76', 'ko', 'basic', 'numbers', '두 번째', '두 번째', 'du beonjjae', 'second', '第二', '두 번째예요.', 'It''s the second.', '是第二个。'),
  ('ko-numbers-basic-77', 'ko', 'basic', 'numbers', '세 번째', '세 번째', 'se beonjjae', 'third', '第三', '세 번째예요.', 'It''s the third.', '是第三个。'),
  ('ko-numbers-basic-78', 'ko', 'basic', 'numbers', '마지막', '마지막', 'majimak', 'last, final', '最后', '마지막이에요.', 'It''s the last one.', '是最后一个。'),
  ('ko-numbers-basic-79', 'ko', 'basic', 'numbers', '번호', '번호', 'beonho', 'number (ID)', '号码', '전화번호가 뭐예요?', 'What''s your phone number?', '你的电话号码是什么？'),
  ('ko-numbers-basic-80', 'ko', 'basic', 'numbers', '몇', '몇', 'myeot', 'how many', '几', '몇 개예요?', 'How many are there?', '几个？'),
  ('ko-numbers-basic-81', 'ko', 'basic', 'numbers', '얼마', '얼마', 'eolma', 'how much', '多少', '얼마예요?', 'How much is it?', '多少钱？'),
  ('ko-numbers-basic-82', 'ko', 'basic', 'numbers', '조금', '조금', 'jogeum', 'a little', '一点', '조금만 주세요.', 'Please give me just a little.', '请给我一点点。'),
  ('ko-numbers-basic-83', 'ko', 'basic', 'numbers', '전부', '전부', 'jeonbu', 'all, everything', '全部', '전부 주세요.', 'Please give me all of it.', '全部给我。'),
  ('ko-numbers-basic-84', 'ko', 'basic', 'numbers', '더', '더', 'deo', 'more', '更多', '더 주세요.', 'Please give me more.', '请再给我一些。'),
  ('ko-numbers-basic-85', 'ko', 'basic', 'numbers', '덜', '덜', 'deol', 'less', '少一些', '덜 넣어 주세요.', 'Please put in less.', '请少放一些。'),
  ('ko-numbers-basic-86', 'ko', 'basic', 'numbers', '충분히', '충분히', 'chungbunhi', 'enough', '足够', '충분해요.', 'It''s enough.', '足够了。'),
  ('ko-numbers-basic-87', 'ko', 'basic', 'numbers', '부족', '부족', 'bujok', 'not enough', '不足', '시간이 부족해요.', 'There isn''t enough time.', '时间不够。'),
  ('ko-numbers-basic-88', 'ko', 'basic', 'numbers', '배', '배', 'bae', 'times, fold', '倍', '두 배예요.', 'It''s double.', '是两倍。'),
  ('ko-numbers-basic-89', 'ko', 'basic', 'numbers', '퍼센트', '퍼센트', 'peosenteu', 'percent', '百分比', '오십 퍼센트예요.', 'It''s fifty percent.', '百分之五十。'),
  ('ko-numbers-basic-90', 'ko', 'basic', 'numbers', '원', '원', 'won', 'won (currency)', '韩元', '천 원이에요.', 'It''s 1,000 won.', '一千韩元。'),
  ('ko-numbers-basic-91', 'ko', 'basic', 'numbers', '달러', '달러', 'dalleo', 'dollar', '美元', '십 달러예요.', 'It''s ten dollars.', '十美元。'),
  ('ko-numbers-basic-92', 'ko', 'basic', 'numbers', '위안', '위안', 'wian', 'yuan', '人民币', '백 위안이에요.', 'It''s one hundred yuan.', '一百人民币。'),
  ('ko-numbers-basic-93', 'ko', 'basic', 'numbers', '가격', '가격', 'gagyeok', 'price', '价格', '가격이 비싸요.', 'The price is expensive.', '价格很贵。'),
  ('ko-numbers-basic-94', 'ko', 'basic', 'numbers', '싸다', '싸다', 'ssada', 'cheap', '便宜', '이건 싸요.', 'This is cheap.', '这个便宜。'),
  ('ko-numbers-basic-95', 'ko', 'basic', 'numbers', '비싸다', '비싸다', 'bissada', 'expensive', '贵', '너무 비싸요.', 'It''s too expensive.', '太贵了。'),
  ('ko-numbers-basic-96', 'ko', 'basic', 'numbers', '거스름돈', '거스름돈', 'geoseureumd on', 'change (money)', '找零', '거스름돈이에요.', 'Here is your change.', '这是找零。'),
  ('ko-numbers-basic-97', 'ko', 'basic', 'numbers', '동전', '동전', 'dongjeon', 'coin', '硬币', '동전이 있어요?', 'Do you have coins?', '有硬币吗？'),
  ('ko-numbers-basic-98', 'ko', 'basic', 'numbers', '지폐', '지폐', 'jipye', 'bill, banknote', '纸币', '만 원짜리 지폐예요.', 'It''s a 10,000 won bill.', '是一万韩元纸币。'),
  ('ko-numbers-basic-99', 'ko', 'basic', 'numbers', '무게', '무게', 'muge', 'weight', '重量', '무게가 얼마예요?', 'What''s the weight?', '重量多少？'),
  ('ko-numbers-basic-100', 'ko', 'basic', 'numbers', '킬로그램', '킬로그램', 'killogeulaem', 'kilogram', '公斤', '일 킬로그램이에요.', 'It''s one kilogram.', '一公斤。'),
  ('ko-numbers-basic-101', 'ko', 'basic', 'numbers', '미터', '미터', 'miteo', 'meter', '米', '백 미터예요.', 'It''s one hundred meters.', '一百米。'),
  ('ko-numbers-basic-102', 'ko', 'basic', 'numbers', '센티미터', '센티미터', 'sentimiteo', 'centimeter', '厘米', '키가 백칠십 센티미터예요.', 'I''m 170 cm tall.', '我身高170厘米。'),
  ('ko-numbers-basic-103', 'ko', 'basic', 'numbers', '킬로미터', '킬로미터', 'killomiteo', 'kilometer', '公里', '십 킬로미터 달렸어요.', 'I ran ten kilometers.', '我跑了十公里。'),
  ('ko-numbers-basic-104', 'ko', 'basic', 'numbers', '리터', '리터', 'riteo', 'liter', '升', '물 이 리터 마셨어요.', 'I drank two liters of water.', '我喝了两升水。'),
  ('ko-numbers-basic-105', 'ko', 'basic', 'numbers', '도', '도', 'do', 'degree', '度', '오늘 삼십 도예요.', 'It''s 30 degrees today.', '今天三十度。'),
  ('ko-numbers-basic-106', 'ko', 'basic', 'numbers', '층', '층', 'cheung', 'floor, story', '层', '삼 층이에요.', 'It''s the third floor.', '三楼。'),
  ('ko-numbers-basic-107', 'ko', 'basic', 'numbers', '호', '호', 'ho', 'number (room/unit)', '号', '삼백일 호예요.', 'It''s room 301.', '301号。'),
  ('ko-numbers-basic-108', 'ko', 'basic', 'numbers', '번', '번', 'beon', 'number, time (counter)', '号，次', '세 번 했어요.', 'I did it three times.', '我做了三次。'),
  ('ko-numbers-basic-109', 'ko', 'basic', 'numbers', '살', '살', 'sal', 'years old', '岁', '몇 살이에요?', 'How old are you?', '你几岁？'),
  ('ko-numbers-basic-110', 'ko', 'basic', 'numbers', '년', '년', 'nyeon', 'year', '年', '이천이십육 년이에요.', 'It''s the year 2026.', '是2026年。'),
  ('ko-numbers-basic-111', 'ko', 'basic', 'numbers', '월', '월', 'wol', 'month', '月', '몇 월이에요?', 'What month is it?', '几月？'),
  ('ko-numbers-basic-112', 'ko', 'basic', 'numbers', '일', '일', 'il', 'day (date)', '号，日', '오늘 며칠이에요?', 'What date is today?', '今天几号？'),
  ('ko-numbers-basic-113', 'ko', 'basic', 'numbers', '주', '주', 'ju', 'week', '周', '한 주 동안이에요.', 'It''s for one week.', '一周的时间。'),
  ('ko-numbers-basic-114', 'ko', 'basic', 'numbers', '달', '달', 'dal', 'month (duration)', '个月', '세 달 걸려요.', 'It takes three months.', '需要三个月。'),
  ('ko-numbers-basic-115', 'ko', 'basic', 'numbers', '매일', '매일', 'maeil', 'every day', '每天', '매일 공부해요.', 'I study every day.', '我每天学习。'),
  ('ko-numbers-basic-116', 'ko', 'basic', 'numbers', '매주', '매주', 'maeju', 'every week', '每周', '매주 운동해요.', 'I exercise every week.', '我每周运动。'),
  ('ko-numbers-basic-117', 'ko', 'basic', 'numbers', '매달', '매달', 'maedal', 'every month', '每月', '매달 월세를 내요.', 'I pay rent every month.', '我每月交房租。'),
  ('ko-numbers-basic-118', 'ko', 'basic', 'numbers', '매년', '매년', 'maenyeon', 'every year', '每年', '매년 여행 가요.', 'I travel every year.', '我每年旅行。'),
  ('ko-numbers-basic-119', 'ko', 'basic', 'numbers', '처음', '처음', 'cheoeum', 'first time', '第一次', '처음이에요.', 'It''s my first time.', '这是第一次。'),
  ('ko-numbers-basic-120', 'ko', 'basic', 'numbers', '다시', '다시', 'dasi', 'again', '再', '다시 해 봐요.', 'Let''s try again.', '再试一次。'),
  ('ko-numbers-basic-121', 'ko', 'basic', 'numbers', '한 번', '한 번', 'han beon', 'once', '一次', '한 번 더 해요.', 'Let''s do it one more time.', '再来一次。'),
  ('ko-numbers-basic-122', 'ko', 'basic', 'numbers', '두 번', '두 번', 'du beon', 'twice', '两次', '두 번 갔어요.', 'I went twice.', '我去了两次。'),
  ('ko-numbers-basic-123', 'ko', 'basic', 'numbers', '여러 번', '여러 번', 'yeoreo beon', 'many times', '好几次', '여러 번 했어요.', 'I did it many times.', '我做了好几次。'),
  ('ko-numbers-basic-124', 'ko', 'basic', 'numbers', '크다', '크다', 'keuda', 'big, large', '大', '이건 커요.', 'This is big.', '这个大。'),
  ('ko-numbers-basic-125', 'ko', 'basic', 'numbers', '작다', '작다', 'jakda', 'small', '小', '이건 작아요.', 'This is small.', '这个小。'),
  ('ko-numbers-basic-126', 'ko', 'basic', 'numbers', '길다', '길다', 'gilda', 'long', '长', '이건 길어요.', 'This is long.', '这个长。'),
  ('ko-numbers-basic-127', 'ko', 'basic', 'numbers', '짧다', '짧다', 'jjalda', 'short', '短', '이건 짧아요.', 'This is short.', '这个短。'),
  ('ko-numbers-basic-128', 'ko', 'basic', 'numbers', '높다', '높다', 'nopda', 'high, tall', '高', '산이 높아요.', 'The mountain is high.', '山很高。'),
  ('ko-numbers-basic-129', 'ko', 'basic', 'numbers', '낮다', '낮다', 'natda', 'low', '低', '가격이 낮아요.', 'The price is low.', '价格低。'),
  ('ko-numbers-basic-130', 'ko', 'basic', 'numbers', '넓다', '넓다', 'neolda', 'wide, spacious', '宽', '방이 넓어요.', 'The room is spacious.', '房间很宽敞。'),
  ('ko-numbers-basic-131', 'ko', 'basic', 'numbers', '좁다', '좁다', 'jopda', 'narrow', '窄', '길이 좁아요.', 'The road is narrow.', '路很窄。'),
  ('ko-numbers-basic-132', 'ko', 'basic', 'numbers', '무겁다', '무겁다', 'mugeopda', 'heavy', '重', '짐이 무거워요.', 'The luggage is heavy.', '行李很重。'),
  ('ko-numbers-basic-133', 'ko', 'basic', 'numbers', '가볍다', '가볍다', 'gabyeopda', 'light (weight)', '轻', '이건 가벼워요.', 'This is light.', '这个轻。'),
  ('ko-numbers-basic-134', 'ko', 'basic', 'numbers', '두껍다', '두껍다', 'dukeopda', 'thick', '厚', '책이 두꺼워요.', 'The book is thick.', '书很厚。'),
  ('ko-numbers-basic-135', 'ko', 'basic', 'numbers', '얇다', '얇다', 'yalda', 'thin', '薄', '종이가 얇아요.', 'The paper is thin.', '纸很薄。'),
  ('ko-numbers-basic-136', 'ko', 'basic', 'numbers', '깊다', '깊다', 'gipda', 'deep', '深', '물이 깊어요.', 'The water is deep.', '水很深。'),
  ('ko-numbers-basic-137', 'ko', 'basic', 'numbers', '얕다', '얕다', 'yatda', 'shallow', '浅', '여기는 얕아요.', 'It''s shallow here.', '这里很浅。'),
  ('ko-numbers-basic-138', 'ko', 'basic', 'numbers', '빠르다', '빠르다', 'ppareuda', 'fast', '快', '정말 빨라요.', 'It''s really fast.', '真快。'),
  ('ko-numbers-basic-139', 'ko', 'basic', 'numbers', '느리다', '느리다', 'neurida', 'slow', '慢', '좀 느려요.', 'It''s a bit slow.', '有点慢。'),
  ('ko-numbers-basic-140', 'ko', 'basic', 'numbers', '가장', '가장', 'gajang', 'most', '最', '가장 좋아요.', 'I like it the most.', '最喜欢。'),
  ('ko-numbers-basic-141', 'ko', 'basic', 'numbers', '제일', '제일', 'jeil', 'number one, best', '第一，最', '제일 맛있어요.', 'It''s the most delicious.', '最好吃。'),
  ('ko-numbers-basic-142', 'ko', 'basic', 'numbers', '약', '약', 'yak', 'about, approximately', '大约', '약 십 분 걸려요.', 'It takes about ten minutes.', '大约需要十分钟。'),
  ('ko-numbers-basic-143', 'ko', 'basic', 'numbers', '정도', '정도', 'jeongdo', 'about, degree', '左右，程度', '한 시간 정도예요.', 'It''s about one hour.', '一个小时左右。'),
  ('ko-numbers-basic-144', 'ko', 'basic', 'numbers', '이상', '이상', 'isang', 'more than', '以上', '백 명 이상이에요.', 'It''s more than 100 people.', '一百人以上。'),
  ('ko-numbers-basic-145', 'ko', 'basic', 'numbers', '이하', '이하', 'iha', 'less than', '以下', '십 도 이하예요.', 'It''s below 10 degrees.', '十度以下。'),
  ('ko-numbers-basic-146', 'ko', 'basic', 'numbers', '이내', '이내', 'inae', 'within', '以内', '삼 일 이내에 해요.', 'I''ll do it within three days.', '三天以内做。'),
  ('ko-numbers-basic-147', 'ko', 'basic', 'numbers', '합계', '합계', 'hapgye', 'total', '合计', '합계가 얼마예요?', 'What''s the total?', '合计多少？'),
  ('ko-numbers-basic-148', 'ko', 'basic', 'numbers', '평균', '평균', 'pyeonggyun', 'average', '平均', '평균이 팔십이에요.', 'The average is eighty.', '平均是八十。'),
  ('ko-numbers-basic-149', 'ko', 'basic', 'numbers', '최대', '최대', 'choedae', 'maximum', '最大', '최대 열 명이에요.', 'Maximum is ten people.', '最多十个人。'),
  ('ko-numbers-basic-150', 'ko', 'basic', 'numbers', '최소', '최소', 'choeso', 'minimum', '最小', '최소 두 명이에요.', 'Minimum is two people.', '至少两个人。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
