-- Expand ja-life-intermediate to 150 curated entries (9-150)
-- Topic: daily life vocabulary for intermediate Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-life-intermediate-9', 'ja', 'intermediate', 'life', '家賃', 'やちん', 'yachin', 'rent, monthly rent', '房租，月租', '家賃は毎月八万円です。', 'The rent is 80,000 yen per month.', '房租每月八万日元。'),
  ('ja-life-intermediate-10', 'ja', 'intermediate', 'life', '間取り', 'まどり', 'madori', 'floor plan, room layout', '户型，房屋格局', 'この部屋の間取りは2LDKです。', 'This apartment''s layout is 2LDK.', '这套房子的户型是两室一厅。'),
  ('ja-life-intermediate-11', 'ja', 'intermediate', 'life', '引っ越し', 'ひっこし', 'hikkoshi', 'moving, relocation', '搬家，搬迁', '来月引っ越しをします。', 'I''m moving next month.', '下个月搬家。'),
  ('ja-life-intermediate-12', 'ja', 'intermediate', 'life', '不動産', 'ふどうさん', 'fudousan', 'real estate, property', '房地产，不动产', '不動産屋で部屋を探しました。', 'I looked for a room at a real estate agency.', '在房产中介找了房子。'),
  ('ja-life-intermediate-13', 'ja', 'intermediate', 'life', '敷金', 'しききん', 'shikikin', 'security deposit', '押金，保证金', '敷金は家賃二ヶ月分です。', 'The security deposit is two months'' rent.', '押金是两个月房租。'),
  ('ja-life-intermediate-14', 'ja', 'intermediate', 'life', '礼金', 'れいきん', 'reikin', 'key money, gratitude payment', '礼金', '礼金なしの物件を探しています。', 'I''m looking for a property with no key money.', '在找不要礼金的房子。'),
  ('ja-life-intermediate-15', 'ja', 'intermediate', 'life', '更新', 'こうしん', 'koushin', 'renewal, update', '续约，更新', '賃貸契約を更新しました。', 'I renewed the rental contract.', '续签了租房合同。'),
  ('ja-life-intermediate-16', 'ja', 'intermediate', 'life', '病院', 'びょういん', 'byouin', 'hospital, clinic', '医院，诊所', '風邪で病院に行きました。', 'I went to the hospital because of a cold.', '感冒了去了医院。'),
  ('ja-life-intermediate-17', 'ja', 'intermediate', 'life', '処方箋', 'しょほうせん', 'shohousen', 'prescription', '处方，药方', '医者に処方箋をもらいました。', 'I got a prescription from the doctor.', '医生开了处方。'),
  ('ja-life-intermediate-18', 'ja', 'intermediate', 'life', '症状', 'しょうじょう', 'shoujou', 'symptoms, condition', '症状，病情', '症状を説明してください。', 'Please describe your symptoms.', '请说明症状。'),
  ('ja-life-intermediate-19', 'ja', 'intermediate', 'life', '診察', 'しんさつ', 'shinsatsu', 'medical examination, consultation', '看诊，诊察', '午前中に診察を受けました。', 'I had a consultation in the morning.', '上午看了诊。'),
  ('ja-life-intermediate-20', 'ja', 'intermediate', 'life', '健康診断', 'けんこうしんだん', 'kenkou shindan', 'health checkup, physical', '体检，健康检查', '毎年健康診断を受けます。', 'I get a health checkup every year.', '每年做体检。'),
  ('ja-life-intermediate-21', 'ja', 'intermediate', 'life', '保険証', 'ほけんしょう', 'hokenshou', 'insurance card, health card', '保险证，医保卡', '保険証を忘れないでください。', 'Please don''t forget your insurance card.', '请别忘了带保险证。'),
  ('ja-life-intermediate-22', 'ja', 'intermediate', 'life', '薬局', 'やっきょく', 'yakkyoku', 'pharmacy, drugstore', '药店，药局', '薬局で薬をもらいます。', 'I pick up medicine at the pharmacy.', '在药店取药。'),
  ('ja-life-intermediate-23', 'ja', 'intermediate', 'life', 'レジ', 'れじ', 'reji', 'cash register, checkout', '收银台，结账处', 'レジで支払いをします。', 'I pay at the register.', '在收银台付款。'),
  ('ja-life-intermediate-24', 'ja', 'intermediate', 'life', '割引', 'わりびき', 'waribiki', 'discount, reduction', '折扣，打折', '三十パーセント割引でした。', 'It was 30 percent off.', '打了七折。'),
  ('ja-life-intermediate-25', 'ja', 'intermediate', 'life', 'セール', 'せーる', 'seeru', 'sale, clearance', '特卖，大促', '夏のセールで服を買いました。', 'I bought clothes during the summer sale.', '在夏季特卖买了衣服。'),
  ('ja-life-intermediate-26', 'ja', 'intermediate', 'life', '返品', 'へんぴん', 'henpin', 'return, returning goods', '退货，退回', '不良品を返品しました。', 'I returned the defective item.', '退了不良品。'),
  ('ja-life-intermediate-27', 'ja', 'intermediate', 'life', '口座', 'こうざ', 'kouza', 'bank account', '账户，银行账号', '銀行口座を開設しました。', 'I opened a bank account.', '开了银行账户。'),
  ('ja-life-intermediate-28', 'ja', 'intermediate', 'life', '振り込み', 'ふりこみ', 'furikomi', 'bank transfer, wire transfer', '汇款，转账', '家賃を振り込みました。', 'I transferred the rent.', '汇了房租。'),
  ('ja-life-intermediate-29', 'ja', 'intermediate', 'life', '引き落とし', 'ひきおとし', 'hikiotoshi', 'automatic debit, direct debit', '自动扣款，代扣', '光熱費は自動引き落としです。', 'Utility bills are automatically debited.', '水电费是自动扣款。'),
  ('ja-life-intermediate-30', 'ja', 'intermediate', 'life', 'ATM', 'エーティーエム', 'eetiiemu', 'ATM, cash machine', 'ATM，自动取款机', 'ATMでお金を下ろしました。', 'I withdrew money from the ATM.', '在ATM取了钱。'),
  ('ja-life-intermediate-31', 'ja', 'intermediate', 'life', '小包', 'こづつみ', 'kodutsumi', 'parcel, small package', '包裹，小包', '小包を郵便局に出しました。', 'I sent a parcel at the post office.', '在邮局寄了包裹。'),
  ('ja-life-intermediate-32', 'ja', 'intermediate', 'life', '書留', 'かきとめ', 'kakitome', 'registered mail', '挂号信', '重要な書類は書留で送ります。', 'I send important documents by registered mail.', '重要文件用挂号信寄。'),
  ('ja-life-intermediate-33', 'ja', 'intermediate', 'life', '郵便番号', 'ゆうびんばんごう', 'yuubin bangou', 'postal code, zip code', '邮编，邮政编码', '郵便番号を記入してください。', 'Please fill in the postal code.', '请填写邮编。'),
  ('ja-life-intermediate-34', 'ja', 'intermediate', 'life', '宅配便', 'たくはいびん', 'takuhaibin', 'home delivery, courier service', '快递，宅配', '宅配便で荷物が届きました。', 'A package arrived by delivery.', '快递送来了包裹。'),
  ('ja-life-intermediate-35', 'ja', 'intermediate', 'life', '住民票', 'じゅうみんひょう', 'juuminhyou', 'resident certificate, resident record', '居住证明，住民票', '住民票を取りに行きます。', 'I''m going to get my resident certificate.', '去办居住证明。'),
  ('ja-life-intermediate-36', 'ja', 'intermediate', 'life', '届出', 'とどけで', 'todokede', 'notification, registration, filing', '申报，手续', '転入届を出しました。', 'I filed a moving-in notification.', '办了迁入手续。'),
  ('ja-life-intermediate-37', 'ja', 'intermediate', 'life', '免許証', 'めんきょしょう', 'menkyoshou', 'driver''s license, license', '驾照，执照', '免許証の更新をしなければなりません。', 'I need to renew my driver''s license.', '必须更新驾照。'),
  ('ja-life-intermediate-38', 'ja', 'intermediate', 'life', '印鑑', 'いんかん', 'inkan', 'personal seal, stamp', '印章，图章', '契約に印鑑が必要です。', 'A personal seal is needed for the contract.', '签合同需要印章。'),
  ('ja-life-intermediate-39', 'ja', 'intermediate', 'life', '電気代', 'でんきだい', 'denkidai', 'electricity bill, power cost', '电费', '夏は電気代が高くなります。', 'Electricity bills go up in summer.', '夏天电费变高。'),
  ('ja-life-intermediate-40', 'ja', 'intermediate', 'life', 'ガス代', 'がすだい', 'gasudai', 'gas bill, gas cost', '煤气费，燃气费', 'ガス代を節約したいです。', 'I want to save on gas bills.', '想省煤气费。'),
  ('ja-life-intermediate-41', 'ja', 'intermediate', 'life', '水道代', 'すいどうだい', 'suidoudai', 'water bill, water cost', '水费', '水道代は二ヶ月に一回払います。', 'The water bill is paid every two months.', '水费两个月交一次。'),
  ('ja-life-intermediate-42', 'ja', 'intermediate', 'life', '光熱費', 'こうねつひ', 'kounetsuhi', 'utility bills, heating and lighting', '水电煤费，光热费', '光熱費を節約しています。', 'I''m saving on utility bills.', '在节省水电煤费。'),
  ('ja-life-intermediate-43', 'ja', 'intermediate', 'life', 'ゴミ出し', 'ごみだし', 'gomidashi', 'taking out garbage, trash disposal', '倒垃圾，丢垃圾', '月曜日がゴミ出しの日です。', 'Monday is garbage day.', '周一是倒垃圾的日子。'),
  ('ja-life-intermediate-44', 'ja', 'intermediate', 'life', '分別', 'ぶんべつ', 'bunbetsu', 'sorting, waste separation', '垃圾分类，分别', 'ゴミの分別をきちんとしましょう。', 'Let''s properly sort our garbage.', '让我们认真做好垃圾分类。'),
  ('ja-life-intermediate-45', 'ja', 'intermediate', 'life', '粗大ゴミ', 'そだいごみ', 'sodai gomi', 'bulky waste, large garbage', '大件垃圾，粗大垃圾', '粗大ゴミは予約が必要です。', 'Bulky waste pickup requires a reservation.', '大件垃圾需要预约。'),
  ('ja-life-intermediate-46', 'ja', 'intermediate', 'life', '回覧板', 'かいらんばん', 'kairanban', 'neighborhood circular, notice board', '传阅板，通知', '回覧板を隣に回しました。', 'I passed the circular to the neighbor.', '把通知传给了邻居。'),
  ('ja-life-intermediate-47', 'ja', 'intermediate', 'life', '町内会', 'ちょうないかい', 'chounai kai', 'neighborhood association', '居委会，町内会', '町内会の会合に出席しました。', 'I attended the neighborhood association meeting.', '参加了居委会的会议。'),
  ('ja-life-intermediate-48', 'ja', 'intermediate', 'life', '梅雨', 'つゆ', 'tsuyu', 'rainy season, monsoon', '梅雨，雨季', '六月は梅雨の季節です。', 'June is the rainy season.', '六月是梅雨季。'),
  ('ja-life-intermediate-49', 'ja', 'intermediate', 'life', '台風', 'たいふう', 'taifuu', 'typhoon, hurricane', '台风', '台風が接近しています。', 'A typhoon is approaching.', '台风正在靠近。'),
  ('ja-life-intermediate-50', 'ja', 'intermediate', 'life', '紫外線', 'しがいせん', 'shigaisen', 'ultraviolet rays, UV', '紫外线', '紫外線対策をしています。', 'I take measures against UV rays.', '在做防紫外线措施。'),
  ('ja-life-intermediate-51', 'ja', 'intermediate', 'life', '趣味', 'しゅみ', 'shumi', 'hobby, interest', '爱好，兴趣', '趣味は読書と料理です。', 'My hobbies are reading and cooking.', '爱好是读书和做菜。'),
  ('ja-life-intermediate-52', 'ja', 'intermediate', 'life', '習い事', 'ならいごと', 'naraigoto', 'lessons, extracurricular class', '学习班，课外学习', '子供の習い事を探しています。', 'I''m looking for classes for my child.', '在找孩子的学习班。'),
  ('ja-life-intermediate-53', 'ja', 'intermediate', 'life', 'ジム', 'じむ', 'jimu', 'gym, fitness center', '健身房', '週三回ジムに通っています。', 'I go to the gym three times a week.', '每周去三次健身房。'),
  ('ja-life-intermediate-54', 'ja', 'intermediate', 'life', '通勤', 'つうきん', 'tsuukin', 'commuting, going to work', '通勤，上班路上', '通勤時間は一時間です。', 'My commute time is one hour.', '通勤时间一小时。'),
  ('ja-life-intermediate-55', 'ja', 'intermediate', 'life', '満員電車', 'まんいんでんしゃ', 'man''in densha', 'packed train, crowded train', '满员电车，拥挤的电车', '毎朝満員電車に乗ります。', 'I ride a packed train every morning.', '每天早上坐满员电车。'),
  ('ja-life-intermediate-56', 'ja', 'intermediate', 'life', '残業', 'ざんぎょう', 'zangyou', 'overtime, working late', '加班，超时工作', '今週は残業が多いです。', 'I have a lot of overtime this week.', '这周加班很多。'),
  ('ja-life-intermediate-57', 'ja', 'intermediate', 'life', '有給', 'ゆうきゅう', 'yuukyuu', 'paid leave, vacation day', '带薪休假，有薪假', '有給を使って旅行に行きます。', 'I''ll use paid leave to travel.', '用带薪假去旅行。'),
  ('ja-life-intermediate-58', 'ja', 'intermediate', 'life', '洗濯', 'せんたく', 'sentaku', 'laundry, washing clothes', '洗衣服，洗涤', '毎日洗濯をしています。', 'I do laundry every day.', '每天洗衣服。'),
  ('ja-life-intermediate-59', 'ja', 'intermediate', 'life', '掃除', 'そうじ', 'souji', 'cleaning, sweeping', '打扫，清洁', '週末に大掃除をします。', 'I do a big cleaning on weekends.', '周末大扫除。'),
  ('ja-life-intermediate-60', 'ja', 'intermediate', 'life', '換気', 'かんき', 'kanki', 'ventilation, airing out', '通风，换气', '部屋の換気をしましょう。', 'Let''s air out the room.', '让我们给房间通通风。'),
  ('ja-life-intermediate-61', 'ja', 'intermediate', 'life', '結露', 'けつろ', 'ketsuro', 'condensation, dew', '结露，水珠', '冬は窓に結露ができます。', 'Condensation forms on windows in winter.', '冬天窗户上会有结露。'),
  ('ja-life-intermediate-62', 'ja', 'intermediate', 'life', '防犯', 'ぼうはん', 'bouhan', 'crime prevention, security', '防盗，安全防范', '防犯カメラを設置しました。', 'I installed a security camera.', '安装了防盗摄像头。'),
  ('ja-life-intermediate-63', 'ja', 'intermediate', 'life', '隣人', 'りんじん', 'rinjin', 'neighbor, person next door', '邻居，隔壁', '隣人と仲良くしています。', 'I get along with my neighbors.', '和邻居关系好。'),
  ('ja-life-intermediate-64', 'ja', 'intermediate', 'life', '騒音', 'そうおん', 'souon', 'noise, loud sound', '噪音，嘈杂', '隣の騒音がうるさいです。', 'The noise from next door is loud.', '隔壁的噪音很吵。'),
  ('ja-life-intermediate-65', 'ja', 'intermediate', 'life', '管理費', 'かんりひ', 'kanrihi', 'management fee, maintenance fee', '管理费，物业费', '管理費は月五千円です。', 'The maintenance fee is 5,000 yen per month.', '管理费每月5000日元。'),
  ('ja-life-intermediate-66', 'ja', 'intermediate', 'life', '宅配ボックス', 'たくはいぼっくす', 'takuhai bokkusu', 'delivery locker, package box', '快递柜，收件箱', '宅配ボックスに荷物が届いています。', 'There''s a package in the delivery locker.', '快递柜里有包裹。'),
  ('ja-life-intermediate-67', 'ja', 'intermediate', 'life', 'クリーニング', 'くりーにんぐ', 'kuriiningu', 'dry cleaning, laundry service', '干洗，洗衣店', 'スーツをクリーニングに出しました。', 'I sent my suit to the dry cleaner.', '把西装送去干洗了。'),
  ('ja-life-intermediate-68', 'ja', 'intermediate', 'life', 'コインランドリー', 'こいんらんどりー', 'koin randorii', 'laundromat, coin laundry', '自助洗衣店，投币洗衣', 'コインランドリーで大物を洗います。', 'I wash large items at the laundromat.', '在自助洗衣店洗大件。'),
  ('ja-life-intermediate-69', 'ja', 'intermediate', 'life', '市役所', 'しやくしょ', 'shiyakusho', 'city hall, municipal office', '市政府，市政厅', '市役所で手続きをしました。', 'I completed procedures at city hall.', '在市政厅办了手续。'),
  ('ja-life-intermediate-70', 'ja', 'intermediate', 'life', '区役所', 'くやくしょ', 'kuyakusho', 'ward office, district office', '区政府，区役所', '区役所に届出を出しました。', 'I filed a notification at the ward office.', '在区政府提交了申报。'),
  ('ja-life-intermediate-71', 'ja', 'intermediate', 'life', 'マイナンバー', 'まいなんばー', 'mainanbaa', 'My Number, individual number card', '个人编号卡', 'マイナンバーカードを申請しました。', 'I applied for a My Number card.', '申请了个人编号卡。'),
  ('ja-life-intermediate-72', 'ja', 'intermediate', 'life', '年金', 'ねんきん', 'nenkin', 'pension, annuity', '养老金，年金', '年金保険料を納めています。', 'I pay pension premiums.', '在缴纳养老金。'),
  ('ja-life-intermediate-73', 'ja', 'intermediate', 'life', '確定申告', 'かくていしんこく', 'kakutei shinkoku', 'tax return, tax filing', '报税，确定申告', '確定申告の時期になりました。', 'It''s tax filing season.', '到了报税的时候了。'),
  ('ja-life-intermediate-74', 'ja', 'intermediate', 'life', '住民税', 'じゅうみんぜい', 'juuminzei', 'resident tax, local tax', '住民税，居民税', '住民税の通知が届きました。', 'I received the resident tax notice.', '收到了住民税通知。'),
  ('ja-life-intermediate-75', 'ja', 'intermediate', 'life', '固定資産税', 'こていしさんぜい', 'kotei shisanzei', 'property tax, fixed asset tax', '固定资产税，房产税', '固定資産税を払いました。', 'I paid the property tax.', '交了固定资产税。'),
  ('ja-life-intermediate-76', 'ja', 'intermediate', 'life', '節約', 'せつやく', 'setsuyaku', 'saving, economizing', '节约，省钱', '電気代を節約しています。', 'I''m saving on electricity.', '在节省电费。'),
  ('ja-life-intermediate-77', 'ja', 'intermediate', 'life', '貯金', 'ちょきん', 'chokin', 'savings, saving money', '存钱，储蓄', '毎月少しずつ貯金しています。', 'I save a little every month.', '每月存一点钱。'),
  ('ja-life-intermediate-78', 'ja', 'intermediate', 'life', 'ローン', 'ろーん', 'roon', 'loan, mortgage', '贷款，按揭', '住宅ローンを返済中です。', 'I''m repaying my mortgage.', '正在还房贷。'),
  ('ja-life-intermediate-79', 'ja', 'intermediate', 'life', 'クレジットカード', 'くれじっとかーど', 'kurejitto kaado', 'credit card', '信用卡', 'クレジットカードで支払います。', 'I pay by credit card.', '用信用卡付款。'),
  ('ja-life-intermediate-80', 'ja', 'intermediate', 'life', '防災', 'ぼうさい', 'bousai', 'disaster prevention, preparedness', '防灾，灾害预防', '防災グッズを準備しています。', 'I prepare disaster prevention supplies.', '在准备防灾用品。'),
  ('ja-life-intermediate-81', 'ja', 'intermediate', 'life', '避難', 'ひなん', 'hinan', 'evacuation, taking shelter', '避难，逃难', '地震の時は避難しましょう。', 'Let''s evacuate during an earthquake.', '地震时去避难吧。'),
  ('ja-life-intermediate-82', 'ja', 'intermediate', 'life', '非常食', 'ひじょうしょく', 'hijou shoku', 'emergency food, survival food', '应急食品', '非常食を三日分用意しています。', 'I have three days'' worth of emergency food ready.', '准备了三天份的应急食品。'),
  ('ja-life-intermediate-83', 'ja', 'intermediate', 'life', '地震', 'じしん', 'jishin', 'earthquake', '地震', '日本は地震が多い国です。', 'Japan is a country with many earthquakes.', '日本是地震多发国家。'),
  ('ja-life-intermediate-84', 'ja', 'intermediate', 'life', '花粉症', 'かふんしょう', 'kafunshou', 'hay fever, pollen allergy', '花粉症', '春は花粉症がつらいです。', 'Spring is tough because of hay fever.', '春天花粉症很难受。'),
  ('ja-life-intermediate-85', 'ja', 'intermediate', 'life', '熱中症', 'ねっちゅうしょう', 'necchuu shou', 'heatstroke, heat exhaustion', '中暑', '熱中症に気をつけてください。', 'Please be careful of heatstroke.', '请注意防中暑。'),
  ('ja-life-intermediate-86', 'ja', 'intermediate', 'life', 'インフルエンザ', 'いんふるえんざ', 'infuruenza', 'influenza, flu', '流感，流行性感冒', 'インフルエンザの予防接種を受けました。', 'I got a flu shot.', '打了流感疫苗。'),
  ('ja-life-intermediate-87', 'ja', 'intermediate', 'life', '歯医者', 'はいしゃ', 'haisha', 'dentist, dental clinic', '牙医，牙科', '歯医者の予約を取りました。', 'I made a dentist appointment.', '预约了牙医。'),
  ('ja-life-intermediate-88', 'ja', 'intermediate', 'life', '眼科', 'がんか', 'ganka', 'ophthalmology, eye doctor', '眼科', '目が痛いので眼科に行きます。', 'My eyes hurt so I''m going to the eye doctor.', '眼睛疼，去看眼科。'),
  ('ja-life-intermediate-89', 'ja', 'intermediate', 'life', '内科', 'ないか', 'naika', 'internal medicine, physician', '内科', '風邪の時は内科に行きます。', 'I go to internal medicine for a cold.', '感冒时去看内科。'),
  ('ja-life-intermediate-90', 'ja', 'intermediate', 'life', '外科', 'げか', 'geka', 'surgery, surgical department', '外科', '怪我をしたので外科で診てもらいました。', 'I got treated at surgery because I was injured.', '受了伤去外科看了。'),
  ('ja-life-intermediate-91', 'ja', 'intermediate', 'life', '保育園', 'ほいくえん', 'hoikuen', 'nursery school, daycare', '保育园，托儿所', '子供を保育園に預けています。', 'I put my child in daycare.', '把孩子送托儿所了。'),
  ('ja-life-intermediate-92', 'ja', 'intermediate', 'life', 'PTA', 'ぴーてぃーえー', 'piitiiee', 'PTA, parent-teacher association', '家长会，PTA', 'PTAの役員になりました。', 'I became a PTA officer.', '当了家长会干部。'),
  ('ja-life-intermediate-93', 'ja', 'intermediate', 'life', '冠婚葬祭', 'かんこんそうさい', 'kankonsousai', 'ceremonies, life events', '婚丧嫁娶，冠婚葬祭', '冠婚葬祭のマナーを覚えましょう。', 'Let''s learn the etiquette for life events.', '学一下婚丧嫁娶的礼节吧。'),
  ('ja-life-intermediate-94', 'ja', 'intermediate', 'life', 'ご祝儀', 'ごしゅうぎ', 'goshuugi', 'monetary gift, wedding gift', '份子钱，红包', '結婚式にご祝儀を持って行きます。', 'I bring a monetary gift to the wedding.', '带份子钱去参加婚礼。'),
  ('ja-life-intermediate-95', 'ja', 'intermediate', 'life', '香典', 'こうでん', 'kouden', 'condolence money, funeral offering', '奠仪，丧礼金', '香典を包みました。', 'I prepared condolence money.', '包了奠仪。'),
  ('ja-life-intermediate-96', 'ja', 'intermediate', 'life', '日用品', 'にちようひん', 'nichiyouhin', 'daily necessities, everyday items', '日用品，生活用品', '日用品を買いに行きます。', 'I''m going to buy daily necessities.', '去买日用品。'),
  ('ja-life-intermediate-97', 'ja', 'intermediate', 'life', '修理', 'しゅうり', 'shuuri', 'repair, fixing', '修理，维修', 'エアコンの修理を頼みました。', 'I requested an AC repair.', '请人修了空调。'),
  ('ja-life-intermediate-98', 'ja', 'intermediate', 'life', 'リフォーム', 'りふぉーむ', 'rifoomu', 'renovation, remodeling', '翻新，装修', 'キッチンをリフォームしました。', 'I renovated the kitchen.', '翻新了厨房。'),
  ('ja-life-intermediate-99', 'ja', 'intermediate', 'life', '契約', 'けいやく', 'keiyaku', 'contract, agreement', '合同，契约', 'インターネットの契約をしました。', 'I signed an internet contract.', '签了网络合同。'),
  ('ja-life-intermediate-100', 'ja', 'intermediate', 'life', '解約', 'かいやく', 'kaiyaku', 'cancellation, termination', '解约，取消', '携帯の契約を解約しました。', 'I cancelled my mobile contract.', '解约了手机合同。'),
  ('ja-life-intermediate-101', 'ja', 'intermediate', 'life', 'Wi-Fi', 'わいふぁい', 'waifai', 'Wi-Fi, wireless internet', 'WiFi，无线网', '自宅のWi-Fiが遅いです。', 'My home Wi-Fi is slow.', '家里的WiFi很慢。'),
  ('ja-life-intermediate-102', 'ja', 'intermediate', 'life', '生活費', 'せいかつひ', 'seikatsuhi', 'living expenses, cost of living', '生活费', '一ヶ月の生活費は十五万円です。', 'My monthly living expenses are 150,000 yen.', '每月生活费15万日元。'),
  ('ja-life-intermediate-103', 'ja', 'intermediate', 'life', '食費', 'しょくひ', 'shokuhi', 'food expenses, food budget', '伙食费，餐费', '食費を月三万円に抑えたいです。', 'I want to keep food expenses to 30,000 yen per month.', '想把伙食费控制在每月3万日元。'),
  ('ja-life-intermediate-104', 'ja', 'intermediate', 'life', '交通費', 'こうつうひ', 'koutsuuhi', 'transportation cost, commuting expense', '交通费', '交通費は会社が負担します。', 'The company covers transportation costs.', '交通费由公司承担。'),
  ('ja-life-intermediate-105', 'ja', 'intermediate', 'life', '家計簿', 'かけいぼ', 'kakeibo', 'household budget book, expense tracker', '家庭账本，记账本', '家計簿をつけています。', 'I keep a household budget book.', '在记家庭账本。'),
  ('ja-life-intermediate-106', 'ja', 'intermediate', 'life', 'ポイントカード', 'ぽいんとかーど', 'pointo kaado', 'loyalty card, point card', '积分卡，会员卡', 'ポイントカードはお持ちですか。', 'Do you have a point card?', '有积分卡吗？'),
  ('ja-life-intermediate-107', 'ja', 'intermediate', 'life', '電子マネー', 'でんしまねー', 'denshi manee', 'e-money, digital payment', '电子钱包，电子货币', '電子マネーで払えますか。', 'Can I pay with e-money?', '可以用电子钱包支付吗？'),
  ('ja-life-intermediate-108', 'ja', 'intermediate', 'life', 'ネットショッピング', 'ねっとしょっぴんぐ', 'netto shoppingu', 'online shopping', '网购，网上购物', 'ネットショッピングが便利です。', 'Online shopping is convenient.', '网购很方便。'),
  ('ja-life-intermediate-109', 'ja', 'intermediate', 'life', 'フリマアプリ', 'ふりまあぷり', 'furima apuri', 'flea market app, resale app', '二手交易APP，闲鱼', 'フリマアプリで不要品を売りました。', 'I sold unwanted items on a flea market app.', '在二手APP上卖了不要的东西。'),
  ('ja-life-intermediate-110', 'ja', 'intermediate', 'life', '定期健診', 'ていきけんしん', 'teiki kenshin', 'regular checkup, periodic exam', '定期检查，定检', '歯の定期健診に行きます。', 'I go for a regular dental checkup.', '去做牙齿定期检查。'),
  ('ja-life-intermediate-111', 'ja', 'intermediate', 'life', '生命保険', 'せいめいほけん', 'seimei hoken', 'life insurance', '人寿保险', '生命保険に加入しました。', 'I signed up for life insurance.', '买了人寿保险。'),
  ('ja-life-intermediate-112', 'ja', 'intermediate', 'life', '医療費', 'いりょうひ', 'iryouhi', 'medical expenses, healthcare costs', '医疗费，看病费', '医療費の領収書を保管しています。', 'I keep medical expense receipts.', '保存医疗费收据。'),
  ('ja-life-intermediate-113', 'ja', 'intermediate', 'life', 'ペット', 'ぺっと', 'petto', 'pet, companion animal', '宠物', 'ペット可のマンションを探しています。', 'I''m looking for a pet-friendly apartment.', '在找可以养宠物的公寓。'),
  ('ja-life-intermediate-114', 'ja', 'intermediate', 'life', '散歩', 'さんぽ', 'sanpo', 'walk, stroll', '散步', '毎朝犬と散歩します。', 'I walk the dog every morning.', '每天早上遛狗。'),
  ('ja-life-intermediate-115', 'ja', 'intermediate', 'life', '町内放送', 'ちょうないほうそう', 'chounai housou', 'community broadcast, local PA', '社区广播', '町内放送で防災情報を流しました。', 'Disaster info was broadcast on the community PA.', '通过社区广播发了防灾信息。'),
  ('ja-life-intermediate-116', 'ja', 'intermediate', 'life', '自治体', 'じちたい', 'jichitai', 'local government, municipality', '地方政府，自治体', '自治体のサービスを利用しています。', 'I use local government services.', '在使用自治体的服务。'),
  ('ja-life-intermediate-117', 'ja', 'intermediate', 'life', '住宅', 'じゅうたく', 'juutaku', 'housing, residence', '住宅，住房', '住宅の耐震性が重要です。', 'Earthquake resistance of housing is important.', '住宅的抗震性很重要。'),
  ('ja-life-intermediate-118', 'ja', 'intermediate', 'life', 'マンション', 'まんしょん', 'manshon', 'apartment building, condo', '公寓楼，住宅楼', '駅近のマンションに住んでいます。', 'I live in an apartment near the station.', '住在车站附近的公寓楼。'),
  ('ja-life-intermediate-119', 'ja', 'intermediate', 'life', 'アパート', 'あぱーと', 'apaato', 'apartment, flat', '公寓，出租房', 'アパートの壁が薄いです。', 'The apartment walls are thin.', '出租房的墙很薄。'),
  ('ja-life-intermediate-120', 'ja', 'intermediate', 'life', '一戸建て', 'いっこだて', 'ikkodate', 'detached house, single-family home', '独栋住宅，独门独院', 'いつか一戸建てに住みたいです。', 'I want to live in a detached house someday.', '总有一天想住独栋住宅。'),
  ('ja-life-intermediate-121', 'ja', 'intermediate', 'life', '近所', 'きんじょ', 'kinjo', 'neighborhood, vicinity', '附近，邻近', '近所にスーパーがあって便利です。', 'It''s convenient that there''s a supermarket nearby.', '附近有超市很方便。'),
  ('ja-life-intermediate-122', 'ja', 'intermediate', 'life', '治安', 'ちあん', 'chian', 'public safety, security', '治安，安全', 'この地域は治安が良いです。', 'This area has good public safety.', '这个地区治安好。'),
  ('ja-life-intermediate-123', 'ja', 'intermediate', 'life', '日当たり', 'ひあたり', 'hiatari', 'sun exposure, sunlight', '采光，日照', '日当たりの良い部屋が好きです。', 'I like rooms with good sunlight.', '我喜欢采光好的房间。'),
  ('ja-life-intermediate-124', 'ja', 'intermediate', 'life', 'ベランダ', 'べらんだ', 'beranda', 'balcony, veranda', '阳台', 'ベランダで洗濯物を干します。', 'I dry laundry on the balcony.', '在阳台晾衣服。'),
  ('ja-life-intermediate-125', 'ja', 'intermediate', 'life', '収納', 'しゅうのう', 'shuunou', 'storage, closet space', '收纳，储物空间', '収納スペースが足りません。', 'There''s not enough storage space.', '储物空间不够。'),
  ('ja-life-intermediate-126', 'ja', 'intermediate', 'life', '断捨離', 'だんしゃり', 'danshari', 'decluttering, minimalism', '断舍离', '断捨離をして部屋がすっきりしました。', 'I decluttered and the room is tidy now.', '断舍离之后房间清爽了。'),
  ('ja-life-intermediate-127', 'ja', 'intermediate', 'life', 'リサイクル', 'りさいくる', 'risaikuru', 'recycling, reuse', '回收，再利用', 'リサイクルショップで家具を買いました。', 'I bought furniture at a recycling shop.', '在二手店买了家具。'),
  ('ja-life-intermediate-128', 'ja', 'intermediate', 'life', '町並み', 'まちなみ', 'machinami', 'townscape, streetscape', '街景，市容', 'この町の町並みが好きです。', 'I like this town''s streetscape.', '我喜欢这个城市的街景。'),
  ('ja-life-intermediate-129', 'ja', 'intermediate', 'life', '公園', 'こうえん', 'kouen', 'park, public garden', '公园', '休日は公園でのんびりします。', 'I relax at the park on holidays.', '休息日在公园放松。'),
  ('ja-life-intermediate-130', 'ja', 'intermediate', 'life', '図書館', 'としょかん', 'toshokan', 'library', '图书馆', '図書館で本を借りました。', 'I borrowed books from the library.', '从图书馆借了书。'),
  ('ja-life-intermediate-131', 'ja', 'intermediate', 'life', 'コンビニ', 'こんびに', 'konbini', 'convenience store', '便利店', 'コンビニで支払いができます。', 'You can make payments at a convenience store.', '可以在便利店付款。'),
  ('ja-life-intermediate-132', 'ja', 'intermediate', 'life', 'ドラッグストア', 'どらっぐすとあ', 'doraggu sutoa', 'drugstore, pharmacy store', '药妆店', 'ドラッグストアで日用品を買います。', 'I buy daily necessities at the drugstore.', '在药妆店买日用品。'),
  ('ja-life-intermediate-133', 'ja', 'intermediate', 'life', 'ホームセンター', 'ほーむせんたー', 'hoomu sentaa', 'home center, hardware store', '家居建材店', 'ホームセンターでDIYの材料を買います。', 'I buy DIY materials at the home center.', '在家居店买DIY材料。'),
  ('ja-life-intermediate-134', 'ja', 'intermediate', 'life', '銀行窓口', 'ぎんこうまどぐち', 'ginkou madoguchi', 'bank counter, teller window', '银行柜台', '銀行窓口で手続きをしました。', 'I completed procedures at the bank counter.', '在银行柜台办了手续。'),
  ('ja-life-intermediate-135', 'ja', 'intermediate', 'life', '通帳', 'つうちょう', 'tsuuchou', 'bankbook, passbook', '存折', '通帳を記帳しました。', 'I updated my bankbook.', '更新了存折。'),
  ('ja-life-intermediate-136', 'ja', 'intermediate', 'life', 'キャッシュレス', 'きゃっしゅれす', 'kyasshu resu', 'cashless, digital payment', '无现金支付', 'キャッシュレス決済が増えています。', 'Cashless payments are increasing.', '无现金支付越来越多。'),
  ('ja-life-intermediate-137', 'ja', 'intermediate', 'life', '自転車', 'じてんしゃ', 'jitensha', 'bicycle, bike', '自行车', '自転車で通勤しています。', 'I commute by bicycle.', '骑自行车通勤。'),
  ('ja-life-intermediate-138', 'ja', 'intermediate', 'life', '駐輪場', 'ちゅうりんじょう', 'chuurinjou', 'bicycle parking, bike lot', '自行车停车场', '駅前の駐輪場を使っています。', 'I use the bicycle parking in front of the station.', '用站前的自行车停车场。'),
  ('ja-life-intermediate-139', 'ja', 'intermediate', 'life', 'エアコン', 'えあこん', 'eakon', 'air conditioner, AC', '空调', 'エアコンのフィルターを掃除しました。', 'I cleaned the AC filter.', '清洗了空调滤网。'),
  ('ja-life-intermediate-140', 'ja', 'intermediate', 'life', '加湿器', 'かしつき', 'kashitsuki', 'humidifier', '加湿器', '冬は加湿器を使います。', 'I use a humidifier in winter.', '冬天用加湿器。'),
  ('ja-life-intermediate-141', 'ja', 'intermediate', 'life', '除湿', 'じょしつ', 'joshitsu', 'dehumidifying, moisture removal', '除湿，去湿', '梅雨の時期は除湿が必要です。', 'Dehumidifying is necessary during rainy season.', '梅雨时期需要除湿。'),
  ('ja-life-intermediate-142', 'ja', 'intermediate', 'life', '暖房', 'だんぼう', 'danbou', 'heating, heater', '暖气，供暖', '暖房をつけてください。', 'Please turn on the heater.', '请开暖气。'),
  ('ja-life-intermediate-143', 'ja', 'intermediate', 'life', '冷房', 'れいぼう', 'reibou', 'cooling, air conditioning', '冷气，空调制冷', '冷房を二十六度に設定しています。', 'I set the AC to 26 degrees.', '空调设定在26度。'),
  ('ja-life-intermediate-144', 'ja', 'intermediate', 'life', 'ネット回線', 'ねっとかいせん', 'netto kaisen', 'internet connection, network line', '网络线路，宽带', 'ネット回線を契約しました。', 'I signed up for internet service.', '签了宽带合同。'),
  ('ja-life-intermediate-145', 'ja', 'intermediate', 'life', '宅配', 'たくはい', 'takuhai', 'home delivery, delivery service', '送货上门，配送', '宅配の時間を指定しました。', 'I specified the delivery time.', '指定了送货时间。'),
  ('ja-life-intermediate-146', 'ja', 'intermediate', 'life', '不在届', 'ふざいとどけ', 'fuzai todoke', 'absence notice, missed delivery', '不在通知，缺席通知', '不在届が入っていたので再配達を頼みました。', 'I found a missed delivery notice and requested redelivery.', '发现了不在通知，申请了重新配送。'),
  ('ja-life-intermediate-147', 'ja', 'intermediate', 'life', '生活リズム', 'せいかつりずむ', 'seikatsu rizumu', 'daily routine, life rhythm', '生活节奏，作息', '規則正しい生活リズムが大切です。', 'A regular daily routine is important.', '规律的生活节奏很重要。'),
  ('ja-life-intermediate-148', 'ja', 'intermediate', 'life', '睡眠', 'すいみん', 'suimin', 'sleep, rest', '睡眠，休息', '睡眠時間を確保しています。', 'I make sure to get enough sleep.', '在保证睡眠时间。'),
  ('ja-life-intermediate-149', 'ja', 'intermediate', 'life', '早起き', 'はやおき', 'hayaoki', 'waking up early, early riser', '早起', '早起きは三文の徳です。', 'The early bird catches the worm.', '早起的鸟儿有虫吃。'),
  ('ja-life-intermediate-150', 'ja', 'intermediate', 'life', '夜更かし', 'よふかし', 'yofukashi', 'staying up late, night owl', '熬夜', '夜更かしは体に悪いです。', 'Staying up late is bad for your health.', '熬夜对身体不好。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
