-- Expand ja-work-intermediate to 150 curated entries (17-150)
-- Topic: work/business vocabulary for intermediate Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-work-intermediate-17', 'ja', 'intermediate', 'work', '営業', 'えいぎょう', 'eigyou', 'sales, business development', '营业, 销售', '営業部は今月の目標を達成しました。', 'The sales department achieved this month''s target.', '营业部达成了本月的目标。'),
  ('ja-work-intermediate-18', 'ja', 'intermediate', 'work', '経理', 'けいり', 'keiri', 'accounting, bookkeeping', '会计, 财务', '経理部に領収書を提出してください。', 'Please submit the receipt to the accounting department.', '请把收据提交给财务部。'),
  ('ja-work-intermediate-19', 'ja', 'intermediate', 'work', '人事', 'じんじ', 'jinji', 'human resources, personnel', '人事, 人力资源', '人事部が新しい採用方針を発表しました。', 'The HR department announced a new hiring policy.', '人事部发布了新的招聘方针。'),
  ('ja-work-intermediate-20', 'ja', 'intermediate', 'work', '総務', 'そうむ', 'soumu', 'general affairs, administration', '总务, 行政', '総務部がオフィスの備品を管理しています。', 'The general affairs department manages office supplies.', '总务部负责管理办公用品。'),
  ('ja-work-intermediate-21', 'ja', 'intermediate', 'work', '企画', 'きかく', 'kikaku', 'planning, project proposal', '企划, 策划', '新しい企画を来週までに提出してください。', 'Please submit the new proposal by next week.', '请在下周之前提交新的企划方案。'),
  ('ja-work-intermediate-22', 'ja', 'intermediate', 'work', '取引先', 'とりひきさき', 'torihikisaki', 'business partner, client company', '客户, 交易对象', '取引先との関係を大切にしています。', 'We value the relationship with our business partners.', '我们重视与客户的关系。'),
  ('ja-work-intermediate-23', 'ja', 'intermediate', 'work', '契約', 'けいやく', 'keiyaku', 'contract, agreement', '合同, 契约', '契約書にサインをお願いします。', 'Please sign the contract.', '请在合同上签字。'),
  ('ja-work-intermediate-24', 'ja', 'intermediate', 'work', '納期', 'のうき', 'nouki', 'delivery date, deadline', '交货期, 交期', '納期に間に合うように進めましょう。', 'Let''s proceed so we can meet the delivery date.', '让我们加紧推进以赶上交货期。'),
  ('ja-work-intermediate-25', 'ja', 'intermediate', 'work', '見積もり', 'みつもり', 'mitsumori', 'estimate, quotation', '估价, 报价', '見積もりを明日までにお送りします。', 'I will send the estimate by tomorrow.', '我会在明天之前发送报价。'),
  ('ja-work-intermediate-26', 'ja', 'intermediate', 'work', '請求書', 'せいきゅうしょ', 'seikyuusho', 'invoice, bill', '发票, 账单', '請求書を月末に発行します。', 'We will issue the invoice at the end of the month.', '我们将在月底开具发票。'),
  ('ja-work-intermediate-27', 'ja', 'intermediate', 'work', '承認', 'しょうにん', 'shounin', 'approval, authorization', '批准, 审批', '部長の承認がないと進められません。', 'We cannot proceed without the manager''s approval.', '没有部长的批准就无法推进。'),
  ('ja-work-intermediate-28', 'ja', 'intermediate', 'work', '提案', 'ていあん', 'teian', 'proposal, suggestion', '提案, 建议', '会議で新しい提案をしました。', 'I made a new proposal at the meeting.', '我在会议上提出了新的建议。'),
  ('ja-work-intermediate-29', 'ja', 'intermediate', 'work', '交渉', 'こうしょう', 'koushou', 'negotiation, bargaining', '谈判, 协商', '価格について交渉する必要があります。', 'We need to negotiate on the price.', '我们需要就价格进行谈判。'),
  ('ja-work-intermediate-30', 'ja', 'intermediate', 'work', '決裁', 'けっさい', 'kessai', 'approval decision, authorization', '决裁, 审批决定', '社長の決裁を待っています。', 'We are waiting for the president''s approval.', '我们正在等待社长的审批。'),
  ('ja-work-intermediate-31', 'ja', 'intermediate', 'work', '稟議', 'りんぎ', 'ringi', 'formal approval request, written proposal', '签呈, 审批申请', '稟議書を回しているところです。', 'The approval request is currently being circulated.', '签呈正在传阅中。'),
  ('ja-work-intermediate-32', 'ja', 'intermediate', 'work', '研修', 'けんしゅう', 'kenshuu', 'training, professional development', '培训, 研修', '来月から新入社員の研修が始まります。', 'New employee training starts next month.', '下个月开始新员工培训。'),
  ('ja-work-intermediate-33', 'ja', 'intermediate', 'work', '異動', 'いどう', 'idou', 'transfer, reassignment', '调动, 人事变动', '来月、大阪支社に異動することになりました。', 'I will be transferred to the Osaka branch next month.', '我下个月将调动到大阪分公司。'),
  ('ja-work-intermediate-34', 'ja', 'intermediate', 'work', '配属', 'はいぞく', 'haizoku', 'assignment, placement', '分配, 派遣', '新入社員が各部署に配属されました。', 'New employees were assigned to each department.', '新员工被分配到了各个部门。'),
  ('ja-work-intermediate-35', 'ja', 'intermediate', 'work', '退職', 'たいしょく', 'taishoku', 'resignation, retirement', '离职, 退休', '退職届を提出する予定です。', 'I plan to submit my resignation letter.', '我打算提交辞职信。'),
  ('ja-work-intermediate-36', 'ja', 'intermediate', 'work', '採用', 'さいよう', 'saiyou', 'hiring, recruitment', '录用, 招聘', '今年は十人を採用する予定です。', 'We plan to hire ten people this year.', '今年计划录用十人。'),
  ('ja-work-intermediate-37', 'ja', 'intermediate', 'work', '内定', 'ないてい', 'naitei', 'job offer, informal decision', '内定, 录用通知', '第一志望の会社から内定をもらいました。', 'I received a job offer from my top-choice company.', '我收到了第一志愿公司的内定。'),
  ('ja-work-intermediate-38', 'ja', 'intermediate', 'work', '福利厚生', 'ふくりこうせい', 'fukuri kousei', 'employee benefits, welfare', '福利待遇, 员工福利', 'この会社は福利厚生が充実しています。', 'This company has excellent employee benefits.', '这家公司的福利待遇很好。'),
  ('ja-work-intermediate-39', 'ja', 'intermediate', 'work', '有給休暇', 'ゆうきゅうきゅうか', 'yuukyuu kyuuka', 'paid leave, paid vacation', '带薪休假, 年假', '有給休暇を申請したいのですが。', 'I would like to apply for paid leave.', '我想申请带薪休假。'),
  ('ja-work-intermediate-40', 'ja', 'intermediate', 'work', '賞与', 'しょうよ', 'shouyo', 'bonus, reward', '奖金, 年终奖', '夏の賞与は七月に支給されます。', 'The summer bonus will be paid in July.', '夏季奖金将在七月发放。'),
  ('ja-work-intermediate-41', 'ja', 'intermediate', 'work', '手当', 'てあて', 'teate', 'allowance, compensation', '补贴, 津贴', '通勤手当は月三万円まで支給されます。', 'The commuting allowance is paid up to 30,000 yen per month.', '通勤补贴每月最多支付三万日元。'),
  ('ja-work-intermediate-42', 'ja', 'intermediate', 'work', '昇給', 'しょうきゅう', 'shoukyuu', 'pay raise, salary increase', '加薪, 涨工资', '毎年四月に昇給があります。', 'There is a pay raise every April.', '每年四月会加薪。'),
  ('ja-work-intermediate-43', 'ja', 'intermediate', 'work', '勤務', 'きんむ', 'kinmu', 'work duty, service', '工作, 上班', '勤務時間は九時から六時までです。', 'Working hours are from 9 to 6.', '工作时间是从九点到六点。'),
  ('ja-work-intermediate-44', 'ja', 'intermediate', 'work', '在宅勤務', 'ざいたくきんむ', 'zaitaku kinmu', 'remote work, work from home', '远程办公, 居家办公', '週に二回在宅勤務をしています。', 'I work from home twice a week.', '我每周居家办公两次。'),
  ('ja-work-intermediate-45', 'ja', 'intermediate', 'work', 'フレックス', 'ふれっくす', 'furekkusu', 'flextime, flexible hours', '弹性工作制, 弹性时间', 'うちの会社はフレックス制度があります。', 'Our company has a flextime system.', '我们公司有弹性工作制度。'),
  ('ja-work-intermediate-46', 'ja', 'intermediate', 'work', '打ち合わせ', 'うちあわせ', 'uchiawase', 'meeting, preliminary discussion', '碰头会, 商讨', '午後三時から打ち合わせがあります。', 'There is a meeting at 3 PM.', '下午三点有个碰头会。'),
  ('ja-work-intermediate-47', 'ja', 'intermediate', 'work', '議事録', 'ぎじろく', 'gijiroku', 'meeting minutes, proceedings', '会议纪要, 会议记录', '議事録を作成して共有してください。', 'Please create the meeting minutes and share them.', '请整理会议纪要并共享。'),
  ('ja-work-intermediate-48', 'ja', 'intermediate', 'work', '資料', 'しりょう', 'shiryou', 'materials, documents', '资料, 材料', '会議の資料を準備しました。', 'I prepared the materials for the meeting.', '我准备好了会议资料。'),
  ('ja-work-intermediate-49', 'ja', 'intermediate', 'work', '発表', 'はっぴょう', 'happyou', 'presentation, announcement', '发表, 演讲', '来週の会議で発表する予定です。', 'I plan to give a presentation at next week''s meeting.', '我计划在下周的会议上发表演讲。'),
  ('ja-work-intermediate-50', 'ja', 'intermediate', 'work', 'プレゼン', 'ぷれぜん', 'purezen', 'presentation, pitch', '演示, 汇报', 'クライアントへのプレゼンを練習しています。', 'I am practicing the presentation for the client.', '我正在练习面向客户的演示。'),
  ('ja-work-intermediate-51', 'ja', 'intermediate', 'work', '業績', 'ぎょうせき', 'gyouseki', 'business results, performance', '业绩, 业务成果', '今期の業績は好調です。', 'Business performance is strong this period.', '本期的业绩表现良好。'),
  ('ja-work-intermediate-52', 'ja', 'intermediate', 'work', '売上', 'うりあげ', 'uriage', 'sales revenue, turnover', '销售额, 营业额', '売上が前年比で二十パーセント増えました。', 'Sales increased by 20% compared to last year.', '销售额比去年增长了百分之二十。'),
  ('ja-work-intermediate-53', 'ja', 'intermediate', 'work', '利益', 'りえき', 'rieki', 'profit, benefit', '利润, 收益', '利益率を改善する必要があります。', 'We need to improve the profit margin.', '我们需要改善利润率。'),
  ('ja-work-intermediate-54', 'ja', 'intermediate', 'work', '予算', 'よさん', 'yosan', 'budget, funds', '预算, 经费', '来年度の予算を検討しています。', 'We are reviewing the budget for next fiscal year.', '我们正在讨论下一年度的预算。'),
  ('ja-work-intermediate-55', 'ja', 'intermediate', 'work', '経費', 'けいひ', 'keihi', 'expenses, costs', '经费, 费用', '出張の経費を精算してください。', 'Please settle the business trip expenses.', '请报销出差费用。'),
  ('ja-work-intermediate-56', 'ja', 'intermediate', 'work', '精算', 'せいさん', 'seisan', 'settlement, reimbursement', '报销, 结算', '経費精算は月末までに行ってください。', 'Please complete expense reimbursement by the end of the month.', '请在月底前完成费用报销。'),
  ('ja-work-intermediate-57', 'ja', 'intermediate', 'work', '部長', 'ぶちょう', 'buchou', 'department head, general manager', '部长, 部门经理', '部長に相談してから決めます。', 'I will decide after consulting with the department head.', '我和部长商量后再做决定。'),
  ('ja-work-intermediate-58', 'ja', 'intermediate', 'work', '課長', 'かちょう', 'kachou', 'section chief, manager', '课长, 科长', '課長が今日は出張中です。', 'The section chief is on a business trip today.', '课长今天出差了。'),
  ('ja-work-intermediate-59', 'ja', 'intermediate', 'work', '係長', 'かかりちょう', 'kakarichou', 'subsection chief, team lead', '系长, 主任', '係長に確認してからお返事します。', 'I will reply after checking with the team lead.', '我和主任确认后再回复您。'),
  ('ja-work-intermediate-60', 'ja', 'intermediate', 'work', '主任', 'しゅにん', 'shunin', 'senior staff, supervisor', '主任, 负责人', '主任がプロジェクトを担当しています。', 'The supervisor is in charge of the project.', '主任负责这个项目。'),
  ('ja-work-intermediate-61', 'ja', 'intermediate', 'work', '社長', 'しゃちょう', 'shachou', 'president, CEO', '社长, 总裁', '社長が全社員にメッセージを送りました。', 'The president sent a message to all employees.', '社长给全体员工发送了消息。'),
  ('ja-work-intermediate-62', 'ja', 'intermediate', 'work', '役員', 'やくいん', 'yakuin', 'executive, board member', '董事, 高管', '役員会議は毎月第一月曜日です。', 'The board meeting is on the first Monday of every month.', '董事会会议在每月第一个周一举行。'),
  ('ja-work-intermediate-63', 'ja', 'intermediate', 'work', '新入社員', 'しんにゅうしゃいん', 'shin nyuu shain', 'new employee, new hire', '新员工, 新入职员工', '新入社員の歓迎会を開きます。', 'We will hold a welcome party for new employees.', '我们将为新员工举办欢迎会。'),
  ('ja-work-intermediate-64', 'ja', 'intermediate', 'work', '正社員', 'せいしゃいん', 'seishain', 'full-time employee, permanent staff', '正式员工, 正社员', '正社員として採用されました。', 'I was hired as a full-time employee.', '我被录用为正式员工。'),
  ('ja-work-intermediate-65', 'ja', 'intermediate', 'work', '派遣', 'はけん', 'haken', 'temporary staffing, dispatch', '派遣, 外派', '派遣社員として三年間働きました。', 'I worked as a temporary staff member for three years.', '我作为派遣员工工作了三年。'),
  ('ja-work-intermediate-66', 'ja', 'intermediate', 'work', 'アルバイト', 'あるばいと', 'arubaito', 'part-time job, side work', '兼职, 打工', '学生時代にアルバイトをしていました。', 'I had a part-time job when I was a student.', '学生时代我做过兼职。'),
  ('ja-work-intermediate-67', 'ja', 'intermediate', 'work', '担当', 'たんとう', 'tantou', 'person in charge, responsible for', '负责人, 担当', '私がこのプロジェクトの担当です。', 'I am in charge of this project.', '我是这个项目的负责人。'),
  ('ja-work-intermediate-68', 'ja', 'intermediate', 'work', '依頼', 'いらい', 'irai', 'request, commission', '委托, 请求', 'デザインの依頼を外部に出しました。', 'We outsourced the design request.', '我们把设计委托给了外部。'),
  ('ja-work-intermediate-69', 'ja', 'intermediate', 'work', '対応', 'たいおう', 'taiou', 'response, handling', '应对, 处理', 'クレームに迅速に対応しました。', 'We responded to the complaint promptly.', '我们迅速处理了投诉。'),
  ('ja-work-intermediate-70', 'ja', 'intermediate', 'work', '確認', 'かくにん', 'kakunin', 'confirmation, verification', '确认, 核实', 'スケジュールを確認させてください。', 'Let me confirm the schedule.', '请让我确认一下日程。'),
  ('ja-work-intermediate-71', 'ja', 'intermediate', 'work', '共有', 'きょうゆう', 'kyouyuu', 'sharing, mutual use', '共享, 分享', '情報を全員に共有してください。', 'Please share the information with everyone.', '请把信息分享给所有人。'),
  ('ja-work-intermediate-72', 'ja', 'intermediate', 'work', '連絡', 'れんらく', 'renraku', 'contact, communication', '联系, 联络', '何かあればすぐに連絡してください。', 'Please contact me immediately if anything comes up.', '如有任何情况请立即联系我。'),
  ('ja-work-intermediate-73', 'ja', 'intermediate', 'work', '相談', 'そうだん', 'soudan', 'consultation, discussion', '商量, 咨询', '上司に相談してから決めます。', 'I will decide after discussing with my supervisor.', '我和上司商量后再决定。'),
  ('ja-work-intermediate-74', 'ja', 'intermediate', 'work', '検討', 'けんとう', 'kentou', 'consideration, examination', '研究, 探讨', '前向きに検討させていただきます。', 'We will consider it positively.', '我们会积极研究。'),
  ('ja-work-intermediate-75', 'ja', 'intermediate', 'work', '調整', 'ちょうせい', 'chousei', 'adjustment, coordination', '调整, 协调', 'スケジュールを調整しましょう。', 'Let''s coordinate the schedule.', '让我们调整一下日程。'),
  ('ja-work-intermediate-76', 'ja', 'intermediate', 'work', '進捗', 'しんちょく', 'shinchoku', 'progress, advancement', '进展, 进度', 'プロジェクトの進捗を教えてください。', 'Please update me on the project progress.', '请告诉我项目的进展情况。'),
  ('ja-work-intermediate-77', 'ja', 'intermediate', 'work', '方針', 'ほうしん', 'houshin', 'policy, direction', '方针, 政策', '会社の方針に従って行動します。', 'I will act according to company policy.', '我会按照公司方针行动。'),
  ('ja-work-intermediate-78', 'ja', 'intermediate', 'work', '目標', 'もくひょう', 'mokuhyou', 'goal, target', '目标, 指标', '今期の売上目標を設定しました。', 'We set the sales target for this period.', '我们设定了本期的销售目标。'),
  ('ja-work-intermediate-79', 'ja', 'intermediate', 'work', '成果', 'せいか', 'seika', 'result, achievement', '成果, 成绩', '研修の成果が出てきました。', 'The results of the training are showing.', '培训的成果开始显现了。'),
  ('ja-work-intermediate-80', 'ja', 'intermediate', 'work', '評価', 'ひょうか', 'hyouka', 'evaluation, assessment', '评价, 考核', '半年に一度、人事評価があります。', 'There is a performance evaluation once every six months.', '每半年进行一次人事考核。'),
  ('ja-work-intermediate-81', 'ja', 'intermediate', 'work', '実績', 'じっせき', 'jisseki', 'track record, actual results', '实绩, 业绩', '過去の実績をもとに判断します。', 'We will judge based on past performance.', '我们将根据过去的实绩来判断。'),
  ('ja-work-intermediate-82', 'ja', 'intermediate', 'work', '改善', 'かいぜん', 'kaizen', 'improvement, reform', '改善, 改进', '業務プロセスの改善に取り組んでいます。', 'We are working on improving business processes.', '我们正在致力于改善业务流程。'),
  ('ja-work-intermediate-83', 'ja', 'intermediate', 'work', '効率', 'こうりつ', 'kouritsu', 'efficiency, productivity', '效率, 生产力', '作業の効率を上げる方法を考えましょう。', 'Let''s think about ways to improve work efficiency.', '让我们想想提高工作效率的方法。'),
  ('ja-work-intermediate-84', 'ja', 'intermediate', 'work', '品質', 'ひんしつ', 'hinshitsu', 'quality, standard', '品质, 质量', '品質管理は非常に重要です。', 'Quality control is extremely important.', '品质管理非常重要。'),
  ('ja-work-intermediate-85', 'ja', 'intermediate', 'work', '納品', 'のうひん', 'nouhin', 'delivery, shipment', '交货, 交付', '来週の金曜日に納品予定です。', 'Delivery is scheduled for next Friday.', '预定下周五交货。'),
  ('ja-work-intermediate-86', 'ja', 'intermediate', 'work', '発注', 'はっちゅう', 'hatchuu', 'placing an order, ordering', '下单, 订购', '新しい備品を発注しました。', 'I placed an order for new supplies.', '我订购了新的办公用品。'),
  ('ja-work-intermediate-87', 'ja', 'intermediate', 'work', '受注', 'じゅちゅう', 'juchuu', 'receiving an order, order intake', '接单, 受理订单', '大口の受注に成功しました。', 'We successfully received a large order.', '我们成功接到了一笔大订单。'),
  ('ja-work-intermediate-88', 'ja', 'intermediate', 'work', '在庫', 'ざいこ', 'zaiko', 'inventory, stock', '库存, 存货', '在庫を確認してから回答します。', 'I will reply after checking the inventory.', '我确认库存后再回复。'),
  ('ja-work-intermediate-89', 'ja', 'intermediate', 'work', '顧客', 'こきゃく', 'kokyaku', 'customer, client', '顾客, 客户', '顧客満足度を向上させたいです。', 'We want to improve customer satisfaction.', '我们想要提升顾客满意度。'),
  ('ja-work-intermediate-90', 'ja', 'intermediate', 'work', '商談', 'しょうだん', 'shoudan', 'business negotiation, deal talk', '商谈, 洽谈', '午後に重要な商談があります。', 'There is an important business negotiation this afternoon.', '下午有一个重要的商谈。'),
  ('ja-work-intermediate-91', 'ja', 'intermediate', 'work', '競合', 'きょうごう', 'kyougou', 'competitor, rivalry', '竞争对手, 竞争', '競合他社の動向を分析しています。', 'We are analyzing the trends of our competitors.', '我们正在分析竞争对手的动向。'),
  ('ja-work-intermediate-92', 'ja', 'intermediate', 'work', '市場', 'しじょう', 'shijou', 'market, marketplace', '市场, 行情', '新しい市場に参入する計画です。', 'We plan to enter a new market.', '我们计划进入新的市场。'),
  ('ja-work-intermediate-93', 'ja', 'intermediate', 'work', '戦略', 'せんりゃく', 'senryaku', 'strategy, tactics', '战略, 策略', '来年度の事業戦略を策定中です。', 'We are formulating next year''s business strategy.', '我们正在制定下一年度的事业战略。'),
  ('ja-work-intermediate-94', 'ja', 'intermediate', 'work', '施策', 'しさく', 'shisaku', 'measure, policy initiative', '措施, 对策', '新しい施策を実施する予定です。', 'We plan to implement new measures.', '我们计划实施新的措施。'),
  ('ja-work-intermediate-95', 'ja', 'intermediate', 'work', '案件', 'あんけん', 'anken', 'project case, matter', '案件, 项目', '今抱えている案件は五つあります。', 'I currently have five cases I''m handling.', '我目前手上有五个案件。'),
  ('ja-work-intermediate-96', 'ja', 'intermediate', 'work', '工程', 'こうてい', 'koutei', 'process, production schedule', '工序, 工程', '工程表を作成してください。', 'Please create a process schedule.', '请制作工程表。'),
  ('ja-work-intermediate-97', 'ja', 'intermediate', 'work', '仕様', 'しよう', 'shiyou', 'specifications, design', '规格, 规范', '仕様書を確認してから開発を始めます。', 'We will start development after reviewing the specifications.', '确认规格书后再开始开发。'),
  ('ja-work-intermediate-98', 'ja', 'intermediate', 'work', '要件', 'ようけん', 'youken', 'requirements, conditions', '要求, 条件', '要件定義を最初に行いましょう。', 'Let''s define the requirements first.', '让我们首先进行需求定义。'),
  ('ja-work-intermediate-99', 'ja', 'intermediate', 'work', '実装', 'じっそう', 'jissou', 'implementation, deployment', '实现, 实装', '新機能の実装が完了しました。', 'The implementation of the new feature is complete.', '新功能的实现已经完成。'),
  ('ja-work-intermediate-100', 'ja', 'intermediate', 'work', '運用', 'うんよう', 'unyou', 'operation, management', '运营, 运用', 'システムの運用を担当しています。', 'I am in charge of system operations.', '我负责系统的运营。'),
  ('ja-work-intermediate-101', 'ja', 'intermediate', 'work', '導入', 'どうにゅう', 'dounyuu', 'introduction, implementation', '引进, 导入', '新しいシステムを導入しました。', 'We introduced a new system.', '我们引进了新的系统。'),
  ('ja-work-intermediate-102', 'ja', 'intermediate', 'work', '更新', 'こうしん', 'koushin', 'update, renewal', '更新, 续签', '契約を更新する時期です。', 'It is time to renew the contract.', '到了续签合同的时候了。'),
  ('ja-work-intermediate-103', 'ja', 'intermediate', 'work', '修正', 'しゅうせい', 'shuusei', 'correction, revision', '修改, 修正', '資料の修正をお願いします。', 'Please make corrections to the document.', '请修改资料。'),
  ('ja-work-intermediate-104', 'ja', 'intermediate', 'work', '差し戻し', 'さしもどし', 'sashimodoshi', 'rejection, sending back', '退回, 驳回', '申請が差し戻されました。', 'The application was sent back for revision.', '申请被退回了。'),
  ('ja-work-intermediate-105', 'ja', 'intermediate', 'work', '引き継ぎ', 'ひきつぎ', 'hikitsugi', 'handover, succession', '交接, 移交', '退職前に引き継ぎを完了させます。', 'I will complete the handover before leaving.', '我会在离职前完成工作交接。'),
  ('ja-work-intermediate-106', 'ja', 'intermediate', 'work', '指示', 'しじ', 'shiji', 'instruction, direction', '指示, 指令', '上司の指示に従ってください。', 'Please follow your supervisor''s instructions.', '请遵从上司的指示。'),
  ('ja-work-intermediate-107', 'ja', 'intermediate', 'work', '報連相', 'ほうれんそう', 'hourensou', 'report-contact-consult, communication basics', '报联商, 职场沟通基本', '報連相を徹底しましょう。', 'Let''s be thorough with reporting, contacting, and consulting.', '让我们彻底做好报联商。'),
  ('ja-work-intermediate-108', 'ja', 'intermediate', 'work', '名刺', 'めいし', 'meishi', 'business card, name card', '名片, 名帖', '名刺交換をしましょう。', 'Let''s exchange business cards.', '让我们交换名片吧。'),
  ('ja-work-intermediate-109', 'ja', 'intermediate', 'work', '敬語', 'けいご', 'keigo', 'honorific language, polite speech', '敬语, 礼貌用语', 'ビジネスでは敬語が必須です。', 'Honorific language is essential in business.', '在商务场合敬语是必须的。'),
  ('ja-work-intermediate-110', 'ja', 'intermediate', 'work', '電話応対', 'でんわおうたい', 'denwa outai', 'phone handling, answering calls', '接听电话, 电话应对', '電話応対のマナーを学びましょう。', 'Let''s learn phone handling etiquette.', '让我们学习接听电话的礼仪。'),
  ('ja-work-intermediate-111', 'ja', 'intermediate', 'work', '議題', 'ぎだい', 'gidai', 'agenda item, topic for discussion', '议题, 议程', '本日の議題は三つあります。', 'There are three agenda items for today.', '今天有三个议题。'),
  ('ja-work-intermediate-112', 'ja', 'intermediate', 'work', '決議', 'けつぎ', 'ketsugi', 'resolution, decision', '决议, 表决', '取締役会で決議されました。', 'It was resolved at the board meeting.', '在董事会上做出了决议。'),
  ('ja-work-intermediate-113', 'ja', 'intermediate', 'work', '委託', 'いたく', 'itaku', 'outsourcing, consignment', '委托, 外包', '業務の一部を外部に委託しています。', 'We outsource part of our operations.', '我们将部分业务委托给外部。'),
  ('ja-work-intermediate-114', 'ja', 'intermediate', 'work', '監査', 'かんさ', 'kansa', 'audit, inspection', '审计, 监查', '来月、内部監査が行われます。', 'An internal audit will be conducted next month.', '下个月将进行内部审计。'),
  ('ja-work-intermediate-115', 'ja', 'intermediate', 'work', 'コンプライアンス', 'こんぷらいあんす', 'konpuraiansu', 'compliance, regulatory adherence', '合规, 法令遵守', 'コンプライアンス研修は全員必須です。', 'Compliance training is mandatory for everyone.', '合规培训全员必须参加。'),
  ('ja-work-intermediate-116', 'ja', 'intermediate', 'work', '情報漏洩', 'じょうほうろうえい', 'jouhou rouei', 'information leak, data breach', '信息泄露, 数据泄露', '情報漏洩を防ぐ対策が必要です。', 'Measures to prevent information leaks are necessary.', '需要采取防止信息泄露的措施。'),
  ('ja-work-intermediate-117', 'ja', 'intermediate', 'work', '個人情報', 'こじんじょうほう', 'kojin jouhou', 'personal information, private data', '个人信息, 隐私数据', '個人情報の取り扱いに注意してください。', 'Please be careful with the handling of personal information.', '请注意个人信息的处理。'),
  ('ja-work-intermediate-118', 'ja', 'intermediate', 'work', '業務改善', 'ぎょうむかいぜん', 'gyoumu kaizen', 'operational improvement, process optimization', '业务改善, 流程优化', '業務改善の提案を募集しています。', 'We are soliciting proposals for operational improvement.', '我们正在征集业务改善的建议。'),
  ('ja-work-intermediate-119', 'ja', 'intermediate', 'work', '会議室', 'かいぎしつ', 'kaigishitsu', 'meeting room, conference room', '会议室, 会客室', '会議室を予約してください。', 'Please reserve a meeting room.', '请预约会议室。'),
  ('ja-work-intermediate-120', 'ja', 'intermediate', 'work', '複合機', 'ふくごうき', 'fukugouki', 'multifunction printer, copier', '复合机, 多功能打印机', '複合機の紙が切れています。', 'The multifunction printer is out of paper.', '复合机没纸了。'),
  ('ja-work-intermediate-121', 'ja', 'intermediate', 'work', '社内メール', 'しゃないめーる', 'shanai meeru', 'internal email, company email', '内部邮件, 公司邮件', '社内メールで通知します。', 'We will notify via internal email.', '我们会通过内部邮件通知。'),
  ('ja-work-intermediate-122', 'ja', 'intermediate', 'work', '件名', 'けんめい', 'kenmei', 'subject line, email title', '邮件主题, 标题', 'メールの件名を分かりやすくしてください。', 'Please make the email subject line easy to understand.', '请把邮件主题写得容易理解。'),
  ('ja-work-intermediate-123', 'ja', 'intermediate', 'work', '添付', 'てんぷ', 'tenpu', 'attachment, enclosure', '附件, 附加', 'ファイルを添付しましたのでご確認ください。', 'I have attached the file, please check it.', '已附上文件，请确认。'),
  ('ja-work-intermediate-124', 'ja', 'intermediate', 'work', '転送', 'てんそう', 'tensou', 'forwarding, transfer', '转发, 转送', 'このメールを関係者に転送してください。', 'Please forward this email to the relevant people.', '请将这封邮件转发给相关人员。'),
  ('ja-work-intermediate-125', 'ja', 'intermediate', 'work', 'お疲れ様', 'おつかれさま', 'otsukaresama', 'good work, thank you for your effort', '辛苦了, 您辛苦了', 'お疲れ様です。今日の報告です。', 'Thank you for your hard work. Here is today''s report.', '辛苦了。这是今天的报告。'),
  ('ja-work-intermediate-126', 'ja', 'intermediate', 'work', 'お世話になっております', 'おせわになっております', 'osewa ni natte orimasu', 'thank you for your support, greeting in emails', '承蒙关照, 邮件问候语', 'いつもお世話になっております。', 'Thank you for your continued support.', '一直以来承蒙关照。'),
  ('ja-work-intermediate-127', 'ja', 'intermediate', 'work', 'ご査収', 'ごさしゅう', 'gosashuu', 'please review and accept, kindly check', '请查收, 请过目', '資料をお送りしますので、ご査収ください。', 'I am sending the materials, please review and accept them.', '我将发送资料，请查收。'),
  ('ja-work-intermediate-128', 'ja', 'intermediate', 'work', '恐れ入りますが', 'おそれいりますが', 'osore irimasu ga', 'I''m sorry to trouble you, excuse me but', '冒昧打扰, 不好意思', '恐れ入りますが、もう一度ご確認いただけますか。', 'I''m sorry to trouble you, but could you confirm once more?', '不好意思，能否请您再确认一次？'),
  ('ja-work-intermediate-129', 'ja', 'intermediate', 'work', '幸いです', 'さいわいです', 'saiwai desu', 'I would appreciate it, it would be helpful', '不胜感激, 万分感谢', 'ご返信いただければ幸いです。', 'I would appreciate it if you could reply.', '如能回复，不胜感激。'),
  ('ja-work-intermediate-130', 'ja', 'intermediate', 'work', '早退', 'そうたい', 'soutai', 'leaving early, early departure', '早退, 提前下班', '体調が悪いので早退させていただきます。', 'I''m not feeling well, so I will leave early.', '因为身体不舒服，我想提前下班。'),
  ('ja-work-intermediate-131', 'ja', 'intermediate', 'work', '欠勤', 'けっきん', 'kekkin', 'absence from work, missing work', '缺勤, 旷工', '無断欠勤は避けてください。', 'Please avoid unexcused absences.', '请避免无故缺勤。'),
  ('ja-work-intermediate-132', 'ja', 'intermediate', 'work', '年末調整', 'ねんまつちょうせい', 'nenmatsu chousei', 'year-end tax adjustment, annual settlement', '年末调整, 年终结算', '年末調整の書類を提出してください。', 'Please submit the year-end tax adjustment documents.', '请提交年末调整的文件。'),
  ('ja-work-intermediate-133', 'ja', 'intermediate', 'work', '源泉徴収', 'げんせんちょうしゅう', 'gensen choushuu', 'tax withholding, withholding at source', '源泉征收, 代扣所得税', '源泉徴収票が必要な方は申請してください。', 'Those who need a withholding tax certificate, please apply.', '需要源泉征收票的人请提出申请。'),
  ('ja-work-intermediate-134', 'ja', 'intermediate', 'work', '扶養', 'ふよう', 'fuyou', 'dependent, family support', '抚养, 赡养', '扶養家族の人数を記入してください。', 'Please fill in the number of dependents.', '请填写被抚养家属的人数。'),
  ('ja-work-intermediate-135', 'ja', 'intermediate', 'work', '社会保険', 'しゃかいほけん', 'shakai hoken', 'social insurance, social security', '社会保险, 社保', '社会保険の手続きが必要です。', 'Social insurance procedures are required.', '需要办理社会保险手续。'),
  ('ja-work-intermediate-136', 'ja', 'intermediate', 'work', '健康診断', 'けんこうしんだん', 'kenkou shindan', 'health checkup, medical examination', '体检, 健康检查', '年に一度の健康診断を受けてください。', 'Please take the annual health checkup.', '请参加一年一次的体检。'),
  ('ja-work-intermediate-137', 'ja', 'intermediate', 'work', '労働組合', 'ろうどうくみあい', 'roudou kumiai', 'labor union, workers'' union', '工会, 劳动组合', '労働組合の会議に出席しました。', 'I attended the labor union meeting.', '我出席了工会会议。'),
  ('ja-work-intermediate-138', 'ja', 'intermediate', 'work', '就業規則', 'しゅうぎょうきそく', 'shuugyou kisoku', 'work regulations, employment rules', '就业规则, 员工守则', '就業規則を読んでおいてください。', 'Please read the work regulations in advance.', '请事先阅读就业规则。'),
  ('ja-work-intermediate-139', 'ja', 'intermediate', 'work', '始末書', 'しまつしょ', 'shimatsusho', 'written apology, incident report', '检讨书, 事故报告', '始末書の提出を求められました。', 'I was asked to submit a written apology.', '我被要求提交检讨书。'),
  ('ja-work-intermediate-140', 'ja', 'intermediate', 'work', '棚卸し', 'たなおろし', 'tanaoroshi', 'inventory check, stocktaking', '盘点, 清点库存', '月末に棚卸しを行います。', 'We will conduct a stocktaking at the end of the month.', '月底进行盘点。'),
  ('ja-work-intermediate-141', 'ja', 'intermediate', 'work', '歩合', 'ぶあい', 'buai', 'commission, percentage-based pay', '提成, 佣金', '営業は歩合制で給与が決まります。', 'Sales staff''s salary is determined by commission.', '营业人员的工资按提成制决定。'),
  ('ja-work-intermediate-142', 'ja', 'intermediate', 'work', '繁忙期', 'はんぼうき', 'hanbouki', 'busy season, peak period', '旺季, 繁忙期', '年末は繁忙期なので残業が増えます。', 'Year-end is the busy season, so overtime increases.', '年底是旺季，加班会增多。'),
  ('ja-work-intermediate-143', 'ja', 'intermediate', 'work', '閑散期', 'かんさんき', 'kansanki', 'slow season, off-peak period', '淡季, 闲散期', '閑散期を利用して研修を行います。', 'We conduct training during the slow season.', '利用淡季进行培训。'),
  ('ja-work-intermediate-144', 'ja', 'intermediate', 'work', '取締役', 'とりしまりやく', 'torishimariyaku', 'director, board member', '董事, 取缔役', '取締役会で方針が決まりました。', 'The policy was decided at the board of directors meeting.', '方针在董事会上决定了。'),
  ('ja-work-intermediate-145', 'ja', 'intermediate', 'work', '株主', 'かぶぬし', 'kabunushi', 'shareholder, stockholder', '股东, 持股人', '株主総会が来月開催されます。', 'The shareholders'' meeting will be held next month.', '股东大会将于下个月召开。'),
  ('ja-work-intermediate-146', 'ja', 'intermediate', 'work', '子会社', 'こがいしゃ', 'kogaisha', 'subsidiary, affiliate', '子公司, 关联公司', '子会社と連携して事業を進めています。', 'We are advancing the business in collaboration with subsidiaries.', '我们与子公司合作推进业务。'),
  ('ja-work-intermediate-147', 'ja', 'intermediate', 'work', '本社', 'ほんしゃ', 'honsha', 'headquarters, main office', '总公司, 总部', '本社は東京にあります。', 'The headquarters is in Tokyo.', '总公司在东京。'),
  ('ja-work-intermediate-148', 'ja', 'intermediate', 'work', '支社', 'ししゃ', 'shisha', 'branch office, regional office', '分公司, 分社', '大阪支社に転勤することになりました。', 'I will be transferred to the Osaka branch office.', '我将调到大阪分公司。'),
  ('ja-work-intermediate-149', 'ja', 'intermediate', 'work', '工場', 'こうじょう', 'koujou', 'factory, manufacturing plant', '工厂, 制造厂', '工場の生産ラインを見学しました。', 'I toured the factory production line.', '我参观了工厂的生产线。'),
  ('ja-work-intermediate-150', 'ja', 'intermediate', 'work', '倉庫', 'そうこ', 'souko', 'warehouse, storage facility', '仓库, 库房', '倉庫の在庫管理を徹底してください。', 'Please be thorough with warehouse inventory management.', '请彻底做好仓库的库存管理。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
