-- Expand ko-food-basic to 150 curated entries (16-150)
-- Topic: food vocabulary for basic Korean learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ko-food-basic-16', 'ko', 'basic', 'food', '국', '국', 'guk', 'soup', '汤', '국이 맛있어요.', 'The soup is delicious.', '汤很好喝。'),
  ('ko-food-basic-17', 'ko', 'basic', 'food', '찌개', '찌개', 'jjigae', 'stew', '炖汤', '찌개를 끓여요.', 'I make stew.', '我煮炖汤。'),
  ('ko-food-basic-18', 'ko', 'basic', 'food', '김치', '김치', 'gimchi', 'kimchi', '泡菜', '김치를 좋아해요.', 'I like kimchi.', '我喜欢泡菜。'),
  ('ko-food-basic-19', 'ko', 'basic', 'food', '라면', '라면', 'ramyeon', 'instant noodles', '方便面', '라면을 먹어요.', 'I eat instant noodles.', '我吃方便面。'),
  ('ko-food-basic-20', 'ko', 'basic', 'food', '치킨', '치킨', 'chikin', 'fried chicken', '炸鸡', '치킨을 시켜요.', 'I order fried chicken.', '我点炸鸡。'),
  ('ko-food-basic-21', 'ko', 'basic', 'food', '떡', '떡', 'tteok', 'rice cake', '年糕', '떡을 먹어요.', 'I eat rice cake.', '我吃年糕。'),
  ('ko-food-basic-22', 'ko', 'basic', 'food', '반찬', '반찬', 'banchan', 'side dish', '小菜', '반찬이 많아요.', 'There are many side dishes.', '小菜很多。'),
  ('ko-food-basic-23', 'ko', 'basic', 'food', '소금', '소금', 'sogeum', 'salt', '盐', '소금을 넣어요.', 'I add salt.', '我放盐。'),
  ('ko-food-basic-24', 'ko', 'basic', 'food', '설탕', '설탕', 'seoltang', 'sugar', '糖', '설탕을 넣어요.', 'I add sugar.', '我放糖。'),
  ('ko-food-basic-25', 'ko', 'basic', 'food', '간장', '간장', 'ganjang', 'soy sauce', '酱油', '간장을 넣어요.', 'I add soy sauce.', '我放酱油。'),
  ('ko-food-basic-26', 'ko', 'basic', 'food', '기름', '기름', 'gireum', 'oil', '油', '기름을 두르세요.', 'Please add oil.', '请放油。'),
  ('ko-food-basic-27', 'ko', 'basic', 'food', '후추', '후추', 'huchu', 'pepper', '胡椒', '후추를 뿌려요.', 'I sprinkle pepper.', '我撒胡椒。'),
  ('ko-food-basic-28', 'ko', 'basic', 'food', '식당', '식당', 'sikdang', 'restaurant', '餐厅', '식당에 가요.', 'I go to a restaurant.', '我去餐厅。'),
  ('ko-food-basic-29', 'ko', 'basic', 'food', '메뉴', '메뉴', 'menyu', 'menu', '菜单', '메뉴를 주세요.', 'Please give me the menu.', '请给我菜单。'),
  ('ko-food-basic-30', 'ko', 'basic', 'food', '주문', '주문', 'jumun', 'order', '点单', '주문할게요.', 'I''ll order.', '我要点单。'),
  ('ko-food-basic-31', 'ko', 'basic', 'food', '맛', '맛', 'mat', 'taste', '味道', '맛이 좋아요.', 'The taste is good.', '味道很好。'),
  ('ko-food-basic-32', 'ko', 'basic', 'food', '맵다', '맵다', 'maepda', 'spicy', '辣', '너무 매워요.', 'It''s too spicy.', '太辣了。'),
  ('ko-food-basic-33', 'ko', 'basic', 'food', '달다', '달다', 'dalda', 'sweet', '甜', '케이크가 달아요.', 'The cake is sweet.', '蛋糕很甜。'),
  ('ko-food-basic-34', 'ko', 'basic', 'food', '짜다', '짜다', 'jjada', 'salty', '咸', '좀 짜요.', 'It''s a bit salty.', '有点咸。'),
  ('ko-food-basic-35', 'ko', 'basic', 'food', '시다', '시다', 'sida', 'sour', '酸', '레몬이 셔요.', 'The lemon is sour.', '柠檬很酸。'),
  ('ko-food-basic-36', 'ko', 'basic', 'food', '쓰다', '쓰다', 'sseuda', 'bitter', '苦', '약이 써요.', 'The medicine is bitter.', '药很苦。'),
  ('ko-food-basic-37', 'ko', 'basic', 'food', '배고프다', '배고프다', 'baegoppeuda', 'hungry', '饿', '배고파요.', 'I''m hungry.', '我饿了。'),
  ('ko-food-basic-38', 'ko', 'basic', 'food', '배부르다', '배부르다', 'baebureuda', 'full', '饱', '배불러요.', 'I''m full.', '我饱了。'),
  ('ko-food-basic-39', 'ko', 'basic', 'food', '목마르다', '목마르다', 'mongmareuda', 'thirsty', '渴', '목말라요.', 'I''m thirsty.', '我渴了。'),
  ('ko-food-basic-40', 'ko', 'basic', 'food', '요리', '요리', 'yori', 'cooking, dish', '菜，料理', '요리를 해요.', 'I cook.', '我做菜。'),
  ('ko-food-basic-41', 'ko', 'basic', 'food', '냉장고', '냉장고', 'naengjanggo', 'refrigerator', '冰箱', '냉장고에 넣어요.', 'I put it in the fridge.', '我放进冰箱。'),
  ('ko-food-basic-42', 'ko', 'basic', 'food', '숟가락', '숟가락', 'sutgarak', 'spoon', '勺子', '숟가락으로 먹어요.', 'I eat with a spoon.', '我用勺子吃。'),
  ('ko-food-basic-43', 'ko', 'basic', 'food', '젓가락', '젓가락', 'jeotgarak', 'chopsticks', '筷子', '젓가락을 사용해요.', 'I use chopsticks.', '我用筷子。'),
  ('ko-food-basic-44', 'ko', 'basic', 'food', '접시', '접시', 'jeopsi', 'plate', '盘子', '접시를 씻어요.', 'I wash the plate.', '我洗盘子。'),
  ('ko-food-basic-45', 'ko', 'basic', 'food', '컵', '컵', 'keop', 'cup', '杯子', '컵에 물을 따라요.', 'I pour water into the cup.', '我往杯子里倒水。'),
  ('ko-food-basic-46', 'ko', 'basic', 'food', '그릇', '그릇', 'geureut', 'bowl', '碗', '그릇에 담아요.', 'I put it in the bowl.', '我盛到碗里。'),
  ('ko-food-basic-47', 'ko', 'basic', 'food', '냄비', '냄비', 'naembi', 'pot', '锅', '냄비에 끓여요.', 'I boil it in a pot.', '我在锅里煮。'),
  ('ko-food-basic-48', 'ko', 'basic', 'food', '프라이팬', '프라이팬', 'peuraipan', 'frying pan', '平底锅', '프라이팬에 볶아요.', 'I stir-fry in a pan.', '我用平底锅炒。'),
  ('ko-food-basic-49', 'ko', 'basic', 'food', '칼', '칼', 'kal', 'knife', '刀', '칼로 잘라요.', 'I cut with a knife.', '我用刀切。'),
  ('ko-food-basic-50', 'ko', 'basic', 'food', '도시락', '도시락', 'dosirak', 'lunch box', '便当', '도시락을 싸요.', 'I pack a lunch box.', '我做便当。'),
  ('ko-food-basic-51', 'ko', 'basic', 'food', '배달', '배달', 'baedal', 'delivery', '外卖', '배달을 시켜요.', 'I order delivery.', '我叫外卖。'),
  ('ko-food-basic-52', 'ko', 'basic', 'food', '포장', '포장', 'pojang', 'takeout, packaging', '打包', '포장해 주세요.', 'Please pack it to go.', '请打包。'),
  ('ko-food-basic-53', 'ko', 'basic', 'food', '예약', '예약', 'yeyak', 'reservation', '预约', '식당을 예약해요.', 'I make a restaurant reservation.', '我预约餐厅。'),
  ('ko-food-basic-54', 'ko', 'basic', 'food', '계산', '계산', 'gyesan', 'bill, check', '结账', '계산해 주세요.', 'Please give me the check.', '请结账。'),
  ('ko-food-basic-55', 'ko', 'basic', 'food', '영수증', '영수증', 'yeongsujeung', 'receipt', '收据', '영수증 주세요.', 'Please give me the receipt.', '请给我收据。'),
  ('ko-food-basic-56', 'ko', 'basic', 'food', '할인', '할인', 'harin', 'discount', '打折', '할인이 있어요.', 'There is a discount.', '有打折。'),
  ('ko-food-basic-57', 'ko', 'basic', 'food', '서비스', '서비스', 'seobiseu', 'service, free extra', '赠送', '이건 서비스예요.', 'This is on the house.', '这个是赠送的。'),
  ('ko-food-basic-58', 'ko', 'basic', 'food', '밥솥', '밥솥', 'bapsot', 'rice cooker', '电饭锅', '밥솥으로 밥을 해요.', 'I cook rice with a rice cooker.', '我用电饭锅做饭。'),
  ('ko-food-basic-59', 'ko', 'basic', 'food', '전자레인지', '전자레인지', 'jeonjareinji', 'microwave', '微波炉', '전자레인지로 데워요.', 'I heat it in the microwave.', '我用微波炉加热。'),
  ('ko-food-basic-60', 'ko', 'basic', 'food', '오븐', '오븐', 'obeun', 'oven', '烤箱', '오븐에 구워요.', 'I bake it in the oven.', '我用烤箱烤。'),
  ('ko-food-basic-61', 'ko', 'basic', 'food', '된장', '된장', 'doenjang', 'soybean paste', '大酱', '된장찌개를 좋아해요.', 'I like soybean paste stew.', '我喜欢大酱汤。'),
  ('ko-food-basic-62', 'ko', 'basic', 'food', '고추장', '고추장', 'gochujang', 'red pepper paste', '辣椒酱', '고추장을 넣어요.', 'I add red pepper paste.', '我放辣椒酱。'),
  ('ko-food-basic-63', 'ko', 'basic', 'food', '참기름', '참기름', 'chamgireum', 'sesame oil', '芝麻油', '참기름을 뿌려요.', 'I drizzle sesame oil.', '我淋芝麻油。'),
  ('ko-food-basic-64', 'ko', 'basic', 'food', '식초', '식초', 'sikcho', 'vinegar', '醋', '식초를 넣어요.', 'I add vinegar.', '我放醋。'),
  ('ko-food-basic-65', 'ko', 'basic', 'food', '마늘', '마늘', 'maneul', 'garlic', '蒜', '마늘을 많이 넣어요.', 'I add a lot of garlic.', '我放很多蒜。'),
  ('ko-food-basic-66', 'ko', 'basic', 'food', '양파', '양파', 'yangpa', 'onion', '洋葱', '양파를 썰어요.', 'I slice the onion.', '我切洋葱。'),
  ('ko-food-basic-67', 'ko', 'basic', 'food', '당근', '당근', 'danggeun', 'carrot', '胡萝卜', '당근을 잘라요.', 'I cut the carrot.', '我切胡萝卜。'),
  ('ko-food-basic-68', 'ko', 'basic', 'food', '감자', '감자', 'gamja', 'potato', '土豆', '감자를 삶아요.', 'I boil potatoes.', '我煮土豆。'),
  ('ko-food-basic-69', 'ko', 'basic', 'food', '고구마', '고구마', 'goguma', 'sweet potato', '红薯', '고구마를 구워요.', 'I roast sweet potatoes.', '我烤红薯。'),
  ('ko-food-basic-70', 'ko', 'basic', 'food', '배추', '배추', 'baechu', 'Chinese cabbage', '白菜', '배추로 김치를 만들어요.', 'I make kimchi with cabbage.', '我用白菜做泡菜。'),
  ('ko-food-basic-71', 'ko', 'basic', 'food', '오이', '오이', 'oi', 'cucumber', '黄瓜', '오이를 먹어요.', 'I eat cucumber.', '我吃黄瓜。'),
  ('ko-food-basic-72', 'ko', 'basic', 'food', '토마토', '토마토', 'tomato', 'tomato', '番茄', '토마토가 맛있어요.', 'The tomato is delicious.', '番茄很好吃。'),
  ('ko-food-basic-73', 'ko', 'basic', 'food', '사과', '사과', 'sagwa', 'apple', '苹果', '사과를 깎아요.', 'I peel an apple.', '我削苹果。'),
  ('ko-food-basic-74', 'ko', 'basic', 'food', '바나나', '바나나', 'banana', 'banana', '香蕉', '바나나를 먹어요.', 'I eat a banana.', '我吃香蕉。'),
  ('ko-food-basic-75', 'ko', 'basic', 'food', '포도', '포도', 'podo', 'grape', '葡萄', '포도를 씻어요.', 'I wash the grapes.', '我洗葡萄。'),
  ('ko-food-basic-76', 'ko', 'basic', 'food', '딸기', '딸기', 'ttalgi', 'strawberry', '草莓', '딸기가 달아요.', 'The strawberry is sweet.', '草莓很甜。'),
  ('ko-food-basic-77', 'ko', 'basic', 'food', '수박', '수박', 'subak', 'watermelon', '西瓜', '여름에 수박을 먹어요.', 'I eat watermelon in summer.', '夏天吃西瓜。'),
  ('ko-food-basic-78', 'ko', 'basic', 'food', '귤', '귤', 'gyul', 'tangerine', '橘子', '귤을 까요.', 'I peel a tangerine.', '我剥橘子。'),
  ('ko-food-basic-79', 'ko', 'basic', 'food', '복숭아', '복숭아', 'boksunga', 'peach', '桃子', '복숭아가 맛있어요.', 'The peach is delicious.', '桃子很好吃。'),
  ('ko-food-basic-80', 'ko', 'basic', 'food', '소고기', '소고기', 'sogogi', 'beef', '牛肉', '소고기를 구워요.', 'I grill beef.', '我烤牛肉。'),
  ('ko-food-basic-81', 'ko', 'basic', 'food', '돼지고기', '돼지고기', 'dwaejigogi', 'pork', '猪肉', '돼지고기를 볶아요.', 'I stir-fry pork.', '我炒猪肉。'),
  ('ko-food-basic-82', 'ko', 'basic', 'food', '닭고기', '닭고기', 'dakgogi', 'chicken meat', '鸡肉', '닭고기를 삶아요.', 'I boil chicken.', '我煮鸡肉。'),
  ('ko-food-basic-83', 'ko', 'basic', 'food', '새우', '새우', 'saeu', 'shrimp', '虾', '새우를 좋아해요.', 'I like shrimp.', '我喜欢虾。'),
  ('ko-food-basic-84', 'ko', 'basic', 'food', '조개', '조개', 'jogae', 'clam, shellfish', '贝类', '조개를 넣어요.', 'I add clams.', '我放贝类。'),
  ('ko-food-basic-85', 'ko', 'basic', 'food', '오징어', '오징어', 'ojingeo', 'squid', '鱿鱼', '오징어를 볶아요.', 'I stir-fry squid.', '我炒鱿鱼。'),
  ('ko-food-basic-86', 'ko', 'basic', 'food', '두부', '두부', 'dubu', 'tofu', '豆腐', '두부를 넣어요.', 'I add tofu.', '我放豆腐。'),
  ('ko-food-basic-87', 'ko', 'basic', 'food', '콩', '콩', 'kong', 'bean, soybean', '豆', '콩을 먹어요.', 'I eat beans.', '我吃豆子。'),
  ('ko-food-basic-88', 'ko', 'basic', 'food', '국수', '국수', 'guksu', 'noodles', '面条', '국수를 좋아해요.', 'I like noodles.', '我喜欢面条。'),
  ('ko-food-basic-89', 'ko', 'basic', 'food', '만두', '만두', 'mandu', 'dumpling', '饺子', '만두를 먹어요.', 'I eat dumplings.', '我吃饺子。'),
  ('ko-food-basic-90', 'ko', 'basic', 'food', '볶음밥', '볶음밥', 'bokkeumbap', 'fried rice', '炒饭', '볶음밥을 만들어요.', 'I make fried rice.', '我做炒饭。'),
  ('ko-food-basic-91', 'ko', 'basic', 'food', '비빔밥', '비빔밥', 'bibimbap', 'bibimbap', '拌饭', '비빔밥을 먹어요.', 'I eat bibimbap.', '我吃拌饭。'),
  ('ko-food-basic-92', 'ko', 'basic', 'food', '김밥', '김밥', 'gimbap', 'kimbap, seaweed rice roll', '紫菜包饭', '김밥을 싸요.', 'I roll kimbap.', '我卷紫菜包饭。'),
  ('ko-food-basic-93', 'ko', 'basic', 'food', '떡볶이', '떡볶이', 'tteokbokki', 'spicy rice cake', '辣炒年糕', '떡볶이를 좋아해요.', 'I like tteokbokki.', '我喜欢辣炒年糕。'),
  ('ko-food-basic-94', 'ko', 'basic', 'food', '순두부', '순두부', 'sundubu', 'soft tofu', '嫩豆腐', '순두부찌개를 먹어요.', 'I eat soft tofu stew.', '我吃嫩豆腐汤。'),
  ('ko-food-basic-95', 'ko', 'basic', 'food', '삼겹살', '삼겹살', 'samgyeopsal', 'pork belly', '五花肉', '삼겹살을 구워요.', 'I grill pork belly.', '我烤五花肉。'),
  ('ko-food-basic-96', 'ko', 'basic', 'food', '불고기', '불고기', 'bulgogi', 'bulgogi', '烤肉', '불고기가 맛있어요.', 'The bulgogi is delicious.', '烤肉很好吃。'),
  ('ko-food-basic-97', 'ko', 'basic', 'food', '갈비', '갈비', 'galbi', 'ribs', '排骨', '갈비를 먹어요.', 'I eat ribs.', '我吃排骨。'),
  ('ko-food-basic-98', 'ko', 'basic', 'food', '냉면', '냉면', 'naengmyeon', 'cold noodles', '冷面', '여름에 냉면을 먹어요.', 'I eat cold noodles in summer.', '夏天吃冷面。'),
  ('ko-food-basic-99', 'ko', 'basic', 'food', '잡채', '잡채', 'japchae', 'glass noodles', '杂菜', '잡채를 만들어요.', 'I make japchae.', '我做杂菜。'),
  ('ko-food-basic-100', 'ko', 'basic', 'food', '전', '전', 'jeon', 'pancake, fritter', '煎饼', '전을 부쳐요.', 'I fry pancakes.', '我煎饼。'),
  ('ko-food-basic-101', 'ko', 'basic', 'food', '죽', '죽', 'juk', 'porridge', '粥', '죽을 끓여요.', 'I make porridge.', '我熬粥。'),
  ('ko-food-basic-102', 'ko', 'basic', 'food', '해물', '해물', 'haemul', 'seafood', '海鲜', '해물을 좋아해요.', 'I like seafood.', '我喜欢海鲜。'),
  ('ko-food-basic-103', 'ko', 'basic', 'food', '김', '김', 'gim', 'seaweed', '海苔', '김을 먹어요.', 'I eat seaweed.', '我吃海苔。'),
  ('ko-food-basic-104', 'ko', 'basic', 'food', '미역', '미역', 'miyeok', 'sea mustard, wakame', '裙带菜', '미역국을 끓여요.', 'I make seaweed soup.', '我做裙带菜汤。'),
  ('ko-food-basic-105', 'ko', 'basic', 'food', '버섯', '버섯', 'beoseot', 'mushroom', '蘑菇', '버섯을 넣어요.', 'I add mushrooms.', '我放蘑菇。'),
  ('ko-food-basic-106', 'ko', 'basic', 'food', '시금치', '시금치', 'sigeumchi', 'spinach', '菠菜', '시금치를 볶아요.', 'I stir-fry spinach.', '我炒菠菜。'),
  ('ko-food-basic-107', 'ko', 'basic', 'food', '호박', '호박', 'hobak', 'pumpkin, zucchini', '南瓜', '호박을 넣어요.', 'I add pumpkin.', '我放南瓜。'),
  ('ko-food-basic-108', 'ko', 'basic', 'food', '파', '파', 'pa', 'green onion', '葱', '파를 썰어요.', 'I chop green onions.', '我切葱。'),
  ('ko-food-basic-109', 'ko', 'basic', 'food', '고추', '고추', 'gochu', 'chili pepper', '辣椒', '고추가 매워요.', 'The chili is spicy.', '辣椒很辣。'),
  ('ko-food-basic-110', 'ko', 'basic', 'food', '생강', '생강', 'saenggang', 'ginger', '姜', '생강을 넣어요.', 'I add ginger.', '我放姜。'),
  ('ko-food-basic-111', 'ko', 'basic', 'food', '깨', '깨', 'kkae', 'sesame seeds', '芝麻', '깨를 뿌려요.', 'I sprinkle sesame seeds.', '我撒芝麻。'),
  ('ko-food-basic-112', 'ko', 'basic', 'food', '식빵', '식빵', 'sikppang', 'sliced bread', '吐司', '식빵을 구워요.', 'I toast the bread.', '我烤吐司。'),
  ('ko-food-basic-113', 'ko', 'basic', 'food', '케이크', '케이크', 'keikeu', 'cake', '蛋糕', '케이크를 먹어요.', 'I eat cake.', '我吃蛋糕。'),
  ('ko-food-basic-114', 'ko', 'basic', 'food', '아이스크림', '아이스크림', 'aiseukeurim', 'ice cream', '冰淇淋', '아이스크림을 먹어요.', 'I eat ice cream.', '我吃冰淇淋。'),
  ('ko-food-basic-115', 'ko', 'basic', 'food', '초콜릿', '초콜릿', 'chokollit', 'chocolate', '巧克力', '초콜릿을 좋아해요.', 'I like chocolate.', '我喜欢巧克力。'),
  ('ko-food-basic-116', 'ko', 'basic', 'food', '주스', '주스', 'juseu', 'juice', '果汁', '주스를 마셔요.', 'I drink juice.', '我喝果汁。'),
  ('ko-food-basic-117', 'ko', 'basic', 'food', '맥주', '맥주', 'maekju', 'beer', '啤酒', '맥주를 마셔요.', 'I drink beer.', '我喝啤酒。'),
  ('ko-food-basic-118', 'ko', 'basic', 'food', '소주', '소주', 'soju', 'soju', '烧酒', '소주를 마셔요.', 'I drink soju.', '我喝烧酒。'),
  ('ko-food-basic-119', 'ko', 'basic', 'food', '와인', '와인', 'wain', 'wine', '葡萄酒', '와인을 마셔요.', 'I drink wine.', '我喝葡萄酒。'),
  ('ko-food-basic-120', 'ko', 'basic', 'food', '탄산수', '탄산수', 'tansansu', 'sparkling water', '气泡水', '탄산수를 마셔요.', 'I drink sparkling water.', '我喝气泡水。'),
  ('ko-food-basic-121', 'ko', 'basic', 'food', '녹차', '녹차', 'nokcha', 'green tea', '绿茶', '녹차를 마셔요.', 'I drink green tea.', '我喝绿茶。'),
  ('ko-food-basic-122', 'ko', 'basic', 'food', '홍차', '홍차', 'hongcha', 'black tea', '红茶', '홍차를 마셔요.', 'I drink black tea.', '我喝红茶。'),
  ('ko-food-basic-123', 'ko', 'basic', 'food', '간식', '간식', 'gansik', 'snack', '零食', '간식을 먹어요.', 'I eat a snack.', '我吃零食。'),
  ('ko-food-basic-124', 'ko', 'basic', 'food', '야식', '야식', 'yasik', 'late night snack', '夜宵', '야식을 먹어요.', 'I eat a late night snack.', '我吃夜宵。'),
  ('ko-food-basic-125', 'ko', 'basic', 'food', '카페', '카페', 'kape', 'cafe', '咖啡厅', '카페에 가요.', 'I go to a cafe.', '我去咖啡厅。'),
  ('ko-food-basic-126', 'ko', 'basic', 'food', '편의점', '편의점', 'pyeonuijeom', 'convenience store', '便利店', '편의점에서 사요.', 'I buy it at a convenience store.', '我在便利店买。'),
  ('ko-food-basic-127', 'ko', 'basic', 'food', '마트', '마트', 'mateu', 'mart, supermarket', '超市', '마트에서 장을 봐요.', 'I grocery shop at the mart.', '我在超市买菜。'),
  ('ko-food-basic-128', 'ko', 'basic', 'food', '시장', '시장', 'sijang', 'market', '市场', '시장에 가요.', 'I go to the market.', '我去市场。'),
  ('ko-food-basic-129', 'ko', 'basic', 'food', '장보기', '장보기', 'jangbogi', 'grocery shopping', '买菜', '장보기를 해요.', 'I go grocery shopping.', '我去买菜。'),
  ('ko-food-basic-130', 'ko', 'basic', 'food', '굽다', '굽다', 'gupda', 'to grill, bake', '烤', '고기를 구워요.', 'I grill meat.', '我烤肉。'),
  ('ko-food-basic-131', 'ko', 'basic', 'food', '끓이다', '끓이다', 'kkeurida', 'to boil', '煮', '물을 끓여요.', 'I boil water.', '我烧水。'),
  ('ko-food-basic-132', 'ko', 'basic', 'food', '볶다', '볶다', 'bokda', 'to stir-fry', '炒', '야채를 볶아요.', 'I stir-fry vegetables.', '我炒菜。'),
  ('ko-food-basic-133', 'ko', 'basic', 'food', '튀기다', '튀기다', 'twigida', 'to deep-fry', '炸', '감자를 튀겨요.', 'I deep-fry potatoes.', '我炸土豆。'),
  ('ko-food-basic-134', 'ko', 'basic', 'food', '찌다', '찌다', 'jjida', 'to steam', '蒸', '만두를 쪄요.', 'I steam dumplings.', '我蒸饺子。'),
  ('ko-food-basic-135', 'ko', 'basic', 'food', '썰다', '썰다', 'sseolda', 'to slice, chop', '切', '고기를 썰어요.', 'I slice the meat.', '我切肉。'),
  ('ko-food-basic-136', 'ko', 'basic', 'food', '씻다', '씻다', 'ssitda', 'to wash', '洗', '과일을 씻어요.', 'I wash the fruit.', '我洗水果。'),
  ('ko-food-basic-137', 'ko', 'basic', 'food', '섞다', '섞다', 'seokda', 'to mix', '混合', '재료를 섞어요.', 'I mix the ingredients.', '我混合材料。'),
  ('ko-food-basic-138', 'ko', 'basic', 'food', '담다', '담다', 'damda', 'to put in, serve', '盛', '밥을 담아요.', 'I serve the rice.', '我盛饭。'),
  ('ko-food-basic-139', 'ko', 'basic', 'food', '데우다', '데우다', 'deuda', 'to heat up', '加热', '음식을 데워요.', 'I heat up the food.', '我加热食物。'),
  ('ko-food-basic-140', 'ko', 'basic', 'food', '식히다', '식히다', 'sikhida', 'to cool down', '冷却', '음식을 식혀요.', 'I cool down the food.', '我让食物冷却。'),
  ('ko-food-basic-141', 'ko', 'basic', 'food', '맛있다', '맛있다', 'masitda', 'delicious', '好吃', '정말 맛있어요.', 'It''s really delicious.', '真好吃。'),
  ('ko-food-basic-142', 'ko', 'basic', 'food', '맛없다', '맛없다', 'maseopda', 'not tasty', '不好吃', '좀 맛없어요.', 'It''s a bit bland.', '有点不好吃。'),
  ('ko-food-basic-143', 'ko', 'basic', 'food', '싱겁다', '싱겁다', 'singeopda', 'bland, tasteless', '淡', '좀 싱거워요.', 'It''s a bit bland.', '有点淡。'),
  ('ko-food-basic-144', 'ko', 'basic', 'food', '느끼하다', '느끼하다', 'neukkihada', 'greasy, oily', '油腻', '좀 느끼해요.', 'It''s a bit greasy.', '有点油腻。'),
  ('ko-food-basic-145', 'ko', 'basic', 'food', '신선하다', '신선하다', 'sinseonhada', 'fresh', '新鲜', '재료가 신선해요.', 'The ingredients are fresh.', '材料很新鲜。'),
  ('ko-food-basic-146', 'ko', 'basic', 'food', '익다', '익다', 'ikda', 'to be cooked, ripe', '熟', '고기가 익었어요.', 'The meat is cooked.', '肉熟了。'),
  ('ko-food-basic-147', 'ko', 'basic', 'food', '날것', '날것', 'nalgeot', 'raw', '生的', '날것으로 먹어요.', 'I eat it raw.', '我生吃。'),
  ('ko-food-basic-148', 'ko', 'basic', 'food', '한식', '한식', 'hansik', 'Korean food', '韩餐', '한식을 좋아해요.', 'I like Korean food.', '我喜欢韩餐。'),
  ('ko-food-basic-149', 'ko', 'basic', 'food', '양식', '양식', 'yangsik', 'Western food', '西餐', '양식을 먹어요.', 'I eat Western food.', '我吃西餐。'),
  ('ko-food-basic-150', 'ko', 'basic', 'food', '중식', '중식', 'jungsik', 'Chinese food', '中餐', '중식을 먹어요.', 'I eat Chinese food.', '我吃中餐。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
