-- Expand ja-anime-intermediate to 150 curated entries (14-150)
-- Topic: anime/drama vocabulary for intermediate Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-anime-intermediate-14', 'ja', 'intermediate', 'anime/drama', 'アニメ', 'アニメ', 'anime', 'anime, animation', '动画，动漫', 'アニメを毎週見ます。', 'I watch anime every week.', '我每周看动画。'),
  ('ja-anime-intermediate-15', 'ja', 'intermediate', 'anime/drama', '原作', 'げんさく', 'gensaku', 'original work, source material', '原作，原著', '原作を読みました。', 'I read the original work.', '我读了原作。'),
  ('ja-anime-intermediate-16', 'ja', 'intermediate', 'anime/drama', '漫画', 'まんが', 'manga', 'manga, comic', '漫画', '漫画が好きです。', 'I like manga.', '我喜欢漫画。'),
  ('ja-anime-intermediate-17', 'ja', 'intermediate', 'anime/drama', '連載', 'れんさい', 'rensai', 'serialization', '连载', '連載が続いています。', 'The serialization continues.', '连载在继续。'),
  ('ja-anime-intermediate-18', 'ja', 'intermediate', 'anime/drama', '作画', 'さくが', 'sakuga', 'animation quality, drawing', '作画，画面', '作画がきれいです。', 'The animation is beautiful.', '作画很漂亮。'),
  ('ja-anime-intermediate-19', 'ja', 'intermediate', 'anime/drama', '放送', 'ほうそう', 'hoso', 'broadcast, airing', '播出，放送', '来週から放送します。', 'It will air from next week.', '下周开始播出。'),
  ('ja-anime-intermediate-20', 'ja', 'intermediate', 'anime/drama', '再放送', 'さいほうそう', 'saihoso', 'rerun, rebroadcast', '重播', '再放送を見ました。', 'I watched the rerun.', '我看了重播。'),
  ('ja-anime-intermediate-21', 'ja', 'intermediate', 'anime/drama', '予告', 'よこく', 'yokoku', 'preview, trailer', '预告', '予告を見ました。', 'I watched the preview.', '我看了预告。'),
  ('ja-anime-intermediate-22', 'ja', 'intermediate', 'anime/drama', '伏線', 'ふくせん', 'fukusen', 'foreshadowing', '伏笔', '伏線が回収されました。', 'The foreshadowing was resolved.', '伏笔被回收了。'),
  ('ja-anime-intermediate-23', 'ja', 'intermediate', 'anime/drama', '主題歌', 'しゅだいか', 'shudaika', 'theme song', '主题曲', '主題歌が好きです。', 'I like the theme song.', '我喜欢主题曲。'),
  ('ja-anime-intermediate-24', 'ja', 'intermediate', 'anime/drama', '挿入歌', 'そうにゅうか', 'sonyuka', 'insert song', '插曲', '挿入歌が流れました。', 'The insert song played.', '插曲响了。'),
  ('ja-anime-intermediate-25', 'ja', 'intermediate', 'anime/drama', '視聴率', 'しちょうりつ', 'shichouritsu', 'viewership rating', '收视率', '視聴率が高いです。', 'The ratings are high.', '收视率很高。'),
  ('ja-anime-intermediate-26', 'ja', 'intermediate', 'anime/drama', '感動', 'かんどう', 'kando', 'being moved, touched', '感动', '感動しました。', 'I was moved.', '我被感动了。'),
  ('ja-anime-intermediate-27', 'ja', 'intermediate', 'anime/drama', '泣ける', 'なける', 'nakeru', 'tear-jerking, moving to tears', '催泪的', '泣ける話でした。', 'It was a tear-jerking story.', '这是一个催泪的故事。'),
  ('ja-anime-intermediate-28', 'ja', 'intermediate', 'anime/drama', '名作', 'めいさく', 'meisaku', 'masterpiece', '名作，杰作', 'これは名作です。', 'This is a masterpiece.', '这是名作。'),
  ('ja-anime-intermediate-29', 'ja', 'intermediate', 'anime/drama', '名場面', 'めいばめん', 'meibamen', 'famous scene', '名场面', '名場面を覚えています。', 'I remember the famous scene.', '我记得那个名场面。'),
  ('ja-anime-intermediate-30', 'ja', 'intermediate', 'anime/drama', '名台詞', 'めいぜりふ', 'meizerifu', 'famous line, quote', '名台词', '名台詞を覚えました。', 'I memorized the famous line.', '我记住了名台词。'),
  ('ja-anime-intermediate-31', 'ja', 'intermediate', 'anime/drama', '配信', 'はいしん', 'haishin', 'streaming, distribution', '播放，配信', '配信で見ます。', 'I watch via streaming.', '我通过网络播放看。'),
  ('ja-anime-intermediate-32', 'ja', 'intermediate', 'anime/drama', '続編', 'ぞくへん', 'zokuhen', 'sequel', '续集', '続編が楽しみです。', 'I look forward to the sequel.', '我期待续集。'),
  ('ja-anime-intermediate-33', 'ja', 'intermediate', 'anime/drama', '前編', 'ぜんぺん', 'zenpen', 'first part', '前篇', '前編を見ました。', 'I watched the first part.', '我看了前篇。'),
  ('ja-anime-intermediate-34', 'ja', 'intermediate', 'anime/drama', '後編', 'こうへん', 'kohen', 'second part', '后篇', '後編も見たいです。', 'I want to watch the second part too.', '我也想看后篇。'),
  ('ja-anime-intermediate-35', 'ja', 'intermediate', 'anime/drama', '総集編', 'そうしゅうへん', 'soshuhen', 'recap episode', '总集篇', '総集編を放送しました。', 'They aired a recap episode.', '播出了总集篇。'),
  ('ja-anime-intermediate-36', 'ja', 'intermediate', 'anime/drama', '劇場版', 'げきじょうばん', 'gekijoban', 'theatrical version, movie', '剧场版', '劇場版を映画館で見ました。', 'I watched the movie in theaters.', '我在电影院看了剧场版。'),
  ('ja-anime-intermediate-37', 'ja', 'intermediate', 'anime/drama', 'シーズン', 'シーズン', 'shiizun', 'season', '季，第几季', '新しいシーズンが始まります。', 'A new season begins.', '新一季开始了。'),
  ('ja-anime-intermediate-38', 'ja', 'intermediate', 'anime/drama', '悪役', 'あくやく', 'akuyaku', 'villain', '反派', '悪役が魅力的です。', 'The villain is charming.', '反派很有魅力。'),
  ('ja-anime-intermediate-39', 'ja', 'intermediate', 'anime/drama', 'ヒロイン', 'ヒロイン', 'hiroin', 'heroine', '女主角', 'ヒロインが強いです。', 'The heroine is strong.', '女主角很强。'),
  ('ja-anime-intermediate-40', 'ja', 'intermediate', 'anime/drama', '脇役', 'わきやく', 'wakiyaku', 'supporting role', '配角', '脇役も人気です。', 'The supporting characters are popular too.', '配角也很受欢迎。'),
  ('ja-anime-intermediate-41', 'ja', 'intermediate', 'anime/drama', '台詞', 'せりふ', 'serifu', 'dialogue, line', '台词', '台詞が自然です。', 'The dialogue is natural.', '台词很自然。'),
  ('ja-anime-intermediate-42', 'ja', 'intermediate', 'anime/drama', '吹き替え', 'ふきかえ', 'fukikae', 'dubbing', '配音', '吹き替え版を見ます。', 'I watch the dubbed version.', '我看配音版。'),
  ('ja-anime-intermediate-43', 'ja', 'intermediate', 'anime/drama', 'オープニング', 'オープニング', 'oopuningu', 'opening', '片头', 'オープニングが好きです。', 'I like the opening.', '我喜欢片头。'),
  ('ja-anime-intermediate-44', 'ja', 'intermediate', 'anime/drama', 'エンディング', 'エンディング', 'endingu', 'ending', '片尾', 'エンディングも見ます。', 'I also watch the ending.', '我也看片尾。'),
  ('ja-anime-intermediate-45', 'ja', 'intermediate', 'anime/drama', '特撮', 'とくさつ', 'tokusatsu', 'special effects, tokusatsu', '特摄', '特撮が好きです。', 'I like tokusatsu.', '我喜欢特摄。'),
  ('ja-anime-intermediate-46', 'ja', 'intermediate', 'anime/drama', '実写', 'じっしゃ', 'jissha', 'live action', '真人版', '実写版が公開されます。', 'The live-action version will be released.', '真人版将上映。'),
  ('ja-anime-intermediate-47', 'ja', 'intermediate', 'anime/drama', '制作', 'せいさく', 'seisaku', 'production', '制作', '制作に時間がかかります。', 'Production takes time.', '制作需要时间。'),
  ('ja-anime-intermediate-48', 'ja', 'intermediate', 'anime/drama', 'スタジオ', 'スタジオ', 'sutajio', 'studio', '工作室，制作公司', 'このスタジオの作品が好きです。', 'I like this studio''s works.', '我喜欢这个工作室的作品。'),
  ('ja-anime-intermediate-49', 'ja', 'intermediate', 'anime/drama', '作品', 'さくひん', 'sakuhin', 'work, piece', '作品', 'この作品は人気です。', 'This work is popular.', '这部作品很受欢迎。'),
  ('ja-anime-intermediate-50', 'ja', 'intermediate', 'anime/drama', 'ジャンル', 'ジャンル', 'janru', 'genre', '类型', 'どのジャンルが好きですか。', 'What genre do you like?', '你喜欢什么类型？'),
  ('ja-anime-intermediate-51', 'ja', 'intermediate', 'anime/drama', 'コメディ', 'コメディ', 'komedi', 'comedy', '喜剧', 'コメディが好きです。', 'I like comedy.', '我喜欢喜剧。'),
  ('ja-anime-intermediate-52', 'ja', 'intermediate', 'anime/drama', 'ホラー', 'ホラー', 'horaa', 'horror', '恐怖', 'ホラーは苦手です。', 'I''m not good with horror.', '我不太能看恐怖片。'),
  ('ja-anime-intermediate-53', 'ja', 'intermediate', 'anime/drama', 'ファンタジー', 'ファンタジー', 'fantajii', 'fantasy', '奇幻', 'ファンタジーが好きです。', 'I like fantasy.', '我喜欢奇幻类。'),
  ('ja-anime-intermediate-54', 'ja', 'intermediate', 'anime/drama', '恋愛', 'れんあい', 'renai', 'romance', '恋爱', '恋愛ドラマを見ます。', 'I watch romance dramas.', '我看恋爱剧。'),
  ('ja-anime-intermediate-55', 'ja', 'intermediate', 'anime/drama', '冒険', 'ぼうけん', 'bouken', 'adventure', '冒险', '冒険アニメが好きです。', 'I like adventure anime.', '我喜欢冒险动画。'),
  ('ja-anime-intermediate-56', 'ja', 'intermediate', 'anime/drama', 'バトル', 'バトル', 'batoru', 'battle', '战斗', 'バトルシーンが最高です。', 'The battle scene is amazing.', '战斗场面太棒了。'),
  ('ja-anime-intermediate-57', 'ja', 'intermediate', 'anime/drama', '日常', 'にちじょう', 'nichijo', 'slice of life, daily life', '日常', '日常系アニメを見ます。', 'I watch slice-of-life anime.', '我看日常系动画。'),
  ('ja-anime-intermediate-58', 'ja', 'intermediate', 'anime/drama', '推理', 'すいり', 'suiri', 'mystery, detective', '推理', '推理ドラマが面白いです。', 'Mystery dramas are interesting.', '推理剧很有趣。'),
  ('ja-anime-intermediate-59', 'ja', 'intermediate', 'anime/drama', 'SF', 'エスエフ', 'esu-efu', 'science fiction', '科幻', 'SF映画を見ました。', 'I watched a sci-fi movie.', '我看了一部科幻电影。'),
  ('ja-anime-intermediate-60', 'ja', 'intermediate', 'anime/drama', '時代劇', 'じだいげき', 'jidaigeki', 'period drama', '古装剧', '時代劇が好きです。', 'I like period dramas.', '我喜欢古装剧。'),
  ('ja-anime-intermediate-61', 'ja', 'intermediate', 'anime/drama', '感想', 'かんそう', 'kanso', 'impression, review', '感想，观后感', '感想を書きます。', 'I write my impressions.', '我写感想。'),
  ('ja-anime-intermediate-62', 'ja', 'intermediate', 'anime/drama', 'ネタバレ', 'ネタバレ', 'netabare', 'spoiler', '剧透', 'ネタバレは嫌です。', 'I hate spoilers.', '我讨厌剧透。'),
  ('ja-anime-intermediate-63', 'ja', 'intermediate', 'anime/drama', 'おすすめ', 'おすすめ', 'osusume', 'recommendation', '推荐', 'おすすめのアニメはありますか。', 'Do you have any anime recommendations?', '有推荐的动画吗？'),
  ('ja-anime-intermediate-64', 'ja', 'intermediate', 'anime/drama', '一気見', 'いっきみ', 'ikkimi', 'binge-watching', '一口气看完', '休みに一気見しました。', 'I binge-watched it during vacation.', '假期一口气看完了。'),
  ('ja-anime-intermediate-65', 'ja', 'intermediate', 'anime/drama', '録画', 'ろくが', 'rokuga', 'recording', '录像', '録画しておきます。', 'I''ll record it.', '我先录下来。'),
  ('ja-anime-intermediate-66', 'ja', 'intermediate', 'anime/drama', '打ち切り', 'うちきり', 'uchikiri', 'cancellation', '腰斩，停播', '打ち切りになりました。', 'It was cancelled.', '被腰斩了。'),
  ('ja-anime-intermediate-67', 'ja', 'intermediate', 'anime/drama', '完結', 'かんけつ', 'kanketsu', 'completion, conclusion', '完结', '物語が完結しました。', 'The story was completed.', '故事完结了。'),
  ('ja-anime-intermediate-68', 'ja', 'intermediate', 'anime/drama', '未完', 'みかん', 'mikan', 'unfinished, incomplete', '未完', 'まだ未完です。', 'It''s still unfinished.', '还没完结。'),
  ('ja-anime-intermediate-69', 'ja', 'intermediate', 'anime/drama', '人気', 'にんき', 'ninki', 'popularity', '人气', '人気が高いです。', 'It''s very popular.', '人气很高。'),
  ('ja-anime-intermediate-70', 'ja', 'intermediate', 'anime/drama', '話題', 'わだい', 'wadai', 'hot topic, trending', '话题', '話題の作品です。', 'It''s a trending work.', '这是热门话题作品。'),
  ('ja-anime-intermediate-71', 'ja', 'intermediate', 'anime/drama', '評判', 'ひょうばん', 'hyoban', 'reputation, reviews', '评价，口碑', '評判がいいです。', 'It has good reviews.', '口碑很好。'),
  ('ja-anime-intermediate-72', 'ja', 'intermediate', 'anime/drama', '批評', 'ひひょう', 'hihyo', 'criticism, critique', '批评', '批評を読みます。', 'I read the critique.', '我看批评文章。'),
  ('ja-anime-intermediate-73', 'ja', 'intermediate', 'anime/drama', 'ファン', 'ファン', 'fan', 'fan', '粉丝', 'ファンが多いです。', 'It has many fans.', '粉丝很多。'),
  ('ja-anime-intermediate-74', 'ja', 'intermediate', 'anime/drama', 'オタク', 'オタク', 'otaku', 'otaku, enthusiast', '宅，狂热爱好者', '私はアニメオタクです。', 'I''m an anime otaku.', '我是动画宅。'),
  ('ja-anime-intermediate-75', 'ja', 'intermediate', 'anime/drama', 'コスプレ', 'コスプレ', 'kosupure', 'cosplay', 'cosplay，角色扮演', 'コスプレをしました。', 'I did cosplay.', '我cos了。'),
  ('ja-anime-intermediate-76', 'ja', 'intermediate', 'anime/drama', '同人', 'どうじん', 'doujin', 'fan-made, doujin', '同人', '同人誌を買いました。', 'I bought a doujinshi.', '我买了同人志。'),
  ('ja-anime-intermediate-77', 'ja', 'intermediate', 'anime/drama', 'グッズ', 'グッズ', 'guzzu', 'merchandise, goods', '周边', 'グッズを集めています。', 'I collect merchandise.', '我在收集周边。'),
  ('ja-anime-intermediate-78', 'ja', 'intermediate', 'anime/drama', 'フィギュア', 'フィギュア', 'figyua', 'figure, figurine', '手办', 'フィギュアを買いました。', 'I bought a figure.', '我买了手办。'),
  ('ja-anime-intermediate-79', 'ja', 'intermediate', 'anime/drama', '聖地巡礼', 'せいちじゅんれい', 'seichijunrei', 'anime pilgrimage', '圣地巡礼', '聖地巡礼に行きます。', 'I''m going on an anime pilgrimage.', '我去圣地巡礼。'),
  ('ja-anime-intermediate-80', 'ja', 'intermediate', 'anime/drama', 'イベント', 'イベント', 'ibento', 'event', '活动', 'アニメイベントに行きます。', 'I''m going to an anime event.', '我去动漫活动。'),
  ('ja-anime-intermediate-81', 'ja', 'intermediate', 'anime/drama', '声', 'こえ', 'koe', 'voice', '声音', '声がいいです。', 'The voice is nice.', '声音很好听。'),
  ('ja-anime-intermediate-82', 'ja', 'intermediate', 'anime/drama', '演技', 'えんぎ', 'engi', 'acting, performance', '演技', '演技が上手です。', 'The acting is skillful.', '演技很好。'),
  ('ja-anime-intermediate-83', 'ja', 'intermediate', 'anime/drama', '原画', 'げんが', 'genga', 'key animation', '原画', '原画がすごいです。', 'The key animation is amazing.', '原画太厉害了。'),
  ('ja-anime-intermediate-84', 'ja', 'intermediate', 'anime/drama', '動画', 'どうが', 'douga', 'in-between animation, video', '动画，视频', '動画を見ます。', 'I watch the video.', '我看视频。'),
  ('ja-anime-intermediate-85', 'ja', 'intermediate', 'anime/drama', '背景', 'はいけい', 'haikei', 'background', '背景', '背景が美しいです。', 'The background is beautiful.', '背景很美。'),
  ('ja-anime-intermediate-86', 'ja', 'intermediate', 'anime/drama', '音楽', 'おんがく', 'ongaku', 'music, soundtrack', '音乐', '音楽がいいです。', 'The music is good.', '音乐很好听。'),
  ('ja-anime-intermediate-87', 'ja', 'intermediate', 'anime/drama', '効果音', 'こうかおん', 'koukaon', 'sound effect', '音效', '効果音がリアルです。', 'The sound effects are realistic.', '音效很逼真。'),
  ('ja-anime-intermediate-88', 'ja', 'intermediate', 'anime/drama', '作曲', 'さっきょく', 'sakkyoku', 'composition, composing', '作曲', '作曲家が有名です。', 'The composer is famous.', '作曲家很有名。'),
  ('ja-anime-intermediate-89', 'ja', 'intermediate', 'anime/drama', '歌手', 'かしゅ', 'kashu', 'singer', '歌手', '歌手が主題歌を歌います。', 'The singer performs the theme song.', '歌手演唱主题曲。'),
  ('ja-anime-intermediate-90', 'ja', 'intermediate', 'anime/drama', '世界観', 'せかいかん', 'sekaikan', 'worldview, world-building', '世界观', '世界観が独特です。', 'The world-building is unique.', '世界观很独特。'),
  ('ja-anime-intermediate-91', 'ja', 'intermediate', 'anime/drama', '設定', 'せってい', 'settei', 'setting, premise', '设定', '設定が面白いです。', 'The premise is interesting.', '设定很有意思。'),
  ('ja-anime-intermediate-92', 'ja', 'intermediate', 'anime/drama', 'キャラクター', 'キャラクター', 'kyarakutaa', 'character', '角色', 'キャラクターが魅力的です。', 'The characters are attractive.', '角色很有魅力。'),
  ('ja-anime-intermediate-93', 'ja', 'intermediate', 'anime/drama', '推し', 'おし', 'oshi', 'favorite character, bias', '推，最喜欢的角色', '推しは誰ですか。', 'Who is your favorite character?', '你推谁？'),
  ('ja-anime-intermediate-94', 'ja', 'intermediate', 'anime/drama', '萌え', 'もえ', 'moe', 'moe, cute appeal', '萌', '萌えキャラが好きです。', 'I like moe characters.', '我喜欢萌系角色。'),
  ('ja-anime-intermediate-95', 'ja', 'intermediate', 'anime/drama', '熱血', 'ねっけつ', 'nekketsu', 'hot-blooded, passionate', '热血', '熱血アニメが好きです。', 'I like hot-blooded anime.', '我喜欢热血动画。'),
  ('ja-anime-intermediate-96', 'ja', 'intermediate', 'anime/drama', '鬱', 'うつ', 'utsu', 'depressing, dark', '致郁', '鬱展開が辛いです。', 'The dark development is painful.', '致郁展开很难受。'),
  ('ja-anime-intermediate-97', 'ja', 'intermediate', 'anime/drama', '伝説', 'でんせつ', 'densetsu', 'legend, legendary', '传说', '伝説的な作品です。', 'It''s a legendary work.', '这是传说级的作品。'),
  ('ja-anime-intermediate-98', 'ja', 'intermediate', 'anime/drama', '制作委員会', 'せいさくいいんかい', 'seisakuiinkai', 'production committee', '制作委员会', '制作委員会が発表しました。', 'The production committee announced it.', '制作委员会公布了。'),
  ('ja-anime-intermediate-99', 'ja', 'intermediate', 'anime/drama', 'クール', 'クール', 'kuuru', 'cour, broadcast quarter', '季度', '来クールの新作が楽しみです。', 'I look forward to next cour''s new shows.', '我期待下一季度的新番。'),
  ('ja-anime-intermediate-100', 'ja', 'intermediate', 'anime/drama', '新番', 'しんばん', 'shinban', 'new anime season', '新番', '新番をチェックします。', 'I check the new anime.', '我查看新番。'),
  ('ja-anime-intermediate-101', 'ja', 'intermediate', 'anime/drama', '覇権', 'はけん', 'haken', 'top-rated, dominant', '霸权', '今期の覇権アニメは何ですか。', 'What''s the top anime this season?', '这一季的霸权动画是哪部？'),
  ('ja-anime-intermediate-102', 'ja', 'intermediate', 'anime/drama', '作者', 'さくしゃ', 'sakusha', 'author, creator', '作者', '作者のインタビューを読みました。', 'I read the author''s interview.', '我读了作者的采访。'),
  ('ja-anime-intermediate-103', 'ja', 'intermediate', 'anime/drama', '画風', 'がふう', 'gafu', 'art style', '画风', '画風が独特です。', 'The art style is unique.', '画风很独特。'),
  ('ja-anime-intermediate-104', 'ja', 'intermediate', 'anime/drama', '回想', 'かいそう', 'kaiso', 'flashback', '回忆，闪回', '回想シーンが多いです。', 'There are many flashback scenes.', '回忆场景很多。'),
  ('ja-anime-intermediate-105', 'ja', 'intermediate', 'anime/drama', 'クリフハンガー', 'クリフハンガー', 'kurifuhangaa', 'cliffhanger', '悬念', 'クリフハンガーで終わりました。', 'It ended on a cliffhanger.', '以悬念结尾了。'),
  ('ja-anime-intermediate-106', 'ja', 'intermediate', 'anime/drama', '番外編', 'ばんがいへん', 'bangaihen', 'side story, extra episode', '番外篇', '番外編を見ました。', 'I watched the side story.', '我看了番外篇。'),
  ('ja-anime-intermediate-107', 'ja', 'intermediate', 'anime/drama', 'OVA', 'オーブイエー', 'oobui-ee', 'OVA, original video animation', 'OVA', 'OVAを見ました。', 'I watched the OVA.', '我看了OVA。'),
  ('ja-anime-intermediate-108', 'ja', 'intermediate', 'anime/drama', 'リメイク', 'リメイク', 'rimeiku', 'remake', '翻拍，重制', 'リメイク版が出ます。', 'A remake is coming out.', '重制版要出了。'),
  ('ja-anime-intermediate-109', 'ja', 'intermediate', 'anime/drama', 'スピンオフ', 'スピンオフ', 'supinnofu', 'spin-off', '衍生作品', 'スピンオフが面白いです。', 'The spin-off is interesting.', '衍生作品很有趣。'),
  ('ja-anime-intermediate-110', 'ja', 'intermediate', 'anime/drama', 'コラボ', 'コラボ', 'korabo', 'collaboration', '联动', 'コラボイベントがあります。', 'There is a collaboration event.', '有联动活动。'),
  ('ja-anime-intermediate-111', 'ja', 'intermediate', 'anime/drama', '声優ラジオ', 'せいゆうラジオ', 'seiyuurajio', 'voice actor radio show', '声优电台', '声優ラジオを聴きます。', 'I listen to voice actor radio.', '我听声优电台。'),
  ('ja-anime-intermediate-112', 'ja', 'intermediate', 'anime/drama', '収録', 'しゅうろく', 'shuuroku', 'recording session', '录制', '収録が終わりました。', 'The recording is finished.', '录制结束了。'),
  ('ja-anime-intermediate-113', 'ja', 'intermediate', 'anime/drama', '映像', 'えいぞう', 'eizo', 'visual, footage', '影像', '映像が美しいです。', 'The visuals are beautiful.', '影像很美。'),
  ('ja-anime-intermediate-114', 'ja', 'intermediate', 'anime/drama', '撮影', 'さつえい', 'satsuei', 'filming, shooting', '拍摄', '撮影が始まりました。', 'Filming has started.', '开始拍摄了。'),
  ('ja-anime-intermediate-115', 'ja', 'intermediate', 'anime/drama', 'ロケ地', 'ロケち', 'rokechi', 'filming location', '外景地', 'ロケ地を訪れました。', 'I visited the filming location.', '我去了外景地。'),
  ('ja-anime-intermediate-116', 'ja', 'intermediate', 'anime/drama', '共演', 'きょうえん', 'kyoen', 'co-starring', '共演', '二人が共演します。', 'The two co-star together.', '两人共演。'),
  ('ja-anime-intermediate-117', 'ja', 'intermediate', 'anime/drama', '出演', 'しゅつえん', 'shutsuen', 'appearance, starring in', '出演', '有名な俳優が出演します。', 'A famous actor appears in it.', '有名演员出演。'),
  ('ja-anime-intermediate-118', 'ja', 'intermediate', 'anime/drama', 'キャスト', 'キャスト', 'kyasuto', 'cast', '演员阵容', 'キャストが豪華です。', 'The cast is gorgeous.', '演员阵容很豪华。'),
  ('ja-anime-intermediate-119', 'ja', 'intermediate', 'anime/drama', 'プロデューサー', 'プロデューサー', 'purodyuusaa', 'producer', '制片人', 'プロデューサーが変わりました。', 'The producer changed.', '制片人换了。'),
  ('ja-anime-intermediate-120', 'ja', 'intermediate', 'anime/drama', '脚色', 'きゃくしょく', 'kyakushoku', 'adaptation, screenplay writing', '改编', '原作からの脚色です。', 'It''s an adaptation from the original.', '这是从原作改编的。'),
  ('ja-anime-intermediate-121', 'ja', 'intermediate', 'anime/drama', '視聴', 'しちょう', 'shicho', 'viewing, watching', '收看', '視聴を続けます。', 'I continue watching.', '我继续收看。'),
  ('ja-anime-intermediate-122', 'ja', 'intermediate', 'anime/drama', '最新話', 'さいしんわ', 'saishinwa', 'latest episode', '最新一集', '最新話を見ました。', 'I watched the latest episode.', '我看了最新一集。'),
  ('ja-anime-intermediate-123', 'ja', 'intermediate', 'anime/drama', '第一話', 'だいいちわ', 'daiichi-wa', 'first episode', '第一集', '第一話から面白いです。', 'It''s interesting from the first episode.', '从第一集就很有趣。'),
  ('ja-anime-intermediate-124', 'ja', 'intermediate', 'anime/drama', '最終話', 'さいしゅうわ', 'saishu-wa', 'final episode', '最终话', '最終話で泣きました。', 'I cried in the final episode.', '最终话我哭了。'),
  ('ja-anime-intermediate-125', 'ja', 'intermediate', 'anime/drama', '神回', 'かみかい', 'kamikai', 'god-tier episode', '神回', '今週は神回でした。', 'This week was a god-tier episode.', '这周是神回。'),
  ('ja-anime-intermediate-126', 'ja', 'intermediate', 'anime/drama', '作画崩壊', 'さくがほうかい', 'sakugahoukai', 'animation breakdown', '作画崩坏', '作画崩壊が話題です。', 'The animation breakdown is a hot topic.', '作画崩坏成了话题。'),
  ('ja-anime-intermediate-127', 'ja', 'intermediate', 'anime/drama', '聖地', 'せいち', 'seichi', 'sacred place, anime location', '圣地', 'アニメの聖地です。', 'It''s an anime sacred place.', '这是动画圣地。'),
  ('ja-anime-intermediate-128', 'ja', 'intermediate', 'anime/drama', '原作者', 'げんさくしゃ', 'gensakusha', 'original author', '原作者', '原作者が監修しました。', 'The original author supervised it.', '原作者进行了监修。'),
  ('ja-anime-intermediate-129', 'ja', 'intermediate', 'anime/drama', '連続ドラマ', 'れんぞくドラマ', 'renzoku-dorama', 'serial drama', '连续剧', '連続ドラマを見ます。', 'I watch a serial drama.', '我看连续剧。'),
  ('ja-anime-intermediate-130', 'ja', 'intermediate', 'anime/drama', '単発', 'たんぱつ', 'tanpatsu', 'one-shot, standalone', '单集，独立', '単発ドラマを見ました。', 'I watched a standalone drama.', '我看了单集剧。'),
  ('ja-anime-intermediate-131', 'ja', 'intermediate', 'anime/drama', '視点', 'してん', 'shiten', 'viewpoint, perspective', '视角', '主人公の視点で描かれます。', 'It''s told from the protagonist''s perspective.', '以主角的视角描绘。'),
  ('ja-anime-intermediate-132', 'ja', 'intermediate', 'anime/drama', '複線', 'ふくせん', 'fukusen', 'subplot', '支线', '複線が多いです。', 'There are many subplots.', '支线很多。'),
  ('ja-anime-intermediate-133', 'ja', 'intermediate', 'anime/drama', '最高潮', 'さいこうちょう', 'saikoucho', 'climax', '高潮', '最高潮に達しました。', 'It reached the climax.', '达到了高潮。'),
  ('ja-anime-intermediate-134', 'ja', 'intermediate', 'anime/drama', '転換', 'てんかん', 'tenkan', 'turning point', '转折', '物語に転換がありました。', 'There was a turning point in the story.', '故事有了转折。'),
  ('ja-anime-intermediate-135', 'ja', 'intermediate', 'anime/drama', '対決', 'たいけつ', 'taiketsu', 'confrontation, showdown', '对决', '最後の対決が始まります。', 'The final showdown begins.', '最后的对决开始了。'),
  ('ja-anime-intermediate-136', 'ja', 'intermediate', 'anime/drama', '友情', 'ゆうじょう', 'yujo', 'friendship', '友情', '友情がテーマです。', 'Friendship is the theme.', '友情是主题。'),
  ('ja-anime-intermediate-137', 'ja', 'intermediate', 'anime/drama', '成長', 'せいちょう', 'seicho', 'growth, development', '成长', '主人公が成長します。', 'The protagonist grows.', '主角在成长。'),
  ('ja-anime-intermediate-138', 'ja', 'intermediate', 'anime/drama', '変身', 'へんしん', 'henshin', 'transformation', '变身', '変身シーンが好きです。', 'I like the transformation scene.', '我喜欢变身场面。'),
  ('ja-anime-intermediate-139', 'ja', 'intermediate', 'anime/drama', '必殺技', 'ひっさつわざ', 'hissatsuwaza', 'special move, finisher', '必杀技', '必殺技がかっこいいです。', 'The special move is cool.', '必杀技很帅。'),
  ('ja-anime-intermediate-140', 'ja', 'intermediate', 'anime/drama', '回', 'かい', 'kai', 'episode (counter)', '集（量词）', '第三回を見ました。', 'I watched episode three.', '我看了第三集。'),
  ('ja-anime-intermediate-141', 'ja', 'intermediate', 'anime/drama', '巻', 'かん', 'kan', 'volume', '卷', '最新巻を買いました。', 'I bought the latest volume.', '我买了最新卷。'),
  ('ja-anime-intermediate-142', 'ja', 'intermediate', 'anime/drama', '連ドラ', 'れんドラ', 'rendora', 'TV series', '电视连续剧', '連ドラを毎週見ます。', 'I watch the TV series every week.', '我每周看电视连续剧。'),
  ('ja-anime-intermediate-143', 'ja', 'intermediate', 'anime/drama', '視聴者', 'しちょうしゃ', 'shichousha', 'viewer, audience', '观众', '視聴者が増えました。', 'The number of viewers increased.', '观众增加了。'),
  ('ja-anime-intermediate-144', 'ja', 'intermediate', 'anime/drama', '出版', 'しゅっぱん', 'shuppan', 'publication', '出版', '出版されました。', 'It was published.', '出版了。'),
  ('ja-anime-intermediate-145', 'ja', 'intermediate', 'anime/drama', '受賞', 'じゅしょう', 'jusho', 'winning an award', '获奖', '受賞しました。', 'It won an award.', '获奖了。'),
  ('ja-anime-intermediate-146', 'ja', 'intermediate', 'anime/drama', 'ノミネート', 'ノミネート', 'nomineeto', 'nomination', '提名', 'ノミネートされました。', 'It was nominated.', '被提名了。'),
  ('ja-anime-intermediate-147', 'ja', 'intermediate', 'anime/drama', '興行収入', 'こうぎょうしゅうにゅう', 'kogyoshunyu', 'box office revenue', '票房收入', '興行収入が高いです。', 'The box office revenue is high.', '票房收入很高。'),
  ('ja-anime-intermediate-148', 'ja', 'intermediate', 'anime/drama', '公開', 'こうかい', 'koukai', 'release, premiere', '公映，上映', '来月公開されます。', 'It will be released next month.', '下个月上映。'),
  ('ja-anime-intermediate-149', 'ja', 'intermediate', 'anime/drama', '試写会', 'ししゃかい', 'shishakai', 'preview screening', '试映会', '試写会に行きました。', 'I went to the preview screening.', '我去了试映会。'),
  ('ja-anime-intermediate-150', 'ja', 'intermediate', 'anime/drama', '完成披露', 'かんせいひろう', 'kanseihiro', 'premiere event', '完成发布会', '完成披露に参加しました。', 'I attended the premiere event.', '我参加了完成发布会。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
