-- Expand ja-verbs-basic to 150 curated entries (16-150)
-- Topic: common verbs for basic Japanese learners
insert into public.vocabulary (
  id, target_language, level, topic,
  target_text, reading, romanization,
  meaning_en, meaning_zh_cn,
  example_text, example_translation_en, example_translation_zh_cn
) values
  ('ja-verbs-basic-16', 'ja', 'basic', 'common verbs', '走る', 'はしる', 'hashiru', 'run, dash', '跑，奔跑', '毎朝走ります。', 'I run every morning.', '我每天早上跑步。'),
  ('ja-verbs-basic-17', 'ja', 'basic', 'common verbs', '泳ぐ', 'およぐ', 'oyogu', 'swim, bathe', '游泳，游', '夏にプールで泳ぎます。', 'I swim in the pool in summer.', '夏天在泳池游泳。'),
  ('ja-verbs-basic-18', 'ja', 'basic', 'common verbs', '飛ぶ', 'とぶ', 'tobu', 'fly, jump', '飞，跳', '鳥が空を飛びます。', 'A bird flies in the sky.', '鸟在天上飞。'),
  ('ja-verbs-basic-19', 'ja', 'basic', 'common verbs', '登る', 'のぼる', 'noboru', 'climb, go up', '爬，登', '山に登ります。', 'I climb the mountain.', '我爬山。'),
  ('ja-verbs-basic-20', 'ja', 'basic', 'common verbs', '降りる', 'おりる', 'oriru', 'get off, descend', '下来，下车', '電車を降ります。', 'I get off the train.', '我下电车。'),
  ('ja-verbs-basic-21', 'ja', 'basic', 'common verbs', '入る', 'はいる', 'hairu', 'enter, go in', '进入，进去', '部屋に入ります。', 'I enter the room.', '我进房间。'),
  ('ja-verbs-basic-22', 'ja', 'basic', 'common verbs', '出る', 'でる', 'deru', 'go out, leave', '出去，离开', '家を出ます。', 'I leave the house.', '我出门。'),
  ('ja-verbs-basic-23', 'ja', 'basic', 'common verbs', '帰る', 'かえる', 'kaeru', 'return, go home', '回去，回家', '早く家に帰ります。', 'I go home early.', '我早点回家。'),
  ('ja-verbs-basic-24', 'ja', 'basic', 'common verbs', '通る', 'とおる', 'tooru', 'pass through, go along', '通过，经过', '公園を通ります。', 'I pass through the park.', '我经过公园。'),
  ('ja-verbs-basic-25', 'ja', 'basic', 'common verbs', '渡る', 'わたる', 'wataru', 'cross, go across', '过，渡过', '橋を渡ります。', 'I cross the bridge.', '我过桥。'),
  ('ja-verbs-basic-26', 'ja', 'basic', 'common verbs', '教える', 'おしえる', 'oshieru', 'teach, tell', '教，告诉', '日本語を教えます。', 'I teach Japanese.', '我教日语。'),
  ('ja-verbs-basic-27', 'ja', 'basic', 'common verbs', '答える', 'こたえる', 'kotaeru', 'answer, respond', '回答，答复', '質問に答えます。', 'I answer the question.', '我回答问题。'),
  ('ja-verbs-basic-28', 'ja', 'basic', 'common verbs', '呼ぶ', 'よぶ', 'yobu', 'call, invite', '叫，邀请', '友達を呼びます。', 'I invite my friend.', '我邀请朋友。'),
  ('ja-verbs-basic-29', 'ja', 'basic', 'common verbs', '頼む', 'たのむ', 'tanomu', 'ask, request', '拜托，请求', '友達に頼みます。', 'I ask my friend for help.', '我拜托朋友。'),
  ('ja-verbs-basic-30', 'ja', 'basic', 'common verbs', '伝える', 'つたえる', 'tsutaeru', 'convey, tell', '传达，转告', 'メッセージを伝えます。', 'I convey the message.', '我传达信息。'),
  ('ja-verbs-basic-31', 'ja', 'basic', 'common verbs', '尋ねる', 'たずねる', 'tazuneru', 'ask, inquire', '询问，打听', '道を尋ねます。', 'I ask for directions.', '我问路。'),
  ('ja-verbs-basic-32', 'ja', 'basic', 'common verbs', '開ける', 'あける', 'akeru', 'open, unlock', '打开，开', '窓を開けます。', 'I open the window.', '我打开窗户。'),
  ('ja-verbs-basic-33', 'ja', 'basic', 'common verbs', '閉める', 'しめる', 'shimeru', 'close, shut', '关，关闭', 'ドアを閉めます。', 'I close the door.', '我关门。'),
  ('ja-verbs-basic-34', 'ja', 'basic', 'common verbs', '押す', 'おす', 'osu', 'push, press', '推，按', 'ボタンを押します。', 'I press the button.', '我按按钮。'),
  ('ja-verbs-basic-35', 'ja', 'basic', 'common verbs', '引く', 'ひく', 'hiku', 'pull, draw', '拉，拽', 'ドアを引きます。', 'I pull the door.', '我拉门。'),
  ('ja-verbs-basic-36', 'ja', 'basic', 'common verbs', '切る', 'きる', 'kiru', 'cut, slice', '切，剪', '紙を切ります。', 'I cut the paper.', '我剪纸。'),
  ('ja-verbs-basic-37', 'ja', 'basic', 'common verbs', '消す', 'けす', 'kesu', 'turn off, erase', '关掉，擦掉', '電気を消します。', 'I turn off the light.', '我关灯。'),
  ('ja-verbs-basic-38', 'ja', 'basic', 'common verbs', 'つける', 'つける', 'tsukeru', 'turn on, attach', '打开，安装', '電気をつけます。', 'I turn on the light.', '我开灯。'),
  ('ja-verbs-basic-39', 'ja', 'basic', 'common verbs', '置く', 'おく', 'oku', 'put, place', '放，放置', '机の上に置きます。', 'I put it on the desk.', '我放在桌上。'),
  ('ja-verbs-basic-40', 'ja', 'basic', 'common verbs', '取る', 'とる', 'toru', 'take, get', '拿，取', '写真を取ります。', 'I take a photo.', '我拍照。'),
  ('ja-verbs-basic-41', 'ja', 'basic', 'common verbs', '送る', 'おくる', 'okuru', 'send, see off', '送，寄', '手紙を送ります。', 'I send a letter.', '我寄信。'),
  ('ja-verbs-basic-42', 'ja', 'basic', 'common verbs', '届ける', 'とどける', 'todokeru', 'deliver, report', '送到，递交', '荷物を届けます。', 'I deliver the package.', '我送包裹。'),
  ('ja-verbs-basic-43', 'ja', 'basic', 'common verbs', '覚える', 'おぼえる', 'oboeru', 'memorize, remember', '记住，记', '単語を覚えます。', 'I memorize vocabulary.', '我记单词。'),
  ('ja-verbs-basic-44', 'ja', 'basic', 'common verbs', '忘れる', 'わすれる', 'wasureru', 'forget, leave behind', '忘记，忘', '名前を忘れました。', 'I forgot the name.', '我忘了名字。'),
  ('ja-verbs-basic-45', 'ja', 'basic', 'common verbs', '考える', 'かんがえる', 'kangaeru', 'think, consider', '想，考虑', 'よく考えます。', 'I think carefully.', '我好好想想。'),
  ('ja-verbs-basic-46', 'ja', 'basic', 'common verbs', '決める', 'きめる', 'kimeru', 'decide, determine', '决定，定', '旅行の日を決めます。', 'I decide the travel date.', '我决定旅行日期。'),
  ('ja-verbs-basic-47', 'ja', 'basic', 'common verbs', '分かる', 'わかる', 'wakaru', 'understand, know', '明白，懂', '日本語が分かります。', 'I understand Japanese.', '我懂日语。'),
  ('ja-verbs-basic-48', 'ja', 'basic', 'common verbs', '信じる', 'しんじる', 'shinjiru', 'believe, trust', '相信，信任', '友達を信じます。', 'I trust my friend.', '我相信朋友。'),
  ('ja-verbs-basic-49', 'ja', 'basic', 'common verbs', '起きる', 'おきる', 'okiru', 'wake up, get up', '起床，起来', '毎朝六時に起きます。', 'I wake up at six every morning.', '我每天早上六点起床。'),
  ('ja-verbs-basic-50', 'ja', 'basic', 'common verbs', '寝る', 'ねる', 'neru', 'sleep, go to bed', '睡觉，睡', '十一時に寝ます。', 'I go to bed at eleven.', '我十一点睡觉。'),
  ('ja-verbs-basic-51', 'ja', 'basic', 'common verbs', '食べる', 'たべる', 'taberu', 'eat, have a meal', '吃，用餐', '朝ごはんを食べます。', 'I eat breakfast.', '我吃早饭。'),
  ('ja-verbs-basic-52', 'ja', 'basic', 'common verbs', '飲む', 'のむ', 'nomu', 'drink, take medicine', '喝，吃药', '水を飲みます。', 'I drink water.', '我喝水。'),
  ('ja-verbs-basic-53', 'ja', 'basic', 'common verbs', '洗う', 'あらう', 'arau', 'wash, clean', '洗，清洗', '手を洗います。', 'I wash my hands.', '我洗手。'),
  ('ja-verbs-basic-54', 'ja', 'basic', 'common verbs', '着る', 'きる', 'kiru', 'wear, put on', '穿，穿上', 'コートを着ます。', 'I wear a coat.', '我穿大衣。'),
  ('ja-verbs-basic-55', 'ja', 'basic', 'common verbs', '脱ぐ', 'ぬぐ', 'nugu', 'take off, undress', '脱，脱掉', '靴を脱ぎます。', 'I take off my shoes.', '我脱鞋。'),
  ('ja-verbs-basic-56', 'ja', 'basic', 'common verbs', '作る', 'つくる', 'tsukuru', 'make, create', '做，制作', '料理を作ります。', 'I cook a meal.', '我做菜。'),
  ('ja-verbs-basic-57', 'ja', 'basic', 'common verbs', '座る', 'すわる', 'suwaru', 'sit, sit down', '坐，坐下', '椅子に座ります。', 'I sit on the chair.', '我坐在椅子上。'),
  ('ja-verbs-basic-58', 'ja', 'basic', 'common verbs', '立つ', 'たつ', 'tatsu', 'stand, stand up', '站，站起来', '前に立ちます。', 'I stand in front.', '我站在前面。'),
  ('ja-verbs-basic-59', 'ja', 'basic', 'common verbs', '笑う', 'わらう', 'warau', 'laugh, smile', '笑，微笑', 'みんなが笑います。', 'Everyone laughs.', '大家都笑了。'),
  ('ja-verbs-basic-60', 'ja', 'basic', 'common verbs', '泣く', 'なく', 'naku', 'cry, weep', '哭，哭泣', '赤ちゃんが泣きます。', 'The baby cries.', '婴儿在哭。'),
  ('ja-verbs-basic-61', 'ja', 'basic', 'common verbs', '怒る', 'おこる', 'okoru', 'get angry, scold', '生气，发怒', '先生が怒ります。', 'The teacher gets angry.', '老师生气了。'),
  ('ja-verbs-basic-62', 'ja', 'basic', 'common verbs', '喜ぶ', 'よろこぶ', 'yorokobu', 'be glad, rejoice', '高兴，欢喜', '母が喜びます。', 'My mother is glad.', '妈妈很高兴。'),
  ('ja-verbs-basic-63', 'ja', 'basic', 'common verbs', '困る', 'こまる', 'komaru', 'be troubled, be at a loss', '为难，困惑', 'お金がなくて困ります。', 'I am troubled because I have no money.', '没钱很为难。'),
  ('ja-verbs-basic-64', 'ja', 'basic', 'common verbs', '驚く', 'おどろく', 'odoroku', 'be surprised, be amazed', '吃惊，惊讶', 'ニュースに驚きました。', 'I was surprised by the news.', '我对新闻感到惊讶。'),
  ('ja-verbs-basic-65', 'ja', 'basic', 'common verbs', '勉強する', 'べんきょうする', 'benkyou suru', 'study, learn', '学习，用功', '毎日日本語を勉強します。', 'I study Japanese every day.', '我每天学日语。'),
  ('ja-verbs-basic-66', 'ja', 'basic', 'common verbs', '運動する', 'うんどうする', 'undou suru', 'exercise, work out', '运动，锻炼', '毎朝運動します。', 'I exercise every morning.', '我每天早上运动。'),
  ('ja-verbs-basic-67', 'ja', 'basic', 'common verbs', '掃除する', 'そうじする', 'souji suru', 'clean, tidy up', '打扫，清扫', '部屋を掃除します。', 'I clean the room.', '我打扫房间。'),
  ('ja-verbs-basic-68', 'ja', 'basic', 'common verbs', '洗濯する', 'せんたくする', 'sentaku suru', 'do laundry, wash clothes', '洗衣服，洗涤', '週末に洗濯します。', 'I do laundry on weekends.', '我周末洗衣服。'),
  ('ja-verbs-basic-69', 'ja', 'basic', 'common verbs', '電話する', 'でんわする', 'denwa suru', 'make a phone call, call', '打电话，来电', '母に電話します。', 'I call my mother.', '我给妈妈打电话。'),
  ('ja-verbs-basic-70', 'ja', 'basic', 'common verbs', '約束する', 'やくそくする', 'yakusoku suru', 'promise, make an appointment', '约定，承诺', '友達と約束します。', 'I make plans with a friend.', '我和朋友约好了。'),
  ('ja-verbs-basic-71', 'ja', 'basic', 'common verbs', '心配する', 'しんぱいする', 'shinpai suru', 'worry, be concerned', '担心，忧虑', '母が心配します。', 'My mother worries.', '妈妈很担心。'),
  ('ja-verbs-basic-72', 'ja', 'basic', 'common verbs', '歩く', 'あるく', 'aruku', 'walk, stroll', '走，步行', '駅まで歩きます。', 'I walk to the station.', '我走到车站。'),
  ('ja-verbs-basic-73', 'ja', 'basic', 'common verbs', '止まる', 'とまる', 'tomaru', 'stop, halt', '停，停下', 'バスが止まります。', 'The bus stops.', '公交车停了。'),
  ('ja-verbs-basic-74', 'ja', 'basic', 'common verbs', '乗る', 'のる', 'noru', 'ride, get on', '乘，上车', '電車に乗ります。', 'I get on the train.', '我坐电车。'),
  ('ja-verbs-basic-75', 'ja', 'basic', 'common verbs', '動く', 'うごく', 'ugoku', 'move, operate', '动，运转', '時計が動きます。', 'The clock moves.', '钟在走。'),
  ('ja-verbs-basic-76', 'ja', 'basic', 'common verbs', '働く', 'はたらく', 'hataraku', 'work, labor', '工作，劳动', '会社で働きます。', 'I work at a company.', '我在公司上班。'),
  ('ja-verbs-basic-77', 'ja', 'basic', 'common verbs', '遊ぶ', 'あそぶ', 'asobu', 'play, hang out', '玩，游玩', '公園で遊びます。', 'I play in the park.', '我在公园玩。'),
  ('ja-verbs-basic-78', 'ja', 'basic', 'common verbs', '休む', 'やすむ', 'yasumu', 'rest, take a day off', '休息，请假', '今日は休みます。', 'I take today off.', '我今天休息。'),
  ('ja-verbs-basic-79', 'ja', 'basic', 'common verbs', '買う', 'かう', 'kau', 'buy, purchase', '买，购买', '本を買います。', 'I buy a book.', '我买书。'),
  ('ja-verbs-basic-80', 'ja', 'basic', 'common verbs', '売る', 'うる', 'uru', 'sell, deal in', '卖，出售', '車を売ります。', 'I sell the car.', '我卖车。'),
  ('ja-verbs-basic-81', 'ja', 'basic', 'common verbs', '払う', 'はらう', 'harau', 'pay, brush off', '付，支付', 'お金を払います。', 'I pay the money.', '我付钱。'),
  ('ja-verbs-basic-82', 'ja', 'basic', 'common verbs', '貸す', 'かす', 'kasu', 'lend, rent out', '借出，出租', '本を貸します。', 'I lend a book.', '我借出书。'),
  ('ja-verbs-basic-83', 'ja', 'basic', 'common verbs', '借りる', 'かりる', 'kariru', 'borrow, rent', '借，租', '図書館で本を借ります。', 'I borrow a book from the library.', '我从图书馆借书。'),
  ('ja-verbs-basic-84', 'ja', 'basic', 'common verbs', '返す', 'かえす', 'kaesu', 'return, give back', '还，归还', '本を返します。', 'I return the book.', '我还书。'),
  ('ja-verbs-basic-85', 'ja', 'basic', 'common verbs', '会う', 'あう', 'au', 'meet, see someone', '见面，碰面', '友達に会います。', 'I meet a friend.', '我见朋友。'),
  ('ja-verbs-basic-86', 'ja', 'basic', 'common verbs', '話す', 'はなす', 'hanasu', 'speak, talk', '说，说话', '日本語で話します。', 'I speak in Japanese.', '我用日语说话。'),
  ('ja-verbs-basic-87', 'ja', 'basic', 'common verbs', '歌う', 'うたう', 'utau', 'sing, chant', '唱，唱歌', 'カラオケで歌います。', 'I sing at karaoke.', '我在卡拉OK唱歌。'),
  ('ja-verbs-basic-88', 'ja', 'basic', 'common verbs', '踊る', 'おどる', 'odoru', 'dance, leap', '跳舞，舞蹈', 'パーティーで踊ります。', 'I dance at the party.', '我在派对上跳舞。'),
  ('ja-verbs-basic-89', 'ja', 'basic', 'common verbs', '描く', 'えがく', 'egaku', 'draw, paint', '画，描绘', '絵を描きます。', 'I draw a picture.', '我画画。'),
  ('ja-verbs-basic-90', 'ja', 'basic', 'common verbs', '撮る', 'とる', 'toru', 'take a photo, film', '拍，拍摄', '写真を撮ります。', 'I take a photo.', '我拍照。'),
  ('ja-verbs-basic-91', 'ja', 'basic', 'common verbs', '住む', 'すむ', 'sumu', 'live, reside', '住，居住', '東京に住みます。', 'I live in Tokyo.', '我住在东京。'),
  ('ja-verbs-basic-92', 'ja', 'basic', 'common verbs', '引っ越す', 'ひっこす', 'hikkosu', 'move house, relocate', '搬家，搬迁', '来月引っ越します。', 'I move next month.', '我下个月搬家。'),
  ('ja-verbs-basic-93', 'ja', 'basic', 'common verbs', '変わる', 'かわる', 'kawaru', 'change, differ', '变，改变', '季節が変わります。', 'The season changes.', '季节变了。'),
  ('ja-verbs-basic-94', 'ja', 'basic', 'common verbs', '始まる', 'はじまる', 'hajimaru', 'begin, start', '开始，起头', '授業が始まります。', 'The class begins.', '上课了。'),
  ('ja-verbs-basic-95', 'ja', 'basic', 'common verbs', '終わる', 'おわる', 'owaru', 'end, finish', '结束，完', '仕事が終わります。', 'Work ends.', '工作结束了。'),
  ('ja-verbs-basic-96', 'ja', 'basic', 'common verbs', '始める', 'はじめる', 'hajimeru', 'start, begin (transitive)', '开始，着手', '新しい仕事を始めます。', 'I start a new job.', '我开始新工作。'),
  ('ja-verbs-basic-97', 'ja', 'basic', 'common verbs', '終える', 'おえる', 'oeru', 'finish, complete (transitive)', '完成，结束', '宿題を終えます。', 'I finish my homework.', '我做完作业。'),
  ('ja-verbs-basic-98', 'ja', 'basic', 'common verbs', '続ける', 'つづける', 'tsuzukeru', 'continue, keep on', '继续，持续', '勉強を続けます。', 'I continue studying.', '我继续学习。'),
  ('ja-verbs-basic-99', 'ja', 'basic', 'common verbs', '止める', 'やめる', 'yameru', 'stop, quit', '停止，辞', 'タバコを止めます。', 'I quit smoking.', '我戒烟。'),
  ('ja-verbs-basic-100', 'ja', 'basic', 'common verbs', '選ぶ', 'えらぶ', 'erabu', 'choose, select', '选，选择', 'プレゼントを選びます。', 'I choose a present.', '我选礼物。'),
  ('ja-verbs-basic-101', 'ja', 'basic', 'common verbs', '探す', 'さがす', 'sagasu', 'look for, search', '找，寻找', '鍵を探します。', 'I look for the key.', '我找钥匙。'),
  ('ja-verbs-basic-102', 'ja', 'basic', 'common verbs', '見つける', 'みつける', 'mitsukeru', 'find, discover', '找到，发现', 'いい店を見つけました。', 'I found a good shop.', '我找到了一家好店。'),
  ('ja-verbs-basic-103', 'ja', 'basic', 'common verbs', '受ける', 'うける', 'ukeru', 'receive, take (an exam)', '接受，参加', '試験を受けます。', 'I take an exam.', '我参加考试。'),
  ('ja-verbs-basic-104', 'ja', 'basic', 'common verbs', '出す', 'だす', 'dasu', 'take out, submit', '拿出，提交', '手紙を出します。', 'I mail a letter.', '我寄信。'),
  ('ja-verbs-basic-105', 'ja', 'basic', 'common verbs', '入れる', 'いれる', 'ireru', 'put in, insert', '放进，装入', 'かばんに入れます。', 'I put it in the bag.', '我放进包里。'),
  ('ja-verbs-basic-106', 'ja', 'basic', 'common verbs', '並ぶ', 'ならぶ', 'narabu', 'line up, stand in a row', '排队，排列', '駅で並びます。', 'I line up at the station.', '我在车站排队。'),
  ('ja-verbs-basic-107', 'ja', 'basic', 'common verbs', '集める', 'あつめる', 'atsumeru', 'collect, gather', '收集，聚集', '切手を集めます。', 'I collect stamps.', '我收集邮票。'),
  ('ja-verbs-basic-108', 'ja', 'basic', 'common verbs', '捨てる', 'すてる', 'suteru', 'throw away, discard', '扔，丢弃', 'ゴミを捨てます。', 'I throw away the trash.', '我扔垃圾。'),
  ('ja-verbs-basic-109', 'ja', 'basic', 'common verbs', '片付ける', 'かたづける', 'katazukeru', 'tidy up, put away', '收拾，整理', '部屋を片付けます。', 'I tidy up the room.', '我收拾房间。'),
  ('ja-verbs-basic-110', 'ja', 'basic', 'common verbs', '直す', 'なおす', 'naosu', 'fix, correct', '修，改正', '時計を直します。', 'I fix the clock.', '我修钟。'),
  ('ja-verbs-basic-111', 'ja', 'basic', 'common verbs', '壊す', 'こわす', 'kowasu', 'break, destroy', '弄坏，破坏', 'コップを壊しました。', 'I broke the cup.', '我打碎了杯子。'),
  ('ja-verbs-basic-112', 'ja', 'basic', 'common verbs', '落とす', 'おとす', 'otosu', 'drop, lose', '掉落，弄丢', '財布を落としました。', 'I dropped my wallet.', '我把钱包弄丢了。'),
  ('ja-verbs-basic-113', 'ja', 'basic', 'common verbs', '拾う', 'ひろう', 'hirou', 'pick up, find', '捡，拾', '落ちた物を拾います。', 'I pick up the dropped item.', '我捡起掉的东西。'),
  ('ja-verbs-basic-114', 'ja', 'basic', 'common verbs', '上がる', 'あがる', 'agaru', 'rise, go up', '上升，上去', '温度が上がります。', 'The temperature rises.', '温度上升了。'),
  ('ja-verbs-basic-115', 'ja', 'basic', 'common verbs', '下がる', 'さがる', 'sagaru', 'fall, go down', '下降，降低', '気温が下がります。', 'The temperature drops.', '气温下降了。'),
  ('ja-verbs-basic-116', 'ja', 'basic', 'common verbs', '増える', 'ふえる', 'fueru', 'increase, grow', '增加，增多', '人口が増えます。', 'The population increases.', '人口增加了。'),
  ('ja-verbs-basic-117', 'ja', 'basic', 'common verbs', '減る', 'へる', 'heru', 'decrease, diminish', '减少，减', 'お金が減ります。', 'Money decreases.', '钱减少了。'),
  ('ja-verbs-basic-118', 'ja', 'basic', 'common verbs', '変える', 'かえる', 'kaeru', 'change, alter (transitive)', '改变，更换', '計画を変えます。', 'I change the plan.', '我改变计划。'),
  ('ja-verbs-basic-119', 'ja', 'basic', 'common verbs', '間に合う', 'まにあう', 'maniau', 'be in time, make it', '赶上，来得及', '電車に間に合います。', 'I make it in time for the train.', '我赶上了电车。'),
  ('ja-verbs-basic-120', 'ja', 'basic', 'common verbs', '急ぐ', 'いそぐ', 'isogu', 'hurry, rush', '赶紧，着急', '学校に急ぎます。', 'I hurry to school.', '我赶着去学校。'),
  ('ja-verbs-basic-121', 'ja', 'basic', 'common verbs', '遅れる', 'おくれる', 'okureru', 'be late, be delayed', '迟到，延迟', '授業に遅れます。', 'I am late for class.', '我上课迟到了。'),
  ('ja-verbs-basic-122', 'ja', 'basic', 'common verbs', '参加する', 'さんかする', 'sanka suru', 'participate, join', '参加，加入', 'パーティーに参加します。', 'I participate in the party.', '我参加派对。'),
  ('ja-verbs-basic-123', 'ja', 'basic', 'common verbs', '準備する', 'じゅんびする', 'junbi suru', 'prepare, get ready', '准备，预备', '旅行の準備をします。', 'I prepare for the trip.', '我准备旅行。'),
  ('ja-verbs-basic-124', 'ja', 'basic', 'common verbs', '紹介する', 'しょうかいする', 'shoukai suru', 'introduce, present', '介绍，引见', '友達を紹介します。', 'I introduce my friend.', '我介绍朋友。'),
  ('ja-verbs-basic-125', 'ja', 'basic', 'common verbs', '説明する', 'せつめいする', 'setsumei suru', 'explain, describe', '说明，解释', 'ルールを説明します。', 'I explain the rules.', '我说明规则。'),
  ('ja-verbs-basic-126', 'ja', 'basic', 'common verbs', '練習する', 'れんしゅうする', 'renshuu suru', 'practice, train', '练习，训练', 'ピアノを練習します。', 'I practice piano.', '我练钢琴。'),
  ('ja-verbs-basic-127', 'ja', 'basic', 'common verbs', '注意する', 'ちゅういする', 'chuui suru', 'be careful, pay attention', '注意，小心', '車に注意します。', 'I watch out for cars.', '我注意车辆。'),
  ('ja-verbs-basic-128', 'ja', 'basic', 'common verbs', '利用する', 'りようする', 'riyou suru', 'use, utilize', '利用，使用', 'バスを利用します。', 'I use the bus.', '我利用公交车。'),
  ('ja-verbs-basic-129', 'ja', 'basic', 'common verbs', '散歩する', 'さんぽする', 'sanpo suru', 'take a walk, stroll', '散步，逛', '公園を散歩します。', 'I take a walk in the park.', '我在公园散步。'),
  ('ja-verbs-basic-130', 'ja', 'basic', 'common verbs', '料理する', 'りょうりする', 'ryouri suru', 'cook, prepare food', '做饭，烹饪', '晩ご飯を料理します。', 'I cook dinner.', '我做晚饭。'),
  ('ja-verbs-basic-131', 'ja', 'basic', 'common verbs', '出かける', 'でかける', 'dekakeru', 'go out, head out', '出门，外出', '友達と出かけます。', 'I go out with a friend.', '我和朋友出门。'),
  ('ja-verbs-basic-132', 'ja', 'basic', 'common verbs', '届く', 'とどく', 'todoku', 'arrive, reach', '到达，送到', '荷物が届きます。', 'The package arrives.', '包裹到了。'),
  ('ja-verbs-basic-133', 'ja', 'basic', 'common verbs', '触る', 'さわる', 'sawaru', 'touch, feel', '摸，触', '猫に触ります。', 'I touch the cat.', '我摸猫。'),
  ('ja-verbs-basic-134', 'ja', 'basic', 'common verbs', '磨く', 'みがく', 'migaku', 'brush, polish', '刷，磨', '歯を磨きます。', 'I brush my teeth.', '我刷牙。'),
  ('ja-verbs-basic-135', 'ja', 'basic', 'common verbs', '干す', 'ほす', 'hosu', 'dry, hang out', '晾，晒', '洗濯物を干します。', 'I hang the laundry to dry.', '我晾衣服。'),
  ('ja-verbs-basic-136', 'ja', 'basic', 'common verbs', '畳む', 'たたむ', 'tatamu', 'fold, put away', '叠，折', '服を畳みます。', 'I fold the clothes.', '我叠衣服。'),
  ('ja-verbs-basic-137', 'ja', 'basic', 'common verbs', '運ぶ', 'はこぶ', 'hakobu', 'carry, transport', '搬，运', '荷物を運びます。', 'I carry the luggage.', '我搬行李。'),
  ('ja-verbs-basic-138', 'ja', 'basic', 'common verbs', '転ぶ', 'ころぶ', 'korobu', 'fall down, trip', '摔倒，跌倒', '道で転びました。', 'I fell on the road.', '我在路上摔倒了。'),
  ('ja-verbs-basic-139', 'ja', 'basic', 'common verbs', '起こす', 'おこす', 'okosu', 'wake someone, cause', '叫醒，引起', '弟を起こします。', 'I wake up my brother.', '我叫醒弟弟。'),
  ('ja-verbs-basic-140', 'ja', 'basic', 'common verbs', '間違える', 'まちがえる', 'machigaeru', 'make a mistake, mix up', '搞错，弄错', '名前を間違えました。', 'I got the name wrong.', '我搞错了名字。'),
  ('ja-verbs-basic-141', 'ja', 'basic', 'common verbs', '手伝う', 'てつだう', 'tetsudau', 'help, assist', '帮忙，帮助', '母を手伝います。', 'I help my mother.', '我帮妈妈。'),
  ('ja-verbs-basic-142', 'ja', 'basic', 'common verbs', '集まる', 'あつまる', 'atsumaru', 'gather, assemble', '聚集，集合', '人が集まります。', 'People gather.', '人们聚集了。'),
  ('ja-verbs-basic-143', 'ja', 'basic', 'common verbs', '別れる', 'わかれる', 'wakareru', 'part, separate', '分别，分手', '友達と別れます。', 'I part with my friend.', '我和朋友分别。'),
  ('ja-verbs-basic-144', 'ja', 'basic', 'common verbs', '慣れる', 'なれる', 'nareru', 'get used to, become accustomed', '习惯，适应', '日本に慣れました。', 'I got used to Japan.', '我习惯了日本。'),
  ('ja-verbs-basic-145', 'ja', 'basic', 'common verbs', '疲れる', 'つかれる', 'tsukareru', 'get tired, be exhausted', '累，疲倦', '仕事で疲れました。', 'I got tired from work.', '我工作累了。'),
  ('ja-verbs-basic-146', 'ja', 'basic', 'common verbs', '痩せる', 'やせる', 'yaseru', 'lose weight, get thin', '瘦，变瘦', '少し痩せました。', 'I lost a bit of weight.', '我瘦了一点。'),
  ('ja-verbs-basic-147', 'ja', 'basic', 'common verbs', '太る', 'ふとる', 'futoru', 'gain weight, get fat', '胖，发胖', '冬に太ります。', 'I gain weight in winter.', '我冬天会胖。'),
  ('ja-verbs-basic-148', 'ja', 'basic', 'common verbs', '似る', 'にる', 'niru', 'resemble, look like', '像，相似', '母に似ています。', 'I look like my mother.', '我像妈妈。'),
  ('ja-verbs-basic-149', 'ja', 'basic', 'common verbs', '違う', 'ちがう', 'chigau', 'differ, be wrong', '不同，不对', '答えが違います。', 'The answer is wrong.', '答案不对。'),
  ('ja-verbs-basic-150', 'ja', 'basic', 'common verbs', '足りる', 'たりる', 'tariru', 'be enough, suffice', '够，足够', '時間が足りません。', 'There is not enough time.', '时间不够。')
on conflict (id) do update set
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
