insert into public.vocabulary (
  id,
  target_language,
  level,
  topic,
  target_text,
  reading,
  romanization,
  meaning_en,
  meaning_zh_cn,
  example_text,
  example_translation_en,
  example_translation_zh_cn
) values
  ('ja-food-basic-15', 'ja', 'basic', 'food', 'お菓子', 'おかし', 'okashi', 'snack', '零食', 'お菓子を少し食べます。', 'I eat a small snack.', '我吃一点零食。'),
  ('ko-food-basic-15', 'ko', 'basic', 'food', '과자', '과자', 'gwaja', 'snack', '零食', '과자를 조금 먹어요.', 'I eat a small snack.', '我吃一点零食。'),
  ('ja-travel-basic-15', 'ja', 'basic', 'travel', '橋', 'はし', 'hashi', 'bridge', '桥', '橋を渡ります。', 'I cross the bridge.', '我过桥。'),
  ('ko-travel-basic-15', 'ko', 'basic', 'travel', '다리', '다리', 'dari', 'bridge', '桥', '다리를 건너요.', 'I cross the bridge.', '我过桥。'),
  ('ja-life-basic-15', 'ja', 'basic', 'daily life', '鍵', 'かぎ', 'kagi', 'key', '钥匙', '鍵を持っています。', 'I have the key.', '我有钥匙。'),
  ('ko-life-basic-15', 'ko', 'basic', 'daily life', '열쇠', '열쇠', 'yeolsoe', 'key', '钥匙', '열쇠를 가지고 있어요.', 'I have the key.', '我有钥匙。'),
  ('ja-numbers-basic-15', 'ja', 'basic', 'numbers', '零', 'れい', 'rei', 'zero', '零', '答えは零です。', 'The answer is zero.', '答案是零。'),
  ('ko-numbers-basic-15', 'ko', 'basic', 'numbers', '영', '영', 'yeong', 'zero', '零', '답은 영이에요.', 'The answer is zero.', '答案是零。'),
  ('ja-verbs-basic-15', 'ja', 'basic', 'common verbs', '洗う', 'あらう', 'arau', 'wash', '洗', '手を洗います。', 'I wash my hands.', '我洗手。'),
  ('ko-verbs-basic-15', 'ko', 'basic', 'common verbs', '씻다', '씻다', 'ssitda', 'wash', '洗', '손을 씻어요.', 'I wash my hands.', '我洗手。'),
  ('ja-food-intermediate-6', 'ja', 'intermediate', 'food', '食材', 'しょくざい', 'shokuzai', 'ingredient', '食材', '新鮮な食材を選びます。', 'I choose fresh ingredients.', '我选择新鲜食材。'),
  ('ko-food-intermediate-6', 'ko', 'intermediate', 'food', '식재료', '식재료', 'sikjaeryo', 'ingredient', '食材', '신선한 식재료를 골라요.', 'I choose fresh ingredients.', '我选择新鲜食材。'),
  ('ja-food-intermediate-7', 'ja', 'intermediate', 'food', '味', 'あじ', 'aji', 'taste', '味道', '味を確認します。', 'I check the taste.', '我确认味道。'),
  ('ko-food-intermediate-7', 'ko', 'intermediate', 'food', '맛', '맛', 'mat', 'taste', '味道', '맛을 확인해요.', 'I check the taste.', '我确认味道。'),
  ('ja-food-intermediate-8', 'ja', 'intermediate', 'food', '栄養', 'えいよう', 'eiyo', 'nutrition', '营养', '栄養を考えます。', 'I consider nutrition.', '我考虑营养。'),
  ('ko-food-intermediate-8', 'ko', 'intermediate', 'food', '영양', '영양', 'yeongyang', 'nutrition', '营养', '영양을 생각해요.', 'I consider nutrition.', '我考虑营养。'),
  ('ja-food-intermediate-9', 'ja', 'intermediate', 'food', '食欲', 'しょくよく', 'shokuyoku', 'appetite', '食欲', '食欲があります。', 'I have an appetite.', '我有食欲。'),
  ('ko-food-intermediate-9', 'ko', 'intermediate', 'food', '식욕', '식욕', 'sigyok', 'appetite', '食欲', '식욕이 있어요.', 'I have an appetite.', '我有食欲。'),
  ('ja-food-intermediate-10', 'ja', 'intermediate', 'food', '調理', 'ちょうり', 'chori', 'cooking', '烹饪', '野菜を調理します。', 'I cook vegetables.', '我烹饪蔬菜。'),
  ('ko-food-intermediate-10', 'ko', 'intermediate', 'food', '조리', '조리', 'jori', 'cooking', '烹饪', '채소를 조리해요.', 'I cook vegetables.', '我烹饪蔬菜。'),
  ('ja-travel-intermediate-6', 'ja', 'intermediate', 'travel', '乗り換え', 'のりかえ', 'norikae', 'transfer', '换乘', '駅で乗り換えます。', 'I transfer at the station.', '我在车站换乘。'),
  ('ko-travel-intermediate-6', 'ko', 'intermediate', 'travel', '환승', '환승', 'hwanseung', 'transfer', '换乘', '역에서 환승해요.', 'I transfer at the station.', '我在车站换乘。'),
  ('ja-travel-intermediate-7', 'ja', 'intermediate', 'travel', '目的地', 'もくてきち', 'mokutekichi', 'destination', '目的地', '目的地に着きました。', 'I arrived at the destination.', '我到达目的地。'),
  ('ko-travel-intermediate-7', 'ko', 'intermediate', 'travel', '목적지', '목적지', 'mokjeokji', 'destination', '目的地', '목적지에 도착했어요.', 'I arrived at the destination.', '我到达目的地。'),
  ('ja-travel-intermediate-8', 'ja', 'intermediate', 'travel', '出発', 'しゅっぱつ', 'shuppatsu', 'departure', '出发', '出発は朝です。', 'Departure is in the morning.', '早上出发。'),
  ('ko-travel-intermediate-8', 'ko', 'intermediate', 'travel', '출발', '출발', 'chulbal', 'departure', '出发', '출발은 아침이에요.', 'Departure is in the morning.', '早上出发。'),
  ('ja-travel-intermediate-9', 'ja', 'intermediate', 'travel', '到着', 'とうちゃく', 'tochaku', 'arrival', '到达', '到着を待ちます。', 'I wait for arrival.', '我等待到达。'),
  ('ko-travel-intermediate-9', 'ko', 'intermediate', 'travel', '도착', '도착', 'dochag', 'arrival', '到达', '도착을 기다려요.', 'I wait for arrival.', '我等待到达。'),
  ('ja-travel-intermediate-10', 'ja', 'intermediate', 'travel', '観光', 'かんこう', 'kanko', 'sightseeing', '观光', '京都を観光します。', 'I go sightseeing.', '我去观光。'),
  ('ko-travel-intermediate-10', 'ko', 'intermediate', 'travel', '관광', '관광', 'gwangwang', 'sightseeing', '观光', '서울을 관광해요.', 'I go sightseeing.', '我去观光。'),
  ('ja-life-intermediate-6', 'ja', 'intermediate', 'daily life', '洗濯', 'せんたく', 'sentaku', 'laundry', '洗衣', '週末に洗濯します。', 'I do laundry on weekends.', '我周末洗衣服。'),
  ('ko-life-intermediate-6', 'ko', 'intermediate', 'daily life', '세탁', '세탁', 'setak', 'laundry', '洗衣', '주말에 세탁해요.', 'I do laundry on weekends.', '我周末洗衣服。'),
  ('ja-life-intermediate-7', 'ja', 'intermediate', 'daily life', '掃除', 'そうじ', 'soji', 'cleaning', '打扫', '部屋を掃除します。', 'I clean the room.', '我打扫房间。'),
  ('ko-life-intermediate-7', 'ko', 'intermediate', 'daily life', '청소', '청소', 'cheongso', 'cleaning', '打扫', '방을 청소해요.', 'I clean the room.', '我打扫房间。'),
  ('ja-life-intermediate-8', 'ja', 'intermediate', 'daily life', '予定', 'よてい', 'yotei', 'schedule', '日程', '予定を確認します。', 'I check the schedule.', '我确认日程。'),
  ('ko-life-intermediate-8', 'ko', 'intermediate', 'daily life', '일정', '일정', 'iljeong', 'schedule', '日程', '일정을 확인해요.', 'I check the schedule.', '我确认日程。'),
  ('ja-life-intermediate-9', 'ja', 'intermediate', 'daily life', '近所', 'きんじょ', 'kinjo', 'neighborhood', '附近', '近所を散歩します。', 'I walk around the neighborhood.', '我在附近散步。'),
  ('ko-life-intermediate-9', 'ko', 'intermediate', 'daily life', '동네', '동네', 'dongne', 'neighborhood', '附近', '동네를 산책해요.', 'I walk around the neighborhood.', '我在附近散步。'),
  ('ja-life-intermediate-10', 'ja', 'intermediate', 'daily life', '習慣', 'しゅうかん', 'shukan', 'habit', '习惯', '良い習慣を作ります。', 'I build a good habit.', '我养成好习惯。'),
  ('ko-life-intermediate-10', 'ko', 'intermediate', 'daily life', '습관', '습관', 'seupgwan', 'habit', '习惯', '좋은 습관을 만들어요.', 'I build a good habit.', '我养成好习惯。'),
  ('ja-work-intermediate-13', 'ja', 'intermediate', 'work', '報告', 'ほうこく', 'hokoku', 'report', '报告', '結果を報告します。', 'I report the result.', '我报告结果。'),
  ('ko-work-intermediate-13', 'ko', 'intermediate', 'work', '보고', '보고', 'bogo', 'report', '报告', '결과를 보고해요.', 'I report the result.', '我报告结果。'),
  ('ja-work-intermediate-14', 'ja', 'intermediate', 'work', '相談', 'そうだん', 'sodan', 'consultation', '商量', '上司に相談します。', 'I consult my manager.', '我和上司商量。'),
  ('ko-work-intermediate-14', 'ko', 'intermediate', 'work', '상담', '상담', 'sangdam', 'consultation', '商量', '상사와 상담해요.', 'I consult my manager.', '我和上司商量。'),
  ('ja-work-intermediate-15', 'ja', 'intermediate', 'work', '依頼', 'いらい', 'irai', 'request', '请求', '資料を依頼します。', 'I request the documents.', '我请求资料。'),
  ('ko-work-intermediate-15', 'ko', 'intermediate', 'work', '요청', '요청', 'yocheong', 'request', '请求', '자료를 요청해요.', 'I request the documents.', '我请求资料。'),
  ('ja-work-intermediate-16', 'ja', 'intermediate', 'work', '進捗', 'しんちょく', 'shinchoku', 'progress', '进展', '進捗を共有します。', 'I share progress.', '我分享进展。'),
  ('ko-work-intermediate-16', 'ko', 'intermediate', 'work', '진행', '진행', 'jinhaeng', 'progress', '进展', '진행 상황을 공유해요.', 'I share progress.', '我分享进展。'),
  ('ja-school-intermediate-13', 'ja', 'intermediate', 'school', '講義', 'こうぎ', 'kogi', 'lecture', '讲课', '講義を受けます。', 'I attend a lecture.', '我听课。'),
  ('ko-school-intermediate-13', 'ko', 'intermediate', 'school', '강의', '강의', 'gangui', 'lecture', '讲课', '강의를 들어요.', 'I attend a lecture.', '我听课。'),
  ('ja-school-intermediate-14', 'ja', 'intermediate', 'school', '教科書', 'きょうかしょ', 'kyokasho', 'textbook', '课本', '教科書を開きます。', 'I open the textbook.', '我打开课本。'),
  ('ko-school-intermediate-14', 'ko', 'intermediate', 'school', '교과서', '교과서', 'gyogwaseo', 'textbook', '课本', '교과서를 펴요.', 'I open the textbook.', '我打开课本。'),
  ('ja-school-intermediate-15', 'ja', 'intermediate', 'school', '欠席', 'けっせき', 'kesseki', 'absence', '缺席', '今日は欠席です。', 'I am absent today.', '我今天缺席。'),
  ('ko-school-intermediate-15', 'ko', 'intermediate', 'school', '결석', '결석', 'gyeolseok', 'absence', '缺席', '오늘은 결석이에요.', 'I am absent today.', '我今天缺席。'),
  ('ja-school-intermediate-16', 'ja', 'intermediate', 'school', '成績', 'せいせき', 'seiseki', 'grade', '成绩', '成績が上がりました。', 'My grade improved.', '我的成绩提高了。'),
  ('ko-school-intermediate-16', 'ko', 'intermediate', 'school', '성적', '성적', 'seongjeok', 'grade', '成绩', '성적이 올랐어요.', 'My grade improved.', '我的成绩提高了。'),
  ('ja-anime-intermediate-12', 'ja', 'intermediate', 'anime/drama', '脚本', 'きゃくほん', 'kyakuhon', 'script', '剧本', '脚本を読みます。', 'I read the script.', '我读剧本。'),
  ('ko-drama-intermediate-12', 'ko', 'intermediate', 'anime/drama', '대본', '대본', 'daebon', 'script', '剧本', '대본을 읽어요.', 'I read the script.', '我读剧本。'),
  ('ja-anime-intermediate-13', 'ja', 'intermediate', 'anime/drama', '演出', 'えんしゅつ', 'enshutsu', 'direction', '演出', '演出が印象的です。', 'The direction is impressive.', '演出令人印象深刻。'),
  ('ko-drama-intermediate-13', 'ko', 'intermediate', 'anime/drama', '연출', '연출', 'yeonchul', 'direction', '演出', '연출이 인상적이에요.', 'The direction is impressive.', '演出令人印象深刻。'),
  ('ja-jlpt-advanced-31', 'ja', 'advanced', 'JLPT', '概要', 'がいよう', 'gaiyo', 'overview', '概要', '概要を確認します。', 'I confirm the overview.', '我确认概要。'),
  ('ko-topik-advanced-31', 'ko', 'advanced', 'TOPIK', '개요', '개요', 'gaeyo', 'overview', '概要', '개요을 확인합니다.', 'I confirm the overview.', '我确认概要。'),
  ('ja-jlpt-advanced-32', 'ja', 'advanced', 'JLPT', '分析', 'ぶんせき', 'bunseki', 'analysis', '分析', '分析を確認します。', 'I confirm the analysis.', '我确认分析。'),
  ('ko-topik-advanced-32', 'ko', 'advanced', 'TOPIK', '분석', '분석', 'bunseok', 'analysis', '分析', '분석을 확인합니다.', 'I confirm the analysis.', '我确认分析。'),
  ('ja-jlpt-advanced-33', 'ja', 'advanced', 'JLPT', '評価', 'ひょうか', 'hyoka', 'evaluation', '评价', '評価を確認します。', 'I confirm the evaluation.', '我确认评价。'),
  ('ko-topik-advanced-33', 'ko', 'advanced', 'TOPIK', '평가', '평가', 'pyeongga', 'evaluation', '评价', '평가을 확인합니다.', 'I confirm the evaluation.', '我确认评价。'),
  ('ja-jlpt-advanced-34', 'ja', 'advanced', 'JLPT', '課題', 'かだい', 'kadai', 'challenge', '课题', '課題を確認します。', 'I confirm the challenge.', '我确认课题。'),
  ('ko-topik-advanced-34', 'ko', 'advanced', 'TOPIK', '과제', '과제', 'gwaje', 'challenge', '课题', '과제을 확인합니다.', 'I confirm the challenge.', '我确认课题。'),
  ('ja-jlpt-advanced-35', 'ja', 'advanced', 'JLPT', '要因', 'よういん', 'yoin', 'factor', '因素', '要因を確認します。', 'I confirm the factor.', '我确认因素。'),
  ('ko-topik-advanced-35', 'ko', 'advanced', 'TOPIK', '요인', '요인', 'yoin', 'factor', '因素', '요인을 확인합니다.', 'I confirm the factor.', '我确认因素。'),
  ('ja-jlpt-advanced-36', 'ja', 'advanced', 'JLPT', '影響', 'えいきょう', 'eikyo', 'influence', '影响', '影響を確認します。', 'I confirm the influence.', '我确认影响。'),
  ('ko-topik-advanced-36', 'ko', 'advanced', 'TOPIK', '영향', '영향', 'yeonghyang', 'influence', '影响', '영향을 확인합니다.', 'I confirm the influence.', '我确认影响。'),
  ('ja-jlpt-advanced-37', 'ja', 'advanced', 'JLPT', '傾向', 'けいこう', 'keiko', 'tendency', '倾向', '傾向を確認します。', 'I confirm the tendency.', '我确认倾向。'),
  ('ko-topik-advanced-37', 'ko', 'advanced', 'TOPIK', '경향', '경향', 'gyeonghyang', 'tendency', '倾向', '경향을 확인합니다.', 'I confirm the tendency.', '我确认倾向。'),
  ('ja-jlpt-advanced-38', 'ja', 'advanced', 'JLPT', '改善', 'かいぜん', 'kaizen', 'improvement', '改善', '改善を確認します。', 'I confirm the improvement.', '我确认改善。'),
  ('ko-topik-advanced-38', 'ko', 'advanced', 'TOPIK', '개선', '개선', 'gaeseon', 'improvement', '改善', '개선을 확인합니다.', 'I confirm the improvement.', '我确认改善。'),
  ('ja-jlpt-advanced-39', 'ja', 'advanced', 'JLPT', '検討', 'けんとう', 'kento', 'review', '研究', '検討を確認します。', 'I confirm the review.', '我确认研究。'),
  ('ko-topik-advanced-39', 'ko', 'advanced', 'TOPIK', '검토', '검토', 'geomto', 'review', '研究', '검토을 확인합니다.', 'I confirm the review.', '我确认研究。'),
  ('ja-jlpt-advanced-40', 'ja', 'advanced', 'JLPT', '構造', 'こうぞう', 'kozo', 'structure', '结构', '構造を確認します。', 'I confirm the structure.', '我确认结构。'),
  ('ko-topik-advanced-40', 'ko', 'advanced', 'TOPIK', '구조', '구조', 'gujo', 'structure', '结构', '구조을 확인합니다.', 'I confirm the structure.', '我确认结构。'),
  ('ja-jlpt-advanced-41', 'ja', 'advanced', 'JLPT', '体系', 'たいけい', 'taikei', 'system', '体系', '体系を確認します。', 'I confirm the system.', '我确认体系。'),
  ('ko-topik-advanced-41', 'ko', 'advanced', 'TOPIK', '체계', '체계', 'chegye', 'system', '体系', '체계을 확인합니다.', 'I confirm the system.', '我确认体系。'),
  ('ja-jlpt-advanced-42', 'ja', 'advanced', 'JLPT', '事例', 'じれい', 'jirei', 'example', '事例', '事例を確認します。', 'I confirm the example.', '我确认事例。'),
  ('ko-topik-advanced-42', 'ko', 'advanced', 'TOPIK', '사례', '사례', 'sarye', 'example', '事例', '사례을 확인합니다.', 'I confirm the example.', '我确认事例。'),
  ('ja-jlpt-advanced-43', 'ja', 'advanced', 'JLPT', '仮定', 'かてい', 'katei', 'assumption', '假定', '仮定を確認します。', 'I confirm the assumption.', '我确认假定。'),
  ('ko-topik-advanced-43', 'ko', 'advanced', 'TOPIK', '가정', '가정', 'gajeong', 'assumption', '假定', '가정을 확인합니다.', 'I confirm the assumption.', '我确认假定。'),
  ('ja-jlpt-advanced-44', 'ja', 'advanced', 'JLPT', '根拠', 'こんきょ', 'konkyo', 'evidence', '根据', '根拠を確認します。', 'I confirm the evidence.', '我确认根据。'),
  ('ko-topik-advanced-44', 'ko', 'advanced', 'TOPIK', '근거', '근거', 'geungeo', 'evidence', '根据', '근거을 확인합니다.', 'I confirm the evidence.', '我确认根据。'),
  ('ja-jlpt-advanced-45', 'ja', 'advanced', 'JLPT', '目的', 'もくてき', 'mokuteki', 'purpose', '目的', '目的を確認します。', 'I confirm the purpose.', '我确认目的。'),
  ('ko-topik-advanced-45', 'ko', 'advanced', 'TOPIK', '목적', '목적', 'mokjeok', 'purpose', '目的', '목적을 확인합니다.', 'I confirm the purpose.', '我确认目的。'),
  ('ja-jlpt-advanced-46', 'ja', 'advanced', 'JLPT', '手段', 'しゅだん', 'shudan', 'method', '手段', '手段を確認します。', 'I confirm the method.', '我确认手段。'),
  ('ko-topik-advanced-46', 'ko', 'advanced', 'TOPIK', '수단', '수단', 'sudan', 'method', '手段', '수단을 확인합니다.', 'I confirm the method.', '我确认手段。'),
  ('ja-jlpt-advanced-47', 'ja', 'advanced', 'JLPT', '結果', 'けっか', 'kekka', 'result', '结果', '結果を確認します。', 'I confirm the result.', '我确认结果。'),
  ('ko-topik-advanced-47', 'ko', 'advanced', 'TOPIK', '결과', '결과', 'gyeolgwa', 'result', '结果', '결과을 확인합니다.', 'I confirm the result.', '我确认结果。'),
  ('ja-jlpt-advanced-48', 'ja', 'advanced', 'JLPT', '過程', 'かてい', 'katei', 'process', '过程', '過程を確認します。', 'I confirm the process.', '我确认过程。'),
  ('ko-topik-advanced-48', 'ko', 'advanced', 'TOPIK', '과정', '과정', 'gwajeong', 'process', '过程', '과정을 확인합니다.', 'I confirm the process.', '我确认过程。'),
  ('ja-jlpt-advanced-49', 'ja', 'advanced', 'JLPT', '理論', 'りろん', 'riron', 'theory', '理论', '理論を確認します。', 'I confirm the theory.', '我确认理论。'),
  ('ko-topik-advanced-49', 'ko', 'advanced', 'TOPIK', '이론', '이론', 'iron', 'theory', '理论', '이론을 확인합니다.', 'I confirm the theory.', '我确认理论。'),
  ('ja-jlpt-advanced-50', 'ja', 'advanced', 'JLPT', '実態', 'じったい', 'jittai', 'reality', '实态', '実態を確認します。', 'I confirm the reality.', '我确认实态。'),
  ('ko-topik-advanced-50', 'ko', 'advanced', 'TOPIK', '실태', '실태', 'siltae', 'reality', '实态', '실태을 확인합니다.', 'I confirm the reality.', '我确认实态。'),
  ('ja-jlpt-advanced-51', 'ja', 'advanced', 'JLPT', '認識', 'にんしき', 'ninshiki', 'recognition', '认识', '認識を確認します。', 'I confirm the recognition.', '我确认认识。'),
  ('ko-topik-advanced-51', 'ko', 'advanced', 'TOPIK', '인식', '인식', 'insik', 'recognition', '认识', '인식을 확인합니다.', 'I confirm the recognition.', '我确认认识。'),
  ('ja-jlpt-advanced-52', 'ja', 'advanced', 'JLPT', '判断', 'はんだん', 'handan', 'judgment', '判断', '判断を確認します。', 'I confirm the judgment.', '我确认判断。'),
  ('ko-topik-advanced-52', 'ko', 'advanced', 'TOPIK', '판단', '판단', 'pandan', 'judgment', '判断', '판단을 확인합니다.', 'I confirm the judgment.', '我确认判断。'),
  ('ja-jlpt-advanced-53', 'ja', 'advanced', 'JLPT', '選択', 'せんたく', 'sentaku', 'choice', '选择', '選択を確認します。', 'I confirm the choice.', '我确认选择。'),
  ('ko-topik-advanced-53', 'ko', 'advanced', 'TOPIK', '선택', '선택', 'seontaek', 'choice', '选择', '선택을 확인합니다.', 'I confirm the choice.', '我确认选择。'),
  ('ja-jlpt-advanced-54', 'ja', 'advanced', 'JLPT', '比較', 'ひかく', 'hikaku', 'comparison', '比较', '比較を確認します。', 'I confirm the comparison.', '我确认比较。'),
  ('ko-topik-advanced-54', 'ko', 'advanced', 'TOPIK', '비교', '비교', 'bigyo', 'comparison', '比较', '비교을 확인합니다.', 'I confirm the comparison.', '我确认比较。'),
  ('ja-jlpt-advanced-55', 'ja', 'advanced', 'JLPT', '変化', 'へんか', 'henka', 'change', '变化', '変化を確認します。', 'I confirm the change.', '我确认变化。'),
  ('ko-topik-advanced-55', 'ko', 'advanced', 'TOPIK', '변화', '변화', 'byeonhwa', 'change', '变化', '변화을 확인합니다.', 'I confirm the change.', '我确认变化。'),
  ('ja-jlpt-advanced-56', 'ja', 'advanced', 'JLPT', '拡大', 'かくだい', 'kakudai', 'expansion', '扩大', '拡大を確認します。', 'I confirm the expansion.', '我确认扩大。'),
  ('ko-topik-advanced-56', 'ko', 'advanced', 'TOPIK', '확대', '확대', 'hwakdae', 'expansion', '扩大', '확대을 확인합니다.', 'I confirm the expansion.', '我确认扩大。'),
  ('ja-jlpt-advanced-57', 'ja', 'advanced', 'JLPT', '縮小', 'しゅくしょう', 'shukusho', 'reduction', '缩小', '縮小を確認します。', 'I confirm the reduction.', '我确认缩小。'),
  ('ko-topik-advanced-57', 'ko', 'advanced', 'TOPIK', '축소', '축소', 'chukso', 'reduction', '缩小', '축소을 확인합니다.', 'I confirm the reduction.', '我确认缩小。'),
  ('ja-jlpt-advanced-58', 'ja', 'advanced', 'JLPT', '安定', 'あんてい', 'antei', 'stability', '稳定', '安定を確認します。', 'I confirm the stability.', '我确认稳定。'),
  ('ko-topik-advanced-58', 'ko', 'advanced', 'TOPIK', '안정', '안정', 'anjeong', 'stability', '稳定', '안정을 확인합니다.', 'I confirm the stability.', '我确认稳定。'),
  ('ja-jlpt-advanced-59', 'ja', 'advanced', 'JLPT', '需要', 'じゅよう', 'juyo', 'demand', '需求', '需要を確認します。', 'I confirm the demand.', '我确认需求。'),
  ('ko-topik-advanced-59', 'ko', 'advanced', 'TOPIK', '수요', '수요', 'suyo', 'demand', '需求', '수요을 확인합니다.', 'I confirm the demand.', '我确认需求。'),
  ('ja-jlpt-advanced-60', 'ja', 'advanced', 'JLPT', '供給', 'きょうきゅう', 'kyokyu', 'supply', '供给', '供給を確認します。', 'I confirm the supply.', '我确认供给。'),
  ('ko-topik-advanced-60', 'ko', 'advanced', 'TOPIK', '공급', '공급', 'gonggeup', 'supply', '供给', '공급을 확인합니다.', 'I confirm the supply.', '我确认供给。'),
  ('ja-jlpt-advanced-61', 'ja', 'advanced', 'JLPT', '資源', 'しげん', 'shigen', 'resource', '资源', '資源を確認します。', 'I confirm the resource.', '我确认资源。'),
  ('ko-topik-advanced-61', 'ko', 'advanced', 'TOPIK', '자원', '자원', 'jawon', 'resource', '资源', '자원을 확인합니다.', 'I confirm the resource.', '我确认资源。'),
  ('ja-jlpt-advanced-62', 'ja', 'advanced', 'JLPT', '環境', 'かんきょう', 'kankyo', 'environment', '环境', '環境を確認します。', 'I confirm the environment.', '我确认环境。'),
  ('ko-topik-advanced-62', 'ko', 'advanced', 'TOPIK', '환경', '환경', 'hwangyeong', 'environment', '环境', '환경을 확인합니다.', 'I confirm the environment.', '我确认环境。'),
  ('ja-jlpt-advanced-63', 'ja', 'advanced', 'JLPT', '制度', 'せいど', 'seido', 'institution', '制度', '制度を確認します。', 'I confirm the institution.', '我确认制度。'),
  ('ko-topik-advanced-63', 'ko', 'advanced', 'TOPIK', '제도', '제도', 'jedo', 'institution', '制度', '제도을 확인합니다.', 'I confirm the institution.', '我确认制度。'),
  ('ja-jlpt-advanced-64', 'ja', 'advanced', 'JLPT', '法律', 'ほうりつ', 'horitsu', 'law', '法律', '法律を確認します。', 'I confirm the law.', '我确认法律。'),
  ('ko-topik-advanced-64', 'ko', 'advanced', 'TOPIK', '법률', '법률', 'beomnyul', 'law', '法律', '법률을 확인합니다.', 'I confirm the law.', '我确认法律。'),
  ('ja-jlpt-advanced-65', 'ja', 'advanced', 'JLPT', '権利', 'けんり', 'kenri', 'right', '权利', '権利を確認します。', 'I confirm the right.', '我确认权利。'),
  ('ko-topik-advanced-65', 'ko', 'advanced', 'TOPIK', '권리', '권리', 'gwolli', 'right', '权利', '권리을 확인합니다.', 'I confirm the right.', '我确认权利。'),
  ('ja-jlpt-advanced-66', 'ja', 'advanced', 'JLPT', '責任', 'せきにん', 'sekinin', 'responsibility', '责任', '責任を確認します。', 'I confirm the responsibility.', '我确认责任。'),
  ('ko-topik-advanced-66', 'ko', 'advanced', 'TOPIK', '책임', '책임', 'chaegim', 'responsibility', '责任', '책임을 확인합니다.', 'I confirm the responsibility.', '我确认责任。'),
  ('ja-jlpt-advanced-67', 'ja', 'advanced', 'JLPT', '交流', 'こうりゅう', 'koryu', 'exchange', '交流', '交流を確認します。', 'I confirm the exchange.', '我确认交流。'),
  ('ko-topik-advanced-67', 'ko', 'advanced', 'TOPIK', '교류', '교류', 'gyoryu', 'exchange', '交流', '교류을 확인합니다.', 'I confirm the exchange.', '我确认交流。'),
  ('ja-jlpt-advanced-68', 'ja', 'advanced', 'JLPT', '協力', 'きょうりょく', 'kyoryoku', 'cooperation', '合作', '協力を確認します。', 'I confirm the cooperation.', '我确认合作。'),
  ('ko-topik-advanced-68', 'ko', 'advanced', 'TOPIK', '협력', '협력', 'hyeomnyeok', 'cooperation', '合作', '협력을 확인합니다.', 'I confirm the cooperation.', '我确认合作。'),
  ('ja-jlpt-advanced-69', 'ja', 'advanced', 'JLPT', '競争', 'きょうそう', 'kyoso', 'competition', '竞争', '競争を確認します。', 'I confirm the competition.', '我确认竞争。'),
  ('ko-topik-advanced-69', 'ko', 'advanced', 'TOPIK', '경쟁', '경쟁', 'gyeongjaeng', 'competition', '竞争', '경쟁을 확인합니다.', 'I confirm the competition.', '我确认竞争。'),
  ('ja-jlpt-advanced-70', 'ja', 'advanced', 'JLPT', '解決', 'かいけつ', 'kaiketsu', 'solution', '解决', '解決を確認します。', 'I confirm the solution.', '我确认解决。'),
  ('ko-topik-advanced-70', 'ko', 'advanced', 'TOPIK', '해결', '해결', 'haegyeol', 'solution', '解决', '해결을 확인합니다.', 'I confirm the solution.', '我确认解决。'),
  ('ja-jlpt-advanced-71', 'ja', 'advanced', 'JLPT', '提案', 'ていあん', 'teian', 'proposal', '提案', '提案を確認します。', 'I confirm the proposal.', '我确认提案。'),
  ('ko-topik-advanced-71', 'ko', 'advanced', 'TOPIK', '제안', '제안', 'jean', 'proposal', '提案', '제안을 확인합니다.', 'I confirm the proposal.', '我确认提案。'),
  ('ja-jlpt-advanced-72', 'ja', 'advanced', 'JLPT', '実現', 'じつげん', 'jitsugen', 'realization', '实现', '実現を確認します。', 'I confirm the realization.', '我确认实现。'),
  ('ko-topik-advanced-72', 'ko', 'advanced', 'TOPIK', '실현', '실현', 'silhyeon', 'realization', '实现', '실현을 확인합니다.', 'I confirm the realization.', '我确认实现。'),
  ('ja-jlpt-advanced-73', 'ja', 'advanced', 'JLPT', '適用', 'てきよう', 'tekiyo', 'application', '应用', '適用を確認します。', 'I confirm the application.', '我确认应用。'),
  ('ko-topik-advanced-73', 'ko', 'advanced', 'TOPIK', '적용', '적용', 'jeogyong', 'application', '应用', '적용을 확인합니다.', 'I confirm the application.', '我确认应用。'),
  ('ja-jlpt-advanced-74', 'ja', 'advanced', 'JLPT', '限界', 'げんかい', 'genkai', 'limit', '界限', '限界を確認します。', 'I confirm the limit.', '我确认界限。'),
  ('ko-topik-advanced-74', 'ko', 'advanced', 'TOPIK', '한계', '한계', 'hangye', 'limit', '界限', '한계을 확인합니다.', 'I confirm the limit.', '我确认界限。'),
  ('ja-jlpt-advanced-75', 'ja', 'advanced', 'JLPT', '展望', 'てんぼう', 'tenbo', 'outlook', '展望', '展望を確認します。', 'I confirm the outlook.', '我确认展望。'),
  ('ko-topik-advanced-75', 'ko', 'advanced', 'TOPIK', '전망', '전망', 'jeonmang', 'outlook', '展望', '전망을 확인합니다.', 'I confirm the outlook.', '我确认展望。')
on conflict (id) do update set
  target_language = excluded.target_language,
  level = excluded.level,
  topic = excluded.topic,
  target_text = excluded.target_text,
  reading = excluded.reading,
  romanization = excluded.romanization,
  meaning_en = excluded.meaning_en,
  meaning_zh_cn = excluded.meaning_zh_cn,
  example_text = excluded.example_text,
  example_translation_en = excluded.example_translation_en,
  example_translation_zh_cn = excluded.example_translation_zh_cn;
